### ISSUE TITLE
Required_without validation rule

### ISSUE THREAD

**Issue by chistel** [codeigniter4/CodeIgniter4#1007]
The above subject does not act as its supposed to, the only part it handles is if the rule field is not available in the request.

before the loop, at this line that has this:
$present = $this->required($data[$str] ?? null); it's should be $present = $this->required($str ?? null); since $str is more of a field in the request. 

Then in the field loop, within the array key check, it's supposed to run this way:
if(!array_key_exists($field,  $data) || (isset($data[$field]) && empty($data[$field])){
       return false:
}

pardon my no code formating, as am on mobile.

**Comment by georgeio** [comment]
I can confirm this case, is anyone working on a fix already? I can submit a PR. I also noticed a typo in the error message it reads 'The {field} field is required when {param} in not present.' I guess the "in" should have been "is".

**Comment by lonnieezell** [comment]
I haven’t had a chance to work on it yet so a PR is very welcome.

**Comment by georgeio** [comment]
@lonnieezell Ok. Something else needed my attention at work could not jump on this immediately. I have submitted a PR for the typo that was really minor, working on this issue now.

**Comment by lonnieezell** [comment]
@georgeio Did you submit the fix fo this one? I'm a bit scattered at the moment. :)

**Comment by lonnieezell** [comment]
it would be better at this point to NOT include Escaper, but not too big of a deal, I don't believe.

**Comment by jim-parry** [comment]
The original behavior, that was claimed to be bad, actually looks correct.
Further, the second part of the proposed fix seems backwards.
Nothing further on this in months, so closing.
