### ISSUE TITLE
Session expire time refresh by xhr/ajax request.

### ISSUE THREAD

**Issue by Przem4S** [codeigniter4/CodeIgniter4#1074]
When sending ajax/xhr (by jQuery), session expiration time was refreshed. 
Example ajax with interval 10 secs, refreshing cookie by method \CodeIgniter\Session\Session->setCookie.
More in topic on forum: https://forum.codeigniter.com/thread-70895.html

**Comment by puschie286** [comment]
i think its not a bug - just the default behavior of CI for "normal" request

we have the \CodeIgniter\API\ResponseTrait for stuff like that
( you still need to handle your session correctly )

@jim-parry maybe we should add a notice to the doc

**Comment by puschie286** [comment]
I don't think its a bug - just the default behavior of CI.

as you cant detect reliable if a request is ajax or not, you need to manage this by yourself
just add a "session_write_close()" to ajax response scripts and CI will stop updating your session cookie
