### ISSUE TITLE
The _remap function is wrong in the development （CI_DEBUG）

### ISSUE THREAD

**Issue by 35598253** [codeigniter4/CodeIgniter4#1137]
test.php
 public function _remap($method)
    {
           $this->list($method);
    }

 protected function list(string $name) {
print_r($name)
}

in the development （CI_DEBUG）
url
localhost/index.php/test/tianjian 

is wrong
Tips：
Method APP\Controllers\test::tianjia() does not exist
system\Debug\Toolbar\Collectors\Routes.php at line 88	
...................................................................................................................................
define('CI_DEBUG',0);

OK!

**Comment by jim-parry** [comment]
Not a clue what this is trying to say, and no further details in 3 months.
