### ISSUE TITLE
SubQueries (tables from outside of the current model)

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1175]
In one of my models I am trying to pass subquery (another table) to final query i.e.

```
$subQuery = $this->setTable('a')->select('usr_id')->where...->getCompiledSelect();
$this->db->resetSelect();
$this->setTable('b') //models table
->whereIn('b_usr_id', $subQuery, false)
->get();
```

but instead of 
```
SELECT * FROM b WHERE b_usr_id IN (SELECT usr_id FROM a WHERE ...)
```
CI returns:
```
SELECT * FROM a WHERE b_usr_id IN (SELECT usr_id\n FROM a\n WHERE ...)
```
(wrong table , additional EOLs)

It looks like we should add to BaseBuilder::resetSelect()  'QBFrom` to resetRun call. I think we should do the same with reset write. Am I right?

I saw there is also  $overwrite option
``` BaseBuilder::from($from, $overwrite = false)```
but shuldn't resetSelect clear  QBFrom as well?

**Comment by natanfelles** [comment]
@nowackipawel What happens if you change this `$this->db->resetSelect();` for this `$this->resetSelect();`?

**Comment by natanfelles** [comment]
Before go to the code, my first suspect is that it is not using the same BaseBuilder instance.
That's why I asked. Probably I am wrong.

**Comment by lonnieezell** [comment]
If you need to access another table from within a model, it's better just to use the db's `table()` method to get a new builder instance. That keeps the queries separated, which is why that exists now. I got tired of queries leaking onto each other in past versions :)

```
$this->db->table('b')
->whereIn('b_usr_id', $subQuery, false)
->get()
```
