### ISSUE TITLE
Problem with Database BaseBuilder binds

### ISSUE THREAD

**Issue by Martin-4Spaces** [codeigniter4/CodeIgniter4#1226]
Imagine this query.
```
$model = new UserModel();
$user = $model
        ->where('id', 2)
        ->orWhereIn('id', [3, 4])
        ->find(); 
```

`where('id', 2)` will generate a bind in BaseBuilder with key _id_.
`orWhereIn('id', [3, 4])` will do the same. 

We will end up with one bind, when we should have two.
The final query will end up like this

```
SELECT *
FROM `users`
WHERE `users`.`id` = (3,4)
OR `users`.`id` IN (3,4)
```

I see that you have already tried to deal with this issue by adding a setBind-method in BaseBuilder. But whereIn() does not use this method. I've tried replacing
`$this->binds[$ok] = $where_in;`
With
`$this->setBind($ok, $where_in);`
But this does not solve the problem. I still end up with a query like this

```
SELECT * 
FROM `users` 
WHERE `users`.`id` = 2 
OR `users`.`id` IN 2
```

Unfortunately I do not have more time to look at this. I hope someone else with take a look :-)

**Comment by FaaaX** [comment]
I found a fix anyway. Look at this.
<img width="848" alt="4spacesdarktemplar____phpstormprojects_4spacesdarktemplar__-_____system_database_basebuilder_php__4spacesdarktemplar_" src="https://user-images.githubusercontent.com/9819124/45717481-6cd42400-bb9a-11e8-8277-c352e2c82e99.png">

**Comment by Tada5hi** [comment]
having the same issue. Your solution fixed mine as well

**Comment by lonnieezell** [comment]
Will have to dig a little deeper when I have a little more time, but that's not a perfect fix. It needs to be fixed in the setBind method, since that helps to ensure that name collisions don't happen, etc.
