### ISSUE TITLE
TODO Database BaseConnection needs better connections

### ISSUE THREAD

**Issue by jim-parry** [codeigniter4/CodeIgniter4#1253]
Database/BaseConnection::getConnection has a todo note...
work with read/write connections

**Comment by MGatner** [comment]
Here's the relevant code:
```
	/**
	 * Returns the actual connection object. If both a 'read' and 'write'
	 * connection has been specified, you can pass either term in to
	 * get that connection. If you pass either alias in and only a single
	 * connection is present, it must return the sole connection.
	 *
	 * @param string|null $alias
	 *
	 * @return mixed
	 */
	public function getConnection(string $alias = null)
	{
		//@todo work with read/write connections
		return $this->connID;
	}
```

I'm honestly not sure what that means. I guess some drivers support multiple simultaneous connections with different permissions, so I could do something like this?
```
$readOnly = $db->getConnection('read');
```

@lonnieezell may need to clarify if this is still desirable and what exactly it should do.

**Comment by lonnieezell** [comment]
Oh, my intent was to at some point be able to define different database connections for read queries than you would use for write queries. This would assist in higher volume sites that use the master/slave setup.

**Comment by MGatner** [comment]
Got it! Yeah I think that's actually pretty slick, so the framework would handle the database routing and you could write code as though it were a single database. I think this is definitely worth keeping, but might require deeper changes.

**Comment by lonnieezell** [comment]
Yeah, I never figured it would be simple :)

**Comment by element-code** [comment]
When designing this, please keep in mind that for some read operations, you want to force the framework to use the "master" as read source, e.g. when calculating aggregate data and writing it back to the "master" periodically :)

**Comment by MGatner** [comment]
@element-code You seem to be knowledgeable in this area! Would you care to take a first pass at implementing this for a Pull Request?

**Comment by xbotkaj** [comment]
We use such system in DHL. For master - slave configuration. Here I would say we need method in builder to switch between databases. Replicated database is usually synced with master in some time interval.You want to read/write to master but you want to read from slave e.g. for reports that aggregates huge ammount of data so it will not slow down performance on master where you need imidiate actions read or write. Simply put we need just selector of database so yo can tell CI which DB you want to use to execute.

**Comment by lonnieezell** [comment]
Since this isn't a bug or other issue, and is just waiting for someone to implement it, I'm closing this.
