### ISSUE TITLE
SQLLite3 Forge needs better column handling

### ISSUE THREAD

**Issue by jim-parry** [codeigniter4/CodeIgniter4#1255]
Database/SQLite3/Forge::_alterTable(...) has a todo note...
implement drop_column(), modify_column()

**Comment by lonnieezell** [comment]
So - this looks to be a giant pain in the ass. SQlite3 does not support drop column or modify column. You have to go through a bunch of steps including creating a new table with the dropped column and then renaming the column.

While it would still be good to implement, definitely not happening for 4.0 initial release. 

http://www.sqlitetutorial.net/sqlite-alter-table/

**Comment by lonnieezell** [comment]
Fixed in #1737
