### ISSUE TITLE
Deallocate prepared statements

### ISSUE THREAD

**Issue by jim-parry** [codeigniter4/CodeIgniter4#1256]
Database/SQLite3/PreparedQuery::_execute(..) has todo note...
finalize()

**Comment by lonnieezell** [comment]
Looks like a common method needs implemented for all of our db libs to destroy the prepared query when we're done with it. SqLite has [finalize](https://sqlite.org/c3ref/finalize.html), MySQL has [deallocate](https://dev.mysql.com/doc/refman/5.7/en/deallocate-prepare.html) and Postgres doesn't appear to have anything.

**Comment by kenjis** [comment]
Closed by #6665
