### ISSUE TITLE
[Re-opened] 404 File not found when running CodeIgniter on local Apache web server and virtual hosts

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1400]
Sorry, but there were indeed typos in the previous bug report (which is closed now) that have been corrected by this post.

I am running locally an Apache web server and use virtual hosts (example name: CodeIgniter4.test). The document root is set to /CodeIgniter4/public. The base URL in App.php is therefore set to:

http://CodeIgniter4.test/

A controller "Standard" is defined and in Routes.php the following default settings exist:
$routes->setDefaultController('Standard'); $routes->setDefaultMethod('index'); 
There are no route definitions!

Trying to call http://CodeIgniter4.test in a browser leads to 404 File not found error which is not correct.

The reason for the error can be found in the validateRequest method of class Router: the parameter $segments contains in this case two string elements of size zero (empty strings). The reason is that autoRoute is called with the URI '/'.
Line 578 of Router.php reads:
if ( ! file_exists(APPPATH . 'Controllers/' . $test . '.php') && $directory_override === false && is_dir(APPPATH . 'Controllers/' . $this->directory . ucfirst($segments[0])) 
where $directory_override is false and $this->directory and $test are initially empty.

This means that for the first test is_dir(APPPATH . 'Controllers/' . $this->directory . ucfirst($segments[0]) is true and the directory is set to '/'.
Unfortunately, it seems to be that the same test is also true when $this->directory has the value '/'. In this case the parameter of is_dir is something like APPPATH.'Controllers//' and still is_dir returns true (I am using PHP 7.1.19).

So, finally $this->directory contains '//', which is of course not correct. This means that the controller's name is "App\Controllers\\\Standard". And a file relating to this controller does not exist and hence the 404 File not found exception is thrown.

PS: I am using CodeIgniter 4 version Alpha2, PHP 7.1.19.
PPS: This bug exists whenever the internally used variable $uri begins and/or ends with a '/'.

**Comment by jim-parry** [comment]
I added to tests/system/Router/RouterTest what I think to be a unit testcase following your description...

	public function testAlmostEmptyURIMatchesDefaults()
	{
		$router = new Router($this->collection);

		$router->handle('/');

		$this->assertEquals($this->collection->getDefaultController(), $router->controllerName());
		$this->assertEquals($this->collection->getDefaultMethod(), $router->methodName());
	}

It passes. What am I missing?

**Comment by hwiesmann** [comment]
Hi,

this test will also pass in my case but:

The default setting in Config/Routes.php is
`$routes->setDefaultNamespace('App\Controllers');`
(see repository).

So, when I modify the test to:
        public function testAlmostEmptyURIMatchesDefaults()
	{
		$this->collection->setDefaultNameSpace('App\Controllers');
		$router = new Router($this->collection);

		$router->handle('/');

		$this->assertEquals($this->collection->getDefaultController(), $router->controllerName());
		$this->assertEquals($this->collection->getDefaultMethod(),     $router->methodName());
	}

I get the result 

> 1) CodeIgniter\Router\RouterTest::testAlmostEmptyURIMatchesDefaults
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Home'
+'App\Controllers\\\Home'

Perhaps the default setting in Config/Routes.php confused me (or CodeIgniter 4?).

**Comment by InsiteFX** [comment]
The document root should be set to the root directory where you installed CodeIgniter 4 not the public folder. You map the public folder.

I use vhosts also.

**Comment by jim-parry** [comment]
@InsiteFX Hmm - I understand "document root" to *be* the mapping, i.e. pointing at the public folder within the "project root". In the above, document root should refer to the DocumentRoot directive inside the virtual hosting element, no? That points at the front ontroller path, i.e. the public folder.
I don't understand your statement :(

**Comment by InsiteFX** [comment]
Hi Jim, yes in the vhost the public_html is the document root. But in phpStorm the root is were you installed CodeIgniter, but it will not see the index.php until I map it in phpStorm to the public_html folder.

`#--------------------------------------------------------------
# HTTPS:
#--------------------------------------------------------------
<VirtualHost *:443>
	DocumentRoot "C:/xampp/htdocs/ci3news/public_html"
	ServerName ci3news.local
	ServerAlias ci3news.local
	SSLEngine on
	SSLCertificateFile "conf/ssl.crt/server.crt"
	SSLCertificateKeyFile "conf/ssl.key/server.key"
	<Directory "C:/xampp/htdocs/ci3news/public_html">
		Options All
		AllowOverride All
		Require all granted
	</Directory>
</VirtualHost>
`

**Comment by jim-parry** [comment]
@InsiteFX Phew - we do mean the same thing then :)
 But we still seem to have CI misbehaving :(

**Comment by InsiteFX** [comment]
Hi Jim,
If they are on a windows system then they need to do the following:

1) edit this with notepad logged in as Administrator.

C:\Windows\System32\drivers\etc\hosts

Make sure that these are not remarked out

127.0.0.1	localhost
::1		localhost

also for vhosts I set the local up like this:

127.0.0.1	cms.local

**Comment by jim-parry** [comment]
@InsiteFX Agreed - that would be easier, setting up a domain alias for their CI VM.
It will be in the writeup I am putting together, thanks.

**Comment by atishamte** [comment]
At the time of defining the virtual host, include public folder in the directory. So there is no need to mention public folder in htaccess file.
I have tried the same on windows, linux and mac with XAMPP and it works like a charm...:)

**Comment by atishamte** [comment]
Is this still open?

**Comment by InsiteFX** [comment]
Jim,
I' am on Windows 10 Pro using XAMPP with VHOSTS and have no problems.

`#--------------------------------------------------------------
# CodeIgniter 4 Testing
#--------------------------------------------------------------

#--------------------------------------------------------------
# Testing CI 4.0 Dev
#--------------------------------------------------------------
<VirtualHost *:80>
    DocumentRoot "\xampp\htdocs\ci4\public_html"
    ServerName ci4.local
    ServerAlias ci4.local
    <Directory "\xampp\htdocs\ci4\public_html">
        Order allow,deny
        Allow from all
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:443>
	DocumentRoot "\xampp\htdocs\ci4\public_html"
    ServerName ci4.local
    ServerAlias ci4.local
    SSLEngine on
    SSLCertificateFile "conf/ssl.crt/server.crt"
    SSLCertificateKeyFile "conf/ssl.key/server.key"
    <Directory "\xampp\htdocs\ci4\public_html">
        Options All
		AllowOverride All
		Require all granted
    </Directory>
</VirtualHost>

#--------------------------------------------------------------
`

**Comment by atishamte** [comment]
I also commented 11 days ago regarding not facing any issue on any of the OS(mac mojave, ubuntu 18.04 and Windows 10 Pro)

**Comment by jim-parry** [comment]
It sounds like this one is fixed :)
