### ISSUE TITLE
Language is not merging with modules

### ISSUE THREAD

**Issue by natanfelles** [codeigniter4/CodeIgniter4#1433]
**Describe the bug**

When a Language file with same *name* of an default file of the *system/Language/en/* is in a module folder, it is not merged.

For example:

I have the following folder structure:

```
application/
module-x/
module-x/Commands/
module-x/Language/en/
```

The namespace is proper configured in the Autoload config. I can see the commands when I call the `spark`.

And the `lang()` function also works - BUT, if a module lang file has the same name of a default file, it does not works.

If a file is named *Foo.php*, it works: `lang('Foo.hello')`.

If a file is named *HTTP.php*, it does not works: `lang('HTTP.hello')`.

Same for others, like *Database.php*, etc.

**CodeIgniter 4 version**

4.0.0-alpha.2

**Affected module(s)**

Language

**Expected behavior, and steps to reproduce if appropriate**

Expected that module Language files be merged.  

**Context**
 - OS: [Debian]
 - Web server [PHP]
 - PHP version [7.2]

**Comment by jim-parry** [comment]
We are aware of this ... see #1262.
There is also the issue of falling back to parent language ("en") if dialect language ("en-CA") is missing a key.
Further testing & refinement are underway :-/

**Comment by natanfelles** [comment]
Hi, @jim-parry !

I think is not related.

Some time ago I also see that is necessary a fallback and would open an issue, but I found open.

This issue is about files with same name. For some reason it is not merged. It is working just if the filename already is not in use.

I wanted to use the filename *Database.php*, but does not works. When updated to *DB.php* works.

[This an example](https://github.com/natanfelles/codeigniter-db/blob/806dbdd669a33aa69eb3141fe7408446f8378e75/src/Commands/Create.php#L28)

**Comment by jim-parry** [comment]
They are related in that the expected order of language file loading is not observed.
I am finding a few anomalies between the behaviour described in the user guide and that evident from the code and unit testing :-/
The problem is likely to be made worse with composer-installing the translations.
A few things to fix here, and they can be done one at a time or all at once :)
