### ISSUE TITLE
WIP Vagrant and/or Docker support

### ISSUE THREAD

**Issue by natanfelles** [codeigniter4/CodeIgniter4#1452]
**Direction**

Maybe a Vagrantfile or a Dockerfile, or both, in the development repo be a good idea.

**Describe the bug**

Difficulty to do local tests before to push online.

**Comment by natanfelles** [comment]
@bvrignaud @deathart @kenjis  - I see that you use it, guys. I'm a newbie.

**Comment by jim-parry** [comment]
You can always use virtualbox, & install a suitable flavor of linux in it.
Using vagrant, they have a centos/7 box that I have had my students play with.
Or ... you could take a leap of faith & upgrade from Windows or OSX :D

bitnami also has a VM image for LAMPP ... https://bitnami.com/stack/lamp/virtual-machine

**Comment by jim-parry** [comment]
It could make more sense to do these as separate repos inside codeigniter4 organization. A vagrantbox could be several GB big; not sure of the size of a docker container.

**Comment by Paradinight** [comment]
@natanfelles I am using the laravel/homestead 

It work with codeigniter too

**Comment by natanfelles** [comment]
@jim-parry your students could help with it.

**Comment by bvrignaud** [comment]
This is 

> @bvrignaud @deathart @kenjis - I see that you use it, guys. I'm a newbie.
Yes. I use docker for most of my developements.
Do you want my docker and docker-compose files ?

**Comment by natanfelles** [comment]
If CI Team accept to add it, and you want to share, or create the files according with CodeIgniter requirements, yes! :smiley: 

With all php extensions, mysql, postgres, redis, etc, ready to run in a CodeIgniter test environment.

**Comment by deathart** [comment]
Look at my repository I added docker (php configure and nginx) 

https://github.com/deathart/BlogCI4

https://github.com/deathart/BlogCI4/tree/master/docker

https://github.com/deathart/BlogCI4/blob/master/docker-compose.yml

**Comment by bangbangda** [comment]
you system is Mac OS? I use valet, so easily.
copy [driver file](https://github.com/bangbangda/CodeIgniter4-valet-driver/blob/master/CodeIgniter4ValetDriver.php) is  ok.
@natanfelles

**Comment by jim-parry** [comment]
I am already planning an expanded "installation" page or pages in the user guide. Would it make sense to start by describing the different ways to install/run CI4 there, and then to add config files as appropriate?
