### ISSUE TITLE
no $baseURL set will be error 500

### ISSUE THREAD

**Issue by yangyunzhi** [codeigniter4/CodeIgniter4#1476]
my code 
--------
#File:App.php
public $baseURL = '';
---------
it's will be notice 
---
You have an empty or invalid base URL. The baseURL value must be set in Config\App.php, or through the .env file.
---
So, I modified the page IncomingRequest.php ,Let it automatically get $baseURL.
-------------
#File:IncomingRequest.php
#Function detectURI()
#Add Codes in 576line 

// baseURL, so let's help them out.
if(empty($baseURL)){
            $httpType = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ||
                (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')) ? 'https://' : 'http://';
            $baseURL = $httpType . (isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : $_SERVER['SERVER_NAME']);
        }
-------------
It's Ok , hahaha

**Comment by jim-parry** [comment]
We do not recommend changing any of the system files (IncomingRequest) in your webapps.
If you think this is something worthy, propose it as a feature (on the forum) or submit a PR for it (here).

The comment for $baseURL inside Config.App already says that CodeIgniter will try to guess this.

You say you get an error 500 ... can you elaborate? Do your error logs shed any loght on things? Is this for every page? What is your configuration?
--------
Turn off the bolding before doing anything - it hurts the eyes and does serve a useful purpose! :-/

**Comment by lonnieezell** [comment]
A lot of people will modify the base script to do that automatically, I'm sure. However, we've chosen to force the user to set that for security reasons. That way all URLs that are built with our URL helpers will only use a known value. Eliminates any possibilities of client interference with the URL.
