### ISSUE TITLE
Issues with redirects - had to use exit to make it work and blank page 

### ISSUE THREAD

**Issue by daljit3** [codeigniter4/CodeIgniter4#1501]
---
name: Bug report
about: Help us improve the framework by reporting bugs!

---
**Describe the bug**
There are two issues with the `redirect()` method.
1) I am not able to use `return redirect()->to('/');` so I have to follow it up with an exit to make it work. e.g. 
```
public function hello() {
//this won't work;
return redirect()->to('/');
//this works
redirect()->to('/');
exit;
}
```
2) The other issue is none of the redirects are working now since approximately after yesterday (17 nov 2018) evening. To make sure, I haven't accidently broken it, I just downloaded a new copy of CI4-develop and after setup I could see welcome message to confirm everything working fine. Then I made these modifications below to the Home controller. If I try `mylocalsite/home/daljit` it just shows a blank page.
```
 namespace App\Controllers;

use CodeIgniter\Controller;

class Home extends Controller
{
	public function index()
	{
		return view('welcome_message');
	}

	//--------------------------------------------------------------------
    public function daljit()
    {
        return redirect()->to("/home/hello");
    }

    public function hello()
    {
        echo "Hello!";
    }
}
```
 
**CodeIgniter 4 version**
CodeIgniter 4 develop branch.

**Comment by jim-parry** [comment]
Ok, the oldInput changes have been reverted, and the unit tests show that bug.
They do not show any redirect() problems.
@daljit3 Can you confirm that redirect works again, and that the old() bug is back?

**Comment by jim-parry** [comment]
Hmm - after setting the baseURL & indexPage properties in App, I get a blank page even for .../home,
although the default home apge continues to work. This may not be a redirect problem at all, but something deeper.
I have looked at the commits over the last week, and don't see what would cause this.
daljit3, when did you last pull the develop branch from the repo, before the most recent one that seems to be problematic?

**Comment by daljit3** [comment]
@jim-parry - no sorry redirect still doesn't work and I kind of rely on redirects to get to edit form page to do the testing for old(). Just for clarification, I updated my local copy again just now. 

Also, I seem to have found another issue which wasn't there before but I need to investigate more what this new issue is and why I am getting this exception all of sudden as yesterday it was working. Could it be linked to that redirect issue?

```
CodeIgniter\HTTP\Exceptions\HTTPException 
BASEPATH/HTTP\Exceptions\HTTPException.php at line 106
``

> daljit3, when did you last pull the develop branch from the repo, before the most recent one that seems to be problematic?

I actually update my local copy everyday using git pull and everything except old() bug worked fine. 

I can confirm that this issue only started after I did git pull today after seeing your comment that it;s fixed.
I am lucky that I uploaded yesterday's code to our server and went live. I just checked and redirects work fine on my live site.

**Comment by jim-parry** [comment]
Very strange.
Now you are getting an exception isnide of the Exception class?
And whatever happened occurred over the last 24-26 hours.
Digging further here too.

**Comment by daljit3** [comment]
Very strange indeed. The reason I am so sure about that it stopped working today is, as I mentioned above, that I published my local site yesterday. My server copy isn't synced to my local as I manually ftp the changes as of now.

**Comment by jim-parry** [comment]
@daljit3 I think this should solve both the redirect problem here, as well as the original old() issue.
If you could test, it would be appreciated.

**Comment by natanfelles** [comment]
@daljit3 When you call the `listErrors()` a view is loaded.

You can check if has errors with `getErrors()` before to load the view.

**Comment by jim-parry** [comment]
The redirect issue was caused by my dropping the sendHeaders(), to address a different bug :-/
Solved one but caused another :(

**Comment by jim-parry** [comment]
Solution confirmed

**Comment by daljit3** [comment]
@jim-parry hi - it seems like redirects are ending on blank again!! Just updated my local copy today.

**Comment by jim-parry** [comment]
You update daily, so they were working yesterday and now not today?

**Comment by daljit3** [comment]
I was working on a different project so I hadn't updated for the past couple of days. I just did and it went blank.

**Comment by jim-parry** [comment]
i'm trying to isolate "when" this broke. so, sometime in the last couple of days...

**Comment by jim-parry** [comment]
I am looking at #1504, #1505 or #1513 as causing the problem

**Comment by daljit3** [comment]
Okay - if you want me to do any quick tests - I am available here for another hour and half. Please let me know.

**Comment by jim-parry** [comment]
The biggest help would be a unit test case that fails when it shouldn't. It is obvious to me that the ones we have now are missing the boat - they are not catching the problem, even I thought we caught it last week. There could be several things happening here.
I believe the relevant tests are in CommonFunctionTest.
Thanks!

**Comment by daljit3** [comment]
I'll look and see if I know how to set that up on my local. 

The exception error is back too! :(

**Comment by daljit3** [comment]
I just ran php unit test and I get 105 failures but if I tried vendor\bin\phpunit --filter CommonFunctionTest I get "No code coverage driver is available". I might not have got it config properly?

**Comment by jim-parry** [comment]
to run just the one test, vendor/bin/phpunit tests/system/CommonFunctionsTest.php

**Comment by natanfelles** [comment]
@daljit3 Please, check if you have the PHP `display_error` active. And if your \Config\App::baseURL has the scheme (http or https), otherwise it ends in a blank page.

**Comment by daljit3** [comment]
@lonnieezell @natanfelles  @jim-parry 
Yes I do have "http" in my .env, `app.baseURL = 'http://mylocalsite.dev/'`

I think I have found what's causing issue for me.

As mentioned before, `return redirect()->to('/');` never worked for me before @jim-parry made some changes the other day. However, I still some places where I have
```
redirect('/user-home');
exit;
```
To fix this issue, I have to replace with `return redirect()->to('/user-home');`

The bizzare thing is that both option worked for me with after @jim-parry fix and it only stopped since I raised this once again.

Here's my quick and dirty test with results on a fresh installation today at 09:30 AM 23/11/2018.
```
class Home extends Controller
{
	public function index()
	{
        echo "<h2>Hello there!</h2>";
        echo "<ol>";
        echo "<li><a href='/home/test1' target='_blank'>Go to Test 1</a></li>";
        echo "<li><a href='/home/test2' target='_blank'>Go to Test 2</a></li>";
        echo "<li><a href='/home/test3' target='_blank'>Go to Test 3</a></li>";
        echo "<li><a href='/home/test4' target='_blank'>Go to Test 4</a></li>";
        echo "<li><a href='/home/test5' target='_blank'>Go to Test 5</a></li>";
        echo "</ol>";
	}

    public function test1()
    {
        redirect("/home/login");
        exit;

        //Fails with this error
        /*
            CRITICAL - 2018-11-23 03:23:38 -->
            #0 C:\xampp-7.2.2\htdocs\myproject\system\HTTP\RedirectResponse.php(86): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
            #1 C:\xampp-7.2.2\htdocs\myproject\system\Common.php(821): CodeIgniter\HTTP\RedirectResponse->route(false)
            #2 C:\xampp-7.2.2\htdocs\myproject\application\Controllers\Home.php(18): redirect('/home/login')
            #3 C:\xampp-7.2.2\htdocs\myproject\system\CodeIgniter.php(825): App\Controllers\Home->test1()
            #4 C:\xampp-7.2.2\htdocs\myproject\system\CodeIgniter.php(325): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
            #5 C:\xampp-7.2.2\htdocs\myproject\system\CodeIgniter.php(235): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
            #6 C:\xampp-7.2.2\htdocs\myproject\public\index.php(45): CodeIgniter\CodeIgniter->run()
            #7 {main}
                 * */
    }
    public function test2() {
        // This test works OK for me
        return redirect()->to("/home/login");
    }
    public function test3() {
        // This test works OK for me
        return redirect()->to("/home/login/?referer=test2");
    }
    public function test4() {
        $refUrl = currentUrlWithQueryString();
        $redirect_to_url = '/home/login/?ref='.$refUrl;

        redirect($redirect_to_url);
        exit;

        /* Failes with this error below

        CRITICAL - 2018-11-23 03:39:20 -->
        #0 C:\xampp-7.2.2\htdocs\myproject\system\HTTP\RedirectResponse.php(86): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
        #1 C:\xampp-7.2.2\htdocs\myproject\system\Common.php(821): CodeIgniter\HTTP\RedirectResponse->route(false)
        #2 C:\xampp-7.2.2\htdocs\myproject\application\Controllers\Home.php(52): redirect('/home/login/?re...')
        #3 C:\xampp-7.2.2\htdocs\myproject\system\CodeIgniter.php(825): App\Controllers\Home->test4()
        #4 C:\xampp-7.2.2\htdocs\myproject\system\CodeIgniter.php(325): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
        #5 C:\xampp-7.2.2\htdocs\myproject\system\CodeIgniter.php(235): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
        #6 C:\xampp-7.2.2\htdocs\myproject\public\index.php(45): CodeIgniter\CodeIgniter->run()
        #7 {main}
        */
    }
    public function test5() {
	    // This test works OK for me
        $refUrl = currentUrlWithQueryString();
        $redirect_to_url = '/home/login/?ref='.$refUrl;

        redirect()->to($redirect_to_url);
        exit;
    }

    public function login() {
        echo "<h2>Welcome to our Login page! :) </h2>";
        echo "<ol>";
        echo "<li><a href='/home'>Go to Home</a></li>";
        echo "</ol>";

    }
}

///---------------- Some helpers -----------------------------------//

function currentUrlWithQueryString($includeBaseUrl=false) {

    $uri = $_SERVER['REQUEST_URI'];
    if($includeBaseUrl == true) {
        $uri = base_url($uri);
    }
    return $uri;
}

```

**Comment by InsiteFX** [comment]
You can no longer use .dev for localhost use .local

These changes were made in chrome and other web browsers.

**Comment by daljit3** [comment]
@InsiteFX yes I am aware of that and that's not the issue.

**Comment by lonnieezell** [comment]
Ah, ok, I see what's going on and looks like docs will take care of most of it. Suggestions after the break: 

1. The redirect() method is built to have the response returned. That is the proper use. So times when you redirect() then exit will never send the actual redirect headers. A blank page is what you should see here. 
2. redirect($url) uses the [reverse routing](https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#reverse-routing) rules to determine the route to go to. You're getting an exception because it's unable to find a route name and/or controller to route to as per the reverse routing needs. That could be cleaned up to provide a better experience. They are there as the default to help with one of the elements that used to be on OWASP's Top 10 list - [Unvalidated Redirects and Forwards](https://www.owasp.org/index.php/Top_10_2013-A10-Unvalidated_Redirects_and_Forwards). 

Here's what I see is needed to fix this up:

1. Update [redirect() docs](https://codeigniter4.github.io/CodeIgniter4/general/common_functions.html?highlight=redirect#redirect) to specify that it's using reverse routing rules (and why) 
2. Potentially provide additional details on the [URI Routing page](https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html)
3. Look into providing a cleaner, more descriptive error when no matched routing rule exists.

**Comment by daljit3** [comment]
@lonnieezell yes that makes sense however please take a look at this test below ...

It doesn't redirect and just displays the text. The other tests 1 to 5 above still seem to work OK so can't figure out what's going wrong with this one.

```
namespace App\Controllers;

use CodeIgniter\Controller;

class Home extends Controller
{
    public function test6() {
		redirectIfNotLoggedIn();
		echo "You are here because you are logged in!";
    }
   public function login() {
		echo "You must login first!";
    }
}

///---------------- Some helpers -----------------------------------//
function redirectIfNotLoggedIn($refUrl=null) {
    if($refUrl == null) {
        $refUrl = currentUrlWithQueryString();
    }
    if(isUserLoggedIn() == false) {
        return redirect()->to('/login/?ref='.$refUrl);
    }
}
function isUserLoggedIn() {
    if (session('loggedin') == true) {
        return true;
    }
    return false;
}
function currentUrlWithQueryString($includeBaseUrl=false) {
    $uri = $_SERVER['REQUEST_URI'];
    if($includeBaseUrl == true) {
        $uri = base_url($uri);
    }
    return $uri;
}
```

**Comment by natanfelles** [comment]
You must return to stop the script:

```php
   public function test6() {
		if(isUserLoggedIn() == false) {
				RETURN redirect()->to('/home/login/?ref='.$refUrl);
		}
		echo "You are here because you are logged in!";
    }
```

**Comment by natanfelles** [comment]
@daljit3 [See Lonnie's comment](https://github.com/codeigniter4/CodeIgniter4/issues/1501#issuecomment-441788883)

**Comment by daljit3** [comment]
@natanfelles Sorry if I wasn't clear but are you referring to @lonnieezell on my old method of using redirect/exit? I have all the redirects now with the returns.

I am trying to understand why the below isn't redirecting. I am returning in the `redirectifnotloggedin();`

```
    public function test6() {
		redirectIfNotLoggedIn();
		echo "You are here because you are logged in!";
    }
function redirectIfNotLoggedIn($refUrl=null) {
    if($refUrl == null) {
        $refUrl = currentUrlWithQueryString();
    }
    if(isUserLoggedIn() == false) {
        return redirect()->to('/home/login/?ref='.$refUrl);
    }
}
```

**Comment by natanfelles** [comment]
To complete: You must return in the Controller method as well. Like the example I gave you.

I used only part of your functions because they do not allow it to be used consistently.

**Comment by daljit3** [comment]
I may be wrong but I am not convinced I need to return from controller too? I mean I expect the redirect to happen when user is not signed in and otherwise just continue. 

I can surely achieve that using different logic e.g. the way you suggested i.e. in the controller. However, I need to check that at various diffrent points so I would end up repeated If/Else checks throughout my project or perhaps I will end up writing my own redirect helper.
```
function my_redirect($url) {
	header("Location: $url");
	exit(0);    
} 
```

**Comment by natanfelles** [comment]
Yes. It continues, because it returns a [RedirectResponse](https://codeigniter4.github.io/CodeIgniter4/general/common_functions.html?highlight=RedirectResponse#redirect) (as the Loonie's comment explain).

It will not `exit` because if you exit, Filters, etc, are not executed. 

You could to use your custom `my_redirect()` if you want, but this will preclude some of the tasks that the framework does before finalizing the response.

**Comment by daljit3** [comment]
I just feel the correct behaviour is that it should redirect() from redirectIfNotLoggedIn() when the condition fails as it's still being called in from a controller method.

**Comment by lonnieezell** [comment]
Here's the code in question, right? 

```
public function test6() {
		redirectIfNotLoggedIn();
		echo "You are here because you are logged in!";
    }
```

While `redirectIfNotLoggedIn()` does return the RedirectResponse, nothing is ever done with that response in the `test6` method. In order for it to work, that redirectResponse that you just got from `redirectIfNotLoggedIn()` needs to be returned out of the controller, otherwise the headers are never sent to the browser. 

At this point, we're dealing with a support issue, and not a bug. If you still have questions, please take it to the forums. I'm only leaving this open to remind us that we have a few things (listed above) that we need to take care of.

**Comment by daljit3** [comment]
Yes understand. Thanks

**Comment by niteraven7** [comment]
@daljit3 Are you using "php spark serve" for local development and do you have a filter (FilterInterface) in your code? I'm going on a hunch here.

**Comment by cobafesbuk** [comment]
Hi, I'm currently migrating my old CodeIgniter code. 
I also encounter this issue today. 

The `redirect()` won't work if there's no `exit()` after it.  `return redirect()` is also not working.
Just wanted to say that it worked without `exit()` in the old CodeIgniter.

**Comment by lonnieezell** [comment]
Well - this isn’t old CodeIgniter so that parts not helpful :)

We’ve gone over and over this and I’m pretty sure it’s solid at this point. Can you provide a code sample?

If I had to take a blind guess it’s that you’re trying to redirect out of a controller constructor and that doesn’t work any longer. You should check out Controller Gilters in the docs.

**Comment by Ruudje87** [comment]
experiencing this problem too.

> I may be wrong but I am not convinced I need to return from controller too? I mean I expect the redirect to happen when user is not signed in inside redirectIfNotLoggedIn() method and otherwise just continue.
> 
> I can surely achieve that using different logic e.g. the way you suggested i.e. in the controller. However, I need to check that at various diffrent points so I would end up repeated If/Else checks throughout my project or perhaps I will end up writing my own redirect helper.
> 
> ```
> function my_redirect($url) {
> 	header("Location: $url");
> 	exit(0);    
> } 
> ```


this worked for me!

**Comment by avegacms** [comment]
> experiencing this problem too.
> 
> > I may be wrong but I am not convinced I need to return from controller too? I mean I expect the redirect to happen when user is not signed in inside redirectIfNotLoggedIn() method and otherwise just continue.
> > I can surely achieve that using different logic e.g. the way you suggested i.e. in the controller. However, I need to check that at various diffrent points so I would end up repeated If/Else checks throughout my project or perhaps I will end up writing my own redirect helper.
> > ```
> > function my_redirect($url) {
> > 	header("Location: $url");
> > 	exit(0);    
> > } 
> > ```
> 
> this worked for me!

Hi. In this case you may use Filters. See that example https://www.patreon.com/posts/visit-logging-27277581

**Comment by Ruudje87** [comment]
> > experiencing this problem too.
> > > I may be wrong but I am not convinced I need to return from controller too? I mean I expect the redirect to happen when user is not signed in inside redirectIfNotLoggedIn() method and otherwise just continue.
> > > I can surely achieve that using different logic e.g. the way you suggested i.e. in the controller. However, I need to check that at various diffrent points so I would end up repeated If/Else checks throughout my project or perhaps I will end up writing my own redirect helper.
> > > ```
> > > function my_redirect($url) {
> > > 	header("Location: $url");
> > > 	exit(0);    
> > > } 
> > > ```
> > 
> > 
> > this worked for me!
> 
> Hi. In this case you may use Filters. See that example https://www.patreon.com/posts/visit-logging-27277581

The redirect functions were not working. thats wat i needed, the filters will not do.
what i want: 

in my admin controller i use a library with some checks. it wil update my routes file and will redirect me to the admin controller again from within my library. Here the redirect->to(current_url()) is not working and it just keeps executing the code but it should redirect with a refresh to the same url. 

adding this works:
header("Location: ".current_url());
exit(0);

**Comment by MGatner** [comment]
You who are having issues still, are you remembering to return the result of `redirect()`? And also not using it in the controller constructor? If you really really can’t get it to work a better alternative to the “header...exit” code above would be to throw a RedirectException, has a slightly nicer cleanup:
https://codeigniter4.github.io/CodeIgniter4/general/errors.html#redirectexception

**Comment by pixobit** [comment]
I'm having issues with this as well int the latest version...
It seems like redirect()->to(url) doesn't do anything

**Comment by VishwasGagrani** [comment]
I am facing the same problem. Can this be an issue related to .htaccess? 

```
Options +FollowSymlinks -Indexes
RewriteEngine on

DirectoryIndex index.php
RewriteCond $1 !^(index\.php|resources|robots\.txt)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L,QSA]

```


As mentioned above, this is the only solution that works:
```
  header("Location: displayProfileView");
exit(0);   
```

**Comment by kenjis** [comment]
See https://codeigniter4.github.io/CodeIgniter4/general/common_functions.html#redirect

**Comment by samualmartin** [comment]
@daljit3 
 
 I also faced the same issue, but i was able to solve it . i belive it an  mistake in the routes file or the redirection url.
 try changing it like(removing the '/ ' before view file or  try 'home/hello'.

**Comment by jefferysafari** [comment]
> [@daljit3](https://github.com/daljit3) When you call the `listErrors()` a view is loaded.
> 
> You can check if has errors with `getErrors()` before to load the view.





https://phps.space/questions/no-instances-of-error-pages-being-displayed
