### ISSUE TITLE
[Documentation] Bug in code example for "Validating $_POST data"

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1520]
---
name: Bug report
about: Bug (misleading code) in example for "Validating $_POST data"

---
**Describe the bug**

The following code is mentioned in "Validating $_POST data":

`public function updateUser(int $userID)
{
    if (! $this->validate([
        'email' => "required|is_unique[users.email,id,{$userID}]",
        'name'  => 'required|alpha_numeric_spaces'
    ]))
    {
        return view('users/update', [
            'errors' => $this->errors
        ]);
    }

    // do something here if successful...
}`

This code gives the impression that the controller class has a variable called "$errors" but this is not the case.

A solution is to use `\Config\Services::validation()->getErrors()` instead of `$this->errors`.

PS: The same applies for the second example code in the same section!

**CodeIgniter 4 version**
CodeIgniter 4 Alpha 2

**Comment by samsonasik** [comment]
please try latest `develop` branch, I can see that it already uses `$this->validator->getErrors()` at https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/incoming/controllers.rst#validating-_post-data

**Comment by jim-parry** [comment]
Agreed, This has already been addressed.
