### ISSUE TITLE
Model events why is there no beforeFind?

### ISSUE THREAD

**Issue by bangbangda** [codeigniter4/CodeIgniter4#1527]
I want to add a where condition before all finds(find findAll first).
for example,
`$where = ['company_id' => session->get('company_id')];`
default search for company data.

beforeFind event is ok?

**Comment by lonnieezell** [comment]
I guess that's a valid use. It seems to me like there would still be situations where you would want that. Personally, I'd just add a new method in the model, `findForCompany($id)` or something. That's more explicit.

**Comment by bangbangda** [comment]
Ok. a good idea. Thank you.

**Comment by MGatner** [comment]
https://github.com/codeigniter4/CodeIgniter4/pull/3344
