### ISSUE TITLE
MYSQL : orderBy() considers CASE statement as a column

### ISSUE THREAD

**Issue by TatwiraT** [codeigniter4/CodeIgniter4#1528]
---
name: Bug report
orderBy() method considers the CASE statement as DB column
---

**Describe the bug**
the orderBy() method considers the CASE ** END statement as DB column , hence it quotes it with magic quotes.

**CodeIgniter 4 version**
CI4 Alpha 2 : commit 2047b5a 

**Affected module(s)**
DB : MySQL DRIVER

**Context**
 - OS: Arch Linux
 - Web server : Apache 3.4
 - PHP version : 7.2.9

**Comment by lonnieezell** [comment]
This can be solved by using the $escape flag on the orderBy method.
