### ISSUE TITLE
\Config\Database::connect returns unexpected result for custom config values

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1533]
---
name: Bug report
about: \Config\Database::connect returns unexpected result for custom config values

---

**Describe the bug**
I am not sure whether this is a bug in the code or if a special remark is missing in the documentation for this kind of constellation:

```
$myConfiguration1 = [...];
$myConfiguration2 = [...]; // $myConfiguration1 != $myConfiguration2
$db1 = \Config\Database::connect($myConfiguration1);
$db2 = \Config\Database::connect($myConfiguration2);
```

The astonishing result is: $db1 == $db2!

The reason for this surprise is that internally an explicit configuration gets the tag 'custom' (see Config.php connect()):

```
		if (is_array($group))
		{
			$config = $group;
			$group = 'custom';
		}
```
And as $getShared has the default value TRUE the first database is returned for the second call as well (because an instance with the key 'custom' already exists for the first connection).

If this is a bug in the code there are at least two (quick) solutions:
1) implement a counter so that $group is something like 'custom_1', 'custom_2' etc.
2) set $getShared to false to prevent returning the wrong instance (this has the consequence that only the last connection instance is internally stored!)

If this is intended behaviour a note in the documentation is required, IMHO!

**CodeIgniter 4 version**
CodeIgniter 4.0.0 Alpha 2

**Affected module(s)**
system/Database/Config.php

**Comment by jim-parry** [comment]
Do you get the proper behavior when you specify FALSE for getShared (the second parameter)?
The way you use connect(), of course the two databases are the same - that is the expected and documented behavior. Nothing astonishing about this.
There may be a separate issue with the 'group' used internally, but getShared default or true will result in $db1==$db2 regardless. You might avoid the problem of only recording the latest connection istance by specifying an explicit 'group' attribute of a config array, eg. different groups dor db1 and db2 (in addition to getShared = false).

**Comment by hwiesmann** [comment]
If I am passing FALSE I will get different databases.

I do not agree that this is expected behaviour - at least I could not find any documentation about it. The documentation says "$getShared Whether to return a shared instance of the connection.". But when passing different configuration settings there is nothing to share (these a different connections in my eyes).

I could also accept that the returned database interface (second call) would return the same variable and using the new configuration settings but it still uses the old ones!

**Comment by lonnieezell** [comment]
You're right. It's a bug. And likely applies to more than just databases, honestly. It currently doesn't take into account any options passed to it. So we should probably append a hash of the options onto the end of the name so we can save unique instances per config settings in the Services class.
