### ISSUE TITLE
Sample code in Entity documentation contains useless statement

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1534]
---
name: Bug report
about: Sample code in Entity documentation contains useless statement

---

**Describe the bug**
The function getCreated() in section "Handling Business Logic" of the documentation contains the following code:

```
public function getCreatedAt(string $format = 'Y-m-d H:i:s')
{
...
        return $format === true ? $this->created_at : $this->created_at->format($format);
}
```
If the function requires as a parameter a string `$format === true` can never be true.

**CodeIgniter 4 version**
CodeIgniter 4.0.0 alpha 2

**Affected module(s)**
Documentation section "Working with Entities" sub-section "Handling Business Logic".

**Comment by jim-parry** [comment]
Fixed in #1540
