### ISSUE TITLE
Docs : some links are broken due to lack of prefix CodeIgniter4

### ISSUE THREAD

**Issue by BadeelProject** [codeigniter4/CodeIgniter4#1537]
---
name: Bug report
about: some link in documentation are miss-redirecting due to the absence of the prefix CodeIgniter4

---

**Describe the bug**
link : (broken link)[https://codeigniter4.github.io/CodeIgniter4/concepts/security.html#id2]
anchor text : HTTP library

thanks

**Comment by bangbangda** [comment]
Link updated.
