### ISSUE TITLE
need change file_exists to is_file?

### ISSUE THREAD

**Issue by ytetsuro** [codeigniter4/CodeIgniter4#1543]
I think would need strict check file when want file.

And, `is_file` is faster than `file_exists`.

In CodeIgniter, the file_exists function is used at the place where you are requesting a file.
I would like to change this to use the is_file function.
Shall I make RR?

your want that change?

https://github.com/codeigniter4/CodeIgniter4/search?q=file_exists&unscoped_q=file_exists

benchmark PHP7.1
```
<?php

touch('dummy');
$start = microtime(true);
for($i = 0; $i < 10000; $i++) {
file_exists('dummy');
}
echo (microtime(true) - $start)."\n";                                           

$start = microtime(true);
for($i = 0; $i < 10000; $i++) {
is_file('dummy');
}
echo (microtime(true) - $start)."\n";
```
0.0363450050354
0.0103449821472

**Comment by natanfelles** [comment]
Yes. Check with `is_file` where only a file is wanted.

[`file_exists`](http://php.net/manual/en/function.file-exists.php) also returns true if the filename is a directory, this is not wanted.
