### ISSUE TITLE
Ability to add namespace to FileLocator class

### ISSUE THREAD

**Issue by amigoscs** [codeigniter4/CodeIgniter4#1552]
I add a `namespace` (`Services::autoloader()->addNamespace()`) and expect the `FileLocator class` to look for my class also in the added namespace, but this does not happen.

**Example:**

In my controller
`Services::autoloader()->addNamespace('MyPlugin', APPPATH . 'Plugins/MyPlugin/');`

Next, I try to access the language file
`Lang('MyPlugin.title')`

I expect the `Language class` will also load the file along the way 
`APPPATH . 'Plugins/MyPlugin/Language/{locale}/MyPlugin.php`

but this is not happening

**CodeIgniter 4 version**
CodeIgniter 4.0.0 alpha 2

**Comment by natanfelles** [comment]
For now, add the namespace in your \Config\Autoload that will work.

For some reason the Autoloader instance used by the FileLocator is not the same as when the system starts.

Investigating...

**Comment by amigoscs** [comment]
I cannot add a namespace to \Config\Autoload, since the number of plugins may be different and not everyone should be connected...

So far I have solved this problem by adding a method to `FileLocator class`
```
public function addNamespace(string $name, string $value)
	{
		$this->namespaces[$name] = $value;
	}
```
and in `Autolader class` made changes to the method `addNamespace()`

```
public function addNamespace(string $namespace, string $path)
	{
		if (isset($this->prefixes[$namespace]))
		{
			. . . . . . . . . . . .
		}
		else
		{
			$this->prefixes[$namespace] = [$path];
			service('locator')->addNamespace($namespace, $path);
		}
		return $this;
	}
```
The solution is not the best, but so far I do not see another...
