### ISSUE TITLE
Maybe routes has problem. [setTranslateURIDashes]

### ISSUE THREAD

**Issue by eterv** [codeigniter4/CodeIgniter4#1564]
I use this config.
 setTranslateURIDashes(true)

I think that if I connent 'users/login-process' (dash) then,
should be connected to 'login_process' (underscore) method of 'users' controller.
but contrary to my expectation, just I could see 404 page not found error page.
So, I've checked source.
I think that something important source is missing.

so now I'm using below modified code temporarily.

in: system/Router/Router.php :: autoRoute() function

	if ( ! empty($segments))
	{
		$this->method = array_shift($segments);
	}

        /**
         * Added - BEGIN
         */
        if ($this->collection->shouldTranslateURIDashes()) {
            $this->translateURIDashes = true;
            $this->method = str_replace('-', '_', $this->method);
        }
        /**
         * Added - END
         */

So, could you please check this point?

**Comment by bangbangda** [comment]
Controller name also needs to be converted.
check this [PR](https://github.com/codeigniter4/CodeIgniter4/pull/1570). do you think it is okay?

**Comment by eterv** [comment]
> Controller name also needs to be converted.
> check this [PR](https://github.com/codeigniter4/CodeIgniter4/pull/1570). do you think it is okay?

Yes. Exactly!
I checked PR and tested. in my case very good.

**Comment by eterv** [comment]
So, I try to added below one line code.

in tryToRouteIt() function (CodeIgniter.php)

// $routes is defined in Config/Routes.php
$this->router = Services::router($routes);
/* ADDED - BEGIN */
$this->router->setTranslateURIDashes($routes->shouldTranslateURIDashes());
/* ADDED - END */

$path = $this->determinePath();

After I modify, there is no problem.

**Comment by lonnieezell** [comment]
@eterv Just pushed a potential fix, please let me know if it works for you. It is based off of what @bangbangda did, but I think he missed one place.

**Comment by eterv** [comment]
@lonnieezell thank you for your help and code.

but, I think that need to add below one line code.

in CodeIgniter.php :: tryToRouteIt() method

// Already exist...
$this->router = Services::router($routes);
// A new line
$this->router->setTranslateURIDashes($routes->shouldTranslateURIDashes());

// Already exists...
$path = $this->determinePath();

After modify it then, finally there is no any problem in auto route.

So, could you please consider and test it?

**Comment by lonnieezell** [comment]
Good catch. Thanks. Fixed now.
