### ISSUE TITLE
Database Migrations inconsistent info about sequential type 

### ISSUE THREAD

**Issue by Martin-4Spaces** [codeigniter4/CodeIgniter4#1577]
Hello

This only applies to migration type sequential.
After this [commit](https://github.com/codeigniter4/CodeIgniter4/commit/08fbcbb54a28c3506083148f766d52e928471287#diff-1194e9e2013880118067cb327d95c75d) adding type hints to system migration class. The supplied version is parsed as int. 
If I want to migrate to version 002 it will parse this as int and therefore remove the 00. The class will then check for migration file with the name 2.php and not 002.php. Resulting in an error, migration file not found.
This conflicts with the old sequential style and the [docs](https://codeigniter4.github.io/CodeIgniter4/dbmgmt/migration.html?highlight=sequential).

**Comment by Martin-4Spaces** [comment]
I tried to change my app from using 002.php to 2.php to comply with the new type hinting. 
Then I get problems with MigrationRunner::findMigrations. This method checks the folder and validate the filename with regex `/^\d{3}_(\w+)$/`. The regex require three digits. 

I'll suggest removing the int type hinting on MigrationRunner::version and MigrationRunner::checkMigrations.

**Comment by jim-parry** [comment]
@Martin-4Spaces Can you test if PR 1585 addresses your issue?

**Comment by Martin-4Spaces** [comment]
@natanfelles @jim-parry It works perfectly!
