### ISSUE TITLE
Model's without primary keys get pagination counts wrong

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#1597]
It seems that I encountered another issue because of not using primary key. It seems that the new CodeIgniter's design is built around primary key system?

I supposed to have '5' results from my query.
I want to count how many result for pagination so I used `$query->countAllResults()` to count it, the result was '2', I don't know where '2' came from.
I then tried to view the result using `$query->getResult()`, it shows '5' results correctly.  `$query->paginate()` shows correct result as well. 

Here's the test code I used
```
$query = $this->select('name, SUM(ctr_choose) as total_choose');
$query->join('food', 'user_answer.id_food=food.id');
$query->groupBy('id_food');
$compiled = $query->getCompiledSelect();
print_r($compiled);
echo '|';
$this->resetQuery();
$query = $this->select('name, SUM(ctr_choose) as total_choose');
$query->join('food', 'user_answer.id_food=food.id');
$query->groupBy('id_food');
print_r($query->countAllResults()); //result: 2 (incorrect)

echo '|';
$query = $this->query($compiled);
print_r(count($query->getResult())); //result: 5 (correct)
	
$link = mysqli_connect("localhost", "root", "", "battermod");
$result = mysqli_query($link, $compiled);
$num_rows = mysqli_num_rows($result);
echo "\n <$num_rows Rows>\n"; //result: 5 (correct)

```

Because there's no `$this->db->last_query();`, I don't know what kind of query `countAllResults` produced.

_Originally posted by @cobafesbuk in https://github.com/codeigniter4/CodeIgniter4/issues/1583#issuecomment-445203683_

**Comment by cobafesbuk** [comment]
Hi, I just noticed `$query->get()->resultID->num_rows` shows correct result.
Better workaround than `count($query->getResult())`.

**Comment by atishamte** [comment]
There is no point of keeping the statement,

$sql = ($this->QBDistinct === true) ? $this->countString . $this->db->protectIdentifiers('numrows') . "\nFROM (\n" . $this->compileSelect() . "\n) CI_count_all_results" : $this->compileSelect($this->countString . $this->db->protectIdentifiers('numrows'));

This should work with,
$sql = $this->compileSelect($this->countString . $this->db->protectIdentifiers('numrows'));

**Comment by lonnieezell** [comment]
@atishamte Not sure where you're referring to with that query. 

However, the more I think about this the less I'm concerned with having it work without a primary key. As we've added a bunch of new features to the model, many do rely on having a primary key to work. Many people also want an ORM and if that's ever going to happen, it's likely that we'll need to have primary keys on models. 

So - closing this because we won't support that in models. I'll have it throw an exception when a model doesn't have a primary key so it's obvious.

**Comment by atishamte** [comment]
I was referring to the countAllResult function body
