### ISSUE TITLE
Memory leak - binds not being cleared after find()

### ISSUE THREAD

**Issue by Martin-4Spaces** [codeigniter4/CodeIgniter4#1604]
Version: Alpha.4.

Memory usage keep increasing when saving a many models. Memory usage raises above 128MB when saving 1.000 models with 10 properties.
I tried setting `$skipValidation = true` and it fixed the issue. Now memory usage is ~2MB. I do not have any validation rules. 

Looks like a memory leak in the validation part. 
Sorry, I do not have further details.

**Comment by Martin-4Spaces** [comment]
I will investigate and return with more details.

**Comment by Paradinight** [comment]
How about an example code?

**Comment by Martin-4Spaces** [comment]
Here is an example project. [CI4Issue.zip](https://github.com/codeigniter4/CodeIgniter4/files/2672163/CI4Issue.zip)

**Model**
```php
class TrashModel extends \CodeIgniter\Model {

    public $table = 'trash';
    public $id;
    public $content;

}
```

**Controller**
```php
    public function exampleWithMemoryLeak()
    {
        $total = 2500; // ~Max for 120MB
        $printInterval = 100;

        $model = new TrashModel();

        for($i = 0 ; $i < $total ; $i++) {

            $model->find($i);

            if(! ($i % $printInterval)) {
                Data::memory("$i items");
                Data::debug(serialize($model));
            }

        }

        $this->response->setJSON(Data::getStore());
        $this->response->send();
    }
```

Data::memory and Data::debug is a debugging tool I use. 
Unzip the project. Add your .env file and database connection. Create a table:
```sql
CREATE TABLE `trash` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `content` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Check the output of `/home` and you will see the memory usage increase over time. You can also see the serialised `$model` and that `binds` grow for every find on the same model. 

Check the output of `/home/exampleWithoutMemoryLeak` and you will that memory usage is unchanged.

```php
    public function exampleWithoutMemoryLeak()
    {
        $total = 10000;
        $printInterval = 100;

        for($i = 0 ; $i < $total ; $i++) {

            $model = new TrashModel();
            $model->find($i);

            if(! ($i % $printInterval))
                Data::memory("$i items");

        }

        $this->response->setJSON(Data::getStore());
        $this->response->send();
    }
```

**Comment by lonnieezell** [comment]
Just pushed a fix. Let me know if you're running into issues with it.
