### ISSUE TITLE
Pls remove string type in parameter $group at Database::forge

### ISSUE THREAD

**Issue by Martin-4Spaces** [codeigniter4/CodeIgniter4#1605]
It is possible to provide a group array to Database::connect(). The same should be possible to Database::forge and Database::utils.

**Comment by lonnieezell** [comment]
while I think it's a fine change to make, I'm curious why you're using just an array and not adding it as a group in the database config. What type of app are you making? Trying to develop a better picture of other people's use cases.

**Comment by Martin-4Spaces** [comment]
@lonnieezell 
I am importing data from an old database supplied by a customer. A one time thing, but the name of that database can change from customer to customer. 
I know the database hostname, username and password. I copy the group from database config and only change the database name. 
This could be avoided if I could supply database name as second parameter to Database::connect/forge/utils.

**Comment by lonnieezell** [comment]
Gotcha. thanks for explaining. Another potential solution is use the .env file to set the database configs, but that would require a PHP/server restart after every change, I think, which isn't feasible if you're doing it all on one server.

**Comment by Martin-4Spaces** [comment]
For now, I solved it by adding the `forge` function to `application/Config/Database` and added support for group as an array.
```php
    public static function forge($group = null) {
        if (is_array($group)) {
            $config = $group;
            $group  = 'custom-' . md5(json_encode($config));
        }

        $config = new \Config\Database();

        static::ensureFactory();

        if (empty($group))
        {
            $group = ENVIRONMENT === 'testing' ? 'tests' : $config->defaultGroup;
        }

        if (is_string($group) && ! isset($config->$group) && strpos($group, 'custom-') !== 0)
        {
            throw new \InvalidArgumentException($group . ' is not a valid database connection group.');
        }

        if (! isset(static::$instances[$group]))
        {
            $db = static::connect($group);
        }
        else
        {
            $db = static::$instances[$group];
        }

        return static::$factory->loadForge($db);
    }

```
