### ISSUE TITLE
Custom routing rule not match the User Guide

### ISSUE THREAD

**Issue by Instrye** [codeigniter4/CodeIgniter4#1609]
**Describe the bug**
https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html
>```
>$routes->add('blog/joe', 'Blogs::users/34');
>```
>A URL containing the segments “blog/joe” will be remapped to the “Blogs” class and the “users” method. The ID will be set to “34”:

But actually the method is `users/34`

visit page show 404

**CodeIgniter 4 version**
version 4.0.0-alpha.3

**Affected module(s)**
Routes

**Expected behavior, and steps to reproduce if appropriate**
In `application/Config/Routes.php` set:
```
$routes->add('blog/joe', 'Blogs::users/34');
```

In `application/Controllers/Blogs.php` set:
```
<?php namespace App\Controllers;

use CodeIgniter\Controller;

class Blogs extends Controller
{
    public function users($id){
        echo $id;
    }
}
```
visit `/blog/joe` and `/blogs/users/34` should show 
![snipaste_2018-12-14_15-28-41](https://user-images.githubusercontent.com/9927289/49989454-32b9c900-ffb5-11e8-95a9-3bdc20e89adb.png)
but visit `/blog/joe` show
![snipaste_2018-12-14_15-28-27](https://user-images.githubusercontent.com/9927289/49989415-1a49ae80-ffb5-11e8-916a-a13d38db2362.png)

**Comment by lonnieezell** [comment]
There's not a bug there. When you're specifying the "to" portion of the route, `users/34` it expects the last, non-placeholder segment, to be the method called. I'm guessing the `34` is supposed to be the ID of the user or post? In that case you need a placeholder to accept the ID from the URL and pass it as an argument to the method. 

```
$routes->add('blog/joe/{id}', 'Blogs::users/$1');
```

Please read the [user guide](https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html) for more information, or ask at the forum for help.
