### ISSUE TITLE
Composer Installation downloads app and application folder.

### ISSUE THREAD

**Issue by rmcdahal** [codeigniter4/CodeIgniter4#1620]
I am trying to install ci using composer using command
 `composer create-project codeigniter4/framework:dev-master ci4`
and composer download all required folders but it also downloaded application folder which is already removed in favour of app

![screenshot_1](https://user-images.githubusercontent.com/1020935/50228500-393eab00-03d0-11e9-956f-ef26f2091ce9.png)

**Comment by jim-parry** [comment]
Sorry - I think that is my fault, not clearing out the distribution folders before uploading. This will be foxed for the next update!

**Comment by jim-parry** [comment]
Patched the release directly, fixing this.
