### ISSUE TITLE
View data not being passed between each call?

### ISSUE THREAD

**Issue by niteraven7** [codeigniter4/CodeIgniter4#1621]
I updated from alpha3 to alpha4 and view data is no longer being passed from view to view. I have a partial template that echos notices, for example "echo $validation->listErrors()". It's being called from a view so I can reuse the code. The $validation variable is no longer being passed from view to view. Has something changed in alpha4? I cannot figure out where from the changelog.

FYI:
Config\View.php
public $saveData = true;

version: alpha4

**Comment by niteraven7** [comment]
It looks like the view config file is not being loaded?

If I change System\View\View.php:
$this->saveData = true;

It works.

**Comment by lonnieezell** [comment]
You're right - the config file wasn't being loaded due to a change in the Toolbar passing the wrong parameters to grab the view, which ended up not loading the view, and the view instance got cached with the wrong setting. 

Fixed in latest push.
