### ISSUE TITLE
Transaction documentation error and/or bug

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1638]
---
name: Bug report
about: Either the documentation in section "Enabling Transactions" is wrong or misleading and/or the transaction handling is buggy.

---

**Describe the bug**
The documentation says in section "Enabling Transactions":

> Transactions are enabled automatically the moment you use $this->db->transStart(). If you would like to disable transactions you can do so using $this->db->transOff()

This might be a misleading documentation in case it is meant that transactions are enabled till $this->db->transOff() is called.
If you interpret the sentence as I do this is a bug because

1. transStart() does not enable transactions (see code below)
```
	public function transStart($test_mode = false)
	{
		if ( ! $this->transEnabled)
		{
			return false;
		}

		return $this->transBegin($test_mode);
	}
```
2. there is no method to enable transactions again once they have been switched off

**CodeIgniter 4 version**
CodeIgniter 4 Alpha 4

**Affected module(s)**
Database

**Comment by puschie286** [comment]
yes the docu text could be more clear - but the point is, there are no reasons to disable and re-enable transaction. you can disable it for testing/dev purpose but in production application you have no reason to disable it ( and lower the security, stability, reliability ).
