### ISSUE TITLE
DebugToolbar - too much recursion

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1650]
I've noticed on some pages that there is no Debug Toolbar icon... i thought it is because of my CSP settings... but I think it is because:

I've noticed on some pages that there is no Debug Toolbar icon... i thought it is because of my CSP settings... but I think it is because:

FF:
```
dev.my-host.com:66:6
newXHR
https://dev.my-host.com/:66:6
newXHR
https://dev.my-host.com/:66:16
newXHR
https://dev.my-host.com/:66:16
newXHR
https://dev.my-host.com/:66:16
newXHR
https://dev.my-host.com/:66:16
newXHR
(... about 60 times X 2)
```
Irudium@Chromium:
```
2?debugbar:1 Uncaught RangeError: Maximum call stack size exceeded
    at new newXHR (?debugbar:1)
    at new newXHR (?debugbar:66)
    at new newXHR (?debugbar:66)
    at new newXHR (?debugbar:66)
    at new newXHR (?debugbar:66)
    at new newXHR (?debugbar:66)
    at new newXHR (?debugbar:66)
    at new newXHR (?debugbar:66)
    at new newXHR (?debugbar:66)
    at new newXHR (?debugbar:66)
```

I think my code is up to date:
```

// Track all AJAX requests           - LINE 62
var oldXHR = window.XMLHttpRequest;

function newXHR() {
	var realXHR = new oldXHR();    - LINE 66
	realXHR.addEventListener("readystatechange", function() {
		// Only success responses and URLs that do not contains "debugbar_time" are tracked
		if (realXHR.readyState === 4 && realXHR.status.toString()[0] === '2' && realXHR.responseURL.indexOf('debugbar_time') === -1) {
			var debugbarTime = realXHR.getResponseHeader('Debugbar-Time');
			if (debugbarTime) {
				var h2 = document.querySelector('#ci-history > h2');
				h2.innerHTML = 'History <small>You have new debug data.</small> <button onclick="loadDoc(' + debugbarTime + ')">Update</button>';
				var badge = document.querySelector('a[data-tab="ci-history"] > span > .badge');
				badge.className += ' active';
			}
		}
	}, false);
	return realXHR;
}

window.XMLHttpRequest = newXHR;        - LINE 82
```

in this case I don't use d() or anything like that, just wanna to see Debug Toolbar. There is some complex data passed to the view but nothing big :/.

**Comment by natanfelles** [comment]
This is the dev will. Eternal recursion.

Please, how can I reproduce it?

**Comment by nowackipawel** [comment]
What do you need? :).
I've got only one action where there this issue occur. ... example json file from debugbar (i cut out salt and other sensiteive data, and password equals your nickname on github).

[debugbar_1546811372.json.zip](https://github.com/codeigniter4/CodeIgniter4/files/2730908/debugbar_1546811372.json.zip)

**Comment by natanfelles** [comment]
Ok, thanks.

**Comment by nowackipawel** [comment]
pls lemme know if you will need anything else :). 
as for now i don't have more ideas what could be helpful for u.

**Comment by nowackipawel** [comment]
Unfortunately there is no ajax call on this page at all. I am using ajax calls in the app widely but this route is free from ajax calls :(. That issue doesn't occur on pages where I am using ajax calls.

Html is here:
[html-que-id.html.zip](https://github.com/codeigniter4/CodeIgniter4/files/2732637/html-que-id.html.zip)
password as was in the previous file.

Calls:
```
200
GET
1570
dev.ss.com
document
html
6.43 KB
20.71 KB
21 ms
200
GET
main.css?t=1546862966
dev.ss.com
stylesheet
css
216.68 KB
216.24 KB
1 ms
304
GET
jquery-3.3.1.min.js
dev.ss.com
script
js
cached
0 B
2 ms
304
GET
popper.min.js
dev.ss.com
script
js
cached
0 B
2 ms
304
GET
bootstrap.min.js
dev.ss.com
script
js
cached
0 B
3 ms
GET
css?family=Montserrat:400,800|Open+Sans:400,700&subset=latin-ext
fonts.googleapis.com
stylesheet
200
GET
/?debugbar
dev.ss.com
script
js
3.34 KB
3.05 KB
8 ms
```

I didn't see that issue on other routes,  I've got defined around 40 of routes.


I could try to organize VPN access to this page if you have to check anything else (it is on my laptop). It is unfinished but I am not planing to change anything in next few days in its code in next couple of days. In case you'd like to see it please write me an email.

**Comment by nowackipawel** [comment]
Woow. gr8.
My editor (php storm) changed tbody => body (weird).  Ofc everything is working now.
Thank you for pointing this out...:D
