### ISSUE TITLE
Issue Extend Core Class

### ISSUE THREAD

**Issue by Iamscalla** [codeigniter4/CodeIgniter4#1653]
There's an issue with getsharedinstance while extend the core class.
prior to the last major change on Autoload and Baseservice, it was all Good.

for instance i extended the view class and used the extended service as follows,
$renderer = Services::renderer($path, null, true);

i still get a call to the core class lib instead of the extended lib.
![screenshot_2019-01-06 error](https://user-images.githubusercontent.com/621320/50734719-9e9de480-11a3-11e9-8f38-7ec8f80118bf.png)

```php
<?php

namespace App\Libraries\View;

use Config\Services;
use CodeIgniter\View\View as BaseView;

class View extends BaseView
{

	/**
	* Check if the view exist
	*
	* @param  string $view
	* @return boolean
	*/
	public function exists(string $view): bool
	{
		$fileExt  = pathinfo($view, PATHINFO_EXTENSION);
		$realPath = empty($fileExt) ? $view . '.php' : $view;
		$file = $this->viewPath . $realPath;
		if (! file_exists($file))
		{
			$file = $this->loader->locateFile($view, 'Views');
		}
		if (empty($file))
		{
			//log_message('error', "{$view} view is not found");
			return false;
		}
		return true;
	}
}

```

then i extended the render service as shown below
```php

public static function renderer($viewPath = null, $config = null, bool $getShared = false)
	{
		if ($getShared)
		{
			return static::getSharedInstance('renderer', $viewPath, $config);
		}

		if (is_null($config))
		{
			$config = new \Config\View();
		}

		if (is_null($viewPath))
		{
			$paths = config(Paths::class);

			$viewPath = $paths->viewDirectory;
		}
		return new \App\Libraries\View\View(
			$config,
			$viewPath,
			static::locator(true), CI_DEBUG,
			static::logger(true)
		);
	}
```

**Comment by chistel** [comment]
@natanfelles did a check, the class path is correct. Mind u, this error occurs when the sharedinstance is true.

**Comment by natanfelles** [comment]
Good to know that you found the bug when you saw that using the same instance in `$r` it worked.

Thanks for mind me (and saying why) even though I've seen it but thought it was part of your customizations! Next time you do not need to open an issue because of this, and that's very good.

**Comment by chistel** [comment]
@natanfelles please re-phrase "Good to know that you found the bug when you saw that using the same instance in $r it worked." I seem lost.

**Comment by natanfelles** [comment]
No. You are not lost. You solved. And that's it.

Thanks, for say that if the `$getShared` param is set to `true`, this error occurs.

Have a great week, @chistel !
