### ISSUE TITLE
Feature request make is_unique - more than one field.

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1655]
As for now is_unique supports only one column like this:

is_unique[t_handbook_subject.hsu_slug,hsu_id,{hsu_id}]

it will be great if we will be able to support sth like this:

``is_unique[t_handbook_subject.hsu_slug,hsu_id#hsu_lang,{hsu_id#hsu_lang}]``
or at least sth like this:
``is_unique[t_handbook_subject.hsu_slug,CONCAT(`hsu_id`,'#',`hsu_lang`),{hsu_id#hsu_lang}]``

... for tables where unique keys contains more than one field.

I know that this first idea how to do this is not smart enough... but i didn't think how to realize it in a good way yet.

Required changes:
- passing entire row to is_unique method,
- parsing is_unique rule.

**Comment by bangbangda** [comment]
I think using [Creating Custom Rules](https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#creating-custom-rules) will solve your problem better.

**Comment by lonnieezell** [comment]
That becomes way too complex a function at that point. I agree that a custom rule is a better solution here, or simply a custom check in the model or wherever.
