### ISSUE TITLE
Cache Filehandler should implement smart directories to optimize cache location speeds

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#1658]
Currently the filehandler for the Cache engine just lumps all cache files in a single directory. To optimize file location, we should implement one or more levels deep of folder structures based on the key name. Also need to ensure that the key name has been sanitized for use as a file name, or a hash be used in it's place, though we might start offsetting the performance gains if we're not too careful there.

**Comment by nowackipawel** [comment]
I am not sure about: 
" or a hash be used " 
because if we will use hash instead of keys we will loose ability to find cache file easily (i.e. command line, file browser, etc.)

**Comment by lonnieezell** [comment]
An md5 or sha1 should always create the same hash. You do have the small chance for name collision even then, though, plus it's less developer friendly for sure. Though something could be added to the toolbar to help show that. 

But I agree. I'm not 100% sold on it. Haven't properly weighed pros vs cons yet. Leaning on the side of just sanitizing the name and calling it good. I did check the code and we don't sanitize the filename anywhere. Probably because it's the developer creating the key name, but we should still do that.
