### ISSUE TITLE
Cache system should support site-wide prefixes

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#1659]
This would provide consistency with the database engine and allow more flexibility for multi-site usages of the framework.

**Comment by bangbangda** [comment]
The $prefix variable in the app/Config/Cache.php file, can't it?
or, can I set it in the PHP code?
`cache()->prefix('blog')->save('userName', $userName, 300);`
`cache()->prefix('website')->save('userName', $userName, 300);`

**Comment by lonnieezell** [comment]
Doh! You're right. It's already there. Silly me.
