### ISSUE TITLE
Sequential Migrations don't run to the correct version

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#1666]
From [the forums](https://forum.codeigniter.com/thread-72628.html):

When i use: php spark migrate:version 20180116211000
it's executing always the first in the migration directory for instance 20180115210500_Add_Department.

When i using the sequential system it work correctly.
For instance: php spark migrate: version 007

**Comment by bangbangda** [comment]
I tested, I didn't find the problem.
Migrations file:
20190118151243_blog.php, 20190118151543_user.php

`php spark migrate:version 20190118151543`
Run 20190118151543_user.php file, is ok.

**Comment by d4mn** [comment]
It's because on some systems default file sort differs i think. When i print $migrations array before migrate it shows bad sorting. Actually migrations array should be sorted on code side to not get this I think.

**Comment by lonnieezell** [comment]
@d4mn Oh man, I had totally forgotten about that. Good call, thanks! It's been a few years since I ran into that but have seen that before.
