### ISSUE TITLE
Pagination / pager->links() double encodes links

### ISSUE THREAD

**Issue by niteraven7** [codeigniter4/CodeIgniter4#1680]
My app is showing some results/reviews on a page and I also have the ability to filter these results using various criteria. My filter parameters passed as an array and are form submitted with get that has a URL like:

/reviews?filter%5Bkeyword%5D=test&filter%5Bsubmit%5D=1

The pager->links() currently and incorrectly **double encodes** the [] and then appends page=1, 2, 3 etc. to the end:

/reviews?filter%255Bkeyword%255D=claim&filter%255Bsubmit%255D=1&page=2

Note the 255B and 255D are double encoded [ and ] and it's breaking the URL.

version: alpha4

Thanks!

-Kyle

**Comment by InsiteFX** [comment]
Read this:

[Apache: how to double-decode double-encoded incoming URLs](http://www.it1me.com/it-answers?id=26635707&ttl=Apache%3A+how+to+double-decode+double-encoded+incoming+URLs)

**Comment by niteraven7** [comment]
@InsiteFX OK- but the whole point of pager->links() is to carry on the query parameters. That way the user can paginate through pages of results (filtered or not).

**Comment by niteraven7** [comment]
I'm thinking of creating a CI4 Controller Filter to modify/clean-up the URI before it's passed on to controller. Maybe I can grab the get variables and loop through/decode/clean-up stuff and then it'll work. I'm just having trouble figuring out how to do that now :-/

**Comment by lonnieezell** [comment]
@niteraven7 Is your code up to date? I feel like we've ran into this in the past and fixed it.

**Comment by niteraven7** [comment]
@lonnieezell Yes, I'm using alpha4.

**Comment by niteraven7** [comment]
I think this is what you might be thinking of:

https://github.com/codeigniter4/CodeIgniter4/issues/950

**Comment by niteraven7** [comment]
It looks like you've decoded the values but not the parameters/keys...

**Comment by niteraven7** [comment]
`			// URL Decode the value to protect
			// from double-encoding a URL.
			// Especially useful with the Pager.
			$parts[$key] = $this->decode($value);
`

**Comment by niteraven7** [comment]
It looks like this works:

`$parts[$this->decode($key)] = $this->decode($value);`

**Comment by lonnieezell** [comment]
@niteraven7 I believe you are correct. Just pushed that change. Hopefully this will work for you.
