### ISSUE TITLE
Router issue - overwriting.

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1692]
I've got two subdomains:
doc and dev.
And my Routes.php is as bellow:
```
$routes->setDefaultNamespace('App\Controllers');
$routes->setDefaultController('Home');
$routes->setDefaultMethod('index');
...
$routes->get('/', 	'App\Controllers\Site\CDoc::index', ['subdomain' => 'doc', 'as' => 'doc_index']);
$routes->add('/', 'Home::index');
```
but after request to https://doc.domain I get Home::index instead of App\Controllers\Site\CDoc::index
I thought the first which is matched is used.... but nope.
I did a test and I changed it to:

```
$routes->add('/', 'Home::index');  // get is working in the same way
$routes->get('/', 	'App\Controllers\Site\CDoc::index', ['subdomain' => 'doc', 'as' => 'doc_index']);
```

effect still the same - doc.domain is opening Home::index .

OFC everything is working as excepted if dev.domain route to Home::index is defined like that : `
$routes->add('/', 'Home::index', ['subdomain' => 'dev']);`

**Comment by lonnieezell** [comment]
Just pushed up a possible fix for this. Can you pull the latest code and give it a try?

**Comment by nowackipawel** [comment]
Will update my code in next few days and I'll let you know. I have to compare my base code with my uncommitted PRs.

**Comment by nowackipawel** [comment]
Ok, I've updated RouteCollection.php only to make quick check.
Unfortunately does not work as expected. 


In this case:
```
$routes->get('/', 			'App\Controllers\Site\CDoc::index', 	['subdomain' => 'doc', 'as' => 'doc_index']);
$routes->add('/', 'Home::index', 	['subdomain' => 'dev']);
``` 
everything is working.

```
$routes->get('/', 			'App\Controllers\Site\CDoc::index', 	['subdomain' => 'doc', 'as' => 'doc_index']);
$routes->add('/', 'Home::index');
 ```
still opens Home:index for https://doc.domain.com.
