### ISSUE TITLE
route_to('name'); does not work for other subdomains

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1697]
I've got config like this:

```$routes->get('i/(:any)', 	'App\Controllers\Site\CDoc::item/$1', 	['subdomain' => 'doc', 'as' => 'doc_item']);```

and I'd like to use it in my project on all of subdomains (doc, dev, etc...) which are in my project. 
It is working as far as it is called using `route_to('doc_item','sth');` from doc.domain.com, but when I am trying to do this from dev.domain.com it does not work. 

I think route_to should not filter possible values to one hostname/subdomain as  Router do; that's why we could specify name of the route i.e. `as=>doc_item`. Many sites has many subdomains and use subdomains widely.  IMHO no possibility for simple linking between subdomains is a strong limit.

**Comment by jim-parry** [comment]
You explicitly provided for a subdomain restriction in your routing options, so it would be expected that the routing rule not apply to the other subdomains.
It sounds like what you are suggesting is already doable by not specifying the subdomain option, no?
What am I missing?
