### ISSUE TITLE
lang bug or not? (empty translations)

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1698]
Is it a bug that lang('File.key') returns File.key for a value defined as empty string?
I think it will be  correct as long as key does not exist in File.php array but not in case like null or ''.
Is there a way to define empty translation items?

**Comment by lonnieezell** [comment]
Well, I'm sure it probably uses an `isset` check instead of `array_key_exists` and that could probably be easily changed. That was intentional, though, so that it was easy to spot missing language strings. 

I'm curious about the need for empty translation strings, though?

**Comment by jim-parry** [comment]
That was done on purpose, so that lang(x) would not fail even with missing translations.
It is part of the intended cascading, i.e checking fr-CA then fr then en, and returning the key if there was no translation.

**Comment by jim-parry** [comment]
btw, an empty message value doesn't sound very helpful.
Eg. the following error occurred: ""
I suggest you provide your own app/Library/Language class, perhaps extending the built-in one, which provides the behavior you would like. You could then provide an over-riding language() method in app/Config/Services to return it.
