### ISSUE TITLE
Bug : changing viewsDirectory misses errors folder when exception occures 

### ISSUE THREAD

**Issue by TatwiraT** [codeigniter4/CodeIgniter4#1701]
---
name: Bug report
about: changing viewsDirectory does not affect the `errors` folder when exceptions are occurred, because of the include is taking default value `APPPATH.'Views/'` instead of the new supplied path

---

**Direction**

**Describe the bug**
![ddd](https://user-images.githubusercontent.com/3307638/52169464-d3647380-2730-11e9-9ba5-2a39010600a7.png)

**CodeIgniter 4 version**
I believe in all, In my case is pre-alpha5

**Expected behavior, and steps to reproduce if appropriate**
it have to use viewsDirectory  

**Context**
 - OS: win7
 - Web server 2.3.4
 - PHP version 7.2.9

**Comment by lonnieezell** [comment]
You can control the folder that exceptions views are located at in Config\Exceptions, with the `$errorViewPath` location: 

```
/*
	|--------------------------------------------------------------------------
	| Error Views Path
	|--------------------------------------------------------------------------
	| This is the path to the directory that contains the 'cli' and 'html'
	| directories that hold the views used to generate errors.
	|
	| Default: APPPATH.'Views/errors'
	*/
	public $errorViewPath = APPPATH . 'Views/errors';
```

It doesn't use the current viewsDirectory as set in Config\Paths on purpose. You might have several folders with themes, or whatever, but only one place where exceptions should be stored.
