### ISSUE TITLE
failValidationError($description)

### ISSUE THREAD

**Issue by vebomedia** [codeigniter4/CodeIgniter4#1702]
$description type must be (mixed) type.. according to description

https://codeigniter4.github.io/CodeIgniter4/outgoing/api_responses.html#failValidationError

but the function accept only string..

return $this->failValidationError($validation->getErrors());

doesn't work because of this issue.

**Comment by lonnieezell** [comment]
You're right -it takes a string. So give it a string: 

```
$errors = implode(', ', $validation->getErrors());
return $this->failValidationError($errors);
```
