### ISSUE TITLE
HTTP Feature Testing not working 

### ISSUE THREAD

**Issue by rino7** [codeigniter4/CodeIgniter4#1710]
**Description of the bug**
I'm working with [appstarter project](https://github.com/codeigniter4/appstarter) and when I try to run phpunit, i found serveral errors:
1) 'tests' folder is not included in the composer download, I could create it but, beyond functioning as a container of tests files, it has the '_support' folder which contain _bootstrap.php that help unit tests be executed correctly.
2) In order to fix the previous error, I downloaded manually[ 'tests' folder from develop branch](https://github.com/codeigniter4/CodeIgniter4/tree/develop/tests). After that, I try to execute a test using [HTTP Feature Testing](https://codeigniter4.github.io/userguide/testing/feature.html) but it throwing the above error:

<pre>Tests\TestHome::testIndex
CodeIgniter\Exceptions\PageNotFoundException: Controller or its method is not found: App\Controllers\\Http:::ci4.extctrl.docker:8080

/var/www/html/ci4-extendedcontroller/vendor/codeigniter4/framework/system/Exceptions/PageNotFoundException.php:14
/var/www/html/ci4-extendedcontroller/vendor/codeigniter4/framework/system/CodeIgniter.php:889
/var/www/html/ci4-extendedcontroller/vendor/codeigniter4/framework/system/CodeIgniter.php:249
/var/www/html/ci4-extendedcontroller/vendor/codeigniter4/framework/system/Test/FeatureTestCase.php:122
/var/www/html/ci4-extendedcontroller/tests/TestHome.php:21 </pre>

**CodeIgniter 4 version**
CodeIgniter 4.0.0-alpha.5 (appstarter, framework and devstarter projects)

**Affected module(s)**
HTTP Feature Testing

**Expected behavior, and steps to reproduce if appropriate**
I've described further the behavior in this [forum post](https://forum.codeigniter.com/thread-72758.html)
**Context**
 - OS: Debian (running in Docker over Windows 10)
 - Web server: Apache 2.4.5 (Debian)
 - PHP version: 7.3.1

**Comment by jim-parry** [comment]
The tests folder in the develop branch is for unit testing the framework itself, NOT your app. It is pusposefully not included in the appstarter distribution!
If you want to crete unit tests for your app, you need to create your own tests folder, and your tests would go inside tests/app
"App\Controllers\\Http:::ci4.extctrl.docker:8080" indicates that your test code might be suspect, rather than any bug in the framework. We can address this further on the forum.

**Comment by rino7** [comment]
@jim-parry Okay, so, what about ['test documentation'](https://codeigniter4.github.io/userguide/testing/feature.html)? Is intended to test my app or is for test the framework? Following that instructions it not seems to work app unit testing. Is there any full example of a working app uni test?

**Comment by jim-parry** [comment]
That test documentation is for testing your app, not the framework. See my response to yor forum thread.

**Comment by lonnieezell** [comment]
@jim-parry Looking at this, we do need to include the `tests/_support` folder as part of it. All of the things that make testing work, even for the application, require some of the stuff in that folder. 

While I think there's stuff that's not necessary and is just for framework development, it doesn't hurt to include it. Would be cleaner to separate it out but probably a giant pain to do so. 

At the very least, though, the following files are required for testing an application (I might have missed some): 

- _bootstrap.php
- CIDatabaseTestCase.php
- CIUnitTestCase.php
- Log/TestLogger.php
- DOM/DomParser.php - though that should probably be moved into system/Tests honestly. 
- Events/MockEvents.php (I think0
- Helpers/* - these should probably also be in system/Tests

Quite a few of the other Mock* classes might prove useful to people when testing their apps, but less critical.

**Comment by jim-parry** [comment]
Alright ... I will play with this :)

**Comment by jim-parry** [comment]
I have jiggered some of the support test files, and the distribution build scripts. This should work better "out of the box" with the next release. I think it wise to wait for that for thorough testing, as there are other changes that will be part of it.

**Comment by atishamte** [comment]
@jim-parry, any success as it might delay the release of beta 2.

**Comment by jim-parry** [comment]
This is the set of tests I am working on at the moment :)

**Comment by jim-parry** [comment]
The changes discussed here have been done. The Controller/Feature testing is a separate issue, and still in progress.
