### ISSUE TITLE
Why there is only 1 function in ArrayHelper? Can we introduce more?

### ISSUE THREAD

**Issue by atishamte** [codeigniter4/CodeIgniter4#1711]
I have gone through the ArrayHelper file and found only one function.

There are multiple functions which we use in our development, which we wish to have in core helpers

Can we suggest those as well to be a part of core functionality instead of custom?

This might help all developers to get the one-stop solution

**Comment by InsiteFX** [comment]
You can still extend the helpers and add what you need to it.

**Comment by nowackipawel** [comment]
If you've got some useful functions ready for this helper please PR it. 
We should be open minded for new ideas. :). 
--
Please note you should provide docs/test as well , you can complete these elements later.

**Comment by jim-parry** [comment]
This isn't a bug. We use github for tracking bugs & approved work packages.
You should raise this on https://forum.codeigniter.com/forum-29.html, with suggested helper methods, thanks.
