### ISSUE TITLE
ZendEscaper - duplicate?

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1716]
I'm not sure why we've got 
`        "zendframework/zend-escaper": "^2.5",`
in `composer.json` if there is a copy of ZendEscaper in `system/ThirdParty` directory.
Is it necessary to get it in ThirdParty and in composre.json at the same time?

**Comment by lonnieezell** [comment]
Well - this isn't a bug. It's in composer so that it always gets updated before a release. As part of updating with composer, it also copies that file to third party, where it can be found by the system whenever we create the zip file for those that don't want to use composer.
