### ISSUE TITLE
Model required validation rule not working 

### ISSUE THREAD

**Issue by REJack** [codeigniter4/CodeIgniter4#1717]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
`insert()` doesn't check for the 'required' validation rule, I've create a demo with a simple [UserModel](https://github.com/REJack/codeigniter4-demo/blob/master/app/Models/UserModel.php) & [UserModelTest](https://github.com/REJack/codeigniter4-demo/blob/master/tests/Demo/UserModelTest.php).
The UserModel requires email, password & username but if I run `insert()` without a username it doesn't fail. 
`cleanValidationRules()` removes the username rules and allows inserts without any of the required fields.

**CodeIgniter 4 version**
since v4.0.0-alpha5

**Affected module(s)**
CodeIgniter/Model

**Expected behavior, and steps to reproduce if appropriate**
`cleanValidationRules()` should only affect`update()`.

**Context**
 - OS: macOS 10.14.3
 - Web server Nginx 1.13.2
 - PHP version: 7.2.10
 - [Demo Repo](https://github.com/REJack/codeigniter4-demo)
 - [Travis Job](https://travis-ci.com/REJack/codeigniter4-demo/jobs/176723772)

**Comment by lonnieezell** [comment]
I've set up some [new tests](https://github.com/codeigniter4/CodeIgniter4/commit/4ff1f5b69efc0ad562f35ac7ba4628726b23b741) and everything is passing as it should. 

Here's how it works, though: it will always check the rules IF the key is there. In other words, this is fine and runs validation rules: 

```
'email' => 'admin@example.com',
'password' => password_hash('password12345678', PASSWORD_BCRYPT),
'username' => '',
```

while this won't run the validation rules: 

```
'email' => 'admin@example.com',
'password' => password_hash('password12345678', PASSWORD_BCRYPT),
```
In 99% of the cases I've ever encountered, this should work as expected. For example, the simplest route just uses the request object and do an insert with all of those values, then the key (`username`) will be there whether it's there or not. The other thing I typically see, and probably the smarter/safer way, is to build an array of values you're passing to the model, like: 

```
$data = [
    'username' => $this->request->getPost('username'),
    'email' => $this->request->getPost('email')
];

$model->insert($data);
```
