### ISSUE TITLE
Bug Report: Seeding

### ISSUE THREAD

**Issue by mayo83** [codeigniter4/CodeIgniter4#1720]
**Describe the bug**
I created the SimpleSeeder, like described in the [docs](https://codeigniter4.github.io/CodeIgniter4/dbmgmt/seeds.html) and called it from the example "Home"-Controller with: 
`$seeder = \Config\Database::seeder();`
`$seeder->call('SimpleSeeder');`

The Class "SimpleSeeder" is located in **app/Database/Seeds** as SimpleSeeder.php But the controller throws an class not found error. At home i have an earlier Version of Codeigniter. The same code there results in a populated database. I cant tell which version of CI4 i have at home but the obvious difference is that there is an "application" directory instead of an "app" directory.

**CodeIgniter 4 version**
4.0.0-alpha.5 (master)

**Affected module(s)**
-

**Expected behavior, and steps to reproduce if appropriate**
-

**Context**
 - OS: Tested on Windows 10 and Linux (Ubuntu like Distribution)
 - Web server: Apache 2.4
 - PHP version: 7.2.x

**Comment by lonnieezell** [comment]
Good catch. It did work if you provided the namespace with it, but should assume the default namespace when one doesn't exist... A fix is on its way.

**Comment by mayo83** [comment]
Glad its not completly my fault. With a defined Namespace the seeder works flawless. ;)
