### ISSUE TITLE
validation rule password never match

### ISSUE THREAD

**Issue by keulu-ing** [codeigniter4/CodeIgniter4#1728]
**Describe the bug**
The validation error is always triggered when use required_with[] check
The validation error is always triggered when use matches[] check

**CodeIgniter 4 version**
alpha-5

**Affected module(s)**
Form Validator

**Reproduce the behavior**
my rules : 
```
protected $validationRules    = [
        'password'     => 'required|min_length[8]',
        // 'password_confirm' => 'required_with[password]|matches[password]'
        'password_confirm' => 'matches[password]'
    ];
```

```
curl -X POST \
  localhost/users \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'cache-control: no-cache' \
  -d 'password=toto&password_confirm=toto'
```

`"password_confirm": "The password_confirm field is required when password is present."`

remove the require_check[] 

`"password_confirm": "The password_confirm field does not match the password field."`

my validations_rules are in my model. everything seems to work exept this one.

**Context**
 - OS: LMDE2
 - Web server Nginx
 - PHP version 7.1

**Comment by lonnieezell** [comment]
What data is being passed in for validation?

**Comment by keulu-ing** [comment]
```
curl -X POST \
  localhost/users \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'cache-control: no-cache' \
  -d 'password=toto&password_confirm=toto'
```
password=toto
password_confirm=toto

both existing in my $request->getPost()

**Comment by bangbangda** [comment]
required_with rule, fixing.
