### ISSUE TITLE
required_with and required_without validation rules

### ISSUE THREAD

**Issue by niteraven7** [codeigniter4/CodeIgniter4#1735]
This may be more a (mis)interpretation of the docs than a bug... but I see it more of a bug. In my opinion the required_with and required_without rules should trigger if the other fields are missing AND also do not have a value. They currently only trigger if the field is completely missing. This logic would also be in line with how the required rule works and also how the docs describe it: "set". I believe my use case is also more realistic and occurs more often thus being more helpful. How often do fields disappear completely?

Thanks for the consideration!

using: alpha5

**Comment by niteraven7** [comment]
Related note, it appears there is some logic in place for required_with to also check for value being set... so maybe this only applies to required_without.

**Comment by lonnieezell** [comment]
Fixed in #1742
