### ISSUE TITLE
Spark doesn't work when using devstarter

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#1748]
The location of the bootstrap file is hardcoded into the spark to look at /system/bootstrap which doesn't work with appstarter/devstarter setups.

Needs to be revised to have a little bit more smarts so it will work out of the box in all environments.

**Comment by lonnieezell** [comment]
@jim-parry Looks like the path is not getting updated in app\Config\Paths to account for the vendor folder with the devstarter release.

**Comment by jim-parry** [comment]
Will fix. The devstarter repo is managed independently, and not a release distribution.

**Comment by jim-parry** [comment]
Fixed app/Config/Paths, as well as composer.json, in the devstarter repo
