### ISSUE TITLE
setDefaultController not working as expected

### ISSUE THREAD

**Issue by tcrawf** [codeigniter4/CodeIgniter4#1758]
---
$routes->setDefaultController() method not working as expected
Default controller not being found with autorouting (without route definition)
---
***Situation:***
Routes.php file contains
$routes->setDefaultNamespace('App\Controllers');
$routes->setDefaultController('Pages/showme');

Routes.php does not contain an explicit route definition. The comment in the Routes.php file indicates that this is only required for performance enhancement.

// We get a performance increase by specifying the default
// route since we don't have to scan directories.
//$routes->get('/', 'Pages::showme'); Commented out

A Pages Controller with 'showme' method exists. This is in the Controllers directory and has a namespace of App\Controllers.

***Expected behaviour:***
Web browser with base url loads the 'showme' method on the Pages controller

***Actual behaviour:***
404 Controller or its method is not found: App\Controllers\\\Pages::showme 
If the route is explicitly defined then the route is reached.

It appears that the validateRequest method in Router.php is setting the $this->directory value to '//'. This is leading to auto-routing failing.

**CodeIgniter 4 version**
v4.0.0-alpha5 develop branch

**Affected module(s)**
Class Codeigniter\Router
File Router.php

**Context**
 - OS: [Ubuntu Bionic]
 - Web server [Apache 2.4.2.9]
 - PHP version [PHP 7.2.10-0]

**Comment by jim-parry** [comment]
setDefaultController specifies the default **controller** only, and should not include a method.
Your definition says to look for the Showme controller inside the Pages folder.
The routes->get('/','Pages::showme'), that you commented out, is the correct way to specify a default behaviour for an empty URI.

**Comment by tcrawf** [comment]
Thank you for the clarification. Much appreciated. I corrected the definition to specify a controller only as follows:
$routes->setDefaultNamespace('App\Controllers');
$routes->setDefaultController('Pages');

The same behaviour is observed if only specifying a controller (which defaults to the index method)
Controller or its method is not found: App\Controllers\\\Pages::index .

Is there an example in the documentation where the default controller is called without explicitly declaring the route?

**Comment by jim-parry** [comment]
This could be related to #1400 
I am re-opening this, but don't have time to dig into it right now.
I thought we had a bug with double folder separators that was fixed, but I could be wrong.

**Comment by tcrawf** [comment]
Thanks for the feedback. This looks to be highly related to the above referenced issue with double folder separators.

Just for clarity, I double checked and the user guide also indicates to use setDefaultController with format 'Controller/method': $routes->setDefaultController('Pages/showme');

**Comment by jim-parry** [comment]
Ah - I see it in the tutorial. That is wrong! <blush>I will fix it!</blush>
With the routing rule "$routes->get('(:any)', 'Pages::showme/$1');", you shouldn't even need to change the default controller.
