### ISSUE TITLE
Add validation on exists database before created

### ISSUE THREAD

**Issue by makaydenko** [codeigniter4/CodeIgniter4#1759]
CodeIgniter don't content any methods of checking of database exists.
Please add validation on exists database before created to **Forge** Class by default:
```php
protected $createDatabaseStr = 'CREATE DATABASE IF NOT EXISTS %s';
```

**Comment by lonnieezell** [comment]
You're right, it currently doesn't, and never has if memory serves correctly. I think this is a good addition, but not going to happen until after 4.0 final, since we've hit a feature freeze until release.
