### ISSUE TITLE
DIRECTORY_SEPARATOR / Different Behavior under Windows

### ISSUE THREAD

**Issue by mcsaygili** [codeigniter4/CodeIgniter4#1760]
DIRECTORY_SEPARATOR / Different Behavior under Windows
Hi, I just want to report bug (as i think)
My Enviroment
- Apache  2.4.38 
- Php 7.2.15
- Windows 10
- Using WAMP 3.1.7
- Codeigniter 4 Alpha 5

Under this code block,
dev10-net\system\Autoloader\FileLocator.php 
function : getNamespaces and locateFile

after while statement, var_dump result is;

`C:\99.mcs\dev10-net\system\Autoloader\FileLocator.php:128:
array (size=3)
  0 => string 'C:\99.mcs\dev10-net\ThirdParty/Site/\' (length=37)
  1 => string 'Site' (length=4)
  2 => string 'Views/theme/2018/common/headerView.php' (length=38)`

if you check array 0, you will see second slash.
when i change DIRECTORY_SEPARATOR to "/" under getNamespaces my problem solved. 

Is it bug or i made mistake ? I'm not sure. :)
Thanks.

**Comment by jim-parry** [comment]
Where does "ThirdParty/Site/" co,]me from? The file locator is looking for namespaced classes, which use backslashes, though the file system might use a different separator.

**Comment by byazrail** [comment]
Only modules problem;

<img width="737" alt="screen shot 2019-02-25 at 14 09 07" src="https://user-images.githubusercontent.com/5870455/53417507-d0cf0400-39e6-11e9-8943-cac8bd32a7f0.png">
<img width="342" alt="screen shot 2019-02-25 at 14 09 41" src="https://user-images.githubusercontent.com/5870455/53417508-d1679a80-39e6-11e9-8cf9-09a3d2dfccad.png">

**Comment by lonnieezell** [comment]
Can you provide example code from where you are calling it that it creates that error?

**Comment by byazrail** [comment]
@lonnieezell used code;
<img width="842" alt="screen shot 2019-02-27 at 08 04 33" src="https://user-images.githubusercontent.com/5870455/53467243-6bbaf300-3a66-11e9-848c-f3ab915aeb80.png">
This mistake only windows problem.

**Comment by puschie286** [comment]
can confirm this problem on strato hosting:
fail: `is_file( APPPATH.'Views\\Content\\'.$Cat.'.php' )`
success: `is_file( APPPATH.'Views/Content/'.$Cat.'.php' )`

all my test systems run windows 10 with apache and none of them have this problem - only one client installation has this problem ( strato hosting )

**Comment by atishamte** [comment]
for the web or cli environment, PHP accepts both \ and / as valid path separators in all OS. So just use / in your code.

When you're on a windows box and there is a need to provide a fully qualified windows/DOS path, there you can use the "\\" instead of '/'.

So, in a general way, DIRECTORY_SEPARATOR works very well the way it is intended.

Follow the link below for reference.
https://stackoverflow.com/questions/6619020/how-can-i-define-the-directory-separator-for-both-windows-and-linux-platforms

**Comment by lonnieezell** [comment]
Yes, it is recommended in PHP 99% of the time to just use a forward slash as a directory separator. PHP standardizes that and knows how to interpret on the filesystem.
