### ISSUE TITLE
Controller Test / Feature Testing output issues

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#1767]
The ControllerTester currently only gets a body in the result when the content is `echo()` in the controller. Using a `return` here doesn't work. 

However - the opposite problem exists with FeatureTesting.

**Comment by jim-parry** [comment]
ControllerTester problem fixed by 1848 & 1855. 
Feature testing up shortly.

**Comment by jim-parry** [comment]
@lonnieezell The user guide suggests that withRoutes() takes an array of mappings, but the FeatureTestCase is using an array of triplet arrays (http verb | add, URI pattern, and routing destination.

Which should it be?

**Comment by lonnieezell** [comment]
@jim-parry Looks like docs are wrong in that case. Should be able to specify the HTTP verb to use like implemented.

**Comment by jim-parry** [comment]
ok, thanks. i will update the docs as part of this

**Comment by jim-parry** [comment]
There is a bigger problem underlying this, with testing routing rules not sticking. 
Working on it.

**Comment by lonnieezell** [comment]
Uh-oh! Need any help on that?

**Comment by jim-parry** [comment]
The problem I am experiencing is that the routecollection is not being updated/replaced by second & subsequent tests in the FeatureTestTestCase. I will push what I have as a WIP -maybe you can see something I am missing, thanks.
