### ISSUE TITLE
Can't set subquery as WHERE condition.

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1775]
```
(new \ExampleModel)->where('(SELECT COUNT(*) FROM t1 WHERE t1_exa_id = ex_id)',10);
```
The reason is in `whereHaving()` method:
```
				$op = $this->getOperator($k);
				$k  = trim(str_replace($op, '', $k)); //here...
```
I am wondering if we could introduce method which allows us to turn off filtering operators from "field" names.

I think the solution will be:
1. changing whereHavingMethod():
```

				$op = $this->getOperator($k);
				if($escapeField)
				{
					$k  = trim(str_replace($op, '', $k));
				}
```
2. changing all whereX() methods like this:
```
	public function where($key, $value = null, $escape = null, $escapeField = true)
	{
		return $this->whereHaving('QBWhere', $key, $value, 'AND ', $escape, $escapeField);
	}
```

or intruduce new method like `escapeFields(bool $escape = true)`
```

	/**
	 * If operators are existed in names of fields should be deleted or not.
	 *
	 * @var bool
	 */
	protected $escapeFields = true;

	/**
	 * Allows to turn off deleting operators from field names.
	 * @param bool $escape
	 * @return $this
	 */
	public function setEscapeFields(bool $escape = true)
	{
		$this->escapeFields = $escape;
		return $this;
	}
```

**Comment by atishamte** [comment]
There is a different way to set the subquery in CodeIgniter.
This is the way to do so,
```
$subQuery = $this->db->table('job')
		   ->select('id')
		   ->where('name', 'Developer')
		   ->getCompiledSelect();
		
$jobs = $this->db->table('job')
                 ->where('id not in (' . $subQuery . ')', null, false)
                 ->get()
                 ->getResult();
```
In the above example, you can see the subquery is mentioned in the where condition, where $value parameter is null and $escape is false.

related to this, I have created the test cases for the same. Refer #1906.

**Comment by lonnieezell** [comment]
Or through [query grouping](https://codeigniter4.github.io/CodeIgniter4/database/query_builder.html#query-grouping).
