### ISSUE TITLE
History::setFiles may crash when reading empty file

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1778]
In case one of the files in WRITEPATH.'debugger/debugbar_*.json is empty the method setFiles will crash. The reason for the crash is that History::setFiles does not check if the local variable $contents contains an object before using it in the assignment

`files[] = [....];`

**CodeIgniter 4 version**
CodeIgniter4 Alpha 2.

**Affected module(s)**
History::setFiles.

**Expected behavior, and steps to reproduce if appropriate**
I do not know how it can happen that files in WRITEPATH.'debugbar' do not have any content. Therefore, I cannot give hints how to reproduce the error of having an empty file in the said directory. Though I suspect that a crash occurred while writing to one of the files and therefore the file was created without any content (or garbage content). But if one of the files is empty the above mentioned bug is visible.

**Comment by atishamte** [comment]
Can you close this as well
