### ISSUE TITLE
Toolbar::run produces incompatible data for json_encode

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1779]
**Describe the bug**
Toolbar::run json_encodes "all data required by Debug Bar". If any of the "data required by Debug Bar" (e.g. an object stored in $_SESSION) is a string containing binary data json_encode may fail. But if json_encode fails NULL is returned by Toolbar::run. This in turn means that no data will be returned.

As a test example for a string containing binary data the favicon image can be used (favicon.png). 

**CodeIgniter 4 version**
CodeIgniter4 Alpha 2

**Affected module(s)**
Toolbar and History (see issue #1778).

**Expected behavior, and steps to reproduce if appropriate**
Toolbar::run should be able to handle strings containing binary data.

**Comment by atishamte** [comment]
What would be the expected output here?
Shall we skip the binary data?

**Comment by lonnieezell** [comment]
Maybe replace any binary data with `{binary blob}` or something before json encoding?
