### ISSUE TITLE
Small typos in documentation section "Taking Advantage of Spl"

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1781]
**Describe the bug**
In section "Taking Advantage of Spl" the example
```
// Get the true realpath
echo $file->getRealpath();
```

contains two typos and should be replaced by
```
// Get the true real path
echo $file->getRealPath();
```

**CodeIgniter 4 version**
CodeIgniter4 Alpha 2 ff

**Comment by lonnieezell** [comment]
Care to make a PR?

**Comment by hwiesmann** [comment]
I wanted but I did not know that signing is required. Currently I am not prepared for signing on github.

**Comment by lonnieezell** [comment]
I've gone ahead and merged that. Thanks!

[This article](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/signing.rst) should help you get setup for signing. Doesn't take too long and once you're setup it is done.
