### ISSUE TITLE
Intention or bug? File::move does not update path

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1782]
**Describe the bug**
After a call to File::move(...) File::getRealPath() still returns the path of the file's previous location. This does not make sense, I believe, because that location is invalid. Therefore, I tend to call this a bug.

**CodeIgniter 4 version**
CodeIgniter4 Alpha 4

**Affected module(s)**
File

**Expected behaviour, and steps to reproduce if appropriate**

This reproduces the bug(?):
```
log_message('debug',$file->getRealPath());
$file->move($newDirectory,$newName);
log_message('debug',$file->getRealPath()); // expected to be $newDirectory.$newName
```

**Comment by lonnieezell** [comment]
Yes, that sounds like a bug!

**Comment by atishamte** [comment]
Here we need to update the reference of $file object to new file as this refers to old file object
