### ISSUE TITLE
Question about date helper

### ISSUE THREAD

**Issue by vibbow** [codeigniter4/CodeIgniter4#1783]
Hi there,

I just look through CI4 code, and when I look at `date_helper `-> `now` function, I'm not quiet sure what is the scenario to use this function.

From what I can see, this function will return a timestamp for a given timezome

but AFAIK timestamp is timezone unrelated, no matter which timezone you are, if you query the timestamp at same time (synced action), you get the same timestamp.

If I misunderstand this function, please let me know.

**Comment by jim-parry** [comment]
Support questions should be asked on the forum, thanks.
We use github for bug tracking and planned work.
I *think* the answer is that now() is for a "master reference", which could be a timezone but doesn't have to be.
