### ISSUE TITLE
File::move is not moving file

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1785]
**Describe the bug**
File::move is not moving a file (but directories if accidentally possible)!

The line in File::move

```
		if (! @rename($this->getPath(), $destination))
```

has to be replaced by
```
		if (! @rename($this->getRealPath(), $destination))
``

because $this->getPath() is only referring to the directory in which the file can be found.

**CodeIgniter 4 version**
CodeIgniter4 Alpha 4

**Affected module(s)**
File

**Comment by bangbangda** [comment]
:open_mouth: When you upload a file, you can move the file normally.
But, `new CodeIgniter\Files\File('/tmp/user-12.png')` will fail.

**Comment by atishamte** [comment]
I guess, this is fixed in #1809

**Comment by jim-parry** [comment]
@hwiesmann Can you confirm that this has been fixed?

**Comment by hwiesmann** [comment]
@jim-parry Works for me!
