### ISSUE TITLE
Output getting buffered when running via command line 

### ISSUE THREAD

**Issue by fijas** [codeigniter4/CodeIgniter4#1792]
When running methods via CLI, output buffering is on. 

Eg: 
```
public function test() {
    for($i = 0; $i <= 10; $i++) {
        echo $i; sleep(2);
    }
}
```

this function prints the output all at once after running instead of printing with a 2 second delay. Adding ob_end_flush() outputs the result as expected. I don't think this is the expected behavior for CLI methods?

CI version: 4.0.0-beta1
PHP Version: 7.2.x

**Comment by lonnieezell** [comment]
If you use the functions in the [CLI library](https://codeigniter4.github.io/CodeIgniter4/cli/cli_library.html), it works as you would expect.
