### ISSUE TITLE
Is hashId function missing?

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1801]
I am sure that I used hashId functions in `-dev` version.
As for now I saw that it is mentioned in docs:
```
(:hash) is the same as :segment, but can be used to easily see which routes use hashed ids (see the Model docs).
```
but I cannot find it anywhere in source code as well as in `Model docs`.

**Comment by nowackipawel** [comment]
I've found related code here:
https://github.com/nowackipawel/CodeIgniter4/blob/develop/system/Model.php
methods:
* findByHashedID
* decodeID
* encodeID
* getHash

**Comment by jim-parry** [comment]
It was removed some time ago; see https://github.com/codeigniter4/CodeIgniter4/commit/f87ffec26b0d3dca7544a6e76e9110f03671dc54#diff-384916434b0b7a276d4abf274120e2c3

It appears your repo is not synch'ed with the main one.

**Comment by nowackipawel** [comment]
@jim-parry : Yes, I know I pointed out to outdated Model.php but there are informations about hashes in current docs. I.e. https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html?highlight=hash (Placeholders section).

**Comment by jim-parry** [comment]
Ah - I think the docs need to be modified :) will do!
