### ISSUE TITLE
Missing documentation: parser is not able to handle nested loops

### ISSUE THREAD

**Issue by hwiesmann** [codeigniter4/CodeIgniter4#1821]
**Describe the bug**
In issue #1799 was clarified that the parser is currently not able to handle nested loops. This is not documented. Therefore, the documentation should be amended to clarify this shortcoming.

**CodeIgniter 4 version**
CodeIgniter4 Beta

**Affected module(s)**
Parser

**Comment by jim-parry** [comment]
This is not a bug, nor is it a claimed feature of the parser. I don't see that the user guide needs to be changed.
I responded to your forum thread on this, suggesting that you might add it as a feature request.

**Comment by hwiesmann** [comment]
I think that this is debatable: if there is a loop statement supported all programming languages support nested loops (at least I am not aware of a language that is not supporting nested loops). Therefore, I also expect that parsers handle nested loops as long as nothing is mentioned. But as this is not the case I suggest to add a remark to the documentation.
