### ISSUE TITLE
UploadedFile::move and File::move have different implementation

### ISSUE THREAD

**Issue by atishamte** [codeigniter4/CodeIgniter4#1825]
I have gone through the file under system/Files/File.php and system/HTTP/File/UploadedFile. Both are having move() method which intend to move the file from one location to another.
But both methods have different implementation.
Is there any reason for the same.
Also both classes have similar type of methods, they why we are not extending one from other?

**Comment by lonnieezell** [comment]
I believe the primary reason was to make use the extra checks and security built into PHP's [move_uploaded_file](https://secure.php.net/manual/en/function.move-uploaded-file.php). This also allows it to play nice with `safe_mode` or `open_basedir` restrictions that might be in place.
