### ISSUE TITLE
ValidationInterface run method $data attribute should be nullable

### ISSUE THREAD

**Issue by d4mn** [codeigniter4/CodeIgniter4#1833]
---
name: Improvement
---
**Describe the bug**
Some inetlisence engines gives me an error when i use `$vvalidation->withRequest($this->request)->run()` without any parameters because in the ValidationInterface $data attribute is not nullable or not not set with default.

**CodeIgniter 4 version**
Codeigniter 4 Beta 1

**Affected module(s)**
ValidationInterface 

**Expected behavior, and steps to reproduce if appropriate**
Intelisence should not show an error on this method without any attributes.
Proposed solution just to set empty array.
`public function run(array $data = [], string $group = null): bool;`

**Comment by atishamte** [comment]
Get the current copy of develop branch, this thing is fixed there.

**Comment by d4mn** [comment]
Damn i looked in issues but missed it. Sorry for that.
