### ISSUE TITLE
Controller response property overriding by ControllerResponse inPHPUnit 

### ISSUE THREAD

**Issue by Przem4S** [codeigniter4/CodeIgniter4#1834]
---
name: Controller response property overriding by ControllerResponse in PHPUnit
about: ControllerResponse instance overriding property of standard Controller in unit testing controller.

---

Code to reproduce:

Controller:
```
namespace App\Controllers;

class Home extends \CodeIgniter\Controller {
    function index() {
        $response = $this->response->setJSON([
            'lang' => $this->request->getLocale()
        ]);
    }
}
```
ControllerTest:

```
<?php

namespace Tests\Controllers;
use CodeIgniter\Test\ControllerTester;
use CodeIgniter\Test\CIDatabaseTestCase;

class HomeTest extends CIDatabaseTestCase {

    use ControllerTester;

    public function testIndex() {
        $result = $this->withURI('http://example.com/rest/')
          ->controller(\App\Controllers\Home::class)
          ->execute('index');
    }
}
```

 - OS: Win 7
 - XAMPP
 - 7.2

**Comment by lonnieezell** [comment]
What is that supposed to test? Your test doesn't show it actually testing the response lang that you set. 

But also - what are you doing with the $response in the controller? Unless you return a redirect response instance from the controller method, the system is designed to work with the Controller's response. 

So I'm confused what the bug actually is here and how you're confirming that.

**Comment by Przem4S** [comment]
Okay, code have only block's to show error.

Full test:
```
public function testIndex() {
        $result = $this->withURI('http://example.com/rest/')
          ->controller(\App\Controllers\Home::class)
          ->execute('index');

        $response = json_decode($result->getBody());
        $this->assertEquals('pl', $response->message);
 }
```

Full controller method:

```
function index() {
        $response = $this->response->setJSON([
            'lang' => $this->request->getLocale()
        ]);

        return $response;
}
```

Error in PHPUnit:
![test](https://user-images.githubusercontent.com/37654401/54364287-dd04c380-466c-11e9-8a65-195be2374fb5.PNG)

**Comment by Przem4S** [comment]
That's Throwable error from ControllerTester.php:

![test](https://user-images.githubusercontent.com/37654401/54364456-3f5dc400-466d-11e9-9c7b-4f544b9270d8.PNG)

**Comment by jim-parry** [comment]
I have fixed this, but there is also a problem with your test.

>         $response = json_decode($result->getBody());
>         $this->assertEquals('pl', $response->message);

After json_decode, $response is an associate array, with a 'lang' key. There is no "message" property or key.
