### ISSUE TITLE
Events.php on method $callable parameter accepts only callable

### ISSUE THREAD

**Issue by d4mn** [codeigniter4/CodeIgniter4#1835]
---
name: Bug report
about: Help us improve the framework by reporting bugs!

---

**Describe the bug**
All these methods: 
 *  Events::on('create', 'myFunction');               // procedural function
 *  Events::on('create', ['myClass', 'myMethod']);    // Class::method
 *  Events::on('create', [$myInstance, 'myMethod']);  // Method on an existing instance
Throws an error because argument $callable in function `public static function on($event_name, callable $callback, $priority = EVENT_PRIORITY_NORMAL)` must be of type callable string and array throws an error

**CodeIgniter 4 version**
Codeigniter 4 beta 1

**Affected module(s)**
Events.php

**Expected behavior, and steps to reproduce if appropriate**
method should not be strict checked in functions attribute

**Context**
 - OS: Debian
 - Web server nginx 1.15
 - PHP version  v7.3.2

**Comment by d4mn** [comment]
I tried to look deeper into this and found this article https://wiki.php.net/rfc/consistent_callables First example of problem i think is it

**Comment by bangbangda** [comment]
I tested it, is OK. @d4mn 
```
$testEvent = new \App\Libraries\TestEvent();
Events::on('pre_system', [$testEvent, 'hello']);
```
```
class TestEvent
{
    public function hello()
    {
        log_message('debug', 'TestEvent hello....');
        return true;
    }
}
```

**Comment by atishamte** [comment]
Is it working as expected?
