### ISSUE TITLE
Controller in folder - method not accessible unless I set a route on Linux - Windows OK 

### ISSUE THREAD

**Issue by daljit3** [codeigniter4/CodeIgniter4#1841]
I have got a test site setup on my local Windows system and same site uploaded on a server with Ubuntu. 

On my local - URLs  `mysite/admin/home/upload` and `mysite/admin/upload` both work fine.
 
However, on my Ubuntu server, `mysite/admin/home/upload` throws up 404 error saying `Controller or its method is not found: App\Controllers\Admin::home` [i.e. its looking for an admin controller and it's home method rather than Home controller in an admin folder] 
I don't have any issues with `mysite/admin/upload` as I believe the route below is parsing correctly. 

What's going wrong here? Here are my routes.

```
$routes->setAutoRoute(true);

$routes->group('admin', ['namespace' => 'App\Controllers\admin'], function($routes)
{
    $routes->add('/', 'Home::index', ['as' => 'admin.home']);
    $routes->add('upload', 'Home::upload', ['as' => 'admin.upload']);
});
```

**Comment by daljit3** [comment]
Just to add into the above - On Ubuntu server, if the controllers at App/Controllers dont have any  issues i.e. I am able to access with `mysite/controllername/methodname` or `mysite/route-name` without any issues. So it's an issue with folders only.

**Comment by lonnieezell** [comment]
The namespace segments (and their respective folders) are expected to be `ucfirst`. Here's an article I wrote up on [namespaces in CI4](https://www.patreon.com/posts/primer-4-19847047).
