### ISSUE TITLE
FileLocator->getNamespaces with parameter

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#1866]
I'm working on an updated MigrationRunner that uses FileLocator to support external PSR4 sources. The `getNamespaces($prefix)` method flattens the return from `$autoloader->getNamespace($prefix)` to a single path, when it is actually an array of paths thus potentially causing `getNamespaces()` to fail to search some valid paths. AFAIK this method is only used by `locateFile()` so is probably safe to rewrite, but seeking advice first.

**Comment by lonnieezell** [comment]
I see 4 uses of it, but all of them are functions within the FileLocator class so you should be fine to modify that as long as all of those other methods don't break: 

- findQualifiedNameFromPath
- listFiles
- locateFiles
- search

**Comment by atishamte** [comment]
@MGatner, any update on this?

**Comment by MGatner** [comment]
I haven't looked into it at all

**Comment by MGatner** [comment]
Looked at this some more, definitely a potential issue. Some packages (like "phpDocumentor\Reflection") define multiple paths for one namespace:

```
["phpDocumentor\Reflection"]=>
  array(3) {
    [0]=>
    string(84) "/var/www/vhosts/.../vendor/composer/../phpdocumentor/reflection-common/src"
    [1]=>
    string(86) "/var/www/vhosts/.../vendor/composer/../phpdocumentor/reflection-docblock/src"
    [2]=>
    string(80) "/var/www/vhosts/.../vendor/composer/../phpdocumentor/type-resolver/src"
  }
```

Using `$locator->locateFile()` will only search the first of these ('reflection-common') and thus fail to match any files in the other paths.

**Comment by MGatner** [comment]
Also, namespaces aren't required to start with a capital ("phpDocumentor" above is a good example again) so this will fail to match sometimes:

https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Autoloader/FileLocator.php#L118

**Comment by MGatner** [comment]
Close by #2059
