### ISSUE TITLE
Class 'CodeIgniter\Filters\DebugToolbar' not found

### ISSUE THREAD

**Issue by ManojKiranA** [codeigniter4/CodeIgniter4#1871]
---
**Describe the bug**
i have installed the CodeIgniter4 with composer 
after the successful installation  i have fired the dev server  by 

`php spark serve --port 8001`

But When i load the `http://localhost:8001/` in browser 

i am getting error as

> Class 'CodeIgniter\Filters\DebugToolbar' not found

After i have tried the manual installation by dowloading the latest releases from the 

[Release Link](https://github.com/CodeIgniter4/framework/releases)

**Context**
 - OS: [Windows 10 pro]
 - Web server [Apache/2.4.38 (Win64)]
 - PHP version [7.2.16]

**Comment by rino7** [comment]
I had The same problem. It was fixed after run "composer update"

**Comment by jim-parry** [comment]
@ManojKiranA Does composer update indeed solve the issue for you?

**Comment by jim-parry** [comment]
I will take the lack of a response as a yes. We have successfully run it.

**Comment by TIWDev** [comment]
I note this issue has been closed, but having undertaken a fresh installed of CI4.0.0-Beta3 last night, the issue does remain.  Running composer update cleared it.

**Comment by Pensare** [comment]
Yesterday I installed CI4 and everything went wlll. This morning I installed it on another machine, and got the message 
`'CodeIgniter\Filters\DebugToolbar' not found`

tried composer update as suggested but it didn't help. The folder filter didn't have the Toolbar.php file, after copying it from the yesterday installation the error disappeared.

**Comment by MGatner** [comment]
@TIWDev @Pensare how did you do the initial install?

**Comment by Pensare** [comment]
I used 
`composer create-project codeigniter4/appstarter project-root -s beta`
after it was created I used
`composer update`

I just tried it again (deleted the project) and now it works well, might have done something stupid myself but not sure because I think I did all the same steps.

**Comment by MGatner** [comment]
I ran those commands and **DebugToolbar.php** is there and functional. It definitely seems like there is something fishy here, but not necessarily replicable.

**Comment by TIWDev** [comment]
@MGatner I think it would have been the same composer command that @Pensare used.  It was a fresh install - I hadn't had CI4 on the machine before, and was definitely done via Codeigniter, so I would simply have followed the instructions.

I have another machine here (which has never had CI4 on it) I can try and install it again if that helps.

**Comment by niranjnn01** [comment]
I took had the same problem today . It was fixed when running "composer update"
