### ISSUE TITLE
Error when running `php spark serve` (spaces in folder names)

### ISSUE THREAD

**Issue by louisl** [codeigniter4/CodeIgniter4#1880]
I was following the Dev Starter installation and noticed a little gotcha when running `php spark serve`.

If you have any folder with spaces in it leading up to the project you get an error from the `passthru` function in `system/Commands/Server/Serve.php`.

So If our path is `/Users/louis/Documents/CodeIgniter Tests/codeigniter4test/devstarter`.

We get the error due to unescaped spaces:-

`Directory /Users/louis/Documents/CodeIgniter does not exist.`

I've figured out this can fixed by adding `escapeshellarg` to the paths being supplied to that command. Ref https://www.php.net/manual/en/function.passthru.php

```
// Set the Front Controller path as Document Root
$docroot = escapeshellarg(FCPATH);

// Mimic Apache's mod_rewrite functionality with user settings
$rewrite = escapeshellarg(__DIR__ . '/rewrite.php');
```

I'll send A PR as soon as I get my CodeIgniter4 git fork properly set up, unless someone wants to slip it in.

CodeIgniter: Version 4.0.0-beta.1
PHP 7.2.14
Mac OS 10.14.3

Next job - fix the coding-standard, sorry been soooooo busy!

**Comment by mierol16** [comment]
Fatal error: Uncaught Error: Class 'CodeIgniter\Autoloader\FileLocator' not found in C:\Users\M!3R0L\Desktop\framework-4.0.4\system\Config\BaseService.php:171
Stack trace:
#0 C:\Users\M!3R0L\Desktop\framework-4.0.4\system\Common.php(539): CodeIgniter\Config\BaseService::locator(true)
#1 C:\Users\M!3R0L\Desktop\framework-4.0.4\system\bootstrap.php(167): helper('url')
#2 C:\Users\M!3R0L\Desktop\framework-4.0.4\spark(44): require('C:\\Users\\M!3R0L...')
#3 {main}
  thrown in C:\Users\M!3R0L\Desktop\framework-4.0.4\system\Config\BaseService.php on line 171

This is the error I get when run 'php spark serve'. Can you identify the error?
