### ISSUE TITLE
Validation Always Print Error Message

### ISSUE THREAD

**Issue by rmcdahal** [codeigniter4/CodeIgniter4#1903]
Here is my Controller 
`public function pagecreate()
    {
        $validation = $this->validate([
            'title' => 'required',
            'content' => 'required'
        ]);
        if (!$validation) {
            $data['page_heading'] = 'Create New Page';
            $data['content_view'] = 'Backend/Pages/Create';
            echo view('Backend/Themes/Base', $data);
        } else {
            $this->model->save(
                [
                    'title' => $this->request->getvar('title'),
                    'content' => $this->request->getVar('body')
                ]
            );
            return redirect()->to('');
        }
    }`

Here is my Views
`<div class="row">
    <div class="col-md-12">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><?php echo $page_heading; ?></h4>
            <?= service('validation')->listErrors() ?>
            <?php echo form_open('admin/pages/create'); ?>
            <div class="form-row">`

And issue is Views always print validation error message , 
The title field is required.
The body field is required.
Is there any problems with my code ?

**Comment by jim-parry** [comment]
Support questions should be asked on the [forum](https://forum.codeigniter.com/index.php), thanks. We use github for bug tracking.
When you post the question, include the view which presents the form being validated, and remember to use [code]...[/code] tags so your sources are readable.
