### ISSUE TITLE
Problem with extending core class.

### ISSUE THREAD

**Issue by enix-app** [codeigniter4/CodeIgniter4#1922]
### Description/Detail

I want to extend `CodeIgniter\View\View` class with additional methods.
I'm using view layouts.

```php
<?php

class MyView extends \CodeIgniter\View\View {

    public function asset()
    {
        //....
    }
}
```

`app/Config/Services.php` file:

```php
<?php namespace Config;

use CodeIgniter\Config\Services as CoreServices;
use CodeIgniter\Config\BaseConfig;

require_once SYSTEMPATH . 'Config/Services.php';

class class Services extends CoreServices
{
    public static function renderer($viewPath=null, $config=null, bool $getShared=true)
    {
        if ($getShared)
        {
            return static::getSharedInstance('renderer', $viewPath, $config);
        }

        if (is_null($config))
        {
            $config = new \Config\View();
        }

        if (is_null($viewPath))
        {
            $paths = config('Paths');
            $viewPath = $paths->viewDirectory;
        }

        return new \MyView($config, $viewPath, static::locator(true), CI_DEBUG, static::logger(true));
    }
}
```

In my view file, shared instance always return `\CodeIgniter\View\View` class, not `MyView` class.

`app/Views/sample.php` file:

```php
<?php

// Error: Call to undefined method CodeIgniter\View\View::asset()   
$this->asset();

```

My solution is simple, only move `CodeIgniter\Config\BaseService::getSharedInstance()` to `Config\Services::getSharedInstance()`.

Any idea? Thanks.

### Version

CodeIgniter 4.0.0-beta-2

### Affected module(s)

Config services files.

**Comment by lonnieezell** [comment]
Changing the location of that method will only break functionality and not solve anything. 

This isn't a bug, though, so should be asked on the forums. 

Bigger question is, though - why are you extending Config\Services? That file is there for you to edit. That's it's sole purpose.
