### ISSUE TITLE
Unable to use _remap without default method in controller

### ISSUE THREAD

**Issue by krishnan57474** [codeigniter4/CodeIgniter4#1928]
**Describe the bug**
A controller with method other than _remap
creates error in routes toolbar collector.

**CodeIgniter 4 version**
CodeIgniter4 Beta 0.0.2

**Affected module(s)**
system\Debug\Toolbar\Collectors\Routes.php

**Expected behavior, and steps to reproduce if appropriate**

1. Set CodeIgniter environment to development
2. Rename index method to _remap in app/Controllers/Home.php
3. run

You get method not exists error.

The following statement in system\Debug\Toolbar\Collectors\Routes.php:

        $method    = is_callable($router->controllerName()) ? new \ReflectionFunction($router->controllerName()) : new \ReflectionMethod($router->controllerName(), $router->methodName());

Calling **\ReflectionMethod($router->controllerName(), $router->methodName())** without method_exists check
causes method not exists error.

**Fix**

        $method    = is_callable($router->controllerName()) ? new \ReflectionFunction($router->controllerName()) : new \ReflectionMethod($router->controllerName(), method_exists($router->controllerName(), '_remap') ? '_remap' : $router->methodName());

**Comment by jim-parry** [comment]
Unable to reproduce this specific problem.
Applying the proposed solution breaks ControllerTesterTest, which expects an index() method.
The user guide says that index() *is* the default method, hence it seems reasonable that not having it, whether or not you have a _remap(), would cause problems.
