### ISSUE TITLE
Model set $escape problem

### ISSUE THREAD

**Issue by arkananta** [codeigniter4/CodeIgniter4#1929]
It's look like if I use more than one SET, I can't use different $escape value.

$this->set('tanggal_transaksi', $data['tanggal_transaksi'], true)->set('balance', 'balance + ' . $data['amount'], FALSE)->where('user_id',$data['user_id'])->update();

generate this query

UPDATE `transaksi` SET tanggal_transaksi = 2019-04-09, balance = balance + 0.1 WHERE `user_id` = '12'

In this case I need tanggal transaksi to be escaped, and balance are not esacpe

**Comment by jim-parry** [comment]
Can you provide a more complete example please.
What do you expect the outcome to be above?
Where does different $escape values come into play?

**Comment by michalsn** [comment]
I couldn't reproduce it. But I added a test to make sure.

**Comment by MGatner** [comment]
Michal's tests have proven consistent and this appears to have been a misunderstanding, or at least is no longer an issue.
