### ISSUE TITLE
Updating appstarter with composer does not take composer.phar into account

### ISSUE THREAD

**Issue by Tilogorn** [codeigniter4/CodeIgniter4#1932]
When you use composer via `composer.phar` (see [installation instructions](https://getcomposer.org/download/)) you get an error during `composer update` due to a "wrong" `post-update-cmd` in `composer.json` because you didn't install `composer` as a globally available binary/script.

Steps to reproduce
```
$ php composer.phar create-project codeigniter4/appstarter -s beta --no-dev
Installing codeigniter4/appstarter (v4.0.0-beta.2)
[...]
$ cd appstarter
$ php ../composer.phar update --no-dev
Loading composer repositories with package information
Updating dependencies
Generating autoload files
> composer dump-autoload
sh: 1: composer: not found
Script composer dump-autoload handling the post-update-cmd event returned with error code 127
```

The line producing the error in `composer.json` is:
```
{
    ...
    "scripts": {
        "post-update-cmd": [
            "composer dump-autoload"
        ]
    },
    ...
}
```
Changing this line to `php ../composer.phar dump-autoload` leads to a successful update in my use-case (`composer.phar` above project root).

I don't know how to resolve this. Maybe composer has information on how it was started? Or there is a more generic way to call `composer` in composer.json.

**While writing this issue, I found a solution**: I found [this](https://getcomposer.org/doc/articles/scripts.md#calling-composer-commands). Replacing `composer` with `@composer` works in my test case. Has to be tested with a regular, global composer installation.

**Comment by jim-parry** [comment]
Your description does not sound like globally installed composer, which would then be accessible as "composer" or "php composer.phar" anywhere. It sounds more like you have a local install in the folder you first run it from.
Having said that, the "@composer" modification you refer to does sound like a better approach, and we can fix that
