### ISSUE TITLE
Appstarter is not working after installation

### ISSUE THREAD

**Issue by rino7** [codeigniter4/CodeIgniter4#1941]
**Describe the bug**
When appstarter installation is finished, a blank page is displayed instead Welcome Home. 
It's not an error 500, it think is related to the output buffer.

**CodeIgniter 4 version**
CI4-beta.2

**Affected module(s)**
Views

**Expected behavior, and steps to reproduce if appropriate**
The expected behavior is see the Welcome Page (and/or other pages)

The steps to reproduce the issue are:

1) Run 'composer create-project codeigniter4/appstarter my-project -s beta'
2) Update Config/App.php with the regarding $baseUrl and remove $indexPage value
3) When you try to access via browser to the site, you will get a blank page. 

As previously said: The problem is in Config/Events.php
For some reason,in https://github.com/codeigniter4/CodeIgniter4/blob/develop/app/Config/Events.php#L25, if I change _ob_end_flush()_ by _ob_get_clean()_ or _ob_end_clean()_ the problem is solved. I don't know why, since both function do similar stuff.

**Context**
 - OS: Debian on Docker Container (Host Machine: Windows 10)
 - Web server [Apache 2]
 - PHP version [7.3]

**Comment by jim-parry** [comment]
There is/was a slight dependency mismatch (alpha instead of beta), and you might have to "composer update" after first install to bring everything up to speed.
The symptom of the dependency is an exception about the DebugToolbar. Check your log file.
This has been updated in the appstarter repo, and the release recreated, but packagist isn't picking it up, and may not until the next beta or rc.

**Comment by rino7** [comment]
I run the 'composer update' after install (forget to include it in the step to reproduce the issue) and the problem persists.
I checked my logfile and there's nothing related. 
Also, I don´t get an error 500 nor warning nor notice, so there's nothing to log.
What was the updates introduced in the repo to fix this? Is there a commit to check in order to reproduce manually these changes in my local repo and test if they solve my problem?

**Comment by jim-parry** [comment]
I manually updated the dependency in the appatarter composer.json.
The appstarter is only generated when we do a release, so there is nothing testable like that.
I cannot recreate the error you describe here, but I do show an exception in the debug toolbar until the composer update.

**Comment by rino7** [comment]
Okay, in my case I can't see neither debug toolbar.
