### ISSUE TITLE
base_url() value dropped between namespaces

### ISSUE THREAD

**Issue by jkiser99** [codeigniter4/CodeIgniter4#1942]
Creating modules, but when returning from a module,  return->response->to (base_url('/'))  fails because base_url() in other namespace is blank.

Sample code:
App/Config/App.php:       public $baseURL = 'http://localhost/ci4/'; 

Route:   $routes->add( '/', 'App/Controllers/Home::index');

App/Controllers/Home.php:
if (!$security['logged_in']) $this->response->redirect(base_url('login'));

Auth/Controllers/Login.php:
// Login form is processed and all is good.  Return to Home now.
$this->response->redirect(base_url("/"));  ===> goes to 'http://localhost/' = not routed
$this->response->redirect(site_url("/"));  ===> goes to 'http://localhost/ci4/'  = worked

**Comment by jim-parry** [comment]
It sounds like this is working as expected.
base_url() doesn't include the "url_suffix" by design, which is the "ci4" segment in your example.
