### ISSUE TITLE
Feature: FK Constraint Enable/Disable

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#1964]
Managing foreign keys with database migrations in Forge is currently a big pain because foreign keys will prevent drops, not display the problem key, and leave a migration partially executed.

Please add `enableForeignKeyConstraints()` and `disableForeignKeyConstraints()` methods to Forge, specifically for migrations `down()` but also good to have generally.

**Comment by lonnieezell** [comment]
Thanks for adding that request :)

**Comment by MGatner** [comment]
Welcome! Full disclosure world: this was @lonnieezell's idea ;)
