### ISSUE TITLE
View Parser site_url not works?

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#1995]
I'm using the view parser library and I have a problem calling a plugin.

In the documentation it says that it is enough to put this fragment of code to obtain the url of the site

`{+ site_url "login" +}`

But when using it nothing happens is a bug? or is there something missing to configure?

**Comment by lonnieezell** [comment]
Looks like the docs are wrong for that. It should be: `{+ siteURL +} ` instead of `{+ site_url +}`. 

I'll get that changed. Thanks!
