### ISSUE TITLE
View Parser Register Plugins as closures not works!

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#1997]
Hello! 

I tried to register custom plugins as closures according to the documentation but there seems to be an error:

```php
public $ plugins = [
    'foo' => '\ Some \ Class :: methodName',
    'bar' => function ($ str, array $ params = []) {
                 return $ str;
    },
]
```
Technically this could not be done since they are registered in a public variable of the class and they are not allowed to implement values that depend on information at runtime to be evaluated.

Therefore in the past example only the plugin declared in 'foo' would work.

Regards!

**Comment by lonnieezell** [comment]
You're right - the docs are incorrect there. I'll update. 

I can confirm that using a plugin as closure does work, though. You can add it in the constructor of that config class. When using a plugin that does not operate as a pair and only operates on parameters inside the tag itself, you wouldn't have a `$str` argument - only the `$params` array: 

```
$this->plugins['bar'] = function(array $params = []) {
    return $params[0] ?? '';
}
```
