### ISSUE TITLE
Paths issue when moving Views outside of app folder

### ISSUE THREAD

**Issue by desttools** [codeigniter4/CodeIgniter4#1998]
When using app/config/Paths.php to set a $viewDirectory, my application is always pulling from app/Views regardless of the setting used here.

I'm seeing this in CI4, beta 3

**Comment by truelineinfotech** [comment]
@desttools can you provide some more information? If possible

**Comment by desttools** [comment]
Sure @truelineinfotech  

The setup I'm trying to get working is using composer to install CI4 system and another repo with my app folder. The Views folder I want to use is outside of the app folder and at my base directory
`/Views
`
My index.php file is located here as you would expect:
`/public/index.php
`
The line in that file that points to my app folder's Paths file is:
`$pathsPath = FCPATH . '../vendor/desttools/myapp/app/Config/Paths.php';
`
Inside the Paths.php file, I'm setting the Views path like this:
`public $viewDirectory = __DIR__ . '/../../../../../Views';
`
And the path to the system:
`public $systemDirectory = __DIR__ . '/../../../../codeigniter4/framework/system';
`
Despite these settings, it's only recognizing the default Views directory inside the app, located at:
`/vendor/desttools/myapp/app/Views
`
Not 100% sure this isn't a misconfiguration on my part, but it's seeming like a bug at the moment.

**Comment by lonnieezell** [comment]
@desttools did you get this resolved? I'm looking through the code and I think it's respecting the view path everywhere.

**Comment by desttools** [comment]
Thanks @lonnieezell for taking a look. It was a learning curve issue on my part. My controller wasn't being called. I had changed the default controller in the Routes.php file (like CI3), but I didn't realize that the controller also needed to be explicitly set in $routes->get();

**Comment by lonnieezell** [comment]
No worries. Glad it's working for you!
