### ISSUE TITLE
validation match[x] don't work anymore... if custom setter is used.

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#2006]
In entity:
```
	public function setUsrPassword($value)
	{
//$this->usr_password 
		$this->attributes['usr_password'] = password_hash('my-password', PASSWORD_BCRYPT, ['cost' => 11]);
	}
```
in model:
```
		$this->validationRules['usr_password_1'] = 'required|matches[usr_password]';
```
I think it is because custom set is called now before validation... before last changes it was called before save action.

**Comment by nowackipawel** [comment]
Additionally 

this code in Entity:
```
	public function setUsrPassword($value)
	{
		$this->attributes['usr_password'] = password_hash( trim($value) . config('App')->salt, PASSWORD_BCRYPT, ['cost' => 11]);
	}
```
makes value $user_entity->usr_password  different every time.

**Comment by lonnieezell** [comment]
I'll look into the validation issue, but there's a simple fix for the second part you brought up: use a different field name. For example, in my auth stuff, I've got a field in the database called `password_hash` to be clear about what's being saved. Then in the Entity there is a `setPassword()` method which does the same as yours. However, it's setting the value of the `password_hash` column and that setter is only called if the password has been changed. 

If you save the password field (using your `setUsrPassword` method) then, yes, the hash will be different every time. That's how password_hash works.

**Comment by lonnieezell** [comment]
Custom sets will always be called on an Entity prior to validation if you're doing validation in the model. 

For certain things, like validating two fields that must match each other, that's best done in the controller before you try to save to database.
