### ISSUE TITLE
CodeIgniter\Entity Setter doesn't work 

### ISSUE THREAD

**Issue by Darkside-15** [codeigniter4/CodeIgniter4#2013]
Hi,

Impossible to use the CodeIgniter\Entity setter with the 4.0.0-beta.3 release while it works well
with 4.0.0-beta.1.

You can just run the example: 
https://codeigniter4.github.io/userguide/models/entities.html?highlight=entity#handling-business-logic to realize the malfunction.

```
public function setPassword(string $pass) {
        $this->password = password_hash($pass, PASSWORD_BCRYPT);

        return $this;
}
```

**Comment by iRedds** [comment]
A few days ago the logic of the Entity changed. Now the data is stored in the $attributes property.
Try this 
```php 
$this->attributes['password'] = password_hash($pass, PASSWORD_BCRYPT);
```
