### ISSUE TITLE
Wrong links for pager

### ISSUE THREAD

**Issue by penguinpower80** [codeigniter4/CodeIgniter4#2016]
When CI is running from a subdirectory, the pager links are incorrect and missing the subdirector(ies) in URI.

**CodeIgniter 4 version**
4.0.0-beta.2

**Affected module(s)**
PAGER

**Expected behavior, and steps to reproduce if appropriate**
Base url: http://mysite.com
CI in subfolder "ci/v4", so final url for site is "http://mysite.com/ci/v4/"

In view, calling "$pager->links()", using all other default settings, pagination links are:

<li><a href="http://mysite.com/<controller>/<view>?page=2">2</a></li>

and should be:

<li><a href="http://mysite.com/ci/v4/<controller>/<view>?page=2">2</a></li>

In my app.php AND .env file, I have app.baseURL set to "http://mysite.com/ci/v4/ 

If I run $page->setPath( 'ci/v4/<controller>/<view>' ) prior to output, then it is correct. but it hardcodes the uri which isn't desirable.
   

**Context**
 - Mac OSX 10.12.6
 - Apache 2.4.29
- PHP 7.2.17

**Comment by jim-parry** [comment]
Pagination does not use the baseURL property.
It is instead based on the current URL, i.e. the page you are on when the links are requested.
I have added additional unit tests to show that this is working as intended.
