### ISSUE TITLE
/System/Debug/Toolbar/Collectors/Routes.php on line 83	

### ISSUE THREAD

**Issue by dayrui** [codeigniter4/CodeIgniter4#2028]
SYSTEMPATH/Debug/Toolbar/Collectors/Routes.php : 83	  —  CodeIgniter\Config\Services::router	( arguments )

76      *
77      * @return array
78      * @throws \ReflectionException
79      */
80     public function display(): array
81     {
82         $rawRoutes = Services::routes(true);
83         $router    = Services::router(null,true);
84 

SYSTEMPATH/Config/Services.php at line 649

642      *
643      * @param \CodeIgniter\Router\RouteCollectionInterface $routes
644      * @param \CodeIgniter\HTTP\Request                    $request
645      * @param boolean                                      $getShared
646      *
647      * @return \CodeIgniter\Router\Router
648      */
649     public static function router(RouteCollectionInterface $routes = null, Request $request = null, bool $getShared = true)
650     {
651         if ($getShared)

**Comment by dayrui** [comment]
SYSTEMPATH/Debug/Toolbar/Collectors/Routes.php : 83
$router = Services::router(null,true);	
$router    = Services::router(null, null,true);

**Comment by dayrui** [comment]
@lonnieezell lonnieezell

**Comment by lonnieezell** [comment]
Typically it's good to say the problem you're seeing, not just leave it for me to decipher. 

I believe https://github.com/codeigniter4/CodeIgniter4/pull/2030 fixes it though.
