### ISSUE TITLE
force_https() doesn't redirect

### ISSUE THREAD

**Issue by hollax** [codeigniter4/CodeIgniter4#2033]
After setting  `public $forceGlobalSecureRequests = true;` in **Config/App.php** , I keep getting empty page response.

**Comment by MGatner** [comment]
What server software are you using?

**Comment by lonnieezell** [comment]
Are there any errors in the logs showing up?

**Comment by MGatner** [comment]
@lonnieezell I've actually replicated this on Apache/2.4.39 (cPanel), HTTP/1.1 - doing some digging.

**Comment by MGatner** [comment]
`force_https()` calls a clean exit before the headers are sent - PR incoming.

**Comment by hollax** [comment]
> What server software are you using?

Sorry for the late response

I am running **apache** on **Centos**
