### ISSUE TITLE
Modify Model's deleted field to be a date

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#2041]
I've been thinking about this a lot for the past few months, and I was in error to simply use a deleted (bool) field to represent soft deletions. Using a `deleted_at` field that is a date and treated the same as `created_at` and `updated_at` is how it should be done. This allows you to actually investigate *when*  it was deleted if you need to, without needing to build a complete action logging system. 

If this is going to happen, it has to be now, before the first RC.

**Comment by rino7** [comment]
I'm agree whit this point. I think we could use 'deleted_at' as flag field but also as a log field.

**Comment by MGatner** [comment]
I'm glad to work on this some, but it seems like a significant enough change that it might merit some collaboration. Could we maybe get a new branch for this?

**Comment by lonnieezell** [comment]
@MGatner I'm not sure it's completely necessary, but I have setup a new branch [over here](https://github.com/codeigniter4/CodeIgniter4/tree/deletedat) for you.

**Comment by MGatner** [comment]
Maybe it's overkill - when I first looked it seemed that this would need changes in a bunch of places but I don't have my head around the whole thing yet. I'll take a look soon.

**Comment by lonnieezell** [comment]
Cool. If you run into anything definitely let me know and I'll see what I can do.

**Comment by MGatner** [comment]
I think https://github.com/codeigniter4/CodeIgniter4/pull/2051 is ready to go for this. It didn't end up being nearly as big a change as I thought, but has a lot of downstream implications so I would appreciate a second set of eyes.

**Comment by lonnieezell** [comment]
@MGatner Thanks so much! I ran out of time to look at it last night. Very close. Just a couple of small items on it.
