### ISSUE TITLE
Model afterInsert return originals?

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2045]
Right now model event `afterInsert` returns "the original key/value pairs being updated" - which is a little ambiguous, it actually means the values you passed into `insert()` (including fields that didn't match `allowedFields`). While this info is somewhat useful, there is no way to determine what was changed, or even the original data (to perform a diff). I would like to see some way of passing either changed fields or the original fields.

**Comment by jim-parry** [comment]
Is this a feature request or a bug report?

**Comment by MGatner** [comment]
I think that's a question of intent. As a developer, the current behavior threw me off and I was unable to do what I expected with the event. But maybe that was my misunderstanding? It's hard to guess the scope of what model after insert events might need to do, but it makes more sense to me for the event to trigger with the *inserted data* rather than the *submitted data*.

**Comment by jim-parry** [comment]
Makes sense.
This could be treated as a feature request (BC), or as a bug (interpretation). I am not sure how much depends on it, or how many developers are using it as is.

**Comment by MGatner** [comment]
Hard to say! I know @lonnieezell has given Model some attention recently, if he has an opinion.

Either way, if this seems at least partway plausible I can start a PR. Think it's okay to proceed?

**Comment by jim-parry** [comment]
If this is indeed a BC, then I think it should wait. Let's see what Lonnie says.

**Comment by lonnieezell** [comment]
I think it's ok to proceed on this. When that portion of the model was originally created, there were a number of aspects with entities and the like that didn't exist yet, so things have been added on and looks like that was overlooked. But, yes, I believe it should be the data that was actually inserted.

**Comment by jim-parry** [comment]
@MGatner Are you thinking  of proceeding with this? Should it be removed from the rc.3 milestone?

**Comment by MGatner** [comment]
It's a small change, I've been swamped but I'll get it in shortly.

**Comment by MGatner** [comment]
Resolved with https://github.com/codeigniter4/CodeIgniter4/pull/2332
