### ISSUE TITLE
"Cannot call session save handler in a recursive manner"

### ISSUE THREAD

**Issue by Martin-4Spaces** [codeigniter4/CodeIgniter4#2056]
<img width="1578" alt="Screenshot_2019-06-14_at_09_23_07_png" src="https://user-images.githubusercontent.com/9819124/59492076-74ee9500-8e88-11e9-8498-509ba0cf937a.png">

Happens sometimes. Cannot give you a step-by-step guide to reproduce. 
This was also a problem in CodeIgniter 3. Check https://github.com/bcit-ci/CodeIgniter/issues/5545

I think the issue os that `filesize($this->filePath . $sessionID)` in `FileHandler::read` is returning a cached size. Check https://stackoverflow.com/questions/3747982/php-filesize-reporting-old-size 

Adding `clearstatcache()` before `filesize` should fix the issue.

**Comment by Winchester37** [comment]
Why use alpha 5 ? CodeIgniter 4.0.0-beta.3 you need to use it.

**Comment by MGatner** [comment]
Agree with @Winchester37 that you should upgrade to the latest version and try again. Also make sure you've read this: https://codeigniter4.github.io/CodeIgniter4/libraries/sessions.html#a-note-about-concurrency (which I assume you know, given your final comment, but for anyone else who finds this thread as well).

**Comment by Martin-4Spaces** [comment]
Forgot to mention. I did upgrade to beta.3 before posting this issue. No difference.

**Comment by faizananwerali** [comment]
Is it an error of maximum execution time? If yes then you should change it apache

**Comment by Martin-4Spaces** [comment]
@faizananwerali I think it is an error of infinite loop caused by cached filesize response. The maximum execution time is an effect of that error.

**Comment by rino7** [comment]
I faced a similar issue with sucessives ajax calls. I've worked around using session_write_close() function at the beginning of the method. But, I'm think that something is not working well.
I read the note about concurrency but have no sense destroy session as susggested because it logout me from the app.
