### ISSUE TITLE
FilterExceptions result in blank page

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2077]
**Describe the bug**
FilterExceptions are failing to load the exception page in development environment, but rather result in a blank page.

**CodeIgniter 4 version**
Branch `develop`

**Expected behavior, and steps to reproduce if appropriate**
Desired behavior is for any exception to display the callback trace and warning message to the developer. To reproduce add any invalid filter to **app/Config/Filters.php**, e.g.:
```
	public $filters = [
		'foobar' => ['before' => ['*']]
	];
```

**Comment by lonnieezell** [comment]
@MGatner we can close this, right?
