### ISSUE TITLE
Entity castAsJson returns an empty array

### ISSUE THREAD

**Issue by WarrenWN** [codeigniter4/CodeIgniter4#2080]
**Describe the bug**
Entity castAsJson returns an empty array

**CodeIgniter 4 version**
Codeigniter 4.0.0-beta.3

**Affected module(s)**
Entity

**Expected behavior, and steps to reproduce if appropriate**
I was testing the Entity class.

I called  `castAsJson('"{\"name\":\"test\",\"age\":0}"',$asArray=true)` and expected to get `['name' => 'test','age' => 0]`,but the function returned an empty array instead.

**Context**
 - OS: Ubuntu 18.04
 - PHP version 7.3

**Comment by nowackipawel** [comment]
I think everything is ok.
Just check difference between:
```
<?php

print_r(json_decode('"{\"name\":\"test\",\"age\":0}"'));
```
and
```
<?php

print_r(json_decode(json_decode('"{\"name\":\"test\",\"age\":0}"')));
```

**Comment by nowackipawel** [comment]
or just try to pass: `'{"name":"test","age":0}'` instead of `'"{\"name\":\"test\",\"age\":0}"'` to that method.

**Comment by WarrenWN** [comment]
Entity.php Line 591 `(strpos($value, '"') === 0 && strrpos($value, '"') === 0 )`

Seems we need to change the code above.

**Comment by nowackipawel** [comment]
This code will check if first and *last* char from the string is - `"`. Am I wrong?
I think one improvement for this place could be extending entire line:
` if ((is_string($value) && ((strpos($value, '[') === 0  && strrpos($value, ']') === 0) || (strpos($value, '{') === 0 && strrpos($value, '}') === 0) || (strpos($value, '"') === 0 && strrpos($value, '"') === 0 ))) || is_numeric($value)) `

As I said in my opinion for your parameter `'"{\"name\":\"test\",\"age\":0}"'` which is correct JSON STRING   function should return the string : `'{"name":"test","age":0}'` not an object/array.

**Comment by WarrenWN** [comment]
Well,actually `'{\"name\":\"test\",\"age\":0}"'` is a result that I got from MySQL DB

**Comment by WarrenWN** [comment]
And I thought the correct code was `(strpos($value, '"') === 0 && strrpos($value, '"') === strlen($value) - 1 )`

**Comment by nowackipawel** [comment]
you are right in this point.
