### ISSUE TITLE
README.md - Link to Announcement on Forums is a 404?

### ISSUE THREAD

**Issue by lloy0076** [codeigniter4/CodeIgniter4#2094]
This is pre-release code and should not be used in production sites.

More information about the plans for version 4 can be found in the announcement on the forums.

...

The link is to http://forum.codeigniter.com/thread-62615.html but that is a 404!

**Comment by MGatner** [comment]
The forums were recently updated and don't seem to support the same link styles. I believe the new link is https://forum.codeigniter.com/showthread.php?tid=71694 - I'll open a PR.

**Comment by MGatner** [comment]
It was actually https://forum.codeigniter.com/showthread.php?tid=62615

**Comment by jim-parry** [comment]
Holding off on changes to forum thread links until I get to the bottom of its misconfiguration.

**Comment by jim-parry** [comment]
This has been fixed at the source, and the forum is using the proper format links again :)
