### ISSUE TITLE
Fatal error Installing using composer

### ISSUE THREAD

**Issue by crysaro** [codeigniter4/CodeIgniter4#2114]
I got a fatal error in the browser after installing CodeIgniter using composer with the following command:
_composer create-project codeigniter4/devstarter my_project_name -s dev_
The error was:
`Fatal error:  require(): Failed opening required 'I:\\my_project_name\\app\\Config/../../vendor/codeigniter4/framework/system/bootstrap.php'
`
I checked the vendor folder and the "**framework**" folder **/vendor/codeigniter4/** is missing. I only saw  **/vendor/codeigniter4/codeigniter4/**.

I renamed the **/vendor/codeigniter4/codeigniter4** to **/vendor/codeigniter4/framework** and there were no more errors.

**Comment by rino7** [comment]
I think that is related with #1871 . Try running 'composer update'  and check if fix it

**Comment by crysaro** [comment]
Running 'composer update' did not fix it.
I created another test project.
`composer create-project codeigniter4/devstarter testproj -s dev`
After installing `cd testproj `
and run 'composer update' and there is still the error.

**Comment by MGatner** [comment]
This is because of https://github.com/codeigniter4/devstarter/issues/1, and it makes the devstarter unusable.

The quick fix is to open **app/Config/Paths.php** and change this line:
```
public $systemDirectory = __DIR__ . '/../../vendor/codeigniter4/framework/system';
```
to this:
```
public $systemDirectory = __DIR__ . '/../../vendor/codeigniter4/codeigniter4/system';
```
("framework" to "codeigniter4")

@jim-parry and I wrote about it a bit, but there's going to need to be a change to the release scripts in **admin/** in order to fix this.

**Comment by jim-parry** [comment]
devstarter is not created by the release scripts. I have updated its app/Config/Paths.php, which should fix the problem for new installs this way. Existing ones might need to manually update the path, as described aboce.

**Comment by jim-parry** [comment]
Not hearing anything contrary in 6 days, I presume the fix works.

**Comment by davido242** [comment]
Thanks Guyz

**Comment by FabricioPatrocinio** [comment]
I use linux, so this worked for me:
`composer update --ignore-platform-reqs`

**Comment by raghavendrapb** [comment]
I have getting the fatal error. after updating composer also getting same error. 

PHP Warning:  require(/opt/lampp/htdocs/ci4/app/Config/../../vendor/codeigniter4/codeigniter4/system/bootstrap.php): Failed to open stream: No such file or directory in /opt/lampp/htdocs/ci4/spark on line 46
PHP Fatal error:  Uncaught Error: Failed opening required '/opt/lampp/htdocs/ci4/app/Config/../../vendor/codeigniter4/codeigniter4/system/bootstrap.php' (include_path='.:/usr/share/php') in /opt/lampp/htdocs/ci4/spark:46
Stack trace:
#0 {main}
  thrown in /opt/lampp/htdocs/ci4/spark on line 46
