### ISSUE TITLE
Packagist not updated with latest release?

### ISSUE THREAD

**Issue by fijas** [codeigniter4/CodeIgniter4#2115]
Not sure if this is the right place to report this. It seems that [packagist](https://packagist.org/packages/codeigniter4/framework) is not updated with latest release? It stills shows v4.0.0-beta.3 as the latest version. I am not able update to beta 4 using `composer update`.

**Comment by jim-parry** [comment]
I presume you are referring to codeigniter4/framework?
The version on packagist has been corrected.
