### ISSUE TITLE
response data not set

### ISSUE THREAD

**Issue by psuplat** [codeigniter4/CodeIgniter4#2124]
Unless I am using it wrong it looks like the `response->setJSON` method is not working

I setup a very basic test controller as shown below:
```
class Foo extends BaseController
{

    public function bar()
    {
        $testData = [
            'success' => true,
            'id' => 123,
        ];
        $this->response->setStatusCode(401)->setJSON($testData);
    }
}
```
![image](https://user-images.githubusercontent.com/14207860/62826777-0dbc3b00-bbc2-11e9-8c46-4dd13e4d9b79.png)

When I run the url in Postman I get the response code I set but body is empty. Am I missing something?

**Comment by MGatner** [comment]
Can you try returning the response object?

**Comment by psuplat** [comment]
Crap, need new glasses. It works like a charm - developer issue, not framework ;)
