### ISSUE TITLE
Query Builder Class documentation

### ISSUE THREAD

**Issue by tangix** [codeigniter4/CodeIgniter4#2140]
Working with the Query Builder I see a couple of calls in the class reference not documented correctly. With sphinx up and running on my machine, would anyone mind me spending some time on fixing this?

**Comment by MGatner** [comment]
If you see something and have the capacity, please fix! That would be great help

**Comment by tangix** [comment]
Looking through the methods I see that many methods have a $test parameter to just return the SQL statement. None of the calls have this parameter documented so I wonder if this is on purpose or not.

**Comment by MGatner** [comment]
@tangix Testing could probably be handled better than with an additional parameter on every function. If you're working up a class reference maybe make a general mention of it but IMO it doesn't need to be listed on every method. Also note that the API docs will (eventually) cover some of the general "class reference" needs without having them fully defined in the User Guide: https://codeigniter4.github.io/api

**Comment by jim-parry** [comment]
This is too vague to br tagged for a milestone. Removing tag.

**Comment by jim-parry** [comment]
Fixed by #2269
