### ISSUE TITLE
Remove "separator" comment between function declarations?

### ISSUE THREAD

**Issue by andreportaro** [codeigniter4/CodeIgniter4#2146]
Hi all,

These comments appear throughout the codebase, and to me it is unclear why it is necessary.

```
	//--------------------------------------------------------------------
```

Some classes with only one method will use it:
https://github.com/codeigniter4/CodeIgniter4/blob/e609147fbc883a3d2ec35518fd822049ba5891fe/app/Config/Database.php#L112

Others won't:
https://github.com/codeigniter4/CodeIgniter4/blob/22c93a53123baf3d64fa3c45c3c005ae808736cd/app/Config/Modules.php#L56

The styleguide does not directly mention where or why such comment would be needed, but it does include one such "separator" on the docblock section.

I feel like it only adds visual bloat and the line breaks between function declarations should already be good enough visual cues, therefore such comments shouldn't be necessary.

I'm happy to create a PR for this if it's agreed upon.

**Comment by lonnieezell** [comment]
Those were a holdover from CI3. They're nice for quickly scanning files but not really necessary. My trend lately has been to leave them out. I'm fine with a PR to remove them.

**Comment by lonnieezell** [comment]
Nothing came of this so closing.
