### ISSUE TITLE
Migration migrate, rollback and create problems

### ISSUE THREAD

**Issue by muradmustafayev** [codeigniter4/CodeIgniter4#2147]
Nowadays trying Migration after @lonnieezell major refactor (08-11-2019, 10:22 PM).

Find out these problems: FYI @MGatner 

- If will be error (such as `Duplicate column name 'id'`) after call `php spark migrate` will be created tables and migration table stays empty.
- Because of the bug above when want to rollback there'll be no changes. 
- Refresh command also not working in this situation. Should drop tables manually and then run migrate again

**Comment by MGatner** [comment]
The old migrations table isn’t compatible and will definitely need to be dropped. The current revision has some implementation issues with the batches so there’s another version coming soon - I don’t recommend dedicating any efforts to the current state. If you need to use migrations in the meantime revert to beta.4.

**Comment by MGatner** [comment]
New migration logic is in place. Please update to the latest `develop` branch and try it again!

**Comment by MGatner** [comment]
https://github.com/codeigniter4/CodeIgniter4/pull/2137

**Comment by muradmustafayev** [comment]
This weekend i will give it a shot, thanks

**Comment by MGatner** [comment]
You are so right. Fix incoming.
