### ISSUE TITLE
Bug: Commands cannot accept many paths

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2148]
**Describe the bug**
Because CLI commands are actually routed their parameters go through some routing and filtering making it impossible to pass certain characters as a parameter. Of note that I ran into was trying to use a command that take a files path - the "/"s and "-"s cause it to be filtered and never arrives in `$params`.

**CodeIgniter 4 version**
Latest develop branch

**Affected module(s)**
CLI Commands

**Expected behavior, and steps to reproduce if appropriate**
Create a simple commands that calls `var_dump($params)` in `run()`. Call it:
`php spark test:command /usr/bin/myfile.txt`
Response is empty array.

**Context**
 - OS: Linux
 - Web server Apache
 - PHP version 7.2+

**Comment by jim-parry** [comment]
Have you tried quoting the offending string?
`php spark test:command "/usr/bin/myfile.txt"`

**Comment by MGatner** [comment]
Yes, it still routes it:
```
class Test extends BaseCommand
{
    public function run(array $params)
    {
		dd($params);
    }
```

```
$ ./spark test "/usr/tmp/bin"

CodeIgniter CLI Tool - Version 4.0.0-rc.1 - Server-Time: 2019-09-24 10:36:06am

│ $params │
array (4) [
    0 => string (0) ""
    1 => string (3) "usr"
    2 => string (3) "tmp"
    3 => string (3) "bin"
]

Called from .../app/Commands/Test.php:14 [App\Commands\Test->run()]
```

**Comment by jim-parry** [comment]
Not a bug. Slashes need to be url-encoded, i.e. %2fusr%2ftemp%2fbin
The parameter needs to then be urldecode(...) in your code to see the original string with slashes.

**Comment by MGatner** [comment]
Maybe "bug" isn't the correct term, but it's definitely a broken expectation. If I'm sitting at a shell prompt and want to call a command with a file argument I type `./command /path/to/file`. For `spark` to require HTML encoding for paths is pretty weird.

**Comment by lonnieezell** [comment]
Agreed, HTML encoding shouldn't be needed here.

**Comment by lonnieezell** [comment]
@MGatner have you had any more chance to look into this?
