### ISSUE TITLE
Return value of CodeIgniter\Database\BaseConnection::getConnectStart() must be of the type float, null returned

### ISSUE THREAD

**Issue by Martin-4Spaces** [codeigniter4/CodeIgniter4#2158]
This error occurs if I connect to a database group but never use it.

Ex.
```
$routes->get('issue', function() {
    $db = Database::connect('default');
    echo 'Nah, I dont need the connection anyway';
});
```

<img width="1333" alt="TypeError" src="https://user-images.githubusercontent.com/9819124/63405833-696b9d00-c3e8-11e9-89a3-0fbfd20858f3.png">

`connectTime` in BaseConnection is set when the first query is run. But Database::formatTimelineData will always call getConnectStart.

**Comment by michalsn** [comment]
I'm not able to reproduce this error using either develop branch or RC.1

**Comment by MGatner** [comment]
Me neither, tested with default and an additional DB connection with the debug toolbar collector on.

**Comment by Martin-4Spaces** [comment]
Me neither. Ty!

**Comment by Martin-4Spaces** [comment]
Aha!
I finally reproduced this issue using develop branch and RC.3.

If you connect to the database in a pre_system event, then toolbar will initialise with 1 database connection. And fail if the connection is never used.

app/Config/Events.php:
```
Events::on('pre_system', function() {
	Database::connect();
});
```
