### ISSUE TITLE
CLI: Exit status

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2163]
We need a way to control the return status of Commands run via Spark. Currently there is no way to indicate to a calling script if a command has encountered a failure without intercepting and parsing the output.

Example: Consider the deployment scenario where additional steps are taken after successful migration. Running `spark migrate` will fail or succeed with no indication in the return code. If MigrateCommand (and then `spark`) could return `1` then the next step in deployment could adjust accordingly.

**Comment by jim-parry** [comment]
Fixed by #2164
