### ISSUE TITLE
Feature idea: Model results by key

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2167]
So I end up doing this all the time, especially for ORM-like prefetching:
```
$results = [];
foreach ((new MyModel())->findAll() as $object)
{
	// Re-index by primary key
	$results[$object->id] = $object;
}
```
I'd like to find an efficient way to do this as part of the model (or builder?) but it creates some potentially-unintuitive scenarios when using `orderBy()` that you could have an array of results with numerical keys not in order. That said I think it could be worth it, but **BaseResult** is already iterating through the whole result set once so ideally it would happen there so it isn't happening twice:
```

		if ($this->resultObject)
		{
			foreach ($this->resultObject as $row)
			{
				$this->resultArray[] = (array) $row;
			}

			return $this->resultArray;
		}

		is_null($this->rowData) || $this->dataSeek(0);
		while ($row = $this->fetchAssoc())
		{
			$this->resultArray[] = $row;
		}
```

 Is this a bad idea for a core change to the framework?

**Comment by pjsde** [comment]
I think that is a good idea. 
Maybe by creating a flag for doing it or not in the getResult to leave the opportunity to the people that dont want it receive the result in the old way

**Comment by MGatner** [comment]
I've implemented a version of this in https://github.com/tattersoftware/codeigniter4-relations and joins can really make a mess of it. I had to add a toggle to turn it off since it would frequently drop join results. I'm not sure it is a good idea for the core framework anymore, though @pjsde's idea of making it a flag might work.

Closing for now.
