### ISSUE TITLE
[internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()

### ISSUE THREAD

**Issue by dayrui** [codeigniter4/CodeIgniter4#2173]
Maximum execution time of 100 seconds exceeded #0 
[internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()

**Comment by MGatner** [comment]
Thanks for reporting, but the info from the Bug Report template would be really helpful in troubleshooting this: https://github.com/codeigniter4/CodeIgniter4/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by lonnieezell** [comment]
Yes, we need more information around what you were trying to do when that error occurred. Code examples would be really helpful.
