### ISSUE TITLE
conflict between php zlib.output_compression and output buffering

### ISSUE THREAD

**Issue by mikemeadeuk** [codeigniter4/CodeIgniter4#2182]
**Describe the bug**
When zlib.output_compression is set to On in php.ini, CI4 cannot display any views and produces headers already sent errors.

**CodeIgniter 4 version**
CodeIgniter 4.0 RC1

**Affected module(s)**
/app/Config/Events.php
Removing this code in app/Config/Events.php, or turning off output_compression in php.ini is a temp solution.
```
while (\ob_get_level() > 0)
	{
		\ob_end_flush();
	}

	\ob_start(function ($buffer) {
		return $buffer;
	});
```

**Context**
 - OS: Centos 7
 - Web server: Apache/2.4.41
 - PHP version: 7.2.1

**Comment by jim-parry** [comment]
This sounds like a PHP problem, not a CodeIgniter one.
From https://www.php.net/manual/en/zlib.configuration.php:
"... a hard to spot gotcha when implementing zlib.output_compression. if you use flush() anywhere in your script (even right at the end) the compression won't work - you need to let that happen automatically or it ends up being sent uncompressed."
CodeIgniter view rendering and unit testing rely on output buffering, and flush().

**Comment by starchild** [comment]
Exactly the same issue for us too.

Surely not being able to use compression is a bad thing?

**Comment by misterhiggs** [comment]
Try this:
`Events::on('pre_system', static function () {
  
    if (ENVIRONMENT !== 'testing') {

       try {
           if (ini_get('zlib.output_compression')) {
            throw FrameworkException::forEnabledZlibOutputCompression();
        }

        while (ob_get_level() > 0) {
            ob_end_flush();
        }

        
        ob_start([fn($buffer) => $buffer]);
       } catch (Exception $ex) {
           // TODO code here
       }
    }`

**Comment by fordoscommerce** [comment]
@starchild https://preprocessor.space/questions/setting-up-context-in-php-a-detailed-guide
