### ISSUE TITLE
Can we use codeigniter 4 on live server??

### ISSUE THREAD

**Issue by humanyu** [codeigniter4/CodeIgniter4#2188]
Can we use CI 4 on live server??

**Comment by nowackipawel** [comment]
I know is not smart, but I'm using beta1 or alpha4 on one of my live
projects  which I won't update because of lot of changes which were made
later.
I saw  some attempts of hacking it but with no success.

**Comment by jim-parry** [comment]
Support questions should be asked on the forum, thanks.
We use github for bug tracking and work packages.
