### ISSUE TITLE
Fail to open system/bootstrap.php

### ISSUE THREAD

**Issue by muradmustafayev** [codeigniter4/CodeIgniter4#2193]
Time to time I see this warning when try install devstarter via Composer.
I run this command from documentation:
`composer create-project codeigniter4/devstarter my-awesome-project -s dev --no-dev`

Warning: require(E:\OSPanel\domains\localhost\magazine\app\Config/../../system/bootstrap.php): failed to open stream: No such file or directory in E:\OSPanel\domains\localhost\magazine\spark on line 43

**Comment by lonnieezell** [comment]
Does this happen every time? Sounds like just occasionally, which will make it a bugger to debug. Anything common on your end when that happens that you can think of?

**Comment by MGatner** [comment]
Also, it's unclear to me if you get that error *while* installing from `composer` (unlikely) or after having installed. And when you get the error, have you run `composer upgrade` first? or is this a fresh run after `install`?

**Comment by muradmustafayev** [comment]
It's fresh install.
I've tried composer ugrade, update with and without --no-dev flag. The result stays the same

I started try CI4 3-4 months ago. Since then had problem and moved to appstarter. But after Migration major update, started to use devapstarter with Composer and worked as expected. Now again this happening

![dev-error](https://user-images.githubusercontent.com/19308062/64597066-2177de80-d3c6-11e9-9410-87149d36f5f2.jpg)

**Comment by lonnieezell** [comment]
@jim-parry I feel we've ran into this before. The devstarter repo is pointing to the wrong `system` location again. Needs to point to `vendor/codeigniter4/codeigniter4/system`.

**Comment by jim-parry** [comment]
Just pushed a change to app/Config/Paths.php, which I thought I had fixed before but obviously didn't :(
Does "composer update" fix the problem now?

**Comment by jim-parry** [comment]
Actually, I am not sure that composer update will help, The change is in the devstart repo, which was probably cloned. That would mean pulling from it, which might clobber work a developer has done.
So, the problem may be fixed for new cloners of the repo, but existing ones might have to manually update app/Config/Paths.php

**Comment by jim-parry** [comment]
So, problem fixed for future users of devstarter; workaroung above for existing users.
