### ISSUE TITLE
Locals problems

### ISSUE THREAD

**Issue by testideah2** [codeigniter4/CodeIgniter4#2195]
Other localizations, except English default, return {field} without translate for validation form.

**Comment by michalsn** [comment]
I couldn't reproduce it.
I found only an error in the Russian translation file codeigniter4/translations#49

**Comment by testideah2** [comment]
> I couldn't reproduce it.
> I found only an error in the Russian translation file [codeigniter4/translations#49](https://github.com/codeigniter4/translations/pull/49)

Yes, this problem is due to incorrect localization.
I fixed this and added some missing files:
- Email.php
- Encryption.php
- RESTful.php
https://github.com/testideah2/Codeigniter-4-Russian-localization
