### ISSUE TITLE
Extending The Model

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#2223]
i dont really understand how this model really works besides the basic stuff that all frameworks has.

I can no longer make the business logic in the models 
I dont have a good example how an many to many relationship works.

Example : 
table : UserModel.
foreign_table : UserCommentsModel.

I need a way based on those two models somehow to retrieve all the info without recoding all the functions.

Do Codeigniter members agree that we need an ORM like MODEL ?
Or it is just me wanting this feature inside CI4 ?

**Comment by MGatner** [comment]
This is probably better suited for the forums, GitHub is for issues and bugs. I think the decision was that CI4 won’t have ORM as part of its core, but there are a couple projects to extend CI4 for such functionality. Here is one from the forums:

https://github.com/hlohrenz/CI4-Relationship-Query-Builder
