### ISSUE TITLE
ini_set() expects parameter 2 to be string, integer given

### ISSUE THREAD

**Issue by John-Betong** [codeigniter4/CodeIgniter4#2235]
Latest commit 957d674 19 hours ago

file: CodeIgniter4/app/Config/Boot/production.php

Statement conflicts with recommended ini_set(...) parameters
```
// line: #10
- ini_set('display_errors', 1);
+ ini_set('display_errors', '1');
```
### Edit:
Final line was truncated, added missing text.

**Comment by MGatner** [comment]
Probably as simple as `ini_set(‘display_errors’, ‘1’)`

**Comment by John-Betong** [comment]
@MGatner 
Is the submitted issue in the correct format to be easily merged?

If not please supply a sample.

**Comment by jim-parry** [comment]
Sample provided, just above :)
