### ISSUE TITLE
 DateTime::createFromFormat()  parameter incorrect

### ISSUE THREAD

**Issue by John-Betong** [codeigniter4/CodeIgniter4#2238]
# DateTime::createFromFormat() expects string, integer given

file: system/HTTP/Response.php

```  
// line # 717
-  $this->setDate( \DateTime::createFromFormat('U', time() ) );
+  $this->setDate( \DateTime::createFromFormat('U', (string) time() ) ); 
```

**Comment by pjsde** [comment]
\DateTime::createFromFormat expects a string in the second parameter, but if an integer is passed, internally converts that integer to a string and gives no error.

**Comment by John-Betong** [comment]
> \DateTime::createFromFormat expects a string in the second parameter, but if an integer is passed, internally converts that integer to a string and gives no error.

The PHP 7 Manual expects a string and if it is not then has to test and convert for all possible parameter types. 

Once the passed type is found ( array, bool, float, integer,  etc) then a nearest match conversion is used and hopefully is correct. The additional processing takes time and can be eliminated by passing the correct type or casting the passed parameter.

Currently this is neither an error or a warning but could change in the near future or if an option arises to have a compiled version then this would surely be an error.

**Comment by pjsde** [comment]
Ok. You're right. 
I thought the function was throwing an error. 
My mistake.
