### ISSUE TITLE
invalid switch parameter 

### ISSUE THREAD

**Issue by John-Betong** [codeigniter4/CodeIgniter4#2239]
# switch() parameter expects string, NULL given

file: system/HTTP/Request.php 
```
// line # 237 
- switch (strtolower($which) )
+  switch (strtolower( (string) $which) )
```

**Comment by jim-parry** [comment]
This is an "issue", not a "pull request". This isn't mergeable.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/CONTRIBUTING.md
You can also check the "pull requests" tab above, for examples.
