### ISSUE TITLE
$builder->like() not support for HAVING clause

### ISSUE THREAD

**Issue by Nudasoft** [codeigniter4/CodeIgniter4#2242]
Sometimes we have to use LIKE with HAVING clause. but $builder->like() only support for WHERE clause.

**Comment by lonnieezell** [comment]
You're correct. Unfortunately it does not support that particular combo. I don't believe CI has ever supported that, so it's not a bug, just a missing feature. We don't have plans to implement that at the moment (unless someone else jumps in and adds it) so for those queries you might have to use the `query()` method with binding to handle escapes for you.
