### ISSUE TITLE
Query grouping not working for HAVING clause

### ISSUE THREAD

**Issue by Nudasoft** [codeigniter4/CodeIgniter4#2247]
Query grouping is only working for WHERE clause. it's not working for HAVING clause. 

My question is why you guys introduced HAVING clause related methods like $builder->having(). whats the point? 

query grouping, like with having clause any of these things not working for having clause. only for where clause. 

Every time I tried to do something with this framework I hit a big wall. I was thought these prolems will get fixed in v4. but its looks like its same as v3.x. 

I tried to contribute and fix these issues. but that narfbg guy never wanted to things get fix.
https://github.com/bcit-ci/CodeIgniter/pull/5643

**Comment by lonnieezell** [comment]
Sounds like you guys were working toward a solution for a while, then it got abandoned. 

No worries, though, as @michalsn got your back this time.
