### ISSUE TITLE
_remap is not working

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#2277]
```
ReflectionException

Method App\Controllers\Api\V1::timestamp() does not exist
```
or:
```
Error

Call to undefined method App\Controllers\Api\V1::get_timestamp() 
```
occurs if some of two methods (one according to Routes and one according to _remap code is not available)

and the simpliefied code:
```
<?php namespace App\Controllers\Api;

use CodeIgniter\Controller;

class V1 extends Controller
{
    public function _remap($method, ...$params)
    {
        return $this->{'get_' . $method}();
    }

    public function get_timestamp()
    {
        return __METHOD__;
    }

    public function timestamp()
    {
        return __METHOD__;
    }
}

```
Anyway if two methods are exists only that one which its name is calculated in _remap returns something to the screen.
`App\Controllers\Api\V1::get_timestamp`

**Comment by jim-parry** [comment]
This doesn't sound like a bug.
Your remap will attempt get_get_timestamp() after remapping, giving the undefined method you show above, with the name before remapping.
Further your remapping ensures that timestamp() on its own will not be called.
The observed behavior is just what I would expect to happen.

**Comment by lonnieezell** [comment]
From [the docs](https://codeigniter4.github.io/CodeIgniter4/incoming/controllers.html#remapping-method-calls):

> If your controller contains a method named _remap(), it will always get called regardless of what your URI contains. It overrides the normal behavior in which the URI determines which method is called, allowing you to define your own method routing rules. 

So, yes, whatever is calculated in the remap method is the only thing that will be called.

**Comment by nowackipawel** [comment]
@lonnieezell I reckon I did not write something clear.
The problem is when in this class there is no method called "timestamp" I've got
```
ReflectionException

Method App\Controllers\Api\V1::timestamp() does not exist
```
I expect that only `get_timestamp()` calculated by `_remap()` will be called and it is, but `ReflectionClass` is also checking if `timestamp()` is callable and caused exception.

**Comment by lonnieezell** [comment]
You could have saved us some time if you would have reported the file the error was happening from - it's the Routes Collector for the debug toolbar. And there is an issue with the toolbar, but not with the actual routing. Working on a fix.

**Comment by nowackipawel** [comment]
@lonnieezell : I would love too but this issue was closed :/. I guess you've already checked it , but if not I will be happy to restore that file and upload screenshots with debug.
