### ISSUE TITLE
Version not updated?

### ISSUE THREAD

**Issue by John-Betong** [codeigniter4/CodeIgniter4#2287]
Can someone check to see if this version is correct - I thought the Hotfix should have been applied:

GitHub clone:
https://github.com/codeigniter4/CodeIgniter4.git

CodeIgniter4/system/CodeIgniter.php ==> const CI_VERSION = '4.0.0-rc.2';

**Comment by jim-parry** [comment]
The version still shows as rc.2, sorry.
The hotfix did not follow the normal release build process.
I have manually updated it in the repo.
