### ISSUE TITLE
Feature: model helper 

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#2292]
Create a new `model()` helper method that functions much like the `config()` help does that provides singletons of models.

**Comment by MGatner** [comment]
Is this a request for help or something you’re working on?

**Comment by lonnieezell** [comment]
Since we are in release candidate mode I just wanted it here as a reminder. :)

**Comment by jim-parry** [comment]
Shouldn't this be raised on the forum first, in a perfect world?

**Comment by lonnieezell** [comment]
Nope - we have always used this for feature planning also, not just bugs. And I didn't intend to raise this for discussion from the masses. :) This was just a reminder for me once we get out of feature-freeze and into new feature development again.

**Comment by jim-parry** [comment]
"Feature" is  part of the ambiguity I see creeping into the issues. Members are using it to raise and discuss proposals, which to me belong in the forum until we agree to add them. I think if we play a bit with the issue tempaltes, we will get it "right enough" :)

**Comment by MGatner** [comment]
Added via #2514
