### ISSUE TITLE
Model()->find() return NULL for existing row

### ISSUE THREAD

**Issue by Workoverflow** [codeigniter4/CodeIgniter4#2306]
**Direction**
Hi! I have faced with problem with Model()->find() and Model()->findAll(). If i call ones of this methods i get null. It's doesn't work after update to 4.0.0-rc.2.1 with composer.

![image](https://user-images.githubusercontent.com/11596112/66273897-45252c00-e881-11e9-8496-27b29e7bd7f8.png)

![image](https://user-images.githubusercontent.com/11596112/66273904-540bde80-e881-11e9-874c-3941cc972d88.png)

**Describe the bug**
Model()->find() and Model()->findAll() doesn't work.

**CodeIgniter 4 version**
4.0.0-rc.2.1

**Affected module(s)**
vendor/codeigniter4/framework/system/Model.php

**Context**
 - OS: MacOS 10.13.6
 - Web server Nginx
 - PHP version 7.2-fpm

**Comment by jim-parry** [comment]
The Model class has been extensively tested, and it is more likely that you are doing something wrong. Please raise this as a support thread on the foru, with code and not images ... enough code that someone can point out the problem.
Thanks.

**Comment by anRoswell** [comment]
Me pasa exactamente lo mismo, no return null a pesar de existir registros...
Exactly the same happens to me, returns null despite existing

**Comment by lonnieezell** [comment]
@anRoswell Your best bet is to ask for advice on the forums.
