### ISSUE TITLE
Feature: AJAX filters don't work

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2314]
**Describe the bug**
According to the User Guide on `$methods` in **app/Config/Filters.php**:
> In addition to the standard HTTP methods, this also supports two special cases: ‘cli’, and ‘ajax’.

However, I cannot find anywhere in the code that would run AJAX filters. Method is set in **system/Filters/Filters** with no clause for AJAX:
```
$method = strtolower($_SERVER['REQUEST_METHOD'] ?? 'cli');
if (array_key_exists($method, $this->config->methods))
```

Unless I've missed something, I think this isn't implemented, and my test Filter is definitely not firing on AJAX calls.

**CodeIgniter 4 version**
Latest develop

**Affected module(s)**
Controller Filters

**Comment by jim-parry** [comment]
No mention of CLI or AJAX filters other than that one sentence in the user guide.
They make sense, and it sounds like they might have been planned, but overlooked in implementation :(
Something to add once stable :)
