### ISSUE TITLE
autoRoute function issue in case of sub-directory

### ISSUE THREAD

**Issue by vargika** [codeigniter4/CodeIgniter4#2319]
If sub-directory is used in the controller, the CodeIgniter\Router class autoRoute function will be wrong, because the directory name will append again to the directory class variable. 
Have to set te directory variable to empty at the beginning of the function. 
(v4.0.0-rc.2.1)

**Comment by MGatner** [comment]
This was fixed with https://github.com/codeigniter4/CodeIgniter4/pull/2308 - please update to the latest version of `develop` branch.

**Comment by vargika** [comment]
No, that is not fix my issue.
for examle request path is: Cat/Citten/index
I call autoRoute with the same 'Cat/Citten/index'.
the value of the $controller variable will be: App\Controllers\Cat\Cat
and the $method will be: Citten

**Comment by MGatner** [comment]
I don't completely understand, but I will reopen the issue. Sorry for the peremptory closure.

**Comment by vargika** [comment]
sorry, I made a mistake. it can be closed.
