### ISSUE TITLE
View Cell Feature ?

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#2322]
About View cells.

We can use the view cells only for minimum unique content.

I hit this bump. I wanted to try the feature and now i am stuck.
I have for example

a view cell that all the content to be rendered if we already loaded some on other view cells.

This is because the Request class is not passed to the controller.

How can i get already loaded params from extended controller if this view cell don`t call the 
initController constructor. ?

Structure
BaseController
Home extends BaseController
[IN HOME] i use a VIEW 
inside that view i use view_cell(Front/Pricing)

This is very important because i already loaded inside the Home, so all view_cells needs to have this data. How can i get this data without sessions :( ?

Front/Pricing extends BaseController

**Comment by lonnieezell** [comment]
You have 2 options: 

1. pass the needed information into the cell as [parameters](https://codeigniter4.github.io/CodeIgniter4/outgoing/view_cells.html#cell-parameters).
2. Grab the current request instance with `service('request')` - that provides a singleton of the request with all of the information you may need.
