### ISSUE TITLE
Bug: Toolbar ErrorException  Division by zero

### ISSUE THREAD

**Issue by web-media** [codeigniter4/CodeIgniter4#2340]
CI_ENVIRONMENT development
**Describe the bug**
refreshing the index page multiple times or entering the same page  (index )multiple times throw
ErrorException Division by zero
also toolbar doesn't show  even when index page displayed correctly
![Capture2](https://user-images.githubusercontent.com/5124319/66963822-f8a5d180-f074-11e9-9634-e4dc45db98d5.PNG)

![Capture](https://user-images.githubusercontent.com/5124319/66963668-88974b80-f074-11e9-8107-310975c13cea.PNG)

```php
CRITICAL - 2019-10-16 17:29:28 --> Division by zero
#0 N:\a\htdocs\ci\system\Debug\Toolbar.php(121): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Division by zer...', 'N:\\a\\htdocs\\ci\\...', 121, Array)
#1 N:\a\htdocs\ci\system\Debug\Toolbar.php(352): CodeIgniter\Debug\Toolbar->run(1571264968.053, 0, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
#2 N:\a\htdocs\ci\system\Filters\DebugToolbar.php(74): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
#3 N:\a\htdocs\ci\system\Filters\Filters.php(187): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
#4 N:\a\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\Filters\Filters->run('/', 'after')
#5 N:\a\htdocs\ci\system\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 N:\a\htdocs\ci\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}


```

**CodeIgniter 4 version**
latest

**Context**
XAMPP for Windows 7.3.7
Apache/2.4.39 (Win64) OpenSSL/1.1.1c PHP/7.3.7
Windows NT PC 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) AMD64
PHP Version 7.3.7
and REQUEST_URI as the protocol.

**Comment by julesbl** [comment]
Tried reproducing this under spark server, seems to work without a problem bar displayed, no division by zero, so probably something in Windows or Apache.

My system
CodeIgniter Version: | 4.0.0-rc.3
-- | --
PHP Version: | 7.3.10-1+ubuntu16.04.1+deb.sury.org+1
PHP SAPI: | cli-server
Environment: | development
Base URL: | http://localhost:8080
TimeZone: | America/Chicago
Locale: | en
Content Security Policy Enabled: | No

**Comment by lonnieezell** [comment]
Cannot recreate. If someone else can feel free to reopen with more details.
