### ISSUE TITLE
Bug: URL, Redirect and Pagination misbehave

### ISSUE THREAD

**Issue by muradmustafayev** [codeigniter4/CodeIgniter4#2347]
I've similar problems as #2119 + some bonuses :)

I've deployed project to `test.com/e` and set `baseURL` from .env file. Issues are:

- Redirect:
1. `redirect()->to('uri')` function redirects to `test.com/uri` not `test.com/e/uri`
2. `redirect()->to('uri')` at localhost(spark serve) duplicates url when tries to redirect. But at server works as expected but with issue N1. At localhost I'm using with trailing slash to bypass the issue `->to('/uri')` 

- base_url misbehave: 
1. `base_url('uri')` -> `test.com/e/uri`.
2. `base_url('/uri')` -> `test.com/uri`. Should be `test.com/e/uri` I guess
3. `base_url() . 'uri'` -> `test.com/e/uri` (works but not a pretty solution)

- Pagination: `$pager->links()` creates `test.com/?page=2` instead of `test.com/e?page=2`

**Comment by muradmustafayev** [comment]
After RC3 update:

- Redirect:
2. `redirect()->to('uri')` at localhost not duplicates URL but at server redirects to 'test.com' not 'test.com/e'

Rest of stays the same. Please, fix routing and redirect issues. Because all these stuff for daily use. Without these too hard

**Comment by jim-parry** [comment]
Can you provide more information so we can help ...
- $baseURL setting
- context in which you call redirect, eg. the controller method code

**Comment by muradmustafayev** [comment]
- `app.baseURL = 'http://test.com/e/' ` from .env file

- The simplest example: when I want to go admin panel, it should redirect to login page (`test.com/e/admin/user/login`). But redirects to `test.com/admin/user/login` (without folder name `e`)

Post.php (controller)
```
public function index()
{
        if(!$this->isLoggedIn())
        {
            return redirect()->to('/admin/user/login');
            // return redirect()->to('admin/user/login'); // this also not working
        }
        // some code
}
```
