### ISSUE TITLE
Bug: lang('app.name') should prefer APPPATH.Language/Validation/en/app.php over installed packages

### ISSUE THREAD

**Issue by SunilEver** [codeigniter4/CodeIgniter4#2354]
**Describe the bug**
lang('app.name') should prefer APPPATH.Language/Validation/en/app.php instead of any package like 'vendor/vendorName/package/Language/en/app.php'
In APPPATH.Language/Validation/en/app.php
```
<?php
return [
    'name' => 'New App',
];
```
In 'vendor/vendorName/package/Language/en/app.php'
```
<?php
return [
   'name' => 'App',
];
```
Now `lang('app.name')` should return "New App" instead of "App"

**CodeIgniter 4 version**
v4.0.0-rc.3

**Affected module(s)**
CodeIgniter\Language\Language::class

**Expected behavior, and steps to reproduce if appropriate**
Language files in APPPATH should be given preference

**Context**
- OS: Ubuntu 16
- Web server Apache/2.4.18
- PHP version 7.3.9-1+ubuntu16.04.1+deb.sury.org+1

**Comment by MGatner** [comment]
Glad this issue already exists. See my notes on https://github.com/codeigniter4/CodeIgniter4/pull/2355 - I do think we need to find a way to do this but it needs to be more efficient (and signed, and pass tests).

Essentially it comes down to the return order of `Services::locator()->search($path)` (from **Language.php:302**) being statically: `System`, `Config`, `App`, `modules`. Language reverses this by `array_replace_recursive()` giving priority to the last matched language string.

IMO the correct search order for language strings should be: `App`, `modules`, `System`.
