### ISSUE TITLE
Bug: with the parser, nl2br in a foreach duplicates entries.

### ISSUE THREAD

**Issue by SteeveDroz** [codeigniter4/CodeIgniter4#2360]
**Describe the bug**
When using the parser, if a loop is made with `{elements}{/elements}`, the entries are doubled if a `nl2br` is used on an attribute of *elements*.

**CodeIgniter 4 version**
4.0.0-rc.3

**Affected module(s)**
Parser

**Expected behavior, and steps to reproduce if appropriate**
Given the following code in controller:

    public function bug()
    {
        $elements = [
            ['a' => 'foo'.PHP_EOL.'bar'],
            ['a' => 'baz'],
        ];
        return service('parser')
            ->setData([
                'elements' => $elements
            ])
            ->renderString('{elements}<p>{a|nl2br}</p>{/elements}');
    }

The result (with added newlines for readability) is:

```
<p>foo<br />bar</p>
<p>baz</p>
|
<p>foo<br />bar</p>
<p>baz</p>
```

Description:

- The `nl2br` works
- The `|` from `{a|nl2br}` is displayed
- The loop is called a second time after the `|`

**Context**
 - OS: Fedora 30
 - Web server Apache 2.4.41
 - PHP version 7.3.10

**Comment by SteeveDroz** [comment]
Hint: [this line](https://github.com/codeigniter4/CodeIgniter4/blob/ba6073210f89cd836d23f54341d59cd69040e447/system/View/Parser.php#L303) is where `replaceSingle()` is called one time too many.

**Comment by najdanovicivan** [comment]
I've found the issue will submit PR.
