### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#2361]
Always i have a bunch of times to insert a record if is not already inserted if a unique column. 

Can you guys make a function method to something like this in the model class

$model->where('id != ', $id)->insert($insert_data);

It is verry frustrating that i have to do always a get request to check if the record exists.

**Comment by crustamet** [comment]
I mean insert an record if a record do not already exist in the table by another column that the primary key.

**Comment by jim-parry** [comment]
Please open feature requests as a thread in https://forum.codeigniter.com/forum-29.html
