### ISSUE TITLE
Bug: current_url function not working as expected.

### ISSUE THREAD

**Issue by jayfortner** [codeigniter4/CodeIgniter4#2365]
**Describe the bug**
Using current_url function produces an unexpected result. 
Expecting accurate url, server root with uri string provided instead.
Screenshot attached.
![codeigniter-currenturl-bug](https://user-images.githubusercontent.com/23372238/67627558-68ae1780-f82c-11e9-8f13-541e9fc17fd5.jpeg)

**CodeIgniter 4 version**
Commit # a424b3e38d0da46ff86c56b2298d8d3f94fb1a26 of the `develop` branch.

**Affected module(s)**
URL Helper.

**Expected behavior, and steps to reproduce if appropriate**
Expected behavior:
 - Function should return URL as set in the App\Config\App.
EDIT: Actual expected behavior: the full URL (including segments) of the page where the function is executed. As pointed out by @dafriend .

Steps to reproduce: 
 - Call current_url in a view.

**Context**
 - OS: Mac OS X 10.13.6
 - Web server: Apache 2.4.33
 - PHP version: 7.2.14

**Comment by dafriend** [comment]
You might be confusing the function `current_url()` with `base_url()`.
`base_url()` is the one that returns the setting in App\Config\App

`current_url()` returns the full URL (including segments) of the page where the function is executed.

**Comment by jayfortner** [comment]
@dafriend Not confused. I just wrote a bad expected behavior statement. I'll do my best to update it. I think we all know what this function is supposed to do and if you look at the attached screenshot you can see that current_url is not returning the url as seen in the browser. My reference to App/Config/App was to avoid implying that it should return with the request uri.

**Comment by jayfortner** [comment]
Thanks @lonnieezell !
