### ISSUE TITLE
Feature Request: Validation: in_db[table.field]

### ISSUE THREAD

**Issue by thingNumber1** [codeigniter4/CodeIgniter4#2366]
Imagine that you have a list of fruits in your database and your users need to select their favorite fruits (but it must be a fruit that previously existed in the database) ...

Currently, to validate the entry, you must select all the fruits from your database, implode the results array and put it into the validation rule with something like this: `in_list['. Implode (',', $ result). ']'`

It would be amazing if you could validate it with something like this: `in_db[fruits.id]` where `fruits` is the name of the table and` id` is the name of the field.

In addition, the query for the second validation method would be faster than the first one because in the second case you can search for a primary or unique key, while in the first you must search for all the "fruits" in the database.

Note: I am aware that currently you can still validate the entry by looking for the primary key outside the validation rules ... but this is not fun if the idea of ​​using the validation rules is to facilitate the lives of the programmers.

**Comment by jim-parry** [comment]
Please raise feature requests in the subforum ... https://forum.codeigniter.com/forum-29.html
We use github to track bugs and approved work, thanks.
