### ISSUE TITLE
Bug: Spark issue with PHP install location

### ISSUE THREAD

**Issue by devyr** [codeigniter4/CodeIgniter4#2367]
**Bug?**
If PHP is installed to a directory with a space in its name 'php spark serve' returns error: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**CodeIgniter 4 version**
CodeIgniter 4.0.0.0-rc3

**Affected module(s)**
Running command 'php spark serve'

**Expected behavior, and steps to reproduce if appropriate**
Install and configure PHP (any version) to 'C:\Program Files\PHP\' (any directory with a space in its name).
Execute command 'php spark serve'.
OR
Execute command '"C:\Program Files\PHP\7.3.10\php.exe" spark serve' (complete php path).

**Context**
 - OS: Windows 10 Pro 64bit
 - Web server: N/A
 - PHP version: 7.3.10

**Comment by lonnieezell** [comment]
This is not an issue with spark. It is a Windows/PHP issue. See [this SO post](https://stackoverflow.com/questions/24904945/command-prompt-error-c-program-is-not-recognized-as-an-internal-or-external-c) for examples of others having issues.

**Comment by EdgarEldy** [comment]
I have experienced the same problem and it still not resolved. 
When i run php spark serve it returns this error :  'C:\Program' is not recognized as an internal or external command' Any help ? 
  @#![Capture](https://user-images.githubusercontent.com/26207338/75605845-39b3f500-5aef-11ea-91fc-701f777b86ac.JPG)

**Comment by MGatner** [comment]
That screenshot was very helpful! This appears to be an issue with the call to PHP itself. I think we need to quote our `passthru` call to the PHP binary here:
```
		passthru($php . ' -S ' . $host . ':' . $port . ' -t ' . $docroot . ' ' . $rewrite, $status);
```

Reopening.

**Comment by EdgarEldy** [comment]
> That screenshot was very helpful! This appears to be an issue with the call to PHP itself. I think we need to quote our `passthru` call to the PHP binary here:
> 
> ```
> 		passthru($php . ' -S ' . $host . ':' . $port . ' -t ' . $docroot . ' ' . $rewrite, $status);
> ```
> 
> Reopening.

Which file ?

**Comment by MGatner** [comment]
system/Commands/Server/Serve.php

**Comment by EdgarEldy** [comment]
Thanks. I fixed it. Don’t forget to fix it also in codeigniter4/framework and all other repository.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mierol16** [comment]
I can't solve this error. Anyone can help?

![image](https://user-images.githubusercontent.com/72370240/98210023-e138cf80-1f7a-11eb-93c2-028cfc1e345a.png)
