### ISSUE TITLE
Bug: Nothing work with minimal config (DIRECTORY SEPARATOR)

### ISSUE THREAD

**Issue by Qarakom** [codeigniter4/CodeIgniter4#2370]
**Describe the bug**
With minimal config nothing work on windows. even not show any error.
I think this problem for DIRECTORY_SEPARATOR. i use Windows 10, Apache, PHP 7.3.9
Directory something show like as this "C:\Server\myapp\../app/Config  

**CodeIgniter 4 version**
CodeIgniter 4 - 4.0.0-rc.3

**Affected module(s)**
Maybe path structure

**Context**
 - OS: Windows 10
 - Web server : Apache/2.4.41 (Win64)
 - PHP version : 7.3.9

**Comment by InsiteFX** [comment]
It has to be your config because I' am running XAMPP PHP 7.3.11 on Windows 10 Pro 64-bit.

Did you add a ending / on to your base_url?

**Comment by Qarakom** [comment]
> It has to be your config because I' am running XAMPP PHP 7.3.11 on Windows 10 Pro 64-bit.
> 
> Did you add a ending / on to your base_url?

Yes. my base url is  http://agent.lo/

**Comment by lonnieezell** [comment]
So what actually happens? "nothing works" could mean a lot of things. 

Is it a blank screen? Have you checked the logs? What do they say? Your server logs? 

I know others are running on Windows just fine, and I've done some testing on a Windows box myself. If there's something specific to your setup that is causing an issue, that's something good for us to know and fix - but we can't do that without details.

**Comment by Qarakom** [comment]
"nothing" means nothing. i use zero setup only install XAMPP and install codeigniter with composer. 
There is no log, no error even no any html source code

**Comment by Qarakom** [comment]
4.0.0 Beta 1 version is work all default config. But 4.0.0-rc.3 version only show white blank page.
also i check it with php spark nothing changed

**Comment by lonnieezell** [comment]
Did you set your environment to `development` the `.env` file? Sounds like errors are hidden because it's in production mode by default.

**Comment by truelineinfotech** [comment]
Rename env file to .env file and then test it.

**Comment by lonnieezell** [comment]
@Qarakom any news on this? Were you able to figure anything out?

**Comment by Qarakom** [comment]
> @Qarakom any news on this? Were you able to figure anything out?

i changed env to .env and also set environment to development. Nothing changed. Only show blank white screen.

**Comment by muh-ramadhan** [comment]
> > @Qarakom any news on this? Were you able to figure anything out?
> 
> i changed env to .env and also set environment to development. Nothing changed. Only show blank white screen.

can you display your <?php phpinfo(); ?>
