### ISSUE TITLE
How to use the pagination with view parser?

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#2371]
Hello there!

I am building a view with pagination with view parser, the problem is how I spend the value of pager to build my links? since it is an object and in view parser it is not possible to use them

```
$data = [
    'rows' => $this->model->paginate(2),
    'pager' => $this->model->pager
];
```

grettings!

**Comment by jim-parry** [comment]
Support questions should be asked on our [forum](https://forum.codeigniter.com/forum-30.html), thanks. We use git hub for bug tracking and planned work.
