### ISSUE TITLE
Feature: About the SameSite COOKIE RFC changes for PHP > 7.3

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#2374]
Hello in the old Codeigniter 3
i had an option to use this directly on the config of cookiePath... 
$cookiePath = '/; SameSite=strict'

setcookie('samesite-test', '1', 0, '/; samesite=strict');

Now with the new C4 this doesnt work anymore 
Please introduce this SameSite Cookie config setting into the 
Config/App.php File
$cookieSameSite = 'strict'; // or lax; i think they are 3 options, none, strict and lax... that have to be implemented..

Please guys send a message if you are thinking of implementing this.
Because for me this is very important !

// by default or something....

**Comment by jim-parry** [comment]
@lonnieezell Is this something overlooked? It feels like a feature request more than a bug.

**Comment by lonnieezell** [comment]
Looks like OP was using  a bit of a hack to get it to work. I think it's a worthy addition - but definitely a new feature. Tag it for the first release after 4.0 I think.

**Comment by crustamet** [comment]
The problem for this to fix it well it is a bit of a change if you want to add the feature

i just documented myself, and with the setcookie function the settings of the session should be passed as array not at simple variables....

So i understand for this you will have to change a lot of stuff. 

What i think is to make it work now at the present and not focuse on this task in the future...

This is a major concern this will help other problems to be solved...

**Comment by natanfelles** [comment]
Requires PHP >= 7.3 
https://www.php.net/manual/en/function.setcookie.php#refsect1-function.setcookie-changelog

**Comment by erikkloeze** [comment]
There exists a workaround for PHP < 7.3 (`$this->CSRFCookieSameSite` has been added as an attribute):

```
if (PHP_VERSION_ID < 70300) {
	setcookie(
		$this->CSRFCookieName, $this->CSRFHash, $expire, $this->cookiePath . "; samesite=" . $this->CSRFCookieSameSite, $this->cookieDomain, $secure_cookie, true                // Enforce HTTP only cookie for security
	);
}
else {
	setcookie($this->CSRFCookieName, $this->CSRFHash, [
		'expires' => $expire,
		'path' => $this->cookiePath,
		'domain' => $this->cookieDomain,
		'secure' => $secure_cookie,
		'httponly' => true,         // Enforce HTTP only cookie for security
		'samesite' => $this->CSRFCookieSameSite,
	]);
}
```

**Comment by crustamet** [comment]
after 4 months i am happy this was added in, seriously :)
