### ISSUE TITLE
Bug: Duplicate headers in response

### ISSUE THREAD

**Issue by hcbd** [codeigniter4/CodeIgniter4#2375]
**Describe the bug**
When receiving 'any' response from any location of the default installation, I am receiving 2 Date: headers
```
HTTP/1.1 200 OK
Host: localhost:8080
Date: Wed, 30 Oct 2019 18:27:20 GMT
Connection: close
X-Powered-By: PHP/7.3.10
Cache-control: no-store, max-age=0, no-cache
Content-Type: text/html; charset=UTF-8
Date: Wed, 30 Oct 2019 18:27:20 GMT
```
**CodeIgniter 4 version**
CodeIgniter-4.0.0-rc.3

**Affected module(s)**
Unknown

**Expected behavior, and steps to reproduce**
Expected behavior:
only 1 Date: header line

Reproduce: 
1. download the rc3. Unzip in a folder and run the php development server with 'php spark serve' in the folder
2. open webbrowser and it's dev tools (i'm using Firefox) and goto: localhost:8080
3. checkout the response headers. there are always 2 Date headers

Found this bugreport, which is closed/merged (but unknown to me if this patch made it into rc3)
https://github.com/codeigniter4/CodeIgniter4/issues/2170

**Context**
 - OS: Fedora 
 - PHP: 7.3.10
 - Server: PHP buildt-in Webserver

**Comment by hcbd** [comment]
I figured out that this happens after PHP added response headers and echoes output. PHP's buildt-in webserver is adding the extra Date: header

This can easily be fixed with a small check by changing:
https://github.com/codeigniter4/CodeIgniter4/blob/c20b7d7c52c7b4551d91be22fef7b58bd601951b/system/HTTP/Response.php#L716
To:
```

if (! isset($this->headers['Date']) && php_sapi_name() != 'cli-server')

```
Only adds the Date header, if CI4 is not running on the php buildt-in webserver

**Comment by lonnieezell** [comment]
A brief search and I don't see that Apache sets it by default, so I'm good to roll with this fix for now. Will have a fix up shortly.
