### ISSUE TITLE
Bug: useSoftDeletes with like function

### ISSUE THREAD

**Issue by edica** [codeigniter4/CodeIgniter4#2380]
**Describe the bug**
Practicing through the tutorial below. Using useSoftDeletes, and the fields indicated created_at, updated_at and deleted_at. Everything is working fine. But when I do a search with "where()" it doesn't show deleted records. Already using "like()" shows all deleted ones as well. like() should also not show deleted ones?

https://codeigniter4.github.io/CodeIgniter4/tutorial/news_section.html

**CodeIgniter 4 version**
CodeIgniter-4.0.0-rc.3

**Affected module(s)**
Unknown

**Expected behavior, and steps to reproduce if appropriate**
Shows deleted register:
$model->orLike(['title' => $q, 'slug' => $q, 'body' => $q])->paginate(5)
Do not show deleted register:
$model->where("body", $q)->paginate(5)

**Context**
 - OS: MacOS
 - Web server MAMP
 - PHP version 7.3.8

**Comment by MGatner** [comment]
@edica I wasn't able to replicate this issue. I have 4 Factories in the database all with "fas ..." icons, one with `deleted_at` set. I ran the following:
```
$factories = new \App\Models\FactoryModel();
$data = [
	'orLike' => $factories->orLike(['icon' => 'fas'])->paginate(5),
	'where' => $factories->where('id <', 4)->paginate(5),
];
```
`orLike` returned 3 of the 4 as expected, `where` returned 2 as expected.

Can you pull the latest `develop` branch and try again, in case it was some issue incidentally fixed along the way? If you are still having problems provide more context (like was the `orLike` following another `where` statement?). 

You can also harvest the actual database queries generated from the Debug Toolbar. For example, from mine above:
```
0.89 ms | SELECT COUNT(*) AS `numrows` FROM `dev_factories` WHERE `icon` LIKE '%fas%' ESCAPE '!' AND `dev_factories`.`deleted_at` IS NULL
-- | --
0.95 ms | SELECT * FROM `dev_factories` WHERE `icon` LIKE '%fas%' ESCAPE '!' AND `dev_factories`.`deleted_at` IS NULL AND `dev_factories`.`deleted_at` IS NULL LIMIT 5
0.97 ms | SELECT COUNT(*) AS `numrows` FROM `dev_factories` WHERE `id` < 4 AND `dev_factories`.`deleted_at` IS NULL
0.88 ms | SELECT * FROM `dev_factories` WHERE `id` < 4 AND `dev_factories`.`deleted_at` IS NULL AND `dev_factories`.`deleted_at` IS NULL LIMIT 5
```

**Comment by MGatner** [comment]
No response from user.

**Comment by Kelvin-te** [comment]
Am on CodeIgniter 4.3.3 and experiencing the same issue. orLike returns deleted records as well.

**Comment by markatsdp** [comment]
Same thing on 4.4.5.

**Comment by kenjis** [comment]
Check the SQL statement that are generated in the Debug Toolbar.

**Comment by markatsdp** [comment]
@kenjis Thanks for the tip. It seems that the like() and orLike() statements are not grouped together when the deleted_at is present. I had to explicitly group them together.
