### ISSUE TITLE
Feature: Migrate:Rollback/Refresh confirmation in production environment

### ISSUE THREAD

**Issue by Martin-4Spaces** [codeigniter4/CodeIgniter4#2385]
I think a confirmation message should be printed whenever running migrate:rollback command in production environment. 
And of cause an option to ignore it :) 
But as a default, I should be warned when trying to rollback production environment.

**Comment by lonnieezell** [comment]
I've had this thought, also. Though, interestingly enough, I believe Laravel used to do this, and now doesn't, but I'd have to check that. I'd be interested in seeing why they removed it if that is the case.

**Comment by najdanovicivan** [comment]
That's good idea but we'll still need to have option of forcing it to run without confirmation so that migrations can be run from auto deployment scripts. This may be the reason why it was removed form Laravel
