### ISSUE TITLE
No such file or Directory found In Ubuntu 19.10

### ISSUE THREAD

**Issue by rsRamgharia** [codeigniter4/CodeIgniter4#2394]
First of all thanks for the latest version of framework, Now coming to the issue. I got the error like below

![Screenshot from 2019-11-11 19-25-50](https://user-images.githubusercontent.com/50511441/68592609-7ebd0880-04b9-11ea-9284-cd835d134fc3.png)

I got above error when i write
`$model = new CodeIgniterUsers();
        return $model->findAll();`

**Comment by lonnieezell** [comment]
That sounds like your database configuration is off. I've gotten around that in the past by changing `localhost` to `127.0.0.1` in the database config before.
