### ISSUE TITLE
Documentation Fix Needed

### ISSUE THREAD

**Issue by rhays816** [codeigniter4/CodeIgniter4#2412]
#1613  the Validation Library @ **Check If Error Exists**.  
You have:

_Check If Error Exists
You can check to see if an error exists with the hasError() method. The only parameter is the field name:_
`if ($validation->hasError('username')
{
    echo $validation->getError('username');
}`

The code is missing the last parentheses in if statement.
Should be:

`if ($validation->hasError('username'))
{
    echo $validation->getError('username');
}`

**Comment by musmanikram** [comment]
@lonnieezell can you please close this bug? Fix has been merged into develop
