### ISSUE TITLE
Bug: Validation not working 

### ISSUE THREAD

**Issue by rsRamgharia** [codeigniter4/CodeIgniter4#2418]
Validation is not working if the key is not present in array.

`
        $data = [
            'name' => $name,
            'email' => $email,
            'password' => $password
        ];
`
if i remove any key from the array, then model will never validate that key

```
protected $validationRules    = [
        'name'     => 'required|alpha_numeric_space|min_length[4]',
        'email'    => 'required|valid_email|is_unique[users.email]',
        'password' => 'required|min_length[6]',
    ];
```
![Screenshot from 2019-11-19 13-13-54](https://user-images.githubusercontent.com/50511441/69126548-7888e680-0ace-11ea-81d0-9c3ba7360a9b.png)

See the above image i remove password from the array and model doesn't validate that field

**Comment by SunilEver** [comment]
Please follow template provided for the bug report. https://github.com/codeigniter4/CodeIgniter4/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md
This will help understand the issue better.

**Comment by lonnieezell** [comment]
Not a bug. The validation library is designed to validate the keys' values against the rules. It is the developer's job to ensure they pass they proper keys in. This allows validation rules to be used for both inserts and updates.
