### ISSUE TITLE
Bug: ImageHandler has no reality checks

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2421]
**Describe the bug**
ImageHandler does not do any verification that it has a valid image loaded, which can lead to some errors with unhelpful descriptions. E.g. `fit()` will try to calculate the aspect ration with a null value, so `$xRatio = $width / $origWidth;` results in "Division by zero".

I don't know where validation should happen - `withFile()` is maybe the best bet but doesn't catch instances where developers forget to use it before calling other methods.

**CodeIgniter 4 version**
develop

**Affected module(s)**
Image Manipulation Class

**Comment by lonnieezell** [comment]
`withFile` makes sense to me. 

Anytime the developer forgot to do a step it should crash loudly so they can catch it...

**Comment by MGatner** [comment]
So errors like "division by zero" are okay if they skip `withFile()` and call `fit()` directly?

**Comment by MGatner** [comment]
Actually to take it one step deeper... `Image` is actually just an extension of `File` with the additional methods `copy()` and `getProperties()` (and some properties) but no constructor... Should `Image` have its own constructor to verify the file is an image?

**Comment by MGatner** [comment]
Deeper still... `getProperties()` relies on PHP's `getimagesize` that has the following note in the manual:
> *Caution* This function expects filename to be a valid image file. If a non-image file is supplied, it may be incorrectly detected as an image and the function will return successfully, but the array may contain nonsensical values.
> Do not use getimagesize() to check that a given file is a valid image. Use a purpose-built solution such as the Fileinfo extension instead.

I'm thinking we either need a lot more involvement or just some way of failing more explicitly.

**Comment by lonnieezell** [comment]
In general yes. Every example in the docs show that you have to use `withFile()`. That library is not intended for general image creation, only manipulating existing images. At that point, it's a developer error and an exception should be thrown so they can locate the error during their testing. 

I suppose we could give a more helpful exception message (that an image is required), but that would require a check on pretty much every function. 

The File constructor already has the option to check if a file exists, but that's an optional check. In the [BaseHandller](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Images/Handlers/BaseHandler.php#L162), though we do check the file exists. That requires the user has actually used `withFile`, though...

**Comment by MGatner** [comment]
Hmm this is tricky.

On the one hand, it seems like a valid `$path` and valid image at that path are requirements for the handlers, and presupposed for every method - that makes me think it should be part of the constructor (but keep `withFile()` to make handling multiple files easy).

On the other hand having the handlers be handler classes makes them easy to use with the service, but creates this situation where it is easy to mess up.

**Comment by MGatner** [comment]
Floating an idea... Since all the methods use `$this->image` and require it to be a valid file & image, we replace that with `$this->image()` (or `getImage()` or whatever) that makes a one-time check (reset by `withFile()`) to do validate path and image and then return the Image instance, and it can handle throwing appropriate messages.
