### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by SunilEver** [codeigniter4/CodeIgniter4#2448]
**Describe the bug**
`$validationMessages` fields on `CodeIgniter\Model` is an overkill. One can always set error messages on `$validationRules` using `errors` key

**CodeIgniter 4 version**
v4.0.0-rc.3

**Affected module(s)**
`Codeigniter\Model`

**Context**
 - OS: Ubuntu 5.4.0-6ubuntu1~16.04.12
 - Web server: php inbuilt server
 - PHP version : 7.3

**Comment by MGatner** [comment]
`$validationMessages` allows errors to be set on-the-fly by the `setValidationMessages()` method, allowing Controllers to provide their own messages that would not ordinarily be available if using the `errors` key in `$validationRules`.
