### ISSUE TITLE
Bug: Filter wildcards ignore default methods

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2455]
**Describe the bug**
Filters applied via **app/Config/Filters.php** `$filters` do a literal check versus the URL, which doesn't take into account default controller methods when resolving wildcards. This makes for confusing behavior - consider the following:
```
public $filters = ['login' => ['before' => ['account/*']]];
```
* https://example.com/account/update - runs
* https://example.com/account - does not run
* https://example.com/account/index - runs

A workaround is to specify the wildcard like `account*` but that also possibly matches other Controllers (like `accountants/index`).

**CodeIgniter 4 version**
Latest `develop`

**Affected module(s)**
Filters, Routes

**Expected behavior, and steps to reproduce if appropriate**
I think a simple inclusion of `{whatever}/` in `*` expansion should work.

**Context**
 - OS: **Linux**
 - Web server **Apache**
 - PHP version **7.3**

**Comment by lonnieezell** [comment]
This was the intended functionality. Much like routes, it works in a top-down method, so if you need to match `accountants` put that prior to `account`.

**Comment by MGatner** [comment]
This is for Filters not Routes, so there is really no way to prevent the wildcard matching. You could add it as an `except` but I still think it is confusing behavior for “foobar/*” not to match “baseurl.com/foobar”.
