### ISSUE TITLE
Double quotes

### ISSUE THREAD

**Issue by MashinaMashina** [codeigniter4/CodeIgniter4#2459]
What is it?

protected function _escapeString(string $str): string
{
	return str_replace("'", "''", remove_invisible_characters($str, false));
}

I'am writing driver for ClickHouse, and I getted error because CI puts double quotes in query. Is it such an abstract function?

My result query from db driver: SELECT * FROM table WHERE `key`=''value''
('' it isnt ")

**Comment by lonnieezell** [comment]
The methods in the database drivers that start with an underscore are intended to be overridden by your own drivers if needed. You should override that method in your driver to properly escape a string.

**Comment by lonnieezell** [comment]
Oh - and in the future, please ask support questions on the forums. Only report bugs here.
