### ISSUE TITLE
Bug: prototype of setBody($data); method in CodeIgniter\HTTP\Message should be changed to setBody(string $data);

### ISSUE THREAD

**Issue by SunilEver** [codeigniter4/CodeIgniter4#2466]
**Describe the bug**
prototype of `setBody($data);` method in `CodeIgniter\HTTP\Message` should be changed to `setBody(string $data);` as when calling `IncomingRequest::getJson()` the method finds something other string and tries to json decode it.

**CodeIgniter 4 version**
v4.0.0-rc.3

**Affected module(s)**
All request modules.

**Expected behavior, and steps to reproduce if appropriate**
CodeIgniter\HTTP\Message::setBody should throw an error if anything other than `string` is passed.

**Context**
 - OS: Ubuntu 16
 - Web server php native server
 - PHP version 7.3.13

**Comment by lonnieezell** [comment]
I believe it's perfectly valid to set an array or object as the body of a Response (which extends Message) so the suggested change would cause issues elsewhere. 

Please provide enough details to recreate the issue that you're having.

**Comment by SunilEver** [comment]
I was using an internally developed package . That package was setting body
as an array. Now I called getJSON() on the incoming request which perform
json_decode on the body. That returned an error that argument to
json_decode should be string.

**Comment by lonnieezell** [comment]
I'm a bit confused here. The `IncomingRequest`'s `getJSON` is intended to retrieve the HTTP request's body and parse it as JSON. That will always be a string after going through a web server, I believe. 

You said you have problems with setting a value in the Message body. How does this have anything to do with `IncomginRequest`? It sounds like you might be using it a way it's not intended for.

**Comment by SunilEver** [comment]
Yes I am using in a way that is not intended. I should pass string but I
pass array . But there should be a type hinting. The body of a request is
always a string. So the param should be of string type. And that way I
should not be able to use it in a way not intended.

**Comment by MGatner** [comment]
We have at least one test that explicitly uses `setBody()` with an array:
```
	public function testJSONGetFromNormalBody()
	{
...
		$body     = [
			'foo' => 'bar',
...
		];
...
		$response->setBody($body);

		$this->assertEquals($expected, $response->getJSON());
	}
```

I think the type needs to remain undefined, but I will update the header variable type so it doesn't specify `string`.
