### ISSUE TITLE
Bug: $useTimestamps cause insert() exception

### ISSUE THREAD

**Issue by hoc-ht** [codeigniter4/CodeIgniter4#2469]
**Describe the bug**
After set **$useTimestamps=true**, I got an exception while try to **insert()**:
`CRITICAL - 2019-12-31 10:49:23 --> ErrorException: array_key_exists(): The first argument should be either a string or an integer in **\vendor\codeigniter4\framework\system\Model.php:703`

**CodeIgniter 4 version**
Version 4.0.0-rc.3

**Context**
 - PHP version 7.3.10

**Comment by MGatner** [comment]
Did you set `createdField`?

**Comment by hoc-ht** [comment]
I'm sorry. This is my mistake. I set wrong value for $updateField, so it cause this exception.
