### ISSUE TITLE
Bug: CodeIgniter\Router\Router->checkRoutes() strpos() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by luisdev1** [codeigniter4/CodeIgniter4#2479]
**Describe the bug**
Attempting to add a route redirection within a namespace route group is returning a parameterization error or an inconsistent redirection (Ex: http://localhost:8080/Acme/Blog/Controllers/blogIndex)

**CodeIgniter 4 [version**`]
[develop]((https://github.com/codeigniter4/CodeIgniter4/blob/develop/))

**Affected module(s)**
CodeIgniter\Router\Router

**Expected behavior, and steps to reproduce if appropriate**
The example code
`$routes->group('blog', ['namespace' => 'Acme\Blog\Controllers'], function($routes){ `

    $routes->add('list', 'Home::index', ['as' => 'blogIndex']); 

    $routes->addRedirect('/', 'blogIndex'); 

`});`

**Context**
 - OS: macOS 10.15.2
 - Web server: Apache 2.2.34
 - PHP version 7.3

**Comment by Instrye** [comment]
Redirect functionality seems to be under development ..
https://github.com/codeigniter4/CodeIgniter4/pull/2338

**Comment by luisdev1** [comment]
@Instrye That changes working for me! Thanks!

https://github.com/codeigniter4/CodeIgniter4/pull/2481
