### ISSUE TITLE
Schema param in the .env file

### ISSUE THREAD

**Issue by crazoid** [codeigniter4/CodeIgniter4#2483]
For postgres db doesn't work for 'php spark migrate' command.
The 'migrations' table and the table specified in migration is always created in public schema and not in the schema specified in the .env file.
Correct migration only works by specifying database schema directly in the app\Config\Database.php file.

**Comment by lonnieezell** [comment]
Please provide the code you tried using in .env.

**Comment by crazoid** [comment]
database.default.hostname = localhost
database.default.database = development
database.default.schema = system
database.default.username = postgres
database.default.password = 123
database.default.DBDriver = postgre
database.default.port = 5432

**Comment by crazoid** [comment]
> Please provide the code you tried using in .env.

database.default.hostname = localhost
database.default.database = development
database.default.schema = system
database.default.username = postgres
database.default.password = 123
database.default.DBDriver = postgre
database.default.port = 5432

**Comment by lonnieezell** [comment]
i'm more familiar with MySQL/MariaDB than Postres. The 2 things that catch my eye are: 

1. the DBDriver should be capitalized: `Postgre`. 
2. I often have to change from `localhost` to `127.0.0.0`. Usually that throws an exception, though, not refuses to acknowledge the settings. 

My only other thought would be to make sure the file is `.env`, not `env` (the leading period is important).
