### ISSUE TITLE
Image Manipulation Class

### ISSUE THREAD

**Issue by Henqsan** [codeigniter4/CodeIgniter4#2498]
Hello!

I am trying to implement the image manipulation library in my controller. But when I try to use the base_url() path, the library cannot find the path!

 ```
 $path_save = base_url('assets/images/test.jpg');

             $image = \Config\Services::image()
            ->withFile($image_file->getTempName())
            ->fit(100, 100, 'center')
            ->save($path_save);
```

What is the difference in using the path to the directory where the image will be saved like this:

base_url('assets/images/test.jpg')

and this way:

'../public/assets/images/test.jpg'

Is there a correct way to indicate the directory path to save the image?

**Comment by MGatner** [comment]
Support questions belong on the forums. Briefly: **public/** should not be part of your URL path - you should be serving it as your root such that the image would be at "http://example.com/assets/images/test.jpg". If you cannot modify the web server you need to use **.htaccess** or equivalent to adjust the path.
