### ISSUE TITLE
Bug: Wrong Links for pager when having subfolders

### ISSUE THREAD

**Issue by Ephaltes** [codeigniter4/CodeIgniter4#2505]
Hello, 

I am using CI on a school server, so i dont have a own subdomain , moreover where are sharing the subdomain with other students, so that we need to use subfolders for identificating the website.

The problem is, when using the pager with subfolders it is generating wrong url, without the subfolder.

In my app.php AND .env file, I have app.baseURL set to "http://mysite.at/itp1-ws2019/"

**CodeIgniter 4 version**
4.0.0-RC3

**Affected module(s)**
PAGER

**Expected behavior, and steps to reproduce if appropriate**

Base URL: http://mysite.at/itp1-ws2019/

when calling $pager->links()  it generates

- http://mysite.at/component/component_table?page=X

**Expected**

- http://mysite.at/itp1-ws2019/component/component_table?page=X

If I run $page->setPath( itp1-ws2019/component/component_table' ) then it is right, but thats way more work for all the pagers I am using

**Context**
- Windows & Ubuntu (Windows development / Ubuntu production)
- Apache/2.4.29
- PHP 7.2

Screenshot where you can see the URL in the addressbar and where i hover over the pagination link
The Table is getting loaded by Ajax

![pic_1](https://user-images.githubusercontent.com/13035924/72929653-8ff88000-3d5a-11ea-950a-90f948eb43b0.png)

In this one I open it directly without ajax , same result
![pic_2](https://user-images.githubusercontent.com/13035924/72929978-2fb60e00-3d5b-11ea-8ec3-d0cd98cb62f7.png)

**Comment by lonnieezell** [comment]
There's been related issues fixed in the current develop branch. Please pull down the latest and give that a try then let me know if the issue still exists.

**Comment by Ephaltes** [comment]
@lonnieezell 
I have tried it, with the new version from the dev branch, I still have the same problem 
only thing is that instead of page it now displays page_components (components is the group)

![pic_3](https://user-images.githubusercontent.com/13035924/72936195-fc797c00-3d66-11ea-93a4-45aa39d9e099.png)

**Comment by tangix** [comment]
@lonnieezell 
Since I guess this is related to #2445 I wonder how it would be possible to help test this.
Like @Ephaltes I have tested development build with the same error, leading me to think there is a configuration (documentation?) confusion here. 
Do you have any link to docs so I can double-check my tests?

**Comment by lonnieezell** [comment]
Pushing  a fix. Looks like changing line 506 of Pager.php to use `'uri' => clone current_url(true)` fixes the issue.
