### ISSUE TITLE
Missing Constant in E-Mail

### ISSUE THREAD

**Issue by penguinpower80** [codeigniter4/CodeIgniter4#2512]
In vendor/codeigniter/framework/system/Email, line 1501 references constant ICONV_ENABLED, but that is no longer set like it was in CI3

**Comment by MGatner** [comment]
This appears to have been a shorthand in CI3 for checking the `iconv` extension:
```
if (extension_loaded('iconv'))
{
	defined('ICONV_ENABLED') OR define('ICONV_ENABLED', TRUE);
	@ini_set('iconv.internal_encoding', 'UTF-8');
}
```

While my reading suggests that extension should be available by default, switching the constant out for now to be safe...
