### ISSUE TITLE
Bug: Class 'Locale' not found when I try to use Time::parse()

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#2519]
Hello I just rum my cmd command for composer to update my codeigniter 4 framework.
Now I got this problem<br>
Error<br>
Class 'Locale' not found<br>
SYSTEMPATH/I18n\Time.php at line 108

```php
101      * @param string|null $locale
102      *
103      * @throws \Exception
104      */
105     public function __construct(string $time = null, $timezone = null, string $locale = null)
106     {
107         // If no locale was provided, grab it from Locale (set by IncomingRequest for web requests)
108         $this->locale = ! empty($locale) ? $locale : Locale::getDefault();
109 
110         // If a test instance has been provided, use it instead.
111         if (is_null($time) && static::$testNow instanceof Time)
112         {
113             if (empty($timezone))
114             {
115                 $timezone = static::$testNow->getTimezone();
```

Just like the "Locale" class file has been removed. Please try to solve this issue.<br>
<br>
This happen when i try to use this:
```php
$time = CodeIgniter\I18n\Time::parse($time, getConfig('site_timezone'));
return $time->humanize();
```
<br>
I am waiting for this issue to be solve.

**Comment by ChibuezeAgwuDennis** [comment]
@lonnieezell and @jim-parry  Please check this problem

**Comment by lonnieezell** [comment]
No need to mention me by name. We're all volunteers here. Wee see every issue that comes through but it sometimes takes a bit to get to it.

**Comment by lonnieezell** [comment]
Also - the `Locale` class is part of the `intl` extension for PHP. Not specific to our framework so make sure you have that loaded in your current PHP environment.

**Comment by ChibuezeAgwuDennis** [comment]
Okay I am sorry

**Comment by ChibuezeAgwuDennis** [comment]
let me see what i can do just that I believe you can help me on this

**Comment by lonnieezell** [comment]
No worries. If you need additional help, though, please ask on the forums. We just do bugs here.

**Comment by ChibuezeAgwuDennis** [comment]
okay
