### ISSUE TITLE
Bug: router service adds backslash to controllername if route is configured

### ISSUE THREAD

**Issue by chriseilander** [codeigniter4/CodeIgniter4#2520]
**Describe the bug**
When a route isn't defined, the controllerName() function in service('router') returns an expected string like 'App\Controllers\{controllername}'. But when a route is defined in the routes.php it also returns an extra \ like '\App\Controllers\{controllername}'.

**CodeIgniter 4 version**
CodeIgniter 4 RC 3 zip version
CodeIgniter 4 Dev starter composer
CodeIgniter 4 App starter composer

**Affected module(s)**
Probably the router service

**Expected behavior, and steps to reproduce if appropriate**
Let the namespace define the route, and return the controller name using
`$router = service("router");
echo $router->controllerName();`
It should return the namespace of the controller with the name.

Now define the route in routes.php, and the same code will return an \ with the namespace of the controller with the controllername.

I expected them to be the same.

**Comment by samsonasik** [comment]
@chriseilander @MGatner I think the correct one is the one with `\` prefix as it fqcn like in the doc comment at https://github.com/codeigniter4/CodeIgniter4/pull/2734/files#diff-d2374d65fd714c18dbee9f5adaa8dd6cL552. 

I created PR #2734 for it.
