### ISSUE TITLE
Multiple composer.json handling in codeigniter!!

### ISSUE THREAD

**Issue by inandi** [codeigniter4/CodeIgniter4#2528]
let's say my project directory structure like this:

```
root
|---vendor/
|---composer.json
|---API_DIRECTORY
	|---index.php
	|---LIBRARY
		|---AWS/
			|---vendor/
			|---composer.json
		|---GOOGLE/
			|---vendor/
			|---composer.json
		|---FACEBOOK/
			|---vendor/
			|---composer.json
	|---vendor/
	|---composer.json
```

as you can see I have multiple packages with different composer.json files. each and every time I need to run composer install separately. how can I do it only once, using one composer JSON file?

**Comment by jlamim** [comment]
Your question is more related to the use of Composer than to CodeIgniter itself. I suggest looking for answers in groups and forums about Composer or even in the CodeIgniter forum.

The issues are for reporting bugs and suggesting improvements and new features.

**Comment by MGatner** [comment]
I agree with @jlamim. Also, please use the forums for support questions - GitHub is for bug reports.

You may be interested in this: https://github.com/composer/composer/issues/183
