### ISSUE TITLE
Error In UserGuide

### ISSUE THREAD

**Issue by ajmeireles** [codeigniter4/CodeIgniter4#2530]
**Where**
In `Error Handling` from UserGuide of CodeIgniter 4

**Error**
The explanation about `RedirectException` say that a way to throw new exception is:
throw new **CodeIgniterRouterExceptionsRedirectException**($route, 301), but the correct way is: 
throw new **\CodeIgniter\Router\Exceptions\RedirectException**($route, 301);

**Comment by MGatner** [comment]
The code is actually correct but for some reason the User Guide markdown is treating it as a quote instead of code, so the slashes are interpreted instead of displayed. I’ll look into that.
