### ISSUE TITLE
$routes not do the job as well

### ISSUE THREAD

**Issue by mjamilasfihani** [codeigniter4/CodeIgniter4#2531]
I use my codeigniter rc3 as HMVC. Here is my structure

![GITHUB](https://user-images.githubusercontent.com/51300528/73802195-755ce700-47ef-11ea-8a2a-cf88cd83dd12.png)

I try to do some action from HomeView with input username and password also method POST that handled by Home Controller to ActionSignIn. I set the route like this `$routes->get('action-signin', 'Acme\Home\Controllers\HomeAction\ActionSignIn::index');`

Peekaboo, it show 404 when I press the submit button. I try to visit `action-signin` directly, nothing was wrong.

**Comment by lonnieezell** [comment]
Please look for support on the forums. The issues here are for bug tracking. 

If you find a  bug while working through things with others on the forum, feel free to bring that back here.

**Comment by mjamilasfihani** [comment]
okay
