### ISSUE TITLE
Bug: multi-column WHERE not prefixed

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2532]
**Describe the bug**
When referencing a fully-qualified column as the target of a WHERE operator the second table name is not prefixed.

**CodeIgniter 4 version**
Latest develop

**Affected module(s)**
Builder (tested with MySQLi)

**Expected behavior, and steps to reproduce if appropriate**
```
$config['DBPrefix'] = 'foo_';
...
$builder = db_connect()->table('mytable');
$builder->where('mytable.created_at < mytable.updated_at')->get()->getResult();
```

The above will thrown an exception "Table not found: mytable" because the generated query looks like:
`SELECT * FROM foo_mytable WHERE foo_mytable.created_at < mytable.updated_at`

(Notice the missing prefix on the latter table reference)

**Context**
 - OS: Ubuntu 18.04
 - Web server: Apache
 - PHP version: 7.3

**Comment by musmanikram** [comment]
@MGatner Please close this bug

**Comment by MGatner** [comment]
Oh yeah thanks for the reminder.
