### ISSUE TITLE
Bug: Docs / Library Reference / Validation: missing important information on reset() method

### ISSUE THREAD

**Issue by bivanbi** [codeigniter4/CodeIgniter4#2535]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
Documentation lacks vital information that Validation instance needs to be reset before re-running validation after a previous run that had errors by calling reset() method.

**CodeIgniter 4 version**
4.0.0rc3

**Affected module(s)**
Documentation / Library Reference / Validation

**Expected behavior, and steps to reproduce if appropriate**
Documentation should emphasize that consecutive validations should be preceded by reset() to get rid of error state from previous runs.

**Comment by musmanikram** [comment]
Can you please create a PR for this?

**Comment by bivanbi** [comment]
Will try my best. Sit tight.

**Comment by bivanbi** [comment]
Pull request with fix has been approved.
