### ISSUE TITLE
Bug: Sessions dont work on PostgreSQL

### ISSUE THREAD

**Issue by MashinaMashina** [codeigniter4/CodeIgniter4#2546]
CI4 save base64 encoded value, but postgres later returns hex encoded value and base64 cant decode value

If in database handler write this code before get query, all is ok
`$this->db->query('SET bytea_output = "escape"');`

https://www.postgresql.org/docs/9.0/datatype-binary.html

I dont know how we must work with binary data in Postgres

https://prnt.sc/r1sng5
https://prnt.sc/r1snv9
https://prnt.sc/r1sot1

I have PostgreSQL v12

**Comment by pstef** [comment]
@MashinaMashina see https://github.com/codeigniter4/CodeIgniter4/pull/2256/commits/4b1774a66dfa2e7d95fe937654a81921fb441538 (which is a part of rejected #2256) for possible inspiration.
