### ISSUE TITLE
Bug: CI4 set ID to NULL when I try insert a row

### ISSUE THREAD

**Issue by MashinaMashina** [codeigniter4/CodeIgniter4#2557]
This code:
```php
if (! empty($properties) && ! empty($primaryKey) && ! in_array($primaryKey, $properties))
{
	$properties[$primaryKey] = $data->{$primaryKey};
}
```

breaks all my app. When I try to insert a row, in example this row:
name: John
age: 21

CodeIgniter add field from primaryKey and fill value to NULL. And postgres got error because id can`t be null

Code for reproduction:
```php
$user = new App\Entities\User;
$user->fill([
	'name' => 'John',
	'age'  => 21,
]);

$userModel->save($user);
// and we get error because primary key of userModel can`t be null
```

**Comment by lonnieezell** [comment]
Make your primary key auto-increment. The Entity expects an auto-incrementing primary key. I thought we had gone back and made that explicit in the user guide but I'm not finding it so that's something we should add. Not a bug, though. It's intended this way.

**Comment by MashinaMashina** [comment]
@lonnieezell it is autoincrement, but for autoincrement work, we don`t must set field

http://prntscr.com/r2gkhf

**Comment by lonnieezell** [comment]
I'm not the most familiar with working with Postgres, but I thought auto-incrementing was only for the `serial` types? Or do I have that wrong?

**Comment by MashinaMashina** [comment]
It work under sequences http://prntscr.com/r2h5c6
https://www.postgresqltutorial.com/postgresql-serial/

http://prntscr.com/r2h64k http://prntscr.com/r2h6bv

**Comment by MashinaMashina** [comment]
@lonnieezell this is still a bug

**Comment by MashinaMashina** [comment]
@lonnieezell @MGatner  open pls this issue. 

Can we add this check? 
```php
&& isset($data->{$primaryKey})
```
to
```php
if (! empty($properties) && ! empty($primaryKey) && ! in_array($primaryKey, $properties))
{
	$properties[$primaryKey] = $data->{$primaryKey};
}
```
