### ISSUE TITLE
Migration on PostgreSQL failes for tables with foreign keys

### ISSUE THREAD

**Issue by psuplat** [codeigniter4/CodeIgniter4#2575]
It would appear that the _disableForeignKeyChecks()_ does not work for migrations for PostgreSQL.

This is my base migration file:
```
public function up()
    {
	$this->db->disableForeignKeyChecks();

        //departments table
        $this->forge->addField([
            'id' => [
                'type' => 'INT',
                'auto_increment' => TRUE
            ],
            'department_name' => [
                'type' => 'VARCHAR',
                'constraint' => '250',
            ],
            'department_email' => [
                'type' => 'VARCHAR',
                'constraint' => '250',
            ],
            'department_head' => [
                'type' => 'VARCHAR',
                'constraint' => '250',
            ],
            'department_disabled' => [
                'type' => 'BOOLEAN',
                'null' => TRUE,
                'default' => FALSE,
            ],
        ]);
        $this->forge->addKey('id', TRUE);
        $this->forge->createTable('departments');

        //domains table
        $this->forge->addField([
            'id' => [
                'type' => 'INT',
                'auto_increment' => TRUE
            ],
            'department_id' => [
                'type' => 'INT',
            ],
            'domain' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
            ],
        ]);
        $this->forge->addKey('id', TRUE);
        $this->forge->addForeignKey('department_id','departments','id');
        $this->forge->createTable('department_domains');
	$this->db->enableForeignKeyChecks();
    }

    public function down()
    {
	$this->db->disableForeignKeyChecks();
	$this->forge->dropTable('departments');
	$this->forge->dropTable('department_domains');
	$this->db->enableForeignKeyChecks();
    }
```

when I run _php spark migrate_ the first time all is good and tables are created with all the keys.
However when I try to run _php spark migrate:refresh_ to reset everything i get the following error:

```
pg_query(): Query failed: ERROR:  cannot drop table departments because other objects depend on it
DETAIL:  constraint department_domains_department_id_foreign on table department_domains depends on table departments
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

I am aware that I can simply drop tables in the correct order, in this case like so:
```
$this->forge->dropTable('department_domains');
$this->forge->dropTable('departments');
```

and it will work (I tested it) but that defeats the purpose of the disabling foreign checks.

**Comment by lonnieezell** [comment]
What version of Postgres are you using? 

In the code we're using `'SET CONSTRAINTS ALL DEFERRED` which should turn them off as far as know. Granted, my Postgres history is pretty limited.

**Comment by psuplat** [comment]
I am using version 11.7

**Comment by pstef** [comment]
1. this is an object dependency, not a row dependency via foreign key
2. SET CONSTRAINTS works within a transaction

**Comment by lonnieezell** [comment]
@pstef I'm sorry, I don't follow. Are you for or against the current implementation?

**Comment by pstef** [comment]
I might be wrong and I don't feel motivated to double-check (as I don't use migrations myself), but if I'm not mistaken, there are two things to notice here:
1. SET CONSTRAINTS only impacts foreign constraint checks for data modification commands. It doesn't affect DROP (DDL).
2. for a SET CONSTRAINTS command to work as expected, it has to be executed within an existing transaction and before the DML commands.

My conclusion is that SET CONSTRAINTS doesn't do what is expected of it here. And even if it would, it would need to happen within a transaction to make any difference.

**Comment by michalsn** [comment]
This is definitely not a bug, just normal PostgreSQL behavior. As @pstef pointed out `SET CONSTRAINTS ALL DEFERRED` is only valid for DML statements and will have no effect here. There is nothing we can do about it.

What we are looking for here is `DROP TABLE ... CASCADE`, and we already have support for this in Postgre driver via third parameter:
```
$this->forge->dropTable('departments', true, true);
$this->forge->dropTable('department_domains', true, true);
```
This is the proper way to handle this in PostgreSQL.
