### ISSUE TITLE
Bug: $forge->dropColumn not allowing arrays

### ISSUE THREAD

**Issue by MohKari** [codeigniter4/CodeIgniter4#2576]
**Describe the bug**
According to the documentation [here](https://codeigniter4.github.io/userguide/dbmgmt/forge.html?highlight=add%20column%20after#dropColumn), the dropColumn method should allow for an array of columns to be dropped. However the method only allows for a string, and the logic doesn't handle the possibility of an array been supplied.

**CodeIgniter 4 version**
4.0.0:master

**Affected module(s)**
CodeIgniter\Database\Forge

**Expected behavior, and steps to reproduce if appropriate**
Be allowed to supply either a string or an array, and either a single or multiple columns are dropped.

**Context**
 - OS: 4.9.184-linuxkit
 - Web server  Apache/2.4.38 (Debian)
 - PHP version 7.2.22

**Comment by musmanikram** [comment]
@lonnieezell please close this issue
