### ISSUE TITLE
Bug: testOrHavingBy() requires a select

### ISSUE THREAD

**Issue by qury** [codeigniter4/CodeIgniter4#2584]
**Describe the bug**

The testOrHavingBy() in tests/system/Database/Live/GroupTest.php is missing a select statement.
This is required by some databases that could be added in future (Oracle, Microsoft SQL Server,etc..) and would not impact the tests for the currently supported DB's.

**CodeIgniter 4 version**
4.0.0-rc4

**Current method:**
public function testOrHavingBy()
	{
		$result = $this->db->table('user')
						->groupBy('id')
						->having('id >', 3)
						->orHaving('SUM(id) > 2')
						->get()
						->getResult();
		$this->assertCount(2, $result);
	}

**Expected:**
	public function testOrHavingBy()
	{
		$result = $this->db->table('user')
                                                ->select('id')
						->groupBy('id')
						->having('id >', 3)
						->orHaving('SUM(id) > 2')
						->get()
						->getResult();
		$this->assertCount(2, $result);
	}

**Comment by musmanikram** [comment]
If we don't pass any column name in query, by default it will add `SELECT *` in query.
If you print `$this->db->showLastQuery()` it will show the complete query which is:  
```SELECT *
FROM "db_user"
GROUP BY "id"
HAVING "id" > 3
OR SUM(id) > 2```

**Comment by qury** [comment]
Try executing the above on microsoft sql server and it will complain that the db_user.name is not part of the group by clause.

The reason i ask for this is that i'm trying to continue the work @puschie286  has done on #503  and  this test is failing due to this. (Also codeigniter3 test for the very same has the id field defined in select).

**Comment by dafriend** [comment]
@qury, You could modify ``testOrHavingBy()`` and include that with whatever PR you eventually make.

**Comment by musmanikram** [comment]
@qury I agree with @dafriend you can add all required tests in your PR.
