### ISSUE TITLE
Bug: CI cant display error with API Response Trait

### ISSUE THREAD

**Issue by MashinaMashina** [codeigniter4/CodeIgniter4#2586]
If we uses https://codeigniter4.github.io/userguide/outgoing/api_responses.html and we get error, in example from db, CI cant display this error and die with this:
`Fatal error</b>:  Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: &quot;Type is not supported&quot;. in /var/www/system/Format/Exceptions/FormatException.php:9`

It because error contains error bug trace with a lot of elements, and json_encode cant handle it.

https://prnt.sc/r62612
https://prnt.sc/r626jq

https://prnt.sc/r626qf
https://prnt.sc/r627gl

**Comment by MGatner** [comment]
Probably related to #2434
