### ISSUE TITLE
Bug:  Class 'Kint\Renderer\Renderer' not found

### ISSUE THREAD

**Issue by arif98741** [codeigniter4/CodeIgniter4#2605]
**Issue**
During running spark in my terminal I am facing Render not found error. 

**CodeIgniter version**
Codeigniter 4

**Error Response**
`
$ php spark serve
An uncaught Exception was encountered

Type:        Error
Message:     Class 'Kint\Renderer\Renderer' not found
Filename:    C:\wamp64\www\ci4\vendor\codeigniter4\framework\system\Config\Config.php
Line Number: 124
`

**Context**
 - OS: [e.g. Windows 10]
 - Web server [e.g. Apache 2.2.41]
 - PHP version [e.g. 7.4.0]

**Comment by arif98741** [comment]
![sc](https://user-images.githubusercontent.com/17213478/75154172-59d26580-5737-11ea-8b54-855ab36a3128.PNG)

**Comment by sba** [comment]
same error here with "php spark serve"

error also occures when running on xampp localhost; http://codeigniter4.local/public/ 
with php 7.3.6, Apache 2.4 on win10

**Comment by jlamim** [comment]
I had the same problem

Windows 10 + PHP 7.4 + Apache 2.4.41 (Wamp)

**Comment by niteraven7** [comment]
Same issue with 'php spark serve' not running but different error.

composer updated from rc4 to 4.0.0

php spark serve
An uncaught Exception was encountered

Type:        ErrorException
Message:     Trying to get property 'maxDepth' of non-object
Filename:    /home/parkmo2020/parkmo/vendor/codeigniter4/framework/system/CodeIgniter.php
Line Number: 232

        Backtrace:
                                                -232 - /home/parkmo2020/parkmo/vendor/codeigniter4/framework/system/CodeIgniter.php::errorHandler
                                                                -193 - /home/parkmo2020/parkmo/vendor/codeigniter4/framework/system/CodeIgniter.php::initializeKint
                                                                -168 - /home/parkmo2020/parkmo/vendor/codeigniter4/framework/system/bootstrap.php::initialize
                                                                -44 - /home/parkmo2020/parkmo/spark::require

parkmo2020@cloudshell:~/parkmo (strong-charge-262521)$ php -v
PHP 7.2.28-1+0~20200220.36+debian9~1.gbpcf4a75 (cli) (built: Feb 20 2020 14:17:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.28-1+0~20200220.36+debian9~1.gbpcf4a75, Copyright (c) 1999-2018, by Zend Technologies

on google clould php72

**Comment by arif98741** [comment]
@niteraven7 You are gettin different error with same command **php spark serve**
<br>
strange

**Comment by lonnieezell** [comment]
You all fail to mention whether this is a new install or an existing install. Is this based on the main repo, or the app starter? 

Looks like I still need to learn more about how the release scripts builds things out, since I did change where I thought the composer.json would come from but it didn't seem to propagate correctly. Change Kint version to `3.3` in `composer.json` and do a `composer update`. That should get it working for you.

**Comment by jlamim** [comment]
@lonnieezell I created a new installation to be able to verify this occurrence.

composer create-project codeigniter4/appstarter --no-dev

And I got the error mentioned at the opening of the Issue

**Comment by arif98741** [comment]
its fresh install using **composer create**
<br>
![fg](https://user-images.githubusercontent.com/17213478/75162533-e8e77980-5747-11ea-9e90-a076dc94e8cb.PNG)

**Comment by niteraven7** [comment]
app starter here.
existing install rc4 updated to 4.0.0

**Comment by jlamim** [comment]
@lonnieezell 

I made a new installation from codeigniter4/framework via composer to be able to compare the structure of composer.json in relation to codeigniter4/appstarter and there are differences between the composer.json files.

In codeigniter4/appstarter there is no explicit mention of "kint-php/kint" in 'require'.

The installation with "codeigniter4/framework" worked correctly, but the installation with "codeigniter4/appstarter" presented the reported problem.

When trying to update the kint package via composer (composer require kint-php/php) to the latest stable version in an installation via "codeigniter4/appstarter" it gives an error saying:

Your requirements could not be resolved to an installable set of packages.

```
- codeigniter4 / framework 4.0.0 requires kint-php / kint ^ 2.1 -> satisfiable by kint-php / kint [2.1, 2.1.1, 2.1.2, 2.2, 2.x-dev] but these conflict with your requirements or minimum-stability.
- codeigniter4 / framework 4.0.0 requires kint-php / kint ^ 2.1 -> satisfiable by kint-php / kint [2.1, 2.1.1, 2.1.2, 2.2, 2.x-dev] but these conflict with your requirements or minimum-stability.
- codeigniter4 / framework 4.0.0 requires kint-php / kint ^ 2.1 -> satisfiable by kint-php / kint [2.1, 2.1.1, 2.1.2, 2.2, 2.x-dev] but these conflict with your requirements or minimum-stability.
- Installation request for codeigniter4 / framework ^ 4.0 -> satisfiable by codeigniter4 / framework [4.0.0].
```

From this I believe that the problem lies in the dependency on Kint installed by default when running the "composer create-project codeigniter4/appstarter project-name".

Perhaps an update to composer.json will be enough to solve the problem.

**Comment by jlamim** [comment]
@lonnieezell 

**### codeigniter4/appstarter**
Requires
    php: >=7.2
    codeigniter4/framework: ^4.0

**### codeigniter4/framework**
Requires
    php: >=7.2
    ext-curl: *
    ext-intl: *
    kint-php/kint: ^2.1
    psr/log: ^1.1
    zendframework/zend-escaper: ^2.5

**Comment by DZywolf** [comment]
@lonnieezell the change you made in the framework repo will not work until you delete the old release (4.0.0) and make a new one. also only way to access the change right now is by switching to
"codeigniter4/framework": "dev-master"

**Comment by lonnieezell** [comment]
Yup. Working on it guys. Patience. :)

**Comment by lonnieezell** [comment]
Released 4.0.1 that fixed that. Unfortunately, it is now showing up an issue that I missed when reviewing our tests refactor last night. I won't have time until later tonight to fix that. A temporary fix is to remove the file: `tests/_support/Commands/CommandsTestStreamFilter.php`.

**Comment by enix-app** [comment]
Me too, in Linux Mint.

**Comment by arif98741** [comment]
@enix-app  Kint\Renderer not found in 4.0.1 but new bug appeared. hope it will be fixed soon.
![Uploading Capture.PNG…]()

**Comment by lonnieezell** [comment]
@arif98741  That was mentioned by two comments previously. :)

**Comment by musmanikram** [comment]
> @enix-app Kint\Renderer not found in 4.0.1 but new bug appeared. hope it will be fixed soon.
> ![Capture](https://user-images.githubusercontent.com/17213478/75182522-c9157d00-576a-11ea-95b9-9ae04e81c87d.PNG)

Created fix for this issue: https://github.com/codeigniter4/CodeIgniter4/pull/2609

**Comment by entrinix** [comment]
> Same issue with 'php spark serve' not running but different error.
> 
> composer updated from rc4 to 4.0.0
> 
> php spark serve
> An uncaught Exception was encountered
> 
> Type: ErrorException
> Message: Trying to get property 'maxDepth' of non-object
> Filename: /home/parkmo2020/parkmo/vendor/codeigniter4/framework/system/CodeIgniter.php
> Line Number: 232
> 
> ```
>     Backtrace:
>                                             -232 - /home/parkmo2020/parkmo/vendor/codeigniter4/framework/system/CodeIgniter.php::errorHandler
>                                                             -193 - /home/parkmo2020/parkmo/vendor/codeigniter4/framework/system/CodeIgniter.php::initializeKint
>                                                             -168 - /home/parkmo2020/parkmo/vendor/codeigniter4/framework/system/bootstrap.php::initialize
>                                                             -44 - /home/parkmo2020/parkmo/spark::require
> ```
> 
> parkmo2020@cloudshell:~/parkmo (strong-charge-262521)$ php -v PHP 7.2.28-1+0~20200220.36+debian9~1.gbpcf4a75 (cli) (built: Feb 20 2020 14:17:10) ( NTS ) Copyright (c) 1997-2018 The PHP Group Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache v7.2.28-1+0~20200220.36+debian9~1.gbpcf4a75, Copyright (c) 1999-2018, by Zend Technologies
> 
> on google cloud php72

Copy the file:

https://raw.githubusercontent.com/codeigniter4/CodeIgniter4/develop/app/Config/Kint.php

Into the file "app/Config/Kint.php"

When updating from composer, this file is missing since it's new.  This fixed it for me.

**Comment by lonnieezell** [comment]
Version 4.0.2 released that should fix all of this for a new install. Sorry about the release issues today.

**Comment by vrochanet** [comment]
Thanks for your work..

**Comment by lnavarroa** [comment]
Hi, I have the same problem, but i solved it by rename system/ThirdParty/Kint/kint.php to system/ThirdParty/Kint/Kint.php

**Comment by arif98741** [comment]
@lnavarroa  great. But 4.0.2 already fixed that issue.

**Comment by lonnieezell** [comment]
While updating the filename works, the correct solution is to update Composer to update your version from 2.x  to 3.x like the framework has done, and copy over the new app/Config/Kint.php to your application.

**Comment by kenjis** [comment]
If you got this error with CodeIgniter v4.3,
See https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_430.html#config-files
