### ISSUE TITLE
User Guide is not in HTML in the download file

### ISSUE THREAD

**Issue by jlamim** [codeigniter4/CodeIgniter4#2607]
When downloading the files for a manual installation, the folder "user_guide_src" does not contain documentation in HTML format, which makes it somewhat useless for the user.

I suggest changing the folder name to "user_guide" and replacing the current content with content in HTML format.

**Comment by rmcdahal** [comment]
I think there is a separate repo for user guide section 
https://github.com/codeigniter4/userguide
We can get it from there

**Comment by jlamim** [comment]
Yes, I am aware of the separate repository for the documentation, but since the .zip files have the directory with the documentation, it should be in a user-readable format.

**Comment by arif98741** [comment]
@jlamim  you are right. if something has not usage, why it is necessary?

**Comment by dafriend** [comment]
The current released version is online [here](https://codeigniter4.github.io/userguide/).
And a download of the same is available [here](https://github.com/codeigniter4/userguide/archive/v4.0.2.zip). At the moment though the download is unavailable. It's probably being rebuilt as I write this.

The folder "user_guide_src" is there for developers that want to contribute to the documentation.

But it would be nice to have a built HTML version in a folder ("user_guide")  as it has been for CI v3 and earlier.

**Comment by MGatner** [comment]
I agree the downloaded version should have a prebuilt HTML guide. It looks like there’s some release tweaking happening, this should be part of that.

**Comment by LittleJ** [comment]
@MGatner & @lonnieezell : I am working on the user guide and I can probably help on this. But where would be the best place ? Should we move the "user_guide_src" folder to "admin", create a new "user_guide" folder containing the html version only ?

**Comment by lonnieezell** [comment]
I haven't dove into all of the build scripts yet, but I don't think moving user_guide_src is the issue. It's a bit of a tricky one since the zip file is built through GitHub releases and I don't know how much control over that we have. And I don't know that we want to commit the built user guide into the repo. 

I'm more tempted to say we rip out the user guide form the download altogether. Of course, this means we need to do some work on the main site to make it simple to see user guides for previous versions of the framework, which is on my short list of changes for the main site once I manage to actually get the credentials for hosting....

**Comment by LittleJ** [comment]
@lonnieezell  Versioning is managed by RTD, could be a solution https://readthedocs.org/

**Comment by MGatner** [comment]
@lonnieezell When I have some time I would like to take a pass at refining releases, maybe implement some of the asset artifacts we talked about via GitHub Actions. IMO the “manual download” should be a curated list of files from the `codeigniter4/appstarter` (or `codeigniter4/framework` if it really must) that includes things like the compiled User Guide, but not things like the User Guide source. I do agree that this repo should stay the same though, no major moving of things.

**Comment by LittleJ** [comment]
I stay available if any help is needed 😉

**Comment by lonnieezell** [comment]
@MGatner I would like to look at using GitHub actions more, maybe even to replace Travis down the road. But I think you're right there's other things it could do for us, maybe even doing an automatic docs build and release when pull requests are merged. 

Also - I think most of our release woes for the download file are probably solved by using /framework for the downloads and not fighting with the main repo.

**Comment by dafriend** [comment]
One thing I think would be useful is for the online (HTML) version of the guide to be rebuilt more often. Changes to the docs would often be of great value to the community that is trying to figure out the new framework. Having the docs update only on a new release hides critical knowledge from the public longer than it should.

**Comment by lonnieezell** [comment]
@dafriend Jim used to update it pretty regularly but I have not been so good at it. That's part of the reason I would like to see it automated. :)

**Comment by dafriend** [comment]
If I can help by minding that part of the store until the automation is in place let me know.

**Comment by lonnieezell** [comment]
@dafriend thanks. I did find a couple of existing GitHub Actions that should take care of building and deploying the master branch so it should get in place pretty quickly.
