### ISSUE TITLE
Bug: Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by afrizal423** [codeigniter4/CodeIgniter4#2613]
$ composer create-project codeigniter4/appstarter ci4                                                                   Installing codeigniter4/appstarter (v4.0.1)
  - Installing codeigniter4/appstarter (v4.0.1): Downloading (100%)
Created project in ci4
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for codeigniter4/framework ^4.0.1 -> satisfiable by codeigniter4/framework[v4.0.1].
    - codeigniter4/framework v4.0.1 requires ext-intl * -> the requested PHP extension intl is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by odilodesderykasimbazi** [comment]
please help me to resolve the problem occured when trying to install codeigniter project via composer

$ composer create-project codeigniter4/appstarter first-Project
Creating a "codeigniter4/appstarter" project at "./first-Project"
Installing codeigniter4/appstarter (v4.3.5)
  - Installing codeigniter4/appstarter (v4.3.5): Extracting archive
Created project in D:\project\codeigproject\first-Project
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codeigniter4/framework[4.0.0, ..., v4.3.5] require ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
    - Root composer.json requires codeigniter4/framework ^4.0 -> satisfiable by codeigniter4/framework[4.0.0, ..., v4.3.5].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-intl` to temporarily ignore these required extensions.

**Comment by paulbalandan** [comment]
Please refer to the [official forum](https://forum.codeigniter.com) for your support questions. Thank you.
