### ISSUE TITLE
Bug: spark migrate -all with appstarter

### ISSUE THREAD

**Issue by michalsn** [codeigniter4/CodeIgniter4#2627]
**Describe the bug**
Running `php spark migrate -all` also run migrations for core system tests.
This is happening only when using appstarter. When I tested zip version, there were no issues.

```console
php spark migrate -all

CodeIgniter CLI Tool - Version 4.0.2 - Server-Time: 2020-02-26 05:21:26am

Running all new migrations...
	Running: (Tests\Support) 20160428212500_Tests\Support\Database\Migrations\Migration_Create_test_tables
	Running: (Tests\Support) 2020-02-22-222222_Tests\Support\Database\Migrations\ExampleMigration
Done
```

**CodeIgniter 4 version**
I'm using CI 4.0.2 (appstarter) installed via Composer.
`composer create-project codeigniter4/appstarter --no-dev .`

**Comment by jlamim** [comment]
I have tested using the installation with Composer "codeigntier4/framework" and also with manuall installation by ZIP file and I have succesfully with both.

Only Composer installation with "codeigniter4/appstarter" present error.

I removed the "tests" directory in my "appstarter" installation and the error not ocurred.

**Comment by MGatner** [comment]
`ExampleMigration` is specified to run against DBTests so should be skipped during normal discovery, even though the namespace is now defined under Composer’s `autoload-dev`. @michalsn I think that was actually your code originally? Any ideas why it would be included?

https://github.com/codeigniter4/CodeIgniter4/blob/develop/admin/starter/tests/_support/Database/Migrations/2020-02-22-222222_example_migration.php

**Comment by michalsn** [comment]
Hmm... I guess it might be my fault then. I wasn't thinking about our testing environment when I was doing some changes to MigrationRunner class and I missed that not skipping test group by default could be a problem.

Since we hardcode some variables in the Database config file when we are in a testing environment, I came up with a simple fix that should be good enough.

Oh... and fun fact... I still get this additional migration file `20160428212500_Create_test_tables.php` ...idk why and where it comes from because I don't see it in the repo, but it's there.

**Comment by MGatner** [comment]
That’s the same file but it’s old name - when I ported all the AppStarter Test\Support files to “Example____” I renamed it to ExampleMigration. If you’re still getting that file then likely it failed to be removed in a release. It also might mean that it doesn’t have the appropriate DBGroup set at the class header, so definitely track that down first in case this is a deployment issue instead of a MigrationRunner one.

**Comment by MGatner** [comment]
Yeah this file should not be in the repo anymore:

https://github.com/codeigniter4/appstarter/blob/master/tests/_support/Database/Migrations/20160428212500_Create_test_tables.php

Nor should most of what is in tests/_support. @lonnieezell!
