### ISSUE TITLE
While serving Application on CLI using different port debugbar is still using a default 8080 port

### ISSUE THREAD

**Issue by ManojKiranA** [codeigniter4/CodeIgniter4#2630]
**Describe the bug**
While serving Application on CLI using different port `debugbar `is still using a default `8080` port

**CodeIgniter 4 version**
`4.0.2`

**Affected module(s)**
Which package or class is the bug in, if known.

**Expected behavior, and steps to reproduce if appropriate**

Since i am using multiple php version. I have configured port `8080` to `apache` 

so I am serving in different port

```
php spark serve --port 1234

CodeIgniter CLI Tool - Version 4.0.2 - Server-Time: 2020-02-27 00:55:59am

CodeIgniter development server started on http://localhost:1234
```

![image](https://user-images.githubusercontent.com/30294553/75420089-3ab51d00-595d-11ea-9472-2b22c12f34f6.png)

**Context** 
 - OS: [Windows 10]
 - PHP version [7.3.11]

**Comment by michalsn** [comment]
Not a bug. Using `php spark serve --port 1234` won't magically change baseURL in config or .env file for you. You have to do it yourself.

**Comment by ManojKiranA** [comment]
> won't magically change baseURL in config or .env file

Thanks for the Fast reply sir. I haven't seen any docs regarding that. 

I was thinking in a way that it will be automatically changed like Laravel framework

sorry for that.

P.S- I am new to codeigniter.
