### ISSUE TITLE
BUG: 4.0.2 Kint not found

### ISSUE THREAD

**Issue by addictedtoberlin** [codeigniter4/CodeIgniter4#2639]
**Describe the bug**
I just started with a fresh install of CI 4.0.2 and set it to development mode but I get an Error: Kint not found. Same when I use CLI to call public/index.php

**CodeIgniter 4 version**
git 4.0.2 Artifact

**Affected module(s)**
Kint Class

Expected behavior, and steps to reproduce if appropriate
Download release tar. Deflate and set Document Root to public.

    Type:        Error
    Message:     Class 'Kint\Kint' not found
    Filename:    /var/www/html/ci4/system/ThirdParty/Kint/init.php
    Line Number: 46

    45 // Dynamic default settings
    46 Kint::$file_link_format = \ini_get('xdebug.file_link_format');
    47 if (isset($_SERVER['DOCUMENT_ROOT'])) {
    48     Kint::$app_root_dirs = array(
    49         $_SERVER['DOCUMENT_ROOT'] => '<ROOT>',
    50         \realpath($_SERVER['DOCUMENT_ROOT']) => '<ROOT>',

**Context**

    OS: Ubuntu 19.10
    Web:  Apache/2.4.41 (Ubuntu) + php-fpm
    PHP: 7.3.11

**Comment by addictedtoberlin** [comment]
I can reproduce it with same configuration on RHEL 8.1:

**Context**

    OS:  Red Hat Enterprise Linux 8.1
    Web: Apache/2.4.37 (RHEL)
    PHP: 7.2.11

**Comment by ST-o-RM** [comment]
Obviously this problem is in the repository https://github.com/codeigniter4/framework
where the file kint.php begins with a small letter
https://github.com/codeigniter4/framework/tree/master/system/ThirdParty/Kint/
change it to capital letter

**Comment by addictedtoberlin** [comment]
You're right. Thanks.
