### ISSUE TITLE
set ci4 repo default branch = master

### ISSUE THREAD

**Issue by tanhaipeng** [codeigniter4/CodeIgniter4#2643]
Please ask support questions on our [forum](https://forum.codeigniter.com/forum-30.html).
We use github issues to track bugs and planned work.

set ci4 repo default branch = master

**Comment by lonnieezell** [comment]
For what purpose? The main repo is intended for framework development. The framework repo is intended for user-facing usage.

**Comment by MGatner** [comment]
`framework` already defaults to master. This repo (`CodeIgniter4`) has to use default `develop` for PRs to be routed correctly. Read up on Git Flow if you have more questions.
