### ISSUE TITLE
Bug: spark no longer lists function when used by without any parameters

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#2645]
in 4.0.2 when issuing the command: `php spark` it should run the `list` command. It currently shows the help instead.

**Comment by MGatner** [comment]
I feel pretty confident this is collateral from https://github.com/codeigniter4/CodeIgniter4/pull/2571

**Comment by lonnieezell** [comment]
@MGatner that was my guess as well. Just had to log it so we could get it fixed since I saw it in the forums.
