### ISSUE TITLE
Bug: Route options filter didn't working 

### ISSUE THREAD

**Issue by gaibz** [codeigniter4/CodeIgniter4#2654]
I think I found a bug in Route options Filter .. 

Using codeigniter 4.0 latest release from composer repository .. 

I have the following config on my routes.php 

> `$routes->post('closed/auth', 'Closed\Auth::auth', ['filter'=>'coba']);`

and have the following config on my filters.php

> `public $aliases = [  'coba' => \App\Filters\CobaFilter::class ];`

and then on my CobaFilter.php under Filters folder 

> `<?php`
>
> namespace App\Filters;
> 
> use CodeIgniter\HTTP\RequestInterface;
> use CodeIgniter\HTTP\ResponseInterface;
> use CodeIgniter\Filters\FilterInterface;
> 
>
> class CobaFilter implements FilterInterface
> {
>    public function before(RequestInterface $request)
>    {
>        die($request); // not executed 
>    }
>
>    public function after(RequestInterface $request, ResponseInterface $response)
>    {
>        return $response;
>    }
>  }`

But if i have group routes config it just work .. i.e (routes.php): 

>    $routes->group('closed', ['filter'=>'coba'], function($routes) 
>    {
>             $routes->post('auth',  'Closed\Auth::auth');
>    });

I'm not quiet sure if this is a bug or just my mistake .. 
i just follow the documentation page : https://codeigniter4.github.io/userguide/incoming/routing.html#applying-filters

Hope you guys find a solution for this ..

**Comment by MGatner** [comment]
Does `closed/auth` actually route in your first example, and just the filter doesn’t run? Can you also turn off autorouting to be sure it’s matching your definition?

**Comment by michalsn** [comment]
I couldn't recreate this bug. The filters in both cases work for me just fine. 

Are you sure you're testing this with `post` request?

**Comment by gaibz** [comment]
> Does `closed/auth` actually route in your first example, and just the filter doesn’t run? Can you also turn off autorouting to be sure it’s matching your definition?

yes, `closed/auth` is routed to my controller perfectly with post request .. 
it just the filter didn't work .. 
in the example above I try to `die($request)` or `die(var_export($request)` execution to see if filter work before hitting the controller .. but `before()` function on my Filter didn't triggering at all .. 

well i'll try to turn off autorouting to see if it working ..

**Comment by gaibz** [comment]
> I couldn't recreate this bug. The filters in both cases work for me just fine.
> 
> Are you sure you're testing this with `post` request?

yep, i am pretty sure that i send `post` request with my Postman ..

**Comment by bangbangda** [comment]
@gaibz 

CobaFilter is run. Replace `die($request); ` with `var_dump($request);exit;`. Try again.

`public function before(RequestInterface $request)
{
     var_dump($request);exit;
}`

**Comment by gaibz** [comment]
> @gaibz
> CobaFilter is run. Replace `die($request); ` with `var_dump($request);exit;`. Try again.
> 
> ```
> public function before(RequestInterface $request)
> {
>      var_dump($request);exit;
> }
> ```
> 
> die($request); will only exit and will not output anything.
> Do you mean that the program has not exited?

yes i know die($request) will only exit and not output anything .. 
but the problem is die() never firing in my case .. the script execution didn't stop at all ..

**Comment by gaibz** [comment]
well, after all i guess  grouping routes 
```php
$routes->group('closed', ['filter'=>'coba'], function($routes)
{
    $routes->post('auth', 'Closed\Auth::auth');
});
```
is the best solution that work in my case  .. 

Thanks all ..
