### ISSUE TITLE
I guess there's no the third parameter

### ISSUE THREAD

**Issue by Qnurye** [codeigniter4/CodeIgniter4#2657]
The document may be problematic : 

[today()](https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/libraries/time.rst#today) , [yesterday()](https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/libraries/time.rst#yesterday) , [tomorrow()](https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/libraries/time.rst#tomorrow)

**Comment by jlamim** [comment]
@Qnurye Excellent observation. I have already made the correction in the documentation and it will soon be applied.
