### ISSUE TITLE
Bug: \I18n\Time object displaying +1 year when object date is set to 2021-12-31

### ISSUE THREAD

**Issue by fefo-p** [codeigniter4/CodeIgniter4#2663]
**Describe the bug**
Got the following object:
`CodeIgniter\I18n\Time (6) 2021-12-31 19:34:42-03:00 -03` retrieved from DB

I use `$oc->periodoFin->toLocalizedString("dd'-'MM'-'YYYY")` to echo it to screen and what I get is `31-12-2022`. I tried using `$oc->periodoFin->getYear()` and It still returns `2022`. (actually, I tried every method I could think of, same result).
On the other hand, when I post that variable with the correct date, it's saved successfully into the DB.
Also, if I d() the object onto the screen (same where the printing error occurs), I get the correct result (`CodeIgniter\I18n\Time (6) 2021-12-31 19:34:42-03:00 -03`).

This happens with dates ranging from `2021-12-26` till `2021-12-31` (both included).
If I use `2021-12-25` or `2022-01-01` (or any other date for that matter) things work as expected.

**UPDATE**
If I just echo $oc->periodoFin then date gets printed correctly, though not in the format I need it to be showed in.

**CodeIgniter 4 version**
4.0.0 final
**Affected module(s)**
CodeIgniter\I18n\Time

**Context**
 - OS: macOS 13.0.5
 - Web server:  Apache/2.4.41 (Unix)
 - PHP version: 7.3.8

**Comment by Instrye** [comment]
“YYYY ” is week-based-year, you can use "yyyy"

**Comment by Instrye** [comment]
I think `getYear` and `getWeekyear` can't normal work. i'm try fix.
