### ISSUE TITLE
Bug: php spark migrate:create File -n NameSpace doesn't create migration class under NameSpace/Database/Migrations directory with composer autoload

### ISSUE THREAD

**Issue by samsonasik** [codeigniter4/CodeIgniter4#2664]
Currently, when running migration create for module namespace, eg: Album, while Album namespace already in composer autolaod, it doesn't create the migration class to `Album/Database/Migrations` directory. Instead, It created file in `app/Database/Migrations` directory.

It needs manually add 'namespace' to `Config/Autoload` class under `app/Config` directory:

```php
		$psr4 = [
			'App'         => APPPATH,                // To ensure filters, etc still found,
			APP_NAMESPACE => APPPATH,                // For custom namespace
			'Config'      => APPPATH . 'Config',
			'Album'       => ROOTPATH . 'modules/Album',
		];
```

to make it generated to correct `Album/Database/Migrations` directory, while I think it should not, as `Album` namespace already in composer.json autoload:

```javascript
	"autoload": {
		"psr-4": {
			"Album\\": "modules/Album"
		}
	},
```

**CodeIgniter 4 version**
4.0.2

**Expected behavior, and steps to reproduce if appropriate**
It create the migration class to Album/Database/Migrations directory:

**Context**
 - OS: OSX
 - Web server: Apache
 - PHP version 7.4

**Comment by MGatner** [comment]
It looks like `CreateMigration` is using an old way of searching namespaces, maybe the code is older?

https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Commands/Database/CreateMigration.php#L127

I think switching this to use `Autoloader:: getNamespace()` should fix the issue.
