### ISSUE TITLE
RESTFUL API with CORS problem

### ISSUE THREAD

**Issue by gilvandev** [codeigniter4/CodeIgniter4#2667]
I know this is not the ideal place to share my problem, but I can't post in the forum because the confirmation email never comes to my inbox.

Well, I started a new API RESTFUL with CI4 and is awesome! But, I have a big problem with CORS in my Angular 9 app. I try this [https://carminemilieni.it/2019/09/19/resolve-cors-and-corb-in-codeigniter-4/](https://carminemilieni.it/2019/09/19/resolve-cors-and-corb-in-codeigniter-4/) but no success.

I tried to overwrite the construct method calling a CORS function (as I've maded with CI3) but the same problem. I really want to use the new CI4 but this project needs to show some results in the next week... If I have help and solve this...if no, I needs to step back to CI3

**Comment by arif-rh** [comment]
@gilvandev 

Try to add this code in your `.htaccess`

```
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
</IfModule>
```

**Comment by zee85** [comment]
That link you posted is your website. I'm not surprised. The people who use CI are not very nice. They lie, steal, cheat. They are the personification of yourself. Someone who uses github for their own gain. Not to promote a useful piece of software, Na… someone like yourself. Someone who has no talent, skill, and probably belongs greeting people at a walmasrt.

**Comment by MGatner** [comment]
@zee85 if you have concerns about spam or endorsement please contact the project team via Slack or the forums. Comments should be on-topic and civil.

**Comment by zee85** [comment]
I do back side development. Please forgive me.

**Comment by zee85** [comment]
Dude who started this thread doesn't even exist.

**Comment by gilvandev** [comment]
@arif-rh thank you so much! It was very helpful. I has tested yesterday and solved the problem. I added another line to your code:

`Header set Access-Control-Allow-Headers "*"`

And @zee85 I'm really sorry about your comments. I really don't contribute with Github projects because I'm a free lancer and I have other jobs in my life. I exist! And I'm fully occuped with other responsabilities. It would be wonderful if we lived in a world where people had 24 hours a day to contribute here rather than spreading hate and making unsubstantiated comments.

Congrats CI community for the excellent job with CI4. I really appreciate it!

**Comment by Nguyenthanhphat9991** [comment]
> @arif-rh thank you so much! It was very helpful. I has tested yesterday and solved the problem. I added another line to your code:
> 
> `Header set Access-Control-Allow-Headers "*"`
> 
> And @zee85 I'm really sorry about your comments. I really don't contribute with Github projects because I'm a free lancer and I have other jobs in my life. I exist! And I'm fully occuped with other responsabilities. It would be wonderful if we lived in a world where people had 24 hours a day to contribute here rather than spreading hate and making unsubstantiated comments.
> 
> Congrats CI community for the excellent job with CI4. I really appreciate it!

please tell me what folder did you put the . htaccess in <3

**Comment by ypkkhatri** [comment]
> > @arif-rh thank you so much! It was very helpful. I has tested yesterday and solved the problem. I added another line to your code:
> > `Header set Access-Control-Allow-Headers "*"`
> > And @zee85 I'm really sorry about your comments. I really don't contribute with Github projects because I'm a free lancer and I have other jobs in my life. I exist! And I'm fully occuped with other responsabilities. It would be wonderful if we lived in a world where people had 24 hours a day to contribute here rather than spreading hate and making unsubstantiated comments.
> > Congrats CI community for the excellent job with CI4. I really appreciate it!
> 
> please tell me what folder did you put the . htaccess in <3

Its already in the public folder of the codeigniter project
