### ISSUE TITLE
OpenSSLHandler: Encrypt/Decrypt

### ISSUE THREAD

**Issue by RedskyThirty** [codeigniter4/CodeIgniter4#2680]
I have some problem sometimes. An encrypted string cannot be decrypted. I get the error :

> Decrypting: authentication failed.
> system/Encryption/Handlers/OpenSSLHandler.php(160): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()

Have you heard other people who met the same problem?

Also, can you verify this:
www/system/Encryption/Handlers/OpenSSLHandler.php - Line 130
"@throws \CodeIgniter\Encryption\EncryptionException" is not correct. It must be "@throws \CodeIgniter\Encryption\Exceptions\EncryptionException" or "@throws EncryptionException". Isn't it?
And line 148: Method "forStarterKeyNeeded" is not defined.

**Comment by musmanikram** [comment]
@RedskyThirty Can you please post your code here?
Yes the other points are valid and creating a PR soon
