### ISSUE TITLE
Bug: $routes->cli() accessible via web browser if autoroute is true

### ISSUE THREAD

**Issue by samsonasik** [codeigniter4/CodeIgniter4#2704]
For example, I have the following  `cli` route: 

```php 
// set auto route to true
$routes->setAutoRoute(true); 

// set "hello" cli route
$routes->cli('hello', 'Commands\Hello::index');
```

and I have the controller: 

```php 
<?php
namespace App\Controllers\Commands;

use App\Controllers\BaseController;

class Hello extends BaseController
{
    public function index()
    {
        echo 'Hello';
    }
}
```

then, I open it via web browser, it still accesible via : `http://ci4.local/commands/hello` , it still accessible.

**CodeIgniter 4 version**
4.0.2

**Expected behavior, and steps to reproduce if appropriate**

By define `cli()`, it should decline the http access into it. The documentation doesn't say it require autoroute to be false: 

```
You can create routes that work only from the command-line, and are inaccessible from the web browser, with the cli() method
```

**Context**
 - OS: OSX
 - Web server Apache
 - PHP version 7.4

**Comment by samsonasik** [comment]
I've created PR #2707 for it

**Comment by kenjis** [comment]
`app/Config/Routes.php`:
```php
$routes->setAutoRoute(true);
 
$routes->cli('hello/(:segment)', 'Home::$1');
```

We can access:
`http://localhost:8080/home`
`http://localhost:8080/home/index`

**Comment by lonnieezell** [comment]
@kenjis Auto-routing is a different bag of worms. Unfortunately, it's how CodeIgniter apps have always worked, too.

**Comment by Kr3m** [comment]
I should add this for anyone who might stumble across it that needs a solution.

```
if(is_cli()) {
 echo "Hello";
}
```
Then you could create an else block to redirect them to a 404.
