### ISSUE TITLE
Bug: calling countAllResults after find($id) produce wrong result

### ISSUE THREAD

**Issue by arif-rh** [codeigniter4/CodeIgniter4#2705]
**Describe the bug** 

calling `countAllResults` after `find($id)` produce wrong result. for example, I made below tests:

````php
    public function testFindIdCountAllResults()
	{
		$model = new UserModel($this->db);

		$model->find(1);

		$this->assertEquals(1, $model->countAllResults());
	}

	public function testFindArrayCountAllResults()
	{
		$model = new UserModel($this->db);

		$model->find([1,2]);

		$this->assertEquals(2, $model->countAllResults());
	}
````
and both produce an error, because all `countAllResults` is 4

![find countAllResults](https://user-images.githubusercontent.com/2386359/76695636-76b5e500-66b4-11ea-9a9f-d230aa6f779d.png)

This issue only happen when we passing `$id` to `find` method. If we omit it, it will work fine, because without passing `$id` it will call `findAll` instead.

**CodeIgniter 4 version** 

4.0.2

**Affected module(s)** 

CodeIgniter\Model

**Expected behavior, and steps to reproduce if appropriate** 

Make test as description above to reproduce the issue

**Context**

- OS: Windows 10
- Web server Apache 2.4.37
- PHP version 7.3.1

**Comment by lonnieezell** [comment]
To the best of my knowledge that's not how the `count_all_results()` method in previous versions of CI3 ever worked, and it's not how the method is intended to work in CI4 either. 

if you do `$users = $model->find(1)` it returns a `Result` instance. All you have to do is grab the results from that and `count()` the results. This method is intended to perform a `COUNT` query on the database itself.
