### ISSUE TITLE
Array validation has a problem

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#2714]
Hello!

I am trying to validate an array structure that comes from my form:
```html
<input type="checkbox" name="category[]" value="id2">
<input type="checkbox" name="category[]" value="id3">
<input type="checkbox" name="category[]" value="id4">
```

I use the validation library dynamically building the rules for each field which would arrive as `category.0`, `category.1` ... 

```php
foreach($data['categorie'] as $key => $value){
    $rules[ 'category.' . $key ] = 'required|alpha|max_length[2]';
}  
```
validation only works well for all values that have key 1 forwards, but does not correctly identify the field that is in the `category.0` position validation fails with "field is required"

```php
 ["category.0"]=>
  string(34) "The categorie.0 field is required.
```

I have debugged that all the fields get to my controller correctly but it seems to be a validation library error.

thank you very much for your amazing work!

**Comment by musmanikram** [comment]
@luispastendev I  tried your code and it worked fine. REturn me these errors:

```Array ( [categorie.0] => The categorie.0 field is required. [categorie.1] => The categorie.1 field is required. [categorie.2] => The categorie.2 field is required. )```

Also i see spelling mistake in your code. in html you are writing `category` and in php loop you are using 
`$data['categorie']` 

Also please make sure you have latest CI4 version i.e `4.0.2`

**Comment by luispastendev** [comment]
@musmanikram thanks for answering!

I actually had an error in the key name, but I still have that problem I have CI version 4.0.2. and the array that comes from the html is different from the one you wrote in your test

this is the body of my request:
```php
["categorie"]=>
  array(5) {
    [0]=>
    string(3) "id2"
    [1]=>
    string(2) "id"
    [2]=>
    string(2) "id"
  }
```
but despite being sending values in my checkboxes, the value of position 0 cannot read it (as if I was not sending anything).

try assigning a value to the key and only then can I solve it:
```php
// HTML
<input type="checkbox" name="category[key1]" value="id2">
<input type="checkbox" name="category[key2]" value="id3">
<input type="checkbox" name="category[key3]" value="id4">

// REQUEST STRUCTURE
["categorie"]=>
  array(3) {
    ["key1"]=>
    string(2) "id"
    ["key2"]=>
    string(2) "id"
    ["key3"]=>
    string(2) "id"
  }

//CONTROLLER
foreach($categories as $key => $cat){
    $rules[ 'category.' . $key ] = 'required|alpha|max_length[2]';
}
```

I show you a test that I carry out with the following code:
```php
$validation =  \Config\Services::validation();
        
foreach($this->request->getPost('category') as $key => $cat){
  $rules[ 'category.' . $key ] = 'required|alpha|max_length[2]';
}
$validation->setRules($rules);
$validation->withRequest($this->request)->run();
var_dump($validation->getErrors());
```
result: 
![imagen](https://user-images.githubusercontent.com/4117596/77004935-8ab44d80-6925-11ea-955b-182cbb0af833.png)

greetings!

**Comment by musmanikram** [comment]
@luispastendev  i think i found the issue. But verifying it first. Then will create a PR.

**Comment by musmanikram** [comment]
@luispastendev , please have a look at my PR and you will find a fix.

replace ```php
empty($currentIndex)
```
 with this 
```php
(empty($currentIndex)  && intval($currentIndex) !== 0)
```

at line `82` in `system/Helpers/array_helper.php` file

**Comment by luispastendev** [comment]
@musmanikram awesome the PR solved the problem!

Thanks a lot !

**Comment by musmanikram** [comment]
> @musmanikram awesome the PR solved the problem!
> 
> Thanks a lot !

![](https://media2.giphy.com/media/Kf0OnhCss3AO0Kema1/giphy.gif)
