### ISSUE TITLE
Bug: $this->request->getPost() is empty when json is send by postman

### ISSUE THREAD

**Issue by uzairali001** [codeigniter4/CodeIgniter4#2720]
**Describe the bug**
When JSON data is sent via postman `$this->request->getPost()` always stays empty even `$_POST` stays empty. although `file_get_contents('php://input')` shows the data. 

what could be the problem and how do I fix it?

**CodeIgniter 4 version**
4.0.2

**Context**
 - OS: Windows 10
 - Web server Apache 2.4.35
 - PHP version 7.4.0

**Comment by lonnieezell** [comment]
First - please ask for support on the forums. We use GitHub for bug tracking. 

Second - json data is never available as a POST variable in PHP. Try `getJSON()` instead. See [this part of the user guide](https://codeigniter4.github.io/CodeIgniter4/incoming/incomingrequest.html#retrieving-input).
