### ISSUE TITLE
Bug: Logger `path` property ignored

### ISSUE THREAD

**Issue by dafriend** [codeigniter4/CodeIgniter4#2725]
CI V 4.0.2 on develop at commit 84b9cc

**Affected module(s)**
``CodeIgniter\Log\Logger``

**Expected behavior, and steps to reproduce if appropriate**
``Config\Logger::path`` setting is not used as the value for where to save log files.

Reproduce by setting some folder other than the default in ``Config\Logger::path``  e.g.

    public $path = WRITEPATH . 'uploads/';

Then log something somewhere, e.g.

```
<?php namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
	$this->logger->emergency("This will not be written to a file in the WRITEPATH/uploads folder");
	return view('welcome_message');
    }
}
```

File will be written to  `WRITEPATH/logs` instead of `WRITEPATH/luploads`.

**Context**
 - Linux Debian 10
 - Apache/2.4.38 (Debian)
 - PHP version  7.3.14

**Comment by samsonasik** [comment]
@dafriend I've created PR #2726 for it. Move the read config "path" read to under `Logger::handlers['CodeIgniter\Log\Handlers\FileHandler']` with not isset and empty string check.
