### ISSUE TITLE
Bug: codeigniter4 download link 404 resource not found

### ISSUE THREAD

**Issue by naolArega** [codeigniter4/CodeIgniter4#2727]
on codeigniter website the link to download codeigniter4 directs to v4.0.2 which says it is not available but if changed to v4.0.1 it works. change the link to v4.0.1 or upload the v4.0.2.

**Comment by MGatner** [comment]
There are still some lingering hosting issues from the transition of ownership after Jim passed. I think this is known and in the works but I'll leave it open as a note for others who may have issues.

For now use the links from the User Guide (https://codeigniter4.github.io/userguide/installation/index.html)

**Comment by lonnieezell** [comment]
Thanks to @MGatner having a chance to dig into this today, it has been resolved and should now be working.
