### ISSUE TITLE
Bug: set_radio() in Form Helper does not work when radio button value equals "0"

### ISSUE THREAD

**Issue by joshdentremont** [codeigniter4/CodeIgniter4#2728]
If your radio button has the value "0" the set_radio() function will not output "checked='checked'" if that value had been clicked. 

I believe this is because empty("0") returns true in the line at https://github.com/codeigniter4/CodeIgniter4/blob/54d370f5658583cab58be3c34fb8d46ec45fc85f/system/Helpers/form_helper.php#L894

If you add `<input type="radio" name="myradio" value="0" <?php echo  set_radio('myradio', '0'); ?> />` to a form you can see that it will not stay checked on submission.

**Comment by MGatner** [comment]
You’re very right! Should be a quick fix plus a new test case. Thanks for reporting.

**Comment by musmanikram** [comment]
@MGatner @jonlabelle will look into this

**Comment by musmanikram** [comment]
@MGatner  @joshdentremont PR is there. Same issue was in checkbox also. Fixed that too :)
