### ISSUE TITLE
The problem is in getting the file sharing by Mime

### ISSUE THREAD

**Issue by demortx** [codeigniter4/CodeIgniter4#2732]
https://github.com/codeigniter4/CodeIgniter4/blob/84b9cc7db148ebd66090ff246a7c0bb63d0d7732/system/HTTP/Files/UploadedFile.php#L363

I’m definitely not sure, but I ran into a problem, when downloading a file it doesn’t determine the exact extension by Mime, in my code, an error was made in the Mime source in the code.

If so, let me know I will fix it.

Now you can upload any file simply by changing the extension from .php to .png and the validator will not notice

Fix?
return Mimes::guessExtensionFromType($this->getMimeType(), $.....

**Comment by MGatner** [comment]
Since actual MIME type detection is imperfect I think the choice was to go with the extension since it is a simpler and more predictable solution. I'll see if @lonnieezell has anything else to say.
