### ISSUE TITLE
Error: Call to undefined function CodeIgniter\CLI\mb_strpos()

### ISSUE THREAD

**Issue by barentshavet** [codeigniter4/CodeIgniter4#2746]
I'm receiving the following error when running `php spark migrate -all`.

```
sigve@plesk-ubuntu-s-4vcpu-8gb-ams3-01:~/app$ php spark migrate -all
An uncaught Exception was encountered

Type:        Error
Message:     Call to undefined function CodeIgniter\CLI\mb_strpos()
Filename:    /var/www/vhosts/cateringtest.eu/app/vendor/codeigniter4/framework/system/CLI/CLI.php
Line Number: 712
```

How do I go around this?

**Comment by MGatner** [comment]
GitHub is for bug reports - please open support requests on the forums.

Incidentally it looks to me like you are missing the `php-mbstring` extension. Please review the server requirements: https://codeigniter4.github.io/userguide/intro/requirements.html
