### ISSUE TITLE
datamap Entities not works!

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#2747]
Hello!

I am trying to save an entity class in my database, but at the time of mapping my values it cannot save them in the database

after validating my data I get my entity class to save it,
```php
$discount = new Discount();
$discount->price = $this->request->getVar('price_discount');
$discount->date_from = $this->request->getVar('date_from');
$discount->date_until = $this->request->getVar('date_until');
```
My entity class is like this
```php
class Discount extends Entity{

    protected $attributes = [
        'price_discount' => null,
        'date_from' => null,
        'date_until' => null
    ];

    protected $datamap = [
        'price' => 'price_discount',
        'valid_from' => 'date_from',
        'valid_until' => 'date_until'
    ];

}
```
My model class allows saving those fields
```php
    protected $table      = 'discounts';
    protected $primaryKey = 'id';
    protected $returnType = 'App\Entities\Discount';
    protected $allowedFields = [
        'price','valid_from','valid_until'
    ];
```
The record manages to be saved but the fields defined in the datamap variable are not saved ...
I have tried to debug the query with `$this->modelDiscount->getLastQuery();` and in effect does not generate the insertion of those fields

grettings!!

**Comment by fefo-p** [comment]
You are not specifying the entity's ID.
**First you need to get the entity from the DB**,
then assign the new values,
then save.

**Comment by luispastendev** [comment]
In

> 
> 
> You are not specifying the entity's ID.
> **First you need to get the entity from the DB**,
> then assign the new values,
> then save.

Hello! I am not trying to update a record. I am trying to create new `save()` records as the documentation works to update and to insert. I have also tried `insert()` but it does not save my records as indicated in `$datamap`

Grettings!

**Comment by fefo-p** [comment]
Sorry, you're right. Deleted the message as soon as I realised, but it was already late :)

**Comment by Tada5hi** [comment]
Hey, 

i run in these problems few weeks ago too. I already created a customized version of the Entity class, so i didn't make a pull request cause i was already in hustle to get a projekt working, which includes a full featured orm on top of the codeigniter database library.

You have to provide a way, to get der reverse data mapping on grud operation to the database, because the entity classs maps all database field identifier to pseudo identifier, and when you grab all attributes you get an array of pseudo identifiers.
So you need for example a additional methods for 
1. getting the reverse data map 
2. get the "raw" (db) field - value mapping. So you have to loop over the existing pseudoKey - value pairs and check if the key exists in the data map if so replace the key.

Hope this helps, if you wish i can make a pull request. :)

Greetings

**Comment by michalsn** [comment]
Entities work just fine.

The only problem I see here is `$allowedFields` array in the model class. It should contain field names after fields mapping: `'price_discount', 'date_from', 'date_until'`.

In short - use real field names from database in your model.

**Comment by luispastendev** [comment]
> 
> 
> Hey,
> 
> i run in these problems few weeks ago too. I already created a customized version of the Entity class, so i didn't make a pull request cause i was already in hustle to get a projekt working, which includes a full featured orm on top of the codeigniter database library.
> 
> You have to provide a way, to get the reverse data mapping on grud operation to the database, because the entity classs maps all database field identifier to pseudo identifier, and when you grab all attributes you get an array of pseudo identifiers.
> So you need for example a additional methods for
> 
>     1. getting the reverse data map
> 
>     2. get the "raw" (db) field - value mapping. So you have to loop over the existing pseudoKey - value pairs and check if the key exists in the data map if so replace the key.
> 
> 
> Hope this helps, if you wish i can make a pull request. :)
> 
> Greetings

Great, I have not had time to review the code of the entities, I would very much appreciate if you could send a PL to see your solution

Thank you!

**Comment by lonnieezell** [comment]
As @michalsn says - it works currently. Use the database field names and you should be good there.
