### ISSUE TITLE
Bug: Official Site is not working

### ISSUE THREAD

**Issue by yigitsayan** [codeigniter4/CodeIgniter4#2749]
https://codeigniter.com/ is not working and returns 500

**Comment by lonnieezell** [comment]
Thanks. That was reported yesterday. I've been working with hosting to actually get access to the VPS. It looks like I have them now, so I should be able to investigate tonight.

**Comment by arma7x** [comment]
Maybe problem with the `writable` folder permission ?

**Comment by lonnieezell** [comment]
That was my first guess, too. But not it. It's throwing an error with GitHub API calls over limit. Trying to get access to CloudFlare, and push the new version of the site which does better caching and more responsible use of the API in general. Had stuff come up last night which sidetracked my time before I could get that far last night. Will hopefully have it working tonight.

**Comment by yigitsayan** [comment]
This seems fixed now and I can reach the site, closing the issue.
