### ISSUE TITLE
codeigniter4/codeigniter4 package not exists in packagist

### ISSUE THREAD

**Issue by samsonasik** [codeigniter4/CodeIgniter4#2753]
For example, I want to get the latest develop branch of the framework to my current `app-starter` app. The only way is by clone the project and copy into vendor directory or manually register this repository into composer.json.

How about add `codeigniter4/codeigniter4` to packagist ?

**Comment by lonnieezell** [comment]
`codeigniter4/codeigniter4` is not intended to be directly installed and make it available as a composer package would encourage that use and create many more support headaches. 

You can easily add it to your composer.json file as a repository. See this example file: https://github.com/lonnieezell/myth-auth/blob/develop/composer.json#L19

**Comment by MGatner** [comment]
Actually you probably want to use the `builds` script that toggles between `framework` and `codeigniter4`: **admin/starter/builds**. If you're using a post-release version of the AppStarter this should be in your project root. Simply run `./builds` and it will switch you to using the latest `develop` branch of `codeigniter4/codeigniter4` so when you run `composer update` you'll always be fresh.

**Comment by samsonasik** [comment]
ok, thank you ;)

**Comment by lonnieezell** [comment]
That sounds like a much better way of doing it, @MGatner Thanks for the reminder. :)

**Comment by samsonasik** [comment]
@MGatner I created PR #2756 to handle `./builds development` try to get all dev version of dependencies with `prefer-stable" => true`, which should only get dev version when required in composer.json
