### ISSUE TITLE
Bug: Multiple select validation problem

### ISSUE THREAD

**Issue by pbquet** [codeigniter4/CodeIgniter4#2757]
Hello,
I try to validate a form with a multiple select that was working in CI3

In my view:
```html
<select name="id_user[]"  multiple="">
<option value="1">user1</option>
<option value="2">user2</option>
<option value="3">user3</option>
</select>
```

In my controller :
```php
echo '<pre>' , var_dump($_POST) , '</pre>';
```
print
```
array(2) {
["id_user"]=>
array(2) {
[0]=> string(1) "1"
[1]=> string(1) "2"
}
["find"]=> string(10) "find"
 }
```
AND 

```php
$this->validation->setRules([
    'id_user[]'=>'numeric',
]);
$this->validation->withRequest($this->request)->run();
echo '<pre>' , var_dump($this->validation->getErrors()) , '</pre>';
```
print
```
array(1) {
  ["id_user[]"]=>  string(46) "The id_user[] field must contain only numbers."
}
```
it looks like CodeIgniter\Validation\run() is looking for "id_user[]" in the $_POST wich doesn't exist, instead of "id_user". And if I change the rule to 'id_user'=>'numeric', it does't care about the multiple value ...
is it a bug or do I have to change something in my code ?

**Context**
- CodeIgniter 4.02
 - Windows 10
 - PHP version 7.3.15

**Comment by musmanikram** [comment]
Looking into this

**Comment by musmanikram** [comment]
@pbquet You can use `id_user.*` as defined in the [documentation](https://codeigniter4.github.io/userguide/libraries/validation.html#validating-keys-that-are-arrays).

But somehow it's still failing. Not able to figure out why.

**Comment by pbquet** [comment]
@musmanikram I tried with `id_user.*` too, and I also have a error :
```php
TypeError
Argument 1 passed to CodeIgniter\Validation\FormatRules::numeric() must be of the type string or null, array given, called in C:\...\system\Validation\Validation.php on line 279
```
perhaps the “dot array syntax” works only when it's in the middle of the syntax like `contacts.*.name`, not at the end...in order to always return a string type .. ?

So should I stop using the [] syntax and use “dot array syntax” instead, or both should work ?

**Comment by musmanikram** [comment]
I would recommend use dot. Then it will be consistent with other validations

**Comment by pbquet** [comment]
ok, so the bug is in the “dot array syntax” now ? Should I create a new issue or keep this one ?

**Comment by musmanikram** [comment]
> ok, so the bug is in the “dot array syntax” now ? Should I create a new issue or keep this one ?

No keep this issue. So we will have a history
