### ISSUE TITLE
Bug: db query '?' bind is not working when use sql with ':=' operator.

### ISSUE THREAD

**Issue by fz19** [codeigniter4/CodeIgniter4#2762]
**Describe the bug**
Database Query '?' Bind is not working when use sql with ':=' operator.

**CodeIgniter 4 version**
v4.0.2

**Affected module(s)**
CodeIgniter\Database\Query (system/Database/Query.php)

**Expected behavior, and steps to reproduce if appropriate**

i use MySQL 5.7.28 and MySQLi driver.

> $db = db_connect();
> $sql = 'SELECT @factorA := ?, @factorB := ?';
> $params = [1,2];
> $db->query($sql, $params);

i expected run query.
`SELECT @factorA := 1, @factorB := 2`.

but it was run query actually
`SELECT @factorA := ?, @factorB := ?`
and occured SQL syntax error.

it seem to understand NamedBind because the sql has ':=' operator.
so i fix ci4 code temporarily.

system/Database/Query.php :: compileBinds() line 371
> $hasNamedBinds = strpos($sql, ':=') === false && strpos($sql, ':') !== false;

i hope solve this problem.
thanks.

**Context**
 - OS: CentOS Linux release 8.1.1911
 - Web server: nginx/1.17.6
 - PHP version: 7.4.3 (php-fpm)

**Comment by musmanikram** [comment]
Let me have look
