### ISSUE TITLE
Bug: rename release  By "v"

### ISSUE THREAD

**Issue by datamweb** [codeigniter4/CodeIgniter4#2763]
Hi @lonnieezell 
Please rename the final package(release) from 4.0.2 to v4.0.2 and 4.0.0 to v4.0.0.
This causes an error in the download link of the website.

**Comment by datamweb** [comment]
#4.0.0

**Comment by lonnieezell** [comment]
I was thinking about that last night as I fixed up the docs links for 3 and I actually need to point it at the `/framework` repo. I'm slammed with many things right now, but it is on my radar and will be fixed up very soon. Thanks.

**Comment by MGatner** [comment]
https://github.com/codeigniter4projects/website2/pull/55
