### ISSUE TITLE
Bug: Controller in Sub Directory is not working

### ISSUE THREAD

**Issue by Techimpace** [codeigniter4/CodeIgniter4#2764]
**Describe the bug**
Controller in Sub Directory is not working, its showing a 404 file not found error

**CodeIgniter 4 version**
4.0.2

**Context**
 - OS: Windows 10
 - Web server Apache
 - PHP version 7.2.24

**Comment by MGatner** [comment]
Please open support requests on the forum. You would also find there that many others have discussed this scenario, e.g.: https://forum.codeigniter.com/thread-73262.html

**Comment by Techimpace** [comment]
After following the procedure mentioned in forum, still we are facing issues, kindly have a look on log :

CRITICAL - 2020-04-04 09:46:55 --> Class 'App\Controllers\products\Controller' not found
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}

**Comment by Techimpace** [comment]
Thanks a lot, it works
