### ISSUE TITLE
Database model error when limiting delete()

### ISSUE THREAD

**Issue by pietrobe03** [codeigniter4/CodeIgniter4#2780]
When trying to delete data from the database with a limit using a model, the LIMIT block is appended twice by the query builder.

This example code
```
$gameCardStackModel->where("gameId", $game["id"])
->orderBy("id", "asc")
->limit(8)
->delete();
```
results in this Query
```
DELETE FROM  `GameCardStacks`\nWHERE `gameId` = '1' LIMIT 8 LIMIT 8
```
Stacktrace:
[stacktrace.json.txt](https://github.com/codeigniter4/CodeIgniter4/files/4404813/stacktrace.json.txt)

**Comment by samsonasik** [comment]
should can be closed in favor of https://github.com/codeigniter4/CodeIgniter4/pull/2781
