### ISSUE TITLE
Bug: Cookie Helper and Response class issue

### ISSUE THREAD

**Issue by anmar-dev** [codeigniter4/CodeIgniter4#2783]
*Description*
Im trying to create a cookie using response class as per the user guide.

`
```
$cookie = [
        'name'   => 'Something',
        'value'  => 'The Value',
        'expire' => '86500',
        'domain' => '.some-domain.com',
        'path'   => '/',
        'prefix' => 'myprefix_',
        'secure' => TRUE,
        'httponly' => FALSE
];

$this->response->setCookie($cookie);
```
`
of course data where different 

try to retrieve the cookie i cant 

` $this->request->getCookie('Something'); `

Also i tried using helper. i just cant to seem to make it work..
However when i use the native php function it works like a charm

`setcookie('mya', 'Some Value', time()+3600, '/');`

and on a different function i just do 
```

	public function testc()
	{
               // Does not work
		echo $this->request->getCookie('mya');
		// Works fine
                 if (isset($_COOKIE['mya'])) {
		 	echo $_COOKIE['mya'];
		 }
	}


```

**CodeIgniter 4 version**
CI4.0.2 Appstarter build using composer 

**Context**
 - OS: Win10
 - Web server WAMP64 
 - PHP version 7.3.5

**Comment by MGatner** [comment]
`setCookie()` is a method for `Response`, not `Request`! I think this isn't a bug so much as just an honest mistake :)

**Comment by MGatner** [comment]
Oops! Honest mistake is mine, I was looking at your `getCookie()` code. Looking into this...

**Comment by MGatner** [comment]
Hard to tell with your test data, but it looks like you might be setting a per-cookie prefix and then not requesting the same prefix with `getCookie()`. In your example, you would either need your App config `cookiePrefix` set to 'my_prefix_' or you would need to request the cookie like this: `$this->request->getCookie('Something', 'myprefix_');`

**Comment by anmar-dev** [comment]
Ok MGatner i give it a try...

**Comment by anmar-dev** [comment]
Ok i gave it a try.. it does not work,..

`
```
         public function index()
	     {
		$cookie = [
		        'name'   => 'ccc',
		        'value'  => 'The Value',
		        'expire' => '86500',
		        'domain' => '.some-domain.com',
		        'path'   => '/',
		        'prefix' => 'myprefix_',
		        'secure' => TRUE,
		        'httponly' => FALSE
		];

		$this->response->setCookie($cookie);
             }
```
`
and my 2nd method 

````
	public function testc()
	{
		var_dump($this->response->getCookie());

		echo $this->response->getCookie('ccc', 'myprefix_');
	}
```
`

i also tried without myprefix no luck.

**Comment by samsonasik** [comment]
It seems caused by the definition of `"secure" => TRUE,`, I tried with `"secure" => FALSE` in localhost and it working fine.

**Comment by samsonasik** [comment]
could you try define ?

```php
'secure' => $this->request->isSecure(),
```

**Comment by lonnieezell** [comment]
I have just tested using the helpers (which in turn use the current request/response) and this simple test works. I think @samsonasik is spot on here. 

```
public function index()
	{
		helper('cookie');

		$cookie = get_cookie('foo');
		d($cookie);

		set_cookie([
			'name' => 'foo',
			'value' => 'bar'. time(),
			'expire' => \time() + 3600,
			'httponly' => FALSE
		]);

		return view('welcome_message');
	}
```

Are you still having problems or did his suggestion clear it up?

**Comment by michalsn** [comment]
This seems like resolved.
