### ISSUE TITLE
Bug: session()->push() Strange behavior

### ISSUE THREAD

**Issue by anmar-dev** [codeigniter4/CodeIgniter4#2786]
Trying to build a cart using session and a came across a strange behavior (actually few).
1. push()
in construct()
```
if (is_null(session('cart'))) {
session()->set('cart', [ ]);
}
```
then on a different method on the same controller i have the following code

```
$item = ['test' => 20];
session()->push('cart', $item);
```
it seems that this method does not work if the session is set but does not contain a value example 

```
if (is_null(session('cart'))) {
session()->set('cart', ['id', 50]);
}
```
then it works fine.

Also 
 session()->destroy() does not destroy the session only partially (Some variables stay)

i have to use native PHP  $_SESSION = arrary(); to reset all session into empty array.

CI4.0.2 using composer appstarter --no-dev (installed today)
PHP 7.3.5
Apache 2.4.39
Win10

**Comment by anmar-dev** [comment]
Ok after changing my PHP version to 7.2.13 it seems the session()->push() works fine.
I guess there is some differences between versions regarding session.

**Comment by MGatner** [comment]
Is this still an issue? And can you clarify which versions of PHP you have tested, working and not?

**Comment by anmar-dev** [comment]
> Is this still an issue? And can you clarify which versions of PHP you have tested, working and not?

MGatner You can close this. My apologies it was a logic error from my part. i do that when i work more than 10 hours straight..
please close the issue.
Sorry again
