### ISSUE TITLE
Bug: Routing placeholder in "controller"part of route doesn't work

### ISSUE THREAD

**Issue by pbquet** [codeigniter4/CodeIgniter4#2787]
Hello,
This route work
```php
$routes->add('{locale}/admin/parameter/base/config/(:num)', 'Admin\Base::config/$1');
```
but in the following one, the first placeholder doesn't work because it is in the "controller" part of the route instead of "method" part :
```php
$routes->add('{locale}/admin/parameter/(:segment)/config/(:num)', 'Admin\$1::config/$2');
```
and that's because the '\\' before $1 escape the '$'

It's possible to resolve this issue in "system/Router/Router.php::checkRoutes" line 470 by changing :

```php
$val = preg_replace('#^' . $key . '$#', $val, $uri);
```
to
```php
$val = preg_replace('#^' . $key . '$#',  str_replace('\\', '\\\\', $val), $uri);
```
What do you think ?

**CodeIgniter 4 version**
4.02

**Affected module(s)**
Router/Router.php

**Context**
 - OS: Windows 10
 - Web server nginx 1.14
 - PHP 7.3.15

**Comment by lonnieezell** [comment]
We've had this brought up before but I have to turn down that feature. I view that as too big of a security risk because that allows anyone to try to load up common controller/method combos during an attempted attack. Not a good feature.
