### ISSUE TITLE
Bug: Problems with QueryBuilder when run multiple queries one by one

### ISSUE THREAD

**Issue by otrelin** [codeigniter4/CodeIgniter4#2800]
I have several tables:
- `hotel` - contains hotels
- `hotel_translation` - contains multilingual fields of hotels (many-to-one to `hotel`)
- `hotel_photo` - contains photos of hotels (many-to-one to `hotel`)
- `hotel_photo_translation` - contains multilingual descriptions of photos (many-to-one to `hotel_photo`)

First I generate query to get all hotels with their translations on one language (`id_lan = 1`):
```php
$hotels = $this->builder('hotel h')
    ->select('h.id_hotel, ht.name', false)
    ->from('hotel_translation ht')
    ->where('h.active', 'true', false)
    ->where('ht.id_hotel', 'h.id_hotel', false)
    ->where('ht.id_lan', 1, false)
    ->get()
    ->getResult();
```
The query is:
```sql
SELECT h.id_hotel, ht.name
FROM "hotel" "h", "hotel_translation" "ht"
WHERE h.active = true
AND ht.id_hotel = h.id_hotel
AND ht.id_lan = 1
```
That's OK!

After that I want to handle the result with `foreach` and get photos of each hotel with translation:
```php
$photos = $this->builder('hotel_photo hp')
    ->select('hp.photo_path, hpt.description', false)
    ->from('hotel_photo_translation hpt')
    ->where('hp.id_hotel', 1, false)
    ->where('hpt.id_hotel_photo', 'hp.id_hotel_photo', false)
    ->where('hpt.id_lan', 1, false)
    ->get()
    ->getResult();
```
But it generates wrong query:
```sql
SELECT hp.photo_path, hpt.description
FROM "hotel" "h", "hotel_translation" "ht", "hotel_photo_translation" "hpt"
WHERE hp.id_hotel = 1
AND hpt.id_hotel_photo = hp.id_hotel_photo
AND hpt.id_lan = 1
```
instead of what I expect:
```sql
SELECT hp.photo_path, hpt.description
FROM "hotel_photo" "hp", "hotel_photo_translation" "hpt"
WHERE hp.id_hotel = 1
AND hpt.id_hotel_photo = hp.id_hotel_photo
AND hpt.id_lan = 1
```
The problem is that when I initialize `builder()` in the second time with other table, this table is ignore (`hotel_photo` in my case) and in the second query are presents all tables from the first query (`hotel` and `hotel_translation` in my case).
It's a critical issue. Or maybe I'm doing something wrong?

---

I think it’s not very convenient to specify one table in initialization of `builder()` and the others in `from()` method. It would be clearer to call `builder()` without parameters and to specify all tables in `from()` (I mean situation with several tables in FROM clause). At least to have such an opportunity (now when trying to call `builder()` without parameter, an error is raised).

---

Also I found that `$QBFrom` property of class `\CodeIgniter\Database\BaseBuilder` is never resets. I guess its should be added to `resetSelect()` method of this class.
![зображення](https://user-images.githubusercontent.com/15085327/78471652-8e284100-773b-11ea-85b2-198875a31153.png)

**Comment by michalsn** [comment]
Partially it's a bug related to resetting `from` part of the query. 

But you also assume that the `builder` method in Model works differently than it actually does. You should use this method with a parameter only once because every other call will return a shared instance. 

So your second query should look like this:
```php
$photos = $this->builder()
    ->select('hp.photo_path, hpt.description', false)
    ->from('hotel_photo hp, hotel_photo_translation hpt', true)
    ...
```

**Comment by otrelin** [comment]
@michalsn thank you for your reply.
Your answer showed me to find a solution - set `true` as the second parameter to `from` method (always?). Its force overwrite QBFrom.

But still, it is somehow inconvenient - in the first query should specify the table in the `builder()`, but in the second one - not. Model may not be tied to one entity/table, but may be common to several tables - in this case there is no "main" table that needs to be specified when initializing the `builder()`.

**Comment by otrelin** [comment]
Besides if set `true` as the second parameter to `from()` in the first query then query failed - missing FROM-clause entry for table "h" (hotel).

So it’s really complicated - when you need to set the table in `builder()` and do not set `true` in`from()`and when you need to do the opposite.

**Comment by michalsn** [comment]
Regarding the second parameter in `from()` method - use it only when you need it. In your case, it will be only the second call. It's not really complicated, you just have to take some time to realize what is happening under the hood.

I think that `builder()` method was created to make life easier for developers - in many cases. You can call is a shortcut? When things become more complex as in your case, I would recommend using a new instance of `BaseBuilder` every time. In your model you can call it like this:
```php
$builder = $this->db->table('my_table1');
...
$builder = $this->db->table('my_table2');
```
That should make it easief for you.

**Comment by otrelin** [comment]
Thank you very much. This is really what I wanted.
