### ISSUE TITLE
Bug: Validation placeholder not being replaced

### ISSUE THREAD

**Issue by erikkloeze** [codeigniter4/CodeIgniter4#2817]
**Describe the bug**
When using validation placeholders in a model and validating data, the placeholder is not being replaced with the actual data. The validation therefore returns false.

**CodeIgniter 4 version**
4.0.2

**Expected behavior, and steps to reproduce if appropriate**
Using the [myth-auth](https://github.com/lonnieezell/myth-auth) package and the GroupModel. Validation rules are defined in the model as:
```
protected $validationRules = [
	'name' => 'required|max_length[255]|is_unique[auth_groups.name,name,{name}]',
	'description' => 'max_length[255]',
];
```

When trying to update a group in the controller using an already existing `name` in the database:
```
$groupModel = new GroupModel();

if (! $this->validate($rules = $groupModel->getValidationRules())) {
	return redirect()->back()->withInput()->with('errors', $groupModel->errors());
}
```
The validation returns false. Looking at the DB (MySQL) query ran it can be seen why:
```SELECT 1 FROM `auth_groups` WHERE `name` = 'admin' AND `name` != '{name}' LIMIT 1```

A manual replacement of `{name}` with the actual value resolves the issue.

**Comment by samsonasik** [comment]
i guess you are using postgresql, seems similar issue with my comment at https://github.com/codeigniter4/CodeIgniter4/issues/2812#issuecomment-611283231

**Comment by erikkloeze** [comment]
After digging through the code I might have found the solution. This might also solve #2812. 

In the `Model` class the `validate()` function includes a `fillPlaceholders()` before it sets the rules and runs the validation:
https://github.com/codeigniter4/CodeIgniter4/blob/895f1e67eb895eacff204e5baba73e5e1b2629af/system/Model.php#L1434-L1439

In the `Controller` class this call to `fillPlaceholders()` is not present:
https://github.com/codeigniter4/CodeIgniter4/blob/895f1e67eb895eacff204e5baba73e5e1b2629af/system/Controller.php#L216-L219

When the `fillPlaceholders()` is added to the `Controller` class and called before the validator runs, the issue is solved:

```
// Replace any placeholders (i.e. {id}) in the rules with
// the value found in $data, if exists.
$rules = $this->fillPlaceholders($rules, $this->request->getVar());

$success = $this->validator
	->withRequest($this->request)
	->setRules($rules, $messages)
	->run();
```
