### ISSUE TITLE
Controller Call to a member function getPost() on null 

### ISSUE THREAD

**Issue by alive1944** [codeigniter4/CodeIgniter4#2823]
Version: 4.0.2

```
<?php

namespace App\Controllers;

use CodeIgniter\API\ResponseTrait;
use CodeIgniter\HTTP\Request;
use CodeIgniter\HTTP\RequestInterface;
use Services\WxConfig;

class Message extends BaseController
{
//    use ResponseTrait;

    public function __construct()
    {
        $user_email = $this->request->getPost('user_email');
        $user_phone = $this->request->getPost('user_phone');
    }
}
```

I just use this and run my code, then  got the error report:  

`Call to a member function getPost() on null`

according to the guide, I extend the BaseController ( I saw that BaseController extend Controller)  
I try to add `parent::__construct();`, but didn't work, I saw the code in BaseController, So did I must run `parent::initController(....);` ? If it is like this, it means I must code these in every controller, and fill in  `\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger` ?

**Comment by alive1944** [comment]
OK, I saw the resource code, I know why it's null now

**Comment by Amar-arruf** [comment]
> OK, I saw the resource code, I know why it's null now
@afraidjpg 
 How ? , I have same Error

**Comment by kenjis** [comment]
See
https://github.com/codeigniter4/CodeIgniter4/blob/22924e85fda560f270c37d47b1bc0a7fee11ad75/app/Controllers/BaseController.php#L22
https://github.com/codeigniter4/CodeIgniter4/blob/22924e85fda560f270c37d47b1bc0a7fee11ad75/system/Controller.php#L25
