### ISSUE TITLE
Bug: $format in ResourceController is ignored

### ISSUE THREAD

**Issue by rmilecki** [codeigniter4/CodeIgniter4#2828]
**Describe the bug**
`CodeIgniter\RESTful\ResourceController` allows (according to the documentation and source code) specifying output format by setting `protected $format` to `xml` or `json`. There is even `ResourceController::setFormat` helper.

It doesn't work however as `$format` seems to be ignored.

In practice calling `ResponseTrait::respond` results in calling `ResponseTrait::format` which negotiates output format:
```
$format = $this->request->negotiate('media', $config->supportedResponseFormats, false);
```
E.g. I get XML when opening page in web browser and JSON when using CLI `curl`.

**CodeIgniter 4 version**
4.0.2

**Affected module(s)**
`ResourceController` and `ResponseTrait::format`.

**Expected behavior, and steps to reproduce if appropriate**
1. Setting `protected $format = 'xml';` should always generate XML response
2. Setting `protected $format = 'json';` should always generate JSON response

**Comment by samsonasik** [comment]
could you try latest dev-develop?

```
php builds development
composer update
```

**Comment by michalsn** [comment]
Already fixed.
