### ISSUE TITLE
Bug: RouteCollection::resource() doesn't work with grouped rules

### ISSUE THREAD

**Issue by rmilecki** [codeigniter4/CodeIgniter4#2829]
**Describe the bug**
When using routes group **and** `::resource()` then methods receive method name as argument instead of segment. Example:
```
$routes->group('api', function($routes) {
	$routes->resource('news', ['controller' => 'Api\News' ]);
});
```
opening `/api/news/show/123` results in CI4 calling `->show('show');` (`'show'` should be `'123'`).

**CodeIgniter 4 version**
4.0.2

**Affected module(s)**
`RouteCollection`

**Expected behavior, and steps to reproduce if appropriate**
Things work as expected when using:
```
$routes->group('api', function($routes) {
	$routes->get('news/(:segment)',      'Api\News::show/$1');
});
```
and according to the documentation initial code using `RouteCollection::resource()` should be equivalent for that.

**Context**
 - OS: Linux
 - PHP version 7.4.2

**Comment by Instrye** [comment]
uri is `/api/news/123`, not `/api/news/show/123`
```
$routes->resource('photos');

// Equivalent to the following:
$routes->get('photos/new',             'Photos::new');
$routes->post('photos',                'Photos::create');
$routes->get('photos',                 'Photos::index');
$routes->get('photos/(:segment)',      'Photos::show/$1');
$routes->get('photos/(:segment)/edit', 'Photos::edit/$1');
$routes->put('photos/(:segment)',      'Photos::update/$1');
$routes->patch('photos/(:segment)',    'Photos::update/$1');
$routes->delete('photos/(:segment)',   'Photos::delete/$1');
```
