### ISSUE TITLE
Bug: Model save method not working if PRIMARY KEY is VARCHAR

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#2835]
Hello again codeigniter TEAM

i am trying to save some data into mysql database table

i have array

```
[0] => Array
(
    [id] => 51610677-FD05-49FC-B6B8-EC6A2B932968
    [date] => 1586855452
)
```
Here is my code
```
$Model->save([
	'id' => '51610677-FD05-49FC-B6B8-EC6A2B932968',
	'date'  => date("Y-m-d H:i:s", 1586855452)
]);
```
The result telling me it was a success but when im going to table i see empty table.

**Comment by musmanikram** [comment]
@crustamet Can you please table schema here?

**Comment by samsonasik** [comment]
Well, actually, for uuid, you should use binary instead of varchar. But if you can give reproducible use case, probably someone or you can propose a fix.

**Comment by michalsn** [comment]
Not a bug. If you use `save()` method and at the same time you have an `id` in the array, the model class will try to make an `update`, not `insert`.

Just use `insert()` method instead. 

Oh... btw, I'm not sure if the default model will play nice with `UUID` field as a primary key - probably not. You will have to make some amends to the way it works, by extending it, because it uses `insertID` in some places.

**Comment by crustamet** [comment]
this is shit, just use insert insted of save lol, this beats the purpose of using save, i have to work extra because codeigniter still doesn't know if i have a record in databse ? or not ? whats the point of even using save() then ?

**Comment by crustamet** [comment]
> @crustamet Can you please table schema here?

there are two keys varchar primary key that is not autoincrement. and a date datetime.

**Comment by michalsn** [comment]
@crustamet This is an open-source project. If you don't like how some things work and see a place for improvements, you can always send a PR.

**Comment by crustamet** [comment]
No man, i am sorry, it is all good,

I can`t send a PR because my method will not be good :)

They think everything trough already.
The save function only works with a standard database table.

The only problem that i am complaining about it is the return IS TRUE while it didn`t do anything.
Ofcourse it returns TRUE because the save method updates nothing because it thinks it already exists.

I went down the rabbit hole :)

The thing here is when the query gets executed, it execute with success and the save method return true if no errors occurred, but it should return how many rows changed in the database.

Anyway it is good like this.

**Comment by crustamet** [comment]
Until the end of the day this is a legit issue or not ?

**Comment by michalsn** [comment]
Not. Everything is working as it supposed to work and as described in the docs.

Also the default Model class supports only auto-increment fields for a primary key.

**Comment by luispastendev** [comment]
@crustamet What are you using to generate the uuids? I find the option that the model methods can work with something other than auto_increments quite interesting.

**Comment by crustamet** [comment]
i get the uids from an API
