### ISSUE TITLE
Bug: Method Spoofing Validation

### ISSUE THREAD

**Issue by alexlancer** [codeigniter4/CodeIgniter4#2855]
**Describe the bug**
While attempting to send a PUT request to my RESTapi endpoint to update a record I found that if I also want to pass a file in my request I could not get "$this->validate($rules)" to work. 
So after changing my request to $_POST and using method spoofing to change the request method to PUT still did not fix the issue. 

**CodeIgniter 4 version**
v4.0.2

**Affected module(s)**
method withRequest

**Expected behavior, and steps to reproduce if appropriate**
the issue comes at line 322 of Validation.php file where 
`if (in_array($request->getMethod(), ['put', 'patch', 'delete']))
{
	$this->data = $request->getRawInput();
}`
in case anyone attempts to pass $_FILES in the request $this->data will be empty.
Maybe a solution would be to change the if statement 
`if (in_array($request->getMethod(), ['put', 'patch', 'delete']) && $_SERVER['REQUEST_METHOD'] != 'POST')`

So that if the initial request is POST then no reason to grab raw input.
Issue #880 seemed similar but not exactly.

**Comment by Instrye** [comment]
Upload file muse use `multipart/form-data`, php just parse this in `POST` before CI,
If we want to parse the data again, we must implement the parser.
In my opinion. Files should not be uploaded in RESTful.

**Comment by alexlancer** [comment]
After doing some random tests, it appears that when using a $this->resource('controller') routing rule
`$routes->resource('photos');

// Equivalent to the following:
....
$routes->put('photos/(:segment)',      'Photos::update/$1');
....
`
@lonnieezell,  even though the rule is for PUT requests (based on docs), you still can make a POST request and the `update` method works just fine and uploads the file, so maybe the documentation should be adjusted.

**Comment by lonnieezell** [comment]
The biggest problem with this is that it assumes that a PUT request should operated just like a POST request. And they shouldn't. According to [the spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6) a PUT request is to allow putting the body of the request at a specific location. So, it cannot accept multiple files. If an image would be sent via a PUT request, it should be only the data for the image.
