### ISSUE TITLE
Bug: `composer require codeigniter4/translations` without stable version

### ISSUE THREAD

**Issue by jlamim** [codeigniter4/CodeIgniter4#2862]
**Describe the bug**
Doing a check in the documentation I identified a problem in the part that talks about "Localization".

It is informed that a good practice to install the language dictionary is to use the command `composer require codeigniter4/translations`, however when executing the command the composer returns a message saying that there is no stable version for the package.

`[InvalidArgumentException] Could not find a version of package codeigniter4/translations matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.`

And in fact there isn't, I checked on https://packagist.org/packages/codeigniter4/translations.

**CodeIgniter 4 version**
4.0.2

**Affected module(s)**
Localization

**Context**
 - OS: Win 10
 - Web server: Apache 2.4.41
 - PHP version: 7.4.4

**Comment by Instrye** [comment]
@lonnieezell 
`codeigniter4/translations`  latest version is `v4.0.0-rc.3`.
I think, we can  Release a stable version

**Comment by lonnieezell** [comment]
Ha! You're right. Guess I forgot about that one. Will do that now.

**Comment by lonnieezell** [comment]
Done.
