### ISSUE TITLE
Installation Problem: Composer installation halts while installing kint-php/kint

### ISSUE THREAD

**Issue by sabbir-rupom** [codeigniter4/CodeIgniter4#2863]
Cannot proceed composer installation. Trying a while but always getting stuck at kint-php/kint download section.

Any way to bypass it ? Is the kint repository down? 

Should I try different installation way ?

**Comment by jlamim** [comment]
I did some installation tests using the composer and there was no problem, it may be some kind of instability.

**Comment by Instrye** [comment]
can you show error?
Any possible information.

**Comment by sabbir-rupom** [comment]
Yes
[https://photos.app.goo.gl/TEDXXyhhFBwLdLzNA](error)
Couple of hour ago I tried to install again, now this error showed

I think github is having heavy traffic issues, that's why project pages are getting timeout problem

**Comment by sabbir-rupom** [comment]
Finally, installed successfully. 

I think the issue was lied with github server heavy traffic. Now all github projects are loading just fine. 
And installed CI4 successfully. :D
