### ISSUE TITLE
Bug: Can't override already defined language in pager

### ISSUE THREAD

**Issue by pixobit** [codeigniter4/CodeIgniter4#2875]
**Describe the bug**
Not completely sure if this was intended, or it's an issue, but I personally find it inconvenient.
I noticed that it's impossible to override the pager translations, unless you change the translation key.

**CodeIgniter 4 version**
4.0.2

**Affected module(s)**
Pager

**Expected behavior, and steps to reproduce if appropriate**
Add pager.php to your languages folder, and insert any of the pager translations, for example:
return [
    'first' => '«',
    'previous' => '‹',
    'next' => '›',
    'last' => '»',
];
Create a pager object with or without a custom template, and use makeLinks to generate the links. You will notice that the expected translations from your file won't be applied, instead the default will be used.

**Comment by jlamim** [comment]
@pixobit  There was really a bug in the paging structure. I already sent a PR with the correction, soon to be released and you can update the code of your application.
