### ISSUE TITLE
custom rules without parameters not get access to $data variable

### ISSUE THREAD

**Issue by nicojmb** [codeigniter4/CodeIgniter4#2876]
**Describe the bug**
First, i've created a custom validation rule:

![image](https://user-images.githubusercontent.com/5610392/80279747-cc43cf80-86ff-11ea-95ce-2d9605c11e29.png)

Then, i register in Validation.php config file:

![image](https://user-images.githubusercontent.com/5610392/80279787-fe553180-86ff-11ea-8415-ad37cb6b4a51.png)

Now, i use in controller:

![image](https://user-images.githubusercontent.com/5610392/80279877-7b80a680-8700-11ea-8320-86a2b804841a.png)

In this momento, the system showme a 500 error because is mandatory to use $fields variable in custom rules.

I would like create a custom rule without parameter but getting acces to $data variable with other fields valules.

> "title": "TypeError",
"type": "TypeError",
"code": 500,
"message": "Argument 2 passed to App\\Validations\\CustomRules::custom_rule() must be of the type array, null given, called in /home/xxx/www/vendor/codeigniter4/framework/system/Validation/Validation.php on line 279",
"file": "/home/xxx/www/app/Validations/CustomRules.php"

**CodeIgniter 4 version**
4.0.2

**Affected module(s)**
class:  CodeIgniter\Validation\Validation::class 
method: processRules
https://github.com/codeigniter4/CodeIgniter4/blob/e3c66293e04bb72c90f3140e3f4204052abade07/system/Validation/Validation.php#L290

**Expected behavior, and steps to reproduce if appropriate**
$data must be accesible if i not need a parameter

**Context**
 - OS: Centos: 7
 - Web server:  ngix
 - PHP version 7.4

**Comment by jlamim** [comment]
@nicojmb Could you give a clearer and less generic example?

**Comment by nicojmb** [comment]
@jlamim i've rewrited the isse with images example and error.

**Comment by jreklund** [comment]
I'm afraid you have created your function incorrectly, as per my understanding. It should be made like this.

```php
public function custom_rule(string $str = null, string $blank = null, array $data): bool
{
     return true;
}
```

**Comment by nicojmb** [comment]
> I'm afraid you have created your function incorrectly, as per my understanding. It should be made like this.
> 
> ```
> public function custom_rule(string $str = null, string $blank = null, array $data): bool
> {
>      return true;
> }
> ```
> 
> You will need to pass `custom_rule[]`, an empty array or take a look at the FileRules and do a similar solution and grabbing the RequestInterface. And from there grabbing the values.

Yes, if i add [] and modify the rule adding this parameter work, but i underdat that code can be fixed to no add "[]" to custom rule if not needed.

**Comment by jreklund** [comment]
Not without making a breaking change, as error will not be the second parameter anymore.
https://codeigniter.com/user_guide/libraries/validation.html#creating-custom-rules

We can add $data to the end, that won't break anything, but $error will no longer be the last item, changing the coding style.
```php
public function custom_rule(string $str = null, string &$error = null, array $data): bool
{
     return true;
}
```

So I think it would just be easier to grab $this->request->getPost() in your custom class instead.

**Comment by nicojmb** [comment]
getPost is not a solution because i can use same rule for GET, POST or RawInputData, the best solution is can access to $data varibale.

I think conditioning this counting paramenters y know if rule name contains array [] can be fixed:

Example:

```
<?php
if(params == 1) --> ($str)
if(params == 2 && rule name contains []) --> ($str, $fields)
if(params == 2 && rule name not contains []) --> ($str, $error)
if(params == 3 && rule name contains []) --> ($str, $fields, $error)
if(params == 3 && rule name not contains []) --> ($str, $data, $error)
if(params == 4) --> ($str, $fields, $data, $error)

```

**Comment by jreklund** [comment]
What's "params" in this instance? There are only $param. And it can either be false or a string.
So I can't see how we can detect such a thing.

**Comment by nicojmb** [comment]
hi @jreklund i tested y my enviroments with this code works fine:

```
<?php
$reflector = new \ReflectionClass($set);
$params = $reflector->getMethod($rule)->getNumberOfParameters();
if ($param === false){
   switch($params)
      {
         case 2 : $passed = $set->$rule($value, $data); break 2;
         case 3 : $passed = $set->$rule($value, $data, $error); break 2;
      }
}
```
This code is added between line 288 and 289, on file CodeIgniter\Validation\Validation.php.

I don't think that my code is optimal but works.

My idea is change documentation adding the posibility of create custom rules without parameters:

```
<?php
// current possibilities
public function even(string $str): bool
public function even(string $str, string &$error = null): bool
public function even(string $str, string $fields, array $data): bool
public function even(string $str, string $fields, array $data, string &$error = null): bool

// new possibilities with this code
public function even(string $str, string $data = array()): bool
public function even(string $str, string $data = array(), string &$error = null): bool
```

**Comment by MGatner** [comment]
This seems like an awful lot of work just to avoid a default parameter. Am I misunderstanding something? We cannot change the current definition because it could be in use by current custom filters.

**Comment by kenjis** [comment]
`[]` is needed when you want to get access to `$data`.
We would decide it is the specification and I don't see any problem with it.

Changing the method signature dynamically seems to be very bad idea.
Could it be statically analyzed?

**Comment by kenjis** [comment]
Please submit feature requests to our [forum](https://forum.codeigniter.com/forum-29.html).
We use github issues to track bugs and planned work.
