### ISSUE TITLE
Bug: Argument 1 passed to CodeIgniter\Database\BaseResult::getFirstRow() must be of the type string, null given, called in /system/Model.php on line 383

### ISSUE THREAD

**Issue by 25hweb** [codeigniter4/CodeIgniter4#2877]
Hi,
In my model I am trying to get an item by its ID. My code is given bellow:
$id = 5;
$currentUser = new User($id);

I obtain:
Argument 1 passed to CodeIgniter\Database\BaseResult::getFirstRow() must be of the type string, null given, called in /system/Model.php on line 383

CodeIgniter 4.0.2
 - OS: linux
 - Apache 2.4.41  
- PHP Version 7.3.9

**Comment by samsonasik** [comment]
please provide complete reproducible example.

**Comment by FelipeAzambuja** [comment]
you send a null on variable $id

**Comment by lonnieezell** [comment]
Is User a Model or an Entity?

Either way you have the syntax wrong. If it's a Model, the first parameter would be a database connection. If an Entity, it would require an array of fields, not just an $id var. 

Not a bug. Closing. If you need more assistance please ask on the forums.

**Comment by abhishekjnvk** [comment]
remove  __construct() function from Modal class.

**Comment by rpuig** [comment]
why do we need to remove the construct from models?
