### ISSUE TITLE
Multiple table query Model first 

### ISSUE THREAD

**Issue by zl59503020** [codeigniter4/CodeIgniter4#2885]
**Describe the bug**
If I use multiple tables to join queries and use aliases, when I use first to get a record but no orderBy is set, an incorrect SQL statement will be generated

**CodeIgniter 4 version**
4.0.2

**Affected module(s)**
[system/Model.php](https://github.com/codeigniter4/CodeIgniter4/blob/098b7fe1fda84f78ba6800d39764714303bbbd3a/system/Model.php#L478)

**Expected behavior, and steps to reproduce if appropriate**
Models/ResourceModel.php
`
class ResourceModel extends Model
{
protected $table = 'ad_resource';
public function test($action)
{
return $this->select([
            'R.id',
            'R.place_id',
            'R.action',
            'R.title',
            'R.src',
            'P.code',
            'P.name',
        ])->from($this->table.' AS R', true)
          ->join('ad_place AS P', 'R.place_id = P.id', 'left')
          ->where('R.action', $action)
          ->first();
}
`
use
`
(new ResourceModel())->test('test');
`
An uncaught Exception was encountered

Type:        mysqli_sql_exception
Message:     Unknown column 'ad_resource.id' in 'order clause'
Filename:    E:\webroot\system\Database\MySQLi\Connection.php
Line Number: 331

Because I set an alias when using From, the correct orderBy cannot be generated

**Context**
 - OS: windows 10
 - Web server nginx
 - PHP version 7.3

**Comment by Instrye** [comment]
This is expected, Because you set `$table = 'ad_resource'`.
The method use $table value to do `order buy`.
You can declare yourself `order by`.
seem:
```
return $this->select(['R.id', 'R.name', 'R.description', 'P.key', 'P.value'])
            ->from($this->table. ' AS R', true)
            ->join('db_misc AS P', 'R.id = P.id', 'left')
            ->where('R.name', $action)
            ->orderBy('R.id', 'DESC')
            ->first();
```

**Comment by michalsn** [comment]
Not a bug.
