### ISSUE TITLE
About javascript: void (0);

### ISSUE THREAD

**Issue by muh-ramadhan** [codeigniter4/CodeIgniter4#2887]
how to handle it?
in codeigniter version 3 for example I use
`<a href="#" data-menu="menu-main"></a>`
it functions as it should not refresh the page.
But in codeigniter version 4 lines of code `href = "#"` refreshes the page. so I changed it to
`<a href="javascript"void(0)" data-menu="menu-main"></a>` to function without having to refresh the page.

But the problem is javascript: void (0); violates HTTPS Content Security Policy on CSP-enabled (Content Security Policy).

**Comment by muh-ramadhan** [comment]
CodeIgniter 4.0.2
Google Chrome Version 81.0.4044.122
Run Local Deveploment and Shared Hosting

**Comment by jlamim** [comment]
Wrong:  <a href="javascript"void(0)" data-menu="menu-main"></a>

Change to:  <a href="javascript:void(0);" data-menu="menu-main"></a>

**Comment by muh-ramadhan** [comment]
> Wrong: `<a href="javascript"void(0)" data-menu="menu-main"></a>`
> 
> Change to: `<a href="javascript:void(0);" data-menu="menu-main"></a>`

Sorry typo,
If Use `href="#"`
This Error Not Toggle `data-menu="example"`
so must use `href=javascript:void(0);`
so that `data-menu="example"` works.
The Case Is Like This, In
`app/Config/Routes.php` Line 19 `$routes->setDefaultController('Welcome');`
If I Use a View That in the Routes Setup I Determined This Error Occurs, But It Does Not Apply to Controllers That Are Not Set on Line 19.
To reduce the use of `javascript:void(0);` In the Default Routes Specified. Because of Content Security Policy Reasons.
