### ISSUE TITLE
Bug:  Debugging toolbar not showing

### ISSUE THREAD

**Issue by dumdam** [codeigniter4/CodeIgniter4#2893]
**Describe the bug**
Debugging toolbar isn't showing after a fresh installation . I followed [this tutorial](https://codeigniter.com/user_guide/tutorial/index.html) . I'm using Apache with XAMPP.
But after I set
`
$baseURL = "http://localhost/ci_path/public/
`
It worked.

**CodeIgniter 4 version**
4.0.2

**Expected behavior, and steps to reproduce if appropriate**
If this is a problem with that tutorial, documentation should be updated.
I think this is a bug, Because as I know, the base url can not contained the `public` folder.
`
http://localhost/ci_path/
`

**Context**
 - OS: Windows 10
 - Web server: Apache
 - PHP version: 7.4.4

I'm new to CI 4.

**Comment by vitnibel** [comment]
Everything works as expected if you follow the tutorial completely.
After all, in the tutorial, a built-in version is used as the server, which is launched by the command:
php spark serve
It will start the server at the http://localhost:8080
It is this address that is specified in the Config/App.php after a fresh installation.
When using Apache as a server, you must correctly specify the root document in apache/conf/httpd.conf or virtual host apache/conf/extra/httpd-vhosts.conf
for example namebase virtual host:
<VirtualHost *:80>
    DocumentRoot "C:/xampp/htdocs/ci4/ci-news/public"
    ServerName ci4.com
</VirtualHost>
then in Config/App.php
public $baseURL = 'http://ci4.com/';

**Comment by solaxes** [comment]
Debug toolbar is not showing for the following usecase..

Platform Ubuntu 18.04

Virtual host setup like shopify-ci.local 

application is running on the virtual host, but debug toolbar is not showing. But when I am running the application using spark, then toolbar is displaying.

my settings are

.env

CI_ENVIRONMENT = development
app.baseURL = "http://shopify-ci.local"

public $baseURL = "http://shopify-ci.local/";

**Comment by FoleyDom** [comment]
Any update on how to fix this?

**Comment by FoleyDom** [comment]
Request URL:
http://dev.blog-space.local/index.php?debugbar_time=1688277294.908586
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
127.0.0.1:80
Referrer Policy:
strict-origin-when-cross-origin

>

**Comment by FoleyDom** [comment]
I just got it to work on my local Apache server. Permissions issue, I used this command to fix the permissions: 
chmod -R 755 writable/ 
chown -R _www:_www writable/
note: I ran this as sudo.
