### ISSUE TITLE
Modular MVP on CI4

### ISSUE THREAD

**Issue by lebidvadim** [codeigniter4/CodeIgniter4#2900]
Hello, I now want to develop my MVP of such a plan in the APP folder, you will have the base of all MVP and the horse will have the “modules” folder and it will expand my MVP. So far, a very big problem is that I can’t create the “modules” folder in the root and put all my modules in it that expand my MVP. I found modularity in the documentation but somehow it is not correctly implemented. Because if I have a module in the “modules” folder for example “News”, then in this “News” folder there should be such folders (Services, Configuration, Filters, Libraries, Filters, Languages, Controller). So that I can install my development with ease in the "modules" folder, fill in my written modules so that I don't get flattery in the "APP" folder and configure all the config files. It is very uncomfortable. At least you have made it possible to expand the config files from the "APP" folder in my "modules / news" folder so that I can inherit from the "APP / config" config.

**Comment by lonnieezell** [comment]
Please only post bugs here. Support should be asked on the forums. 

Short answer is that, yes, it does work. But you have to make sure to specify each namespace individually. Just adding a namespace for "Modules" is not enough. You must also specify "Modules/News" on its own .
