### ISSUE TITLE
Cache redis or memcached

### ISSUE THREAD

**Issue by samirios182805** [codeigniter4/CodeIgniter4#2909]
Hello first, I would like to thank everyone for the great work they are doing. Congratulations

I have a query when using cache memcached or redis does not work

it does not make any cache and that is configured correctly

I would like help

**Comment by jlamim** [comment]
@samirios182805 Is there an error on the screen or in the log file? If so, share the error message as it helps us better understand the scenario.

Also inform the version of CI, PHP and the Operating System used.

**Comment by samirios182805** [comment]
use windows 10, laragon redis php 7.2 Codeigniter 4.0.2
does not show any errors only does not cache in redis only in file


App/Config/Cache.php

	public $handler = 'file'; working
	public $handler = 'redis'; not working no create cache

**Comment by jlamim** [comment]
@samirios182805 Can you do a test using `predis' when using `redis` and give feedback?

**Comment by samirios182805** [comment]
sorry it works for me apparently it had redis installed but the windows extension does not check files for files and it did not show me any errors, maybe you can put a warning if your version of php does not have the redis extension

**Comment by michalsn** [comment]
The whole idea behind the backup handlers is to avoid showing errors directly.
You can always check your logs. Any error will be mentioned there.
