### ISSUE TITLE
Why this route does not work ?

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#2919]
Hello i am trying to make an action type in a controller
i have this route that is not working for some reason

```
$routes->group('cms/banners', ['namespace' => 'App\Controllers\Modules\cms'], function($routes)
{
	$routes->get('/', 'Banners::index');
	$routes->get('?action=(.+)', 'Banners::$1');
});
```
Am i doing something wrong here ?

When i try to access https://example/cms/banners?action=add
does not link to the route

**Comment by vitnibel** [comment]
It is not possible to use "query string" parameters in routing at all.
[manual](https://codeigniter.com/user_guide/incoming/routing.html)
> Typically there is a one-to-one relationship between a URL string and its corresponding controller class/method.

If it is fundamentally important for your project, I would advise something like this
`$routes->get('action/(:any)', 'Banners::action/$1');`

and then in the function action get the data from query string

`$params = $this->request->getGet()`

**Comment by crustamet** [comment]
Thanks i already used it like how you showed in your post.
