### ISSUE TITLE
Bug: Not bug, but Fix Documentation, please

### ISSUE THREAD

**Issue by njsx** [codeigniter4/CodeIgniter4#2920]
In the validation section:

less_than  ->  Fails if field is greater than or equal to the parameter value or not numeric. 
less_than_equal_to  ->  Fails if field is greater than the parameter value or not numeric.

must be reverse!

**Comment by paulbalandan** [comment]
Not a doc error. I think you are confused.

Let us say you have a param value of 5 and test values of 5 and 6:

```php
// not the official syntax though
// TESTVAL OPERATOR[PARAMVAL]
5 less_than[5] // false
6 less_than[5] // false
5 less_than_equal_to[5] // true
6 less_than_equal_to[5] // false
```

**Comment by michalsn** [comment]
As @paulbalandan pointed out - documentation is fine.
