### ISSUE TITLE
`错误：Model

### ISSUE THREAD

**Issue by nabadao** [codeigniter4/CodeIgniter4#2923]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
Why does the model findall() return null, onlydeleted() - > findall() return all data instead of soft deleted data

**CodeIgniter 4 version**
Which version 4.03.

**Affected module(s)**
Which package or class is the bug in, if known.

**Expected behavior, and steps to reproduce if appropriate**
![image](https://user-images.githubusercontent.com/44055234/80933338-e5cad280-8df5-11ea-80ad-803786a9fe37.png)
![image](https://user-images.githubusercontent.com/44055234/80933363-fa0ecf80-8df5-11ea-9db1-246b6bc870ea.png)
![image](https://user-images.githubusercontent.com/44055234/80933504-9afd8a80-8df6-11ea-905a-0da4e4e1bfaa.png)
![image](https://user-images.githubusercontent.com/44055234/80933631-20813a80-8df7-11ea-8b1c-7668491d807d.png)
![image](https://user-images.githubusercontent.com/44055234/80933640-2d059300-8df7-11ea-8304-d5a10de61de7.png)
{"method":"CLI","route":"conf\/getConfDeleted","handler":"\\App\\Controllers\\Conf::getConfDeleted"},{"method":"CLI","route":"conf\/delConf","handler":"\\App\\Controllers\\Conf::delConf"}
**Context**
 - OS: Linux VM_21_239_centos 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 
 - Web server 2.4.0
 - PHP Version 7.3.16

**Comment by jlamim** [comment]
Change the value of  `$useTimestamps` to` true` and check if you are going to save the information for the fields that have a problem.

> `$useTimestamps`
> This boolean value determines whether the current date is automatically added to all inserts and updates. If true, will set the current time in the format specified by $dateFormat. This requires that the table have columns named ‘created_at’ and ‘updated_at’ in the appropriate data type.

**Comment by nabadao** [comment]
> 更改 的值，并检查是否要为有问题的字段保存信息。`$useTimestamps`` true`
> 
> > `$useTimestamps`此布尔值确定当前日期是否自动添加到所有插入和更新中。如果为 true，则以 $dateFormat 指定的格式设置当前时间。这要求表在适当的数据类型中具有名为"created_at"和"updated_at"的列。

Thank you very much for your answer. There are created at and updated at and deleted at in the database table, and $usetimestamps is also set to true, but you still don't get the desired result. For now, you can only use this method instead: $this - > confmodel - > where ('deleted at! = ', 0) - > get() - > getresultarray(); and $this - > confmodel - > where ('deleted at', 0)->get()->getResultArray();

![image](https://user-images.githubusercontent.com/44055234/80973640-3c65fa00-8e52-11ea-869f-33db3621de7e.png)


![image](https://user-images.githubusercontent.com/44055234/80973898-8c44c100-8e52-11ea-9db3-5608a86a2b02.png)

**Comment by Instrye** [comment]
CI4是通过 deleted_at 是不是 NULL 来判断的, `0`会被认为是已经删除了，
另外注意到你的日期都是2020但是你在数据库中配置了(int) 11，你可以设置  `$dateFormat`  为 `int`

**Comment by Instrye** [comment]
你的数据库相应字 默认应该设置为NULL
in database, `created_at`, `updated_at`, `deleted_at` muse set `Allow NULL` and `DEFAUILT VALUE IS NULL`

**Comment by nabadao** [comment]
> CI4是通过 deleted_at 是不是 NULL 来判断的, 会被认为是已经删除了，
> 你应该通过设置 设置为 true 来自动更新 , , ，而不是自己赋值
> 另外注意到你的日期都是2020但是你在数据库中配置了(int) 11，你可以设置 为 `0``$useTimestamps``created_at``updated_at``deleted_at``$dateFormat``int`
> 
> CI4 use IS NULL judgment the column data is delete. is not null. so , the column is deleted.
> you should set is true. system can auto set , ,
> if you want use int(11) save timestamps, you muse set is `deleted_at``0``$useTimestamps``created_at``updated_at``deleted_at``$dateFormat``int`

好的，谢谢，我设置为 int 是为了存时间戳，可能是我把哪里设置错误了，框架执行的时候存储成为2020了 

好的，谢谢，我设置为 int 是为了存时间戳，可能是我把哪里设置错误了，框架执行的时候存储成为2020了
OK, thank you. I set int to save timestamps. Maybe I set it wrong. It's 2020 when the framework executes

**Comment by nabadao** [comment]
> 你的数据库相应字 默认应该设置为NULL
> in database, `created_at`, `updated_at`, `deleted_at` muse set `Allow NULL` and `DEFAUILT VALUE IS NULL`

谢谢 按照你说的设置就可以了
hank you. Just follow your setup
