### ISSUE TITLE
Bug: Model Instantiation

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#2924]
I am trying to load model dynamically just like a controller would work.

Up in my controller i have the namespace set

```
$Model = 'BannersModel';
$this->Model = new $Model();
```
But this does not work.
If i have this code

`$this->Model = new BannersModel();`

This works perfectly.

What i am trying to do only works if i have the hole namespace in the instantiation like this

```
$Model = 'App\\Models\\BannersModel';
$this->Model = new $Model();
```

Is there a way to load the model from the namespace without typing the namespace fully when i instantiate ?

**Comment by crustamet** [comment]
I know i ask all time stupid questions dude.
Please someone answer even if it doesn't help, maybe it does.

I really want to automate a system using codeigniter 4 pls.
I found a way but i had to remake all model folders.

I was using nested folders.

**Comment by lonnieezell** [comment]
You have got to be a little more patient than just waiting an hour for a response. This is staffed by volunteers. Additionally, this is not a bug in the framework, so you should use the forums. 

Quick answer: Doesn't look like it. But you could try using some of the features in the FileLocater class to search through namespaces and find the class for you.
