### ISSUE TITLE
URL rewrite problem

### ISSUE THREAD

**Issue by khaiphan9x** [codeigniter4/CodeIgniter4#2925]
I'm trying to point a subweb to a Controller, I don't want to interfere with Routes.  I tried to point ^(.*) to index.php /subweb/$1, but it didn't work.  I think this is an Apache problem, I'm looking for a similar solution that points to index.php?controller=$1.  Is there any solution?

**Comment by jlamim** [comment]
If you are using the standard CI4 structure, you have to be aware that the default public directory is `/public` and no longer the root where the application is installed.

So, in order not to need changes, you must place the subfolders inside `/public`.

If you have changed the directory structure, and you are not using `/public`, then it will depend on your directory structure. (if you changed it, please share it as it is after the change).

If you did not make any notes, redirecting access to `/public` using a` .htaccess` file at the root of the application, the subfolders can be at the root, at the same level of `/public` and `/app` for example that will work.

If you are redirecting to `/public`, then you must place these subfolders inside `/public` or create rules in the root `.htaccess` file to tell the Apache server what to do when access is attempted to an existing folder.

**Comment by khaiphan9x** [comment]
> Nếu bạn đang sử dụng cấu trúc CI4 tiêu chuẩn, bạn phải lưu ý rằng thư mục chung mặc định là `/public`và không còn là gốc nơi ứng dụng được cài đặt.
> 
> Vì vậy, để không cần thay đổi, bạn phải đặt các thư mục con bên trong `/public`.
> 
> Nếu bạn đã thay đổi cấu trúc thư mục và bạn không sử dụng `/public`, thì nó sẽ phụ thuộc vào cấu trúc thư mục của bạn. (nếu bạn thay đổi nó, vui lòng chia sẻ nó như sau khi thay đổi).
> 
> Nếu bạn không thực hiện bất kỳ ghi chú nào, chuyển hướng truy cập vào `/public`việc sử dụng ` .htaccess`tệp ở thư mục gốc của ứng dụng, các thư mục con có thể ở gốc, ở cùng cấp độ `/public`và `/app`ví dụ như vậy sẽ hoạt động.
> 
> Nếu bạn đang chuyển hướng đến `/public`, thì bạn phải đặt các thư mục con này bên trong `/public`hoặc tạo quy tắc trong `.htaccess`tệp gốc để báo cho máy chủ Apache biết phải làm gì khi truy cập vào thư mục hiện có.



> If you are using the standard CI4 structure, you have to be aware that the default public directory is `/public` and no longer the root where the application is installed.
> 
> So, in order not to need changes, you must place the subfolders inside `/public`.
> 
> If you have changed the directory structure, and you are not using `/public`, then it will depend on your directory structure. (if you changed it, please share it as it is after the change).
> 
> If you did not make any notes, redirecting access to `/public` using a` .htaccess` file at the root of the application, the subfolders can be at the root, at the same level of `/public` and `/app` for example that will work.
> 
> If you are redirecting to `/public`, then you must place these subfolders inside `/public` or create rules in the root `.htaccess` file to tell the Apache server what to do when access is attempted to an existing folder.

Sorry this is not my problem, I left Document Root as /public, as mentioned above, I am trying to point all Requests to a Controller with .htaccess.  Thanks

**Comment by jlamim** [comment]
So it seems to me that your problem is not characterized as a bug. Therefore, the correct place and with more solution information is in the Forum.

https://forum.codeigniter.com
