### ISSUE TITLE
Bug: Translation key separated by dot

### ISSUE THREAD

**Issue by MichalPB1** [codeigniter4/CodeIgniter4#2932]
**Describe the bug**
In version 4.0.2 translation keys may be separated by a dot. E.g

```
return [
     'quantity' => 'Quantity',
     'logs.quantity' => 'The quantity of the product has been changed to <b>{value}</b>',
];
```

However, in version 4.0.3 it no longer works as before. The `logs.quantity` key is not found, but strangely, the value from the` quantity` key is returned. If the `quantity` key is deleted, we get nothing.

After changing the split into nested arrays, everything works as it should

```
return [
    'quantity' => 'Quantity',
    'logs' => [
        'quantity' => 'The quantity of the product has been changed to <b>{value}</b>',
    ],
];

```

**CodeIgniter 4 version**
4.0.3

**Affected module(s)**
Language

Probably after changes in this pull request https://github.com/codeigniter4/CodeIgniter4/pull/2833

**Expected behavior, and steps to reproduce if appropriate**

If we don't use nested arrays in translations

`lang ('Product.quantity')` should return `Quantity`

`lang ('Product.logs.quantity')` should return `The quantity of the product has been changed to <b>{value}</b>`

**Context**
 - OS: Ubuntu
 - Web server cli-server
 - PHP version 7.3

**Comment by samsonasik** [comment]
I've created PR #2938 for it.
