### ISSUE TITLE
Bug: init of $data arrays in controllers

### ISSUE THREAD

**Issue by Conspir3D** [codeigniter4/CodeIgniter4#2933]
**Description**
When you fill an array in a controller function, typically the $data array, and the first value is a returned array from a models function, the key won't be populated. look at **expected behaviour**

**CodeIgniter 4 version**
4.0.3

**Affected module(s)**
Seems that the bug is somwhere around controller/modell package

**Expected behavior, and steps to reproduce if appropriate**
not working, $data['data'] **is not** populated at 'page' view:

```
$data['data'] = $model->getData($id);
$data['title'] = 'Page for '.$data['data']['dataname'];
$data['something'] = 'else';

echo view('page', $data);
```

working, $data['data'] **is** populated at 'page' view:

```
$data['something'] = 'else';
$data['data'] = $model->getData($id);
$data['title'] = 'Page for '.$data['data']['dataname'];

echo view('page', $data);
```

**Context**
 - OS: Debian Linux 10
 - Web server Apache2
 - PHP version 7.3

**Comment by Instrye** [comment]
Can you `var_dump($data)` show data? I want know `$data['data']` value type.
![image](https://user-images.githubusercontent.com/9927289/81154256-515b9e00-8fb6-11ea-85de-a1a2eb8269fe.png)
![image](https://user-images.githubusercontent.com/9927289/81154276-5587bb80-8fb6-11ea-9311-b0abd5acdcba.png)
![image](https://user-images.githubusercontent.com/9927289/81154321-5e788d00-8fb6-11ea-946f-833c04387b8e.png)

**Comment by samsonasik** [comment]
`$data` in the view is refer to 'data' key, not the `$data` in the controller, so, you can call in the view:

```php
echo $data['dataname'];
```

**Comment by michalsn** [comment]
Not a bug.
