### ISSUE TITLE
Bug:  start migration in manual mode

### ISSUE THREAD

**Issue by lebidvadim** [codeigniter4/CodeIgniter4#2942]
**Direction**
migrations

**Describe the bug**
when migrations are manually started via the **$migrate->latest()** function; it creates only the migrations table and does not find all namespaces. 

**CodeIgniter 4 version**
4.0.3.

**Affected module(s)**
**system\ Database\MigrationRunner.php** line **475**

**Expected behavior, and steps to reproduce if appropriate**
it’s not clear why you did that check because APP gets into **$this->namespace** and in **Services:: autoloader ()->getNamespace()** it is already there, and that check turns out like I don’t need.

**Context**
 - OS: [e.g. Windows 11]
 - Web server [e.g. Apache 1.2.3]
 - PHP version [e.g. 7.2]

**Comment by Instrye** [comment]
you migration file name is ?
```
Migration file names
Each Migration is run in numeric order forward or backwards depending on the method taken. Each migration is numbered using the timestamp when the migration was created, in YYYYMMDDHHIISS format (e.g. 20121031100537). This helps prevent numbering conflicts when working in a team environment.

Prefix your migration files with the migration number followed by an underscore and a descriptive name for the migration. The year, month, and date can be separated from each other by dashes, underscores, or not at all. For example:

20121031100537_add_blog.php
2012-10-31-100538_alter_blog_track_views.php
2012_10_31_100539_alter_blog_add_translations.php
```

**Comment by Instrye** [comment]
if you want run all namespace, you can use
`$migration->setNamespace(null)->latest()`

**Comment by lebidvadim** [comment]
so why should I do this if the documentation says use **$migrate->latest ()**

**Comment by MGatner** [comment]
> You can also use `$migration->setNamespace(null)->latest()` to include migrations from all namespaces.

It is literally the next line.

**Comment by samsonasik** [comment]
can be closed in favor of https://github.com/codeigniter4/CodeIgniter4/pull/2943
