### ISSUE TITLE
Bug: Validation tries to validate inputs even for empty values with no `required` parameter

### ISSUE THREAD

**Issue by pars0097** [codeigniter4/CodeIgniter4#2951]
assume we have a form with 2 text input, 1st for the name, and 2nd for email.
and here are our rules:
```
$rules = [
            'name' => [
                'label'  => 'Name',
                'rules'  => 'required',
            ],
            'email' => [
                'label'  => 'Email',
                'rules'  => 'min_length[6]|valid_email'
            ]
        ];
```
when a user insers a name but not email validation show errors for `min_lenght` and `valid_email`
the `POST/GET` input  is somthing like this:
```
['name'=>'user_entered_name'', 'email'=>'']
```
logically `min_length[6]|valid_email` is working the right way. but sience `email` field is not required in user form  it shoudn't validate when empty string passed as email value.
if i could pass filtered input (remove indexes with empty value) to `validate()` the problem was solved  but I didn't find any method to validate custom data (not `$_GET / $_POST`).
I think there should be a method like `setValidationData($myArray)` or like this.

**Comment by michalsn** [comment]
Not a bug. `permit_empty` rule is here to the rescue :) 

And BTW, even in controller you can always use validation class directly:
```php
service('validation')->setRules($rules)->run($customData);
```
