### ISSUE TITLE
Pager should have getTotalResults method function

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#2954]
I am requesting this because it is easy to make.

The problem is when i am using **Paginate on model** and it makes this query that counts all results from the database.
But i have no option to retrieve the Total Count and have to make another query to get countAllResults again.

**So i am duplicating queries because of this.**

**Comment by crustamet** [comment]
Code for getTotalResults from Pager

	/**
	 * Returns the total count of the results.
	 *
	 * @param string|null $group
	 *
	 * @return integer
	 */

	public function getTotalResults(string $group = 'default'): int
	{
		$this->ensureGroup($group);
		
		return $this->groups[$group]['total'];
	}

This works great Surely as i see the pattern from all other functions

**Comment by michalsn** [comment]
We already have the `getDetails()` method which will return a handful of data as an array - including `total` number of results.
