### ISSUE TITLE
Bug: Documentation Issue

### ISSUE THREAD

**Issue by Melluish** [codeigniter4/CodeIgniter4#2960]
In "CodeIgniter4/user_guide_src/source/tutorial/news_section.rst" at the very bottom of the "Display the news" section in the note you mention that you're passing the second parameter of "url" to the "esc" function, but in the code snippet you don't appear to be.

Should the parameter be passed or should the note be amended?

**Comment by jreklund** [comment]
You should use it, I put the note in the bottom. It's used here:
`<p><a href="/news/<?= esc($news_item['slug'], 'url'); ?>">View article</a></p>`

I can see #2961 are moving it.

**Comment by Melluish** [comment]
Oh, I see it. Yeah, should be closer to the context in which it's being used. Thanks.
