### ISSUE TITLE
Bug: URI class - working with segments is really strange

### ISSUE THREAD

**Issue by michalsn** [codeigniter4/CodeIgniter4#2962]
**Describe the bug**
I think there is a problem in the way that some methods are handling segments right now.
Here is an example:
```php
$uri = new \CodeIgniter\HTTP\URI('http://something.com/hello/there');

// will return ['hello', 'there']
d($uri->getSegments());
// will return 'hello' - ok
d($uri->getSegment(1));
// will return 'there' - ok
d($uri->getSegment(2));
// will return '' - why? it's not there
d($uri->getSegment(3));
// will throw an exception - ok
// not really easy to work with but this is a different story
d($uri->getSegment(4));
```
Here we go with a really strange part:
```php
$uri = new \CodeIgniter\HTTP\URI('http://something.com/hello/there');

// will return '' - why? it's not there
d($uri->getSegment(3));
// will NOT throw an exception (even if segment 3 is not set)
d($uri->setSegment(4, 'honey'));
// will return '' - that's surprising considering no error when
// we set it a line before
d($uri->getSegment(4));
// will return 'honey'
d($uri->getSegment(3));
```
Actually I don't think it's very complicated to fix, but the main problem are BC changes. People can already rely on the empty string that is returned in some cases. So the question is how should it be handled.

Also working with `getSegment()` and throwing an exception when segment is not there is not very easy to work with. So it would be good to have something to surpass this without the need of catching the exception every time. One idea was proposed here: #2952

**CodeIgniter 4 version**
All versions

**Affected module(s)**
URI class

**Expected behavior**
```php
$uri = new \CodeIgniter\HTTP\URI('http://something.com/hello/there');

// should throw an exception
d($uri->getSegment(3));

```

```php
$uri = new \CodeIgniter\HTTP\URI('http://something.com/hello/there');

// should throw an exception
d($uri->getSegment(3));
// should throw an exception
d($uri->setSegment(4, 'honey'));
// should throw an exception
d($uri->getSegment(4));
```

**Comment by crustamet** [comment]
If you want to get the exception use the request Class
`$request->getSegment(3)`

This works for me.

The uri should not throw exceptions by itself, but i see it return empty string, maybe it should return NULL because there aren't any

**Comment by michalsn** [comment]
@crustamet there is no `$request->getSegment()` method. You probably think about `$request->uri->getSegment()` - this method exists and is an alias to the same class I'm referring in this issue.

**Comment by crustamet** [comment]
Oh yes i was talking about that, and now i see that come empty when should throw exception.

**Comment by crustamet** [comment]
I don't know what is happening really with this uri, for me it works good.
Besides it does not work exactly how it needs to work

Ex : https://example.com/admin/cms/socials

	$uri->getSegment(-1); //returns empty
	$uri->getSegment(0); //returns empty
	$uri->getSegment(1); //returns empty
	$uri->getSegment(2); //returns admin
	$uri->getSegment(3); //returns cms
	$uri->getSegment(4); //returns socials
	$uri->getSegment(5); //returns empty
	$uri->getSegment(6); //returns throw error exception

I do not know why it does this it seems like the segment **1** and the last segment available **5** are always empty only if your base_url is set **https://example.com/admin/**

If not base_url with **/admin/**
it does crazy shit if you have no slash "/" at the end in the base_url

And another thing is when your httaccess rewrites this there are another bunch of shit happening.

So i really don't know exactly what is happening with these segments.
For now i manage to work with them and have no problems.
