### ISSUE TITLE
Bug: There's no way to change default spark serve port using code

### ISSUE THREAD

**Issue by willnode** [codeigniter4/CodeIgniter4#2966]
**Describe the bug**
I'm trying to create a custom CLI command to `spark serve --port 4000`. I tried this:

```php
namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;

class Start extends BaseCommand
{
	protected $group       = 'App';
	protected $name        = 'start';
	protected $description = 'Start Server on Port 4000';

	public function run(array $params)
	{
		$this->call('serve', ['-port', '4000']);
	}
}
```

And running `php spark start`. However it serving port 8080 instead.

My best guess that it's happened because the `$params` argument is not considered in `Serve.php`:

https://github.com/codeigniter4/CodeIgniter4/blob/a063f14e62b36531f52afa0bf71b8e54c00f6399/system/Commands/Server/Serve.php#L129

https://github.com/codeigniter4/CodeIgniter4/blob/a063f14e62b36531f52afa0bf71b8e54c00f6399/system/Commands/Server/Serve.php#L140-L143

**CodeIgniter 4 version**
Latest version

**Affected module(s)**
None, I think

**Expected behavior, and steps to reproduce if appropriate**
It's serving at the custom port (4000)

**Context**
 - OS: Windows 10 64 Bit
 - PHP version 7.3.9

**Comment by samsonasik** [comment]
For quick tweak, I think you can do something like this:

```php
        (function ($cli) {
            $cli::$options = [
                'port' => 4000,
            ];
        })->bindTo($cli = new \CodeIgniter\CLI\CLI(), $cli)($cli);

        $this->call('serve');
```

**Comment by samsonasik** [comment]
Another way can be like this: 

```php
	public function run(array $params)
	{
		$_SERVER['argv'][2] = '--port';
		$_SERVER['argv'][3] = '4000';
		$_SERVER['argc']    = 4;
		\CodeIgniter\CLI\CLI::init();

                $this->call('serve');
	}
```

**Comment by willnode** [comment]
Thanks @samsonasik. Seems kinda dirty workaround but I like it.

Not sure if I can call this a 'bug' anymore. But if the true implementation to provide args with `$params` does too much, please close this issue.

**Comment by samsonasik** [comment]
@willnode I can't close it, I'm not maintainer
