### ISSUE TITLE
Bug: form_upload second parameter VALUE is not used in source code 

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#2967]
This is the code in **form_helper**

	function form_upload($data = '', string $value = '', $extra = ''): string
	{
		$defaults                = [
			'type' => 'file',
			'name' => '',
		];
		is_array($data) || $data = ['name' => $data];
		$data['type']            = 'file';

		return '<input ' . parse_form_attributes($data, $defaults) . stringify_attributes($extra) . " />\n";
	}

Surely we see that the **$value** is **not used** inside this function. from the source code

**Comment by crustamet** [comment]
And because of this set_value for files does not work.
I am trying to upload a file and when i have form errors from validation rules
the upload file gets removed.

I am trying a bunch of shit code to fix this. So much work i have to do with form_upload and set_value dude.

**Comment by crustamet** [comment]
No one ? 🗡️
Please someone review this. This is very important to me.
I am eager to show you the code how i resolve this very weird but i got up some very big problems with it.
Someone please comment here about this issue Thanks.

**Comment by michalsn** [comment]
I don't think this is possible. This is blocked on a browser level. Maybe there is some hacky way to accomplish this, but this would be a security issue.

The valid question is why do we have `$value` variable there, but I guess it is because of the direct import from CI3.

**Comment by crustamet** [comment]
i have a way to save the file if was valid file anyways. and store it but i don't know how to implement this in the firm helper.
