### ISSUE TITLE
Relax the requirement for SQL to be a string

### ISSUE THREAD

**Issue by JanZelenka** [codeigniter4/CodeIgniter4#2969]
Hi!
I'm building a Database driver. The difficulty is that the database engine is queried using an API, not SQL. As a consequence the table (FROM clause) is a part of the API URL, not the query itself. I would find it helpful if the DB methods that work with the $sql parameter could be relaxed not to require strictly the string data type and allow an array as well.
Thanks for considering

**CodeIgniter 4 version**
4.0.3

**Affected module(s)**
Database

**Comment by MGatner** [comment]
Could you provide an example of what you're talking about it?

**Comment by JanZelenka** [comment]
It goes like this:
I have a Builder class that creates the queries for me - which need to be in a JSON format. Also, since it is API based, the table name is a part of the URL but the where clause is in the body.
To properly use the Connection class I need to pass these array based queries as string, in my override of the execute() method convert them back to arrays, extract the different pieces of information and then convert back to string to use in the API call.

It's lot of converting back and forth that could be skipped if methods like simpleQuery(), execute() and so would allow for arrays to passed in.

**Comment by lonnieezell** [comment]
Unfortunately I don't think we can do that unless it is in the next major release. All of the current drivers have type-hinting of `string`. If anyone is using that to cast variables into a string for them it would be completely broken.

**Comment by MGatner** [comment]
Stringables are accepted for string typehints, so you can accomplish this by passing a class with `__toString()` and you could use your arrays as an Iterable.
