### ISSUE TITLE
Bug: Mistake in uri_string() documentation

### ISSUE THREAD

**Issue by SoulReaver** [codeigniter4/CodeIgniter4#2972]
**Describe the bug**
According to [docs](https://codeigniter.com/user_guide/helpers/url_helper.html?highlight=uri_string#uri_string) `uri_string` function

> Returns the path part of your current URL.

While it returns path part relative to base_url.

**CodeIgniter 4 version**
4.0.3

**Affected module(s)**
docs (or URL Helper if what's in docs was the intended functionality)

**Expected behavior, and steps to reproduce if appropriate**
example page in service: example.com/ci-blog/login
base url: example.com/ci-blog/
url to the page relative to base url: login
`uri_string` returns: login
according to docs it should return: /ci-blog/login (or without initial slash)

While it can be considered that it's the function that does not work as intended, I think the way it works currently is the one that's the most useful. That's why I'd like to suggest updating documentation instead:

> Returns the path part of your current URL ** that is relative to base url**.

**Context**
 - OS: Windows 10
 - Web server: Apache 2.4.41
 - PHP version: 7.3.12

**Comment by michalsn** [comment]
Yes, it's a mistake in the docs. We definitely want it to be relative to `baseUrl`.
