### ISSUE TITLE
Bug: CI_DEBUG incorrect type and fails strict validation

### ISSUE THREAD

**Issue by John-Betong** [codeigniter4/CodeIgniter4#2975]
Adding the following script to index.php and to every single ./system PHP file makes the script **compatible** with the PHP Strict 7.?? source. 

If and only if **'declare(strict_types=1)'** is declared in the parent file will strict_types have any effect.

<?php DECLARE(STRICT_TYPES=1); ?>

The following three files fail PHP strict validation because they "type juggle" to change the numeric to a bool:

Files:
./app/Config/Boot/development.php
./app/Config/Boot/production.php
./app/Config/Boot/testing.php

// FAIL
// defined('CI_DEBUG') || define('CI_DEBUG', 1);

// PASS:
defined('CI_DEBUG') || define('CI_DEBUG', TRUE);

These three small changes make it possible to render the Welcome page using PHP Strict Mode.

**Comment by lonnieezell** [comment]
Submit a PR and I'll be happy to merge.
