### ISSUE TITLE
Bug: Blank Page on Production Server

### ISSUE THREAD

**Issue by Andrewsuares** [codeigniter4/CodeIgniter4#2980]
Using Codeigniter 4.0.3

We were seeing a blank page after uploading CodeIgniter to our linux server. After days of troubleshooting, I figured this was the problem below in Events.php. Disabled it from line 25 and the page loaded. Can you please fix this. Codeigniter 3 was known to just work out of the box. Having an IF statement here that works only on production means that devs wouldn't see this during testing.
Events::on('pre_system', function () {
	if (ENVIRONMENT !== 'testing')
	{
		while (\ob_get_level() > 0)
		{
			\ob_end_flush();
		}

		\ob_start(function ($buffer) {
			return $buffer;
		});
	}

**Comment by paulbalandan** [comment]
By any chance, is your `php.ini` setting `zlib.output_compression` not turned off? I have a case where zlib compression is on and output buffering is on resulted to a blank page.

**Comment by Andrewsuares** [comment]
From my php.ini. 

zlib.output_compression = On

Out buffering needs to check this setting and enable or disable itself automatically or throw up an error.

**Comment by khairilazizee** [comment]
My zlib.output_compression = Off, but i still get the error. why? 

i am using mamp in windows.

**Comment by paulbalandan** [comment]
check if you have write permissions on the writable folder

**Comment by khairilazizee** [comment]
i have the write permission on all folder.  Is this happen because i am using mamp?

**Comment by paulbalandan** [comment]
please raise your support question in the [forum](forum.codeigniter.com). Others may have faced your issue and have solutions.
