### ISSUE TITLE
[Feature request] Slugs Link

### ISSUE THREAD

**Issue by muh-ramadhan** [codeigniter4/CodeIgniter4#2988]
I Hope The Link Slugs Function Is Added As A Text Helper In The Next Codeigniter Version.

For Example I Use a Helper.

> `helper('slug');` Load Slug Helper

Example slug_helper.php

> function slug_link($slug) {$array = array (' ');
$array_data = array ('-', '/', '\\', ',', '.', '#', ':', ';', '\'', '"', '[',']', '{','}', ')', '(', '|', '`', '~', '!', '@', '%', '$', '^', '&', '*', '=', '?', '+', '–');
$slug = str_replace($array_data, '', $slug); //Remove Character From Data array_data
$trim = trim($slug); //Remove Space First And Last
$preg_replace = preg_replace('/\s+/', ' ', $trim); //Remove Doube Space
$slug = strtolower(str_replace($array, '-', $preg_replace)); //Change Single Space To - And To Lowecase
return $slug;
}

Function Save

> $data = [
'slug_link'		=> slug_link($this->request->getPost('title')), //slug_link From Helper
];

Output Clear

> text-text-text-text

**Comment by lonnieezell** [comment]
I believe you're looking for [url_title()](https://codeigniter.com/user_guide/helpers/url_helper.html)
