### ISSUE TITLE
Bug: Force download

### ISSUE THREAD

**Issue by khaiphan9x** [codeigniter4/CodeIgniter4#2995]
PHP error: Error Call to a member function setFileName() on null
```
/*
var_dump(is_file($path)); // return true
var_dump(basename($path)); // return test.zip
*/
return $this->response->download($path)->setFileName(basename($path));
```
CI Version: 4.0.2
PHP Version: 7.4.3

**Comment by paulbalandan** [comment]
Try setting the second argument of `$this->response->download` to a value of `null`.

**Comment by khaiphan9x** [comment]
> Try setting the second argument of `$this->response->download` to a value of `null`.

According to the documentation, the second argument is unnecessary.  Is this counted as a bug?

**Comment by paulbalandan** [comment]
From the docs:
If you set the second parameter to NULL and `$filename` is an existing, readable file path, then its content will be read instead.

Based on your code example, you really need to set the second argument to null.
