### ISSUE TITLE
Bug: incorrect type - system/Database/MYSQLi/Connection.php

### ISSUE THREAD

**Issue by John-Betong** [codeigniter4/CodeIgniter4#2996]
Build: ace3f2c - Thursday May 14th, 2020

Over 420 files have the following declaration added:

`<?php DECLARE(STRICT_TYPES=1); ?>`

There is only a single file remaining which prevents STRICT_TYPES validation.

file:  ./system/Database/MYSQLi/Connection.php
`
public function connect(bool $persistent = false)
{
// Do we have a socket path?
if ($this->hostname[0] === '/')
{
	$hostname = null;
	$port     = null;
	$socket   = $this->hostname;
}
else
{
	$hostname = ($persistent === true) ? 'p:' . $this->hostname : $this->hostname;
	$port     = empty($this->port) ? null : $this->port;
// OLD
	$socket   = null; 
// NEW
	$socket   = (string) null; // JOHN ADDED (string)
}

`

Online demo: https://ci4-strict.tk

**Comment by michalsn** [comment]
PR is always welcome.
