### ISSUE TITLE
Bug: current_url() loses subdomain

### ISSUE THREAD

**Issue by divpusher** [codeigniter4/CodeIgniter4#3004]
Hello!

I set up my site in a way to use subdomains as a language parameter, e.g.:

mydomain.com
de.mydomain.com
fr.mydomain.com

Unfortunately, I had to realize that when I use the `return redirect()->to('/anything');` function, it loses the subdomain. I tracked the issue back to the **current_url()** function. That's where the subdomain goes missing. E.g.:

```
// you are on https://de.mydomain.com
echo current_url(); // displays https://mydomain.com
```

I think the default, expected behavior would be to keep the subdomain. The **base_url()** function already returns the base url from the config, if someone wants that.  Also, I wouldn't want to rewrite **every** redirect now in all of my controllers after months of work because of this.

According to the [docs](https://codeigniter4.github.io/userguide/helpers/url_helper.html?highlight=current_url#current_url), **current_url()** _"returns the full URL (including segments) of the page being currently viewed"_. So, I think it should contain the subdomain as well. Or is there any security reason why it works this way, maybe?

**Comment by Instrye** [comment]
the method use `App/Config/App::$baseURL` OR `.ENV::baseURL`

**Comment by ivantcholakov** [comment]
Well, the easiest way is url autodetection to be implemented and the configuration option to be chaged this way:

```php
    //public $baseURL = 'http://localhost:8080/';
    public $baseURL = \DETECTED_BASE_URL;
```

I know that autodetection is not liked, but I think, a secure and relatively reliable way is possible. $_SERVER['HTTP_HOST'] should not be used, only server controlled variables can do the job. Also, if the site is placed under a subdirectory this case could be autodetected too, it is possible. 

Autodectection may not be set by default, it could be proposed in the setting comment with an appropriate warning.

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/starter-public-edition-5/blob/32d6c09eaace3e6eb03b7a7d643e381ad719bdd7/platform/bootstrap/helpers.php#L129

https://github.com/ivantcholakov/starter-public-edition-5/blob/32d6c09eaace3e6eb03b7a7d643e381ad719bdd7/platform/bootstrap/bootstrap.php#L240

**Comment by michalsn** [comment]
@ivantcholakov from what I see in the code you linked you're relying on a `$_SERVER['SERVER_NAME']`. Sadly this gives you pretty much the same level of security as when using `$_SERVER['HTTP_HOST']`.

Autodetection will never happen. But we might think about something like `allowedHosts` variable which can contain allowed hosts (possibly with wildcard support for subdomains?).

**Comment by ivantcholakov** [comment]
Maybe this whole autodetection with a list of allowed baseUrls that would be checked with preg_match() would be better? I want sub-directories to be detected too.

**Comment by ivantcholakov** [comment]
https://expressionengine.com/blog/http-host-and-server-name-security-issues

**Comment by ivantcholakov** [comment]
Here is an additional draft for for restriction of site access to trusted host names only.

https://github.com/ivantcholakov/starter-public-edition-5/commit/caeec137ace6e2e6391b4579a6a04711a4448b3b

**Comment by MGatner** [comment]
All of the `*_url()` functions are intentionally based on the Config (i.e. baseURL, indexPage, forceSecureRequests) and not intended to match the browser URL. As you have noted, detection is pretty complicated and not guaranteed to be accurate so the framework focuses on getting an accurate path and then relying on the developer to handle the rest.
