### ISSUE TITLE
Class 'App\Models\UserModel' not found

### ISSUE THREAD

**Issue by ckgan88** [codeigniter4/CodeIgniter4#3014]
use CodeIgniter\Controller;
use App\Models\UserModel;

class Login extends Controller {

	protected $helpers = ['html','form', 'url'];

    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger) {
        parent::initController($request, $response, $logger);

        //--------------------------------------------------------------------
        // Preload any models, libraries, etc, here.
        //--------------------------------------------------------------------

        $this->session   = Services::session();
        $this->usermodel = new UserModel(); <-------------- this no found
    }

====================== Model Class Below ======================

 namespace App\Models;
    
use CodeIgniter\Model;

class Usermodel extends Model {

    protected $table = 'tbl_users';

    public function __construct() {
        parent::__construct();
        
        $db = \Config\Database::connect();
        $bd = $db->table($this->table);
    }
}

In my localhost, it work good. But once i upload to server. It show
Class 'App\Models\UserModel' not found
Please help. Im new Codeigniter. Thanks

**Comment by samsonasik** [comment]
your classname must be UserModel, not Usermodel. Please ask in forum instead for question.

**Comment by ckgan88** [comment]
> your classname must be UserModel, not Usermodel. Please ask in forum instead for question.

Opsss, Thanks. You are awesome thanks.

**Comment by truelineinfotech** [comment]
i am sure you localhost will be on windows os
