### ISSUE TITLE
Bug: delete_files() and hidden directories

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#3015]
**Describe the bug**
`delete_files()` in the Filesystem Helper currently ignores hidden directories. I'm not sure if this is a "bug" since the code seems to do it deliberately (notice the first line):
```
if (is_dir($path . DIRECTORY_SEPARATOR . $filename) && $filename[0] !== '.')
{
	delete_files($path . DIRECTORY_SEPARATOR . $filename, $del_dir, $htdocs, $_level + 1);
}
elseif ($htdocs !== true || ! preg_match('/^(\.htaccess|index\.(html|htm|php)|web\.config)$/i', $filename))
{
	@unlink($path . DIRECTORY_SEPARATOR . $filename);
}
```
But this isn't documented anywhere and seems an odd exclusion. For example, cleaning up an example project `delete_files()` fails to remove the root directory because it contains **.github/**.

If leaving hidden directories is intentional, then I would be in favor of giving this the same treatment as `get_filenames()`: remove the recursive call, use a `RecursiveIteratorIterator` instead, and add a parameter for `bool $hidden = false`.

**CodeIgniter 4 version**
`develop`

**Affected module(s)**
Helpers > Filesystem

**Expected behavior, and steps to reproduce if appropriate**
Given:
ROOT/app/[files]
ROOT/writable/[files]
ROOT/.github/[files]

I would expect calling `delete_files('ROOT', true)` to wipe the whole project, but it does not.

**Context**
 - OS: Linux
 - Web server: Apache
 - PHP version: 7.3

**Comment by lonnieezell** [comment]
This is a direct port from previous versions, I believe, so I couldn't tell you the reasoning. 

I'm good with your suggestion.
