### ISSUE TITLE
Bug: select() & selectSum() not consistent / aligned with docs

### ISSUE THREAD

**Issue by Xirt** [codeigniter4/CodeIgniter4#3019]
**Bug description**
Although parameters descriptions on usage of select() and selectSum() are similar on https://codeigniter.com/user_guide/database/query_builder.html, the first method accepts Arrays as input in practice while the latter does not. The easy fix could be to disallow Arrays for select(), but based on the use case for these methods I would expect alignment on acceptance of Arrays. This would prevent many occurences of the method selectSum() in case this is required.

**CodeIgniter 4 version**
4.0.1

**Affected module(s)**
CodeIgniter\Database\BaseBuilder

**Expected behavior, and steps to reproduce if appropriate**
The below (simplified) code reproduces the issue.

```
$db = \Config\Database::connect();
$builder = $db->table('table');
$builder->select(["field_a", "field_b", "field_c"]); // allowed
$builder->selectSum(["field_d", "field_e", "field_f"]); // not allowed
$query = $builder->groupBy("field_group")->get()
```

**Potential fix**
I believe it could be fixed in BaseBuilder::selectSum() by checking for Arrays, looping through them and then feeding them into the method maxMinAvgSum($select, $alias, $type). Potentially this should be done also for other methods (min, max, ...) and obviously documentation should be aligned. Alternatively, this loop could be placed in a seperate method as the logic is likely the same for all these related methods (min, max, ...); only the $type fed into maxMinAvgSum($select, $alias, $type) differs.
```
public function selectSum($select = '', string $alias = '')
{

    if (is_array($select))
    {

        foreach ($select as $current)
        {

            $current = is_string($current) ? [$current] : $current;
            $this->maxMinAvgSum($current[0] ?? '', $current[1] ?? '', 'SUM');

        }

        return $this;

    }

	return $this->maxMinAvgSum($select, $alias, 'SUM');
}
```

**Context**
 - OS: Windows 10
 - Web server: Apache
 - PHP version 7.3.12

**Comment by paulbalandan** [comment]
These two methods are `faux amis` (false friends). They appear to have similar signatures but their usage are actually different so they can't have the same handling of parameters due to the nuances each method has.
