### ISSUE TITLE
Bug: getPostGet($index) return $_POST if there is no $index  in post and get

### ISSUE THREAD

**Issue by vebomedia** [codeigniter4/CodeIgniter4#3020]
in 4.0.3 

$start = $this->request->getPostGet('start');

if( ! empty($start) )
{
   //always true because getPostGet('start') return all $_POST if  there is no $_POST['start']
}

that was good working on V4.0.2

this function should be return NULL if there no $_POST['start'] && $_GET['start']

**Comment by Instrye** [comment]
Sorry. it's my mistake.
