### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by argiamahya** [codeigniter4/CodeIgniter4#3021]
my error is 
PHP Warning:  require(D:\xampp\htdocs\myCIapp\app\Config/../../vendor/codeignite
r4/framework/system/bootstrap.php): failed to open stream: No such file or direc
tory in D:\xampp\htdocs\myCIapp\spark on line 44

Warning: require(D:\xampp\htdocs\myCIapp\app\Config/../../vendor/codeigniter4/fr
amework/system/bootstrap.php): failed to open stream: No such file or directory
in D:\xampp\htdocs\myCIapp\spark on line 44
PHP Fatal error:  require(): Failed opening required 'D:\xampp\htdocs\myCIapp\ap
p\Config/../../vendor/codeigniter4/framework/system/bootstrap.php' (include_path
='D:\xampp\php\PEAR') in D:\xampp\htdocs\myCIapp\spark on line 44

Fatal error: require(): Failed opening required 'D:\xampp\htdocs\myCIapp\app\Con
fig/../../vendor/codeigniter4/framework/system/bootstrap.php' (include_path='D:\
xampp\php\PEAR') in D:\xampp\htdocs\myCIapp\spark on line 44

why my project

**Comment by darklightcode** [comment]
Run `composer install`

**Comment by argiamahya** [comment]
ok thanks :)

**Comment by argiamahya** [comment]
i have another problem :
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codeigniter4/framework v4.0.3 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - codeigniter4/framework v4.0.2 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - codeigniter4/framework v4.0.1 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - codeigniter4/framework 4.0.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - Installation request for codeigniter4/framework ^4 -> satisfiable by codeigniter4/framework[4.0.0, v4.0.1, v4.0.2, v4.0.3].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by byazrail** [comment]
ext-intl required.

Try composer commands;
composer update --ignore-platform-reqs

**Comment by darklightcode** [comment]
You need to enable the intl extension in your php.ini, it's part of server requirements for Codeigniter 4, they state that in the readme page. [https://github.com/codeigniter4/CodeIgniter4#server-requirements](https://github.com/codeigniter4/CodeIgniter4#server-requirements)

**Comment by michalsn** [comment]
Please, use the forum for the support questions.

**Comment by rozaqabdul656** [comment]
hade

**Comment by FabricioPatrocinio** [comment]
I use linux, so this worked for me:
 `composer update --ignore-platform-reqs`

**Comment by fajarkun07** [comment]
not work for me here this error

```php
PHP Fatal error:  Uncaught Error: Call to undefined function CodeIgniter\locale_set_default() in /var/www/html/website_sekolah/vendor/codeigniter4/framework/system/CodeIgniter.php:184
Stack trace:
#0 /var/www/html/website_sekolah/vendor/codeigniter4/framework/system/bootstrap.php(181): CodeIgniter\CodeIgniter->initialize()
#1 /var/www/html/website_sekolah/spark(44): require('/var/www/html/w...')
#2 {main}
  thrown in /var/www/html/website_sekolah/vendor/codeigniter4/framework/system/CodeIgniter.php on line 184

```

**Comment by paulbalandan** [comment]
`composer update --ignore-platform-reqs` is just a temporary hack to pass the installation stage. `ext-intl` is a required PHP extension by CI 4. If you will not enable `intl` you cannot use its defined functions (`locale_set_default`) and classes (`MessageFormatter`) which are used across the framework and you will just get fatal errors.

**Enabling `ext-intl` is the permanent fix for this.**

**Comment by Imanur** [comment]
i have a errorr with my project

Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required 'C:\xampp\htdocs\ci4\vendor\codeigniter4\framework\system\Commands\Server/rewrite.php' (include_path='C:\xampp\php\PEAR') in Unknown on line 0

how? anybody know?

**Comment by mnurulhuda2** [comment]
Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs\ci4app\app
\Config/../../vendor/codeigniter4/framework/system\bootstrap.php' (include_path=
'C:\xampp\php\PEAR') in C:\xampp\htdocs\ci4app\spark:45
Stack trace:
#0 {main}

**Comment by arqprtma** [comment]
sesuaikan dengan versi xampp sebelumnya
