### ISSUE TITLE
Bug: Most validation rules enforce requirement of the field

### ISSUE THREAD

**Issue by element-code** [codeigniter4/CodeIgniter4#3025]
When using predefined validation rules like `alpha`, `decimal`, `greater_than` and `less_than` the field can't be optional, since these rules still kick in, even if the field is empty.

**Expected behavior and Suggestion**
Most of the predefined rules should pass trough if the field is `NULL`. Then use `required` to check for empty fields.
There might be issues with 0 numbers / decimals and required (`required` does not only check `NULL` - `empty(trim($str))`) but we could prevent these in custom or more specific rules instead of defining thousands of new rules like `decimal_optional`.

But we can't check if the Field is `NULL` before applying rules, because we want to be able to validate against `NULL` in some rules like `required` or maybe custom rules. So we have to check for `NULL` in every rule separately.

**Steps to reproduce**
Set `alpha` as validation rule, let the field blank and try to validate. In my opinion the validation error should only occur when using `alpha` **and** `required` together.

**Quickfix**
As stated in the comments, use the `permit_empty` rule.

**CodeIgniter 4 version**
Released 4.0.3

**Affected module(s)**
`Validation\{FormatRules, FileRules}` (at least)

**Comment by michalsn** [comment]
Just use `permit_empty` rule.

**Comment by element-code** [comment]
This does work, thanks for the quick reply.

Anyway i see the described behavior as a problem (bug or feature 🤷‍♂️), at least it should get discussed.

**Comment by michalsn** [comment]
This behavior was intended.

At this point, any change to the rules that you mentioned would be a BC change, so this will not happen.
