### ISSUE TITLE
Bug: Helpers at non-default locations are not found

### ISSUE THREAD

**Issue by JanZelenka** [codeigniter4/CodeIgniter4#3026]
I have a namespace: App\Libraries\FileMaker
at a corresponding location on the disc.
I also have a subfolder Helpers at that location with the file filemaker_helper.php in it.

According to the documentation the correct way to load this helper is: helper('App\Library\FileMaker\filemaker').
Unfortunatelly that doesn't work. The autoloader stops searching through the namespace segments once it matches the first one with the App namespace and attaches the Helpers segment followed by the rest of the namespace:
...app\Helpers\Library\FileMaker\filemaker_helper.php

**Version**: 4.0.3.
**Affected module**: Custom Helpers

**Comment by InsiteFX** [comment]
Helpers should go into folder helpers if use with app

otherwise modules should have there own helpers folder.

**Comment by JanZelenka** [comment]
I see. Of course, thanks for clarifying this. I need to declare my FileMaker namespace outside the App namespace...
