### ISSUE TITLE
Error: No input file specified.

### ISSUE THREAD

**Issue by gokhanalkan** [codeigniter4/CodeIgniter4#3030]
Hello, I get the error I mentioned in the title in the ci4 project. I reached the solution by making a small revision in the htacces file.
Before: RewriteRule ^ (. *) $ Index.php / $ 1 [L]
After: RewriteRule ^ (. *) $ Index.php? / $ 1 [L]
Will usage in this way cause a problem for the project?

**Comment by khaiphan9x** [comment]
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]
```

**Comment by michalsn** [comment]
No, it won't cause any problems. Some servers need custom changes to `.htaccess` file. 

I'm glad you worked it out.
