### ISSUE TITLE
Bug: File Validation not validate correctly.

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3032]
**Describe the bug**
I have a form that uploads an image.
So many cases i had to test to find that is not working correctly.

I have these rules that i am trying to make the app good but i am failing to do so.

      $Rules['image'] = ['label' => 'Image', 'rules'=>'uploaded[image]|is_image[image]|max_size[image.2048]'];

Case Required (1) with empty input.
i receive this error **Image is not a valid uploaded file**
Case 1 is ok.

Case Required (2) with file that is not an image.
i receive this error **Image is not a valid, uploaded image file.**
Case 2 is ok.

Case Required (3) with file that is an image but bigger than max_size.
i receive this error **Image is not a valid uploaded file.**
Case 3 is **not** ok.
Here it should tell me **Image is too large of a file.**

__________________________________________
However. if i have This other Rule set

      $Rules['image'] = ['label' => 'Image', 'rules'=>'max_size[image.2048]'];

Case Max Size with empty input
i receive this error **Image is too large of a file.**
Case Max Size is **not** ok.
It shouldn't give any error.

**CodeIgniter 4 version** (This works the same as the 4.0.3 also)
Latest Development Version
 - PHP version 7.3.14

**Comment by crustamet** [comment]
So i was looking inside the code of the FileRules my dudes. I found these important lines that interfere.

	public function uploaded(string $blank = null, string $name, array $data): bool
	{
		$file = $this->request->getFile($name);

		if (is_null($file))
		{
			return false;
		}

		if (ENVIRONMENT === 'testing')
		{
			return $file->getError() === 0;
		}

		return $file->isValid();
	}

This function executes first if the first rule is uploaded so it returns it is not a valid file because inside there 

	public function isValid(): bool
	{
		return is_uploaded_file($this->path) && $this->error === UPLOAD_ERR_OK;
	}

_______________________________________
So if i remove this rule because is shit

	$Rules['image'] = ['label' => 'Image', 'rules'=>'is_image[image]|max_size[image.2048]'];

Now it remains the Case Max Size problem, if the input is empty i keep getting 
**Image is too large of a file**

After looking into max_size i noticed the params were missing because i put a dot instead of a comma in the rulles like from the example from the documentation so i changed it to the comma.

The validation just not working anymore for the size...
Because size is 0 from the $this->request->getFile('image');

So it does not get into the if with the size checking
**if ($file->getSize() / 1024 > $params[0])**

**Comment by crustamet** [comment]
Someone please change this function from
**system/Validation/FileRules**

	public function max_size(string $blank = null, string $params, array $data): bool
	{
		// Grab the file name off the top of the $params
		// after we split it.
		$params = explode(',', $params);
		$name   = array_shift($params);

		if (! ($files = $this->request->getFileMultiple($name)))
		{
			$files = [$this->request->getFile($name)];
		}
		
		foreach ($files as $file)
		{
			if (is_null($file))
			{
				return false;
			}
			
			if ($file->getError() === UPLOAD_ERR_NO_FILE)
			{
				return true;
			}
			
			if ($file->getSize() / 1024 > $params[0])
			{
				return false;
			}
		}

		return true;
	}


TO 


	public function max_size(string $blank = null, string $params, array $data): bool
	{
		// Grab the file name off the top of the $params
		// after we split it.
		$params = explode(',', $params);
		$name   = array_shift($params);

		if (! ($files = $this->request->getFileMultiple($name)))
		{
			$files = [$this->request->getFile($name)];
		}
		
		foreach ($files as $file)
		{
			if (is_null($file))
			{
				return false;
			}
			
			if ($file->getError() === UPLOAD_ERR_NO_FILE)
			{
				return true;
			}
			
			if ($file->getError() === UPLOAD_ERR_INI_SIZE)
			{
				return false;
			}
		}

		return true;
	}

**Comment by crustamet** [comment]
everything works as expected besides this max_size function, someone should update this please. Because now it works as expected.

     if ($file->getSize() / 1024 > $params[0])
change to

     if ($file->getError() === UPLOAD_ERR_INI_SIZE)

That is it and it will work perfectly.

**Comment by fujael** [comment]
Thank you for locating the problem. I wish they will see the bug and put attention on it.

**Comment by paulbalandan** [comment]
I think instead of replacing the condition, we should add that condition before the actual checking of the filesize. In your case, your parameter size of 2048 coincides with your `upload_max_size` ini directive. So this was checked first.
