### ISSUE TITLE
Bug: Route redirection not working

### ISSUE THREAD

**Issue by MichalPB1** [codeigniter4/CodeIgniter4#3041]
**Describe the bug**
After using 
```
$routes->addRedirect('example', 'profile/dashboard');
```
I get an error 
```
key() expects parameter 1 to be array, string given
```
but if the second param I set as named route then everything is working properly. The problem exists only when the second param is a URI

**CodeIgniter 4 version**
4.0.2

**Affected module(s)**
```
Router/Router.php at line 430
```
I not sure but here I found some changes for this line https://github.com/codeigniter4/CodeIgniter4/pull/2481/files#diff-d2374d65fd714c18dbee9f5adaa8dd6cL488

**Expected behavior, and steps to reproduce if appropriate**
 Redirection working properly for the second param as a URI .

**Context**
 - OS: Ubuntu
 - PHP version 7.3

**Comment by Instrye** [comment]
This problem is because `profile/dashboard` not set in `$routes`. I will fix.

**Comment by MichalPB1** [comment]
@Instrye thx for your answer :) but it not true. That route is already defined and if I change it to route name everything works.

I think that redirect should work even that URI is not defined - you don't think so? We could have a situation that redirection to not existed URI redirect it to the next URI.

**Comment by MichalPB1** [comment]
It's more complicated :) It looks like redirection doesn't work for addresses with / eg `checkout/shoppingCart`, `profile/orders` when route name is defined

Now the redirection works
```
$routes->addRedirect('asdasd', 'checkout/shoppingCart', 301);

$routes->get('shoppingCart', 'CheckoutController::shoppingCart');
```
Now the redirection does not work:
```
$routes->addRedirect('asdasd', 'checkout/shoppingCart', 301);

$routes->get('shoppingCart', 'CheckoutController::shoppingCart', ['as' => 'checkout.shoppingCart']);
```

**Comment by Instrye** [comment]
I just use `$routes->add` to test, This looks bad.

Regarding your second question, I think you are right, I have made a change

**Comment by Instrye** [comment]
> It's more complicated :) It looks like redirection doesn't work for addresses with / eg `checkout/shoppingCart`, `profile/orders` when route name is defined
> 
> Now the redirection works
> 
> ```
> $routes->addRedirect('asdasd', 'checkout/shoppingCart', 301);
> 
> $routes->get('shoppingCart', 'CheckoutController::shoppingCart');
> ```
> 
> Now the redirection does not work:
> 
> ```
> $routes->addRedirect('asdasd', 'checkout/shoppingCart', 301);
> 
> $routes->get('shoppingCart', 'CheckoutController::shoppingCart', ['as' => 'checkout.shoppingCart']);
> ```

This problem is because `addRediret` after setRoutes, you can run
```
$routes->get('shoppingCart', 'CheckoutController::shoppingCart');
$routes->addRedirect('asdasd', 'checkout/shoppingCart', 301);
```
I think this is the correct order

**Comment by MichalPB1** [comment]
You're right. After changing the routes order is a bit better but still, there are few bugs(?):
- cannot redirect to `checkout/shoppingCart` if that route has set the name. It a forcing for us using `checkout.shoppingCart` route name - it's not practising if we manage redirection from eg database
- cannot redirect to another redirect
- setting redirection code is not working, always get 307 despite the fact that I set 301
- I think that we should be able to redirect the existing route in the system to another. For example, I could change the `login` to `register` - it's an often practice if we have a login and register form on one view

or I am still doing something a wrong way?

**Comment by Instrye** [comment]
> You're right. After changing the routes order is a bit better but still, there are few bugs(?):
> 
> * cannot redirect to `checkout/shoppingCart` if that route has set the name. It a forcing for us using `checkout.shoppingCart` route name - this is not practical if we manage redirection from eg database
> * cannot redirect to another redirect
> * setting redirection code is not working, always get 307 despite the fact that I set 301
> * I think that we should be able to redirect the existing route in the system to another. For example, I could change the `login` to `register` - it's an often practice if we have a login and register form on one view
> 
> or I am still doing something a wrong way?

I think, These problems already processed

**Comment by MichalPB1** [comment]
Ok, I tested your code from PR and:

1. Yes, that works :)
2. Yes, that works :)
3. I found in `HTTP/Response.php` at line `784` that response code is overridden for a method other than `refresh`, but that method is forced as `auto` in `Codeigniter.php` at line `315` - is it a correct?
4. I have a problem with redirect `login` to `register`. It looks like the `URL === route name` is a problem and we are redirection to `http://localhost:8082/\App\Controllers\AuthController::login`
```
$routes->add('login', 'AuthController::login', ['as' => 'login']);
```

**Comment by MichalPB1** [comment]
I have the same error as in point 4 when I try to visit (not redirect) a `/login` page

**Comment by Instrye** [comment]
> Ok, I tested your code from PR and:
> 
> 1. Yes, that works :)
> 2. Yes, that works :)
> 3. I found in `HTTP/Response.php` at line `784` that response code is overridden for a method other than `refresh`, but that method is forced as `auto` in `Codeigniter.php` at line `315` - is it a correct?
> 4. I have a problem with redirect `login` to `register`. It looks like the `URL === route name` is a problem and we are redirection to `http://localhost:8082/\App\Controllers\AuthController::login`
> 
> ```
> $routes->add('login', 'AuthController::login', ['as' => 'login']);
> ```

>The first parameter is the URI pattern for the old route. The second parameter is either the new URI to redirect to, or the name of a named route. 

So, Second Parameter is URI OR named, Class::name not support

Another problem is not what I am good at, But code annotate seems to give a reason, You can see : https://en.wikipedia.org/wiki/Post/Redirect/Get

**Comment by MichalPB1** [comment]
> So, Second Parameter is URI OR named, Class::name not support

I know that `Class::name` is not supported. The example was not a redirection but route definition so

1. Define a route URI the same as a the route name 

```
$routes->add('login', 'AuthController::login', ['as' => 'login']);
```

2. Add a redirection from eg `login` to another url eg `register`

```
$routes->addRedirect('login', 'register', 301);
```
3. You are redirected to `http://localhost:8082/\App\Controllers\AuthController::login` wchich is a wrong URI

That problem is only when the URI is the same as the route name

> Another problem is not what I am good at, But code annotate seems to give a reason, You can see : https://en.wikipedia.org/wiki/Post/Redirect/Get

Yes, I saw that. But I not able to create a `301` redirection via `$routes->addRedirect`? So how can I do it?

**Comment by Instrye** [comment]
You first problem I can't recurrent.
In my test. If:
```
$routes->addRedirect('login', 'register');
$routes->add('login', 'AuthController::login', ['as' => 'login']);
```
Location: http://example.com/register
View: Controller or its method is not found: \App\Controllers\Register::index
If:
```
$routes->add('login', 'AuthController::login', ['as' => 'login']);
$routes->addRedirect('login', 'register', 302);
```
Location: http://localhost/login
View: Controller or its method is not found: \App\Controllers\AuthController::login

**Comment by MichalPB1** [comment]
@Instrye  forgive me, I gave you wrong code :/

There should be a `get` method not an `add` method

```
$routes->get('login', 'AuthController::login', ['as' => 'login']);
$routes->get('register', 'AuthController::register', ['as' => 'register']);
$routes->addRedirect('login', 'register');
```
or

```
$routes->addRedirect('login', 'register');
$routes->get('login', 'AuthController::login', ['as' => 'login']);
$routes->get('register', 'AuthController::register', ['as' => 'register']);
```

We are redirected to location `\App\Controllers\AuthController::login`

**Comment by Instrye** [comment]
> 
> 
> @Instrye forgive me, I gave you wrong code :/
> 
> There should be a `get` method not an `add` method
> 
> ```
> $routes->get('login', 'AuthController::login', ['as' => 'login']);
> $routes->get('register', 'AuthController::register', ['as' => 'register']);
> $routes->addRedirect('login', 'register');
> ```
> 
> or
> 
> ```
> $routes->addRedirect('login', 'register');
> $routes->get('login', 'AuthController::login', ['as' => 'login']);
> $routes->get('register', 'AuthController::register', ['as' => 'register']);
> ```
> 
> We are redirected to location `\App\Controllers\AuthController::login`

The problem because custom router replace. Router must be only.

**Comment by MichalPB1** [comment]
> The problem because custom router replace. Router must be only.
Sorry, but I don't understand. Can you explain what you mean?

**Comment by Instrye** [comment]
First, you set `login` is `AuthController::login`. Then, you set `login` is redirect to `register`. It was set twice, which caused a conflict.

**Comment by michalsn** [comment]
@Instrye is right.

It seems to me like everything is sorted out already. If not, please feel free to open a new issue.
