### ISSUE TITLE
How to set private properties in CodeIgniter\Database\BaseResult::getCustomResultObject()

### ISSUE THREAD

**Issue by ChoiBU** [codeigniter4/CodeIgniter4#3051]
CodeIgniter\Database\BaseResult::getCustomResultObject(string $className)
In this function directly access member properties and assign values
like this
`$this->customResultObject[$className][$i]->$key = $value;`
So, can't set private properties.
But. How to use 'setter' or 'constructor arguments'?

**Comment by michalsn** [comment]
This is more like a support question so in the future please post questions on our forum.

Well... obviously constructor arguments are not supported, but you can handle setters via magic `__set()` method. Anyway, I think you should check the `Entity` class feature. It will solve something around 99% of your problems: https://codeigniter4.github.io/userguide/models/entities.html

**Comment by ChoiBU** [comment]
In this case not entity, std Object.

**Comment by michalsn** [comment]
I don't think that `stdObject` can have private properties, sorry. As I said, you should use custom class or Entity.

**Comment by ChoiBU** [comment]
class CustomClass
{
    private $id;
    public function setId(id) {$thsi->id = id;}
}
In this case

$this->customResultObject[$className][$i]->$key = $value;
It doesn't works;

**Comment by michalsn** [comment]
As I mentioned before - use magic `__set()` method. Also, if you have more questions, please ask them on our forum.
```php
public function __set($key, $value)
{
	$method = 'set' . ucfirts($key);

	if (method_exists($this, $method))
	{
		$this->$method($value);
	}
}
```
