### ISSUE TITLE
Link to User Guide on README.md

### ISSUE THREAD

**Issue by dafriend** [codeigniter4/CodeIgniter4#3053]
The CodeIgniter4 repository README uses the URL https://codeigniter4.github.io/userguide/ as the "primary documentation". Is that appropriate? 

Or should it link to the work-in-progress version at https://codeigniter.com/user_guide/index.html instead?

I'll accept having this assigned but need direction.

**Comment by jreklund** [comment]
Currently both are hosting the latest version.

Codeigniter.com had the development branch version for a while, as it contained fairly outdated information and some nasty bug for the documentation itself. Normally Codeigniter.com should not be patched with a development version, as it started popping up question in the forum regarding function that could not be used yet.

If I remember correctly codeigniter.com should (in the future) contain the sable version and after we have got our Github hooks set up. The github hosted version will be automatically built for developers, so we have the latest version available for the development branch.

**Comment by dafriend** [comment]
> Currently both are hosting the latest version.

I see now that the two links in my OP are the same version. However, the two links on the readme are not the same document.  Go to the "General Topics" page of both and you will see the content differs. 

Looking closer at the document at the link advertised as the "current in-progress User Guide"  I see it is significantly behind the current "released" version. It looks to predate the first release.

The documentation is frequently updated often with corrections that need to be available to users on a timely basis. IMO, much more often than framework releases. An "as commits happen" version of the docs is probably more important for end-user devs than it is for framework contributor devs.

**Comment by lonnieezell** [comment]
> The documentation is frequently updated often with corrections that need to be available to users on a timely basis. IMO, much more often than framework releases. An "as commits happen" version of the docs is probably more important for end-user devs than it is for framework contributor devs.

You're probably right. I've asked on the forums and gotten no takers to help build out that functionality to auto-build it. In the meantime, it's [available in every install](https://github.com/codeigniter4/CodeIgniter4/tree/develop/user_guide_src/source) of the project. You don't need to build it to use it, though it's prettier and more convenient that way of course.

**Comment by jreklund** [comment]
That one are way off yes. [GH-pages](https://github.com/codeigniter4/CodeIgniter4/tree/gh-pages) in CodeIgniter4 project haven't been updated. All these are built manually, so I guess the maintainers miss them from time to time.

Yeah, it gets updated from time to time. I have updated around half of the pages myself. Removing incorrect stuff and updated methods that weren't mentioned. At this time the same user guide branch also contains new function that get's added. If we put all new functions in there people will try to use them, and get frustrated on why we it dosen't work.

So we need a stable and a development one. People can of course use the development user guide if they wan't but they need to be aware that everything won't work. After we are done there should be no errors in the stable one, and only new stuff in the development one. But we are not there yet.

You can always help if you wan't. I'm currently on "Controllers and Routing > IncomingRequest Class" and working from there. But I have been too busy for the past month, so haven't done anything.

And for "as commits happen", that's what github actions are for. We are seeking help for this particular thing; https://forum.codeigniter.com/thread-76552.html
Updating the outdated manual automatically. So if you have time, you can help by fixing it.
