### ISSUE TITLE
Bug: Documentation news app project

### ISSUE THREAD

**Issue by tobecci** [codeigniter4/CodeIgniter4#3054]
**Describe the bug**
the news/slug page in the documentation project fails to load

**CodeIgniter 4 version**
4.0.3

**Affected module(s)**
the overview view

**Expected behavior, and steps to reproduce if appropriate**
when you visit the news page it loads the overview view listing the news items in the database along with a link redirecting to `News::view/$1` route which displays the single news item.
but it does not show the page.
the reason lies in the view
```html
 <p><a href="/news/<?= esc($news_item['slug'], 'url'); ?>">View article</a></p>
```
should instead be 
```html
 <p><a href="news/<?= esc($news_item['slug'], 'url'); ?>">View article</a></p>
```

**Context**
 - Web server xampp 3.2.4
 - PHP version 7.4.4

**Comment by dafriend** [comment]
I cannot reproduce the problem. In fact, the correct news/slug page loads with or without your proposed fix.

**Comment by jreklund** [comment]
That example are based off a real domain. It won't work in subfolders.
http://localhost/codeigniter4/public/news

You should create a virtual host named e.g. example.com
http://example.com/news

Or using `php spark serve` as stated in [Getting Up and Running](https://codeigniter.com/user_guide/tutorial/index.html#getting-up-and-running).
http://localhost:8080/news

**Comment by tobecci** [comment]
okay, i tried it and it's working on localhost:8080 served by spark

**Comment by tobecci** [comment]
> I cannot reproduce the problem. In fact, the correct news/slug page loads with or without your proposed fix.

are you serving the project on xampp?
