### ISSUE TITLE
line 374 in system/Entity.php json_encode add JSON_UNESCAPED_UNICODE

### ISSUE THREAD

**Issue by itartpro** [codeigniter4/CodeIgniter4#3059]
**Describe the bug**
When saving stuff to database, using $entity->property, with property being cast as json-array it does a poor job of saving for russian, and I suspect other languages. Is it possible to set line 374 in system/Entity.php to this: json_encode($value, JSON_UNESCAPED_UNICODE);

Add JSON_UNESCAPED_UNICODE to handle different languages? Otherwise it takes a lot of space in database when each letter is represented as \u043d (for example)

**CodeIgniter 4 version**
4.0.3

**Affected module(s)**
CodeIgniter\Entity

**Comment by lonnieezell** [comment]
I think this makes sense. Will do.
