### ISSUE TITLE
Bug: Fatal error: Cannot declare class CodeIgniter\Exceptions\PageNotFoundException

### ISSUE THREAD

**Issue by enix-app** [codeigniter4/CodeIgniter4#3067]
**Describe the bug**

This is not intentional,

I added route:

```php
$routes->get('/test/(:num)', 'Home::index');
```

I tried in bar url:

``http://localhost:8080/test/([0-9]+)``

``http://localhost:8080//``

``http://localhost:8080/test/abc``

Show me an error:

```
Fatal error: Cannot declare class CodeIgniter\Exceptions\PageNotFoundException, because the name is already in use in D:\codeigniter4\CodeIgniter4-test\system\Exceptions\PageNotFoundException.php on line 3

Fatal error: Cannot declare class CodeIgniter\Exceptions\PageNotFoundException, because the name is already in use in D:\codeigniter4\CodeIgniter4-test\system\Exceptions\PageNotFoundException.php on line 3
```
**CodeIgniter 4 version**
development, last commit #3062 , fresh install

**Affected module(s)**
Exception class, Router class

**Context**
 - Environment: development
 - OS: Win10
 - Built-in PHP Web server, Apache2.4
 - PHP 7.3

**Comment by samsonasik** [comment]
@enix-app Yes, it seems a new bug in development branch . @lonnieezell @MGatner could you looking at it? Probably caused after autoload PR #3052 /cc @mostafakhudair

**Comment by MGatner** [comment]
I haven't noticed it but I will see if I can reproduce tomorrow when I update a project with that new Autoload.

**Comment by MGatner** [comment]
UPDATE: I've been able to replicate this. Still not sure as to the root cause.

**Comment by MGatner** [comment]
The bug was introduced with #2958. Actual underlying issue TBD

**Comment by MGatner** [comment]
**system/Debug/Exceptions.php**, Line 308:

`include $file;`

**Comment by MGatner** [comment]
The problem is actually a collision with `$file` caused by `extract($vars);`. Fix incoming.
