### ISSUE TITLE
utf-8 slug character doesn't work in url

### ISSUE THREAD

**Issue by perspolise** [codeigniter4/CodeIgniter4#3089]
I add persian character to uri like this: 

`http://ci4.local:8080/تماس-با-ما`

in routes.php :

`$routes->get('/(:any)', 'Home::page/$1');`

but i see this error:

```
Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.
Error 404
ci4.local
Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.2 

````

**Comment by lonnieezell** [comment]
While I'm not 100% sure what's causing this particular error to show up, be aware that the HTTP spec requires characters other than US_ASCII to be url-encoded. That means that those characters are, unfortunately, disallowed by the spec.

**Comment by michalsn** [comment]
I think that non-ASCII characters are automatically translated to ASCII by the server. But it's only my guess (I haven't checked).

Anyway, looking at the error I would say that this is not a CodeIgniter problem. Probably `.htaccess`? I would try to call `http://ci4.local:8080/index.php/تماس-با-ما` to check if this will work.

**Comment by lonnieezell** [comment]
I cannot recreate using the latest CI develop branch and the built-in server. 

I added the route:

```$routes->get('/(:any)', 'Home::page/$1');```

and modified the default controller by adding this method: 

```
public function page($page = null)
{
	dd($page);
}
```
Visiting the URL `localhost:8080/تماس-با-ما` works just fine for me. Likely a server issue. 

If you need additional help please visit the forums and ask there.

**Comment by perspolise** [comment]
@lonnieezell I check all persian character. codeigniter `.htaccess` have a problem with ‍`م‍` character. I change:

`RewriteRule ^(.*)$ index.php/$1 [L]`

to 

`RewriteRule ^([\s\S]*)$ index.php/$1 [L,NC,QSA]` 

and my problem with `م` character is fixed now.

**Comment by lonnieezell** [comment]
Good find. I've included that in the latest code.
