### ISSUE TITLE
Bag pars array to xml 

### ISSUE THREAD

**Issue by demortx** [codeigniter4/CodeIgniter4#3092]
https://github.com/codeigniter4/CodeIgniter4/blob/f7dfb404fdd7bf7360fb4cab7f661527149dd157/system/Format/XMLFormatter.php#L107

Hot Fix
if (!is_numeric($key)) {
    $output->addChild("$key", htmlspecialchars("$value"));
} else {
    $output->addChild("item{$key}", htmlspecialchars("$value"));
}

before
<ORDER_QTY><0>1</0></ORDER_QTY>

after
<ORDER_QTY>< item0>1< /item0 ></ORDER_QTY>

**Comment by michalsn** [comment]
Good catch! I suppose not many people use XML format anymore because otherwise, this problem would come sooner.
