### ISSUE TITLE
Call to undefined function CodeIgniter\Debug\current_url()

### ISSUE THREAD

**Issue by Bezzoom** [codeigniter4/CodeIgniter4#3106]
Hi, Team!

I was getting this error on three different Linux machines. At the same time on the machine under Windows with IIS everything works normally.

I tried adding a URL helper to autoload, but it doesn't help and your manual says that this helper loads automatically.

can you tell me where to pay my attention

Thanks!

**Comment by Bezzoom** [comment]
Some additional information

on IIS, the domain name is something like mysuperdomain
but on linux machines my.super.domain.com

maybe it matters

the baseurl variable is equal to http://my.super.domain.com

**Comment by Instrye** [comment]
Show you code. We need more info.

**Comment by Bezzoom** [comment]
Function call not in my code. 

This CI error:

`108      * @param \CodeIgniter\HTTP\ResponseInterface $response
109      *
110      * @return string JSON encoded data
111      */
112     public function run(float $startTime, float $totalTime, RequestInterface $request, ResponseInterface $response): string
113     {
114         // Data items used within the view.
115         $data['url']             = current_url();
116         $data['method']          = $request->getMethod(true);
117         $data['isAJAX']          = $request->isAJAX();
118         $data['startTime']       = $startTime;
119         $data['totalTime']       = $totalTime * 1000;
120         $data['totalMemory']     = number_format((memory_get_peak_usage()) / 1024 / 1024, 3);
121         $data['segmentDuration'] = $this->roundTo($data['totalTime'] / 7);
122         $data['segmentCount']    = (int) ceil($data['totalTime'] / $data['segmentDuration']);`

**Comment by Bezzoom** [comment]
Full Backtrace:

SYSTEMPATH/Debug/Toolbar.php : 356   —  CodeIgniter\Debug\Toolbar->run ( arguments )
```
349 
350             $toolbar = Services::toolbar(config(Toolbar::class));
351             $stats   = $app->getPerformanceStats();
352             $data    = $toolbar->run(
353                     $stats['startTime'],
354                     $stats['totalTime'],
355                     $request,
356                     $response
357             );
358 
359             helper('filesystem');
360 
361             // Updated to time() so we can get history
362             $time = time();
363 
```
SYSTEMPATH/Filters/DebugToolbar.php : 75   —  CodeIgniter\Debug\Toolbar->prepare ( arguments )
```
68      * @param RequestInterface|\CodeIgniter\HTTP\IncomingRequest $request
69      * @param ResponseInterface|\CodeIgniter\HTTP\Response       $response
70      *
71      * @return void
72      */
73     public function after(RequestInterface $request, ResponseInterface $response)
74     {
75         Services::toolbar()->prepare($request, $response);
76     }
77 
78     //--------------------------------------------------------------------
79 }
80 
```
SYSTEMPATH/Filters/Filters.php : 199   —  CodeIgniter\Filters\DebugToolbar->after ( arguments )
```
192                         continue;
193                     }
194 
195                     return $result;
196                 }
197                 elseif ($position === 'after')
198                 {
199                     $result = $class->after($this->request, $this->response);
200 
201                     if ($result instanceof ResponseInterface)
202                     {
203                         $this->response = $result;
204                         continue;
205                     }
206                 }
```
SYSTEMPATH/CodeIgniter.php : 418   —  CodeIgniter\Filters\Filters->run ( arguments )
```
411         $this->gatherOutput($cacheConfig, $returned);
412 
413         // Never run filters when running through Spark cli
414         if (! defined('SPARKED'))
415         {
416             $filters->setResponse($this->response);
417             // Run "after" filters
418             $response = $filters->run($uri, 'after');
419         }
420         else
421         {
422             $response = $this->response;
423 
424             // Set response code for CLI command failures
425             if (is_numeric($returned) || $returned === false)
```
SYSTEMPATH/CodeIgniter.php : 308   —  CodeIgniter\CodeIgniter->handleRequest ( arguments )
```
301 
302             $this->response->pretend($this->useSafeOutput)->send();
303             $this->callExit(EXIT_SUCCESS);
304         }
305 
306         try
307         {
308             return $this->handleRequest($routes, $cacheConfig, $returnResponse);
309         }
310         catch (RedirectException $e)
311         {
312             $logger = Services::logger();
313             $logger->info('REDIRECTED ROUTE at ' . $e->getMessage());
314 
315             // If the route is a 'redirect' route, it throws
```
FCPATH/index.php : 46   —  CodeIgniter\CodeIgniter->run ()
```
39 /*
40  *---------------------------------------------------------------
41  * LAUNCH THE APPLICATION
42  *---------------------------------------------------------------
43  * Now that everything is setup, it's time to actually fire
44  * up the engines and make this app do its thang.
45  */
46 $app->run();
47 
```
