### ISSUE TITLE
Bug: AH01075: Error dispatching request on Basic CI4

### ISSUE THREAD

**Issue by isantolin** [codeigniter4/CodeIgniter4#3110]
**Describe the bug**
The basic Codeigniter 4 without any configuration and a Server with default configuration (That works with Codeigniter 3) Cant load and shows 503 error

**CodeIgniter 4 version**
v4.0.3

**Affected module(s)**
Codeigniter

**Expected behavior, and steps to reproduce if appropriate**
- Put Basic Codeigniter on /Apache directory
- point DocumentRoot to /Apache/public
- Point the browser to: http://localhost (Delays more than 10 seconds to load) and...
- The following error will appear
```
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

```
[Tue Jun 16 21:51:05.886556 2020] [proxy_fcgi:error] [pid 937802:tid 140579791218432] [client ::1:34246] AH01067: Failed to read FastCGI header
[Tue Jun 16 21:51:05.886598 2020] [proxy_fcgi:error] [pid 937802:tid 140579791218432] (104)Connection reset by peer: [client ::1:34246] AH01075: Error dispatching request to :
[Tue Jun 16 21:53:09.284478 2020] [proxy_fcgi:error] [pid 937802:tid 140579681842944] [client ::1:34798] AH01067: Failed to read FastCGI header
[Tue Jun 16 21:53:09.284563 2020] [proxy_fcgi:error] [pid 937802:tid 140579681842944] (104)Connection reset by peer: [client ::1:34798] AH01075: Error dispatching request to : 
```

**Context**
 - OS: Fedora 32
 - Web server: Apache 2.4.43
 - PHP-FPM: 7.4.7

**Comment by paulbalandan** [comment]
Is this still an issue?

If yes, have you tried giving permissions to php to write in the writable folder?

**Comment by isantolin** [comment]
@paulbalandan Now showing :

( ! ) Fatal error: Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /var/www/html/project-root/vendor/codeigniter4/framework/system/Config/BaseService.php on line 195

(Same configuration)

**Comment by paulbalandan** [comment]
Have you tried upgrading to the latest version?

**Comment by isantolin** [comment]
> Have you tried upgrading to the latest version?

yes, i am using the last version

**Comment by paulbalandan** [comment]
> @paulbalandan Now showing :
> 
> ( ! ) Fatal error: Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /var/www/html/project-root/vendor/codeigniter4/framework/system/Config/BaseService.php on line 195
> 
> (Same configuration)

This is a problem with the xdebug extension. It seems BaseService has entered infinite recursion. Can you post a screenshot of the error page?

**Comment by isantolin** [comment]
@paulbalandan 
![image](https://user-images.githubusercontent.com/264640/91643644-95622b00-ea0b-11ea-8b3a-e7192a3a06bd.png)

**Comment by michalsn** [comment]
Please, edit your `php.ini` file and increase value for `xdebug.max_nesting_level`

**Comment by isantolin** [comment]
@michalsn Xdebug not installed


(base) [root@airwave7 php.d]# php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
json
libxml
mbstring
mcrypt
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
uopz
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by paulbalandan** [comment]
How is that possible? That error page is produced by xdebug

**Comment by paulbalandan** [comment]
@isantolin can you try changing `BaseService` on lines 191 to 201 and changing to the following. See diff:
```diff
        public static function __callStatic(string $name, array $arguments)
	{
		$name = strtolower($name);

-		if (method_exists(Services::class, $name))
+		if (method_exists(static::class, $name))
		{
-			return Services::$name(...$arguments);
+			return static::$name(...$arguments);
		}

		return static::discoverServices($name, $arguments);
	}
```

Please see if that solves your issue?

**Comment by isantolin** [comment]
@paulbalandan Not yet

![image](https://user-images.githubusercontent.com/264640/91660872-c21b4e80-eaae-11ea-91f8-8862a829d9e9.png)

**Comment by isantolin** [comment]
![image](https://user-images.githubusercontent.com/264640/91661039-ec214080-eaaf-11ea-84e1-d6afc2a22682.png)

**Comment by paulbalandan** [comment]
> @paulbalandan Not yet
> 
> ![image](https://user-images.githubusercontent.com/264640/91660872-c21b4e80-eaae-11ea-91f8-8862a829d9e9.png)

At least that solves the function nesting issue. Can you try using the latest develop branch? Line 139 on system/bootstrap.php on mine is a whitespace only.

**Comment by isantolin** [comment]
@paulbalandan I tryied with the development version. Old error returns

![image](https://user-images.githubusercontent.com/264640/91665861-fb63b680-eace-11ea-9d4a-4790c5584ce1.png)

**Comment by paulbalandan** [comment]
Yes that is expected because it will overwrite your changes. Trying changing it again to use `static`.

**Comment by isantolin** [comment]
@paulbalandan Yes, i tried 

![image](https://user-images.githubusercontent.com/264640/91666073-74174280-ead0-11ea-8536-a0ddf7cbf544.png)

**Comment by paulbalandan** [comment]
@isantolin i'm sorry i think this is a bug in PHP already. `__callStatic` should only be called when the static method is not present in a class. In your case, however, `__callStatic` is ALWAYS called even though the static method is existing in the class. `autoloader` and `discoverServices` are, as you can see, defined static methods, so calling those should invoke them directly, not going through `__callStatic`. This causes the infinite recursion error you are facing.

Have you tried in php other than php-fpm?

**Comment by isantolin** [comment]
@paulbalandan no, because all my server infraestructure is based in php-fpm and CI4 needs to be compatible.
Exists any workaround to deal with this bug?

**Comment by paulbalandan** [comment]
I'm sorry I'm not well versed with php-fpm. Can you try opening a bug report to the PHP core?

**Comment by paulbalandan** [comment]
Since this is not a framework issue, I'm closing this.
