### ISSUE TITLE
Bug: Validation rules max_size

### ISSUE THREAD

**Issue by mrardiyansyah** [codeigniter4/CodeIgniter4#3122]
To be honest when I use this rule it works as usual. But when adding this query builder update rules it always raises the error message that has been created.

`if ($this->request->getMethod() == 'post') {
            $rules = [
                'name' => 'required|alpha_space',
                'image' => [
                    'label' => 'Image',
                    'rules' => 'max_size[image,2048]|mime_in[image,image/gif,image/jpeg,image/png]',
                    'errors' => [
                        'max_size' => 'Allowed maximum size is 2MB', //Always display this error message 
                         even though the uploaded file is 1KB
                        'mime_in' => 'The Image type is not allowed. Allowed types : gif, jpeg, png'

                    ],
                ]
            ];

            if (!$this->validate($rules)) {
                $data['validation'] = $this->validator;
            } else {
                $newData = ['a'=>1]
                $model->update('1',$newData);
;`

**Comment by paulbalandan** [comment]
Are you using the latest develop branch?

**Comment by michalsn** [comment]
I wasn't able to reproduce it, sorry. It's probably something with your code logic? You can also check if you have any rules set in your model.
