### ISSUE TITLE
Execute bootstrapEnvironment() & detectEnvironment() before Services::exceptions() 

### ISSUE THREAD

**Issue by arma7x** [codeigniter4/CodeIgniter4#3138]
I did override current Services::exceptions() and my new Services::exceptions() need to access specific value of CONSTANT loaded from custom boot files based upon the current environment.
Posibble to update [Codeigniter.php](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/CodeIgniter.php) by moving [Line 190](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/CodeIgniter.php#L190) below [Line 194](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/CodeIgniter.php#L194)

**Comment by arma7x** [comment]
missmatch label, Refactor

**Comment by michalsn** [comment]
I think it shouldn't cause problems. And your reasoning to have access to the environment variables make sense to me.

You should try to make a PR (if you want to this change happen sooner rather than later 😉).
