### ISSUE TITLE
Bug: CodeIgniter 4.0.3 Controller will not display pdf files in browser

### ISSUE THREAD

**Issue by InsiteFX** [codeigniter4/CodeIgniter4#3144]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
Forum reference: [https://forum.codeigniter.com/thread-76768-post-377020.html#pid377020](url)

The controller will not display pdf files in the wen browser using php headers.
`		// Store the file name into variable
		// The location of the PDF file on the server
		$file = WRITEPATH . 'pdf/CodeIgniterAjaxPagination.pdf';
		$fileName = 'CodeIgniterAjaxPagination.pdf';
		
		// Header content type
		header('Content-type: application/pdf');
		header('Content-Disposition: inline; filename="' . $fileName . '"');
		header('Content-Transfer-Encoding: binary');
		header('Content-Length: ' . filesize($file));
		header('Accept-Ranges: bytes');

		// Read the file
		readfile($file);`

Displays garbage characters.

**CodeIgniter 4 version**
Which version (and branch, if applicable) the bug is in.

CodeIgniter 4.0.3 Dev

**Affected module(s)**
Which package or class is the bug in, if known.

Something to do with the Controller were the code is ran from.

**Expected behavior, and steps to reproduce if appropriate**
A clear and concise description of what you expected to happen,
and how you got there.

It should have displayed the pdf file in the web browser chrome newest version.
Works file using straight php code script and loading form the folder directly into chrome.
.  
Feel free to include a text/log extract, but use a pastebin facility for any
screenshots you deem necessary.

**Context**
 - OS: [e.g. Windows 10 x64]
 - Web server [e.g. Apache 2.4.3]
 - PHP version [e.g. 7.4.7]

**Comment by michalsn** [comment]
We should use the Response class to set headers.
```php
$this->response->setHeader('Content-Type', 'application/pdf');
```

**Comment by jorge-koki** [comment]
$content = file_get_contents($ruta);
        header('Content-Type: application/pdf');
        header('Content-Length: ' . strlen($content));
        header('Content-Disposition: inline; filename="' . $file . '"');
        header('Cache-Control: private, max-age=0, must-revalidate');
        header('Pragma: public');
        ini_set('zlib.output_compression', '0');
        die($content);

**Comment by InsiteFX** [comment]
As mentioned above use:

`$this->response->setHeader('Content-Type', 'application/pdf');`
