### ISSUE TITLE
Router RegEx not working. 

### ISSUE THREAD

**Issue by mmrtonmoybd** [codeigniter4/CodeIgniter4#3169]
RegEx not working in router. I use this
 [a-z0-9\x{0980}-\x{09ff}-]+$/u 
RegEx but Codeigniter throw a error out over of range system/Router/Router.php on line 425

**Comment by michalsn** [comment]
Sorry, but we don't allow to set regex flags or delimiters. But I guess we should support `u` by default.

**Comment by mmrtonmoybd** [comment]
> Sorry, but we don't allow to set regex flags or delimiters. But I guess we should support `u` by default.

Thank you now it's working and router RegEx now support Unicode.

**Comment by michalsn** [comment]
I'm reopening this issue since it's not resolved yet.

@mmrtonmoybd it would be great if you could check #3172 and see if it works as it should.

**Comment by mmrtonmoybd** [comment]
Unicode router not working with place holder.
Like this :
$routes->addPlaceholder(':category', '([a-z\x{0980}-\x{09ff}-]+)');
$routes->addPlaceholder(':pslug', '([a-zA-Z0-9\x{0980}-\x{09ff}-]+)');

$routes->add('(:category)/(:pslug)', 'Single::index/$1/$2');

But it is working on segment like this

$routes->add('([a-z\x{0980}-\x{09ff}-]+)/([a-zA-Z0-9\x{0980}-\x{09ff}-]+)', 'Single::index/$1/$2');

**Comment by michalsn** [comment]
I just checked it and it works fine. I added a test for this to make sure.

I believe your definition for placeholder is incorrect. Try this one:

```php
$routes->addPlaceholder(':category', '[a-z\x{0980}-\x{09ff}-]+');
$routes->addPlaceholder(':pslug', '[a-zA-Z0-9\x{0980}-\x{09ff}-]+');

$routes->add('(:category)/(:pslug)', 'Single::index/$1/$2');
```
