### ISSUE TITLE
Add this relationship in model.

### ISSUE THREAD

**Issue by mmrtonmoybd** [codeigniter4/CodeIgniter4#3170]
Please add this relationship in model. I am working with laravel more than 2 years, but now I am learning codeigniter. In codeigniter I was depressed to that there are no relationship in model orm.
Please add this relationship in codeigniter model like Laravel

1. One To One
2. One To Many
3. One To Many (Inverse)
4. Many To Many
5.  Has One Through
6. Has Many Through

**Comment by truelineinfotech** [comment]
you should take look [( https://github.com/hlohrenz/CI4-Relationship-Query-Builder)]

**Comment by mmrtonmoybd** [comment]
> 
> 
> you should take look https://github.com/hlohrenz/CI4-Relationship-Query-Builder

It is third-party Relationship query builder. CodeIgniter did not provide it internally.

**Comment by lonnieezell** [comment]
Feature requests should be made on the forums in the future please. GitHub is for bug tracking.

However, CodeIgniter has a long history of not including an ORM and there are not currently any plans for an official one. You can always bring in a third-party ORM/database layer, though. IIRC, you can even use Eloquent, unless that's the Blade engine I'm remembering can easily be used outside?
