### ISSUE TITLE
Cannot extend core HTTPException class

### ISSUE THREAD

**Issue by arnisjuraga** [codeigniter4/CodeIgniter4#3178]
What I am trying to do is to extend core `HTTPException` class because Facebook API on HTTP requests replies with non-standart HTTP response codes and Codeigniter throws Exception on those cases.
So, I wanted to extend HTTPException class to add additional non-standart HTTP response codes (like `190` from https://developers.facebook.com/docs/graph-api/using-graph-api/error-handling/#errorcodes )

The documentation states that, e.g.:

> If you need to use a constructor in your class make sure you extend the parent constructor:

https://codeigniter4.github.io/CodeIgniter4/extending/core_classes.html#extending-core-classes

My `app/Config/Autload.php` config line for additional class loading:
```php
$classmap = [
            'CodeIgniter\HTTP\Exceptions\HTTPException' => APPPATH . '/HTTPException.php',
        ];
```

And the class file itself located under `app/HTTPException.php`:
```php
<?php

use CodeIgniter\HTTP\Exceptions\HTTPException;

class HTTPException extends \CodeIgniter\HTTP\Exceptions\HTTPException
{
    public function __construct()
    {
        dd("Loaded!"); 
    }
}
```

My example looks like this, but it always throws some error that 
`Fatal error: Cannot declare class HTTPException because the name is already in use in /app/HTTPException.php on line 7`

***Similar questions:***

And, also, it would be enough if those codes would be possible to "ignore"?
Like problem described here: https://forum.codeigniter.com/thread-75069.html 
And the extension of core classes also discussed here: #358

**Comment by paulbalandan** [comment]
The name of the child class clashes with the parent class. So, perhaps, you can change the name of the core HTTPException in your `use` statement.
```php
use CodeIgniter\HTTP\Exceptions\HTTPException as BaseHTTPException;

class HTTPException extends BaseHTTPException
{

}
```

**Comment by michalsn** [comment]
Please use our forum for support questions. This place is for bug reporting only.
