### ISSUE TITLE
Testing withSession() generates an error.

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#3190]
Hi! I am testing a method of my controller which displays a json only if an established session is found.

To perform the test I am using the following code since the path can be accessed only if the `logged_in` variable exists in session

```php
public function testERP(){
        $values = [
            'logged_in' => TRUE,
            'username' => 'foo'
        ];

        $response = $this->withSession($values)->get('/');
        
        $response->assertSessionHas('logged_in',TRUE);
        print_r($response->getJSON());
        $response->assertStatus(200);
}
```

In my class it's like the following:
```php
use CodeIgniter\API\ResponseTrait;
class Dash extends BaseController
{
    use ResponseTrait;
    public function index()
    {
        $session = \Config\Services::session();

        if($session->logged_in == TRUE){

            $data = [
                [
                    'id' => 1,
                    'username' => 'foo1',
                ],
                [
                    'id' => 2,
                    'username' => 'foo2',
                ],
            ];
            return $this->respond($data,200);
        }else{
            throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();
        }
    }
}
```
![imagen](https://user-images.githubusercontent.com/4117596/86197737-a41b8700-bb1b-11ea-8403-c9d9ceff0b68.png)

The test only works correctly if I don't use the logged_in comparison but it is not correct because there must be a session to access the resource.

regards!

**Comment by MGatner** [comment]
@luispastendev The problem is that your test case has already defined the session parameters yet your session handler is trying to modify the parameters. I recommend using `MockSession` during testing, especially Feature Tests. I actually just sent over a PR to mock the session by default (https://github.com/codeigniter4/CodeIgniter4/pull/3193) but fi you don't want to wait for that you could borrow some of the code to do it yourself.

**Comment by luispastendev** [comment]
Hi @MGatner use your PR code and I managed to circumvent the sessions to test. I thank you very much for your help :)

**Comment by MGatner** [comment]
Glad to hear it! Is this issue closed then?
