### ISSUE TITLE
Bug: no Filter arguments passed

### ISSUE THREAD

**Issue by tangix** [codeigniter4/CodeIgniter4#3216]
**Describe the bug**
When running Filters, before() and after() doesn't get arguments passed to them. This is contrary to the information in the docs:
https://codeigniter.com/user_guide/incoming/routing.html#applying-filters
Changing the method signature is not possible since this would break FilterInterface validation.

**CodeIgniter 4 version**
4.0.3

**Affected module(s)**
\CodeIgniter\Filters\Filter
\CodeIgniter\Filters\FilterInterface

**Expected behavior, and steps to reproduce if appropriate**
I should be able to get the arguments from the route into my Filter. With a route specified as:
`$routes->add('users/delete/(:segment)', 'AdminController::index', ['filter' => 'admin-auth:dual,noreturn']);`
I'd expect to get access to `['dual', 'noreturn']` in my Filter implementation.

**Context**
- PHP 7.3.19

**Comment by hermitprime** [comment]
Same issue here. The user guide does not give any method to retrieve the parameter. So the bug is fixed?

**Comment by tangix** [comment]
> Same issue here. The user guide does not give any method to retrieve the parameter on the filters. So the bug is fixed?

To the best of my knowledge there is no easy way to fix this without breaking old code implementing the FilterInterface. My PR created a new interface with the correct function signature and changing the logic in the library to check for the new interface as well as the old. (Unfortunately my PR doesn't pass the tests on github but does locally, so I don't know if the PR will be considered at all.)
The core devs will have to look at this I guess and possibly find a better way forward. Currently I have applied my patch to the framework, but that's not the correct way to do it.

**Comment by tangix** [comment]
Fixed in 4.0.4
