### ISSUE TITLE
Bug: set_checkbox, set_radio not working default true.

### ISSUE THREAD

**Issue by yks118** [codeigniter4/CodeIgniter4#3228]
**Describe the bug**
form_helper.php load and code write set_checkbox('field', 'value', true); return value ''.
not return ' checkbox="checked"'.

**CodeIgniter 4 version**
4.0.3
4.0.2 is work.

**Affected module(s)**
/system/Helpers/form_helper.php

**Expected behavior, and steps to reproduce if appropriate**
/app/Controllers/BaseController.php in form_helper.php load.
view folder write code.
```php
var_dump(set_checkbox('field', 'value', true));
```
return value is ''.
method GET not POST.

**Context**
 - OS: Ubuntu 18.04
 - Web server: nginx/1.19.0
 - PHP version: PHP 7.4.7

**Comment by Mauricevb** [comment]
This bug seems to be returned again? When I write:
 ```var_dump(set_checkbox('field', 'value', true));``` 

It returns:
```'' (length=0)```

I am using CodeIgniter 4.1.1
