### ISSUE TITLE
Can't successfully validate CLI::prompt when field param has periods

### ISSUE THREAD

**Issue by paulbalandan** [codeigniter4/CodeIgniter4#3233]
**Describe the bug**
I am making a CLI command that prompts the user whenever there is a file to be overwritten. In my prompt I just say `File already exists. Overwrite?` and supply the array of options `['y', 'n']`. Now when I am supplying an input, pressing any of `Enter`, `y`, `n` fails validation and say that input is not within the list.

**CodeIgniter 4 version**
dev-develop

**Affected module(s)**
CLI, possibly Validation also

**Expected behavior, and steps to reproduce if appropriate**
1. Create a controller:
```php
use CodeIgniter\CLI\CLI;

class Home extends BaseController
{
    public function index()
    {
        if (!is_cli()) {
            exit('Needs to run on CLI');
        }

        if (CLI::prompt('We are at home. Leave?', ['y', 'n']) == 'y')
        {
            CLI::write('We\'re leaving.');
        }
    }
}
```

2. Run in terminal:
```
php public/index.php home/index
```

3. Fill in the prompt.
4. I suspect the culprit is in how `Validation` runs the process, perhaps in lines 177 or 178. But I'm not sure yet.
5. Temporary fix for this is obviously removing the period but I want to know is this the intended behavior also for prompts?

Cheers!

**Context**
 - OS: Win 10
 - Web server CLI
 - PHP version 7.4.7

**Comment by michalsn** [comment]
It's a bug. We use "prompt text" as a rule field and dot is intended to be there only in purpose to handle arrays. We should replace `.` with something else before using validation class and then replace the text from error message back to use `.` again.

See: https://codeigniter.com/user_guide/libraries/validation.html#validating-keys-that-are-arrays

**Comment by paulbalandan** [comment]
Maybe we can use a `$tempfieldname` to substitute for the prompt text to use in the validation process?

**Comment by michalsn** [comment]
Oh, silly me... We can just use `$label` option and set `$field` as some constant value like "temp".

**Comment by michalsn** [comment]
Hm... wait we can't do that, sorry.

**Comment by paulbalandan** [comment]
What I meant was in line 285, instead of `$field` as `validate`'s first argument, maybe we can use something else. Like "temp" as what you've said. Or "prompt".

**Comment by michalsn** [comment]
Sorry, obviously it's not my day. The label option should work okay.
