### ISSUE TITLE
How to call resource route

### ISSUE THREAD

**Issue by spike-sudo** [codeigniter4/CodeIgniter4#3239]
Please I need help to enable me know how to map the resource route to http request.

 for example am trying to call this url via axios
    
    http://localhost/nmc/public/api/unregisteredpatients?userid=hen11@gmail.com

and i have created the following resource routes to call my api

    //$routes->resource('api/unregisteredpatients/(:any)', 'UnregisteredPatients::show/$1', ['namespace' => 'Api']);
    //$routes->get('api/unregisteredpatients/(:any)', 'UnregisteredPatients::show/$1', ['namespace' => 'Api']);
    $routes->resource('api/unregisteredpatients/(:any)', ['controller' => 'Api/UnregisteredPatients']);

None of these was able to call my api method instead they all called the index() method, whereas I wanted it to call the show($id) method to enable me utilise the $id to fetch data.

    public function show($id = null) {
        .....
    }

Please I need help

**Comment by michalsn** [comment]
Sorry, but we don't answer support questions here. Please post your question in the [forum](https://forum.codeigniter.com/forum-30.html).

**Comment by spike-sudo** [comment]
the username field of the forum will not allow me create an account.. tired of trying different combination of strings but won't accept any. Please can i have an assistance on this thread

**Comment by michalsn** [comment]
I just checked it and I could create a new account without any problems.

**Comment by spike-sudo** [comment]
Thank you so much i was able to register and i found the solution in the forum.
