### ISSUE TITLE
Hint message in tutorial does not correspond to the example code shown

### ISSUE THREAD

**Issue by Connum** [codeigniter4/CodeIgniter4#3242]
**Documentation URL:**
https://codeigniter4.github.io/userguide/tutorial/news_section.html

**Description:**
At the end of the section **Display the news**, there's a note with the following message:
> We are again using using esc() to help prevent XSS attacks. But this time we also passed “url” as a second parameter. That’s because attack patterns are different depending on the context in which the output is used. You can read more about it here.

However, there is no `"url"` parameter in the code example above that note:
```
<h2><?= esc($news['title']); ?></h2>
<?= esc($news['body']); ?>
```

So, either the parameter is missing, or the note is superfluous here.

**Comment by jreklund** [comment]
Hi, this are a duplicate of #2960 and have been fixed in the development branch. I placed it on the wrong code block.
