### ISSUE TITLE
Missing code formatting for migration block in documentation

### ISSUE THREAD

**Issue by arnisjuraga** [codeigniter4/CodeIgniter4#3243]
Missing code formatting for 

```php spark migrate:create [filename]```

block at https://codeigniter4.github.io/userguide/dbmgmt/migration.html#create-a-migration

**Comment by paulbalandan** [comment]
This can be closed. This is fixed in #3244.

https://codeigniter4.github.io/CodeIgniter4/dbmgmt/migration.html#create-a-migration
