### ISSUE TITLE
Bug: Url's not working

### ISSUE THREAD

**Issue by InsiteFX** [codeigniter4/CodeIgniter4#3245]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
Downloaded newest developer version install using my same vhost. setup all config
load index.php goes right to the home page. type in home on bar and get 404 page not found on all links
https://admin.local/ --. works
https://admin.local/home --> 404 error page not found
Does the same thing with all the Myth/Auth links 404 page not found.

So I downloaded the production 4,0,3 version and guess what everything works right out of the box.
with the same setup parameters.

**CodeIgniter 4 version**
Which version (and branch, if applicable) the bug is in.
This developer version this branch

**Affected module(s)**
Which package or class is the bug in, if known.
Seems to be something with the routes or router.

**Expected behavior, and steps to reproduce if appropriate**
A clear and concise description of what you expected to happen,
and how you got there.  
Feel free to include a text/log extract, but use a pastebin facility for any
screenshots you deem necessary.
Expected all the url links to work.
**Context**
 - OS: [e.g. Windows 99]
 - Web server [e.g. Apache 1.2.3]
 - PHP version [e.g. 6.5.4]

**Comment by MGatner** [comment]
Could you share at least the relevant parts of **app/Config/Routes.php** and any changes you have made to **public/.htaccess**?

**Comment by InsiteFX** [comment]
Nothing has been changed in the Routes.php or the ,htaccess file only change is to the app.php config
`#BaseUrl = 'https://admin.local/` and removed index.php from the config.

The released ver 4.0.3 worked right off the developer version will not work at all. Same same changes made to the production framework.

**Comment by michalsn** [comment]
I think it's because of the recent changes in `.htaccess`.

I'm not sure if we should use all these flags by default. Personally I would stay with the initial rule:
```
RewriteRule ^(.*)$ index.php/$1 [L]
```

**Comment by MGatner** [comment]
@InsiteFX could you try reverting that change (https://github.com/codeigniter4/CodeIgniter4/commit/f0e6f60a82be9658999dcebc889ce6e96af996b9) and see if it works? If that fails revert this one and try again: https://github.com/codeigniter4/CodeIgniter4/commit/7c8d3bf44280e026e8ee5c21f5c567fcfc4f457c#diff-d2374d65fd714c18dbee9f5adaa8dd6c

**Comment by InsiteFX** [comment]
This one is the problem!

I reverted this one and everything started working again --> (f0e6f60)

**Comment by MGatner** [comment]
@lonnieezell ’s in trouble 😂

**Comment by paulbalandan** [comment]
Adding square brackets on `\s\S` works for me.

`RewriteRule ^([\s\S]*)$ index.php/$1 [L,NC,QSA]`

**Comment by MGatner** [comment]
@InsiteFX can you try that with square brackets?

**Comment by lonnieezell** [comment]
Square brackets makes sense there.

**Comment by InsiteFX** [comment]
Yes, this did work I try several url's like to home and Myth/Auth login and register all work with these square brackets.

`RewriteRule ^([\s\S]*)$ index.php/$1 [L,NC,QSA]`
