### ISSUE TITLE
erorr line in resize image using fit in visual studio code

### ISSUE THREAD

**Issue by perspolise** [codeigniter4/CodeIgniter4#3249]
I work with Visual Studio Code 1.46.1 and Ci 4.0.2. For resize image I have this code:
```
$image = \Config\Services::image()
        ->withFile('/path/to/image/mypic.jpg')
        ->fit(100, 100, 'center')
        ->save('/path/to/image/mypic_thumb.jpg');
```
this work but i see red line error in visual studio code like this:

![f](https://user-images.githubusercontent.com/19752074/86887141-60251500-c10d-11ea-83d7-aa1ae2f03edd.png)

when i change `fit` to `crop` red line is removed and work true. i think `fit` function have a problem.

**Comment by paulbalandan** [comment]
I can confirm this also with latest `develop` branch. No problem with code. Problem however is on PHPDoc block of `fit` showing return type of `boolean` instead of `$this`.

**Comment by paulbalandan** [comment]
I'll make a PR later.
