### ISSUE TITLE
form_upload second parameter VALUE was not used in source code, i found a way to do it.

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3256]
Hello guys i kinda need your help with this implementation into the form helper form_upload to save the value
This is what i've did.

HTML file with the form upload piece source code

	$input_attrs = array();
	$input_attrs['id'] = 'image';
	$input_attrs['class'] = 'custom-file-input '.$invalid;
	
	echo form_upload('image', set_value('image'), $input_attrs);
	
	if(set_value('image'))
		echo form_hidden('image', set_value('image'));

Form validation Controller piece source code.

	$Rules['image'] = ['label' => 'Image', 'rules'=>'is_image[image]|max_size[image,2048]|uploaded[image]'];
	$this->validator->setRules($Rules);

	if (!$this->validator->run($postData))
	{
            // this is to save the image for later because the image field was good and the rest of the form was invalid. 
            // so we save the file name into an normal input value
		if(!$this->validator->hasError('image')) 
		{
			$image = $this->request->getFile('image');
			
			if($image)
			{
				if ($image->isValid() && !$image->hasMoved())
				{
					$image_val = set_value('image');
					
					$_POST['image'] = $this->request->getFile('image')->store();
					
					@unlink(WRITEPATH.'uploads/'.$image_val);
				}
			}
		}
		
		return redirect()->back()->withInput();
	}
    else // if the form validation was passed
	{
            // we check if there was already an upload we get the file
            if(set_value('image'))
		{
			$image = $this->request->getFile('image');
			$image_val = set_value('image');
			
                        // here we check if the image was reuploaded
			if ($image->isValid() && !$image->hasMoved())
			{
				@unlink(WRITEPATH.'uploads/'.$image_val);
				
				$insert['image'] = $image->getRandomName();
				$image->move(FCPATH.'../assets/files/portfolio_items', $insert['image']);
			}
			else // we use the set_value we already set
			{
				$file = new File(WRITEPATH.'uploads/'.$image_val);
				
				$insert['image'] = $file->getRandomName();
				$file->move(FCPATH.'../assets/files/portfolio_items', $insert['image']);
			}
		}
		else // do a regular upload
		{
			$image = $this->request->getFile('image');
			
			if($image)
			{						
				if ($image->isValid() && !$image->hasMoved())
				{
					$insert['image'] = $image->getRandomName();
					$image->move(FCPATH.'../assets/files/portfolio_items', $insert['image']);
				}
			}
		}
       }

After all this i have an ideea how to implement into the form helper it is very easy and has only this constrain if you use the name image for the $_FILES this name will not be available on the POST / GET request.

On another hand this validator needs to to all of this by itself that is very hard for me to implement.

This piece of code here works every way with the browser i have tested so far. and for sure it can be made on CLI also.

Someone can you review this please and tell me what do you think about this ?

**Comment by crustamet** [comment]
If we do this we can use simply. I hope.

$insert['image'] = set_value_image('image') for not interfere with the other set_value

**Comment by michalsn** [comment]
I'm glad it works for you, but I don't think it fits the framework's core.

The thing is we are still not able to set a default value for file input because it's not supported by the browser.

Also, I would advise you to not blindly trust user input.

**Comment by crustamet** [comment]
Wait what ?
The file is saved if it passed all validations, and then is output in a input type text, what it has to do with the browser ?

**Comment by michalsn** [comment]
Not everyone expects this kind of behavior from the file input. It has a lot to do with the browser and the way the file input is handled by it.

When I was saying "to not blindly trust user input" I was referring to this line: 
```php
$file = new File(WRITEPATH.'uploads/'.$image_val);
```

Feel free to make your own extension/package but I personally don't see a place for something like this in the core.
