### ISSUE TITLE
Bug: CodeIgniter\I18n -> Class 'Locale' not found

### ISSUE THREAD

**Issue by devorama** [codeigniter4/CodeIgniter4#3294]
**Describe the bug**
Was looking at this issue
https://github.com/codeigniter4/CodeIgniter4/issues/1807

when I tried to test his samples, I then looked at docs on how to load the class
https://codeigniter4.github.io/CodeIgniter4/libraries/time.html?highlight=settimezone
But instead I got the error
Class 'Locale' not found

Checked the source and there is nothing named Locale file or Text wise for a class

IncomingRequest has this logic in there code, but Time.php uses it directly

```
                        if (class_exists('\Locale', false))
			{
				\Locale::setDefault($locale);
			} 

```

**CodeIgniter 4 version**
4.0.3

**Affected module(s)**
Time.php , part of CodeIgniter\I18n

**Expected behavior, and steps to reproduce if appropriate**
Should load the file

**Comment by paulbalandan** [comment]
You need to have the `intl` extension installed on your machine.

**Comment by devorama** [comment]
@paulbalandan  Thank you for that  , did not realize it via the docs, might be handy to mention it in docs, if it is somewhere I missed it sorry, thanks again. 
 
> You need to have the `intl` extension installed on your machine.

**Comment by devorama** [comment]
For extra reference thanks to paulbalandan comment I found the php manual doc entry for it
https://www.php.net/manual/en/class.locale.php
one can get the install info etc from there based on the pacakge the class in part of.
(https://www.php.net/manual/en/book.intl.php)

**Comment by paulbalandan** [comment]
It's okay. It is stated in the README.

https://github.com/codeigniter4/CodeIgniter4#server-requirements

**Comment by devorama** [comment]
Thank you again @paulbalandan  for the quick help. Then all good I just missed it. Thanks again

**Comment by adityabayu1231** [comment]
Thanks

**Comment by huynhminhsangit** [comment]
I'm facing this problem after setting vhost, if i run serve with spark cml: php spark serve it's ok, when i try using vhost, i get locale class not found. 
Note: intl extension in php.ini without semicolon.
Anyone pls send me a solution to fix this. Thank you very much!
My OS: MacOS 13.0
Model: Mac Air M1 2020

**Comment by kenjis** [comment]
You need to have the `intl` extension installed in your vhost PHP.

**Comment by cijagani** [comment]
@huynhminhsangit you need to enable extension in php.ini for php-cli. There will be 2 php.ini files. You have to do in php-cli too.

**Comment by huynhminhsangit** [comment]
> 

I try view in location you suggest but not see it
<img width="773" alt="image" src="https://user-images.githubusercontent.com/16367000/200496507-8994b9f9-0b3f-4d55-a2a9-b0c3a5be2860.png">

**Comment by kenjis** [comment]
You need to know where the `php.ini` locates. There may be many `php.ini` in your PC.
You can find the path with the `phpinfo()` function for web, or the `php --ini` command for CLI.
