### ISSUE TITLE
Language folders inside locale folders

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3300]
This is already working or ?

For me it does not working

I have in the locale language folder /en
Another folder with some language files 

/en/test/add.php
/en/test/edit.php

etc...

How can i make this work ?

**Comment by michalsn** [comment]
It was resolved here: https://github.com/codeigniter4/CodeIgniter4/pull/3254

Please ask support questions in the [Forum](https://forum.codeigniter.com/forum-30.html).
