### ISSUE TITLE
Bug: URI::setQuery replaces dots in URL parameters with underscores

### ISSUE THREAD

**Issue by JanZelenka** [codeigniter4/CodeIgniter4#3303]
When performing Curl calls, the method mentioned in the title uses parse_str to make an array of parameters.
As per the PHP documentation, parse_str replaces characters illegal in variable names with underscore.
The outgoing query parser must be able to work with the request without modifying it.

*CodeIgniter 4 version:* 4.0.3
*Affected module(s)*: Those using the URI class
*Expected behavior*: Performing a CURL call shouldn't end up sending a different request than the one specified by the calling code.
*Context*: MacOS MAMP 4.5 with PHP 7.2.1

**Comment by devorama** [comment]
If I might ask, what type of query variables are you trying to send  for the document state
"Because variables in PHP can't have dots and spaces in their names, those are converted to underscores"
This can I assume that this will be good values to test with  ?

`?test me=4&test.another=23`

**Comment by JanZelenka** [comment]
Yes, I believe that would be a good test. My parameter is this: ?script.param=123

**Comment by devorama** [comment]
Hi there. 
On a subnote you look for those parameters in a php script via the $_GET,$_POST or $_REQUEST they will also 
be converted as with parse_str. Thus it maybe not best practice, but will give it a look to see if there is a solution if somebody else 
dont come up with a solution beforehand

https://www.php.net/manual/en/language.variables.external.php

**Comment by devorama** [comment]
This just for information sake. Tested with the following
```
 		  $uri = new URI();  
		  $arr['script.param'] = 1234;
		  $arr['another test'] = 'hallo test';
		  $arr['another[bracket]'] = 'hallo bracket';
          $arr['another-minus'] = 'hallo minus';		  
		  $uri = $uri->setQueryArray($arr);
		  
		  echo 'setQueryArray  : '.$uri->getQuery() . '</br>';
		  
		  $uri = new URI();  
		  $uri = $uri->setQuery('?script.param=1234&another test=hallo test&another[bracket]=hallo bracket&another-minus=hallo minus');
		  echo 'setQuery  : '.$uri->getQuery() . '</br>';
```
and the output is the following
```
setQueryArray : script_param=1234&another_test=hallo+test&another%5Bbracket%5D=hallo+bracket&another-minus=hallo+minus
setQuery : script_param=1234&another_test=hallo+test&another%5Bbracket%5D=hallo+bracket&another-minus=hallo+minus
```

**Comment by devorama** [comment]
@michalsn 
Based on this post, this is a possible security concern also as it can be abused the  way underscores are parsed into the variables
CI uses the variables directly from $_POST etc in CodeIgniter\HTTP\Request -> populateGlobals

https://www.secjuice.com/abusing-php-query-string-parser-bypass-ids-ips-waf/

**Comment by michalsn** [comment]
@devorama It was a security threat in Drupal since they have some Form API that actually uses `#`. We don't allow this sign in the query string. Maybe it's a lack of knowledge from my side but I don't see here anything we should worry about.

As for initial issue - we probably need to introduce some new option like `useRawQuery` or something, and use it with the CURLRequest class.

**Comment by johpromed** [comment]
@michalsn  Thank you for your time in and knowledge in this. The useRawQuery idea is a good one as it wont break current known functionality and behaviour.
