### ISSUE TITLE
CURL Error htts SSL 

### ISSUE THREAD

**Issue by demortx** [codeigniter4/CodeIgniter4#3314]
https://github.com/codeigniter4/CodeIgniter4/blob/b1e2dece4a9598b55acaefcdf02eac633c52452e/system/HTTP/CURLRequest.php#L676

You must add a parameter
$curl_options[CURLOPT_SSL_VERIFYHOST] = $config['verify'];

Otherwise, an unpredictable error occurs when accessing http://

Or add the ability to set options
Exemple: 
$curl = new CURLRequest( $config, new URI($options['base_uri'] ?? null), $response, $options );
$curl->setOpt(CURLOPT_SSL_VERIFYHOST, false);

**Comment by Instrye** [comment]
Did you encounter any errors?
In production environments the value of this option should be kept at 2 (default value).

**Comment by demortx** [comment]
> Did you encounter any errors?
> In production environments the value of this option should be kept at 2 (default value).
