### ISSUE TITLE
See method in controller testing does not recognize accents

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#3319]
it seems that there is a bug in the functions that read the dom, since when looking for letters with accents the tests fail.

```
$result->see('Recuperación de contraseña')
```

Regards!

**Comment by samsonasik** [comment]
Please check if #3324 fix it.

**Comment by luispastendev** [comment]
Thank you very much @samsonasik  your PR solved the support for strings with accents

Regards :)!
