### ISSUE TITLE
Bug: Pager pagination ( page value in url )

### ISSUE THREAD

**Issue by ixiDev** [codeigniter4/CodeIgniter4#3328]
Hi.
i am using a pager library to make pagination  to table in html but  the pagination links not correct at all .
for example :
the expected link like this : http://example.com/posts?page=2
but i got this   http://example.com/posts?page_1594893828=2
i don't know where this random number (1594893828) come from .

**CodeIgniter 4 version**
ci_version : 4.0.2

**Affected module(s)**
Pager

**Solution**

The solution that i make to fix this error is to go to **System/Pager/Pager.php** class 
Line 500  and  replace this : 
`'pageSelector' => $group === 'default' ? 'page' : 'page_' . $group,`
with this :
 `'pageSelector' => 'page',`
 the random number come from $group variable and it's change every time
-------
what i want to know is is that solution that i make is it's correct or not.
Thanks <3

**Comment by michalsn** [comment]
Please upgrade to the latest version - we have v4.0.4 already. Also, I was not able to reproduce this error with the latest relese.

**Comment by ixiDev** [comment]
@michalsn  
Ok thanks i will try it
