### ISSUE TITLE
Bug: API requests with a trailing forward slash

### ISSUE THREAD

**Issue by djsaturn** [codeigniter4/CodeIgniter4#3330]
I spent a lot of time trying to figure out why my routes were not working and found that I needed to exclude the trailing forward slash.

```
$routes->post('API/news', 'API\News::create');

$routes->get('API/news', 'API\News::view'); 
```

Example:
POST http://localhost/API/news/ will send you to the GET (http://localhost/API/news/view) route
POST http://localhost/API/news will work correctly

Even if I set my route with the trailing forward slash I still get routed to API\news::view. 

CI Version 4.0.4

**Comment by bagimuka** [comment]
$routes->post('API/news', 'YourController::create');
    $routes->get('API/news', 'YourController::view');

**Comment by michalsn** [comment]
Not really a bug. Trailing slashes are redirected by default. But now I started to wonder if these rules should be enabled by default.

If you want to change this behavior, edit your `.htaccess` file and comment out these two lines responsible for removing trailing slashes from request https://github.com/codeigniter4/CodeIgniter4/blob/develop/public/.htaccess#L19

**Comment by djsaturn** [comment]
I see, not sure what the purpose is of redirecting on trailing slashes but when calling these routes with an API the results are not correct and can cause some frustration trying to figure out what's wrong. Took me a few hours to figure this one out. 

Thanks!

**Comment by paulbalandan** [comment]
In this [article](https://www.danielmorell.com/guides/htaccess-seo/redirects/https-www-and-trailing-slash), Google's John Mueller clarified what counts as duplicate content in this tweet.

> I noticed there was some confusion around trailing slashes on URLs, so I hope this helps. tl;dr: slash on root/hostname=doesn't matter; slash elsewhere=does matter (they're different URLs)
![image](https://user-images.githubusercontent.com/51850998/87858159-7da07d00-c95e-11ea-98ec-771978f8f293.png)

**Comment by djsaturn** [comment]
On all my internal APIs that shouldn't be a problem to cover. My only concern is when I have APIs available to the public. Lets say someone uses one of my API end points on Zapier or whatever. They inadvertently add the trailing slash. The user might get frustrated and think my APIs do not work. Just my two cents. Now that I understand the reasoning behind it, I have no problem excluding trailing slashes.

**Comment by michalsn** [comment]
Okay, I guess we're leaving this as it is.
