### ISSUE TITLE
Bug: missing clear upgrade instructions

### ISSUE THREAD

**Issue by tangix** [codeigniter4/CodeIgniter4#3332]
**Describe the bug**
CI3 docs contained clear instructions for each upgrade. This is missing from CI4.

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
docs

**Expected behavior, and steps to reproduce if appropriate**
Docs should contain clear instructions for users if there are any changes required to their code.

**Comment by michalsn** [comment]
Resolved via #3333
