### ISSUE TITLE
Bug: Image watermark after save.. text not align in center  middle when resolution lower and higher.

### ISSUE THREAD

**Issue by bagimuka** [codeigniter4/CodeIgniter4#3356]
->withFile('/path/to/image/mypic.jpg')
        ->text('Copyright 2017 My Photo Co', [
            'color'      => '#fff',
            'opacity'    => 0.5,
            'withShadow' => true,
            'hAlign'     => 'center',
            'vAlign'     => 'middle',
            'fontSize'   => 20
        ])
        ->save('/path/to/new/image.jpg');

**Comment by kamal-fresco** [comment]
kjk
