### ISSUE TITLE
Bug: stringify_attributes() looks unfinished.

### ISSUE THREAD

**Issue by ivantcholakov** [codeigniter4/CodeIgniter4#3363]
https://github.com/codeigniter4/CodeIgniter4/blob/v4.0.4/system/Common.php#L1007

The comment about stringify_attributes() says that the first parameter may be a string, an array and an object type. But I don't see code to handle the object type case, for example a type check and get_object_vars() call.

**Comment by ivantcholakov** [comment]
Or something like this: https://gist.github.com/ericlbarnes/3195974

**Comment by paulbalandan** [comment]
Line 1034 is the answer you are looking for.

**Comment by ivantcholakov** [comment]
Ah, sorry.
