### ISSUE TITLE
Bug: warning in Routes.php

### ISSUE THREAD

**Issue by gmeister2** [codeigniter4/CodeIgniter4#3369]
**Describe the bug**
When using the group function in Routes.php, example:
$routes->group('api', ['namespace' => 'App\API\v1'], function($routes)
{
    $routes->resource('users');
});

PhpStorm gives the following warning:
Expected parameter of type 'array|array[]', 'Closure' provided

**CodeIgniter 4 version**
CI 4.04

**Affected module(s)**
app\Config\Routes.php

**Expected behavior, and steps to reproduce if appropriate**
CI 4.03 did not show this warning, because of difference in DocBlock of 'group' function in:
vendor\codeigniter4\framework\system\Router\RouteCollection.php

**Comment by bagimuka** [comment]
$routes->group('/', [
    'namespace' => 'App\Controllers\API\v1''
], function($routes) {

$routes->resource('users');

});


put that in controller folder.. and use name space in ur controller

**Comment by gmeister2** [comment]
I took the example from the CI User Guide. My application work fine, I just wanted to report the warning given by PhpStorm.

**Comment by paulbalandan** [comment]
@gmeister2 I made the PR for the docblock changes of RouterCollection and did not know that PhpStorm resolves docblocks that way. I am using VSCode as my IDE and no warnings were generated using your example. Can you try using `mixed` as typehint if it will be removed?

**Comment by gmeister2** [comment]
Yes, this solves it for me.
`line 729: @param mixed  ...$params`

**Comment by paulbalandan** [comment]
OK, I'll PR that.

**Comment by gmeister2** [comment]
Thanks!

**Comment by vitalijalbu** [comment]
I have the same problem, please help. Thanks.

![carbon-1](https://user-images.githubusercontent.com/40239902/93985211-0c79ad80-fd85-11ea-95cc-35100fff3638.png)
![Schermata 2020-09-22 alle 14 58 38](https://user-images.githubusercontent.com/40239902/93985232-10a5cb00-fd85-11ea-9420-f08d9b9839f4.png)
