### ISSUE TITLE
Bug: Entity's original is not set

### ISSUE THREAD

**Issue by haugli92** [codeigniter4/CodeIgniter4#3370]
**Describe the bug**
\CodeIgniter\Entity class does not set original's when initialized with data as a parameter to __construct function.

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
\CodeIgniter\Entity

**Expected behavior, and steps to reproduce if appropriate**
When initializing a new instance of Entity I assume that attributes:protected and original:protected should be set. Otherwise i cant use functions like hasChanged().

**Code:**
```
$entity = new Entity(['username' => 'Haugli92']);

print_r($entity);
```

**Result:**
```
App\Entities\Entity Object
(
    [datamap:protected] => Array
        (
        )

    [dates:protected] => Array
        (
            [0] => created_at
            [1] => updated_at
            [2] => deleted_at
        )

    [casts:protected] => Array
        (
        )

    [attributes:protected] => Array
        (
            [username] => Haugli92
        )

    [original:protected] => Array
        (
        )

    [_cast:CodeIgniter\Entity:private] => 1
)

```

**Context**
 - OS: Ubuntu 18.04.4
 - Web server Nginx nginx/1.14.0
 - PHP version PHP 7.3.16

**Comment by haugli92** [comment]
By switching positions of syncOriginal() and fill() in the __construct function of Entity-class seems to solve the problem.

```
/**
 * Allows filling in Entity parameters during construction.
 *
 * @param array|null $data
 */
public function __construct(array $data = null)
{
	$this->fill($data);
	$this->syncOriginal();
}
```

Could this have been a solution?

**Comment by michalsn** [comment]
This is not a bug. Some developers may want to set default values for attributes inside the Entity class.

In your case just use `syncOriginal()` after instantiating Entity class. It's a public method for a reason.
