### ISSUE TITLE
Bug: Logs Collector isn't collecting logs for Debug Toolbar

### ISSUE THREAD

**Issue by paulbalandan** [codeigniter4/CodeIgniter4#3376]
**Describe the bug**
I've noticed that we have a Logs collector for showing logs in the toolbar. But there are no logs shown in the toolbar. Even the Logs tab is not shown. I've even triggered an exception to be logged just to test this log collector but still no tab is visible. I've verified in the debugbar JSON file that Logs is included in the collectors.

`Config\Toolbar` has Logs collector active
`Config\Logger` has `$threshold` of 4
debugbar.json has this content for Logs before and after an exception:
```
{
            "title": "Logs",
            "titleSafe": "logs",
            "titleDetails": "",
            "display": {
                "logs": []
            },
            "badgeValue": null,
            "isEmpty": true,
            "hasTabContent": true,
            "hasLabel": false,
            "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACYSURBVEhLYxgFJIHU1FSjtLS0i0D8AYj7gEKMEBkqAaAFF4D4ERCvAFrwH4gDoFIMKSkpFkB+OTEYqgUTACXfA/GqjIwMQyD9H2hRHlQKJFcBEiMGQ7VgAqCBvUgK32dmZspCpagGGNPT0/1BLqeF4bQHQJePpiIwhmrBBEADR1MRfgB0+WgqAmOoFkwANHA0FY0CUgEDAwCQ0PUpNB3kqwAAAABJRU5ErkJggg==",
            "hasTimelineData": false,
            "timelineData": []
        },
```

**CodeIgniter 4 version**
Probably all versions

**Affected module(s)**
Toolbar, or Logs collector

**Expected behavior, and steps to reproduce if appropriate**
The `Logs` will appear as a tab in the Toolbar with the logs there.

**Actual behavior**
![image](https://user-images.githubusercontent.com/51850998/88083499-b7b78c00-cbb5-11ea-9491-d8eb8f71c60a.png)
*No signs of `Logs` tab*

**Context**
 - OS: Win10
 - Web server Apache 2.4.41
 - PHP version 7.4.8

**Comment by michalsn** [comment]
I've added `log_message('error', 'The error says hi');` to the `Home::index`
`$threshold` in `Config\Logger` is set to 3 (by default).

Logs tab in the toolbar is visible.

**Comment by paulbalandan** [comment]
So does that mean we need to manually trigger `log_message` in our code for the tab to appear??

**Comment by paulbalandan** [comment]
I thought the Logs tab serves as a convenient way to view the logs in the writable folder for easy viewing. Am I incorrect?

**Comment by michalsn** [comment]
The Logs tab should show log messages for the current request only.

**Comment by paulbalandan** [comment]
So that's the missing keyword: `current` request. Thanks for the clarification. 😁
