### ISSUE TITLE
Using CodeIgniter4 with Oracle Database

### ISSUE THREAD

**Issue by yogahilmi** [codeigniter4/CodeIgniter4#3388]
Dear All,

I plan to use Oracle Database. 
How do I use Codeigniter 4 with Oracle Database? 
Is it possible?

Thank you very much.

**Comment by lonnieezell** [comment]
There is no currently approved driver yet. However - there is [a PR](https://github.com/codeigniter4/CodeIgniter4/pull/2487) from a while back that is in the pipeline to get more testing and approved. It needs to be updated to the latest version of CI and tested. Not sure if you're up for that, but I don't currently have an Oracle install in place, so additional help testing that out would always be welcome.

**Comment by yogahilmi** [comment]
Thank you,
What about MSSQL? Is it possible with CI4?

**Comment by lonnieezell** [comment]
[That driver](https://github.com/codeigniter4/CodeIgniter4/issues/503) is being actively worked on currently, and sounds like it is getting close. Currently we only have drivers for MySQL, Postres, and SQLite.

**Comment by kenjis** [comment]
See https://codeigniter.com/user_guide/changelogs/v4.2.0.html#database
