### ISSUE TITLE
CodeIgniter4 is ready to work with PHP 7.4?

### ISSUE THREAD

**Issue by circuitmamu** [codeigniter4/CodeIgniter4#3389]
Please submit feature requests to our [forum](https://forum.codeigniter.com/forum-29.html).
We use github issues to track bugs and planned work.

In PHP 7.4 many new changes comes that reduce the code but some functions affect and change its structure from core

Eg.
 [**implode**](https://www.php.net/manual/en/function.implode)
 
 $array = array('lastname', 'email', 'phone');
 $comma_separated_73 = implode(",", $array); // it uses till PHP 7.3
 $comma_separated_73 = implode($array,","); // it uses from PHP 7.4
 
 And in Codeigniter 4 it is many places like database library
 
 So please consider this in feature request

**Comment by lonnieezell** [comment]
All of framework tests are currently passing in 7.4 so I believe, yes, it's ready. I've heard of others using it on that version, also. 

I think you are misunderstanding a change in implode, though. 

> Passing the glue after the pieces (i.e. not using the documented order of parameters) has been deprecated. 

What you're showing that it uses from 7.4 forward is actually what's being deprecated and won't work, even though it's never been documented to work that way.
