### ISSUE TITLE
Bug: CLI options not present in $params when run through spark via terminal

### ISSUE THREAD

**Issue by paulbalandan** [codeigniter4/CodeIgniter4#3400]
**Describe the bug**
I don't know if this is a bug or intentional design choice. if you will be accessing the `$params` array via direct to spark, you will only get the segments. For example:

```php
<?php

namespace CodeIgniter\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;

class TestCmd extends BaseCommand
{
    protected $group        = "Test";
    protected $name         = "test";
    protected $usage        = "test param1 param2 -option1 value1 ";

    public function run(array $params)
    {
        CLI::write(print_r($params, true));
    }
}
```

If I will run `php spark test as df -gh jk` in the terminal, I am expecting result to be
```
Array
(
    [0] => as
    [1] => df
    [gh] => jk
)
```

but got
```
Array
(
    [0] => as
    [1] => df
)
```

This is important if we will be making commands and a developer relies only on `$params` to check for options. If he will write `$option = $params['gh'] ?? null`, overlooking the more comprehensive `$options = $params['gh'] ?? CLI::getOption('gh')`, he will always get `null` even if passing the `gh` option.

This is not a problem if we are making programmatic calls, like using `$this->call()` inside other commands as we can explicitly include the options in the `$params`.

**CodeIgniter 4 version**
develop

**Affected module(s)**
CodeIgniter::runController()

**Context**
 - OS: Win10
 - Web server Apache 2.4.41
 - PHP version 7.4.8

**Comment by samsonasik** [comment]
@paulbalandan can be closed in favor of your PR at https://github.com/codeigniter4/CodeIgniter4/pull/3401  ?

**Comment by paulbalandan** [comment]
@samsonasik that was my first guess and even retried it now. Still fails. `command()` only works for programmatic calls. But if we will be using it directly thru terminal, it will still give only the segments. This behavior is in `CodeIgniter::runController()` where the `$params` passed is the segments array only. I don't know if that is intended really.

**Comment by najdanovicivan** [comment]
Options are not present in the $params array. To get the option value CLI:getOption() method should be used

**Comment by paulbalandan** [comment]
> Options are not present in the $params array. To get the option value `CLI:getOption()` method should be used

Yes, I'm aware of that. But my question is why? Arguments can be accessed by either $params or CLI::getSegment(), but options can only be accessed by CLI::getOption, if made thru spark

**Comment by kenjis** [comment]
This behavior is not consistent.

```sh-session
$ php spark test param1 param2 -opt1 opt1val

CodeIgniter v4.1.4 Command Line Tool - Server Time: 2021-10-15 18:28:19 UTC-05:00

Array
(
    [0] => param1
    [1] => param2
)
```

But if you use `command()`:
```php
command('test param1 param2 -opt1 opt1val');
```
```sh-session
Array
(
    [0] => param1
    [1] => param2
    [opt1] => opt1val
)
```

**Comment by kenjis** [comment]
I think `$param` should have `[opt1] => opt1val` even if called via spark.

**Comment by kenjis** [comment]
In the current implementation, `param` and `option` are completely different.
Therefore the `command()` taking options in params is incorrect behavior.
https://github.com/codeigniter4/CodeIgniter4/blob/0045a6f5f2d7d35cad9123ca5f8efbe84f51eaf6/system/Common.php#L180

But there is no way to pass options to `command()`/`BaseCommand::call()`.

The `BaseCommand::run()` method should have had options as a parameter.
```php
        abstract public function run(array $params, array $options)
```
https://github.com/codeigniter4/CodeIgniter4/blob/0045a6f5f2d7d35cad9123ca5f8efbe84f51eaf6/system/CLI/BaseCommand.php#L101

But adding a parameter is a breaking change.

**Comment by paulbalandan** [comment]
I think the opposite. IMO `command()` represents correct behavior. The way I see it, CI4 was designed initially to work only for browsers (and what the user guide says) that's why code in `system/Codeigniter.php` is working only on the "params" (i.e. URI segments). When support for spark was added later, this behavior was left unchecked (check `CodeIgniter::runController()`)

**Comment by MGatner** [comment]
Good conversation here. I commented on the PR, but just as a reminder CI4 supports three types of requests:
1. Web: URI segments become parameters, sent to Controllers via Routes, output controlled by Headers to browser
2. Spark: accessed by CLI via the `spark` command, arguments are Command arguments, sent to Commands by CommandRunner, output controlled by CLI class
3. PHP CLI: accessed by CLI via `php public/index.php`, arguments become URI segments, sent to Controllers via Routes, output varies

2 & 3 are often conflated because 3 is somewhat of a niche case, but (as of now) still needs to be supported.
