### ISSUE TITLE
Encryption Class does not allow to change digest parameter from SHA512 to SHA256 or others

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3404]
I was trying to encrypt a message with a lower security hmac.

With the SHA512 it just occupy so much space and i want to occupy less space for the message to be encrypted.

For a 6 char message i get a big encrypted message while this is to big for my database to handle.

I just want to use hmac SHA256 for this.

Is this the intended functionality for the encryption library ?
Maybe i`m using something that i don't need to use.

**Comment by crustamet** [comment]
Or can we please have a variable that returns the hex instead of binary for the config encryption ?

**Comment by michalsn** [comment]
Just add `public $digest = 'SHA256';` to your Encryption config file.

Hex for encryption config key - there is a PR underway that will solve this: https://github.com/codeigniter4/CodeIgniter4/pull/3397
