### ISSUE TITLE
Bug: form_textarea helper row and col defaults not overwriting when defined as $extra

### ISSUE THREAD

**Issue by durbintl** [codeigniter4/CodeIgniter4#3412]
**Describe the bug**
The default text area `row="10"` and `col="40"` is not overwritten with the value provided, either as an array or string, in the `$extra` parameter. 

**CodeIgniter 4 version**
CI 4.0.4 (master)

**Affected module(s)**
Form Helper

**Expected behavior, and steps to reproduce if appropriate**
Currently `form_textarea('demo', '', ['rows'=>'4', 'cols'=>'10'])` and `form_textarea('demo', '', 'rows="4" cols="10"')` would both output `<textarea name="mailingaddress" cols="40" rows="10"  rows="4" cols="10"></textarea>`.

**Context**
 - OS: macOS Catalina 10.15.5
 - Web server Apache 2.2.34
 - PHP version 7.4.2

**Comment by Instrye** [comment]
see: https://codeigniter4.github.io/userguide/helpers/form_helper.html#form_textarea
```
form_textarea( ['rows'=>'4', 'cols'=>'10']);
```

**Comment by durbintl** [comment]
@Instrye What you are suggesting does function as expected, however this bug targets the third parameter `$extra` in `form_textarea([$data = ''[, $value = ''[, $extra = '']]])`. Of course we could remove the second and third parameters, but since the code is already in use, that would not be wise less an update should break a site. :)

**Comment by durbintl** [comment]
PR is in testing now.
