### ISSUE TITLE
Bug: delete_cookie() helper function not working

### ISSUE THREAD

**Issue by mail2bapi** [codeigniter4/CodeIgniter4#3433]
**Describe the bug**
I am having an issue with deleting cookies by name. I am using helper function delete_cookie('cookie_name');
But the helper is not deleting the named cookie. Though cookie can be deleted by vanilla PHP.

I am in **development** mode and using **localhost**

**CodeIgniter 4 version**
CI4 Version v4.0.4

**Affected module(s)**

**Expected behavior, and steps to reproduce if appropriate**
Created a session using
` helper('cookie');
        set_cookie([
            'name'   => 'cookie_name',
            'value'  => $encrypter->encrypt($token['token']),
            'expire' => '3600',
        ]);`

Tried to remove it using
`helper('cookie');
delete_cookie('cookie_name');`

My env
`app.cookiePrefix = 'dev_'
app.cookieDomain = ''
app.cookiePath = '/'
app.cookieSecure = true
app.cookieHTTPOnly = false`

**Context**
 - OS: Ubuntu 20.04
 - Web server:  Apache 2.4.43
 - PHP version 7.4.8

**Comment by InsiteFX** [comment]
To delete a cookie you need to give it time in the pass `time() - 3600` see the minus 3600
