### ISSUE TITLE
Bug: Cannot declare class Config\Paths, because the name is already in use

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3434]
Hello i am trying to use the frontend config paths into my backend config paths.
both folders are found inside the codeigniter framework as follows

path/backend // APP folder
path/frontend // APP folder
path/system
path/writable

Both are configured correctly they work very nice.
I changed the path for the folders in the index.php file.
and changed the autoloader to have this namespace available.

Autoloader PSR 

	$psr4 = [
			'App'         		=> APPPATH,
			APP_NAMESPACE 		=> APPPATH,
			'Config'      		=> APPPATH . 'Config',
			'FrontEnd'  		=> ROOTPATH . 'frontend',
	];

in Controller of Backend

	$config = config( 'FrontEnd\\Config\\Paths', false); 
	// the second param is false because if it is true it return the backend path configuration

**Fatal error: Cannot declare class Config\Paths, because the name is already in use in /path/frontend/Config/Paths.php on line 12**

I was looking into the **modules** config file and on both apps and they are enabled
...

I just want to use the frontend paths in the backend.

**Comment by paulbalandan** [comment]
Have you tried namespacing your frontend configs with `FrontEnd\Config` instead of the regular `Config`?

**Comment by michalsn** [comment]
This is just a wrong namespace. @paulbalandan showed how this should be resolved.
