### ISSUE TITLE
getRoutesOptions should return the controller and method if available

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3445]
I am trying to get the controller and method name from the routes

i tried this function getRoutesOptions but it only returns what options you've put for it
namespace, alias, but not the controller or method

Could we have such a function for this ?
Or is already something implemented that i can use ?

For sure i can put in an option that say the crontroller and method manually, but i don't think it is necessary.

**Comment by lonnieezell** [comment]
We only have it for the current route within the router. 

```
service('router')->controllerName();
service('router')->methodName();
```

Currently you would need to extend the RouteCollection to get that information and I'm not convinced it has a large enough use case to include in the core. What are you using it for?

**Comment by crustamet** [comment]
I am trying to make a cronjob sync from crontab automatically find the controller that was implemented in a cronjob controller method

**Comment by crustamet** [comment]
It is really bugging me that this does not returns the controller and the method.. laravel has this function

for Example i have this route

    $routes->group('cronjobs', ['namespace' => 'App\Controllers\Cronjobs'], function($routes){
        $routes->get('test', 'Test::index', ['as'=>'test']);
    }
in my controller 

    $routes = Services::routes();
    print_r($routes->getRoutesOptions('cronjobs/currency_exchange'));

 i got this returned


    [namespace] => App\Controllers\Cronjobs
    [as] => test
 
But the Controller and Method is missing from this array.
I would really like these to be returned also

**Comment by enix-app** [comment]
I think, I need this feature too....

**Comment by lonnieezell** [comment]
We accept pull requests for features people want. And I would be fine with that being added. 

Also - if you want to help out with Cron features for CodeIgniter, [here's an in-development module](https://github.com/lonnieezell/codeigniter4-tasks/) that could really use additional hands. I have almost zero development time at the moment.
