### ISSUE TITLE
Bug: afterUpdate event return array instead of key value

### ISSUE THREAD

**Issue by oleg1540** [codeigniter4/CodeIgniter4#3450]
**Describe the bug**
I tried to use model events - _afterInsert_ and _afterUpdate_.
`protected $afterInsert = ['someFunction'];`
`protected $afterUpdate = ['someFunction'];`

According the docs _afterInsert_ and _afterUpdate_ must return **id**:
> id = the primary key of the new row, or 0 on failure.
> id = the primary key of the row being updated.

But _afterUpdate_ return **id** as array.
I opened _system/Model.php_ and found out there this code:
`if (is_numeric($id) || is_string($id))
		{
			$id = [$id];
		}`
...
`$eventData = [
			'id'     => $id,
			'data'   => $eventData['data'],
			'result' => $result,
		];`
In this regard, the question - is it bug in event data or inaccuracy in the docs?

**CodeIgniter 4 version**
4.0.3.

**Expected behavior, and steps to reproduce if appropriate**
I expected to get primary key value in _someFunction_ instead of array.
`protected function someFunction($data) {
    var_dump($data['id']); // didn't expect array
}`
Another way - make notice about it in docs.

**Context**
 - OS: [Windows 7]
 - Web server [Apache 2.4]
 - PHP version [7.4.5]

**Comment by michalsn** [comment]
I guess that the user guide has to be updated. It's because `update()` method accepts also an array of ids.

PR would be appreciated :)

**Comment by oleg1540** [comment]
Ok, I'll make PR with changes in docs :)
