### ISSUE TITLE
updateBatch does not accept entities

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#3451]
Hello

The `updatebatch()` function does not currently work with entities, nor does the `save()` function.

Currently it only allows working with stdClass objects.

Regards!

**Comment by michalsn** [comment]
`updateBatch()` indeed should be fixed but I don't think there is any problem with `save()` method. Could you please provide an example that would be easy to reproduce?

**Comment by luispastendev** [comment]
Hello @michalsn 

First of all thanks for your PR to solve the problem with `updateBatch()`,

The error occurs when I try to use the `save` function to `save / update` an array of data that are entities for example:

+ currently in the database I have the `id: 10`

2 records enter one to update data of  `id: 10` and a new record to insert.

```php
  $p1 = new Product(); // entity class
  $p1->id = 10; 
  $p1->name = 'update-1';

  $p2 = new Product(); 
  $p2->name = 'new product';

  $model = model('Models/ProductModel');
  $model->save([$p1, $p2]);
```

The expected result would be to update the `name` of the record `id: 10` and insert the new product but when executing the code it throws the following error:

![imagen](https://user-images.githubusercontent.com/4117596/89596779-c9d43400-d81d-11ea-86d1-9713d8457c93.png)

Thank you very much for your precious time.

**Comment by michalsn** [comment]
Thank you for the details. Unfortunately `save()` method doesn't support this kind of functionality and I don't think it should.

Your best shot would be to create a new method `saveBatch()` (or something similar), iterate through your array, and call `save()` for every entity separately.

**Comment by luispastendev** [comment]
@michalsn of course at the moment I am solving it that way, but I thought that the save method could also have that behavior. anyway with updatebatch and insertbatch we have enough to solve any problem

thanks for everything!
