### ISSUE TITLE
Bug: form_textarea in form_helper does not create specified 'rows'

### ISSUE THREAD

**Issue by itartpro** [codeigniter4/CodeIgniter4#3452]
**Describe the bug**

**CodeIgniter 4 version**
4.04

**Affected module(s)**
system/Helpers/form_helper.php
function form_textarea
lines 298 to 301

**Expected behavior, and steps to reproduce if appropriate**
when I create a textarea using echo form_textarea('text', set_value('text'), ['rows' => '5']);
**I still get 10 rows**...anyway for a quick fix is to change lines 298 to 301 from this:
$defaults = [
	'name' => is_array($data) ? '' : $data,
	'cols' => '40',
	'rows' => '10',
];

to this:
$defaults = [
	'name' => is_array($data) ? '' : $data,
	'cols' => $extra['cols'] ?? '40',
	'rows' => $extra['rows'] ?? '10',
];

Please consider this as I use the form helper a lot and my proposed quick-fix adds almost no overhead to system.

**Comment by paulbalandan** [comment]
There is a fix for this in the latest develop branch. Can you pull that and check if that resolves your issue?

**Comment by michalsn** [comment]
I believe it's fixed by #3415

**Comment by itartpro** [comment]
Ah, sweet.
