### ISSUE TITLE
Form validation does not have a rule to validate if field value differs from a string

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3462]
Hello i am trying to validate an input that must have another string besides what i set

So for example
i have an input type text with value of "Test"

I want to validate this field that must be changed so it cannot have string Test inside the field

I have no rule for this
Something like 
is_not_string[test]

**Comment by michalsn** [comment]
You can probably use `regex_match` rule for this. Something like: `regex_match[^(?!.*?Test).*]` maybe?

**Comment by crustamet** [comment]
I also can verify the post and give a custom message saying the string cannot be "Test"

With regex i get error "The Test input has not a valid format". (for this to correct i have to put a custom validation error message)
While a is_not_string[test] can give an error message like "The Test field cannot be Test".

I would really like this is_not_string in the validation form.

**Comment by lonnieezell** [comment]
We have an `in_list` rule already, it would make sense to have the inverse of that, `not_in_list`.
