### ISSUE TITLE
Bug: set() doesn't work on DateTime database field types

### ISSUE THREAD

**Issue by pars0097** [codeigniter4/CodeIgniter4#3471]
```
$loginTime=date('Y-m-d H:i:s')
$userModel->set(['lastLogin' => $loginTime])->where('id',$user['id'])->update();
```
it should Update the lastLogin field with $loginTime value. 
but it produces an error: You must use the "set" method to update an entry. 
when I change 'lastLogin' to a text field type it works correctly.

CI v4.0.4
OS: Windows 10
Web server apache
PHP v7.4

**Comment by InsiteFX** [comment]
You know you can have MySQLi automatically update the datetime fields if you setup your tables like this:

`  `created_at`  DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at`  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`

**Comment by paulbalandan** [comment]
I think this error is due to method overloading. Not sure if this will work but can you try this:
```php
$userModel->where('id',$user['id'])->set(['lastLogin' => $loginTime])->update();
```

**Comment by michalsn** [comment]
@InsiteFX Using `CURRENT_TIMESTAMP` is not really applicable here... also this method has two pitfalls - it does not always use the timezone we want (and we're not always able to set it to what we need). And the second is that the value is always updating ;)

@pars0097 Please check if you have `lastLogin` listed in your model's `$allowedFields`.
