### ISSUE TITLE
Bug:  Fatal error running

### ISSUE THREAD

**Issue by dicky54putra** [codeigniter4/CodeIgniter4#3473]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**

**CodeIgniter 4 version**
Which version (and branch, if applicable) the bug is in.

**Affected module(s)**
Which package or class is the bug in, if known.

**Expected behavior, and steps to reproduce if appropriate**
A clear and concise description of what you expected to happen,
and how you got there.  
Feel free to include a text/log extract, but use a pastebin facility for any
screenshots you deem necessary.

**Context**
 - OS: [e.g. Windows 99]
 - Web server [e.g. Apache 1.2.3]
 - PHP version [e.g. 6.5.4]

**Comment by dicky54putra** [comment]
PHP Warning:  require(C:\xampp\htdocs\ci4app\app\Config/../../vendor/codeigniter
4/codeigniter4/system/bootstrap.php): failed to open stream: No such file or dir
ectory in C:\xampp\htdocs\ci4app\spark on line 44

Warning: require(C:\xampp\htdocs\ci4app\app\Config/../../vendor/codeigniter4/cod
eigniter4/system/bootstrap.php): failed to open stream: No such file or director
y in C:\xampp\htdocs\ci4app\spark on line 44
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\ci4app\app
\Config/../../vendor/codeigniter4/codeigniter4/system/bootstrap.php' (include_pa
th='C:\xampp\php\PEAR') in C:\xampp\htdocs\ci4app\spark on line 44

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\ci4app\app\Conf
ig/../../vendor/codeigniter4/codeigniter4/system/bootstrap.php' (include_path='C
:\xampp\php\PEAR') in C:\xampp\htdocs\ci4app\spark on line 44

**Comment by paulbalandan** [comment]
Run `composer install` or `composer update` in your terminal.

**Comment by InsiteFX** [comment]
Did you move the public folder or rename?

**Comment by michalsn** [comment]
Not a bug. 

If running `composer update` didn't help and you still have a problem with the installation, please feel free to post on our [Forum](https://forum.codeigniter.com/forum-30.html).
