### ISSUE TITLE
Bug: Argument 1 passed to CodeIgniter\Config\Services::request() must be an instance of Config\App or null, instance of BackEnd\Config\App

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3475]
I have changed the namespace from Config\App to BackEnd\Config\App

it gives me an error in the core here. 
called in /path/system/CodeIgniter.php on line 571

Some of configuration files i can't use on BackEnd and FrontEnd simultaneously.

How can i make this work without changing core ?

This issue come from #3434

**Comment by crustamet** [comment]
Some of config files are working by changing the namespace for instance 
App/Config/Paths.php

But for some config files are not working. 

It requires me to change all cores files where are hardcoded ?

**Comment by crustamet** [comment]
I had to remove from services where **App $config** was present just like below

From all static functions where that was present only like that i can really have different namespace for every config without changing alot of core files.

FROM

	public static function request(App $config = null, bool $getShared = true)
	{
		if ($getShared)
		{
			return static::getSharedInstance('request', $config);
		}

		if (! is_object($config))
		{
			$config = config(App::class);
		}

		return new IncomingRequest(
				$config,
				static::uri(),
				'php://input',
				new UserAgent()
		);
	}

TO

	public static function request($config = null, bool $getShared = true)
	{
		if ($getShared)
		{
			return static::getSharedInstance('request', $config);
		}

		if (! is_object($config))
		{
			$config = config(App::class);
		}

		return new IncomingRequest(
				$config,
				static::uri(),
				'php://input',
				new UserAgent()
		);
	}

Do you think guys that is necessarily to have this **App $config** in all those services ?

**Comment by michalsn** [comment]
Your own config file should extend `Config\App`.

Please ask support questions in the [Forum](https://forum.codeigniter.com/forum-30.html).

**Comment by crustamet** [comment]
support questions in the forum that nobody answers ?

I had post 2 threads i had no replies over 3 months ago.

And what do you mean my own config file.

I have the default app config is already extended of BaseConfig


namespace Config;

use CodeIgniter\Config\BaseConfig;

class App extends BaseConfig

__________________________________
I don't want a new config file i just want to use this one.

**Comment by crustamet** [comment]
Please answer when you have the time.
This issue is bugging me for at least 2 weeks.
I will appreciate your answer.

**Comment by paulbalandan** [comment]
As I understand it, `Config` is a reserved and extensively used namespace throughout the framework. So it is not advisable to overwrite this namespace with your own. If there is really a need to have different configs in your case, such as your frontend and backend configs, then it is advised to create a new file for that extending this config.

```php
namespace FrontEnd\Config;

use Config\App as BaseAppConfig;

class App extends BaseAppConfig
{}
```

**Comment by paulbalandan** [comment]
Extending BaseConfig should only be used in creating new config files for new libraries. Not for recreating existing config files. This way we can be sure of no runtime errors while using the wrong config files.

**Comment by crustamet** [comment]
Thank you @paulbalandan i was waiting for a response

Yes i notice i cannot change some of the config files namespace.
I almost post this problem on stackoverflow. 
This rules apply on all config files or only on the App Config ?

I will try out your option. Tricky resolution really.

I am sorry for being such a pain with my problems, but i am following the manual and i'm searching for options before posting here, when i ran out of where to look, i post my issue.

I am sure this will be a problem for big projects in the future for others, i think we should update the documentation with this issue and how to resolve. The documentation only help people for developing new Modules, i guess my structure is a bit different ?

Anyways man thank you again i really appreciate your response.

**Comment by crustamet** [comment]
I really can't get this to work, i created the Files extending this config in each frontend and backend folders

	public $psr4 = [
		APP_NAMESPACE 						=> APPPATH,
		'Config'      						=> APPPATH . 'Config',
		'FrontEnd'  						=> ROOTPATH . 'frontend',
		'FrontEndConfig'  					=> ROOTPATH . 'frontend/Config',
	];

It is not working man, when i try this

	$res = config('\FrontEndConfig\FrontEnd', FALSE); 

or this

	$res = config('\FrontEnd\App', FALSE);

or this

	$res = config('\FrontEnd\Config\FrontEnd', FALSE);

i still receive the BackEnd Config...

When i try this

	$res = config('\FrontEnd\Config\App', FALSE);

or this

	$res = config('\FrontEnd\FrontEnd', FALSE);

Cannot declare class Config\App, because the name is already in use in <b>/path/frontend/Config/App.php on line 0

**Comment by crustamet** [comment]
I've tried everything man is not working, i changed file names i changed the autoload so the namespace will not overlap

either i receive the **admin config** or i get the **Cannot declare class Config\App, because the name is already**

**Comment by paulbalandan** [comment]
Can you try this:

1. Register all namespaces:
```php
public $psr4 = [
    APP_NAMESPACE => APPPATH,
   'Config'                  => APPPATH . 'Config',
   'FrontEnd'              => ROOTPATH . 'frontend',
   'BackEnd'               => ROOTPATH . 'backend',
];
```

2. Make sure the directory structures of frontend and backend are somewhat similar to this: (This way we can be sure it imitates the same structure as the default and so PSR4 is still followed.)
```
frontend ---|
                   |---Controllers/
                   |---Config/
                   |---Filters/
...
```

3. In your frontend or backend config file (e.g. the App config), make sure when you `use` the default `Config\App` you have the `as` keyword to make sure there are no name clashes:
```php
// frontend/Config/App.php
<?php

namespace FrontEnd\Config;

use Config\App as BaseAppConfig;

class App extends BaseAppConfig
{
}

// backend/Config/App.php
<?php

namespace BackEnd\Config;

use Config\App as BaseAppConfig;

class App extends BaseAppConfig
{
}
```

4. Use them now.
```php
$res = config('FrontEnd\Config\App', false);
```

By logic, this should work. If not, then there's probably a problem with `Config::get()`.

**Comment by crustamet** [comment]
I tried this, it does not load my app instead i receive a HTTP error 500

The PSR4 is the same as you post, the folder structure is as what you said

	Uncaught Error: Class 'Config\App' not found in /path/backend/Config/App.php:5

**Comment by crustamet** [comment]
[https://nativityweb.com/structures.png](url)

**Comment by paulbalandan** [comment]
> https://nativityweb.com/structures.png
> 
> I can give you a share screen of what i have setup to verify if everything is legit. if you want

I think I found the fault here.

Please include also the default `app` folder containing the Config, Filters, etc. This `app` folder should be on the same level as `system`.

So
```
path -|
  +---backend
  +---frontend
  +---app
  +---system
  +---writable
```

**Comment by crustamet** [comment]
OMG, i get it now. Thanks.

So in fact they will be treated like a Module not as an app

**Comment by crustamet** [comment]
This is not good man, i've done what you said, everything works fine no errors, but now i never load the backend config only the app config, i wanted to overwrite all variables from app config with the backend app config i cannot.

The thing is i am using different sessions, different database different everything on both frontend and backend, i cant use a default one if i cannot overwrite it when codeigniter starts.

I treat the frontend and backend like separate projects.

Also i have different Autoloaders, for backend and frontend i cannot stick everything into the app autoloader.

Maybe i am doing something wrong or this is how codeigniter works.

Now i get the FrontEnd session on the BackEnd

**Comment by crustamet** [comment]
Everything is loading from the app/Config/App
and not from the backend/Config/App

**Comment by paulbalandan** [comment]
How do you load the configs?

Since you know them already by name you try the direct one. 
`$res = new \BackEnd\Config\App();`

if you will be using the `config()` function try the full name also.
`$res = config('BackEnd\Config\App', false);`

**Comment by crustamet** [comment]
getting the config now works, but the problem is the application when bootstrap starts everything starts with the app folder and not with the backend folder

**Comment by crustamet** [comment]
I mean the project is initialized with the Default config files and not with the backend config files

**Comment by crustamet** [comment]
I think im not making myself clear enough, i don't know if you understand what i am trying to do here..
I will try to explain as best i can.

So my public folders i have 

public_html/index.php for the frontend. This must use FrontEnd Configuration files
public_html/admin/index.php for the backend. This must use BackEnd Configuration Files

This means i have different session settings, different database settings, different autoload settings, different libraries, filters, services, etc..

This worked without the App Folder that you specified here

> 
> I think I found the fault here.
> 
> Please include also the default `app` folder containing the Config, Filters, etc. This `app` folder should be on the same level as `system`.
> 
> So
> 
> ```
> path -|
>   +---backend
>   +---frontend
>   +---app
>   +---system
>   +---writable
> ```

I just want to get the frontend cookie from the session from the config file without hardcoding it
in my backend.

I do not treat the frontend and backend as Modules, i treat them as applications that uses the same codeigniter system.
Do you think is possible what i am trying to do here ?

**Comment by paulbalandan** [comment]
OK. I think I'm getting what you are trying to do here. I saw that structure on a website I have taken over in creating.

Since you are creating two different index.php files, make sure you have also two different bootstrap files. At present, the initialization of the `CodeIgniter` object is done using the default `Config\App` as you've said.

1. Copy the bootstrap.php file somewhere. But make sure to have a distinction, like frontendBootstrap.php or whatever.
2. In those copied bootstrap files, edit instances of `APPPATH` with `ROOTPATH . 'backend'` or `ROOTPATH . 'frontend'`.
3. Then change this line `$appConfig = config(Config\App::class);` to use your specific config.
4. In your respective index files, change the line `$app = require realpath(rtrim($paths->systemDirectory, '/ ') . '/bootstrap.php');` to where you have stored your custom bootstrap.

**Comment by crustamet** [comment]
Ok i have copied backend folder to another folder named test so i can test there and not be afraid if i brake something
Basically i duplicated what i had working in the backend folder to test folder

I created the TestBootstrap.php inside **test** folder

I did what you asked.
I will post files here.

This is the bootstrap file

	<?php

	namespace CodeIgniter;

	use CodeIgniter;
	use Config;

	/**
	 * The path to the application directory.
	 */
	if (! defined('APPPATH'))
	{
		define('APPPATH', realpath($paths->appDirectory) . DIRECTORY_SEPARATOR);
	}

	/**
	 * The path to the project root directory. Just above APPPATH.
	 */
	if (! defined('ROOTPATH'))
	{
		define('ROOTPATH', realpath(APPPATH . '../') . DIRECTORY_SEPARATOR);
	}

	/**
	 * The path to the system directory.
	 */
	if (! defined('SYSTEMPATH'))
	{
		define('SYSTEMPATH', realpath($paths->systemDirectory) . DIRECTORY_SEPARATOR);
	}

	/**
	 * The path to the writable directory.
	 */
	if (! defined('WRITEPATH'))
	{
		define('WRITEPATH', realpath($paths->writableDirectory) . DIRECTORY_SEPARATOR);
	}

	/**
	 * The path to the tests directory
	 */
	if (! defined('TESTPATH'))
	{
		define('TESTPATH', realpath($paths->testsDirectory) . DIRECTORY_SEPARATOR);
	}

	/*
	 * ---------------------------------------------------------------
	 * GRAB OUR CONSTANTS & COMMON
	 * ---------------------------------------------------------------
	 */
	if (! defined('APP_NAMESPACE'))
	{
		require_once ROOTPATH . 'test/' . 'Config/Constants.php';
	}

	// Let's see if an app/Common.php file exists
	if (file_exists(ROOTPATH . 'test/' . 'Common.php'))
	{
		require_once ROOTPATH . 'test/' . 'Common.php';
	}

	// Require system/Common.php
	require_once SYSTEMPATH . 'Common.php';

	/*
	 * ---------------------------------------------------------------
	 * LOAD OUR AUTOLOADER
	 * ---------------------------------------------------------------
	 *
	 * The autoloader allows all of the pieces to work together
	 * in the framework. We have to load it here, though, so
	 * that the config files can use the path constants.
	 */

	if (! class_exists(Config\Autoload::class, false))
	{
		require_once SYSTEMPATH . 'Config/AutoloadConfig.php';
		require_once ROOTPATH . 'test/' . 'Config/Autoload.php';
		require_once SYSTEMPATH . 'Modules/Modules.php';
		require_once ROOTPATH . 'test/' . 'Config/Modules.php';
	}

	require_once SYSTEMPATH . 'Autoloader/Autoloader.php';
	require_once SYSTEMPATH . 'Config/BaseService.php';
	require_once SYSTEMPATH . 'Config/Services.php';
	require_once ROOTPATH . 'test/' . 'Config/Services.php';

	// Use Config\Services as CodeIgniter\Services
	if (! class_exists('CodeIgniter\Services', false))
	{
		class_alias('Config\Services', 'CodeIgniter\Services');
	}

	$loader = CodeIgniter\Services::autoloader();
	$loader->initialize(new Config\Autoload(), new Config\Modules());
	$loader->register();    // Register the loader with the SPL autoloader stack.
	// Now load Composer's if it's available

	if (is_file(COMPOSER_PATH))
	{
		/**
		 * The path to the vendor directory.
		 *
		 * We do not want to enforce this, so set the constant if Composer was used.
		 */
		if (! defined('VENDORPATH'))
		{
			define('VENDORPATH', realpath(ROOTPATH . 'vendor') . DIRECTORY_SEPARATOR);
		}

		require_once COMPOSER_PATH;
	}

	// Load environment settings from .env files
	// into $_SERVER and $_ENV
	require_once SYSTEMPATH . 'Config/DotEnv.php';

	$env = new CodeIgniter\Config\DotEnv(ROOTPATH);
	$env->load();

	// Always load the URL helper -
	// it should be used in 90% of apps.
	helper('url');

	/*
	 * ---------------------------------------------------------------
	 * GRAB OUR CODEIGNITER INSTANCE
	 * ---------------------------------------------------------------
	 *
	 * The CodeIgniter class contains the core functionality to make
	 * the application run, and does all of the dirty work to get
	 * the pieces all working together.
	 */

	$appConfig = config(\Test\Config\App::class);

	$app       = new CodeIgniter\CodeIgniter($appConfig);
	$app->initialize();

	return $app;


Now the index.php file from test folder

	<?php

	// Valid PHP Version?
	$minPHPVersion = '7.2';
	if (phpversion() < $minPHPVersion)
	{
		die("Your PHP version must be {$minPHPVersion} or higher to run CodeIgniter. Current version: " . phpversion());
	}
	unset($minPHPVersion);

	// Path to the front controller (this file)
	define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR);

	// Location of the Paths config file.
	// This is the line that might need to be changed, depending on your folder structure.
	$pathsPath = realpath(FCPATH . '../../path/app/Config/Paths.php');
	// ^^^ Change this if you move your application folder

	/*
	 *---------------------------------------------------------------
	 * BOOTSTRAP THE APPLICATION
	 *---------------------------------------------------------------
	 * This process sets up the path constants, loads and registers
	 * our autoloader, along with Composer's, loads our constants
	 * and fires up an environment-specific bootstrapping.
	 */

	// Ensure the current directory is pointing to the front controller's directory
	chdir(__DIR__);

	// Load our paths config file
	require $pathsPath;
	$paths = new Config\Paths();

	// Location of the framework bootstrap file.
	$app = require realpath(FCPATH . '../../path/test/TestBootstrap.php');
	
	/*
	 *---------------------------------------------------------------
	 * LAUNCH THE APPLICATION
	 *---------------------------------------------------------------
	 * Now that everything is setup, it's time to actually fire
	 * up the engines and make this app do its thang.
	 */
	$app->run();


Now **test/config/app.php**

	<?php namespace Test\Config;

	use Config\App as BaseAppConfig;

	class App extends BaseAppConfig
	{

		public $baseURL = 'https://website.com/test/';

		...
		
	}


I get this Error **Fatal error: Cannot declare class Config\Modules, because the name is already in use in /home2/nativity/nativityweb/app/Config/Modules.php on line 0**

**Comment by crustamet** [comment]
i tried to namespace with \Test\
like this
$loader->initialize(new \Test\Config\Autoload(), new \Test\Config\Modules());

it is not working because they need to be very strict Config\Autoload and Config\Modules when is getting passed to the loader

**Comment by paulbalandan** [comment]
> i tried to namespace with \Test
> like this
> $loader->initialize(new \Test\Config\Autoload(), new \Test\Config\Modules());
> 
> it is not working because they need to be very strict Config\Autoload and Config\Modules when is getting passed to the loader

In that case you need also to extend the Autoload and Modules config as what you did for App config. Something like class Modules extends BaseModulesConfig. This should get away with the typehint.

**Comment by crustamet** [comment]
**test/Config/Modules.php**

	<?php namespace Test\Config;

	use Config\Modules as BaseModulesConfig
	// Cannot extend BaseConfig or looping resources occurs.
	class Modules extends BaseModulesConfig

**test/Config/Autoload.php**

	<?php namespace Test\Config;

	// use CodeIgniter\Config\AutoloadConfig;
	use Config\Autoload as BaseAutoloadConfig;

	class Autoload extends BaseAutoloadConfig


I receive this error **PHP Fatal error:  Uncaught Error: Class 'Config\Autoload' not found in /path/test/Config/Autoload.php:6**

**Comment by paulbalandan** [comment]
Ah. I get it. Since we are not yet using PSR4 autoloading here in the bootstrap files, you need to manually include the extended configs here.
```
if (! class_exists(Test\Config\Autoload::class, false))
{
	require_once SYSTEMPATH . 'Config/AutoloadConfig.php';
        require_once APPPATH . 'Config/Autoload.php';
	require_once ROOTPATH . 'test/' . 'Config/Autoload.php';
	require_once SYSTEMPATH . 'Modules/Modules.php';
        require_once APPPATH . 'Config/Modules.php';
	require_once ROOTPATH . 'test/' . 'Config/Modules.php';
}
```

**Comment by crustamet** [comment]
Ok this seems to work now. Omg dude, you have no ideea how much i tried this..

I cannot believe it is working.

For sure this must go in the documentation.

Thanks for the help, i wouldn't done it without you man.

**Comment by crustamet** [comment]
This works now as intended and i can even get frontend confing in the backend but there are so many problems, for example the Views are now loading from the app/config/view instead of the backend/config/view

I am trying to overwrite Services with the backend services but the view class already initialized somewhere.

The main problem is that i am changing the core as i go, i am afraid with the new updates that will come.

I am for sure there is an easier approach for this problem i had without copy the bootstrap.php change it and loading it.

I don't know if this is a issue or not but i think it is man sincerely, since i had to change alot of stuff, i am certain there are some config files that are using from the app folder and not from the backend folder.

**Comment by crustamet** [comment]
It would have been better if i created a function that reads the file search for the variable and retrieve the value instead of loading it.
I thought i could get the config by changing the namespace but it seems it got very complicated, and besides now i have another app folder that is useless for me and somehow files are loading from there.

Ofcourse they are loading from there hehe :)

**Comment by paulbalandan** [comment]
If you want different views to load you should modify the bootstrap to load your extended Config\Views instead. Then you should modify the path constants like FCPATH to something more relevant like FRONTENDFCPATH. Unfortunately, this is the only way I can think of that will suit your requirements.

For the services you should explicitly provide your modified configs and paths or else the defaults will be used.

**Comment by paulbalandan** [comment]
The idea here is to intercept all calls to the default app files by explicitly providing your custom files.

**Comment by crustamet** [comment]
forget this.. there is no support documentation for multiple index files, i'm gonna remove the app folder and continue from where i was, and make a function that search in the file for the value i am looking for.

That is why i post this issue as i said below if here we drop the APP $config to be strict everything wold have work perfectly, because i already tested it, and can have namespaced configs without extending anything.

After i post this issue i saw a commit that put more strict $configs. 

When you mentioned this issue here
paulbalandan mentioned this issue 3 days ago
Optimize: Services #3463

I thought it will gonna be resolved, looks like we are beginning to limit the developers.

> Some of config files are working by changing the namespace for instance
> App/Config/Paths.php
> 
> But for some config files that the Services are using App $config into the methods are not working only if i remove App $config.
> for example
> 
> ```
> public static function request(App $config = null, bool $getShared = true)
> ```
> 
> remove App to be like this
> 
> ```
> public static function request($config = null, bool $getShared = true)
> ```
