### ISSUE TITLE
Bug: Unable to connect to the database

### ISSUE THREAD

**Issue by dimasoppo448** [codeigniter4/CodeIgniter4#3477]
**Describe the bug**
Please need help. I can't connect to the database not from model or manually connect. The database is exist. Try to change .env or config still doesn't work.

error:
SYSTEMPATH\Database\BaseConnection.php at line 425 (something about connID)
SYSTEMPATH\Database\BaseConnection.php : 646   —  CodeIgniter\Database\BaseConnection->initialize ()

.env:
database.default.hostname = localhost
database.default.database = baru
database.default.username = root
database.default.password = 
database.default.DBDriver = MySQLi

**CodeIgniter 4 version**
4.0.4, Mysqli driver

i have already follow the documentation and change hostname to 127.0.0.1 but still can't connect to he database.

 - PHP version 7.4.8

**Comment by lonnieezell** [comment]
Most likely not a bug. Try changing `localhost` to `127.0.0.1`. 

In the future please ask for help on the forums, we use GitHub for tracking issues.

**Comment by dimasoppo448** [comment]
change localhost to 127.0.0.1 doesn't help

**Comment by paulbalandan** [comment]
You have not provided a password. Or you have not registered yet the root user to MySQL server.

**Comment by dimasoppo448** [comment]
when i run in xampp project/public/ it can connect 

and somehow when use spark serve i can't connect to the database

**Comment by paulbalandan** [comment]
Try setting your logs threshold to 4 so that errors will be logged too. Then run the code again. Then tell us the ERROR line you get in your logs.
