### ISSUE TITLE
Bug: Error message for matches rule doesn't support nested params

### ISSUE THREAD

**Issue by mihail-minkov** [codeigniter4/CodeIgniter4#3492]
**Describe the bug**
When using the Validation library, specifically the matches rule for passwords, it's not clear and not mentioned in the documentation how to implement it. I tried the following:

```php
public $registro = [
    'registro.password' => [
        'rules' => 'required|min_length[6]',
        'errors' => [
            'required' => 'La contraseña es un campo obligatorio.',
            'min_length' => 'La contraseña debe ser de al menos 6 caracteres.'
        ]
    ],
    'registro.verificar_password' => [
        'rules' => 'required|matches[registro.password]|min_length[6]',
        'errors' => [
            'required' => 'Verificar contraseña es un campo obligatorio.',
            'matches[registro.password]' => 'Las contraseñas no coinciden, por favor revisa.',
            'min_length' => 'Verificar contraseña es un campo que debe ser de al menos 6 caracteres.'
        ]
    ]
];
```

The problematic part is the `errors['matches[registro.password]']` index in the validation rules array. If I use it like that, when validating, the error message is:

> The registro.verificar_password field does not match the registro.password field.

Which is not a text defined by me.

If I change it to `errors['matches']` I get the text I defined:

> Las contraseñas no coinciden, por favor revisa.

If I do the following example, I get the following results:

```php
var_dump($post['registro']['password'] == $post['registro']['verificar_password']);
// Output
// bool(true)

if(!$validation->run($post, 'registro')) {
    echo $validation->listErrors();
}
// Output 
// Las contraseñas no coinciden, por favor revisa.
```

**CodeIgniter 4 version**
4.0.4 : dev-develop

**Affected module(s)**
Validation Library

**Expected behavior, and steps to reproduce if appropriate**
I expect the validation to not have errors.

**Context**
 - OS: Windows 10 x64 1909
 - Web server Apache/2.4.25 (Win64)
 - PHP version 7.3.3

**Comment by michalsn** [comment]
You should define your rules this way:
```php
'matches' => 'Las contraseñas no coinciden, por favor revisa.',
```
But besides that, there is indeed a bug. I just prepared a PR with the fix.

**Comment by mihail-minkov** [comment]
It would be really useful if the example is added to the docs here: https://www.codeigniter.com/user_guide/libraries/validation.html

**Comment by michalsn** [comment]
It's already there: https://codeigniter.com/user_guide/libraries/validation.html#translation-of-messages-and-validation-labels

**Comment by mihail-minkov** [comment]
> It's already there: https://codeigniter.com/user_guide/libraries/validation.html#translation-of-messages-and-validation-labels

It is in the rules section only, but there isn't a single example of how to use it in the predefined error messages, that's what brought me here. It's unclear whether it should be used with the brackets or not. I now know how to use it, because you explained above, but I did hit my head against the wall for about an hour :)

**Comment by michalsn** [comment]
Oh... I linked to the wrong section, though it's not bad either.

Look here: https://codeigniter.com/user_guide/libraries/validation.html#setting-custom-error-messages it's a pretty good example and you have a rule with a parameter. IMO validation documentation is pretty solid and we can't add an example for every rule.

**Comment by mihail-minkov** [comment]
> Oh... I linked to the wrong section, though it's not bad either.
> 
> Look here: https://codeigniter.com/user_guide/libraries/validation.html#setting-custom-error-messages it's a pretty good example and you have a rule with a parameter. IMO validation documentation is pretty solid and we can't add an example for every rule.

Yes, I do agree it would be impossible to add this, but again, that includes an example with `['errors']['min_length']` and while that should be enough, if you compare not only 2 fields but several different pairs, it's not really clear how to do it, something like:

```php
'password3' => [
    'rules' => 'required|matches[password]|matches[password2]|min_length[6]',
    'errors' => [
        'required' => 'This field is required',
        'matches[password]' => 'Password 3 doesn\'t match password 1.',
        'matches[password2]' => 'Password 3 doesn\'t match password 2.',
        'min_length' => 'Your password should be at least 6 characters in length.'
    ]
]
```

I know this example is not necessarily a real case scenario, but it's a valid example. As you can see the errors messages could be defined either with `matches` or with `matches[index]`.

**Comment by michalsn** [comment]
The answer is simple. Something like this (`rule[parameter]` on `errors` array) is not supported - just because it's not worth implementing.

Validation class is flexible enough so you can define such rules differently (cascading - with other fields) and if it's somehow impossible, then you can always create your own rule to handle an edge case.

Validation rules are there to cover 90-95% of real-life cases. Everything else has to be handled individually by the developer.
