### ISSUE TITLE
Bug: I cant upload mp4 files 

### ISSUE THREAD

**Issue by hoceyn** [codeigniter4/CodeIgniter4#3494]
**Describe the bug**
when I try to upload a mp4 file, I get invalid file error . I try to check :

- codeigniter config mime file type
- try fix problem with change validation parameters
- change php.ini settings 
- etc
I can upload any files like photos , office and pdf file format with same logic and different validation. but I think it's not possible with mp4 files.

function code :

```
{
        //uploaded file address = https://coverr.co/videos/happy-young-girl-texting-near-the-sea-KwV5cuJ0lr
	$photo = $this->request->getFile($input_name);
	dd($photo);
	//result:
	//protected error -> integer 1
	//protected hasMoved -> boolean false
	//protected name -> string (47) "coverr--06-20-young-girl-at-the-bay-11-3419.mp4"
	//protected originalMimeType -> string (0) ""
	//protected originalName -> string (47) "coverr--06-20-young-girl-at-the-bay-11-3419.mp4"
	//protected path -> string (0) ""
	//protected size -> integer 0

	$validation = $this->validate([
	$input_name => [
				"uploaded[$input_name]",
				"max_size[$input_name,10096]",
				"mime_in[$input_name,video/mp4,video/mp,video/webm'']
		]);
		if(!$validation)
		{
			dd($this->validator->getError($input_name));
		}
	// result:
	// myfile is not a valid uploaded file.

}
```

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
request , file

**Context**
 - OS: [e.g. windows 10]
 - Web server  wamp 2.4.33
 - PHP version [7.2.4]

**Comment by paulbalandan** [comment]
You have an error code of 1, which is `UPLOAD_ERR_INI_SIZE`. You need to adjust the `upload_max_filesize` directive in your php.ini
