### ISSUE TITLE
Bug: Database group defined in .env doesn't work

### ISSUE THREAD

**Issue by mihail-minkov** [codeigniter4/CodeIgniter4#3497]
**Describe the bug**
I am converting a Wordpress site to a new site using CI4. I wanted to make a secondary database connection to import the Wordpress articles to the new site.

What I tried to do was the following:

```env
database.default.hostname = localhost
database.default.database = newdb
database.default.username = user
database.default.password = password
database.default.DBDriver = MySQLi

database.wpdb.hostname = localhost
database.wpdb.database = olddb
database.wpdb.username = user
database.wpdb.password = password
database.wpdb.DBDriver = MySQLi
```

From what I've seen in the docs, the value after `database.` is the group name. Then inside the Model I add this:

```php
$this->wpdb = \Config\Database::connect('wpdb');
```

When I reload my page I get this:

```
InvalidArgumentException
wpdb is not a valid database connection group. 
```

If I add the wpdb group inside the Config\Database.php file it works fine, but then I'd have to add the Database.php to my .gitignore in order to not have issues when deploying in production.

Is this a bug or it's just not supposed to work this way?

Should I understand that the variables added in the .env file related to CI4 are not extendable, or I'd have to modify both files in order to do that?

**CodeIgniter 4 version**
4.0.4 : dev-develop

**Affected module(s)**
env file

**Expected behavior, and steps to reproduce if appropriate**
I want to be able to add the secondary database from the .env file so that I don't have to ignore my Database.php file in terms of configuration.

**Context**
 - OS: Windows 10 x64 1909
 - Web server Apache/2.4.25 (Win64)
 - PHP version 7.3.3

**Comment by michalsn** [comment]
Not a bug.

Variables defined in the `.env` file can only override variables that already exist. To stay safe just don't fill values in your `Config\Database.php` file.
