### ISSUE TITLE
php 8 support

### ISSUE THREAD

**Issue by bagimuka** [codeigniter4/CodeIgniter4#3498]
please updated php version 8 support in this framework. this good for future framework

**Comment by element-code** [comment]
This might be a good moment to drop all support for versions below `7.4` and finally use typing through the framework..

**Comment by paulbalandan** [comment]
Support for `7.2` will be dropped on its EOL this coming November. Support for `7.3` will still continue probably until its scheduled EOL. So support for property typing will not happen very soon enough until supported versions will only be `7.4+`.

**Comment by otengkwame** [comment]
> It will definitely be supported in full, but we will probably build toward it as release isn't until November. My guess is `4.1` will have "tentative support" for PHP 8

It's a good consideration, since PHP 8 will be a big thing for the community

**Comment by lonnieezell** [comment]
4.0.5 and 4.1 will be PHP8 compatible.
