### ISSUE TITLE
Bug: When Cronjob run the ip address of the request is 0.0.0.0

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3512]
i save all my requests into a table of database, i found out that the cronjobs that run on my system the ip address is 0.0.0.0
it should be the ip of the server right ?

**Comment by michalsn** [comment]
Please ask support questions in the [Forum](https://forum.codeigniter.com/forum-30.html).

**Comment by nowackipawel** [comment]
Imho It is correct. What if server has many up addresses or ip4 and ipv6
addresses?

**Comment by crustamet** [comment]
@michalsn This was a retorical question, did you even read the title ?

This is a BUG.
Steps to recreate is when using the command line the 
Request Class from the codeigniter RETURNS the ip_address 0.0.0.0

It should be the IP of the Server.

**Comment by michalsn** [comment]
Yes, my bad - sorry about that.

For future reference - if possible, please use our template to report bugs. It will help a lot.

**Comment by crustamet** [comment]
k i understand. thanks. maybe in the future who got the same for cli request will be able to extend it somehow and change the request class with the ip address
