### ISSUE TITLE
Bug: Upload file validation, $model->validate return true if failed

### ISSUE THREAD

**Issue by sandiwinter** [codeigniter4/CodeIgniter4#3532]
**Describe the bug**
When uploading file, validation returning true but validation error message exists

**CodeIgniter 4 version**
Version 4.0.0

**Affected module(s)**
Validation

**Expected behavior, and steps to reproduce if appropriate**
define validation rule like:
'package' => 'max_size[package,10000]|ext_in[package,zip]'
then upload file like .txt and run validation function

**Context**
 - OS: Windows 10
 - Web server Apache
 - PHP version 7.2

**Comment by sandiwinter** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/2854469/91088818-f5934e80-e652-11ea-996c-9e8c4cf7f5c3.jpg)

I noticed that this part will solve issue

**Comment by MGatner** [comment]
First, you referenced `4.0.0` - if that's actually the tested version then please confirm the issue still exists on the la eat branch. 

Second, I'm not sure that Model should be interacting with file upload fields. Can you share more of the context where this is causing issues? Cleaning validation rules ensures the data is ready for the database and probably file validation should be happening in the controller.

**Comment by sandiwinter** [comment]
Based on documentation we can use file upload validation rules:
https://codeigniter.com/user_guide/libraries/validation.html?highlight=validation#rules-for-file-uploads

Issue is in Cleaning validation rules function inside model, because function checking only $_POST, but files coming in $_FILES so rule is removed even if file is uploaded.

I suggested solution here which works perfectly on my side:
https://github.com/sandiwinter/CodeIgniter4/commit/d9631f3c0f1c2f63b609b8d06da4f059a4d8e5e6

Maybe someone from CI team can optimize this a bit if needed.

Thanks

**Comment by MGatner** [comment]
I understand the issue. My point is that using your `Model`'s validation is preparing data for the database, and since files cannot be inserted it should be perfectly normal for the model to ignore validation rules related to content in `$_FILES`. If you need to validate uploads I recommend doing it at the Controller (https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#the-controller) and then passing database-relevant content to your Model for its own validation.

**Comment by sandiwinter** [comment]
Thanks! ,  found solution which works even without changing core files:

```
$save_data = array_merge($this->request->getPost(), array('myfile'=>$this->request->getFile('myfile')));

if($this->request->getMethod() == 'post')
        if ($model->validate($save_data) == TRUE)
```

So file must be added in validation rule, $this->request->getPost() is not enough.

Maybe there is some more elegant method to fetch all request data?

**Comment by MGatner** [comment]
Glad you got it working. I don't think there is a way to gather post and file data in one go - this is because they are stored in separate superglobals int he underlying PHP. `$_REQUEST` has "Get" and "Post" values but `$_FILES` is not included in any other superglobal.

**Comment by sandiwinter** [comment]
Ok this is fine solution. Thank you very much!
