### ISSUE TITLE
Bug: Invalid serialization data for DateTime object

### ISSUE THREAD

**Issue by AngelRodriguezGuru** [codeigniter4/CodeIgniter4#3553]
**Describe the bug**
I create an entity and cache it. When I try to get from cache it gives me error: "Invalid serialization data for DateTime object".

```
SYSTEMPATH\Cache\Handlers\FileHandler.php at line 321
$data = unserialize(file_get_contents($this->path . $key));
```

This is example code:

```
// Entity
class Web extends Entity
{
    protected $attributes = [
       'url'  => null,
       'created_at' => null
   ];
}

// Controller
$web = new \App\Entities\Web();
$web->url = 123;
$web->created_at = date('Y-m-d H:i:s');

$cache = service('cache');
$cache->save('webname', $web, 300);

$web = $cache->get('webname');
print_r($web);
```

**CodeIgniter 4 version**
4.0.3

**Affected module(s)**
Entity, Cache, DateTime

**Context**
 - OS: Windows 10
 - Apache 2.4.41
 - PHP 7.4.2

**Comment by paulbalandan** [comment]
This is because on unserialisation, `DateTime::__wakeup()` is called but the serialized object is `Time` which has properties not present in the native `DateTime`. This causes invalid serialization
