### ISSUE TITLE
Deprecated assertArraySubset in PHPUnit8 used in FeatureResponse::assertJSONFragment

### ISSUE THREAD

**Issue by paulbalandan** [codeigniter4/CodeIgniter4#3562]
This is meant to be addressed in v4.1 where hopefully after bumping PHP version requirement we'll also bump dependencies' version, like phpunit to v9.

`FeatureResponse::assertJSONFragment` is using the [deprecated `assertArraySubset` method](https://github.com/sebastianbergmann/phpunit/issues/3494).

**Comment by MGatner** [comment]
Definitely that will be the time to make the change. I'm sure this can be addressed sooner - thanks for making the note on it.
