### ISSUE TITLE
can not install on linux os

### ISSUE THREAD

**Issue by sabbirshawon** [codeigniter4/CodeIgniter4#3572]
I have got these two errors while run codeingter 4 on linux os

`Warning: require(/opt/lampp/htdocs/ci4/test01/app/Config/../../vendor/codeigniter4/framework/system/bootstrap.php): failed to open stream: No such file or directory in /opt/lampp/htdocs/ci4/test01/public/index.php on line 36
`

`Fatal error: require(): Failed opening required '/opt/lampp/htdocs/ci4/test01/app/Config/../../vendor/codeigniter4/framework/system/bootstrap.php' (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/ci4/test01/public/index.php on line 36`

**Comment by paulbalandan** [comment]
Did you downloaded `codeigniter4/appstarter`?

**Comment by paulbalandan** [comment]
Run `composer install` in your terminal.

**Comment by sabbirshawon** [comment]
I tried with this command but still showing these errors..

**Comment by paulbalandan** [comment]
Show me your project directory structure.

**Comment by sabbirshawon** [comment]
Firstly I tried with this command:
`composer create-project codeigniter4/appstarter test01`

then in terminal i faced these issues:

`Installing codeigniter4/appstarter (v4.0.4)
  - Installing codeigniter4/appstarter (v4.0.4): Loading from cache
Created project in test01
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codeigniter4/framework v4.0.4 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - codeigniter4/framework v4.0.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - codeigniter4/framework v4.0.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - codeigniter4/framework v4.0.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - codeigniter4/framework 4.0.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - Installation request for codeigniter4/framework ^4 -> satisfiable by codeigniter4/framework[4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.`


Then when i try to run: http://localhost/ci4/test01/public/ it shows these erros:

`Warning: require(/opt/lampp/htdocs/ci4/test01/app/Config/../../vendor/codeigniter4/framework/system/bootstrap.php): failed to open stream: No such file or directory in /opt/lampp/htdocs/ci4/test01/public/index.php on line 36`

`Fatal error: require(): Failed opening required '/opt/lampp/htdocs/ci4/test01/app/Config/../../vendor/codeigniter4/framework/system/bootstrap.php' (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/ci4/test01/public/index.php on line 36`

**Comment by MGatner** [comment]
> Your requirements could not be resolved to an installable set of packages

You do not meet all the system requirements. Please review them in the User Guide: https://codeigniter4.github.io/CodeIgniter4/intro/requirements.html

If you need more help, support requests should be open on the forums - GitHub Issues are for bug reports: https://forum.codeigniter.com/forum-30.html
