### ISSUE TITLE
Bug: Uninitialized string offset: 1    CI 4

### ISSUE THREAD

**Issue by snowoffice** [codeigniter4/CodeIgniter4#3573]
Error Getting
"title": "ErrorException",
    "type": "ErrorException",
    "code": 500,
    "message": "Uninitialized string offset: 0",
    "file": "D:\\Xampp\\htdocs\\works\\SciHorizon\\system\\Database\\Query.php",
    "line": 479,

Apache Server

Prepare statement i am using
```
$pQuery = $this->DB->prepare(function($db)
{
    $sql = "INSERT INTO articles (article_slug,article_url,article_title,
                article_abstract,article_authors,article_area,article_keywords,article_journal,
                article_volume,article_issue,article_page_no,article_indexing,
                article_published_date,article_created_by,
                article_created_ip,pdf_name,pdf_file,image_file,image_file_name)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    return (new Query($db))->setQuery($sql);
}); 
```

Query Execution
```
$pQuery->execute("slug","url","title","abstract","authors","areas",
"keywords","journalName","volume","issue","pageNumber","indexing",
"publishDate","creatingAuthor","ip","pdfTitle","pdfFileName","",""); 
```

Issue:
After inserting into database getting the above error.

Cases 1
    Getting the above error if i try to insert any empty string for any field.
case 2 
   If all fields are non empty then no error

**Comment by paulbalandan** [comment]
The error is pretty straightforward. You are trying to have an array access on an empty string.
```php
$word = 'CodeIgniter';
$a = $word[0];
echo $a; // will give you 'C'

$empty = '';
$b = $empty[0]; // will throw an error
```
