### ISSUE TITLE
Bug: Model doesn't reset errors in FeatureTestCase

### ISSUE THREAD

**Issue by lefuentes** [codeigniter4/CodeIgniter4#3578]
**Describe the bug**
When I test with FeatureTestCase class the errors of  models don't reset and I receive the last error. 
Example:
Test PUT Method with bad validation. It return that I expect. But in the next test if I Test Put Method with success validation I still receive the last errors.
[Example](https://pastebin.pl/view/1de3f1cd)

**CodeIgniter 4 version**
latest.

**Context**
 - OS: [Linux]
 - PHP version [7.3]

**Comment by MGatner** [comment]
Are your tests using `model()` or `ModelFactory` to load your models? If so you are probably getting shared instances of them. You can use `ModelFactory::reset()` in your test `setUp()` to make sure shares instances are cleared. This might not be a bad idea to add to the default resets.

**Comment by lefuentes** [comment]
I don't use `ModelFactory`. I will try with that. But I think it doesn't a clear solution. 
I have another bug when I use FeatureTestCase. The filters definied in the routes don't reset when first I test an route with filter and then I test an route without filters.
https://github.com/codeigniter4/CodeIgniter4/blob/8c90aa045e906a909dde3ca300b428048e038d21/system/CodeIgniter.php#L409

It's beacuse the variable `filterInfo` has the before value
https://github.com/codeigniter4/CodeIgniter4/blob/8c90aa045e906a909dde3ca300b428048e038d21/system/Router/Router.php#L182

If it's necessary I will create another issue.

**Comment by MGatner** [comment]
The Filters issue sounds like this (https://github.com/codeigniter4/CodeIgniter4/issues/3085) resolves July 7. Are you using the latest version of the code?

**Comment by lefuentes** [comment]
I tried this solution but it doesn't work. it's apply after of function `tryToRouteIt`. 
Tomorrow I will upload an example complete about this bug.

**Comment by MGatner** [comment]
Okay, please open a new issue for the filters example, and this can track the validation issue. My guess is that you will need to reset Validation between tests - something we should probably be doing in the core.

**Comment by lefuentes** [comment]
It's an example when models doesn't reset de errors.

Test Class: 
https://pastebin.pl/view/80e85853

Controller Class:
https://pastebin.pl/view/4586b4b0

If it's necessary I upload more files.
