### ISSUE TITLE
Bug: When have multi filter class, and "before" function return true，other filters after this filter not working

### ISSUE THREAD

**Issue by Hermit-xx** [codeigniter4/CodeIgniter4#3579]
**CodeIgniter 4 version**
4.0.4

Sometimes I want to use "return true" in filter's "before" function to termination function continues to running. But if a filter use 'return true", and this filter is not the last, the filters after this are not working.

**Here some test code:**
/app/Config/Filters.php
``` 
public $aliases = [
        't1' => \App\Filters\Test1::class,
        't2' => \App\Filters\Test2::class
	];
public $globals = [
	'before' => ['t1', 't2'],
	'after'  => ['toolbar'],
];
```
/app/Filters/Test1.php
```
    public function before(RequestInterface $request, $arguments = null)
    {
        var_dump('test1111');
        return true;
    }
```
/app/Filters/Test2.php
```
    public function before(RequestInterface $request, $arguments = null)
    {
        var_dump('test222');
    }
```

Test1 is working but Test2 not working. I read the code, maybe the reason is here:
/system/Filters/Filters.php :190
```
if (empty($result))
{
	continue;
}

return $result;
```
When "before" return true, "continue" not working.  **so i try to return null or return false in "before" function, after filter is working.**
This may not be a bug, I hope this situation can be explained in the document.

**Comment by MGatner** [comment]
The docs state:

> you may at times want to stop the actions in the controller from happening. You can do this by passing back anything that is not the request object

But as you pointed out this is incorrect - it actually needs to pass back something something "empty" in order for the rest of the filters to run. For your case I would recommend returning the Request object, since that's the "default" return value for a successful filter. But we should definitely update the User Guide to be consistent with the code.

**Comment by 326214730** [comment]
I see, thanks for your advice,  I'll try it. : )

**Comment by element-code** [comment]
Sometimes running a after filter would be usefull, e.g. when returning a 429 from the rate limiter and using a after filter to detect empty response body + error http code to display a custom error page.
