### ISSUE TITLE
Bug: CURL call returns always code 200 in case de server uses HTTP/2

### ISSUE THREAD

**Issue by JanZelenka** [codeigniter4/CodeIgniter4#3586]
When making a curl call using the CURLRequest class and the server is IIS using the HTTP 2.0 protocol, the first header starts with "HTTP/2 "
The file CURLRequest.php contains this regex parsing on line 598:
`preg_match('#^HTTP\/([12]\.[01]) ([0-9]+) (.+)#', $header, $matches);`

This fails to parse. It would work if the server used HTTP/2.0 but unfortunately, IIS says HTTP/2.
As a result, no status code is retrieved and CodeIgniter probably somewhere down the way decides it's 200.
 
*CodeIgniter 4 version:* **4.0.4**
*Affected module(s):* CURLRequest
*Context: * **IIS**

**Comment by JanZelenka** [comment]
I did have a look at this and did some testing. This what I believe is the correct regex expression:
#^HTTP\/([12](?:\.[01])?) ([0-9]+) (.+)#

**Comment by MGatner** [comment]
Thanks! Would you submit a Pull Request with your update regex?

**Comment by JanZelenka** [comment]
I will try. Right now I'm quite under pressure from the actual commercial project and when I look at the process of correctly submitting a pull request, it takes more time than I have with the required test cases and so...

**Comment by MGatner** [comment]
I totally get it. Do what you can. I think in this case you could probably just edit the files right in GitHub: submit the updated regex and then add to https://github.com/codeigniter4/CodeIgniter4/blob/develop/tests/system/HTTP/CURLRequestTest.php a copy of `testResponseHeaders()` with the shortened header.
