### ISSUE TITLE
Bug pars xml

### ISSUE THREAD

**Issue by demortx** [codeigniter4/CodeIgniter4#3588]
https://github.com/codeigniter4/CodeIgniter4/blob/f7dfb404fdd7bf7360fb4cab7f661527149dd157/system/Format/XMLFormatter.php#L94

1. arrayToXML(['BBB096630BD' => 'data...'], ...) - Its ok
2. arrayToXML(['096630FR' => 'data...'], ...)         - No ok

The problem with the second example is that it starts with a digit, and passes the check for! is_numeric, and when parsing back into an object, this xml gives an error.

The solution I think is to add a check for the first character not a digit and if a digit then add 'item'

**Comment by paulbalandan** [comment]
Can you try the latest develop version? The code you're referencing is quite outdated.

**Comment by paulbalandan** [comment]
On second look, isn't this the same to your own #3092 ?

**Comment by demortx** [comment]
A new bug got out if by accident xml text comes across in the key, then the parser does not work correctly

return preg_replace('/^(xml).*/iu', 'item$0', $key); // XML is a reserved starting word

Exemple:
arr[
     'XMLtest' => [ ... ]
]

https://github.com/codeigniter4/CodeIgniter4/blob/fc9e219ff74b4ad4835be69cb4af3d839a86eca3/system/Format/XMLFormatter.php#L103

**Comment by paulbalandan** [comment]
> A new bug got out if by accident xml text comes across in the key, then the parser does not work correctly
> 
> return preg_replace('/^(xml).*/iu', 'item$0', $key); // XML is a reserved starting word
> 
> Exemple:
> arr[
> 'XMLtest' => [ ... ]
> ]
> 
> https://github.com/codeigniter4/CodeIgniter4/blob/fc9e219ff74b4ad4835be69cb4af3d839a86eca3/system/Format/XMLFormatter.php#L103


A user provided key cannot start with XML, regardless of case, because it is a reserved word for the XML specification. In this case, `item` will be prepended to the key so that it will cause an error.

Your example is covered by the test case. Please look at the data provider.
