### ISSUE TITLE
Bug: Segments Also Include The Segments In BASE_URL

### ISSUE THREAD

**Issue by SyedMuradAliShah** [codeigniter4/CodeIgniter4#3594]
**Description**
The issue is in the segments also It also focus on the segments in the base_url.  Let me explain it a little bit more, 
My base_url is: http://localhost/pep_digital
My current_url is: http://localhost/pep_digital/dashboard

```
$uri = new \CodeIgniter\HTTP\URI(current_url(true));
print_r($uri->getSegments());
```
Its output is:
Array ( [0] => pep_digital [1] => dashboard )

`print_r($uri->getSegment(1));`

Its output is:
pep_digital 

Well in the CodeIgniter 3, `$this->uri->segment(1)` it was the dashboard.

It is the issue all users will face when the project is inside the sub-folder. The segments should exclude the segments in base_url.

**CodeIgniter 4 version**
4.0.4
 
**Affected module(s)**
\system\HTTP\URI.php

**Context**
- Windows 10
- PHP version 7.2.19

**Comment by MGatner** [comment]
Can you confirm this is still an issue against the latest code on the `develop` branch? I suspect it is, as the original intent may have been this way, but it will help with discerning what to do.

**Comment by SyedMuradAliShah** [comment]
Yes it is in the latest branch, btw I tried it the following code 

```
        $request = \Config\Services::request();
        $request->uri->getSegments();
        $request->uri->getSegment(1);
```
For URL: http://localhost/pep_digital/dashboard

And the output is:
Array ( [0] => dashboard )  dashboard

**Comment by michalsn** [comment]
This seems like a bug. But keep in mind that `URI` class has no knowledge about your `baseUrl`. It will parse whatever URL you will provide and as you showed it will be parsed correctly.

You should rather use something like below, because this way (after this bug will be fixed) information about `baseUrl` will propagate correctly.
```php
$uri = current_url(true);
d($uri->getSegments());
```
