### ISSUE TITLE
Bug: Database cache not working

### ISSUE THREAD

**Issue by MichalPB1** [codeigniter4/CodeIgniter4#3597]
I not sure if a database cache is implemented in CI 4. I have sets `cache` on `true` and `cacheDir` for an already exists directory but still not working.

I looked for using that configuration in the system and I found only a definition of these variables in `system/Database/BaseConnection.php` but nothing more.

**Context**
 - OS: Linux
 - Web server PHP local
 - PHP version 7.3

**Comment by michalsn** [comment]
Sorry, but there is no cache built-in for the database layer and definitely there won't be any. Please use the `Cache` class instead.

But you have a fair point here - we probably should clean this up as these are leftovers from the CI3 rewrite. I think I will leave this open just so we don't forget about this.

**Comment by MichalPB1** [comment]
Ok, so docs should be also fixed.

Can I found some documentation of using Cache for Model?

**Comment by michalsn** [comment]
Basically there is no difference between using the Cache class in or outside the model.
