### ISSUE TITLE
$_SERVER should not have .env file info

### ISSUE THREAD

**Issue by Instrye** [codeigniter4/CodeIgniter4#3615]
https://github.com/codeigniter4/CodeIgniter4/blob/473a8f54e68b1743557f459d11bcab3673669a2a/system/Config/DotEnv.php#L151-L154

Usually, we set the database password in the .env file, the security encryption string.
If $_SERVER have this info. It will become unsafe.
If the programmer forgets to delete the debugging information, the information will be exposed.

example:
![image](https://user-images.githubusercontent.com/9927289/92374930-0784ef00-f133-11ea-9342-1838e64793ae.png)

**Comment by michalsn** [comment]
I'm not sure if I'm following - do we store `$_SERVER` variables somewhere automatically? What debugging options do you have in mind?

**Comment by Instrye** [comment]
@michalsn 
I mean, $_SERVER should not contain .env information.
.env often contains sensitive information.
If the system has some vulnerabilities, only need to print $_SERVER, important information such as database password will be exposed.
