### ISSUE TITLE
Bug: getHeaders returns Array with no values

### ISSUE THREAD

**Issue by milaan-muc** [codeigniter4/CodeIgniter4#3616]
Hi!

Yesterday i started a new project with CI4 and tried to implement a webhook with GitLab where i get a post to my CI installation when the repository has changes.

My problem is that the `$request->getHeaders()` function is returning an Array and i can see the fields but they are all empty.
The native php function `getallheaders()` returns everything.

Here is the debug output. First the CI function, second line the php function.

```
DEBUG - 2020-09-07 19:48:00 --> {"Content-Type":{},"Content-Length":{},"Host":{},"Connection":{},"X-Gitlab-Token":{},"X-Gitlab-Event":{}}
DEBUG - 2020-09-07 19:48:00 --> {"Content-Length":"1774","Host":"domain.local","Connection":"close","X-Gitlab-Token":"1234567890","X-Gitlab-Event":"Push Hook","Content-Type":"application\/json"}
```
My Controller:

```
<?php namespace App\Controllers;
use CodeIgniter\HTTP\Header;
class Home extends BaseController
{
public function git()
	{
		shell_exec('cd /srv/domain.local/ && git reset --hard HEAD && git pull && git pull');
		$header_ci = json_encode($this->request->getHeaders());
		$header_native = json_encode(getallheaders());
		log_message('debug', $header_ci);
		log_message('debug', $header_native);
	}
}
```

**Comment by michalsn** [comment]
The thing is that `getHeaders()` method returns an array of `Header` objects. So it can't be converted just like that. You need to use something like:
```php
$headers = array_map(function($header) { 
	return $header->getValueLine(); 
}, $this->request->getHeaders());
```
This way you gonna get the `key => string value` array of headers. 

Maybe it's a good idea to prepare an additional method, like `getHeadersArray()` to make that easier.
