### ISSUE TITLE
Files as optional in validation rules

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#3619]
Applying the permit_empty rule within the validation of a file does not work correctly as it completely ignores the validation if the user uploads a file 
```php
$rules['fotos.*'] = [
    'rules' => 'permit_empty|uploaded[field]|max_size[field,500]|is_image[field]',
];
```
Another method that could also be useful is to restrict the number of files that a user can upload in the case of using multiple files `max_files[field, 3]` or a minimum of `min_files[field, 2]`

grettings

**Comment by Instrye** [comment]
Since the value of a file upload HTML field doesn’t exist. 
So, 'permit_empty' always return true.

**Comment by crustamet** [comment]
this is not a bug some validations are for $_POST, and some are for $_FILES don`t use them together.

just don`t use the uploaded[field] rule if you don`t want it to be required

**Comment by michalsn** [comment]
In the user guide, we have separate sections for file uploads related rules.

The idea with the validation rule for `max` and `min` number of files sounds good. PRs are welcomed, as always.
