### ISSUE TITLE
Bug: Target batch not found when running `php spark migrate:rollback`

### ISSUE THREAD

**Issue by yassinedoghri** [codeigniter4/CodeIgniter4#3620]
**Describe the bug**
When running a migration rollback through the spark command `php spark migrate:rollback`, an exception is thrown:

```
> php spark migrate:rollback

CodeIgniter v4.0.4 Command Line Tool - Server Time: 2020-09-08 09:13:36 UTC+00:00

Rolling back migrations to batch:  1
An uncaught Exception was encountered

Type: RuntimeException
Message: Target batch not found: 1
Filename: /vendor/codeigniter4/codeigniter4/system/Database/MigrationRunner.php
Line Number: 305
    Backtrace:
           -127 - /vendor/codeigniter4/codeigniter4/system/Commands/Database/MigrateRollback.php::regress
           -100 - /vendor/codeigniter4/codeigniter4/system/CLI/Commands.php::run
           -108 - /vendor/codeigniter4/codeigniter4/system/CLI/CommandRunner.php::run
           -86 - /vendor/codeigniter4/codeigniter4/system/CLI/CommandRunner.php::index
           -961 - /vendor/codeigniter4/codeigniter4/system/CodeIgniter.php::_remap
           -449 - /vendor/codeigniter4/codeigniter4/system/CodeIgniter.php::runController
           -357 - /vendor/codeigniter4/codeigniter4/system/CodeIgniter.php::handleRequest
           -86 - /vendor/codeigniter4/codeigniter4/system/CLI/Console.php::run
           -57 - /spark::run
```

**CodeIgniter 4 version**
Latest `develop`

**Affected module(s)**
`./system/Database/MigrationRunner.php`

**Expected behavior, and steps to reproduce if appropriate**
Should rollback database migration. Updated codeigniter4 from 9a7e826138bf8940ef8c7a25d59d67b1aebfe0ee where it works fine.

**Context**
 - OS: Debian GNU/Linux 10 (buster)
 - Local dev server with spark
 - PHP version 7.2

**Comment by paulbalandan** [comment]
I can't reproduce this. Using the latest develop [`9b6eda`](https://github.com/codeigniter4/CodeIgniter4/commit/9b6eda2729d4a8912ccfe8f8c20587b21ff92ac4).

I used SQLite3 as driver. Then used default test migration script as is.

`php spark migrate:status`
```
CodeIgniter v4.0.4 Command Line Tool - Server Time: 2020-09-08 07:02:50 UTC-05:00

App
  Filename              Migrated On: 
  Create_test_tables    ---
```

`php spark migrate`
```
Running all new migrations...
        Running: (App) 20160428212500_Tests\Support\Database\Migrations\Migration_Create_test_tables
Done migrations.
```

`php spark migrate:status`
```
CodeIgniter v4.0.4 Command Line Tool - Server Time: 2020-09-08 07:04:12 UTC-05:00

App
  Filename              Migrated On: 
  Create_test_tables    2020-09-08 07:03:41
```

`php spark migrate:rollback`
```
CodeIgniter v4.0.4 Command Line Tool - Server Time: 2020-09-08 07:04:39 UTC-05:00

Rolling back migrations to batch:  0
        Rolling back: (App) 20160428212500_Create_test_tables
Done
```

**Comment by yassinedoghri** [comment]
Sorry, I don't know if it helps but I didn't specify the db driver: I'm using `MySQLi` as driver.

I've dug into the code and have some insights that might help.
The problem is in `/system/Database/MigrationRunner.php`, line 296:
```php
if ($targetBatch !== 0 && ! in_array($targetBatch, $batches, true))
```
The condition checks whether the `$targetBatch` exists in the `$batches` array with the strict param to `true`. By setting the strict param to `false`, the rollback worked.

So, I've checked the `$targetBatch` type and the types of the values in `$batches` using CLI::write().

```php
CLI::write('TargetBatch: ' . gettype($targetBatch)); // TargetBatch: integer
CLI::write('In batch array: ' . gettype($batches[0])); // In batch array: string
```

The types do not match so the condition passes and an exception is thrown (line 305).
In `/system/Database/MigrationRunner.php`, line 842, the `getBatches()` method returns an array of strings.

Can it be something on my side? It's quite weird that having a previous version of the devlop branch (9a7e826138bf8940ef8c7a25d59d67b1aebfe0ee) just works fine.

**Comment by michalsn** [comment]
@yassinedoghri Thank you for investigating this.
