### ISSUE TITLE
Migration trouble 

### ISSUE THREAD

**Issue by 24edukasi** [codeigniter4/CodeIgniter4#3624]
Hi there, 
any body know, what this is thing......
please help me
CI 4.0.4

![Capture](https://user-images.githubusercontent.com/58927337/92563821-60bf6080-f2a2-11ea-8d29-92098af464e9.PNG)

**Comment by hkhairinas** [comment]
looks like your sql files, that have an error near 'l at line 10 ?

**Comment by 24edukasi** [comment]
> looks like your sql files, that have an error near 'l at line 10 ?

i am no have/make sql files at all.....???

**Comment by hkhairinas** [comment]
> 
> 
> > looks like your sql files, that have an error near 'l at line 10 ?
> 
> i am no have/make sql files at all.....???

you are trying to migrate the database into your project right?
the sql file should be on your app/database/migrations.
correct me if i am wrong.

**Comment by michalsn** [comment]
@24edukasi Hmm... it looks like the query responsible for creating a table with `migrations` table is failing. I don't think we've made any changes there recently. You may try to update to the dev branch and run it again - if you installed CI4 via composer then run `php builds development` and then `composer update` to get the latest dev changes.

From what I checked the produced query look like this:
```sql
CREATE TABLE IF NOT EXISTS `migrations` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`version` VARCHAR(255) NOT NULL,
	`class` TEXT NOT NULL,
	`group` VARCHAR(255) NOT NULL,
	`namespace` VARCHAR(255) NOT NULL,
	`time` INT(11) NOT NULL,
	`batch` INT(11) UNSIGNED NOT NULL,
	CONSTRAINT `pk_migrations` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;
```
So you can try to run this SQL directly in your database client and check if there are any errors.

**Comment by 26Piedrosa** [comment]
Check your migration code

**Comment by paulbalandan** [comment]
@24edukasi are you still experiencing this issue?

**Comment by aqilfiqran** [comment]
> Hi there,
> any body know, what this is thing......
> please help me
> CI 4.0.4
> 
> ![Capture](https://user-images.githubusercontent.com/58927337/92563821-60bf6080-f2a2-11ea-8d29-92098af464e9.PNG)

check ur migration file. there is invalid syntax in there?

**Comment by paulbalandan** [comment]
I guess this is not an issue with the framework and no response has been received from OP if this is still an issue. Closing this, but reopen if the problem still persists.
