### ISSUE TITLE
Bug: Cannot use view filter on array values

### ISSUE THREAD

**Issue by element-code** [codeigniter4/CodeIgniter4#3630]
When trying to use a custom [view Filter](https://codeigniter.com/user_guide/outgoing/view_parser.html#filters) for array values nothing happens.

**Affected module(s)**
[`View\Parser` ](https://github.com/codeigniter4/CodeIgniter4/blob/50f5548fe50af5fec69bbfecb6b4c3f525f38916/system/View/Parser.php#L306)

**Expected behavior, and steps to reproduce if appropriate**
`{foo|bar}` should always lead to the call of the filter `bar` no matter what type `foo` is. Right now nothing happens since [`$replace`](https://github.com/codeigniter4/CodeIgniter4/blob/50f5548fe50af5fec69bbfecb6b4c3f525f38916/system/View/Parser.php#L316) will not contain `{foo|bar}`.

**Comment by michalsn** [comment]
Sorry, but `Parser` class is designed to work only with associative arrays. And filters work only for a single variable not array.

We are always open to a PRs though.
