### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by nicojmb** [codeigniter4/CodeIgniter4#3640]
**Describe the bug**
I've a LanguageFilter wiht method "before" to check session value and set current languange with method setLanguage($locale) in the codigniter request classs.

In debug toolbar the the laguage is correct but translations show incorrect language (when i use lang() always return default language translation).

the problem only happens when i've an lang() function call before the request()->setLocale($language) and static service language not update when run setLocale($locale) and return next translation with default locale.

![image](https://user-images.githubusercontent.com/5610392/93019507-b31cbc00-f5d7-11ea-949c-f691b1801087.png)

![image](https://user-images.githubusercontent.com/5610392/93019514-b9ab3380-f5d7-11ea-8285-ea6ba059175f.png)

The translation files are correct, if i change default language to english, showme "logout" twice :(

![image](https://user-images.githubusercontent.com/5610392/93019550-0a229100-f5d8-11ea-8f27-93f3f2209d8f.png)

If i comment the first lang() then works as expected.

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
Language Helper 
Language Service

**Expected behavior, and steps to reproduce if appropriate**
lang() function get correct translation after "setLocale" function.

**Context**
 - OS: Centos
 - Web server: Nginx
 - PHP version: 7.4.10

**Comment by michalsn** [comment]
This is not a bug. When we call `lang()` function for the first time we simply initialize the shared `language` service. The next call to `lang()` operates on the same instance as before so that's why there is no change - despite changing the locale for the request.

You should use `service('language')->setLocale($lang)` instead.

**Comment by nicojmb** [comment]
Great, i try and works, boy also needs to call "service('request')->setLocale($lang);" to update request current language if not the debug toolbar showme incorrect language buy translations works.

My code now looks like this:

```
service('language')->setLocale($language);
service('request')->setLocale($language);
```

And works as spected, thankyou so much @michalsn
