### ISSUE TITLE
Bug: getRoutesOptions return wrong when I have >2 routes has same name, but different method (HTTPVerb)

### ISSUE THREAD

**Issue by mrhung** [codeigniter4/CodeIgniter4#3700]
//my routes

`$routes->get('product/add', 	'App\Product::add', ['as' => 'app_product_add']);`
`$routes->post('product/add', 'App\Product::add_ajax', ['as' => 'app_product_add_ajax']);`

//my function 
`$router  = \Config\Services::router();`
`$match  = $router->getMatchedRoute(); // => IT'S OK`
`$options = $router->getMatchedRouteOptions(); //=> WRONG BY METHOD`

$options alway is: `['as' => 'app_product_add_ajax']`
I want setMethod() and default method by current request in here for return right options

How can't I hot fix this bug?

Help me.
Thanks

**Comment by crustamet** [comment]
Yes i had this problem also.
It would have been nice if the system differentiate this methods in the routes also.

Because of this i changed all my segments routes to not be the same as GET and POST

ex : 

get('product/add')
post('product/submit_add')
