### ISSUE TITLE
Bug: view caching not work on windows

### ISSUE THREAD

**Issue by paul45** [codeigniter4/CodeIgniter4#3711]
The cache file does not creating when i don't set cache_name option 

i have see issue #2821 and i think it is the same issue

on windows and with CI 4.0.4

**Comment by paulbalandan** [comment]
Can you provide your code where the caching didn't work? It has been fixed in #2821 so there may be something peculiar to your code that causes the problem.

**Comment by paul45** [comment]
sorry my issue isn't clear

this code don't create cache
`<?php $this->extend('templates/theme_bs'); ?>
<?= $this->section('content') ?>
            <?= $this->include("templates/slider",['cache' => 86400]) ?>
<?= $this->endSection()  ?>`


and this code create cache
`<?php $this->extend('templates/theme_bs'); ?>
<?= $this->section('content') ?>
            <?= $this->include("templates/slider",['cache' => 86400, 'cache_name' => 'slider']) ?>
<?= $this->endSection()  ?>`
