### ISSUE TITLE
Bug: Validating Json Requests

### ISSUE THREAD

**Issue by caswell-wc** [codeigniter4/CodeIgniter4#3719]
**Describe the bug**
When building a json API, the Controller::validate function does not work because the data from the json sent to the request is not being loaded correctly.

**CodeIgniter 4 version**
CodeIgniter 4.0.4

**Affected module(s)**
Validation

**Expected behavior, and steps to reproduce if appropriate**
1. Create a controller endpoint for accepting the request
2. In the endpoint use this function call `$this->validate(['username' => 'required|alpha_dash')` to validate your request
3. Send `{"username": "test"}` to the endpoint
4. I would expect this to pass the validation but it is saying that username is missing.

**Context**
 - OS: CentOS7
 - Web server: Apache 2.4.6
 - PHP version: 7.2.24

**Comment by ian-hubbard-alcolizer** [comment]
I'm not sure if this should be re-opened or a new bug created but I've implemented this change and discovered it doesn't work out-of-the-box with the Axios library as the content type being sent is: `application/json;charset=UTF-8`

Which fails the test: `$this->getHeader('Content-Type')->getValue() === 'application/json'`
