### ISSUE TITLE
page not  redirecting. when i redirecting by calling function

### ISSUE THREAD

**Issue by khushmohammad** [codeigniter4/CodeIgniter4#3729]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**

**CodeIgniter 4 version**
Which version (and branch, if applicable) the bug is in.

**Affected module(s)**
Which package or class is the bug in, if known.

**Expected behavior, and steps to reproduce if appropriate**
A clear and concise description of what you expected to happen,
and how you got there.  
Feel free to include a text/log extract, but use a pastebin facility for any
screenshots you deem necessary.

**Context**
 - OS: [e.g. Windows 99]
 - Web server [e.g. Apache 1.2.3]
 - PHP version [e.g. 6.5.4]

**Comment by khushmohammad** [comment]
public function checksession(){
			$userId = session()->has('name');			
			if (!$userId) { return redirect()->to(base_url()); }
			
			
	}
	public function index()
	{		
			$this->checksession();
			echo view('Header');
			echo view('Dashboard/Home');
			echo view('Dashboard/footer');
		
	}

**Comment by lonnieezell** [comment]
Not a bug. 

You're not returning the RedirectResponse to the calling method, but not returning it out of the `index()` method itself. Read up on [controller filters](https://codeigniter.com/user_guide/incoming/filters.html) for a better solution.
