### ISSUE TITLE
Bug: route bug

### ISSUE THREAD

**Issue by SyedMuradAliShah** [codeigniter4/CodeIgniter4#3731]
**Describe the bug**
There is a bug while defining *as* in the route.  When I use 
`$routes->add('admins/suspend/(:num)', 'AdminsController::suspend/$1', ['as' => 'suspend_admin']);`
It give me error exception, 
```
Undefined offset: 0
SYSTEMPATH\Router\RouteCollection.php at line 1347
```
When I change `['as' => 'suspend_admin']` to `['as' => 'suspends_admin']` or to anything its working.

Please check this, why it don't accept suspend_admin? 

**Added errorHandler ( arguments )**
```
Array
(
    [from] => dashboard/admins/suspend/([0-9]+)
    [params] => Array
        (
        )

    [matches] => Array
        (
            [0] => Array
                (
                    [0] => ([0-9]+)
                )

            [1] => Array
                (
                    [0] => [0-9]+
                )

        )

    [pattern] => ([0-9]+)
    [index] => 0
)
```

**Error generating**
The error is only generate when I use `base_url(route_to('suspend_admin') )`.  It looks like the issue is because of the dynamic argument.

When I remove `(:num)` the issue becomes to fix.

**CodeIgniter 4 version**
- 4.0.4

**Affected module(s)**
Route

**Context**
- OS: Window 10
- Apache 2.4.46
- 7.4.10

**Comment by InsiteFX** [comment]
route_to takes a controller/method you should not need the base_url() try it without the base_url.

**Comment by michalsn** [comment]
Please read how to use `route_to()` function in the [user guide](https://codeigniter4.github.io/CodeIgniter4/general/common_functions.html#route_to). 

Basically, if you define a parameter in your URL, then you have to apply it to the function. In your case, something like this should work: `route_to('suspend_admin', 123)`.
