### ISSUE TITLE
Fabricators documentation error

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#3743]
In the example where they show the `getCount` functionality, I think there is an error in the code since the table where it should get the random `id` is from groups, not from users

```php
class UserModel
{
    protected $table = 'users';

    public function fake(Generator &$faker)
    {
            return [
            'first'    => $faker->firstName,
            'email'    => $faker->email,
            'group_id' => rand(1, Fabricator::getCount('groups')), // <---- 
            ];
    }
```

https://codeigniter.com/user_guide/testing/fabricator.html#table-counts

**Comment by paulbalandan** [comment]
I think @MGatner  can answer that.

**Comment by MGatner** [comment]
You are absolutely correct! I will patch that.
