### ISSUE TITLE
Bug: createTable if not exists not working

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3757]
**Direction**

	class AddTest extends Migration
	{
		public function up()
		{
			$primary_key = [
				'type'           => 'INT',
				'constraint'     => 5,
				'unsigned'       => true,
				'auto_increment' => true,
			];
			
			$title = [
				'type'           => 'VARCHAR',
				'constraint'     => '100',
			];
			
			$this->forge->addField([
				'id' => $primary_key,
				'test' => $title
			]);
			
			$this->forge->addKey('id', true);
			$this->forge->createTable('test', TRUE); 
			// HERE SECOND ARGUMENT is TRUE to create if not exists statement
		}

		public function down()
		{
			$this->forge->dropTable('test');
		}
	}

**Describe the bug**
I still receive the error table already exists
When i check the SQL the statement "IF NOT EXISTS" does not appear in the SQL

I checked the code

**CodeIgniter 4 version**
Latest

**Expected behavior, and steps to reproduce if appropriate**
This should not give an error and instead should prepend the "IF TABLE NOT EXISTS" statement when try to create table

**Comment by MGatner** [comment]
Please specify which database driver and, if you've only tested one and are able, please test others.

**Comment by crustamet** [comment]
oh Yes sorry, i forgot about the driver, i am using MySQL

**Comment by crustamet** [comment]
Sorry i made a mistake, everything works fine as intended.
