### ISSUE TITLE
Bug:  CLI: Exception view shows full path

### ISSUE THREAD

**Issue by element-code** [codeigniter4/CodeIgniter4#3763]
Like the debug toolbar, the exception view in the cli should also replace the `APP` & `SYSTEM` paths.
This
- makes them easier to read
- saver to share

**CodeIgniter 4 version**
`4.0.4`

**Comment by paulbalandan** [comment]
Please use the `develop` branch. The CLI `error_exception` file is updated already.

**Comment by paulbalandan** [comment]
See #3367

**Comment by element-code** [comment]
Sorry, didn't see that.
