### ISSUE TITLE
Bug: Model update() only set first array value

### ISSUE THREAD

**Issue by andresyebenes** [codeigniter4/CodeIgniter4#3764]
**Describe the bug**
When updating a Model with more than 1 array values, it only updates the first value (for first column) in the database.

**CodeIgniter 4 version**
CodeIgniter 4.0.4

**Affected module(s)**
CodeIgniter\Model

**Expected behavior, and steps to reproduce if appropriate**
Code used from the Controller:
```
$db = \Config\Database::connect();
$data = [
    'is_allowed' => 1,
    'is_dismissed' => 0
];
$questionsModel = new \App\Models\QuestionsModel();
$questionsModel->update(intval($id), $data);

d($data);
d($db->getLastQuery()->getQuery());
```

And:

```
$db = \Config\Database::connect();
$questionsModel = new \App\Models\QuestionsModel();
$questionsModel->where('id', $id)
        ->set($data)
        ->update();

d($data);
d($db->getLastQuery()->getQuery());
```

Both methods for updating mutiple columns are printing this query;
`UPDATE questions SET is_allowed = 1, updated_at = '2020-10-13 12:17:50'
WHERE questions.id IN (1)`

And:

`UPDATE questions SET is_allowed = 1, updated_at = '2020-10-13 12:17:50'
WHERE id = '1'`

Expected query should be:
`UPDATE questions SET is_allowed = 1, is_dismissed = 0, updated_at = '2020-10-13 12:17:50'
WHERE id = '1'`

**Context**
 - OS: Linux
 - Web server Apache 2
 - PHP version: PHP 7.4.6

**Comment by michalsn** [comment]
Are you sure you added `is_dismissed` to the Model's `$allowedFields` array?

**Comment by andresyebenes** [comment]
Well, you're right, I didn't add it to $allowedFields.

Thank you!
