### ISSUE TITLE
Restore method for CodeIgniter Model.

### ISSUE THREAD

**Issue by enix-app** [codeigniter4/CodeIgniter4#3767]
I think the CodeIgniter\Model needs ``restore`` method to restore the trashed item.

```php
$user = new UserModel;

$user
	->where('id', $id)
	->set([
		'deleted_at' => null,
	])
	->update()
;
```

Because there are ``withDeleted()``, ``OnlyDeleted()``, ``purgeDeleted()`` methods.
I want to create my custom CRUDR library, but I'm lazy to extends ``CodeIgniter\Model`` to add ``restore()`` and ``restoreAll()``.

Just an idea. Thanks!

**Comment by paulbalandan** [comment]
Please feel free to open a PR.

**Comment by aqilfiqran** [comment]
Nice idea
