### ISSUE TITLE
The page does not open correctly:(

### ISSUE THREAD

**Issue by webroman** [codeigniter4/CodeIgniter4#3770]
I have a page on codeignater 4. In the browser, the page opens correctly, but when I redirect to this page, the 404 page opens, and then if I refresh the page again, then it loads again correctly. Why could this be? 

also if I send a request to the page with ajax, then 404 opens, and it works correctly in the browser

My routes:
$routes->get('page2101', 'page::page2101');

My controller "Page"

public function page2101() {
echo 'Hello World!';
}

**Comment by paulbalandan** [comment]
Can you provide the code where the redirection is occurring?

In my test code, I am returning a redirect to `page2101` and it works. Don't know how it doesn't work for you. If you can provide more code, that would be better.

**Comment by paulbalandan** [comment]
This was raised in the forum so I assume this is not a bug but an error in user implementation.
