### ISSUE TITLE
Bug: Validation: Placeholder replacement not working for complex validation rules

### ISSUE THREAD

**Issue by element-code** [codeigniter4/CodeIgniter4#3774]
When using the following Syntax for the rules, `Validation::fillPlaceholders()` cant find the rules and fails to replace any placeholders
```php
$rules = [
	'email' => [
		'rules' => ['required', 'trim', 'valid_email', 'max_length[191]', 'is_unique[users.email, id, {id}]'],
	]
]
```

`Validation::run()` handles this for the validation itself:
https://github.com/codeigniter4/CodeIgniter4/blob/b8ad7782ab91be361a3ec3501b1ecf0c20b99023/system/Validation/Validation.php#L172-L173

PR Incomming

**Comment by kenjis** [comment]
It seems the way to set rules with array is not documented.
Am I overlooked it?
