### ISSUE TITLE
The formatMessage function of the Language class works intermittently

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#3784]
Currently I uploaded my application to my remote server, I am using the `humanize()` function from the library Time, Curiously in my local server if it works correctly and in my remote server it cannot show the messages :(

I was researching the code of CI4 and I found that it uses the function `formatMessage()` of the php intl extension to generate the format of the strings passing the calculated time and the patterns as a reference

when performing a test on my remote server I observe that it does not show the messages of humanize () because the function `` returns false even though the intl extension is enabled
```php
// file: system\Language\Language.php 
// line: 274
return \MessageFormatter::formatMessage($this->locale, $message, $args);
```

What are you thinking about? Should a fix be applied to the language files pattern or should I consider updating the version of intl on my server?

I leave the configurations of my local server where it works correctly and of my remote server

local:
![imagen](https://user-images.githubusercontent.com/4117596/96352597-fdd39d00-1089-11eb-8f4a-98ae978c1e97.png)

remote server.
![imagen](https://user-images.githubusercontent.com/4117596/96352605-0a57f580-108a-11eb-98c4-b66513b2293d.png)

Cheers!

**Comment by michalsn** [comment]
This is a native PHP class so if something doesn't work on your production setup, I would recommend updating it (seems like it's really outdated).

**Comment by luispastendev** [comment]
ty michalsn i will update the extension
