### ISSUE TITLE
Bug: Class '\CodeIgniter\Database\pdo\Connection' not found 

### ISSUE THREAD

**Issue by Guilherme-fagundes** [codeigniter4/CodeIgniter4#3785]
The framework does not connect with the Driver PDO
`
public $default = [
		'DSN'      => 'mysql:host=localhost;dbname=sistemalogin',
		'hostname' => '',
		'username' => 'root',
		'password' => '',
		'database' => 'sistemalogin',
		'DBDriver' => 'pdo',
		'DBPrefix' => '',
		'pConnect' => false,
		'DBDebug'  => (ENVIRONMENT !== 'development'),
		'cacheOn'  => false,
		'cacheDir' => '',
		'charset'  => 'utf8',
		'DBCollat' => 'utf8_general_ci',
		'swapPre'  => '',
		'encrypt'  => false,
		'compress' => false,
		'strictOn' => false,
		'failover' => [],
		'port'     => 3306,
	];
`

**Comment by samsonasik** [comment]
Please read user guide for PDO configuration https://codeigniter.com/user_guide/database/configuration.html?highlight=pdo

**Comment by michalsn** [comment]
@Guilherme-fagundes There is no PDO support yet. You have to use a native driver: `MySQLi`.
