### ISSUE TITLE
Blank page show

### ISSUE THREAD

**Issue by RakibN** [codeigniter4/CodeIgniter4#3812]
When uploaded on the server my project blank page shows.
public folder all fille move to root file then 
App.php file chance public $baseURL = 'http://truequery.xyz/vsn/';
env file rename to .env and #CI_ENVIRONMENT = production chance to CI_ENVIRONMENT = development
db
 database.default.hostname = localhost
database.default.database = truequer_news
database.default.username = truequer_new
database.default.password = XrFrhz3.]i]n
database.default.DBDriver = MySQLi
then  index.php $pathsPath = FCPATH . '../app/Config/Paths.php';   chance to $pathsPath = FCPATH . 'app/Config/Paths.php';
 blank page show how can solve it?

**Comment by paulbalandan** [comment]
What CI version are you using? Did you check your php.ini if the zlib.output_compression is turned on? Does the server have the php intl extension installed?

**Comment by RakibN** [comment]
Version 4.0.2 ... I upload my project shared hosting. how can check my server php intl extension

**Comment by paulbalandan** [comment]
Is it feasible for you to upgrade to at least 4.0.4? In there there is a check against blank pages.

If you have access to the terminal in the server, you can try `php --ri intl`. Or if this is shared hosting, you can ask the provider where is your own php.ini or if intl is installed.
