### ISSUE TITLE
Translation function 'lang' does not work as described

### ISSUE THREAD

**Issue by vonboth** [codeigniter4/CodeIgniter4#3822]
In the documentation you are describing the lang function to work this way:
```
// Displays "£7.41"
echo lang('{price, number, currency}', ['price' => 7.41], 'en-GB');
```

However this doesn't work in the current release (4.0.4).

It just echos the string: {price, number, currency}

If I comment out the lines 140 - 143 inside the file framework/system/Language/Language.php
```
// ignore requests with no file specified
		/*if (! strpos($line, '.'))
		{
			return $line;
		}*/
```

it works as described and the output is: £7.41

**Comment by paulbalandan** [comment]
I believe this is more of a documentation issue than a bug in the code. The `lang` function is intended to work with language strings inside files which are loaded by the function.

**Comment by vonboth** [comment]
Is that so?
It would be much more comfortable (and makes more sense for me) if it would work as described in the documentation and not in the way that every string has to be a language file.

However either this or that needs a revision.

**Comment by paulbalandan** [comment]
Per code, the parsing seems to support only file-based language strings. But you are right. The example in the documentation is most appropriate for single uses.

Any thoughts, @MGatner , @michalsn , @samsonasik ?
