### ISSUE TITLE
Bug: Parser - Replacements happening even if key does not fully matches { value }

### ISSUE THREAD

**Issue by eSkiSo** [codeigniter4/CodeIgniter4#3825]
**Describe the bug**
If a key of data array contains the start of the next keys, all of the replacements from then on will be done with the value of this first key, even it not fully matched.

**CodeIgniter 4 version**
4.0.4 (live)

**Affected module(s)**
Parser

**Expected behavior, and steps to reproduce if appropriate**
```php
$parser = \Config\Services::parser();
$data   = [
	'company' => 'Problem',
	'company_name' => 'X Company',
	'company_street' => 'Street Name',
	'company_city' => 'City Name',
	'company_country' => 'England',
];
$template = '<html> {company_name} <br> {company_street} <br>  {company_city} <br>  {company_country} </html>';
$parser->setData($data);
echo $parser->renderString($template);
```
- Current Output
```
Problem
Problem
Problem
Problem 
```
- What was expected
```
X Company
Street Name
City Name
England
```
- Also if the first key on the array is **company_c** instead of **company** this will be the output:
```
X Company
Street Name
Problem
Problem
```

**Context**
 - OS: 18.04.5 LTS
 - Web server: Apache/2.4.29
 - PHP version: PHP 7.4.10

**Comment by paulbalandan** [comment]
This has been fixed in #3749
