### ISSUE TITLE
CodeIgniter\Database\Exceptions\DatabaseException #8

### ISSUE THREAD

**Issue by Jolted98** [codeigniter4/CodeIgniter4#3826]
Hi guys,
I'm facing trouble trying to connect to the database using CodeIgniter 4. I have installed the MySQL extension, I have configured the database in the .env file but I just can't connect to the database for some reason.

**Comment by paulbalandan** [comment]
This should have been raised in the [forums](https://forum.codeigniter.com) instead as this is not a bug report.
