### ISSUE TITLE
Custom rules for the validator error

### ISSUE THREAD

**Issue by demortx** [codeigniter4/CodeIgniter4#3837]
https://github.com/codeigniter4/CodeIgniter4/blob/91f08c4011ddc7526db32fdee7dbbdd76b87fc8a/system/Validation/Validation.php#L319

When creating a custom rule, for example, for processing a multidimensional array

```php
public function valid_list_data(array $array, string $fields, array $data, string &$error = null): bool
    {
        $fields = explode(',',$fields);
        if (is_array($array)){
            foreach ($array as $item){
                foreach ($fields as $field) {
                    if (!isset($item[$field]))
                        return false;
                    if ($item[$field] === ''){
                        return false;
                    }
                }
            }

        }else
            return false;
        
        return true;
    }
```

We set the rules to process the array and check if all the parameters came
'rules' => 'required|valid_list_data[gr,id,count,enc,name,img,chance]',

feeding data
settings[items][1][gr]: 
settings[items][1][id]: 
settings[items][1][count]: 
settings[items][1][enc]: 
settings[items][1][name]: 
settings[items][1][img]: 

we get an error
file: "/var/www/mmoweb.ru/system/Validation/Validation.php"
line: 319
message: "Array to string conversion"

This is due to the fact that implode does not process multidimensional array, how can I fix or work around this?

**Comment by paulbalandan** [comment]
Support questions should be raised in the [forum](forum.codeigniter.com)
