### ISSUE TITLE
Bug: insertBatch not generating createdField

### ISSUE THREAD

**Issue by wiedhodho** [codeigniter4/CodeIgniter4#3838]
when I use insertBatch, the field createdField not generating current date/timestamp

database: mariadb
feature: insertbatch

**Comment by paulbalandan** [comment]
Did you use the `useTimestamps` set to `true`?

**Comment by wiedhodho** [comment]
Yes, I have set $useTimestamps to true, but it still null on database.

**Comment by paulbalandan** [comment]
Please provide your Model code where you are doing the insertBatch.

**Comment by paulbalandan** [comment]
Please confirm if you set the following correctly:

1. $useTimestamps is set to true
2. the $createdField is included in the array of allowedFields
3. the $createdField is set in the database

**Comment by wiedhodho** [comment]
This is my model code
`
protected $table = 'dokumentasi';
	protected $primaryKey = 'dokumentasi_id';

	protected $returnType = 'object';
	protected $useSoftDeletes = true;

	protected $allowedFields = [
		'dokumentasi_program',
		'dokumentasi_user',
		'dokumentasi_foto1',
		'dokumentasi_foto2',
		'dokumentasi_foto3',
	];

	protected $useTimestamps = true;
	protected $createdField = 'dokumentasi_created';
	protected $updatedField = 'dokumentasi_lastupdate';
	protected $deletedField = 'dokumentasi_deleted';

	protected $validationRules = [
		'dokumentasi_program' => 'required',
		'dokumentasi_user' => 'required',
		'dokumentasi_foto1' => 'required',
		'dokumentasi_foto2' => 'required',
		'dokumentasi_foto3' => 'required',
	];
`

**Comment by wiedhodho** [comment]
oh sorry, this is my fault, I forgot to add createdfield into allowedfields

**Comment by wiedhodho** [comment]
this is my model code:

`protected $table = 'data_miskin';
	protected $primaryKey = 'data_miskin_id';

	protected $returnType = 'object';
	protected $useSoftDeletes = true;

	protected $allowedFields = [
		'data_miskin_penerima',
		'data_miskin_kategori',
		'data_miskin_lastupdate',
		'data_miskin_user',
		'data_miskin_program',
	];

	protected $useTimestamps = true;
	protected $createdField = 'data_miskin_created';
	protected $updatedField = 'data_miskin_lastupdate';
	protected $deletedField = 'data_miskin_deleted';

	protected $validationRules = [
		'data_miskin_penerima' => 'required',
		'data_miskin_kategori' => 'required',
		'data_miskin_user' => 'required',
		'data_miskin_program' => 'required',
	];`

**Comment by wiedhodho** [comment]
this is my code:

`protected $table = 'data_miskin';
	protected $primaryKey = 'data_miskin_id';

	protected $returnType = 'object';
	protected $useSoftDeletes = true;

	protected $allowedFields = [
		'data_miskin_penerima',
		'data_miskin_kategori',
		'data_miskin_created',
		'data_miskin_user',
		'data_miskin_program',
	];

	protected $useTimestamps = true;
	protected $createdField = 'data_miskin_created';
	protected $updatedField = 'data_miskin_lastupdate';
	protected $deletedField = 'data_miskin_deleted';

	protected $validationRules = [
		'data_miskin_penerima' => 'required',
		'data_miskin_kategori' => 'required',
		'data_miskin_user' => 'required',
		'data_miskin_program' => 'required',
	];`

**Comment by paulbalandan** [comment]
then, the code how are you inserting to the db?

**Comment by wiedhodho** [comment]
this is the code to insert to the db

`foreach ($json->pilihan as $p) {
				$data[] = [
					'data_miskin_penerima' => $p,
					'data_miskin_kategori' => $json->kategori,
					'data_miskin_user' => 'guest',
					'data_miskin_program' => $json->id,
				];
			}
			$r = $this->model->insertBatch($data);`

**Comment by paulbalandan** [comment]
Reading my emails, I've seen you've originally forgotten to include the created field in the allowed fields. Is your code still doing null inserts after inclusion?

**Comment by wiedhodho** [comment]
at the first code, I have forgot to include createdfield in the allowed field. Then I add the createdfield in the allowed fields, but it still same, the code not generated the timestamp/date in the createdfield with $db->insertBatch();

**Comment by MGatner** [comment]
Created and updated fields do not need to be in allowedFields

**Comment by jahmedk** [comment]
@wiedhodho which data type are you using for 
'data_miskin_created';
'data_miskin_lastupdate';
'data_miskin_deleted';
in table??

**Comment by wiedhodho** [comment]
I use timestamp data type. 
When I use $db->save, the createdfield automatic filled by current time. But not when use inserbatch

**Comment by MGatner** [comment]
https://github.com/codeigniter4/CodeIgniter4/pull/3879

**Comment by michalsn** [comment]
It's working just fine, my guess is that you're using v4.0.4, and changes that add support for `$useTimestamps` in the `insertBatch()` method was introduced only in the `develop` branch.
