### ISSUE TITLE
Bug: debugbar should not insert code in code tag

### ISSUE THREAD

**Issue by includebeer** [codeigniter4/CodeIgniter4#3847]
The debugbar insert code in code tag. I have a blog module where I save HTML code in an article and on my test site with the debug bar enabled, it adds code in my article in the HTML code for the debug bar. This is with CI 4.0.3.

**Comment by paulbalandan** [comment]
This has been fixed by #3804 in the latest develop.

**Comment by includebeer** [comment]
Ha sorry, I searched for debugbar instead of toolbar, that’s why I didn’t see this one.
