### ISSUE TITLE
IncomingRequest Class "hasFile" function does not exist as described in the documentation.

### ISSUE THREAD

**Issue by rifatardiyansyah13** [codeigniter4/CodeIgniter4#3852]
The documentation contains functions to minimize security risks with uploaded files using : 
[https://codeigniter.com/user_guide/incoming/incomingrequest.html?highlight=hasfile](url)

`$files = $request->getFiles(); `
`if($files->hasFile('uploadedFile'){...}`

But this function does not work at all and does not exist as described in the documentation. Please clarify and correct the functions provided in documentation. Thank you in advance.

I am using CodeIgniter 4 Version 4.0.4

**Comment by paulbalandan** [comment]
`$files` there is an instance of `CodeIgniter\HTTP\Files\FileCollection` and not of `IncomingRequest`.

> Information about all uploaded files can be retrieved through `$request->getFiles()`, which returns a `FileCollection` instance. This helps to ease the pain of working with uploaded files, and uses best practices to minimize any security risks.

See https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/HTTP/Files/FileCollection.php#L130
