### ISSUE TITLE
Bug: single_service does not set service's arguments correctly

### ISSUE THREAD

**Issue by sfadschm** [codeigniter4/CodeIgniter4#3854]
**Describe the bug**
The global `single_service` method sets the getShared attribute to `false` and then calls the service like this:

    // Ensure it's NOT a shared instance
    array_push($params, false);
    
    return Services::$name(...$params);

This works fine for services which only have the `getShared` argument passed to them (e.g. "timer" which is used both in the docs and in the doc block of `single_service` as an example and which is also used in the CommonFunctionTest). Services accepting multiple arguments however will trigger a type error (e.g., the "pager" service):

> Argument 1 passed to CodeIgniter\Config\Services::pager() must be an instance of Config\Pager or null, bool given, called in C:\XAMPP...

It seems that the `...$params` three dot operator (or whatever you want to call it) does not work as intended here.

Calling the same service with `service()` works, as no arguments at all are passed to `pager()`, such that all arguments fallback to their default values.

I see two solutions here:
1. The documentation should be updated to explain, that all arguments of a service called via `single_service` have to be included in the call, e.g. `single_service('pager', [null, null])`. However, this would make the function itself useless I think, as I can just directly invoke the service then.
2. We need to find a way to insert the `$params` array into the service function argument list "from the back". Honestly, I couldn't find any starting point when looking for something like that. Maybe there is a way to determine the number of arguments a function expects, so we could pad the `$params` array with the corresponding number of 'null' values (as all service function arguments seem to default to 'null' as far as I see).

Any ideas on this?

**CodeIgniter 4 version**
latest develope

**Affected module(s)**
services / common methods

**Expected behavior, and steps to reproduce if appropriate**
The getShared attribute should be unpacked to the last attribute of the requested service function.

**Context**
 - Windows 10
 - Apache 2.4
 - PHP 7.4

**Comment by paulbalandan** [comment]
We can probably use the Reflection classes, like `ReflectionParameter` or `ReflectionFunction`.

**Comment by sfadschm** [comment]
Thats what I came to think about, too.
I just tried this, and it seems to work so far (although I'm not really familiar with the Reflection classes). Adapted from the system/View/Cell:

	// Determine number of service function arguments (except $getShared)
	$refMethod	 = new ReflectionMethod(new Services(), $name);
	$paramCount	 = $refMethod->getNumberOfParameters() - 1;

	// Pad the params array with 'null' as this is the service
	// function arguments default value. Reduce $paramCount to
	$params = array_pad($params, $paramCount, null);

	// Ensure it's NOT a shared instance
	array_push($params, false);

	return Services::$name(...$params);

This seems to work with most services, however, it will likely not work, e.g. with `curlrequest`, as its first parameter defaults to `[]` instead of null. As far as I see, this is the only exception.

Would it be feasible to change the default value for this argument to null, too? This would be more consistent with the other services and from the function itself it does not seem necessary to be an array.

If not I guess we need to loop through the Reflection function parameters and pad the $params array one by one.

**Comment by paulbalandan** [comment]
We could use the `getDefaultValue()` to get the default for each param. At this point we cannot change the defaults to all use `null` as it would be BC for some.

**Comment by paulbalandan** [comment]
I have a solution in mind, although rudimentary. I'll work on this before this week ends.

**Comment by sfadschm** [comment]
> 
> 
> We could use the `getDefaultValue()` to get the default for each param. At this point we cannot change the defaults to all use `null` as it would be BC for some.

Right, I forgot that these functions are adaptable.


> 
> 
> I have a solution in mind, although rudimentary. I'll work on this before this week ends.

Perfect, thanks :)
If anybody else has this issue, the easiest workaround till the fix is to provide the services parameters with the function call, e.g.
    
    $pager = single_service('pager', null, null);
