### ISSUE TITLE
Bug: Double initializing of class

### ISSUE THREAD

**Issue by xbotkaj** [codeigniter4/CodeIgniter4#3855]
**Describe the bug**
Double initializing of the config class. Problem is that I am extending config class Filters from module. I have setup that I have shared configs between all apps and I am extending main config file located in shared folder by apps config. But happens that auto discovery is trying to make second initializing run in my shared folder a that makes fatal error for initializing already initialized class.

**CodeIgniter 4 version**
4.0.4 (develop)

**Affected module(s)**
Config

**Expected behavior, and steps to reproduce if appropriate**
Auto discovery should no try initialize already initialized class. There should be check to prevent it.

**Context**
 - OS: Windows 8.1 x64
 - Web server Apache
 - PHP version 7.4.11

**Comment by paulbalandan** [comment]
Can you describe more of your issue?

As I understand, you are extending `Config\Filters` but how are you doing it exactly?

**Comment by xbotkaj** [comment]
> Can you describe more of your issue?
> 
> As I understand, you are extending `Config\Filters` but how are you doing it exactly?

class Filters extends \SharedNamespace\Config\Filters

**Comment by paulbalandan** [comment]
Please provide more information to help us solve your issue.

1. Are you using the released 4.0.4 version or the latest develop?
2. Do you have a test case that can reproduce the problem?

**Comment by xbotkaj** [comment]
> Please provide more information to help us solve your issue.
> 
> 1. Are you using the released 4.0.4 version or the latest develop?
> 2. Do you have a test case that can reproduce the problem?

1. It is mentioned in the first "4.0.4 (develop)" so latest 
2. Case provided. make module and try to extend config file from the module like I provided :)

**Comment by najdanovicivan** [comment]
You cannot have same config class with same name in multiple modules try renaming \SharedNamespace\Config\Filters to BaseFilters

But again you can only use class Filters in a single module. What about naming the extended configs as

class {ModuleName}Filter

**Comment by najdanovicivan** [comment]
@paulbalandan what about adding namespace for config like we have for language files

config($class . '.' . $namespace);

**Comment by xbotkaj** [comment]
> @paulbalandan what about adding namespace for config like we have for language files
> 
> config($class . '.' . $namespace);
> 
> But again this will have to be handled in .env file which further complicates things

Hi, I simply disabled auto-load feature for everything and handling loading manually :) Works fine...

**Comment by MGatner** [comment]
This is because Filter alias discovery uses the same pattern: {namespace}/Config/Filters.php

Basically, Filters.php outside of App has conflicting use. The "quick fix" to use it as a Config class is to disable filter module discovery (app/Config/Modules.php), or to implement a Registrar for the Filters Config changes you need. But this will need some resolution in the framework itself.

**Comment by MGatner** [comment]
I've looked into this more and decided that, while the name conflict is not ideal it is not actually a problem. If you need to "extend" an App config you should be using Registrars, not interposing module config classes. Filters is really the only place this would cause issues though, but simply renaming the class (as others noted above) is an easy workaround.
