### ISSUE TITLE
Unexpected validation bug

### ISSUE THREAD

**Issue by Terrorboy** [codeigniter4/CodeIgniter4#3859]
- OS: linux
 - Web server nginx
 - PHP version php-fpm 7.4
- CI: 4.0.4
----
The code was written to simply check whether the rule is numeric(default validation library). However, the required rule that I haven't added is working.
(If there is a value, the purpose is to check if it is a number. This is thought to occur in all conditions where the required rule is not added.)

Why is that?

**Comment by michalsn** [comment]
Please use `permit_empty` rule. You can read more about it here: https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#available-rules.
