### ISSUE TITLE
Bug: CI4 won't recognise current namespace for language files

### ISSUE THREAD

**Issue by LucasKovacs** [codeigniter4/CodeIgniter4#3867]
**Describe the bug**
I'm working on a project that has 4 different modules, but for simplicity let's keep it on 2 (admin, site). Both modules have a language file inside located under Languages/en/global_lang.php. Due to an issue, and debugging I've notice that CI goes through all namespaces looking for that languages path and file.

```
array(2) {
  [0]=>
  string(51) "/var/www/html/website/admin/Language/en/global_lang.php"
  [1]=>
  string(50) "/var/www/html/website/site/Language/en/global_lang.php"
}
```

The method Language::requireFile will load both files, regardless of the current namespace, and set unneeded language lines.

According to CI docs:

> Language files are located automatically from defined namespaces when using the lang() method, as long as the file follows the same directory structures as the main application directory.

Problem with that, is that it adds a lot of extra load of unnecessary files. I should have a way to indicate in which namespace the file that I want is, or some way to the lang() function only goes to look on my current module namespace and not all around.

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
Language

**Expected behavior, and steps to reproduce if appropriate**
**Steps to reproduce**
- Create two modules with language files on them, same language and same file name.
- load language on any controller of those modules
- print all language lines, you'll see lines from both files, even the one that's outside the namespace.

**Expected**
- I only get the language lines from the file within the namespace

**Context**
- OS: [Linux]
- Web server [Apache/2.4.38 (Debian)]
- PHP version [7.4.10]

**Comment by michalsn** [comment]
Sorry, but it's not a bug - it is the desired behavior.

The way it's working this way is because we want to have the ability to override language files loaded from the external modules in our application.

The easiest solution seems to be renaming the language files. Unless you have a different idea that will allow us to stick to the current behavior and at the same time meet your needs.
