### ISSUE TITLE
Bug: Unexpected filter behavior

### ISSUE THREAD

**Issue by pixobit** [codeigniter4/CodeIgniter4#3874]
CodeIgniter 4.0.4

Unexpected filter behavior

Steps to reproduce:
1. Create a POST only filter
```
public $methods = [
    'post' => ['captcha']
];
```

2.1 Pass arguments for the filter route with generic route
`$routes->add('contact', 'HomeController::contact', ['filter' => 'captcha:verify']); `
Resulted issue: Would change the filter's behavior to run on GET method as well.

2.2 Pass arguments for the filter route with post specific route
`$routes->post('contact', 'HomeController::contact', ['filter' => 'captcha:verify']); `
Resulted issue: Arguments wouldn't get passed to the filter

**Comment by MGatner** [comment]
Filters applied through app/Config/Filters.php and app/Config/Routes.php should be non-overlapping. Everything you describe seems expected to me - try removing the filter in Filters.php and just use the Routes `post` version.
