### ISSUE TITLE
how can Codeigniter 4 default icon remove

### ISSUE THREAD

**Issue by RakibN** [codeigniter4/CodeIgniter4#3877]
My project Codeigniter version is 4.0.2 . I have face one problem Codeigniter icon always shows my right buttom site . i am hover
the icon left buttom show javascript:void(0). how can remove this icon.

**Comment by RakibN** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/57635856/98894817-d973b080-24cf-11eb-82c3-29e92da60ecd.png)

**Comment by truelineinfotech** [comment]
change environment development to production

**Comment by truelineinfotech** [comment]
ask your question / query in forum site.

**Comment by samsonasik** [comment]
Closed as solution provided.
