### ISSUE TITLE
url_title doesn't work with decimal number in title

### ISSUE THREAD

**Issue by perspolise** [codeigniter4/CodeIgniter4#3878]
I have decimal number in my title like: 

` this product size 0.5` or ` this product size 0,5` 

I need to create slug url and add to database using `url_title` function:

`url_title('this product size 0.5')` but in action `url_title` remove `.` or `,` from url and output is:

`this product size 05` 

how do can I keep `.` or `,` in url when I work with `url_title` function?!

**Comment by michalsn** [comment]
There is no option in the `url_title()` function that can handle this.

Please ask support questions in the [Forum](https://forum.codeigniter.com/forum-30.html).
