### ISSUE TITLE
Bug: Sqldrv problems to insert when change DBPrefix 

### ISSUE THREAD

**Issue by savilaj** [codeigniter4/CodeIgniter4#3881]
CRITICAL - 2020-11-13 01:16:51 --> [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'sap.sap.EndPoints'.

duplicates DBPrefix when DBPrefix value is other than dbo.
It also does not take the value of schema

In App\Config\Database.php
	public $development = [
		'DSN'      => '',
		'hostname' => 'xxxxxxxxxxxx',
		'username' => 'xxxxxxxxxxxx',
		'password' => 'xxxxxxxxx',
		'database' => 'develop',
		'DBDriver' => 'sqlsrv',
		**'DBPrefix' => 'sap.'**,  
		'pConnect' => false,
		'DBDebug'  => (ENVIRONMENT !== 'production'),
		'charset'  => 'utf8',
		'DBCollat' => 'utf8_general_ci',
		'swapPre'  => '',
		'encrypt'  => false,
		'compress' => false,
		'strictOn' => false,
		'failover' => []
	];

**Comment by rattones** [comment]
a table in SQL SERVER can not have **.** (dot) character in the compound of the name like **sap.**

**Comment by savilaj** [comment]
> a table in SQL SERVER can not have **.** (dot) character in the compound of the name like **sap.**

... and not have (dot) in the table name:

```
class EndPointModel extends BaseModel {

  protected $table = 'EndPoints';
  protected $primaryKey = 'code';
  protected $allowedFields = [
      'code',
      'name',
      'baseURL',
      'method',
      'query',
      'verify',
      'debug',
      'http_errors',
      'timeout',
      'username',
      'password'
  ];
  protected $returnType = 'App\Entities\EndPoint';
```

**Comment by rattones** [comment]
'DBPrefix' => 'sap.',

that dot .. DBPrefix is used to ad a prefix to table name, in this case, **sap.**  will generante **sap.EndPoints** as table name

**Comment by hdrodriguez** [comment]
I currently have that same problem since the company where I work uses different schemes than dbo, which is why I have not been able to migrate from CI3, solution is 'prefix.'

**Comment by savilaj** [comment]
> I currently have that same problem since the company where I work uses different schemes than dbo, which is why I have not been able to migrate from CI3, solution is 'prefix.' ?

No, it is not the solution. When using a DBprefix other than dbo. a select, an update, works correctly, but when using an insert it fails.

**Comment by savilaj** [comment]
The solution we have adopted to be able to migrate to CI4 has been to change the prefix to dbo. in all tables

**Comment by rattones** [comment]
cause this DBPrefix is not the **dbo.**, it's a prefix to all name of tables, like: 
DBPrefix = '' -> dbo.address
DBPrefix = 'usu_' -> dbo.usu_address 

as you can see in the file *system/Database/BaseConnection.php* at line: **1347**

```
	/**
	 * DB Prefix
	 *
	 * Prepends a database prefix if one exists in configuration
	 *
	 * @param string $table the table
	 *
	 * @return string
	 * @throws \CodeIgniter\Database\Exceptions\DatabaseException
	 */
```

**Comment by eSkiSo** [comment]
This issue is related with the driver **_insert** funcion (on **Builder.php**):
```php
protected function _insert(string $table, array $keys, array $unescapedKeys): string
	{
		$fullTableName = $this->getFullName($table);

		// insert statement
		$statement = 'INSERT INTO ' . $fullTableName . ' (' . implode(',', $keys) . ') VALUES (' . implode(', ', $unescapedKeys) . ')';

		return $this->keyPermission ? $this->addIdentity($fullTableName, $statement) : $statement;
	}
``` 
The issue is that only on **_insert** this happens, does not happen on **_update** or **_delete**
This **getFullName** puts the table name in the **DATABASE.SCHEMA.TABLE** format, but **SCHEMA** is hardcoded ( with **dbo** as far as i can see in the code *Connection.php* file)

So the quick fix woud be to replace **$fullTableName** with **$table** in the **$statement** inside **_insert** function.

**Comment by michalsn** [comment]
As mentioned earlier - `DBPrefix` is a different setting than `schema`.

If you check the [user guide](https://codeigniter4.github.io/CodeIgniter4/database/configuration.html#explanation-of-values), you will find a `schema` config variable that can be set.

Anyway, I feel like we need to use a full table name when it's possible to avoid confusion.
