### ISSUE TITLE
How Can remove CodeIgniter4 icon

### ISSUE THREAD

**Issue by RakibN** [codeigniter4/CodeIgniter4#3882]
Please ask support questions on our [forum](https://forum.codeigniter.com/forum-30.html).
We use github issues to track bugs and planned work.
hey! My CodeIgniter  projects version is 4.0.2  . i con remove the codeigniter default icon... how can remove codeigniter icon
![Screenshot_8](https://user-images.githubusercontent.com/57635856/99071264-f5647880-25db-11eb-891d-ba5bf9d0e22d.png)

**Comment by paulbalandan** [comment]
Please use the [forum](forum.codeigniter.com) to ask questions. We use GitHub to track bugs.
