### ISSUE TITLE
Bug: How can remove Codeinatore default icon 

### ISSUE THREAD

**Issue by RakibN** [codeigniter4/CodeIgniter4#3883]
My Project Codeinatore version 4.0.2. my client requrermeent is Codeinatore default icon remove to my project
![Screenshot_8](https://user-images.githubusercontent.com/57635856/99072850-fea31480-25de-11eb-9b1a-03365501478b.png)

**Comment by totoprayogo1916** [comment]
set environment

**Comment by totoprayogo1916** [comment]
Duplicate of #3882

**Comment by paulbalandan** [comment]
For the last time, please raise your question in the forums. You will get your answers there. You have asked this thrice already.
