### ISSUE TITLE
Feature: Spark header Suppression

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#3918]
With `codeigniter4-tasks` on the way I think we need a way to suppress the `showHeader()` output from Spark calls. By default anything scheduled via the `crontab` will use the `MAILTO=""` parameter to send output from a script. The email is suppressed when there is no output, but because of Spark's `showHeader()` there is always some output even when a command doe snot display anything.

I'm thinking probably an environment variable, since arguments and parameters aren't parsed yet at the time of the `showHeader()` call. But I'm open to other ideas.

**Comment by lonnieezell** [comment]
We could provide a simple `--quiet` flag, or similar, at spark level to tell it that. Although I would almost expect quiet to forgo ANY output, which might not be desirable.

**Comment by paulbalandan** [comment]
I would also expect `--quiet` to remove any output. How about `--no-header` flag and we could just simply check it via `$_SERVER['argv']`.

**Comment by MGatner** [comment]
What I like about the current implementation is the output happens before any argument parsing. If we could still find a way to do that with an argument that would be great.

**Comment by paulbalandan** [comment]
Since cron tasks are expected to run on Linux, how about passing env variable, like `NO_HEADER` or else, when calling spark. Something like this:

```
$ NO_HEADER=1 php spark migrate
```

Then `showHeader()` can be modified to accept an optional boolean argument whether to show/hide the header.
Inside `spark`:

```diff
-$console->showHeader();
+$console->showHeader(! (bool) getenv('NO_HEADER'));
```
