### ISSUE TITLE
Bug: Pre-commit hook for Phpstan and sniffer stop working after e111f04d74569e413c5aede3ed9bd9fa1ce7dca2 

### ISSUE THREAD

**Issue by hurtsky** [codeigniter4/CodeIgniter4#3920]
**Describe the bug**
pre-commit stop working after e111f04d74569e413c5aede3ed9bd9fa1ce7dca2

warning showed*
```
Running PHPStan...
dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../phpstan/phpstan" && pwd)
if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi
"${dir}/phpstan" "$@"
Running Code Sniffer...
dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../squizlabs/php_codesniffer/bin" && pwd)
if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi
"${dir}/phpcbf" "$@"
```

**CodeIgniter 4 version**
develop

**Expected behavior, and steps to reproduce if appropriate**
pre-commit for phpstan and sniffer should run on pre-commit

**Context**
 - Windows 10
 - Apache 2.4.46
 - PHP version 7.4

**Comment by samsonasik** [comment]
@najdanovicivan could you take a look at this? Thank you.

**Comment by najdanovicivan** [comment]
This is Windows related issue. I haven't work with windows for ages will have to set it up in a VM and check out what will be the best way to handle this to work on all platforms

**Comment by paulbalandan** [comment]
I can confirm this to be a problem on Windows platforms. Looking into this I think this is more of a bug in Composer's way of generating the binary for Unix platforms.

@najdanovicivan can you try changing the binaries of `phpstan` and `phpcbf` in `vendor/bin/` to the example below and removing the `php` prefixed by [`e111f04`](https://github.com/codeigniter4/CodeIgniter4/commit/e111f04d74569e413c5aede3ed9bd9fa1ce7dca2) to see if your original issue is resolved?

```diff
dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../phpstan/phpstan" && pwd)
if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

-"${dir}/phpstan" "$@"
+php "${dir}/phpstan" "$@"
```

**Comment by najdanovicivan** [comment]
@paulbalandan I've put a patch for windows inside the script

@hurtsky can you check it out and confirm it is working

**Comment by hurtsky** [comment]
@najdanovicivan look like its working.. fixed the problem. thank you
