### ISSUE TITLE
 Pdo driver not found

### ISSUE THREAD

**Issue by Guilherme-fagundes** [codeigniter4/CodeIgniter4#3922]
How to connect to the bank with pdo?
When informing the data in the documentation, the message that the driver was not found is displayed.
Help me!!!

**Comment by qury** [comment]
What kind of database would you like to use?

**Comment by Guilherme-fagundes** [comment]
I usually use MYSQL. use the PDO because it is safer because of the prepare statement

**Comment by lonnieezell** [comment]
We don't currently have a PDO driver. The Query Builder does a very similar thing for security as a prepared statement, but our MySQL and Postgres drivers do support true prepared statements when you need them.

**Comment by luckdragon** [comment]
it's been almost 2 years since this was commented on, is there still not a pdo driver for mysql in CI4?

**Comment by kenjis** [comment]
No.
See https://github.com/codeigniter4/CodeIgniter4/tree/develop/system/Database

**Comment by ampmonteiro** [comment]
This information / detail should be in the Docs.

**Comment by kenjis** [comment]
It is documented:
https://codeigniter4.github.io/CodeIgniter4/intro/requirements.html
