### ISSUE TITLE
Bug: controller routing on modules not working

### ISSUE THREAD

**Issue by LucasKovacs** [codeigniter4/CodeIgniter4#3927]
**Direction**
Some context, this is the forum thread where this has been discussed https://forum.codeigniter.com/thread-78044.html and on my opinion is an issue.

**Describe the bug**
Controllers under modules should be part of the routing without the need to create a lot of routes for it.

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
- routing

**Expected behavior, and steps to reproduce if appropriate**
I'd expect that any controller set under my modules folder to be automatically routed like the ones that are on the app folder. After all CI knows where those controllers are. They could use the module name as route prefix. For example.:
modules/admin/controllers/login.php should be http://mysite.com/admin/login

Currently I have to set every single rule so CI knows where those controllers are. This doesn't make any sense because I'm being force to put everything under app/controllers to avoid defining all the routes. My admin module for example is really big and I will have to define a lot of things, one rule for each method that my controllers have.

**Context**
- OS: [Linux]
- Web server [Apache/2.4.38 (Debian)]
- PHP version [7.4.10]

**Comment by paulbalandan** [comment]
Reading on the thread I understand the need but this is not a bug. Instead, it is an inherent limitation as described in the documentation so any enhancements to do what you strive is very welcome.

**Comment by LucasKovacs** [comment]
@paulbalandan I would be happy to give it a try. Any pointer where to start looking? :)

**Comment by paulbalandan** [comment]
Since this is all about routing you should start to look at `CodeIgniter\Router\RouteCollection` class since this is where routes are defined.
