### ISSUE TITLE
Bug: locale_set_default causing "Whoops" failure in MacOS PHP 7.3.9 on develop branch

### ISSUE THREAD

**Issue by samfullman** [codeigniter4/CodeIgniter4#3933]
https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/CodeIgniter.php#L176

As mentioned, I get a "Whoops!" notice.  I am on the `develop` branch.  Commenting out this line it runs just fine

`Samuels-MacBook-Pro:public_html samuelfullman$ php -r "echo locale_set_default('en');"
1 Samuels-MacBook-Pro:public_html samuelfullman$ 
`
(of course that's the CLI but it also shows as 7.3.9)

**Comment by paulbalandan** [comment]
This is not a bug. Installing the Intl extension will solve your issue.
