### ISSUE TITLE
Missing function locale_set_default(...) in Codeigniter 4

### ISSUE THREAD

**Issue by Ansulsingkang** [codeigniter4/CodeIgniter4#3953]
try to change in /system/Codeignater.php line 184
 locale_set_default($this->config->defaultLocale ?? 'en');

become:

	if( function_exists('locale_set_default' ) ) :
        locale_set_default($this->config->defaultLocale ?? 'en');
        endif;

_Originally posted by @Ansulsingkang in https://github.com/codeigniter4/CodeIgniter4/issues/3171#issuecomment-734558338_

**Comment by paulbalandan** [comment]
That is a hack and won't be accepted. Please install `intl` and its dependencies for the function to work.

**Comment by Ansulsingkang** [comment]
Can you show us how to install it in cpanel?

**Comment by paulbalandan** [comment]
You should you cpanel provider if intl is installed. Then in your custom php.ini add the line `extension=intl`.
