### ISSUE TITLE
Undefined function

### ISSUE THREAD

**Issue by sbn111** [codeigniter4/CodeIgniter4#3954]
//Load PHPMailer library
        $this->load->library('phpmailer_lib');
        
        //PHPMailer object
        $mail = $this->phpmailer_lib->load();

The above code is working in codeignitor 3. But not working in codeignitor 4.

What I need to use instead of the above?

Thank you

**Comment by paulbalandan** [comment]
Please raise your questions in the [forum](forum.codeigniter.com). Github is used only for bug reports.
