### ISSUE TITLE
PHP8: Deprecate required param after optional

### ISSUE THREAD

**Issue by enix-app** [codeigniter4/CodeIgniter4#3957]
I've found a lot of code bugs in PHP v8. Generally the use of parameters in functions.
Reference: https://php.watch/versions/8.0/deprecate-required-param-after-optional

Why don't the required parameters take precedence?
This should not be the writing syntax.

**Comment by sfadschm** [comment]
Are you using the latest develop version?
This was done already in #3938.

**Comment by enix-app** [comment]
Okay, thanks!
