### ISSUE TITLE
Bug: Tutorial news app has no CSRF protection

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#3959]
**Describe the bug**
The tutorial in user guide uses `csrf_field()`.
 <https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/tutorial/create_news_items.rst#create-a-form>

And it also says:
> The csrf_field() function creates a hidden input with a CSRF token that helps protect against some common attacks.

It is true, but csrf filter is off by default. So I think there is no CSRF protection in the app.

**CodeIgniter 4 version**
https://codeigniter4.github.io/userguide/tutorial/create_news_items.html#create-a-form
(Last updated on Jul 15, 2020.)

**Affected module(s)**
Documentation

**Expected behavior, and steps to reproduce if appropriate**
Add instruction to enable csrf filter in the documentation.

**Comment by fransiscusrolandamalau** [comment]
is this what is neededhttps://codeigniter.com/user_guide/libraries/security.html#cross-site-request-forgery-csrf

**Comment by lonnieezell** [comment]
Well damn, you're right. That is definitely not supposed to be that way. Should have it set for all POST methods by default. Anyone care to do a short PR?

**Comment by fransiscusrolandamalau** [comment]
Do you mean PR add instructions to enable csrf filter in documentation?

**Comment by lonnieezell** [comment]
If it's not documented well, then sure, but I was actually referring to a PR to ensure it's loaded by default for all POST requests. I could have sworn it used to be.

**Comment by kenjis** [comment]
Related #2913
