### ISSUE TITLE
Bug: RAR file detected as CSV

### ISSUE THREAD

**Issue by wiedhodho** [codeigniter4/CodeIgniter4#3979]
I've tried to upload an rar file, and use validation ext_in[rar]

It always fail. 

When i tried to check, the system always detect to csv (application/octet-stream) not as a rar file.

**Comment by sfadschm** [comment]
This is the same as #3921, just for another file extension. From the web, it seems that almost every file type can have the binary file type `application/octet-stream`.
So I wonder if it makes sense to batch add this type to all extensions instead of fixing each one on their own bug report.

**Comment by InsiteFX** [comment]
I think that all they need to do is add the mime types to the Mimes.php file.

**Comment by sfadschm** [comment]
Correct. The question is whether this should be done in the repo here to prevent future bug reports for such errors or if the user should add the MIME types themselves, as `Mime.php` is in the App config anyways.

**Comment by InsiteFX** [comment]
That is the way we always did it in CodeIgniter 3, we just added it to Mimes.php
Then when a new version of CodeIgniter came out they usually added it to Mimes.php

**Comment by sfadschm** [comment]
Î'm thinking that rather than adding the `application/octet-stream` to each and every single file extension, it would maybe be useful to have the guesser rely on the passed file extension alone (if any is given) and not check whether `application/octet-stream` is listed in the extensions MIME types. Not sure if this would mean some security risk though.

**Comment by michalsn** [comment]
The `application/octet-stream` is used when there is no other way to handle the file. I would rather try adding `application/vnd.rar` mime type to the `rar` array.

**Comment by michalsn** [comment]
Sadly, I can't verify returning `application/octet-stream` for `rar` file on Linux or Windows platform.

I would check if the PHP `fileinfo` extension is enabled because the lack of this extension may be also the reason.

**Comment by sfadschm** [comment]
@wiedhodho can you please check if the changes in #4085 solve your issue?
