### ISSUE TITLE
php spark serve error on php 8

### ISSUE THREAD

**Issue by bi2b** [codeigniter4/CodeIgniter4#3980]
i got an error when i use php spark serve with php 8.
in php 7.4 it's run normally.
error detail
`Type:        ErrorException
Message:     Required parameter $from follows optional parameter $verbs
Filename:    /htdocs/ci4/vendor/codeigniter4/framework/system/Router/RouteCollection.php
Line Number: 1017`

**Comment by paulbalandan** [comment]
This is a known bug with v4.0.4 not yet compatible with PHP 8.

**Comment by enix-app** [comment]
Use this branch https://github.com/codeigniter4/CodeIgniter4/tree/php8

**Comment by InsiteFX** [comment]
I went back to php 7.4.13 because of to many bugs in php 8 you will also get session warnings.

**Comment by tangix** [comment]
> I went back to php 7.4.13 because of to many bugs in php 8 you will also get session warnings.

Are the bugs you found in CI (because of non-compatibility yet) or in PHP 8 itself?

**Comment by enix-app** [comment]
> I went back to php 7.4.13 because of to many bugs in php 8 you will also get session warnings.

Mee to. CodeIgniter4 isn't ready for PHP8 yet.

**Comment by paulbalandan** [comment]
Latest changes already incorporates fixes for php8, so this can be closed now.

**Comment by samsonasik** [comment]
Note to user that found this issue, if you want to try app starter with php 8, you can run:

```
php builds development && composer update
```

To try development version before 4.0.5 release.

**Comment by feryalicization** [comment]
> Note to user that found this issue, if you want to try app starter with php 8, you can run:
> 
> ```
> php builds development && composer update
> ```
> 
> To try development version before 4.0.5 release.

This realy work, thank bro

**Comment by wandaazhar007** [comment]
> Note to user that found this issue, if you want to try app starter with php 8, you can run:
> 
> ```
> php builds development && composer update
> ```
> 
> To try development version before 4.0.5 release.

It's work. Thank you so much bro

**Comment by johnebarita** [comment]
Hi I'm new to CI. How to update my CI4 framework to the latest release without redoing my code?

**Comment by kenjis** [comment]
@johnebarita 
Please ask support questions on our [forum](https://forum.codeigniter.com/forum-30.html).
We use github issues to track bugs and planned work.
