### ISSUE TITLE
Bug: assertSee() can not assert title tag.

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#3984]
**Describe the bug**
[assertSee()](https://codeigniter4.github.io/userguide/testing/feature.html#dom-assertions) can not assert `title` tag.

`$result->assertSee('<title>CodeIgniter Tutorial</title>');` -> Pass
`$result->assertSee('CodeIgniter Tutorial', 'title');` -> Fail

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
Tests

**Expected behavior, and steps to reproduce if appropriate**
`assertSee('CodeIgniter Tutorial', 'title');` should pass when the page has the `title` tag.

**Context**
 - OS: [macOS 10.15.7]
 - Web server [n/a]
 - PHP version [7.4.13]

**Comment by paulbalandan** [comment]
I'm not familiar with `DomXPath` it uses under the hood, but it seems when the 1st arg of `assertSee` has tags, it considers the whole DOM. However, removing the tags, the code will search only within the `<body/>`. I dunno if that is a bug for you or is desirable.

**Comment by kenjis** [comment]
I don't know why it searches only within the `<body/>`.

**Comment by michalsn** [comment]
The first example that passes uses simple `mb_strpos()` for search. But the second one that fails uses the `DOMXPath` class, which has buggy rules that force a search only inside the `body` tag.

**Comment by sfadschm** [comment]
@paulbalandan is right here.
When using `assertSee`, the `see` method of `DOMParser` is called. If no element selector is passed to `assertSee`, this searches the whole DOM. If an element is passed, the `DOMParser->doXPath` function is used for searching. In this function `body` implicitly always gets added to the search string.
I feel this is more a consistency issue than a bug. Taking the UG literally, it 

     asserts that text/HTML is on the page
so I would think the `<title>` tag in the `<head>` should never be found. This is also what the PHPDoc states:

    Assert that the desired text can be found in the result body.

However, `DOMParser->see` and `doXPath` do not explicitly state that only the `body` is searched, but rather the whole DOM.

My personal opinion:
I do not see, why `doXPath `should only search the DOM of `body`. Btw. `doXPath` even behaves differently when using different kinds of selectors (e.g., passing a tag with an id will only search the `body`, but passing an id without a tag will search the whole DOM).

Options that I see:
1 modify the `DOMParser->see()` method to always use `doXPath`
2 modify `doXPath` to search the whole DOM anytime and update the `assertSee` UG
3 modify `DOMParser` and `doXPath` by adding an additional optional parameter `bool $onlyBody = false/true` to enable switching

**Comment by sfadschm** [comment]
> 
> 
> The first example that passes uses simple `mb_strpos()` for search. But the second one that fails uses the `DOMXPath` class, which has buggy rules that force a search only inside the `body` tag.

:D three minutes too late.
Can you also update the `assertSee` PHPDoc? It now searches the whole result, not only the result body.

**Comment by michalsn** [comment]
😅 

I'm not a linguistic expert but 

> Assert that the desired text can be found in the result body.

doesn't sound to me like the suggestion of a `body` tag... but I might be wrong. English is not my first language, so can I hear one more opinion on this one before I push a change?

**Comment by sfadschm** [comment]
> 
> 
> 😅
> 
> I'm not a linguistic expert but
> 
> > Assert that the desired text can be found in the result body.
> 
> doesn't sound to me like the suggestion of a `body` tag... but I might be wrong. English is not my first language, so can I hear one more opinion on this one before I push a change?

No worries, neither am I. Just the way I read those docs. I'm in for other opinions :)

**Comment by kenjis** [comment]
My English is not good. :-)

The User Guide says:
> You can perform tests to see if specific elements/text/etc exist with the body of the response with the following assertions.

I read it as the body of the response object, or the HTTP response body (not in the response header).
Not in the body tag.

**Comment by sfadschm** [comment]
Okay, just leave it then :-)

**Comment by sfsf9797** [comment]
Hi, do you mind share how you get $result?
thanks
