### ISSUE TITLE
Empty html-file created when moving uploaded files with $img->move()

### ISSUE THREAD

**Issue by ivanBell199** [codeigniter4/CodeIgniter4#4020]
I have tried to implement file uploading using the example from the Codeigniter 4 documentation. In my controller I have this code:
```
if($imagefile = $this->request->getFiles())
{
   foreach($imagefile['images'] as $img)
   {
      if ($img->isValid() && ! $img->hasMoved())
      {
           $newName = $img->getRandomName();
           $img->move('img/folder1/folder2', $newName);
      }
   }
}
```
This code nicely saves the uploded files in the "folder2" directory. However it also creates an empty html-file in the "folder2" directory. This file is named "folder2index". This behavior is undesired, because I simply need to upload a few files without anything else. For now I have just added some code to automatically remove the html-file.

**Comment by iRedds** [comment]
Add a slash in the end of the path img/folder1/folder2/ <- 
You will get the correct index.html file.
if you don't need index.html you can create your own logic to move uploaded files.

**Comment by michalsn** [comment]
I guess we can say it's solved.
