### ISSUE TITLE
setUpdateBatch

### ISSUE THREAD

**Issue by hanmoguoke** [codeigniter4/CodeIgniter4#4025]
function setUpdateBatch  Must be a two-dimensional array or object，

The document is：
setUpdateBatch($key[, $value = ''[, $escape = NULL]])
Parameters: | $key (mixed) – Field name or an array of field/value pairs
$value (string) – Field value, if $key is a single field
$escape (bool) – Whether to escape values and identifiers

Adds field/value pairs to be updated in a table later via updateBatch().

How to use it？
What I want to achieve is not to escape data when batch updatewith updateBatch

**Comment by iRedds** [comment]
```php
$data = [
   [
      'id' => 1,
      'title' => 'My title' ,
      'name'  => 'My Name 2' ,
      'date'  => 'My date 2'
   ],
   [
      'id' => 2,
      'name'  => 'Another Name 2' ,
      'date'  => 'Another date 2'
   ]
];
$db->setUpdateBatch($data, 'id', false)
$db->updateBatch(null, 'id')
// or 
$data = [
   [
      'id' => 1,
      'name'  => 'My Name 2' ,
      'date'  => 'My date 2'
   ],
   [
      'id' => 2,
      'name'  => 'Another Name 2' ,
      'date'  => 'Another date 2'
   ]
];
$dataNotEscape = [
   ['title' => 'My title'],
   ['title' => 'Another title']
];

$db->setUpdateBatch($dataNotEscape, 'title', false)
$db->updateBatch($data, 'id')
```

**Comment by paulbalandan** [comment]
Both examples of @iRedds are correct. If you need no escaping, just set the `$escape` param of setUpdateBatch to false.

**Comment by hanmoguoke** [comment]
thank u! it works!
