### ISSUE TITLE
updated_at field is filled with the current timestamp when inserting new data along with created_at

### ISSUE THREAD

**Issue by fahmiegerton** [codeigniter4/CodeIgniter4#4038]
> Please ask support questions on our [forum](https://forum.codeigniter.com/forum-30.html).
> We use github issues to track bugs and planned work.

Well I can't log in on there. Here's the screenshot:
![image](https://user-images.githubusercontent.com/5303871/103270756-a9d32600-49f3-11eb-9f46-fee19195ef59.png)

So, here it is. I'm just saying it straight away. The ```updated_at``` field is filled with the current timestamp when inserting new data, while it shouldn't. I don't know what I'm misconfigured of but, been tried everything, seems same. Here's the capture: 
![image](https://user-images.githubusercontent.com/5303871/103270878-f454a280-49f3-11eb-803e-16d4063ada0c.png)

And here's the model:
![image](https://user-images.githubusercontent.com/5303871/103270918-0c2c2680-49f4-11eb-813a-d0363f38c7fd.png)

And here's the data type:
![image](https://user-images.githubusercontent.com/5303871/103270991-22d27d80-49f4-11eb-90ce-e1acd03a23b2.png)

I hope someone could help me. I need a date of when the data is updated, but seems for now I need to do it manually. Thank you.

**Comment by paulbalandan** [comment]
Based on the Model's code, during data inserts the `created_at` and `updated_at` fields are both set with the same time during creation. The `updated_at` field will only get updated of there is an actual update of data.

**Comment by fahmiegerton** [comment]
> Based on the Model's code, during data inserts the `created_at` and `updated_at` fields are both set with the same time during creation. The `updated_at` field will only get updated of there is an actual update of data.

Shouldn't be ``NULL``` like the ```deleted_at``` ? Why would it be set on both field?

**Comment by paulbalandan** [comment]
I'm not the proper person to answer the logic behind the setting of `updated_at` but I'm guessing it is based on the assumption that update is technically the same with creation in terms of starting point. I mean is if you update something which isn't there in the first place is the same with creating it. Your point is valid but I'm afraid the current behavior cannot be changed now as it may be breaking for users who are already relying in this behavior.

If you want to circumvent this behavior without adding additional code, you can do is add the `updated_at` field to the data you're inserting. The default behavior is the `updated_at` field is set automatically during inserts when it is not found in the `$data` array.

You can do something like this:
```php
$data = [
    'name' => 'foo',
    'description' => 'bar',
    'updated_at' => null, // don't forget to add this line to force not setting `updated_at` with same date as `created_at`
];

// insert the data using our model
$model->insert($data);
```

**Comment by lonnieezell** [comment]
You didn't mis-configure. That's by design. That allows you to include newly created records when sorting by the most recently updated.
