### ISSUE TITLE
docs: Step installation method by Git

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#4043]
CodeIgniter4 can be installed in a number of different ways: manually, using Composer, or using Git. 

Those are the opening lines of the CodeIgniter installation method.
But on the documentation does not found how to install using GIT.

https://codeigniter4.github.io/CodeIgniter4/installation/index.html

**Comment by MGatner** [comment]
Hmm interesting. I guess this would be a method that used a locally cloned repo for the System path so we t would be easy to keep updated. A nice middle ground between download and Composer, I do think we should include instructions.

**Comment by kenjis** [comment]
I would like to remove the Git installation from the user guide as no one has addressed this issue.

**Comment by lonnieezell** [comment]
I mean, it's just a `git clone` so would be an easy writeup, but honestly, I'd prefer to encourage Composer installation so I'm not concerned with removing the git reference, personally.

**Comment by totoprayogo1916** [comment]
Another way using GitHub directly just by activate repo as template .
Then can run `git clone`.
ref: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template

**Comment by kenjis** [comment]
Which repository do you install with `git clone`?
Does anyone actually use a git install?

**Comment by paulbalandan** [comment]
> Another way using GitHub directly just by activate repo as template .

If there would be a template repo, that would be the `appstarter`. Not this development repo.

> Does anyone actually use a git install?

We have a user in the forums who is openly using `git clone`.

**Comment by MGatner** [comment]
You would need to do one of two things:
1. Clone the framework repo and then modify files in-place (basically never `pull` again)
2. Clone the AppStarter then run `composer install`

But 1) is strongly discouraged (framework repo should be for development only) and 2) still require Composer. So I would be in favor of dropping this from the UG. There is no harm in people doing it but I don't think it adds anything useful.

**Comment by kenjis** [comment]
I think if a user do `git clone` appstarter, they can update project files with `git merge`.
But the same thing can be done with https://github.com/tattersoftware/codeigniter4-patches

**Comment by MGatner** [comment]
I have no problem with someone using `git clone appstarter` but I don't think it deserves a dedicated "installation method" section in the docs because it still requires Composer and it introduces a level of complexity that I wouldn't want to support for developers who are unfamiliar with resolving merge conflicts. It also makes the project mostly unusable as a separate Git repo, which seems like a bad practice to encourage in 2022.
