### ISSUE TITLE
Bug: Issue with pagination

### ISSUE THREAD

**Issue by Lourys** [codeigniter4/CodeIgniter4#4045]
Today I tried to make a pagination system with Pager, the service included in CodeIgniter and with the model system bundled in.
I think there is an issue. When you make a query with the builder and call the paginate() method the pagination doesn't works properly...
So I looked at the paginate() implementation and I saw that Pager is called through Services but with getShared variable set to false... So when I use pager after I can't get data initialized before by the paginate() function.
I think the getShared variable should be set to true (in system/Model.php file).

Maybe I do it wrong? If it's not an issue I would like to know what is the good way to do this.

**Comment by lonnieezell** [comment]
Not a bug. If we used a shared instance it would be impossible to have multiple pagers on a single page. 

You don't describe what the issue you ran into is so I can't really help. Please provide more details on what you're experiencing.

**Comment by Lourys** [comment]
Thank's for your answer!
I just made something like this:

MyController.php
```php
public function index() {
    $articleModel = new ArticleModel();
    $myData = $articleModel->paginate(10);
    
    $pager = Services::pager();
    // When I do this, I get an error:
    dd($pager->getDetails());
}
```
So when I do this, I get a CodeIgniter\Pager\Exceptions\PagerException (default is not a valid Pagination group.)
So my question is how can I retrieve the instance of Pager created by ArticleModel?

**FIXED: Instance is retrievable through $articleModel->pager**
Sorry for the inconvenience

**Comment by MGatner** [comment]
Glad you found the solution!
