### ISSUE TITLE
Bug: username input form shows root as a default value

### ISSUE THREAD

**Issue by joancomaz** [codeigniter4/CodeIgniter4#4062]
**Describe the bug**
By default, it displays the _user_ and _password_ values ​​from the _Database.php_ database configuration file in the user input and password fields of any custom view.

**CodeIgniter 4 version**
4.0.4

**Expected behavior, and steps to reproduce if appropriate**
View code:
`<input class="form-control" type="text" name="username" id="username" value="<?= $data->username ?>" />`
The input field show **root** when the data is empty, because the username of my database config is _root_!

**Context**
 - OS: Windows 10
 - Apache 2.4.43
 - PHP version 7.4.6

**Comment by MGatner** [comment]
If I understand correctly, you are saying that `$data` is somehow receiving values from your database config? Please include code samples of your controller (or whatever is calling this view). Also please test the same code against the latest `develop` branch of the framework as there have been hundreds of bug fixes and changes. I would also recommend you try using `var_dump()` to confirm the actual type and contents of `$data`.

**Comment by joancomaz** [comment]
Yes, it is. I post code snippets below:

### Controller:
```
public function new() {
  $view = 'new';
  $data = [
    'user' => new UserModel(),
  ];

  echo view("user/$view", $data);
}
```

### Model: 
```
class UserModel extends Model {

    protected $table = 'users';
    protected $primaryKey = 'id';

    protected $allowedFields = [
        'id',
        'username',
        'password'
    ];
}
```

### View:
```
<form action="create" method="post" enctype="multipart/form-data">
    <?= csrf_field() ?>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label for="name">Username</label>
                <input class="form-control" type="text" name="username" id="username" value="<?= old('username', $user->username) ?>" /> 
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="name">Password</label>
                <input class="form-control" type="password" name="password" id="password" value="<?= old('password', $user->password) ?>" /> 
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary" name="submit">
                <i class="fas fa-save"></i>
                Save
            </button>
        </div>
    </div>
</form>
```

**Comment by MGatner** [comment]
You are using a Model where you want a result or Entity. Your model connects to the database and retrieves the rows. It also has magic get function to cascade into its database connection, so when you ask for "UserModel->password" it is actually retrieving your database connection password, just like you asked. 

Check the User Guide section on using Models.
