### ISSUE TITLE
Bug: Required parameter $from follows optional parameter $verbs

### ISSUE THREAD

**Issue by Faiizii** [codeigniter4/CodeIgniter4#4076]
**Describe the bug**
I download the zip file from [here](https://codeigniter.com/download) and extract it inside the XAMP htdocs. On runing the `php spark serve` command in the root of the directory, I am facing the following issue

> Type:        ErrorException
Message:     Required parameter $from follows optional parameter $verbs
Filename:    C:\xampp\htdocs\codi\system\Router\RouteCollection.php
Line Number: 1017

Also I tried to run the CodeIgnitor4 as traditionally like CodeIgnitor3, but I am unable to run it. 

**Expected behavior, and steps to reproduce if appropriate**
It should show me the home page of the CodeIgniter 4
**Context**
 - OS: Windows 10
 - PHP version 8.0.0 (cli) (built: Nov 24 2020 22:02:57)

**Comment by iRedds** [comment]
CI4 is not fully compatible with php8

**Comment by michalsn** [comment]
This is already fixed in the develop branch and will be available in the next release.

**Comment by Faiizii** [comment]
Also facing the following issue with php 7.2.34 version 

> Fatal error: Uncaught Error: Call to undefined function CodeIgniter\locale_set_default() in C:\xampp\htdocs\codignitor4\system\CodeIgniter.php:184

**Comment by iRedds** [comment]
> This is already fixed in the develop branch and will be available in the next release.
This is not a fix. It's a crutch.
All arguments are required except $ options. There is no point in specifying default values.
