### ISSUE TITLE
Pagination work in local, but error in server

### ISSUE THREAD

**Issue by MuhammadAnhar** [codeigniter4/CodeIgniter4#4096]
I have some error with my pagination, and it's **my controller :** 
$data =
				[
					'title' 	 => "The Memories Story - Photography",
					'validation' => $this->validation,
					'photos' 	 => $this->CoverFotoModel->getPhotos(),
					'pager' 	 => $this->CoverFotoModel->pager,
					'provinces'  => $this->ProvinsiModel->provinsi()
				];
			return view('index/photograph', $data);

**My Model :**
public function getPhotos()
    {
        return $this->table('cover_foto')
            ->join('provinces', 'provinces.id=cover_foto.provinsi_cover')
            ->join('regencies', 'regencies.id=cover_foto.kabupaten_cover')
            ->paginate(8, 'cover_foto');
    }

**My View :**
<?= $pager->links('cover_foto', 'photo_pagination'); ?>

**My Pagination view**

**and this message error :**

CodeIgniter\View\Exceptions\ViewException
Invalid file: {0}  
SYSTEMPATH/Exceptions/FrameworkException.php at line 21
public static function forInvalidFile(string $path)
20     {
21         return new static(lang('Core.invalidFile', [$path]));
22     }
SYSTEMPATH/View/View.php : 228   —  CodeIgniter\Exceptions\FrameworkException::forInvalidFile ( arguments )
**This the an arguments
$path | App\Views\Pagers\photo_pagination.php
**

Please help in my error Mr. @lonnieezell

**Comment by samsonasik** [comment]
It mostly a case sensitive things, check your filename. This kind of issue should go to forum.
