### ISSUE TITLE
Bug: Using insertBatch with a large amount of data will result in an error.

### ISSUE THREAD

**Issue by tomomo** [codeigniter4/CodeIgniter4#4099]
Using insertBatch with a large amount of data will result in an error.

```log
CRITICAL - 2021-01-13 21:23:37 --> Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes)
```

The data is about 150,000.
I also increased the memory limit, but it doesn't change.

```php
set_time_limit(120);
// ini_set('memory_limit', '256M');
// ini_set('memory_limit', '512M');
ini_set('memory_limit', '1024M');

$db->table('address')->truncate();
$db->table('address')->insertBatch($data);
```

It does not change even if "Size" is specified.
```php
$db->table('address')->insertBatch($chunk, null, 50);
```

It has a solid track record in CI3 as it is just a rewrite of what was originally used in CI3 into CI4.
I think it's a bug.

It seems that it can be avoided by using `array_chunk`.
```php
foreach (array_chunk($rows, 50) as $chunk)
{
  $db->table('address')->insertBatch($chunk);
}
```

**Context**
 - CodeIgniter version 4.0.4, develop
 - PHP version 7.4

**Comment by MGatner** [comment]
Is your environment set to `production`? In `development` the Debug Toolbar is likely intercepting every database call and logging its contents, which can balloon very quickly for large datasets, and could cause issues regardless of how you broke up the queries.

**Comment by tomomo** [comment]
Thank you for your reply.

Certainly it was `development` that I set up.
I switched to `production` and rewrote it to a setting that does not generate logs as much as possible as follows.
But the result is the same. HTTP Status 500.

```
# .env
CI_ENVIRONMENT = production
logger.threshold = 0
```

```php
$db->table($table)->truncate();
// foreach (array_chunk($rows, 50) as $chunk)
// {
// 	$db->table($table)->insertBatch($chunk);
// }

$db->table($table)->insertBatch($rows, null, 50);
unset($rows);
```

**Comment by Bartabat** [comment]
Hello,

I had the same problem today on version 4.1.3 by resuming a script with insertBatch that I originally used on codeigniter 3 without memory problem.

While digging through the code I noticed that the `$binds` property of the `CodeIgniter\Database\BaseBuilder` class was not emptied after the execution of the query, which causes a continuous increase in memory.


The property is emptied in the [insert()](https://github.com/codeigniter4/CodeIgniter4/blob/795e9c47c06724d8a82226566ad83c0fbc300fdb/system/Database/BaseBuilder.php#L2255) and [update()](https://github.com/codeigniter4/CodeIgniter4/blob/795e9c47c06724d8a82226566ad83c0fbc300fdb/system/Database/BaseBuilder.php#L2449) method, but it is not in [insertBatch()](https://github.com/codeigniter4/CodeIgniter4/blob/795e9c47c06724d8a82226566ad83c0fbc300fdb/system/Database/BaseBuilder.php#L2076) or [updateBatch()](https://github.com/codeigniter4/CodeIgniter4/blob/795e9c47c06724d8a82226566ad83c0fbc300fdb/system/Database/BaseBuilder.php#L2567).

I gave it a try by manually emptying the `$bind` property after my `insertBatch()` calls and the memory consumption remained stable.

I have not looked in more detail but it is possible that other types of request are affected by this problem.

**Comment by shantiweb** [comment]
I am getting same high memory usage with insertBatch and updateBatch.
CI4 please fix this sooner
