### ISSUE TITLE
Bug: a new installation of codeignitor 4.0.4 show 404 error Sorry! Cannot seem to find the page you were looking for.

### ISSUE THREAD

**Issue by rytplays** [codeigniter4/CodeIgniter4#4111]
**Describe the bug**
a new installation of codeignitor 4.0.4 show 404 error
Sorry! Cannot seem to find the page you were looking for.

**CodeIgniter 4 version**
4.0.4

**Expected behavior, and steps to reproduce if appropriate**
A clear and concise description of what you expected to happen,
and how you got there.  
Feel free to include a text/log extract, but use a pastebin facility for any
screenshots you deem necessary.

**Context**
 - OS: Windows 10
 - Web server Apache
 - PHP version 8

![image](https://user-images.githubusercontent.com/76940161/104809183-55141580-5811-11eb-95ef-89f2536f83bd.png)

**Comment by paulbalandan** [comment]
Please post your support questions in the [forums](https://forum.codeigniter.com).
