### ISSUE TITLE
current_url() global method returning URLs without the index.php part. 

### ISSUE THREAD

**Issue by npwsamarasinghe** [codeigniter4/CodeIgniter4#4116]
CI VERSIONS: CI4 4.04 and develop branch.

I saw someone talking about this issue on the CI forum and thought to give it a try. And yes that method not returning URLs with the index.php part even it's in the indexPage configuration.

**Comment by MGatner** [comment]
Thanks for taking a look at this. I've responded on the PR, but this seems to be intended (according to the User Guide and tests). I acknowledge it does not make much sense, but if it is not a bug then it would be a breaking change. 

We will see what the rest of the team thinks, but an alternative would be to define a new function like "this_url()" that does it the way you would expect.

**Comment by MGatner** [comment]
Per the conversation on the PR this is not a bug, but an opportunity for an enhancement.

**Comment by MGatner** [comment]
I'm running into this issue again trying to verify "active" links on menus. This closer experience is making me realize that the current function is a problem: it generates a URL that will not work in most configurations with an `indexPage`. That said we probably still can't change `current_url()` but I am looking into alternatives and would like to deprecate that function so as not to promulgate the issue.

**Comment by lonnieezell** [comment]
To me this is a bug. Current url should return the current url whether it has `index.php` in it or not. I haven't looked at the code for that in a while, but my guess is it should be using `site_url` instead of `base_url`.
