### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Elsyaqif** [codeigniter4/CodeIgniter4#4126]
permisi admin mohon solusi untuk codeigniter4 punyaku dan bagaimana solusinya
![git](https://user-images.githubusercontent.com/77525530/104864724-6faed180-596c-11eb-84cf-4344a6c9b18a.jpg)

terimakasih

**Comment by paulbalandan** [comment]
Please write in English for issue reporting.

This is not a bug. Warnings are emitted by Composer when the external dependency you're using is declared abandoned by the maintainer. While it doesn't affect us directly, reliance on code provided by such dependencies should be omitted. `fzaninotto/faker` has been replaced with `fakerphp/faker` in the latest develop so in the next release this is fixed. for `php-token-stream` this is used by `phpunit ^8.5`. If you'll be using `phpunit ^9` this dependency is removed by phpunit itself so no worries for that.

Either way, these errors should not concern you as these are warnings for development dependencies.
