### ISSUE TITLE
BaseConfig property issue

### ISSUE THREAD

**Issue by mostafakhudair** [codeigniter4/CodeIgniter4#4140]
I don't know if it's a bug or deliberate

All config file that extends BaseConfig
if property equal to '/', when i try to retrieve that property it returns this string .. /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

**Comment by iRedds** [comment]
Example?

**Comment by michalsn** [comment]
Can't reproduce.

I'm closing this, since it doesn't seem to be a bug, but feel free to continue the conversation - especially if you can provide some code examples, your server configuration, and CI version. Thanks.
