### ISSUE TITLE
Bug: Required parameter $userAgent follows optional parameter $body in

### ISSUE THREAD

**Issue by navalnyj** [codeigniter4/CodeIgniter4#4148]
**Describe the bug**
Deprecated: Required parameter $userAgent follows optional parameter $body in C:\nginx\html\system\HTTP\IncomingRequest.php on line 161

Fatal error: Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\nginx\html\app\Config\Events.php:33) in C:\nginx\html\system\Debug\Exceptions.php:164 Stack trace: #0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\nginx\\html\\s...', 164) #1 C:\nginx\html\system\Debug\Exceptions.php(164): header('HTTP/1.1 500 In...', true, 500) #2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException)) #3 {main} thrown in C:\nginx\html\system\Debug\Exceptions.php on line 164

Fatal error: Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\nginx\html\app\Config\Events.php:33) in C:\nginx\html\system\Debug\Exceptions.php:164 Stack trace: #0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\nginx\\html\\s...', 164) #1 C:\nginx\html\system\Debug\Exceptions.php(164): header('HTTP/1.1 500 In...', true, 500) #2 C:\nginx\html\system\Debug\Exceptions.php(224): CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException)) #3 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler() #4 {main} thrown in C:\nginx\html\system\Debug\Exceptions.php on line 164

**CodeIgniter 4 version**
Latest stable 4.0.4

**Affected module(s)**
Which package or class is the bug in, if known.

**Expected behavior, and steps to reproduce if appropriate**
You re not noobs, but u did noob mistake (you should use optional (auto defined method parameters variables put at the end of function defining))

public function __construct($config, URI $uri = null, $body = 'php://input', UserAgent $userAgent)

**Context**
 - OS: Windows 10
 - Web server nginx 1.19
 - PHP version 8.0.1

I love codeigniter <3 That's why i waste my time and did register and create issue, so dont blame please on me if i did incorrect bug report.. Better this one than nothing!

FREE NAVALNY!!!! PUTIN'S PALACE (60+M Views @ youtube in 3 days+)

Have good life!

**Comment by kenjis** [comment]
4.0.4 does not support PHP8.
Please check the latest `develop` branch.

**Comment by navalnyj** [comment]
Thank you <3
