### ISSUE TITLE
Seed Command in document Not found

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#4154]
Hello the Seed command for creating a seeder file not found in the document. I was doing try and error to get it and finally I get two commands that is not documented in the document. <br>
This command lines are
<br>
``
php spark make:seeder file_name
``
<br>
``
php spark db:create db_name
``
<br>
Please try include this to the document.
<br>
I don't know how to contribute to codeigniter else i suppose to do it by myself without even giving anyone headache to this

**Comment by kenjis** [comment]
See the current in-progress User Guide:
https://codeigniter4.github.io/CodeIgniter4/cli/cli_generators.html#make-seeder

**Comment by paulbalandan** [comment]
Currently, we do not have documentation for `db:create` as it is new.

**Comment by paulbalandan** [comment]
@ChibuezeAgwuDennis please see doc fix for `db:create`. For the make:seeder, doc is already in the latest develop.
