### ISSUE TITLE
Bug: Soft deletes and model validation when unique

### ISSUE THREAD

**Issue by mmacagnan** [codeigniter4/CodeIgniter4#4162]
Hi,

I try to use the soft deletes provided by framework, but when use in validation rules unique,
it doesn't ignores the deleted records.

**Comment by VipinFarswan** [comment]
Its not a bug.Suppose you add new email in database which already exits in db but currently soft deleted but when in future you want to restore that soft deleted data then you will have two entries with same email in database.So if you don't have any intention to restore soft deleted data then its better to deleted that entry.

**Comment by xbotkaj** [comment]
> Hi,
> 
> I try to use the soft deletes provided by framework, but when use in validation rules unique,
> it doesn't ignores the deleted records.

Hi @mmacagnan :)

You are mixing two things together. UNIQUE attribute is database constraint and soft delete is just CodeIgniter way how to select (ignore soft deleted rows). But you can not have two same unique values in the database (NEVER).

This is not bug. Works as designed ;)

**Comment by mmacagnan** [comment]
Thanks for the support.
