### ISSUE TITLE
Bug: Deprecated: Required parameter $userAgent follows optional parameter $body in /opt/lampp/htdocs/framework-4.0.4/system/HTTP/IncomingRequest.php on line 161

### ISSUE THREAD

**Issue by MusheAbdulHakim** [codeigniter4/CodeIgniter4#4172]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
After downloading the framework from the main **website,www.codeigniter.com/** ,I moved it to my htdocs folder, gave it write access and opened it in the browser only to get this error

Fatal error: Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /opt/lampp/htdocs/framework-4.0.4/app/Config/Events.php:33) in /opt/lampp/htdocs/framework-4.0.4/system/Debug/Exceptions.php:164 Stack trace: #0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/opt/lampp/htdo...', 164) #1 /opt/lampp/htdocs/framework-4.0.4/system/Debug/Exceptions.php(164): header('HTTP/1.1 500 In...', true, 500) #2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException)) #3 {main} thrown in /opt/lampp/htdocs/framework-4.0.4/system/Debug/Exceptions.php on line 164

Fatal error: Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /opt/lampp/htdocs/framework-4.0.4/app/Config/Events.php:33) in /opt/lampp/htdocs/framework-4.0.4/system/Debug/Exceptions.php:164 Stack trace: #0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/opt/lampp/htdo...', 164) #1 /opt/lampp/htdocs/framework-4.0.4/system/Debug/Exceptions.php(164): header('HTTP/1.1 500 In...', true, 500) #2 /opt/lampp/htdocs/framework-4.0.4/system/Debug/Exceptions.php(224): CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException)) #3 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler() #4 {main} thrown in /opt/lampp/htdocs/framework-4.0.4/system/Debug/Exceptions.php on line 164

**CodeIgniter 4 version**
Which version (and branch, if applicable) the bug is in.
version 4
**Affected module(s)**
Which package or class is the bug in, if known.
HTTP/IncomingRequest.php
**Expected behavior, and steps to reproduce if appropriate**
A clear and concise description of what you expected to happen,
and how you got there.  
Feel free to include a text/log extract, but use a pastebin facility for any
screenshots you deem necessary.

**Context**
 - OS: [ Parrot Os 4.10]
 - Web server [Apache/2.4.46 (Debian)]
 - PHP version [7.4.11]

**Comment by samsonasik** [comment]
Not a bug, you seems have a whitespace or header sent before start a session. Ask to forum for such question https://forum.codeigniter.com/index.php

**Comment by meigiyanto** [comment]
> Not a bug, you seems have a whitespace or header sent before start a session. Ask to forum for such question https://forum.codeigniter.com/index.php

you did not indicate in which thread discussed the problem above, I had a hard time looking for it in the forum
