### ISSUE TITLE
Bug: forge cant set default value = CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#4174]
Forge for create table cant set default value `CURRENT_TIMESTAMP`
```
'dt' => [
    'type'    => 'TIMESTAMP',
    'default' => CURRENT_TIMESTAMP
],
```

**CodeIgniter 4 version**
v4.0.4

**Context**
 - OS: Windows 10
 - PHP version 7.4.11

**Comment by xbotkaj** [comment]
Hi @totoprayogo1916 . What database syste do you use? 

For MariaDB you do not set CURRENT_TIMESTAMP, it is set automatically :)
`MariaDB has special behavior for the first column that uses the TIMESTAMP data type in a specific table. For the first column that uses the TIMESTAMP data type in a specific table, MariaDB automatically assigns the following properties to the column:

DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP`

THX

**Comment by totoprayogo1916** [comment]
![image](https://user-images.githubusercontent.com/2387514/106563901-14313600-655f-11eb-92d5-a0a10cf5e57b.png)
and the error when run: 
```
'dt' => [
    'type'    => 'TIMESTAMP',
    'default' => CURRENT_TIMESTAMP
],
```
![image](https://user-images.githubusercontent.com/2387514/106564684-23fd4a00-6560-11eb-9f57-7215d0257bae.png)

tried to change with
```
'dt' => [
    'type'    => 'TIMESTAMP',
    'default' => 'CURRENT_TIMESTAMP'
],
```
![image](https://user-images.githubusercontent.com/2387514/106564748-42634580-6560-11eb-8dda-77dda828b25c.png)

**Comment by xbotkaj** [comment]
Hi @totoprayogo1916 , 

definetely it must be with 'CURRENT_TIMESTAMP' with '' since it is not PHP constant.

The second one is throwing directly from MySQL, Try to make SQL directly in phpMyAdmin and see if it runs or if you have xdebug to see what is sending CI to database, I am not able to see it since I have no this setup with MySQL

`CREATE TABLE t1 (
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dt DATETIME DEFAULT CURRENT_TIMESTAMP
);`

(you can try even run query directly from CI - raw query)

If this pass then we need to see what CI is sending to MySQL :)

THX

**Comment by xbotkaj** [comment]
Hi @totoprayogo1916 

I did whole setup and I can confirm this is bug, we are escaping CURRENT_TIMESTAMP, this value cannot be escaped.

SQL from CI -> `CREATE TABLE IF NOT EXISTS `table1` (
	`id` INT NOT NULL,
	`dt` DATETIME NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
	`ts` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP'
) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci`

**Comment by michalsn** [comment]
We just don't offer support for not escaped values. You should define your field as a string:

```php
'dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP'
```

https://codeigniter4.github.io/CodeIgniter4/dbmgmt/forge.html#passing-strings-as-fields

**Comment by joelsodias** [comment]
Hi, my two cents contribution... at line 1122 of Forge.php I'vre have rewritten to this and worked to me... Hope it helps ;)
(using MariaDB by the way)

	/**
	 * Field attribute DEFAULT
	 *
	 * @param array $attributes
	 * @param array $field
	 *
	 * @return null|void
	 */
	protected function _attributeDefault(array &$attributes, array &$field)
	{
		if ($this->default === false)
		{
			return;
		}

		if (array_key_exists('DEFAULT', $attributes))
		{
			if ($attributes['DEFAULT'] === null)
			{
				$field['default'] = empty($this->null) ? '' : $this->default . $this->null;

				// Override the NULL attribute if that's our default
				$attributes['NULL'] = true;
				$field['null']      = empty($this->null) ? '' : ' ' . $this->null;
			}
			else
			{
                                // Try to workaround CURRENT_TIMESTAMP not supported 
				if ($attributes['DEFAULT'] === 'CURRENT_TIMESTAMP') {
				  $field['default'] = $this->default .'CURRENT_TIMESTAMP';
				} else {
				  $field['default'] = $this->default . $this->db->escape($attributes['DEFAULT']);
				}
			}
		}
	}

**Comment by KNobHack** [comment]
@joelsodias what about drivers other than mysqli? will it cause problems?

**Comment by kenjis** [comment]
I sent a PR #5957
