### ISSUE TITLE
Estimated date of new version (4.0.5 or 4.1)

### ISSUE THREAD

**Issue by nicojmb** [codeigniter4/CodeIgniter4#4182]
Hi team!!

I want to start a new project with codeigniter and I am waiting for the new version for its improvements and for the support of php 8.

Do you have any idea when the new version will be published?

It is to know whether to wait or not.

Cheers!

**Comment by paulbalandan** [comment]
Let's have @lonnieezell or @MGatner take the center stage. 🙌

**Comment by MGatner** [comment]
Lonnie has been very busy. It is my goal to release this week, but I'm not sure if I have the access I need to do that without him. We will try.

**Comment by kenjis** [comment]
Is the next release 4.0.5 or 4.1? 
Or will both be released?

After releasing 4.1, Is 4.0 going to be maintained?

**Comment by MGatner** [comment]
Both will be released. 4.0.5 will support 7.2 through 8, 4.1 will drop support for 7.2

The team is too strapped to maintain legacy branches. If the community needs continued support for 7.2 then someone will need to step up to take charge of the 4.0.x maintenance.

**Comment by kenjis** [comment]
I got it. Thank you!

**Comment by samsonasik** [comment]
already released.
