### ISSUE TITLE
Bug: UploadedFile::store() can't return null

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#4183]
**Describe the bug**
`UploadedFile::store()` could return `null`:
https://github.com/codeigniter4/CodeIgniter4/blob/7ca2a7193ae0a109c75fd47233ae954a6db350e0/system/HTTP/Files/UploadedFile.php#L379-L380
But the return type is `string`.
https://github.com/codeigniter4/CodeIgniter4/blob/7ca2a7193ae0a109c75fd47233ae954a6db350e0/system/HTTP/Files/UploadedFile.php#L373

**CodeIgniter 4 version**
develop branch.

**Affected module(s)**
UploadedFile

**Expected behavior, and steps to reproduce if appropriate**
I'm not sure. If `$this->move()` fails, what should be returned?

**Context**
- OS: [macOS 10.15.7]
- Web server [PHP built-in]
- PHP version [7.4.13]

**Comment by paulbalandan** [comment]
It is strange phpstan didn't flag this incompatible return. 🤔

**Comment by kenjis** [comment]
I found that `$this->move()` never returns `false`. So phpstan does not complains?
https://github.com/codeigniter4/CodeIgniter4/blob/7ca2a7193ae0a109c75fd47233ae954a6db350e0/system/HTTP/Files/UploadedFile.php#L131

So should it be like this?
```diff
--- a/system/HTTP/Files/UploadedFile.php
+++ b/system/HTTP/Files/UploadedFile.php
@@ -376,8 +376,9 @@ class UploadedFile extends File implements UploadedFileInterface
        $fileName   = $fileName ?? $this->getRandomName();
 
        // Move the uploaded file to a new location.
-       return ($this->move(WRITEPATH . 'uploads/' . $folderName, $fileName)) ?
-               $folderName . $this->name : null;
+       $this->move(WRITEPATH . 'uploads/' . $folderName, $fileName);
+
+       return $folderName . $this->name;
    }
 
    //--------------------------------------------------------------------
```

**Comment by kenjis** [comment]
I sent PR #4187
