### ISSUE TITLE
if_exist not working with file

### ISSUE THREAD

**Issue by jahmedk** [codeigniter4/CodeIgniter4#4194]
![image](https://user-images.githubusercontent.com/22505794/106363728-2d15cd80-634c-11eb-9854-8bf28b753fcb.png)

**Comment by paulbalandan** [comment]
Please provide us your test code so we can find the problem.

**Comment by jahmedk** [comment]
$aRules = [
	'user.img' => [
		'label' => 'User Image',
		'rules' => 'if_exist|uploaded[user.img]|is_image[user.img]|max_size[user.img,2048]'
	]
];
$validation =  \Config\Services::validation();
$validation->setRules($aRules);
if(!$validation->run($this->request->getVar())){
	echo '<pre>';
	print_r($validation->getErrors());
	echo '</pre>';
}

**Comment by jahmedk** [comment]
`		$aRules = [
			'user.img' => [
				'label' => 'User Image',
				'rules' => 'if_exist|uploaded[user.img]|is_image[user.img]|max_size[user.img,2048]'
			]
		];
		$validation =  \Config\Services::validation();
		$validation->setRules($aRules);
		if(!$validation->run($this->request->getVar())){
			echo '<pre>';
			print_r($validation->getErrors());
			echo '</pre>';
		}`

**Comment by jahmedk** [comment]
![image](https://user-images.githubusercontent.com/22505794/106364988-60f4f100-6354-11eb-9ce8-f185765a5cdd.png)

**Comment by paulbalandan** [comment]
`IncomingRequest::getVar()` will search in the `$_REQUEST` array. I believe you want to search in the `$_FILES` array instead. So you should use `$this->request->getFile('user.img')`.

**Comment by jahmedk** [comment]
It looks like I have to verify twice or merge both array (`IncomingRequest::getVar()` `$this->request->getFile`), i think CI 4 form validator should handle this, a new rule might make it easier for something like if_file_exist

**Comment by paulbalandan** [comment]
But if you use `$this->request->getFile` will that solve your issue?

Let's have the others say on `if_file_exist`, @michalsn ?

**Comment by michalsn** [comment]
Right now, the only rules that are supported when working with files are listed under [rules for file upload](https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#rules-for-file-uploads).

The good way to solve this is probably to prepare a correctly formatted array from `$_FILES` (key => file name) and include it to the request data. Having separate rules versions for files would be a headache.

Not sure if we should do it automatically when using `withRequest()` call. We can add an optional parameter to this method (but it will be a BC). Maybe creating a separate method that will add prepared `$_FILES` array to the validated data (`withRequestAndFiles()`) have more sense.

**Comment by jahmedk** [comment]
Okay, I wanted some way to make the file validation optional :)

**Comment by kenjis** [comment]
Please submit feature requests to our [forum](https://forum.codeigniter.com/forum-29.html).
We use github issues to track bugs and planned work.
