### ISSUE TITLE
Bug: Upgrading from 4.0.4 to 4.0.5 is not complete

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#4212]
**Describe the bug**
https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_405.html says only `app/Config/Services.php`.
And https://codeigniter4.github.io/CodeIgniter4/installation/installing_composer.html#upgrading says
> Read the upgrade instructions, and check designated app/Config folders for affected changes.

But not only `app/Config/Services.php`, the following files are modified in `app`: 
```
4.0.5/app/Config/App.php
4.0.5/app/Config/Autoload.php
4.0.5/app/Config/Boot/development.php
4.0.5/app/Config/Boot/production.php
4.0.5/app/Config/Boot/testing.php
4.0.5/app/Config/Cache.php
4.0.5/app/Config/Constants.php
4.0.5/app/Config/ContentSecurityPolicy.php
4.0.5/app/Config/Database.php
4.0.5/app/Config/DocTypes.php
4.0.5/app/Config/Email.php
4.0.5/app/Config/Encryption.php
4.0.5/app/Config/Events.php
4.0.5/app/Config/Exceptions.php
4.0.5/app/Config/Filters.php
4.0.5/app/Config/ForeignCharacters.php
4.0.5/app/Config/Format.php
4.0.5/app/Config/Generators.php
4.0.5/app/Config/Honeypot.php
4.0.5/app/Config/Images.php
4.0.5/app/Config/Kint.php
4.0.5/app/Config/Logger.php
4.0.5/app/Config/Migrations.php
4.0.5/app/Config/Mimes.php
4.0.5/app/Config/Modules.php
4.0.5/app/Config/Pager.php
4.0.5/app/Config/Paths.php
4.0.5/app/Config/Routes.php
4.0.5/app/Config/Security.php
4.0.5/app/Config/Services.php
4.0.5/app/Config/Toolbar.php
4.0.5/app/Config/UserAgents.php
4.0.5/app/Config/Validation.php
4.0.5/app/Config/View.php
4.0.5/app/Controllers/BaseController.php
4.0.5/app/Controllers/Home.php
4.0.5/app/Views/errors/cli/error_404.php
4.0.5/app/Views/errors/cli/error_exception.php
4.0.5/app/Views/errors/html/debug.css
4.0.5/app/Views/errors/html/debug.js
4.0.5/app/Views/errors/html/error_exception.php
```

**CodeIgniter 4 version**
4.0.5, 4.1.1

**Affected module(s)**
User Guide

**Expected behavior, and steps to reproduce if appropriate**
A clear and concise description to upgrade.

**Comment by MGatner** [comment]
None of the changes made to **app** are breaking changes, so the existing versions will work fine. There are always likely going to be files in **app** changed and I don't know that we want to enumerate all of them unless they would otherwise affect behavior.

@paulbalandan & I have both published tools to help with migrating non-system folders, but maybe we should make a general note in the User Guide about this being up to the developer?

**Comment by MGatner** [comment]
Here's my example of patching a project - I think this one was actually `4.0.3` but you get the idea: https://github.com/codeigniter4projects/playground/pull/25/commits/28d086f35312b5be3400a643cad6760659d5e9ca

**Comment by kenjis** [comment]
Corrected modified file list:
```
4.0.5/LICENSE
4.0.5/README.md
4.0.5/app/Config/App.php
4.0.5/app/Config/Autoload.php
4.0.5/app/Config/Boot/development.php
4.0.5/app/Config/Boot/production.php
4.0.5/app/Config/Boot/testing.php
4.0.5/app/Config/Cache.php
4.0.5/app/Config/Constants.php
4.0.5/app/Config/ContentSecurityPolicy.php
4.0.5/app/Config/Database.php
4.0.5/app/Config/DocTypes.php
4.0.5/app/Config/Email.php
4.0.5/app/Config/Encryption.php
4.0.5/app/Config/Events.php
4.0.5/app/Config/Exceptions.php
4.0.5/app/Config/Filters.php
4.0.5/app/Config/ForeignCharacters.php
4.0.5/app/Config/Format.php
4.0.5/app/Config/Generators.php
4.0.5/app/Config/Honeypot.php
4.0.5/app/Config/Images.php
4.0.5/app/Config/Kint.php
4.0.5/app/Config/Logger.php
4.0.5/app/Config/Migrations.php
4.0.5/app/Config/Mimes.php
4.0.5/app/Config/Modules.php
4.0.5/app/Config/Pager.php
4.0.5/app/Config/Paths.php
4.0.5/app/Config/Routes.php
4.0.5/app/Config/Security.php
4.0.5/app/Config/Services.php
4.0.5/app/Config/Toolbar.php
4.0.5/app/Config/UserAgents.php
4.0.5/app/Config/Validation.php
4.0.5/app/Config/View.php
4.0.5/app/Controllers/BaseController.php
4.0.5/app/Controllers/Home.php
4.0.5/app/Views/errors/cli/error_404.php
4.0.5/app/Views/errors/cli/error_exception.php
4.0.5/app/Views/errors/html/debug.css
4.0.5/app/Views/errors/html/debug.js
4.0.5/app/Views/errors/html/error_exception.php
4.0.5/composer.json
4.0.5/env
4.0.5/license.txt
4.0.5/phpunit.xml.dist
4.0.5/public/.htaccess
4.0.5/public/index.php
4.0.5/spark
```

Most of the files are changed comments only. So we probably do not need to enumerate them.

But wouldn't it be better to enumerate the following files?
They update some functionality or fix bug.

- `app/Views/*`
- `public/index.php`
- `public/spark`
- `phpunit.xml.dist`

**Comment by Lorenz512** [comment]
@MGatner 
> None of the changes made to app are breaking changes, so the existing versions will work fine. [...] but maybe we should make a general note in the User Guide about this being up to the developer?

Mentioning this within the documentation, maybe even within the [upgrade notes](https://codeigniter.com/user_guide/installation/upgrading.html#upgrading-from-a-previous-version), would be great.
I was not entirely sure and had been searching for this exact statement.

**Comment by najdanovicivan** [comment]
@MGatner I've previously suggested having those configs extend default config classes which should be located in CodeIgniter\Config namespace. 

The issue here can happen if a new config property is added. It will not be present anywhere in the App\Config which can be a breaking change. Having default always available will make it possible to use just overrides in App\Config or event don't use App\Config and only put configs in the .env file

**Comment by MGatner** [comment]
@najdanovicivan Absolutely I think this is a great idea. Nobody has taken it on as a whole but @mostafakhudair has done this with a number of the configs when splitting them out and cleaning up.
