### ISSUE TITLE
Documentation: multiple databases setup in the ENV also need to be setup in the database config file

### ISSUE THREAD

**Issue by kaosweaver** [codeigniter4/CodeIgniter4#4218]
**Describe the bug**
The documentation for the ENV file doesn't explicitly state that the setup for databases needs to match the database config file setup (even though the entries are empty in the database config file, they're still mandatory)

**CodeIgniter 4 version**
CI4.0.4, docs

**Expected behavior, and steps to reproduce if appropriate**
On this page: https://codeigniter.com/user_guide/database/configuration.html#configuring-with-env-file

It should be changed from:

"As with all other"

To:

"Each database setup inside the .env file must also have a corresponding entry in the configuration folder's database file. The entries names must match. If you have two database connections you want to setup in the .env file,it will look like:"
```
database.default.hostname = 127.0.0.1
database.default.username = something1
database.default.password = somepass1
database.default.database = somedatabase1
database.default.DBDriver = MySQLi

database.second.hostname = 127.0.0.1
database.second.username = something1
database.second.password = somepass1
database.second.database = somedatabase2
database.second.DBDriver = MySQLi
```
And then the app/config/database.php file will look like:

```
public $default = [
    'DSN'      => '',
    'hostname' => '',
    'username' => '',
    'password' => '',
    'database' => '',
    'DBDriver' => '',
    'DBPrefix' => '',
    'pConnect' => TRUE,
    'DBDebug'  => TRUE,
    'charset'  => 'utf8',
    'DBCollat' => 'utf8_general_ci',
    'swapPre'  => '',
    'encrypt'  => FALSE,
    'compress' => FALSE,
    'strictOn' => FALSE,
    'failover' => [],
];
public $second = [
    'DSN'      => '',
    'hostname' => '',
    'username' => '',
    'password' => '',
    'database' => '',
    'DBDriver' => '',
    'DBPrefix' => '',
    'pConnect' => TRUE,
    'DBDebug'  => TRUE,
    'charset'  => 'utf8',
    'DBCollat' => 'utf8_general_ci',
    'swapPre'  => '',
    'encrypt'  => FALSE,
    'compress' => FALSE,
    'strictOn' => FALSE,
    'failover' => [],
];
```

**Comment by paulbalandan** [comment]
The user's `.env` file is just meant to **fill in the values** for your config files so that you can actually leave the actual config file empty and write your secrets in the `.env` file. Being such, in order for your `.env` to fill in the values, you need the config files to actually have the "container" for those values, which is/are the corresponding property/(ies). But, yeah, for the sake of clarity we may need to discuss this in the docs.

Take note that this does not only apply to database config. It also applies to other configs fillable by `.env`, which are actually classes extending `CodeIgniter\Config\BaseConfig`.

**Comment by kaosweaver** [comment]
I'm new to using .env files and without the help in the forum, I would have never known this was the issue (until I went to the system folder and walked the code to see what was happening) - more documentation for explicit things like this would be good.

**Comment by MGatner** [comment]
Agreed, need some general docs on `.env` behavior. And to get rid of that strange "As with other" 🤔
