### ISSUE TITLE
Bug: cannot resolve Services::xxx()

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#4220]
**Describe the bug**

```php
$request = Services::request();
```
PhpStorm says:
> Method 'request' not found in \Config\Services

PHPStan says:
> phpstan: Call to an undefined static method Config\Services::request().

**CodeIgniter 4 version**
develop branch, 4.0.5, 4.1.1

**Affected module(s)**
Services

**Expected behavior, and steps to reproduce if appropriate**
No errors on static analysis.

**Context**
- OS: [macOS 10.15.7]
- Web server [PHP built-in]
- PHP version [7.4.13]

**Comment by iRedds** [comment]
Now App\Config\Services extends from CodeIgniter\Config\BaseServices instead of CodeIgniter\Config\Services
Even if the IDE does not see the method, it will still be called.

**Comment by kenjis** [comment]
This is because of #3943

**Comment by kenjis** [comment]
The problem is I have to see yellow code in PhpStorm.
My CI build is broken, because PHPStan reports many errors.
