### ISSUE TITLE
Bug: getFileMultiple expects an "0" index but string is given

### ISSUE THREAD

**Issue by jcnmulio** [codeigniter4/CodeIgniter4#4221]
When I submit a multiple file upload with an index string, the FileCollection thow an error because it expects a "0" index to validate if the file is an instace of UploadedFile.

**Example**: I upload a file with name: file[161222884111885wQEcg7]. The index is 161222884111885wQEcg7, but de FileCollection class at line 40 do this:

```
return (is_array($uploadedFile) && ($uploadedFile[0] instanceof UploadedFile)) ?
					$uploadedFile : null;
```

So that make an 500 error "Undefined offset: 0", beacause $uploadedFile[0] does not exists

The version of CodeIgniter is **4.0.4**

It affect the **CodeIgniter\HTTP\Files\FileColletion class**

I think that the validation should be done by extracting the key from the current position of the array. Something like:

```
return (is_array($uploadedFile) && ($uploadedFile[key($uploadedFile)] instanceof UploadedFile)) ?
					$uploadedFile : null;
```

Regards

**Comment by sfadschm** [comment]
How about using the `array_first_key()`? A new rector rule for that was recently merged.

**Comment by jcnmulio** [comment]
Hi, I think it's a good point, but array_key_first is only available from PHP 7.0 to above. If there's no problem with that that's fine, but maybe the solution should be backward compatible.

**Comment by paulbalandan** [comment]
Starting `4.1.0`, CI4 only supports PHP >= 7.3. So we can use the `array_key_first()` here. If you can send a PR, that'd be great.

**Comment by jcnmulio** [comment]
PR done!

Thx
