### ISSUE TITLE
Bug: CodeIgniter 4.1.1 - csrf token is always regenerated

### ISSUE THREAD

**Issue by dcygan** [codeigniter4/CodeIgniter4#4224]
Csrf token is always regenerate even the variable $regenerate = false in Config\Security.

**CodeIgniter 4 version**
 4.1.11

**Comment by paulbalandan** [comment]
Can you provide your test code? There's no change in the current behavior of the CSRF token generation so this is unexpected.

**Comment by dcygan** [comment]
It tests it on a fresh version 4.1.1 without any changes. 
I noticed that the csrf cookie is not being added. I had no problem with that in version 4.0.4
