### ISSUE TITLE
Cache unable to write to /var/www/html/ci4test/writable/cache/ 

### ISSUE THREAD

**Issue by web4r** [codeigniter4/CodeIgniter4#4227]
hello i want to ask, my problem install codeigniter 4 in centos 8 

![Screen Shot 2021-02-04 at 15 57 48](https://user-images.githubusercontent.com/73053939/106868871-e3d5cd00-6701-11eb-9dd1-633006c66a97.png)

permission in writable 777
my .env change CI_ENVIRONMENT = development 
im access via <ippublic>/project-name/publik folder

**Comment by kenjis** [comment]
Please ask support questions on our [forum](https://forum.codeigniter.com/forum-30.html).
We use github issues to track bugs and planned work.

**Comment by Rarach28** [comment]
hi, any solution?

**Comment by ViniciusFernan** [comment]
chmod 777 -R /var/www/html/ci4test/writable/cache/
change the access permission to the cache folder by the terminal of the container

**Comment by ayushsonone07** [comment]
its very easy to solve :
just go to your project folder -> right click -> permission -> change permission from read only to read & write.
