### ISSUE TITLE
make:scaffold input information is missing 

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#4230]
![imagen](https://user-images.githubusercontent.com/4117596/106953677-43c77600-66f8-11eb-8ff9-22de326bbc3b.png)

Hello it seems that it is necessary to put what it is about each that asks for the entry of the name of: migrations / models / controllers etc.

`Migration name:`
`Model name:`
.....

**Comment by paulbalandan** [comment]
Definitely! I've missed reviewing that part in the big refactor. Thanks.

**Comment by luispastendev** [comment]
@paulbalandan TY 👍

**Comment by luispastendev** [comment]
It was just what we needed. Thank you very much for your time.
