### ISSUE TITLE
Feature: add old data in afterUpdate model event

### ISSUE THREAD

**Issue by oleg1540** [codeigniter4/CodeIgniter4#4234]
I want to check if the value of a field has changed in model event **afterUpdate** for do something. But eventData contains only 
>**data** = the key/value pairs being updated.

Maybe add current row(s) (data before update) in eventData? Something like this:
>**oldData** = the row(s) with old data (before update)

It will allow to follow for changes of fields values.

**Comment by iRedds** [comment]
To have old data, you need to make a query before updating, but not everyone wants this behavior.
Therefore, you better define the events of the model yourself and perform the manipulations you need.

**Comment by MGatner** [comment]
@iRedds is correct: Model events are limited to what they already have without issuing additional queries. You could certainly implement this yourself, but ti does not fit in the framework.
