### ISSUE TITLE
Dev: Restrictions on trait "ResponseTrait"

### ISSUE THREAD

**Issue by DOCHIS** [codeigniter4/CodeIgniter4#4238]
About files : /system/API/ResponseTrait.php

---

For issues where description only supports string in ResponseTrait trait
I checked the following issues
#2176
#1702
#420

Especially "failValidationError" 
In the case of functions, aren't there many cases where the description is an array?

Arrays are supported in the "fail" function,
Wouldn't it be nice if it was improved to allow returning arrays from other functions in trait?

---

Have a nice day
Thank you

**Comment by MGatner** [comment]
It might be nice, but the string-only version is published and would require a major version because updating the signature would break any existing extensions: https://3v4l.org/s2L1T

**Comment by MGatner** [comment]
If you feel strongly about this them raise some discussion on the forums and we can add it as a request for the version 5 brainstorm: https://github.com/codeigniter4/CodeIgniter4/projects/6
