### ISSUE TITLE
Bug: Session issue with CI Environment set to Testing (CI4)

### ISSUE THREAD

**Issue by DOCHIS** [codeigniter4/CodeIgniter4#4248]
**Describe the bug**
This is an issue with the post in the forum.
https://forum.codeigniter.com/thread-77859.html
There is an opinion from "includebeer" that this issue is a bug

Can you tell me if that code is a bug or what kind of problem it is trying to solve?
  .
  .
  .
**CodeIgniter 4 version**
CI4 4.1.1
  .
  .
  .
**Affected module(s)**
system/Session/Session.php
Line 1020 ~ 1024
```
protected function startSession()
	{
		if (ENVIRONMENT === 'testing')
		{
			$_SESSION = [];
			return;
		}

		// @codeCoverageIgnoreStart
		session_start();
		// @codeCoverageIgnoreEnd
	}
```
  .
  .
  .
**Expected behavior, and steps to reproduce if appropriate**
Same as forum post.

When CI_ENVIRONMENT is set to "testing" in the ".env" file,
"session" is continuously initialized and the session cannot be used.
  .
  .
  .
**Context**
 - OS: Windows 10 (64Bit) / Mac Bic Sur 11.2
 - Web server : Apache 2.4
 - PHP version : PHP 7.4.12 / PHP 7.4.13

**Comment by kenjis** [comment]
It seems this is CI4 specification.
`testing` is special environment for PHPUnit testing.
You can't use it for other purpose.

**Comment by kenjis** [comment]
@DOCHIS What's your problem?
You could change from `testing` to `test` or something.
Do you have to use `testing` for your development?

**Comment by DOCHIS** [comment]
Oh I understand
I just wondered if it was a bug that the session was initialized when ENVIRONMENT was testing.

If it is a spac, we will set it as 'test' and produce it.

Thank you.
Have a nice day.
