### ISSUE TITLE
QBSelect, QBFrom, other properties cannot be accessed, modified from the model.

### ISSUE THREAD

**Issue by x1250** [codeigniter4/CodeIgniter4#4255]
I think is relevant to not have that big limitation anymore.

**Comment by kenjis** [comment]
What do you want to do from the model?

**Comment by paulbalandan** [comment]
Why do you need to access the DB's internals from the model?

**Comment by paulbalandan** [comment]
Please provide your use case of exposing those to the public API. Closing for now.
