### ISSUE TITLE
Bug: Fabricator::fake() function is breaking when it returns an array

### ISSUE THREAD

**Issue by caswell-wc** [codeigniter4/CodeIgniter4#4261]
**Describe the bug**
I have a test that uses the `fake()` function from the `test` helper. I am passing in a Fabricator class that has a `fake()` method which currently returns an array.
When I try to run this test, I am getting this error:
```
TypeError : method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given
 /var/www/html/vendor/codeigniter4/framework/system/Test/Fabricator.php:440
 /var/www/html/vendor/codeigniter4/framework/system/Test/Fabricator.php:502
 /var/www/html/vendor/codeigniter4/framework/system/Test/Fabricator.php:409
 /var/www/html/vendor/codeigniter4/framework/system/Test/Fabricator.php:544
 /var/www/html/vendor/codeigniter4/framework/system/Helpers/test_helper.php:40
 /var/www/html/tests/database/RoleModelTest.php:156
```
I can fix this by casting the array as an object but the documentation says that it needs to return an array so either there's a bug in the code or the documentation needs to be updated.

**CodeIgniter 4 version**
v4.1.1

**Affected module(s)**
CodeIgniter\Test\Fabricator::makeArray()

**Expected behavior, and steps to reproduce if appropriate**
I would expect the fake data to be created and passed back to my test.

**Context**
 - OS: CentOS 8
 - Web server: Apache 2.4.37
 - PHP version: 8.0.2

**Comment by paulbalandan** [comment]
Can you give your test script?

**Comment by caswell-wc** [comment]
My test function looks like this:

```
 /** @test */
    public function removeUsersCanRemoveAllUsersFromARole() {
        $role = fake(RoleFabricator::class);
        $user = fake(UserFabricator::class);

        $this->hasInDatabase('user_role', [
            'user_id' => $user->id,
            'role_id' => $role->id
        ]);

        $this->roleModel->removeAllUsers($role->id);

        $this->dontSeeInDatabase('user_role', ['role_id' => $role->id]);
    }
```

The fabricator looks like this:
```
class RoleFabricator extends RoleModel {

    /**
     * Build a fake role
     *
     * @param $faker
     * @return array
     */
    public function fake(&$faker) {
        return [
            'name'        => $faker->regexify('[a-zA-Z ]+'),
            'description' => $faker->sentence,
            'slug'        => $faker->unique()->regexify('[a-z]+_[a-z]+')
        ];
    }
}
```
This is just one example. This happens anywhere I am using a Fabricator with a `fake()` method within the `fake()` helper method. This was working fine when I was running CodeIgniter 4.0.5. It was only after upgrading to 4.1.1 that I had a problem. Changing my Fabricator to this does fix it:
```
class RoleFabricator extends RoleModel {

    /**
     * Build a fake role
     *
     * @param $faker
     * @return object
     */
    public function fake(&$faker) {
        return (object)[
            'name'        => $faker->regexify('[a-zA-Z ]+'),
            'description' => $faker->sentence,
            'slug'        => $faker->unique()->regexify('[a-z]+_[a-z]+')
        ];
    }
}
```

But that's not what the documentation shows.

**Comment by paulbalandan** [comment]
Confirmed this is an issue with PHP 8 changing the behavior of method_exists to strictly check the type of the first argument to be either object or string.
