### ISSUE TITLE
Unable to reset psw on CI Forums :: Unable to create a new account either

### ISSUE THREAD

**Issue by ZoeFken** [codeigniter4/CodeIgniter4#4273]
As this is the only way of contacting the team behind CI4 i see no other way then this to let you know that the reset psw function is not working on your forum. 

Reset : ok
Link in email : ok
New psw : not ok
Error message on forum : Authorization code mismatch. Are you accessing this function correctly? Please go back and try again.

When I tried to create a new account to address this issue I could not seem to register a new account. Every username I tried was invalid. 

Username tried : ZoeFken, Zoefken1, 1ZoeFken, 1zoef, zoef1

**Comment by paulbalandan** [comment]
Did you try to hard reset your browser's cache?

**Comment by ZoeFken** [comment]
I tried to ctrl + F5 but if it is required to hard reset my browser cache I stil believe their is a major bug :D

**Comment by paulbalandan** [comment]
This `Authorization code mismatch` is a problem with MyBB, which runs the forums. So there's nothing we can do with it. I myself also experiences this occasionally when trying to sign in. So I just do it over and over until it passes.

**Comment by ZoeFken** [comment]
Wow a known issue that prevents new users to make a account and old users from resetting theirs. Switch to a diffrent system.

**Comment by sfadschm** [comment]
> This `Authorization code mismatch` is a problem with MyBB, which runs the forums. So there's nothing we can do with it. I myself also experiences this occasionally when trying to sign in. So I just do it over and over until it passes.

I have this, too. Everytime I try to log in, the error appears, but so far, the second try was always successful. I thought it has something to do with my Browser settings deleting every cookie, website setting and everything else when closing.

**Comment by sfadschm** [comment]
https://community.mybb.com/thread-218862.html
This looks quite recent to me.
Btw., who is taking care of the forums?

**Comment by paulbalandan** [comment]
Lonnie is taking care of the forums.

Closing as this is out of scope.
