### ISSUE TITLE
Model Alternative Keys

### ISSUE THREAD

**Issue by EpicKris** [codeigniter4/CodeIgniter4#428]
Models currently use the primary key for a variety of its methods including `save()`, it would be useful to also be able to specify an alternative key (or keys) that rarely change. For example; a country or currency alpha code, or a URL slug, etc…

If this is something that's agreed I can implement this and create a pull request.

**Comment by lonnieezell** [comment]
I'm good with that. Go for it. :)

**Comment by Ema4rl** [comment]
I think it's absolutely necessary. Implement please!

**Comment by lonnieezell** [comment]
Was never implemented properly and it's been over a year. Closing.
