### ISSUE TITLE
Bug: getVar does not look at $_SESSION as documentation suggests

### ISSUE THREAD

**Issue by lovetoast** [codeigniter4/CodeIgniter4#4284]
Request class, getvar - does not look at $_SESSION superglobal  as documentation states.

**CodeIgniter 4 version**
Which version (and branch, if applicable) the bug is in.
LATEST BRANCH and version

https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/HTTP/RequestTrait.php

See populateglobals above, it should reference $_SESSION

**Comment by MGatner** [comment]
Where do you see that? I don't see SESSION included on the lists:

> The getVar() method will pull from $_REQUEST, so will return any data from $_GET, $POST, or $_COOKIE.

**Comment by paulbalandan** [comment]
There is nothing in the documentation saying that `$_REQUEST` contains the `$_SESSION` variable. Even the PHP doc does not mention it being included, only `$_GET`, `$_POST`, and `$_COOKIE` and defaults to `GP` in `php.ini`.

Perhaps you are confused with `$_SESSION` instead?

**Comment by lovetoast** [comment]
Apologies for the delay, I am quite certain the documentation says it here:

_You can retrieve input from $_SERVER, $_GET, $_POST, $_ENV, and $_SESSION through the Request object. The data is not automatically filtered and returns the raw input data as passed in the request. The main_

https://codeigniter4.github.io/userguide/incoming/incomingrequest.html

From this page

**Comment by lonnieezell** [comment]
The current docs are [here](https://codeigniter.com/user_guide/incoming/incomingrequest.html). They also state $_SESSION but that is a mistake. This method was never meant to retrieve information from the session. The user guide needs updating.

**Comment by kenjis** [comment]
I'll take care of this.

**Comment by kenjis** [comment]
Done! #4321

**Comment by MGatner** [comment]
Thanks @kenjis
