### ISSUE TITLE
Bug: FeatureTest dies when throws RedirectException/cached page

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#4288]
**Describe the bug**
`CodeIgniter::run()` may call `exit()` and if you hit the point, FeatureTest (phpunit) dies.

https://github.com/codeigniter4/CodeIgniter4/blob/18d0c3cfa4b765d2cb3b7dd662b03643e818a006/system/CodeIgniter.php#L328
https://github.com/codeigniter4/CodeIgniter4/blob/18d0c3cfa4b765d2cb3b7dd662b03643e818a006/system/CodeIgniter.php#L345
https://github.com/codeigniter4/CodeIgniter4/blob/18d0c3cfa4b765d2cb3b7dd662b03643e818a006/system/CodeIgniter.php#L1139-L1144

**CodeIgniter 4 version**
develop branch

**Affected module(s)**
CodeIgniter.php, Tests

**Expected behavior, and steps to reproduce if appropriate**
phpunit does not die.

**Context**
- OS: [macOS 10.15.7]
- Web server [n/a]
- PHP version [7.4.15]

**Comment by MGatner** [comment]
The method description says

> Made into a separate method so that it can be mocked during testing without actually stopping script execution.

Is the issue that this mocking is not happening by default for Feature Test Cases?

**Comment by kenjis** [comment]
@MGatner Yes.

See
- https://github.com/kenjis/ci4-4288/blob/main/tests/feature/RedirectExceptionTest.php
- https://github.com/kenjis/ci4-4288/blob/main/app/Controllers/Test.php

```
$ composer test
> phpunit
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

.. (phpunit died)
```

**Comment by MGatner** [comment]
We have **system/Test/Mock/MockCodeIgniter.php** but I see it isn't being used. It isn't immediately apparent to me how we would inject that during CIUnitTest but I believe that is the solution.

**Comment by kenjis** [comment]
@MGatner Thank you for the info.
I will look into it.

**Comment by kenjis** [comment]
See #4315
