### ISSUE TITLE
Bug: FeatureTest cannot assert Status(404)

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#4306]
**Describe the bug**
If you `call()` 404 URI (controller or method does not exist), `CodeIgniter\Exceptions\PageNotFoundException` is thrown.
So we can't write an assertion like `$result->assertStatus(404);`.

**CodeIgniter 4 version**
develop branch.

**Affected module(s)**
Test

**Expected behavior, and steps to reproduce if appropriate**
We can write  an assertion like `$result->assertStatus(404);`.

**Context**
- OS: [macOS 10.15.7]
- Web server [n/a]
- PHP version [7.4.15]

**Comment by kenjis** [comment]
Is throwing exception intentional?

CodeIgniter4/FeatureTestCaseTest.php at 6e1163f57bc65413f215ef0a34c1cedf4f127952 · codeigniter4/CodeIgniter4
https://github.com/codeigniter4/CodeIgniter4/blob/6e1163f57bc65413f215ef0a34c1cedf4f127952/tests/system/Test/FeatureTestCaseTest.php#L249-L253

**Comment by MGatner** [comment]
Yes this is expected because CodeIgniter.php is actually watching for that exception explicitly:
```

		try
		{
			return $this->handleRequest($routes, $cacheConfig, $returnResponse);
		}
		catch (RedirectException $e)
		{
			$logger = Services::logger();
			$logger->info('REDIRECTED ROUTE at ' . $e->getMessage());

			// If the route is a 'redirect' route, it throws
			// the exception with the $to as the message
			$this->response->redirect(base_url($e->getMessage()), 'auto', $e->getCode());
			$this->sendResponse();

			$this->callExit(EXIT_SUCCESS);
		}
		catch (PageNotFoundException $e)
		{
			$this->display404errors($e);
		}
```
