### ISSUE TITLE
Bug: require the unused namespace

### ISSUE THREAD

**Issue by fanqingxuan** [codeigniter4/CodeIgniter4#4309]
**Direction**

**Describe the bug**
require a unused namespace

`use CodeIgniter\HTTP\RedirectResponse;` on line 21 in file system/CodeIgniter.php
**CodeIgniter 4 version**
release-4.0.5

no effect with normal code run.

**Comment by paulbalandan** [comment]
Can you open a PR?

**Comment by fanqingxuan** [comment]
change to open a pr
