### ISSUE TITLE
Bug: DB Forge does not support adding composite foreign keys

### ISSUE THREAD

**Issue by najdanovicivan** [codeigniter4/CodeIgniter4#4310]
**Direction**
It's impossible to add composite foreign key using forge

**Describe the bug**
I need to add the foreign key on multiple columns like this

```
  CONSTRAINT fk_column
     FOREIGN KEY (column1, column2)
     REFERENCES parent_table (column1, column2)
     ON UPDATE CASCADE
     ON DELETE CASCADE
```
Executing forge produces error when following is used

```
$this->forge->addForeignKey('column1,column2', 'parent_table', 'column1,column2', 'cascade', 'cascade')
```

**CodeIgniter 4 version**
dev-master

**Affected module(s)**
Database

This Issue is just to be noted. I'll work on the solution when I'm available. 

Related to:
#4120 
#4115

**Comment by paulbalandan** [comment]
Fixed in #4932
