### ISSUE TITLE
Bug: $model->errors() produce output when no error

### ISSUE THREAD

**Issue by hurtsky** [codeigniter4/CodeIgniter4#4323]
**Describe the bug**
`$model->errors()` produce output of  `array(1) { ["CodeIgniter\Database\MySQLi\Connection"]=> string(0) "" }` even no validation errors
I believe this happen after this merged https://github.com/codeigniter4/CodeIgniter4/pull/4312

**CodeIgniter 4 version**
develop

**Expected behavior, and steps to reproduce if appropriate**
should return empty string only

**Context**
 - Win 10 Pro
 - Apache 2.4.46
 - PHP version 7.4.11

**Comment by MGatner** [comment]
Ah good catch! I will add a check for empty message. I guess we are missing a test case as well.
