### ISSUE TITLE
Implement default fields escaping configuration in Model

### ISSUE THREAD

**Issue by reinaldorauch** [codeigniter4/CodeIgniter4#4339]
Edit: I thought that it was an undocumented feature to define the default for controlling the escaping of the fields in the model but now understanding more about the code i that it was not the case. So im proposing this to implement this feature to set the defaults  for escaping the fields.

An example of a situation that this is desired if you have a table

```SQL
CREATE TABLE a_test (
  id INT UNSIGNED AUTO_INCREMENT,
  bit_value BIT(2) NOT NULL
) engine = innodb;
```

If you escape the value going to bit_value, lets say it must be 0, it will become the string '0', that, in MySQL it converts to the binary value of the '0' that is not b'0' and therefore borking the insert.

If i could define the default for the escape in the model as below:

```php
<?php
// ...
class TestModel extends Model {
    // ...
    protected $escape = [
        'bit_value' => false
    ];
    // ...
}
```

It would help me to use the default save, insert and update methods defined in Model.

I opened the #4340 PR to implement this issue. 

Any thoughts on this will be welcome

**Comment by kenjis** [comment]
It seems nobody needs this.
Close.

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
