### ISSUE TITLE
Bug: prepared statement execute() returns Result object for all queries

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#4342]
**Describe the bug**
In the CI4 spec, `query()` returns bool for write-type queries.
But the current implementation of `execute()` returns Result object for all queries.

Isn't it a bug?

See <https://github.com/codeigniter4/CodeIgniter4/pull/4176#issuecomment-784805837>.

**CodeIgniter 4 version**
develop branch.

**Affected module(s)**
Database

**Expected behavior, and steps to reproduce if appropriate**
The same as `query()` return value.

**Comment by michalsn** [comment]
Yes, for write-type queries we should have a boolean result.

**Comment by sclubricants** [comment]
Does https://github.com/codeigniter4/CodeIgniter4/pull/6750 close this?

**Comment by kenjis** [comment]
Yes.

**Comment by kenjis** [comment]
Closed by #6750
