### ISSUE TITLE
Discussion: Exception Design

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#4358]
The current exception classes are not neatly categorized, and when creating a new exception class, it is difficult to determine which exceptions to inherit and implement.

Also, when throwing exceptions, it is sometimes difficult to determine which exceptions to throw.

Click and see the class diagram:
![class dia](http://www.plantuml.com/plantuml/png/nLV1Zjem4BtlL_0BlVMuBRje8z62AEg9Y-iCgONjGUE987_VD0ZBLXIyGGxSCiz-yzuC7bkyEXR4jT4lKWldPdCieQYiOg3TNCY_i7i_IpYoGkikW8zdS6QmfPjjQilA10lA73KOi9p8vpyBoq1x8U6bRoCsuBYlFxIP52ifz3iHKY9njDSd7cJEbqN8RiDqLr8EqEvLDKrnY0S5dqwz867WX7IuQVrDiFWZ70HCZtaexkJ0kV2qrD5GryyxsAcY-umnHO-RYKJ6yMFnXYUhKPJtsnYlRYKrtRQ8wz47Mbae3IwWTS2pzNyYBx2svMDzC53if8Dw7X9tK7vdI4PmoBiWapOdVRyzKFu3BJH737lWiQV_F1_RxJfWTN7crwBuyjK6h2xEBM545SzXXunNoT_W9LOXgGsprXuHVhImdYxzMbGtxhPLpQlzz_zhBdyNM-c-5yfSwWPhZdaRA1M1vBxGs4GjajtlBv0rAMu2fiUoIpaNl_TNABFGRw5LAJZMycX-EGMdIAYDfnkWRng8qtypUYDYW2gmiXcaHjENVjewJWGF7UxNDgwD_WS0)
[source](http://www.plantuml.com/plantuml/uml/nLV1Rjim3BtdA_mBk-tOBMrG0zrQPCLElMWoumcLn82YaVhlvsge8ALJjHXoSZEVzVWUQL62hnmBui7erKfguLopnWxQtYe6UbeB-HkURbuax5cXTN-143Vmmc0xrsm7oyf4BvJPQp1WkP0lFBQMWNP2mhzi90OS7-ld5vDY9OM-8K8g94xMXiHPvlgkZTbJMEvAoG7QdUgNAGxnMS5_fzwGC710UlxG-hLWyKiuY9W12r3QoSo-2BJIrb1lZpFOkQBpZ5EAdZyJQSQPOt6D1wjHTBDjp52taaQ_BE46z8nMDag3YsWUkBJ-T-GD3hOxhmy6IfruwDX3-GogxGp924wCUUHipIcSRylBtwA5SOySCGDsySzp-_Zu4B5yNFcsQ3zzjX7BnxKbZEZJEVJ8V9Lw3Rx3FYPDOStQKyAt2TRBfNyG_GTds_t0zxklh-zSzIvwwNTUg7AfMnoEU5le587azqAd9V98TRy_G0waU8oO0QikvLnwtxz1bOL-2gqwmQbMGElBAJX4B1ylDq1VD11dVpFo8sA0Uh1op5AJwIjVRPwJmBdDtQok9kJr7_4F)

In addition, the following questions arise.
- What is the difference between `AlertError`, `CriticalError`, and `EmergencyError`?
- What is the difference between an exception that extends `Error` and an exception that extends `Exception`?
- What is the difference between exceptions placed in `CodeIgniter/Exceptions/` and exceptions placed in components such as `CodeIgniter/Filters/`?
- In what cases do we implement `ExceptionInterface`?
- What is the `FrameworkException`?
- Do we need `CodeIgniter\Cache\Exceptions\ExceptionInterface`?
- Shouldn't there be `LogicException`?

Another problem that has been found is that the exceptions thrown by database-related classes are disparate and not standardized. See #4331

It seems to me that we need to classify the exception classes in a way that is easy to understand, and also indicate what kind of exceptions we throw.

What are your thoughts?

**Comment by MGatner** [comment]
I think @paulbalandan spent quite a bit of time on this recently, and on framework exceptions in general. I agree that the chart makes it clear this is quite a mess and some standardization is in order. I expect that changing thrown types counts as a breaking change, so we may be limited to some degree on what we can patch in the short term, but let's plan for a full overhaul in version 5.

**Comment by kenjis** [comment]
Why `DatabaseException` extends `Error`?

- [Throwable](https://www.php.net/manual/en/class.throwable.php)
   - [Error](https://www.php.net/manual/en/class.error.php)
       - [ArithmeticError](https://www.php.net/manual/en/class.arithmeticerror.php)
       - [AssertionError](https://www.php.net/manual/en/class.assertionerror.php)
       - [CompileError](https://www.php.net/manual/en/class.compileerror.php)
       - [TypeError](https://www.php.net/manual/en/class.typeerror.php)
       - [ValueError](https://www.php.net/manual/en/class.valueerror.php)
       - [UnhandledMatchError](https://www.php.net/manual/en/class.unhandledmatcherror.php)
       - [FiberError](https://www.php.net/manual/en/class.fibererror.php)
   - [Exception](https://www.php.net/manual/en/class.exception.php)

See https://www.php.net/manual/en/language.errors.php7.php#language.errors.php7.hierarchy

`Error` is not `Exception`. But `DatabaseException` seems to be a Runtime Exception.

**Comment by MGatner** [comment]
I have no idea why it was coded this way, perhaps @lonnieezell can chime in. I just spent some time reading up on best practices for this in PHP and here's what I've come to...

Errors were a hard failure point but at some point they were changed to be catchable. Because `catch (Exception $e)` is such a common practice PHP decided that an Error should *not* be included in that so defined a new superclass `Throwable`. This entire distinction appears to be a historical progression that we inherit today, and while there isn't community consensus on this most people stick to Exceptions and leave Errors for internal functions. This is also my recommendation. 

Now: can we do this in a way that isn't massively breaking? My guess is that developers who are catching these currently are either using `Throwable` or `DatabaseException`, which will both still work. But anyone catching `Error` will not.

**Comment by kenjis** [comment]
> most people stick to Exceptions and leave Errors for internal functions. This is also my recommendation.

I agree. I would like to remove throwing Error classes in the framework.

**Comment by kenjis** [comment]
I have created PR #8470.
The exception or parent class changes a little, but it does not seem to break existing apps in most cases.
What do you think? @codeigniter4/core-team

**Comment by kenjis** [comment]
I sent #8728
Please review.

**Comment by kenjis** [comment]
Closed by #8728
