### ISSUE TITLE
Bug: Minimum PHP Version Discrepancy

### ISSUE THREAD

**Issue by tyea** [codeigniter4/CodeIgniter4#4361]
**Describe the bug**
There is a discrepancy between the `$minPHPVersion` variables in `public/index.php` and `spark`. One sets a value of `7.3` whereas the other sets a value of `7.2`.

**CodeIgniter 4 version**
4.1.1

**Expected behavior, and steps to reproduce if appropriate**
I think both variables should set a value of `7.3` as this is the minimum PHP version specified in the documentation.

**Context**
 - https://github.com/codeigniter4/CodeIgniter4/blob/5e852b39f99df9df9a5a9ff35de4eb7bcacb39bc/public/index.php
 - https://github.com/codeigniter4/CodeIgniter4/blob/5e852b39f99df9df9a5a9ff35de4eb7bcacb39bc/spark
 - https://www.codeigniter.com/user_guide/intro/requirements.html

**Comment by totoprayogo1916** [comment]
closed by #4217
