### ISSUE TITLE
Feature: In HTTP Feature Testing, delivering in body in application/json format

### ISSUE THREAD

**Issue by ByeongUkChoi** [codeigniter4/CodeIgniter4#4362]
Post in forum
https://forum.codeigniter.com/thread-77210.html

HTTP Feature Testing Dosc
https://codeigniter4.github.io/userguide/testing/feature.html#

```php
// Submit a form
$result = $this->call('post', 'contact'), [
    'name' => 'Fred Flintstone',
    'email' => 'flintyfred@example.com'
]);
```
It's only populated $_POST
We use "$request->getPost();"
But not working "$request->getJSON();"

What should I do to send JSON format in http feature testing?

**Comment by kenjis** [comment]
See <https://codeigniter4.github.io/userguide/testing/feature.html#formatting-the-request>.

**Comment by ByeongUkChoi** [comment]
> See https://codeigniter4.github.io/userguide/testing/feature.html#formatting-the-request.

I missed that part, Thanks, a lot :)

**Comment by kenjis** [comment]
@ByeongUkChoi Nobody's perfect. ;-)
