### ISSUE TITLE
Bug: Filter in routes doesn't work if user input url in different case

### ISSUE THREAD

**Issue by adidesember** [codeigniter4/CodeIgniter4#4369]
If I use filter in routes, for example: `$routes->get('admin/home/x1', 'admin\home: x1', ['filter' => 'fil']);`
its works if user open the url with lowercase letters only (https://localhost/public/admin/home/x1), 

but if the user opens the url in uppercase letters (https://localhost/public/admin/HOmE/X1) then the filter does not work and this I think to be unsafe. sorry for my bad english

![Capture2](https://user-images.githubusercontent.com/22036666/109438850-5cf4e580-7a5e-11eb-93a5-eaee48c32c5c.PNG)

![Capture](https://user-images.githubusercontent.com/22036666/109438853-5e261280-7a5e-11eb-92a3-1a0280fcb719.PNG)

**Comment by paulbalandan** [comment]
No feedback and stale. Closing.
