### ISSUE TITLE
Bug: set404Override now working in group rotes

### ISSUE THREAD

**Issue by Gh-Moradi** [codeigniter4/CodeIgniter4#4400]
I set the set404Override in group rotes, But it does not work and gives an error.
```
$routes->group('panel', ['filter' => 'role:Writer'], function($routes) {
	$routes->setDefaultNamespace('App\Controllers\Panel');
	$routes->set404Override('Show404::index');
	$routes->get('home', 'Home::index');
	$routes->get('posts', 'Post::index');
	// And more...
});
```

But when I set it like this it works right:

```
$routes->set404Override('App\Controllers\Panel\Show404::index');
```

Is this a bug? or am i wrong?

I using this platform:
CodeIgniter 4 version
 - OS: Windows 10
 - Web server Apache 2.4.41
 - PHP version 7.3.11

**Comment by paulbalandan** [comment]
Thanks @iRedds for the explanation. Closing this.
