### ISSUE TITLE
MySQLi Forge support ZEROFILL attribute

### ISSUE THREAD

**Issue by element-code** [codeigniter4/CodeIgniter4#4402]
Support zerofill in mysqli forge, maybe as value for `unsigned`.
```php
'postalCode' => [
	'type' => 'INT,
	'constraint' => 5,
	'unsigned' => 'ZEROFILL',
	'null' => TRUE,
]
```

The current workaround adding the attribute as part of `type` is kinda nasty.
https://forum.codeigniter.com/thread-70075.html?highlight=zerofill

```php
'postalCode' => [
	'type' => 'INT(5) ZEROFILL',
	'unsigned' => TRUE,
	'null' => TRUE,
],
```

**Comment by iRedds** [comment]
As far as I understand, zerofill only supports MySQL.
That is, it can change the behavior of your application when changing the DBMS.
I think in this case you would be better off using mutation (getters) in the entity to convert the number to a string with a leading zero.

**Comment by kenjis** [comment]
Yes, ZEROFILL is MySQL specific.
`Forge` should not support it.
