### ISSUE TITLE
FeatureTest currently supports file testing? 

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#4405]
FeatureTest currently supports file testing? or how you could simulate the loading of a file given a path and using a. 

```php
        $this->withHeaders(
             ['Content_Type' => 'multipart/form-data']
         )->call('post', 'path/', [
             'file' => SUPPORTPATH . "assets/test_video.mp4"
         ]);
```

grettings!!

**Comment by paulbalandan** [comment]
Please raise support questions in the [forum](https://forum.codeigniter.com). Closing this.
