### ISSUE TITLE
Bug: log_message passed object

### ISSUE THREAD

**Issue by John-Betong** [codeigniter4/CodeIgniter4#4407]
**Info**
I have been trying for over a week to trace a new site's "Network connection Error"  from going down overnight. No errors in logs so added "strict_types=1" to all PHP app and system PHP files, also set .env -> CI_ENVIRONMENT = development and eventually managed to get some errors reported.

**Describe the bug**
  Incorrect type passed when error encountered. Trying to pass Object instead of a string type to log_message(...);

**CodeIgniter 4 version**
  CI_VERSION - 4.1.1

**Expected behavior, and steps to reproduce if appropriate**
I expected an error to be logged. 

**Affected module(s)**
  ./system/Database/MYSQLI/Connection.php
[code]
public function execute(string $sql)
	{
		while ($this->connID->more_results())
		{
			$this->connID->next_result();
			if ($res = $this->connID->store_result())
			{
				$res->free();
			}
		}
		try
		{
			return $this->connID->query($this->prepQuery($sql));
		}
		catch (mysqli_sql_exception $e)
		{
			# PROBLEM 2021-03-09 ==> $e is an Object and string required
			log_message('error', $e->getMessage());
			# log_message('error', $e);
			
			if ($this->DBDebug)
			{
				throw $e;
			}
		}
		return false;
	}
[/code]

**Context**
 - Web server [e.g. Apache 2]
 - PHP version [8.0.3]
 - Site: https://ci4-strict.tk

**Comment by MGatner** [comment]
Looks like a mistake there! Could you submit this as a PR?
