### ISSUE TITLE
Running via CLI - Only Default Controller works

### ISSUE THREAD

**Issue by arielcannal** [codeigniter4/CodeIgniter4#4415]
Please ask support questions on our [forum](https://forum.codeigniter.com/forum-30.html).
We use github issues to track bugs and planned work.
I'm using version 4.1.1, and when I run the application via CLI / CRON, on Linux (cPanel), the framework loads only Default Controller, ignoring the parameters passed on the CRON command line:
/usr/local/bin/ea-php74 /home1/agille54/api/public/index.php tray api

When testing execution on my local Windows (WAMP), via CMD, I have no problems.
The Controller and method exist and are correct. On Windows it works. Via Browser / Chrome, it also works.
I imagine it is something related to the Linux environment, or to some PHP configuration in this environment.

**Comment by arielcannal** [comment]
I found that the problem occurs when the application's ENVIRONMENT is "testing".

**Comment by MGatner** [comment]
You should probably never set the environment to testing. This is designed specifically to work with unit tests and can definitely mess things up.

**Comment by arielcannal** [comment]
Thank you very much! I did not know...

**Comment by sfadschm** [comment]
> You should probably never set the environment to testing. This is designed specifically to work with unit tests and can definitely mess things up.

Can we maybe add that to the docs? I think there was several issues in the past due to this misunderstanding.

**Comment by lonnieezell** [comment]
It's in the docs, see: https://codeigniter.com/user_guide/general/environments.html
