### ISSUE TITLE
Bug: can't run `spark migrate` on CI server

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#4428]
**Describe the bug**
It is similar to #4033 and #3309.

```
CodeIgniter v4.1.1 Command Line Tool - Server Time: 2021-03-14 12:58:03 UTC+09:00

ERROR: 404
コントローラまたはそのメソッドが見つかりません。: \App\Controllers\Cimigrate::index
```

**CodeIgniter 4 version**
develop branch (after 4.1.1)

**Affected module(s)**
spark

**Expected behavior, and steps to reproduce if appropriate**
Run `php spark migrate` on CI server.

**Context**
 - OS: Ubuntu 20.04
 - Web server n/a
 - PHP version 7.3.27

**Comment by kenjis** [comment]
Does someone know why this `if` is needed?
https://github.com/codeigniter4/CodeIgniter4/blob/bc4da069a806e9695de6f18538d244125982e4b2/system/CodeIgniter.php#L508-L511

**Comment by paulbalandan** [comment]
I think that is a remnant of using Travis CI for testing before. But not sure though.

**Comment by MGatner** [comment]
Has anyone tried this without that CI override?
