### ISSUE TITLE
Request: Feature Test Optimization

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#4438]
Feature tests are really slow. It is not unusual for a single test to take up to 2 seconds. I have optimized my set up as best I can, running database migrations & seeds once but the tests are still magnitudes slower than other tests.

If anyone has experience analyzing PHP runtimes to figure out where our bottlenecks are, improving execution in the framework would be a huge resource savings trickling down to all projects.

**Comment by kenjis** [comment]
You can profile with Xdebug.
See <https://xdebug.org/docs/profiler>.

**Comment by lonnieezell** [comment]
I've never had the chance but at some point would like to dive deep into the database layer as that seems the slowest link. And I don't think it's just the database connection. 

I'm assuming you're using an in-memory SQLite db for your tests already?

**Comment by MGatner** [comment]
Yea this is with SQLite, memory, and `$migrateOnce` and `$seedOnce`. Similar non-feature tests run very quickly - it is definitely something else happening. 

@kenjis Thanks for the tip! I already use Xdebug a lot so I will look into this profiler.

**Comment by MGatner** [comment]
I believe the suggestions here are sufficient tools for anyone looking to optimize their projects.
