### ISSUE TITLE
Bug: Queries with LOWER( throwing errors 

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#4443]
Using the latest develop branch, I am seeing a query that worked in 4.1 now fail. 

Here's a test case that's failing with the error: `SQLite3::query(): Unable to prepare statement: 1, unrecognized token: ":"`

```
public function testWhereWithLower()
	{
		$this->db->table('job')
		         ->insert([
			         'name'        => 'Brewmaster',
			         'description' => null,
		         ]);

		$jobs = $this->db->table('job')
		                 ->where('LOWER(job.name)', 'brewmaster')
		                 ->get()
		                 ->getResult();

		$this->assertCount(1, $jobs);
	}
```

**Comment by lonnieezell** [comment]
@paulbalandan I know you did some work on the `setBinds` method recently. Any ideas what might have changed on this?

**Comment by paulbalandan** [comment]
Not sure what's the problem but the recent changes only to setBinds is how it stores the binds. Oh, also how it recognizes a named bind. I'll look into this.
