### ISSUE TITLE
Bug: modules - config - constants not loaded

### ISSUE THREAD

**Issue by ZoeFken** [codeigniter4/CodeIgniter4#4447]
**Describe the bug**
When I create a module in my application and I add the autoload function. I then add the 'constants' to the aliases in the modules.php config file. The constants file in my modules>folder>config>constants.php is not beeing loaded.

**CodeIgniter 4 version**
Master

**Affected module(s)**
All my modules (did not yet test if other configs have the same issue.

**Expected behavior, and steps to reproduce if appropriate**
I expected the constants.php to be loaded once the module was called on.

**Comment by kenjis** [comment]
`APPPATH . 'Config/Constants.php'` is loaded in the bootstrap.
And there is no documentation for constants in modules.

It seems there is no functionality for constants in modules.
So this is not a bug.

**Comment by ZoeFken** [comment]
There is documentation about auto loading config files in modules.

**Comment by kenjis** [comment]
> No special change is needed when working with configuration files. These are still namespaced classes and loaded with the new command:

You need to `new` the config class. The `Constants.php` is not a class.
So it seems the config files in the user guide are only Config classes.

**Comment by ZoeFken** [comment]
Then this should be altered. There can be a usecase for constants in modules.

**Comment by MGatner** [comment]
I agree that constants should have representation in the Modules config. This will take implementing though, not a simple change.

**Comment by lonnieezell** [comment]
Constants is currently an app-specific setting. While it might be nice to change that up, can you not define those constants in whatever config file the module has?

**Comment by ZoeFken** [comment]
I can and I did (as to the lack of any other solution). Yet I believe that it should be defined in a constants file, The modules structure is made to reflect the main app structure. So every deviation of that path is a problem in my opinion.
