### ISSUE TITLE
Bug: results on getX() not equal 

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#4452]
At the doc: https://codeigniter4.github.io/userguide/libraries/time.html#viewing-differences
![image](https://user-images.githubusercontent.com/2387514/111739663-025ce580-88b6-11eb-996e-e3562b6426ee.png)

**Describe the bug**
The result is not equal,
one is positive value
and the other is negative value

```PHP
echo $diff->getSeconds();
// return: -220924800

echo $diff->seconds;
// return: 220924800
```

**CodeIgniter 4 version**
v4.1.1

**Comment by kenjis** [comment]
I think the property value is a bug. The user guide is correct.
See #4453
