### ISSUE TITLE
Bug: PHPStorm anlysis fault

### ISSUE THREAD

**Issue by InsiteFX** [codeigniter4/CodeIgniter4#4474]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
phpStorm is flagging these to lines in the Model as ERRORS.
$this->db says to make it public there is no $db in the top values

**CodeIgniter 4 version**
Newest Development version today.

**Affected module(s)**
system/Model

**Expected behavior, and steps to reproduce if appropriate**
Should have no errors

**Context**
 - OS: Windows 10 x64 20H2
 - Web server Apache 2.3.46
 - PHP version 8.0.3

`	public function __construct(ConnectionInterface &$db = null, ValidationInterface $validation = null)
	{
		parent::__construct($validation);

		/**
		 * @var BaseConnection $db
		 */
		$db = $db ?? Database::connect($this->DBGroup);

		$this->db = &$db; <-- ERROR
	}
`
And here.

`	public function builder(?string $table = null)
	{
		// Check for an existing Builder
		if ($this->builder instanceof BaseBuilder)
		{
			// Make sure the requested table matches the builder
			if ($table && $this->builder->getTable() !== $table)
			{
				return $this->db->table($table);
			}

			return $this->builder;
		}

		// We're going to force a primary key to exist
		// so we don't have overly convoluted code,
		// and future features are likely to require them.
		if (empty($this->primaryKey))
		{
			throw ModelException::forNoPrimaryKey(static::class);
		}

		$table = empty($table) ? $this->table : $table;

		// Ensure we have a good db connection
		if (! $this->db instanceof BaseConnection)
		{
			$this->db = Database::connect($this->DBGroup); <-- ERROR
		}

		$builder = $this->db->table($table);

		// Only consider it "shared" if the table is correct
		if ($table === $this->table)
		{
			$this->builder = $builder;
		}

		return $builder;
	}
`

Says to make them public but if you look at the top of the Model there is no $db defined.

**Comment by kenjis** [comment]
@InsiteFX Thank you for your report.
I sent PR.

**Comment by InsiteFX** [comment]
Well the Commit is not working so I have reported this to phpStorm to find an answer to this problem.

Thing is it never showed this until the latest CodeIgniter build.

**Comment by MGatner** [comment]
The latest version of the branch removed the `@mixin Model` from `BaseBuilder` which should never have been there to begin with. It was causing segmentation faults in PHPStan. As noted on the PR, this issue is actually a bug with PHPStorm. I'm curious to see what comes of it! Please link any relevant tickets here so we can track.

**Comment by InsiteFX** [comment]
Ok, here is an update I loaded the same project from March 8, 2020 and guess what no phpStorm errors.

So it looks like something that has been changed in the latest build in the models is causing the errors.

**Comment by MGatner** [comment]
@InsiteFX most definitely: it was the bug I mentioned above, just fixed in #4480. Have you heard anything back from PHPStorm?

**Comment by InsiteFX** [comment]
Yes, they wanted to know what database class was being used.

But get this now I downloaded the latest build last night was late installed it this morning and no more errors,
very strange.

**Comment by MGatner** [comment]
> downloaded the latest build

The latest of PHPStorm? If so then hopefully that means they fixed it, that would be great!

**Comment by kenjis** [comment]
#4491

**Comment by InsiteFX** [comment]
MGatner, the bug won't show up until you open the system/Model then it will go red error.
