### ISSUE TITLE
Bug: Filter is not work !

### ISSUE THREAD

**Issue by xgdd1987** [codeigniter4/CodeIgniter4#4482]
**Describe the bug**

Filters do not intercept default controllers and methods .

**CodeIgniter 4 version**
4.1.1

**code**
Config/Filter.php :
`public $filters = ['isLoggedIn' => ['before' => ['admin/*']]];`

If I visit xxxx.com/admin , the filter will not intercept. Default page xxxx.com/admin/home/index Will be accessed.

**Context**
 - OS: [e.g. Windows 99]
 - Web server [e.g. Apache 1.2.3]
 - PHP version [e.g. 6.5.4]

**Comment by MGatner** [comment]
Filters are very literal matches. If you have `admin/*` it will NOT match `admin` because there is no trailing slash on URI segments. Try changing your filter to apply to `admin*` and let me know if that fixes it.

**Comment by MGatner** [comment]
@xgdd1987 please confirm this is an actual issue and not just an implementation mistake.

**Comment by xgdd1987** [comment]
When accessing the default page /admin，can the framework get the default controller and method /admin/welcome/index, and then filter it?

**Comment by paulbalandan** [comment]
No word from the OP. This seems to be not a framework issue.
