### ISSUE TITLE
Bug: Session removeTempdata() method not accepting arrays.

### ISSUE THREAD

**Issue by zoruz** [codeigniter4/CodeIgniter4#4490]
**Describe the bug**
Its annoying using multiple removeTempdata() statements. this method should accept arrays.

**CodeIgniter 4 version**
4.1.1

**Comment by MGatner** [comment]
This is not a bug, it is a complaint. If you would like it to be a feature request (which I think is reasonable) then create a forum post first and get some feedback - or skip that step and create the PR yourself. Hint: we cannot change the signature on the method, probably make a new method.
