### ISSUE TITLE
Bug: Differences in file names created with  CLI command

### ISSUE THREAD

**Issue by datamweb** [codeigniter4/CodeIgniter4#4495]
**Describe the bug**
Hi, @paulbalandan
I use CLI for create, modal, seed and ...
When I give the name as **TestModal** but the corresponding file with the name **Testmodal** is created in the directories.

**CodeIgniter 4 version**
4.1.1

**Affected module(s)**
CLI

**Expected behavior, and steps to reproduce if appropriate**
step 1 : php spark make:modal
Step 2 : **TestModal**
Step 3 : Files are created  but named **Testmodal**.
This problem exists for other commands(make:seeder ,make:filter and ...) as well. 

**Context**
 - OS: [Windows 10]
 - Web server [Apache 2.0 Handler]
 - PHP version [8.0.0]

**Comment by paulbalandan** [comment]
@datamweb thanks for the report. it seems the culprit is in `GeneratorTrait::qualifyClassName()`. I'll look into the issue this weekend.
