### ISSUE TITLE
Bug: Filter controller does not work for controllers in the sub-folder

### ISSUE THREAD

**Issue by muh-ramadhan** [codeigniter4/CodeIgniter4#4501]
**Describe the bug**
User 1 can still access the user controller 2 (Userb/*) with a display without CSS but all methods in the controller can be executed by user 1, even though in the display console 500 (internal server error).
When I tried the Controllers without sub folders, the Filter worked properly.

Filters
https://pastebin.com/YMB3wCBS

My Filter
FiterlUserb https://pastebin.com/Y0Xyt4TN
FiterlUserb https://pastebin.com/1FWkPjvw

Controller
Login https://pastebin.com/cBWUnBw2

**CodeIgniter 4 version**
Codeigniter 4.1.1

**Affected module(s)**
Which package or class is the bug in, if known.

**Expected behavior, and steps to reproduce if appropriate**
Log https://pastebin.com/xZDmrk3V

**Context**
 - OS: Windows 10 Pro 64-bit (10.0, Build 18363)
 - xampp-windows-x64-8.0.2-0-VS16
 - Web server Apache/2.4.46 (Win64)
 - PHP Version 8.0.2
 - Microsoft Edge Version 89.0.774.63 (Official build) (64-bit)

**Comment by muh-ramadhan** [comment]
![image](https://user-images.githubusercontent.com/47452507/112761767-06f86b00-9027-11eb-86f6-4a5be0daff44.png)

This Page Should Not Show
The Filters Work Properly If I Use The Controller Without A Folder

**Comment by muh-ramadhan** [comment]
![image](https://user-images.githubusercontent.com/47452507/112762029-f85e8380-9027-11eb-97ab-6a648ab5d6b3.png)

This Page Should Not Show
The Filters Work Properly If I Use The Controller Without A Folder

**Comment by MGatner** [comment]
Your code is too much for me to distill into an actual issue. If you could demonstrate this with a minimum code example that would help. 

Also just to clarify: does "subfolded" refer to your project, or the controllers within your project?

**Comment by paulbalandan** [comment]
Stale issue. Closing.
