### ISSUE TITLE
Bug: return $this->failValidationError($validation->getErrors()) Has Invalid Signature

### ISSUE THREAD

**Issue by adamfisher** [codeigniter4/CodeIgniter4#4506]
The documentation for **[return $this->failValidationError($validation->getErrors());](https://codeigniter4.github.io/userguide/outgoing/api_responses.html#failValidationError)** shows this line is working in the documentation but in reality, I keep getting a 500 error. I am trying to build some validation for my REST API.

But if I pass the following manually then the list of validation errors returns successfully:

```php
return $this->fail($this->validator->getErrors());
```

**CodeIgniter 4 version**
4.1.1

**Affected module(s)**
**`trait ResponseTrait`**

**Expected behavior, and steps to reproduce if appropriate**
Create a POST method in a controller like this and it will fail with 500:

```php
    public function create()
    {
        if($this->validate('vendor')) {
            $vendor = $this->request->getJSON();
            $this->model->insert($vendor);
            return $this->respondCreated();
        }
        return $this->failValidationError($this->validator->getErrors());
    }
```

but change the last line to this:

```php
return $this->fail($this->validator->getErrors());
```

and you successfully get back:

```json
{
    "status": 400,
    "error": 400,
    "messages": {
        "first_name": "The first_name field may only contain alphabetical characters.",
        "last_name": "The last_name field may only contain alphabetical characters.",
        "account_type": "The account_type field must be one of: checking,savings.",
        "signature_date": "The signature_date field must contain a valid date."
    }
}
```

**Context**
Docker Image: `webdevops/php-apache-dev:7.4`

**Comment by kenjis** [comment]
It seems the sample code is not correct.
https://github.com/codeigniter4/CodeIgniter4/blob/f19fe3627aeaa46fc77c55305e490ab49e46c02d/tests/system/API/ResponseTraitTest.php#L326-L342
