### ISSUE TITLE
Bug: Model::_call() static analysis

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#4509]
**Describe the bug**
With the removal of `@mixin Model` from `BaseBuilder`, magic calls to Model that match a `BaseBuilder` method will now "return" that method's type, causing subsequent calls too create static analysis issues. For example:
```php
$users = model(UserModel::class)->where('name', 'Bob');
```
`$users` is now a `Model` with its `$builder` property primed for the criterium, but because the `@mixin BaseBuilder` matched `BaseBuild::where(): self` PHPStan thinks `$users` is `BaseBuilder`. So calling a model method after this:
```php
$user = $users->first();
```
... will cause static analysis to complain:

> Call to an undefined method CodeIgniter\Database\BaseBuilder::first()

I have tried a few things, like adding `@method` to Model, but thus far I don't see a good solution.

**CodeIgniter 4 version**
`develop` latest

**Affected module(s)**
`Model`, `BaseBuilder`

**Context**
 - OS: Ubuntu
 - Web server: Apache
 - PHP version: 7.4

**Comment by WinterSilence** [comment]
@MGatner https://phpstan.org/developing-extensions/dynamic-return-type-extensions

**Comment by MGatner** [comment]
Thanks @WinterSilence I will take a look

**Comment by WinterSilence** [comment]
@MGatner [for example](https://github.com/phpstan/phpstan-nette/tree/master/src)

**Comment by paulbalandan** [comment]
Did you try adding an inline phpdoc?
```php

/** @var \CodeIgniter\Model $users */
$users = (new UserModel)->where('name', 'foo');
$users->first();
```

PHPStan respects inline types regardless of the `treatPhpDocTypesAsCertain` setting.

**Comment by MGatner** [comment]
@paulbalandan yes that was just an example. We've created this issue for ever Model in all projects, so we need to come up with a solution. @WinterSilence 's suggestion of a template I think will be the way to go, but I haven't had time to dig into it yet.

**Comment by WinterSilence** [comment]
@MGatner "don't need to dig, just replace `Nette\Utils\Html`/`Html` in [example ](https://github.com/phpstan/phpstan-nette/tree/master/src/Reflection/Nette)(:

**Comment by jozefrebjak** [comment]
@MGatner is there some solution to this issue ?

**Comment by MGatner** [comment]
@jozefrebjak I have not researched a templates solution at all.

**Comment by kenjis** [comment]
@WinterSilence 
>  don't need to dig, just replace Nette\Utils\Html/Html in phpstan/phpstan-nette

If you could write PHPStan extensions easily, could you write and send PR for this issue?
It is too difficult to understand.

**Comment by WinterSilence** [comment]
@kenjis you no need writes something new, just replace `Nette\Utils\Html` https://github.com/phpstan/phpstan-nette/blob/f4654b27b107241e052755ec187a0b1964541ba6/src/Reflection/Nette/HtmlClassReflectionExtension.php#L16 to your class name

**Comment by kenjis** [comment]
@WinterSilence Please, could you create a PR for us?

**Comment by kenjis** [comment]
It seems "Dynamic Return Type Extensions" does not solve the problem.
> If the return type of a method is not always the same, but depends on an argument passed to the method, you can specify the return type by writing and registering an extension.
https://phpstan.org/developing-extensions/dynamic-return-type-extensions

I propose that removing `@mixin BaseBuilder` and adding `@method` for methods which can be used in the Model.

```diff
--- a/system/Model.php
+++ b/system/Model.php
@@ -38,9 +38,10 @@ use ReflectionProperty;
  *      - allow intermingling calls to the builder
  *      - removes the need to use Result object directly in most cases
  *
- * @mixin BaseBuilder
- *
  * @property BaseConnection $db
+ *
+ * @method $this where($key, $value = null, ?bool $escape = null)
+ * @method $this select($select = '*', ?bool $escape = null)
  */
 class Model extends BaseModel
 {
```

**Comment by kenjis** [comment]
I sent a PR #5970
