### ISSUE TITLE
Array Validation Fails

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#4510]
hi there!

validation with more than 1 level only validates the first match. 

Example: 
```php
// rule
'bar.*.foo' => [
    'rules' => 'required'
]

// data
"bar" => [
  [
    'foo' => 'baz'
  ],
  [
    'foo' => ''
  ]
]
```

the above validation should fails, however it passes.  https://codeigniter4.github.io/userguide/libraries/validation.html#validating-keys-that-are-arrays

**Comment by WinterSilence** [comment]
@luispastendev is wrong record, can you public example?
~~~php
'bar.*.foo' => [
    'rules' => 'required'
]
~~~

**Comment by WinterSilence** [comment]
~~~php
$validation->setRules([
    'contacts.*.name' => 'required'
]);
~~~
not same to
~~~php
->setRules(['bar.*.foo' => ['rules' => 'required']])
~~~

**Comment by luispastendev** [comment]
@WinterSilence the same result

**Comment by WinterSilence** [comment]
@luispastendev required = not empty:
~~~php
\Config\Services::validation()
->setRules(['bar.*.foo' => 'required'])
->run([
    "bar" => [
        ['foo' => 'baz'],
        ['foo' => 'bar']
    ]
]); // true
~~~

**Comment by luispastendev** [comment]
@WinterSilence I think the required rule should fail if an empty value is sent. taking your examples if you try the following fails and under what you explain it should return true 

```php
$result4 = \Config\Services::validation()
    ->setRules(['bar.*.foo' => 'required'])
    ->run([
        "bar" => [
            ['foo' => ''],
            ['foo' => '']
        ]
    ]);
```

doc:

![image](https://user-images.githubusercontent.com/4117596/113601543-15d2b500-9607-11eb-9b65-3a73d8626600.png)

**Comment by WinterSilence** [comment]
@luispastendev all right, i fix my comment later

**Comment by WinterSilence** [comment]
@luispastendev but method really have other bug:
~~~php
$result = \Config\Services::validation()
    ->setRules(['bar.*' => 'required'])
    ->run(["bar" => []]); // return true
~~~

**Comment by luispastendev** [comment]
@WinterSilence right! it only works if it detects something empty `['']` that seems to be fixed with: 

```
if (is_array($value) && end($fieldNameToken) === '*' && ! empty($value))
```

but the other problem I don't know what others think, but the other problem I do not know what others think at least reading the code I do not see an intention to support that use case
