### ISSUE TITLE
Bug: failed to open stream

### ISSUE THREAD

**Issue by Fauzanarth** [codeigniter4/CodeIgniter4#4514]
Hi there!
After php spark serve run, i open localhost:8080 and there is an error like this 

**Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required 'A:\xampp\htdocs\ci4app\vendor\codeigniter4\framework\system\Commands\Server/rewrite.php' (include_path='\xampp\php\PEAR') in Unknown on line 0**

How to solve this error?

CodeIgniter 4 version
develop latest

Context

OS: Windows
Web server: Apache
PHP version: 7.3

**Comment by paulbalandan** [comment]
Please ask support questions in the forum.

Run `composer update`
