### ISSUE TITLE
Bug: mock single_service

### ISSUE THREAD

**Issue by gmeister2** [codeigniter4/CodeIgniter4#4515]
**Describe the bug**
Cannot mock `single_service()`

**CodeIgniter 4 version**
CI 4.1.1

**Affected module(s)**
system/Common.php -> `single_service()`
system/Config/BaseService.php -> `serviceExists()`

**Expected behavior, and steps to reproduce if appropriate**
When getting a service like this (shared instance):
`$example = service('example');`
Afterwards you can a mock this when testing with:
`Services::injectMock('example', $example);`

When getting a service like this (new instance):
`$example = single_service('example');`
Creating a mock when testing is not possible with:
`Services::injectMock('example', $example);`

**Comment by MGatner** [comment]
Mocked services only apply to shared instances, whereas `single_service()` is explicitly for acquiring non-shared instances:

> Always returns a new instance of the class.

I'm not saying this is the most desirable behavior but whoever created Services built it this way, it is not a bug.

**Comment by gmeister2** [comment]
Ok, thanks for your answer. I was unsure whether to label this as a bug or a feature request. My confusion stems from the documentation under Test / Mocking Services, my understanding was that mocking would apply to all Services.

**Comment by MGatner** [comment]
I agree that mocking being for "shared only" is unintuitive and I would support such a feature request. If you wish to pursue this please post it on the forums (you can link it here) to gather feedback. I am curious whether the team would consider this a breaking change given that some developers may be using mocking with the understanding that it *won't* affect their new instances?

**Comment by gmeister2** [comment]
Link to forum:
http://forum.codeigniter.com/forum-29.html
