### ISSUE TITLE
Bug: Unable to use debugger toolbar on a live server

### ISSUE THREAD

**Issue by DrAliRagab** [codeigniter4/CodeIgniter4#4516]
**Describe the bug**
I was using debugger toolbar and it was working well at `localhost`. But when trying to use the toolbar at live server it don't work.
Ci4 on development mode.
I tried to debug the problem but with no luck. 

![Screenshot 2021-04-05 003510](https://user-images.githubusercontent.com/37520558/113522376-9f06cf00-95a8-11eb-9cc2-48487d92acfb.png)

![Screenshot 2021-04-05 005047](https://user-images.githubusercontent.com/37520558/113522417-03c22980-95a9-11eb-8ab2-189d8c4cc074.png)

**CodeIgniter 4 version**
4.1.1

**Context**
 - OS: Ubuntu 18
 - Web server FPM served by NGINX
 - PHP version 8.0

**Comment by paulbalandan** [comment]
Does your `app.baseURL` has a port number in it?

**Comment by DrAliRagab** [comment]
> Does your `app.baseURL` has a port number in it?

No

**Comment by DrAliRagab** [comment]
I tried to add port :443 to bas link with the same error

**Comment by paulbalandan** [comment]
Is your `CI_ENVIRONMENT` set to `development`?

**Comment by paulbalandan** [comment]
Try to add port 8080 to your app base URL

**Comment by MGatner** [comment]
Paul is giving helpful troubleshooting steps, but generally: your App Config settings need to match a *reachable URL*. Check baseURL, indexPage, forceGlobalRequests; check your .htaccess rules. Anything that would cause the Toolbar URL not to be valid (or require a redirect) will keep the code from loading. 

Aside, we should probably have some JavaScript to post an alert when this happens, or at least a helpful console message.

**Comment by DrAliRagab** [comment]
Thank you for all your great help.
Due to  some technical errors in server, we go for backup and this problem just disappeared.
I don't know why and how. but everything is working fine now.
