### ISSUE TITLE
Bug: Query::matchSimpleBinds index problem only toolbar.

### ISSUE THREAD

**Issue by byazrail** [codeigniter4/CodeIgniter4#4518]
**Describe the bug**

**CodeIgniter 4 version**
4.1.1

**Expected behavior, and steps to reproduce if appropriate**
<img width="1221" alt="Screen Shot 2021-04-05 at 13 42 00" src="https://user-images.githubusercontent.com/5870455/113566366-3c97e800-9615-11eb-9bc8-e9563ece4daf.png">
<img width="869" alt="Screen Shot 2021-04-05 at 13 42 20" src="https://user-images.githubusercontent.com/5870455/113566367-3d307e80-9615-11eb-8a46-11cf6c02bba4.png">

**Context**
 - OS: [Centos 7]
 - Web server [nginx]
 - PHP version [7.3.27]

**Comment by paulbalandan** [comment]
Can you try the latest develop branch? There's already fixes for Query so maybe your issue has been fixed.

**Comment by byazrail** [comment]
> Can you try the latest develop branch? There's already fixes for Query so maybe your issue has been fixed.

I check, I will report the result.

**Comment by byazrail** [comment]
@paulbalandan It looks like it hasn't improved yet.
It gives the same error.

<img width="1284" alt="Screen Shot 2021-04-05 at 16 19 13" src="https://user-images.githubusercontent.com/5870455/113578004-d4540100-962a-11eb-8eba-73f05fbc0c6e.png">
<img width="1169" alt="Screen Shot 2021-04-05 at 16 19 08" src="https://user-images.githubusercontent.com/5870455/113578013-d74ef180-962a-11eb-9743-8f4fda160e71.png">

**Comment by byazrail** [comment]
For the workaround;
In Database\Query.php::debugToolbarDisplay;
`$sql = $this->getQuery();`
change.
`$sql = $this->getOriginalQuery();`

**Comment by paulbalandan** [comment]
Are you passing a raw SQL query or a `BaseBuilder` instance? Can you share your sql code thru the builder?

**Comment by byazrail** [comment]
> Are you passing a raw SQL query or a `BaseBuilder` instance? Can you share your sql code thru the builder?

BaseBuilder Query;
```
$builder = $this->db->table('search_mview p');
$builder->select('p.*');
$builder->where('p.locations_ids ?| ARRAY[\'639\']', null, false);
$builder->where('p.status', 1);
$builder->orderBy('p.id', 'ASC');
$builder->limit(10);
$builder->get();
```

**Comment by byazrail** [comment]
Exception Details;
![Screen Shot 2021-04-05 at 17 05 11](https://user-images.githubusercontent.com/5870455/113582492-1f711280-9631-11eb-9286-415ce6c7fe9b.png)
<img width="1005" alt="Screen Shot 2021-04-05 at 17 03 56" src="https://user-images.githubusercontent.com/5870455/113582362-f486be80-9630-11eb-8916-12672ef7794a.png">

**Comment by paulbalandan** [comment]
Ok, I'll try to replicate this. One question though as I am not that immersed in database operations. What does this mean?
```
$builder->where('p.locations_ids ?| ARRAY[\'639\']', null, false);
```

**Comment by paulbalandan** [comment]
I'm suspecting the framework is matching `?|` as a simple bind but has nothing to bind with, causing the undefined offset.

**Comment by byazrail** [comment]
> Ok, I'll try to replicate this. One question though as I am not that immersed in database operations. What does this mean?
> 
> ```
> $builder->where('p.locations_ids ?| ARRAY[\'639\']', null, false);
> ```

PostgreSQL Jsonb array filter.

<img width="1704" alt="Screen Shot 2021-04-05 at 17 11 48" src="https://user-images.githubusercontent.com/5870455/113583221-0a48b380-9632-11eb-8178-50e4ee98b8d7.png">
https://www.postgresql.org/docs/9.5/functions-json.html

**Comment by byazrail** [comment]
> I'm suspecting the framework is matching `?|` as a simple bind but has nothing to bind with, causing the undefined offset.

![Screen Shot 2021-04-05 at 17 13 12](https://user-images.githubusercontent.com/5870455/113583413-4a0f9b00-9632-11eb-9576-39c93190b24d.png)
<img width="999" alt="Screen Shot 2021-04-05 at 17 13 34" src="https://user-images.githubusercontent.com/5870455/113583422-4aa83180-9632-11eb-874a-8a5626d748f4.png">

**Comment by byazrail** [comment]
MATERIALIZED VIEW Result.
Only PostgreSQL jsonb column filter;
locations_ids etc.
![Screen Shot 2021-04-05 at 17 15 47](https://user-images.githubusercontent.com/5870455/113583719-aecaf580-9632-11eb-9ec8-44cf9fa9b02d.png)

**Comment by byazrail** [comment]
My Solution;

![Screen Shot 2021-04-05 at 17 19 55](https://user-images.githubusercontent.com/5870455/113584116-2f89f180-9633-11eb-84df-015bfccbd65c.png)

**Comment by paulbalandan** [comment]
After setting up my Postgres database, I'm using this script but I'm getting the expected empty result. No exceptions where thrown.
```php
<?php

require __DIR__ . '/system/Test/bootstrap.php';

use Config\Database;

$db = Database::connect();

$builder = $db->table('search p');
$sql = $builder
	->select('p.*')
	->where('p.location ?| ARRAY[\'639\']', null, false)
	->where('p.status', 1)
	->orderBy('p.id', 'ASC')
	->limit(10)
	->get();

var_dump($sql);

```

The dump would give me, as expected:
```
class CodeIgniter\Database\Postgre\Result#24 (8) {
  public $connID =>
  resource(78) of type (pgsql link)
  public $resultID =>
  resource(82) of type (pgsql result)
  public $resultArray =>
  array(0) {
  }
  public $resultObject =>
  array(0) {
  }
  public $customResultObject =>
  array(0) {
  }
  public $currentRow =>
  int(0)
  protected $numRows =>
  NULL
  public $rowData =>
  NULL
}
```

**Comment by byazrail** [comment]
@paulbalandan hi,

The normal query is already running.
Problems on Debug / Toolbar.
As I mentioned at the beginning.

**Comment by paulbalandan** [comment]
Confirming this issue. It seems this errors when on the browser. on CLI this works as fine.
