### ISSUE TITLE
Bug: typo error when creating a model using php spark make:model

### ISSUE THREAD

**Issue by reszko** [codeigniter4/CodeIgniter4#4525]
**Describe the bug**
The command line **php spark make:model** creates a Model File with the propertie $useSoftDelete in singular, when the correct way is in the plural, like this:

$useSoftDeletes

Because of this, that feature does not work when deleting records.

**CodeIgniter 4 version**
4.1.1

**Expected behavior, and steps to reproduce if appropriate**
$useSoftDeletes

**Context**
 - OS: [e.g. Windows 10]
 - Web server [e.g. 2.4.46]
 - PHP version [e.g. 7.3.21]

**Comment by samsonasik** [comment]
It seems already fixed in latest develop https://github.com/codeigniter4/CodeIgniter4/pull/4319
