### ISSUE TITLE
Table alias is not working with softDeletes

### ISSUE THREAD

**Issue by jahmedk** [codeigniter4/CodeIgniter4#4527]
![image](https://user-images.githubusercontent.com/22505794/113851306-cfbb5400-97b4-11eb-9542-e854ee044ffa.png)
![image](https://user-images.githubusercontent.com/22505794/113851343-d944bc00-97b4-11eb-9415-0b3b6fdf9fab.png)
![image](https://user-images.githubusercontent.com/22505794/113851575-127d2c00-97b5-11eb-89e6-d0d0c68861fa.png)

**Comment by paulbalandan** [comment]
I don't recall `Model` directly supporting table aliasing in its `$table` property. It is erroring because `$model->table` is also used in forming the complete field name, such as table.id. In your case, since you aliased it directly in the model, your id would be queried as `cities AS ct.id` which is obviously wrong since you don't have a `cities` field.

You should do the aliasing the table like this:
```php
class CitiesModel extends Model
{
    protected $table = 'cities';
    // ...
}

$builder = model('App\Models\CitiesModel')->builder('cities AS ct');
$builder->select(['ct.name']);
// ... 
```

**Comment by jahmedk** [comment]
Thanks @paulbalandan

**Comment by jahmedk** [comment]
When i set the alias according to your solution, findAll is undefined
![image](https://user-images.githubusercontent.com/22505794/113973541-ecf42f00-9855-11eb-9f9c-4a6020cf68eb.png)

**Comment by jahmedk** [comment]
When i set the alias according to your solution, findAll is undefined
![image](https://user-images.githubusercontent.com/22505794/113973857-6be96780-9856-11eb-97a2-b8fc0a23f2ea.png)

**Comment by paulbalandan** [comment]
`findAll` is a method of Model, while `$builder` is an instance of `BaseBuilder`. Do this:
```php
$model = model('App\Models\CitiesModel');

// initialize the builder's table as aliased ct
$model->builder('cities AS ct'); // notice we don't save the builder instance as compared before.

// call the model using the aliased table using builder mixin
$model->select(['ct.name']);
$model->join(...);
$model->findAll(100, 0);
```

**Comment by iRedds** [comment]
@paulbalandan In your example, if the property of the table is "cities AS ct", it will raise the error described in the issue. If the value of the table property is different, then the call to the builder ``$model->builder('cities AS ct'); `` will not change anything, since the method will return a new instance of the builder, not a shared.

**Comment by jahmedk** [comment]
Now in select alias isn't working
![image](https://user-images.githubusercontent.com/22505794/113985655-d655d400-9865-11eb-9c8b-458527742763.png)
![image](https://user-images.githubusercontent.com/22505794/113985697-deae0f00-9865-11eb-8eef-3986ec8df1ec.png)

**Comment by jahmedk** [comment]
The alias doesn't work in select 
![image](https://user-images.githubusercontent.com/22505794/113986187-64ca5580-9866-11eb-8954-f0af930d03fd.png)
![image](https://user-images.githubusercontent.com/22505794/113986208-6c89fa00-9866-11eb-8cf1-ad98de699073.png)

**Comment by paulbalandan** [comment]
Ok, I thought that would work.

**Comment by jahmedk** [comment]
Please take a look here
https://github.com/codeigniter4/CodeIgniter4/pull/4532/files
i tried to fix it

**Comment by jahmedk** [comment]
![image](https://user-images.githubusercontent.com/22505794/114065942-9ec24880-98b4-11eb-83da-d51bda79c50a.png)

**Comment by WinterSilence** [comment]
hm... you can't use whitespaces in table name, mysql not support it.

**Comment by WinterSilence** [comment]
@paulbalandan before i'm thinked whitespaces in table name not allowed, but it's not true - we must escape they.

**Comment by WinterSilence** [comment]
@jahmedk you cant use `$table = 'cities AS ct';` because it's valid name for table in mysql, need check list of db tables. you can wrap table name: `$table = '`cities` AS ct';`

**Comment by kenjis** [comment]
The property `$table` is the name of database table.
`cities AS ct` is not a table name. The Model is not a Query Builder.
We should not change the meaning of the property.

@jahmedk Why do you need to use an alias for the table `cities`?

**Comment by jahmedk** [comment]
> The property `$table` is the name of database table.
> `cities AS ct` is not a table name. The Model is not a Query Builder.
> We should not change the meaning of the property.
> 
> @jahmedk Why do you need to use an alias for the table `cities`?

I need to join with country table
![image](https://user-images.githubusercontent.com/22505794/114267648-65a1e980-9a16-11eb-8c7a-9713aa2d1234.png)

**Comment by kenjis** [comment]
You can join without an alias. 
```php
$model->select([
    'cities.name AS city',
    'c.name AS country',
]);
$model->join('countries AS c', 'cities.country_id=c.id');
```

**Comment by jahmedk** [comment]
But if i need to fetch more than 10 column and table name is large like tablenaaaaaaaaaaaame
$model->select([
    'tablenaaaaaaaaaaaame.col1',
    'tablenaaaaaaaaaaaame.col2',
    'tablenaaaaaaaaaaaame.col3',
    'tablenaaaaaaaaaaaame.col4',
    'tablenaaaaaaaaaaaame.col5',
    'tablenaaaaaaaaaaaame.col6',
    'tablenaaaaaaaaaaaame.col7',
    'tablenaaaaaaaaaaaame.col8',
    'tablenaaaaaaaaaaaame.col9',
    'tablenaaaaaaaaaaaame.col10',
    'c.name AS country',
]);
$model->join('countries AS c', 'cities.country_id=c.id');

??

**Comment by kenjis** [comment]
```php
$model->select([
   $this->table . '.col1',
   $this->table . '.col2',
   $this->table . '.col3',
   $this->table . '.col4',
   $this->table . '.col5',
   $this->table . '.col6',
   $this->table . '.col7',
   $this->table . '.col8',
   $this->table . '.col9',
   $this->table . '.col10',
   'c.name AS country',
]);
```

**Comment by jahmedk** [comment]
This will not work in controller the table is a property of model.

**Comment by iRedds** [comment]
Magic
```php
public function getColunmWithTable($column)
{
    return array_map(function($value) {
        return $this->table . '.' . $value;
    }, (array) $column);
}

$model->select($model->getColunmWithTable(['col1', 'col2']))
    ->select('c.name AS country');
```

**Comment by WinterSilence** [comment]
@iRedds why not foreach? closure better for helpers - `$closure->call($model, $columns)`
~~~php
function normalizeColumns(string ...$columns): array
{
    foreach ($columns as &$column) {
       $column = $this->table . '.' . $column;
    }

    return $columns;
}
~~~

**Comment by WinterSilence** [comment]
@ jahmedk  also in controller work:
~~~php
$columns = substr_replace($columns, $model->getTable() . '.', 0, 0);
~~~
or `table-prefix.*` :)

**Comment by michalsn** [comment]
It's not a bug. Aliases shouldn't be declared as a part of the table model.

Most of the time we want to use aliases only in particular methods. This is already possible. The simplest example will look like this:

```php
class CitiesModel extends Model
{
    protected $table = 'cities';
    ...
    public function alias()
    {
        $model = model('App\Models\CitiesModel');

        $model
            ->select('ct.name')
            ->from('cities ct', true) // simply override table and add alias for query
            ->join('countries c', 'ct.country_id = c.id')
            ->findAll(100, 0);
    }
}
```
In some cases, we also need to change a table variable, to work properly with some of the model's methods, e.g.: `find(id)`

```php
    public function alias()
    {
        $model = model('App\Models\CitiesModel');

        $model
            ->select('ct.name')
            ->from('cities ct', true) // simply override table and add alias for query
            ->setTable('ct') // override table name for use inside the model
            ->join('countries c', 'ct.country_id = c.id')
            ->find(1);
    }
```

Using aliases may look a little complicated but it is that way only when we want to use them with the model. 
In every situation like that, we should think a moment if using a model is really necessary -  creating a builder instance may be enough in many cases:

```php
    public function alias()
    {
        $builder = $this->builder('cities c');

        $builder
            ->select('ct.name')
            ->join('countries c', 'ct.country_id = c.id')
            ->get()
            ->getResultArray();
    }
```
