### ISSUE TITLE
Pager - Different url for first page

### ISSUE THREAD

**Issue by najdanovicivan** [codeigniter4/CodeIgniter4#4529]
I'm using the model pager to create pagination and I noticed the following limitation

I have the first page as

{domain}/{some-page}

Now I use pagination as
{domain}/{some-page}/page/{page-num}

The issue that in pager i get the first page as 
{domain}/{some-page}/page/1 

But i need pagination not to have /page/1 on the first page but instead link to {domain}/{some-page}

In order to have /page/ in pager i use the following 

```
$modelModel->pager->setPath(rtrim($route_to(static::class), '/') . '/page/');
```

What do you thing about adding the property string|string[] $prePaginationSegments to the pager class. So in my case I'll be setting this as 'page' instead of setting the complete path

**Comment by paulbalandan** [comment]
Please send in a PR if you want this functionality.
