### ISSUE TITLE
Bug: BaseBuilder::trackAliases()

### ISSUE THREAD

**Issue by WinterSilence** [codeigniter4/CodeIgniter4#4537]
`CodeIgniter\Database\BaseBuilder::trackAliases()` have 2 problems:
1. table name can contain whitespaces, mysql: 
~~~sql
CREATE TABLE `to do` (`id` INT(11) NULL DEFAULT NULL) COLLATE='utf8_general_ci' ENGINE=InnoDB;
~~~
2. method don't trim whitespaces when spit by comma: `trackAliases('foo, bar')` -> `trackAliases(' bar')` -> added alias `bar` to table `bar`.

**CodeIgniter 4 version**
4.1.1 (dev)

**Comment by kenjis** [comment]
`trackAliases()` is a protected method. How do you call `trackAliases('foo, bar')`?

**Comment by WinterSilence** [comment]
@kenjis by the public methods, for example https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Database/BaseBuilder.php#L592

**Comment by WinterSilence** [comment]
@kenjis P.S. you can call call protected/private methods too, reflect about it (:

**Comment by kenjis** [comment]
@WinterSilence You can't call `trackAliases('foo, bar')` by the `from()`.
Because it contains `,`.
https://github.com/codeigniter4/CodeIgniter4/blob/df8730a037eaf2a7fe3b0f2a2cd436d5692649a3/system/Database/BaseBuilder.php#L602-L611

**Comment by WinterSilence** [comment]
@kenjis ok, I miss, but it's also called in `join()`
https://github.com/codeigniter4/CodeIgniter4/blob/df8730a037eaf2a7fe3b0f2a2cd436d5692649a3/system/Database/BaseBuilder.php#L659

**Comment by kenjis** [comment]
Is it possible?
`join('foo, bar', ...)`

It seems at least there is no test code like that:
```
Method
join
Found usages
AliasTest.php
AliasTest
testAliasLeftJoinWithLongTableName
		$builder->join('users as u', 'users.id = jobs.id', 'left');
testAliasLeftJoinWithShortTableName
		$builder->join('users as u', 'u.id = jobs.id', 'left');
Builder.php
Builder
join
		return parent::join($table, $cond, $type, $escape);
FindModelTest.php
FindModelTest
testSoftDeleteWithTableJoinsFind
		$results = $this->createModel(UserModel::class)->join('job', 'job.id = user.id')->find(1);
testSoftDeleteWithTableJoinsFindAll
		$results = $this->createModel(UserModel::class)->join('job', 'job.id = user.id')->findAll();
testSoftDeleteWithTableJoinsFirst
		$results = $this->createModel(UserModel::class)->join('job', 'job.id = user.id')->first(1);
JoinTest.php
JoinTest
testFullOuterJoin
		$builder->join('users as u', 'users.id = jobs.id', 'full outer');
testJoinIsNotNull
		$builder->join('table2', 'field IS NOT NULL');
testJoinIsNull
		$builder->join('table2', 'field IS NULL');
testJoinMultipleConditions
		$builder->join('table2', "table1.field1 = table2.field2 AND table1.field1 = 'foo' AND table2.field2 = 0", 'LEFT');
testJoinSimple
		$builder->join('job', 'user.id = job.id');
testJoinWithAlias
		$builder->join('users u', 'u.id = jobs.id', 'LEFT');
JoinTest.php
JoinTest
testSimpleJoin
						->join('user', 'user.id = job.id')
```

**Comment by WinterSilence** [comment]
@kenjis never mind, i miss `https://github.com/codeigniter4/CodeIgniter4/blob/df8730a037eaf2a7fe3b0f2a2cd436d5692649a3/system/Database/BaseBuilder.php#L715 , before i thinked method can be use to build query like as `SELECT table1.column1, table2.column2 FROM table1, table2 WHERE table1.column1 = table2.column1;`

**Comment by kenjis** [comment]
It seems that it is not possible to raise an error via public methods.
