### ISSUE TITLE
Bug: Mysql connection issue with MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT 

### ISSUE THREAD

**Issue by fedeburo** [codeigniter4/CodeIgniter4#4558]
https://github.com/codeigniter4/CodeIgniter4/blob/1d40479705a531a3f98371bd12588a20f601268b/system/Database/MySQLi/Connection.php#L162-L165

Hi, i am facing a problem making a mysqli ssl connection to database. 
I am using CodeIgniter version 4, 
mysqli->client_info = "mysqlnd 7.4.3"
Database driver: "MySQLi"

The problem is that when i have the ssl_verify = false, it never gets into:
`elseif (defined('MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT') && version_compare($this->mysqli->client_info, '5.6', '>='))
					{
						$client_flags += MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT;
					}`.

The version_compare is comparing the mysqli->client_info which in my case is "mysqlnd 7.4.3" to a "5.6" and this will always return false.

Something similar is happening on line 166.

A possible fix it could be replace that part of the version_compare to:
`elseif (defined('MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT') && version_compare(preg_replace("/[a-zA-Z\s]/", "", $this->mysqli->client_info), '5.6', '>='))` 
Where there i am replacing any string and whitespace before the version number.
Would you be able to change this? If not, which could be the solution to this problem?

**Comment by paulbalandan** [comment]
Can you open a PR for this?

**Comment by fedeburo** [comment]
> Can you open a PR for this?

Ok. I am not sure if i should create a new branch or make the pull request in an existing one?

**Comment by paulbalandan** [comment]
Please create a new branch for your PR.

**Comment by fedeburo** [comment]
#4566 pull request done
