### ISSUE TITLE
Bug: Cookie path replaced with system's PATH env variable

### ISSUE THREAD

**Issue by masuraoru** [codeigniter4/CodeIgniter4#4559]
**Describe the bug**
In every request that creates a new cookie, the cookie path is replaced with the system PATH env variable.

**CodeIgniter 4 version**
develop

**Affected module**
CodeIgniter\Config\BaseConfig

**Steps to reproduce**
- open browser's dev console
- run request that **creates new** cookie
- see **path** attribute in Set-Cookie of response headers (for me it's path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin)

**Expected behavior**
- path attribute must contain value from cookie config class, e.g. '/'

**Context**
 - OS: Ubuntu 20.04
 - Apache 2.4.41
 - PHP 7.4.3

**Comment by masuraoru** [comment]
During debugging I came to the conclusion that the problem lies in CodeIgniter\Config\BaseConfig:147.
Not sure how to fix this correctly. My temporary workaround: 
replace
>$value = getenv($property);

with

> if ($property=='path') {
>     return null;
> }
>$value = getenv($property);

**Comment by totoprayogo1916** [comment]
have same issue

![image](https://user-images.githubusercontent.com/2387514/115818160-63805780-a426-11eb-9f60-1afdbcf001d9.png)
