### ISSUE TITLE
Bug: Class information on output is missing during migrate:rollback command

### ISSUE THREAD

**Issue by joelsodias** [codeigniter4/CodeIgniter4#4579]
**Describe the bug**
MigrationRunner.php removeHistory results differs from addHistory in CLI command migrate:rollback

Class information on output is missing during migrate:rollback command

**CodeIgniter 4 version**
CodeIgniter v4.1.1 Command Line Tool

**Affected module(s)**
CodeIgniter\Database\MigrationRunner::removeHistory

**Expected behavior, and steps to reproduce if appropriate**

When I execute a migration:

`codeigniter> php spark migrate

CodeIgniter v4.1.1 Command Line Tool - Server Time: 2021-04-17 19:30:03 UTC-03:00

Running all new migrations...
        Running: (App) 20210414214700_App\Database\Migrations\UserTable
        Running: (App) 20210414220000_App\Database\Migrations\UserEventsTable
        Running: (App) 20210415000000_App\Database\Migrations\CustomerTable
        Running: (App) 20210416000000_App\Database\Migrations\CustomerUsersTable
        Running: (App) 2021-04-17-213225_App\Database\Migrations\Test
`

When I execute a rollback:

`codeigniter> php spark migrate:rollback

CodeIgniter v4.1.1 Command Line Tool - Server Time: 2021-04-17 19:27:31 UTC-03:00

Rolling back migrations to batch:  1
        Rolling back: (App) 2021-04-17-213225_
        Rolling back: (App) 20210416000000_
        Rolling back: (App) 20210415000000_
        Rolling back: (App) 20210414220000_
        Rolling back: (App) 20210414214700_
Done rolling back migrations.`

As you can see, all classes information are missing

![image](https://user-images.githubusercontent.com/407522/115128810-e2086f80-9fb6-11eb-9df3-52dc466d493c.png)

**Context**
 - OS: [Windows 10]
 - Web server [Apache 2.4.41]
 - PHP version [7.4.0]

**Comment by MGatner** [comment]
I've noticed this as well! Hopefully a quick fix. Thanks for reporting!

**Comment by joelsodias** [comment]
No problem!  Glad to help!

Thanks for the great work at CodeIgniter 
I will try to help more at free time...
