### ISSUE TITLE
Model->where method does not exist

### ISSUE THREAD

**Issue by patch-lee** [codeigniter4/CodeIgniter4#4583]
Hi, CI4 Team

I just ran into a problem when calling Model->where method

When ever I called $this->where, $this->asArray()->where, or (new UserModel)->where , I would encouter an error: 500 method does not exist.

```json
    "title": "TypeError",
    "type": "TypeError",
    "code": 500,
    "message": "method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given",
    "file": "/Users/caliv3r/Documents/Works/online-training/web_api/vendor/codeigniter4/framework/system/BaseModel.php",
    "line": 1770,
    "trace": [...]
```

Here is my model
```php
<?php

namespace App\Models;

use CodeIgniter\Model;
use Exception;

class UserModel extends Model
{
	public function __construct()
	{
		helper('database');
	}

	protected $table                = 'users';
	protected $primaryKey           = 'user_id';
	protected $useAutoIncrement     = true;
	protected $insertID             = 0;
	protected $returnType           = 'array';
	protected $useSoftDelete        = true;
	protected $protectFields        = true;
	protected $allowedFields        = [
		'emp_code', 'first_name', 'last_name',
		'password', 'is_admin', 'dept_id',
		'created_by', 'updated_by', 'deleted_by'
	];

	// Dates
	protected $useTimestamps        = true;
	protected $dateFormat           = 'datetime';
	protected $createdField         = 'created_at';
	protected $updatedField         = 'updated_at';
	protected $deletedField         = 'deleted_at';

	// Validation
	protected $validationRules      = [];
	protected $validationMessages   = [];
	protected $skipValidation       = false;
	protected $cleanValidationRules = true;

	public function findUserByEmpCode(string $empCode)
	{
		$user = $this
			->asArray()
			->where(['emp_code' => $empCode])
			->first();

		if (!$user)
			throw new Exception('User does not exist for specified employee code');

		return $user;
	}

	public function findUserByEmpCodeAndPassword(string $empCode, string $password)
	{
		$user = $this
			->asArray()
			->where(['emp_code' => $empCode, 'password' => $password])
			->first();

		if (!$user) throw new Exception('Invalid Credentials');

		return $user;
	}
 }
```

I have read through CI documentation which says
`This query may be modified by interjecting Query Builder commands as needed prior to calling this method:`
```php
$users = $userModel->where('active', 1)
                   ->findAll();
```

But I can't use this method as the docs said.

What am I missing here? please kindly advice.

Thanks :)

**Comment by paulbalandan** [comment]
Can you show us the full stack trace of the exception thrown?

**Comment by paulbalandan** [comment]
And, have you tried changing the constructor to this?
```php
public function __construct($db, $validation)
{
    parent::__construct($db, $validation);
    helper('database');
}
```

**Comment by patch-lee** [comment]
> Can you show us the full stack trace of the exception thrown?

{
    "title": "Error",
    "type": "Error",
    "code": 500,
    "message": "Cannot use object of type CodeIgniter\\Database\\SQLSRV\\Result as array",
    "file": "/Users/caliv3r/Documents/Works/online-training/web_api/app/Controllers/Auth.php",
    "line": 32,
    "trace": [
        {
            "file": "/Users/caliv3r/Documents/Works/online-training/web_api/vendor/codeigniter4/framework/system/CodeIgniter.php",
            "line": 936,
            "function": "login",
            "class": "App\\Controllers\\Auth",
            "type": "->",
            "args": []
        },
        {
            "file": "/Users/caliv3r/Documents/Works/online-training/web_api/vendor/codeigniter4/framework/system/CodeIgniter.php",
            "line": 432,
            "function": "runController",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->",
            "args": [
                {}
            ]
        },
        {
            "file": "/Users/caliv3r/Documents/Works/online-training/web_api/vendor/codeigniter4/framework/system/CodeIgniter.php",
            "line": 333,
            "function": "handleRequest",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->",
            "args": [
                null,
                {
                    "handler": "file",
                    "backupHandler": "dummy",
                    "storePath": "/Users/caliv3r/Documents/Works/online-training/web_api/writable/cache/",
                    "cacheQueryString": false,
                    "prefix": "",
                    "file": {
                        "storePath": "/Users/caliv3r/Documents/Works/online-training/web_api/writable/cache/",
                        "mode": 416
                    },
                    "memcached": {
                        "host": "127.0.0.1",
                        "port": 11211,
                        "weight": 1,
                        "raw": false
                    },
                    "redis": {
                        "host": "127.0.0.1",
                        "password": null,
                        "port": 6379,
                        "timeout": 0,
                        "database": 0
                    },
                    "validHandlers": {
                        "dummy": "CodeIgniter\\Cache\\Handlers\\DummyHandler",
                        "file": "CodeIgniter\\Cache\\Handlers\\FileHandler",
                        "memcached": "CodeIgniter\\Cache\\Handlers\\MemcachedHandler",
                        "predis": "CodeIgniter\\Cache\\Handlers\\PredisHandler",
                        "redis": "CodeIgniter\\Cache\\Handlers\\RedisHandler",
                        "wincache": "CodeIgniter\\Cache\\Handlers\\WincacheHandler"
                    }
                },
                false
            ]
        },
        {
            "file": "/Users/caliv3r/Documents/Works/online-training/web_api/public/index.php",
            "line": 44,
            "function": "run",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->",
            "args": []
        },
        {
            "file": "/Users/caliv3r/Documents/Works/online-training/web_api/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php",
            "line": 45,
            "args": [
                "/Users/caliv3r/Documents/Works/online-training/web_api/public/index.php"
            ],
            "function": "require_once"
        }
    ]
}

**Comment by patch-lee** [comment]
> And, have you tried changing the constructor to this?
> 
> ```
> public function __construct($db, $validation)
> {
>     parent::__construct($db, $validation);
>     helper('database');
> }
> ```

No, I haven't tried yet.
But If that so, what arguments should I supply for `new UserModel()` ?

I'm calling UserModel in my controller.
```php
<?php

namespace App\Controllers;

use App\Controllers\BaseController;
use App\Models\UserModel;
use CodeIgniter\HTTP\ResponseInterface;
use Exception;

class Auth extends BaseController
{
	public function login()
	{
		$rules = [
			'username' => 'required',
			'password' => 'required|min_length[0]|max_length[20]'
		];

		$input = $this->getRequestInput($this->request);
		if (!$this->validateRequest($input, $rules)) {
			return $this->getResponse($this->validator->getErrors(), ResponseInterface::HTTP_BAD_REQUEST);
		}

		$userModel = new UserModel();
		try {
			// $user = $userModel->where(['emp_code', $input['username'], $input['password']])->first();
			$user = $userModel->findUserByEmpCodeAndPassword($input['username'], $input['password']);
		} catch (Exception $e) {
			return $this->getResponse(['401NF' => $e->getMessage()], ResponseInterface::HTTP_UNAUTHORIZED);
		}
                // ... rest of code
        }
}
```


Thanks for reply :)

**Comment by paulbalandan** [comment]
Yes, I forgot that. Change the parameters to nullable.
```php
public function __construct($db = null, $validation = null)
{
    parent::__construct($db, $validation);
    helper('database');
}

**Comment by patch-lee** [comment]
> Yes, I forgot that. Change the parameters to nullable.
> 
> ```
> public function __construct($db = null, $validation = null)
> {
>     parent::__construct($db, $validation);
>     helper('database');
> }
> ```

Thank you so much! worked like a charm!

Closing this issue now, thanks again for the help :)
