### ISSUE TITLE
Bug: colon issue in query binding

### ISSUE THREAD

**Issue by tibszabo-dev** [codeigniter4/CodeIgniter4#4595]
**Describe the bug**
Query binding fails when using date_format with hours in it (colon issue)

If there is a colon in the query, the query builder thinks it is a named bind, and handles the query in that way, even if you have ? bindings.

**CodeIgniter 4 version**
v4.1.1

**Affected module(s)**
system/Database/Query.php
Line 352

**Expected behavior, and steps to reproduce if appropriate**
Old version: 
`$hasNamedBinds = strpos($sql, ':') !== false && strpos($sql, ':=') === false;`
This returns true when query has `date_format(now(), '%d-%m-%Y %H:%i')`, but in the query I only use ? as binding, so it won't find any :mybind: binding.

suggestion: `$hasNamedBinds = preg_match('/:[a-z._-]+:/',$sql);`

With this fix, all my queries are working.

**Context**
 - OS: debian 10
 - Web server: Apache 2.4.38
 - PHP version: 7.3.27

**Comment by tibszabo-dev** [comment]
I saw a fix in the develop branch, I think it must be a quick patch, because 4.1.1 is getting old.

**Comment by paulbalandan** [comment]
> I saw a fix in the develop branch, I think it must be a quick patch, because 4.1.1 is getting old.

Yes, there's already a fix for the bindings. Can you check that out if it will pass with your use case?

**Comment by tibszabo-dev** [comment]
> > I saw a fix in the develop branch, I think it must be a quick patch, because 4.1.1 is getting old.
> 
> Yes, there's already a fix for the bindings. Can you check that out if it will pass with your use case?

Yes, it is working well with that fix!

**Comment by paulbalandan** [comment]
Thanks for confirming. Closing then.
