### ISSUE TITLE
Bug: Customized Validation language does not take effect

### ISSUE THREAD

**Issue by hanmoguoke** [codeigniter4/CodeIgniter4#4597]
I customized Validation.php file in App\Language\En 
eg this:

return [
   'required'              => '{field}不能为空'
]

but that looks does not take effect

I installed it by composer create-project codeigniter4/appstarter project-root

**Comment by paulbalandan** [comment]
Can you try this proposed fix?
https://github.com/codeigniter4/CodeIgniter4/issues/4318#issuecomment-790248826
