### ISSUE TITLE
Bug:   chmod 777 writable/cache fixed codeignitor install for me

### ISSUE THREAD

**Issue by davidbuzz** [codeigniter4/CodeIgniter4#4598]
**Describe the bug**
brand new to codeignitor 4, just installed it with composer:
composer create-project codeigniter4/appstarter composerstarter

visited composerstarter/public/   page in browser on localhost and got a 'whoops' page, this fixed the 'whoops' immediately:
chmod 777 /blahblah/composerstarter/writable/cache/

**CodeIgniter 4 version**
whatever composer installed, today.

**Expected behavior, and steps to reproduce if appropriate**
'whoops' was not expected.  after chmod 777 of the writable/cache folder the 'whoops' went away.   composer should have been able to get this right.

**Context**
 - OS: x86_64 GNU/Linux ubuntu 20.10 / groovy
 - Web server:  standard apache2 
 - PHP version : php --version = PHP 7.4.9

**Comment by paulbalandan** [comment]
This is not a framework issue. It has been documented that you must have the proper permissions to write on the `writable` folder. For composer, I know this doesn't change the permissions of directories. If you think otherwise, then please open a bug report in their repo.

**Comment by davidbuzz** [comment]
Well... if composer can't be made to do this automatically, afaict, then whatever doco I read that told me the composer command to run didn't also tell me to 'chmod  777 ' the folder , so was unclear as far as I'm concerned.  I'd suggest that at the very least doc needs to be clearer. I am a smart person, and I didn't raise this issue for fun., I really was surprised by it, and it really did stop me proceeding.
