### ISSUE TITLE
Bug: Can't connect to MySQLi using SSL encrypt connection

### ISSUE THREAD

**Issue by luizzz** [codeigniter4/CodeIgniter4#4616]
**CodeIgniter 4 version**
4.1.1

**Affected module(s)**
/app/config/Database.php
/system/Database/MySQLi/Connection.php

**Expected behavior, and steps to reproduce**
https://forum.codeigniter.com/thread-79089.html

**Comment by michalsn** [comment]
Correct, we shouldn't be required to present a certificate to enable a secure connection.

**Comment by paulbalandan** [comment]
Resolved by #4885
