### ISSUE TITLE
intl - Name missing exception  

### ISSUE THREAD

**Issue by John-Betong** [codeigniter4/CodeIgniter4#4636]
Solved the following infuriating cryptic message: 

**File**: ./system/Language/Core.php
`'missingExtension'             => 'The framework needs the following extension(s) installed and loaded: {0}.',`

**File**: ./system/Language/Language.php
`protected function formatMessage($message, array $args = [])
{
	if (! $this->intlSupport || $args === [])
	{
	  // John_Betong - ADDED THE FOLLOWING	
 	$message = $args ? $message .= $args[0] : $message;

	return $message;
	}

	if (is_array($message))
	{
		foreach ($message as $index => $value)
		{
			$message[$index] = $this->formatMessage($value, $args);
		}

		return $message;
	}

	return MessageFormatter::formatMessage($this->locale, $message, $args);
}// endfunc
`

**Comment by paulbalandan** [comment]
Already fixed by #4549
