### ISSUE TITLE
Bug: cli not working with cron

### ISSUE THREAD

**Issue by pixobit** [codeigniter4/CodeIgniter4#4699]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
I was trying to run CI4 through cli, and it didn't seem to be working... So after a long debugging session, I've found out that CI4 wasn't recognizing it as a cli execution, and the routing was failing because of this. The reason was, that if CI4 is called by crontab, the PHP_SAPI constant will return 'cgi-fcgi' instead of 'cli' which is checked against in Common.php fn is_cli()

**CodeIgniter 4 version**
4.1.1

**Affected module(s)**
Which package or class is the bug in, if known.

**Expected behavior, and steps to reproduce if appropriate**
Expected to work the same way, as when I run it from cli

**Context**
 - OS: CentOS 7
 - Web server Apache 2
 - PHP version 7.4

**Comment by paulbalandan** [comment]
When running inside the cron, can you check the value of the `TERM` env variable?
```php
var_dump(getenv('TERM'));
```

**Comment by pixobit** [comment]
Will check later today when I get a bit of free time

**Comment by pixobit** [comment]
it returns "bool(false)"

**Comment by paulbalandan** [comment]
Last checks to see if CGI can be safely regarded as CLI.
```php
var_dump(! isset($_SERVER['REMOTE_ADDR']));
var_dump(! isset($_SERVER['HTTP_USER_AGENT']));
var_dump(count($_SERVER['argv']) > 0);
var_dump(! isset($_SERVER['REQUEST_METHOD']));
```
