### ISSUE TITLE
Bug: redirect()->withInput()->back() always redirect to / in HTTP Test and Controller testing

### ISSUE THREAD

**Issue by samsonasik** [codeigniter4/CodeIgniter4#4710]
**Describe the bug**

I am on upgrading my [ci4-album](https://github.com/samsonasik/ci4-album) that tested in CI 4.0.3 which has the following code:

```php
	public function add()
	{
		if ($this->request->getMethod() === 'post')
		{
			$data = $this->request->getPost();
			if ($this->repository->save($data))
			{
				session()->setFlashdata('status', 'New album has been added');
				return redirect()->route('album-index');
			}

			session()->setFlashdata('errors', model(AlbumModel::class)->errors());
			return redirect()->withInput()->back();
		}

		return view('Album\Views\album\add', ['errors' => session()->getFlashData('errors')]);
	}
```

which was testable with code:

```php
	public function testAddAlbumInvalidData()
	{
		$request = Services::request(null, false);
		$request->setMethod('post');

		$result = $this->withRequest($request)
						->controller(Album::class)
						->execute('add');
		$this->assertTrue($result->isRedirect());

		$request = Services::request(null, false);
		$request->setMethod('get');

		$result = $this->withRequest($request)
					   ->controller(Album::class)
					   ->execute('add');
		$this->assertTrue($result->isOK());
		$this->assertTrue($result->see('The artist field is required.'));
		$this->assertTrue($result->see('The title field is required.'));
	}
```

On latest `CI 4.1.2`, it always false for `result->see()`. On debugging, checking the redirect Url, it always back to `/` instead of `/album/add` so it always failuire. It happen in `HTTP` test as well:

```php
public function testAddAlbumInvalidData()
{
        $result = $this->post('/album/add');
        $this->assertTrue($result->isRedirect());
        var_dump($result->getRedirectUrl());
}
```

which result:

```bash
string(32) "http://localhost:8080/index.php/"
```

which should be:

```bash
string(32) "http://localhost:8080/index.php/album/add"
```

On another debugging, somehow, the session always empty for : 

```php
var_dump(model(AlbumModel::class)->errors());die;
```

which actually exists if it called in the web browser.

```php
array(2) { ["artist"]=> string(29) "The artist field is required." ["title"]=> string(28) "The title field is required." }
```

**CodeIgniter 4 version**
4.1.2

**Affected module(s)**
Test

**Expected behavior, and steps to reproduce if appropriate**

It should work.

- PHPUnit configuration https://github.com/samsonasik/ci4-album/blob/master/phpunit.xml.dist
Database 
- Testing setup: https://github.com/samsonasik/ci4-album#testing
- Error demo: https://github.com/samsonasik/ci4-album/pull/9/checks?check_run_id=2626262047#step:11:18

**Context**
 - OS: MacOS Big Sur 11.3
 - Web server CLI
 - PHP version 8.0.6

**Comment by MGatner** [comment]
`redirect()->back()` will default to root when there is no `__ci_previous_url`, which in feature and controller tests should always be the case (unless you are preserving sessions between tests). I'm curious how this was working before.

**Comment by samsonasik** [comment]
`__ci_previous_url` is not exists, for just back to previous uri, the `$_SERVER['HTTP_REFERER']` initialization tweak can be used but the session is gone.

I check versions one by one, and it seems it is not working since `4.0.5`, so we need to check the diff between https://github.com/codeigniter4/CodeIgniter4/compare/v4.0.4...v4.0.5

**Comment by MGatner** [comment]
I don't see you setting `$_SESSION['_ci_previous_url']` or `$_SERVER['HTTP_REFERER']` so if this was working before it must have been carried over from a previous test. Maybe it was the changes to `CIUnitTestCase`? https://github.com/codeigniter4/CodeIgniter4/compare/v4.0.4...v4.0.5#diff-581964b1f9dfdbe8e8fb29c615b299dac0fb4624e080117fe787447b92c14749

**Comment by samsonasik** [comment]
That should work without that tweak with `withInput()` and `back()` to bring input into session and back to current URI, it is a `303` post redirect get work. 

Definetely needs check in the `CIUnitTestCase`

**Comment by samsonasik** [comment]
It is previously working on <= 4.0.4

**Comment by samsonasik** [comment]
I am closing for now, still an issue, but use another solution already.
