### ISSUE TITLE
Bug: CURL Class - BaseURI options notworking 

### ISSUE THREAD

**Issue by obipascal** [codeigniter4/CodeIgniter4#4713]
**Describe the bug**
The CURL Class BaseURI config option for setting API baseuri is notworking

**CodeIgniter 4 version**
Version: 4.1.2

**Affected module(s)**
CURL Class

**Expected behavior, and steps to reproduce if appropriate**
I Was expecting the CURL class to make request to subsequent api endpoints after setting the base uri in the config initialization option.

**Context**
 - OS: window 10 pro
 - Appache
 - PHP version 7+

**Comment by MGatner** [comment]
Could this be related to #4707? What is your `baseURL` in **app/Config/App.php** and the `baseURI` you are using with `CURLRequest`?

**Comment by paulbalandan** [comment]
I think this is related to that issue as he is referring to setting the base uri.

**Comment by MGatner** [comment]
Yes I think this was solved in #4715. @obipascal please test and re-open if you are still having issues.

**Comment by obipascal** [comment]
Yes This has been resolved
OBI PASCAL BANJUARE
