### ISSUE TITLE
Bug: deprecated notice on CodeIgniter\HTTP\RequestInterface::getMethod()

### ISSUE THREAD

**Issue by Ciro23** [codeigniter4/CodeIgniter4#4717]
CodeIgniter\HTTP\RequestInterface::getMethod() has a @deprecated notice for the $upper parameter, but vscode recognizes the entire method as deprecated making it crossed out
![image](https://user-images.githubusercontent.com/38884767/119164092-59b93680-ba5c-11eb-80b9-580ccbbf9ba2.png)
![image](https://user-images.githubusercontent.com/38884767/119164148-663d8f00-ba5c-11eb-829b-9136b553fbff.png)

**Comment by paulbalandan** [comment]
You're right on this one that the `@deprecated` notice deprecates the whole method instead of the parameter. Technically, this is not a bug as your code will still work. For now, you just need to ignore the intelephense warning.
