### ISSUE TITLE
Bug: Module route filters not loading 

### ISSUE THREAD

**Issue by iRedds** [codeigniter4/CodeIgniter4#4720]
**Describe the bug**
If the module route has a filter, then the filter is checked in App\Config\Filters.
If the filter is not found, then an error is thrown. 
If a module filter must be registered in App\Config\Filters, then trying to load the module filters extension is meaningless. 

Example
```php
//Module/Namespace/Config/Routes
$routes->add('route', 'Controller::method', ['filter' => 'module_filter']);
//Module/Namespace/Config/Filters
$filters->aliases['module_filter'] = Module\Namespace\Filters\SomeFilter::class;
```

**CodeIgniter 4 version**
4.1.2

**Affected module(s)**
CodeIgniter, Filters

**Comment by kenjis** [comment]
@iRedds I sent a PR #5280
Could you try?
