### ISSUE TITLE
Bug: Localization is not setting setlocale function from php.net

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#4738]
**Direction**
Hello i would like to translate months and days of week trough localization settings

**Describe the bug**
**setLocale()** method is not setting setlocale from php.net
as in example 

         setlocale(LC_ALL, 'fr_FR.UTF-8');

and when i echo this line 

         <?=strftime('%A')?>

i would get the name of the day in that language if is set correctly.

**CodeIgniter 4 version**
Latest Version

**Comment by paulbalandan** [comment]
This is not a bug but rather not implemented. If you want this functionality, please send a PR.
