### ISSUE TITLE
Bug: Caching something through cron, is not accessible in the web application

### ISSUE THREAD

**Issue by pixobit** [codeigniter4/CodeIgniter4#4751]
**Describe the bug**  
If I use `cache()->save('products-facet', $data, 0);` in a cron job (which is a cli route), the web application won't be able to access this cache, it will throw "Permission Denied"

**CodeIgniter 4 version**  
4.1.2

**Expected behavior, and steps to reproduce if appropriate**  
Not sure what's the correct way to tackle this, but what I did as a workaround for now, is that I changed the chmod after caching from 0640 to 0644

Note: The purpose of this cron is to index some data, that's why I'm using the caching

**Comment by MGatner** [comment]
This was addressed recently. Upgrade your framework and then set `file.mode` in **app/Config/Cache.php**.
