### ISSUE TITLE
cache key for const RESERVED_CHARACTERS

### ISSUE THREAD

**Issue by hentailing** [codeigniter4/CodeIgniter4#4758]
In v4.1.2 CodeIgniter\Cache\Handlers\BaseHandler added a const RESERVED_CHARACTERS，It's limited ":" in the cache key when I using RedisDriver.
I want to use ":" to distinguish the namespace in redis.

**Comment by MGatner** [comment]
See "Cache Keys" at https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_412.html

I've got mixed feelings about the reserved characters. I don't like that our keys are so environment-dependent (e.g. `:` breaks Windows `FileHandler` but is fine in all other scenarios), but ideally the Cache layer is ignorant of its underlying driver & OS. PSR-6 is clear about the disallowed characters list (`{}()/\@:`). Maybe some research is in order as to what other frameworks do? Maybe hashing keys with "illegal" characters so they are still permitted from a developer perspective?

**Comment by michalsn** [comment]
Hashing "illegal" characters may bring a lot of confusion when someone would like to read the cached data outside the CodeIgniter.

I wonder if it wouldn't be a better idea to remove the constant from `BaseHandler` and add it as an additional config variable? This way it could be modified pretty easily. As long as the developer knows what he/she is doing modifying these should be allowed. The `:` sign is pretty common when it comes to Redis.

**Comment by MGatner** [comment]
@michalsn I think that is a great suggestion. I regret this change, given all the issues that it has caused. The original issue was that cache keys were not safely transferable across drivers and operating systems, causing some unfortunate production failures with weird error messages. Simultaneous to this issue I was working on the PSR-6 & -16 adapters (which do have very strict key definitions), so I "killed two birds with one stone". 

Offering the developer a Config option for the allowed keys has the added benefit of opening this setting to be environment-based, which is what we are really after. I think as long as the default Config value matches the current class constant we could roll this out smoothly.

**Comment by michalsn** [comment]
Yes, moving this to the config file plus adding some basic info in the user guide should do the trick.

**Comment by paulbalandan** [comment]
If he is using the colon to namespace the key, he should set that in his config instead of bypassing the allowed characters.
```php
// Config\Cache
public $prefix = 'foo:';
```
Then supply the keys normally. This way, the keys will be prefixed just like how he wants it namespaced.

**Comment by michalsn** [comment]
I think the problem here is not about prefixing all the variables but using the colon inside the "key" to distinguish complex cache namespace, something like: `key:{product_id}:{user_id}`. Of course, we can say: "use something else" - as we do now, but the better idea would be to make these reserved characters editable.

**Comment by MGatner** [comment]
This would also fix a number of requests to allow characters, like #4765. I think the Config is the way to go, and we can always keep the current set and even the constant as a fallback.

**Comment by hentailing** [comment]
Thanks for your answer. I get a new idea, set cacheKey as `foo.bar`.

**Comment by paulbalandan** [comment]
Fixed in #5008
