### ISSUE TITLE
Bug: Error using SQLITE3 strftime in CodeIgniter 4.1.2

### ISSUE THREAD

**Issue by jolupa** [codeigniter4/CodeIgniter4#4760]
**Describe the bug**
This line was working perfectly before the update to CodeIgniter 4.1.2
`->where('strftime("%Y-%m", release)', date('Y-m'))`
Now I have the following error:
`SQLite3::query(): Unable to prepare statement: 1, unrecognized token: &quot;:strftime('%Y-%m',&quot;`

**CodeIgniter 4 version**
4.1.2

**Context**
 - OS: Fedora 34
 - Web server: Running directly on Spark server not in production
 - PHP version: 7.4.19

**Comment by paulbalandan** [comment]
Have you tried removing the single quotes around `strftime`?
```diff
-->where('strftime("%Y-%m", release)', date('Y-m'))
+->where(strftime("%Y-%m", release), date('Y-m'))
```

And what is `release`? It does not appear to be a correct variable name.

**Comment by jolupa** [comment]
> Have you tried removing the single quotes around `strftime`?
> 
> ```diff
> -->where('strftime("%Y-%m", release)', date('Y-m'))
> +->where(strftime("%Y-%m", release), date('Y-m'))
> ```
> 
> And what is `release`? It does not appear to be a correct variable name.

Yes I removed the single quotes, then the error says `release is not a variable` but `release` is the column name where I want to check the date.

I followed the sqlite 3 manual and it was working on CodeIgniter previous version 4.1.1

**Comment by paulbalandan** [comment]
Thanks! This is a bug in the Query binds recognition. As the characters in the regex are quite limited, Query failed to bind the where clause.

**Comment by paulbalandan** [comment]
@jolupa can you try the referenced PR to see if it will work in your use case?

**Comment by jolupa** [comment]
> @jolupa can you try the referenced PR to see if it will work in your use case?

It works flawlessly!
Thanks a lot there's no errors now!

**Comment by paulbalandan** [comment]
Thanks. But that needs refinements as it's dangerous to allow all inclusions.

**Comment by paulbalandan** [comment]
@jolupa can you retest the new regex, please?

**Comment by jolupa** [comment]
> @jolupa can you retest the new regex, please?

Works too. There's no problems.
