### ISSUE TITLE
Bug: Class 'Locale' not found

### ISSUE THREAD

**Issue by bi2b** [codeigniter4/CodeIgniter4#4775]
i got this error.

Error
Class 'Locale' not found search →

SYSTEMPATH/I18n/Time.php at line 80

73      * @param string|null              $locale
74      *
75      * @throws Exception
76      */
77     public function __construct(string $time = null, $timezone = null, string $locale = null)
78     {
79         // If no locale was provided, grab it from Locale (set by IncomingRequest for web requests)
80         $this->locale = ! empty($locale) ? $locale : Locale::getDefault();
81 
82         // If a test instance has been provided, use it instead.
83         if (is_null($time) && static::$testNow instanceof Time)
84         {
85             if (empty($timezone))
86             {
87                 $timezone = static::$testNow->getTimezone();

**Comment by paulbalandan** [comment]
Enable the `intl` extension. `Locale` is a class from `ext-intl`.
