### ISSUE TITLE
getUnbufferedRow() - memory usage 

### ISSUE THREAD

**Issue by sclubricants** [codeigniter4/CodeIgniter4#4799]
Version 4.x

When using the getUnbufferedRow() for mysql results it seems that the driver does not properly apply the appropriate logic.

According to php docs, the default result mode is: MYSQLI_STORE_RESULT 

When performing unbuffered queries you need to use MYSQLI_USE_RESULT while executing the query method.

https://www.php.net/manual/en/mysqlinfo.concepts.buffering.php

A simple hack:

in file: /system/Database/MySQLi/Connection.php

Add property to class:  public $result_mode = MYSQLI_STORE_RESULT; // default

on line 329 in the execute method change:
return $this->connID->query($this->prepQuery($sql));
to:
return $this->connID->query($this->prepQuery($sql),$this->result_mode);

Then in model when you need unbuffered results you can set result mode: $model->db->result_mode = MYSQLI_USE_RESULT;

I have a query when run in buffered mode consumes 300mb. 

Then when I use getUnbufferedRow() it still consumes 100mb.

After applying the above hack and setting $model->db->result_mode = MYSQLI_USE_RESULT; it only consumes 5mb.

Perhaps there is a better fix than the one I outline above but this seems to make huge improvements in memory usage.

**Comment by MGatner** [comment]
I'm not familiar with these modes but if you've found a vast improvement that would translate into the framework, by all means please submit it as a Pull Request so we can consider incorporating it!

**Comment by paulbalandan** [comment]
@sclubricants can you submit a PR so we can vet on your proposed changes?

**Comment by sclubricants** [comment]
I have never contributed before and have no idea what I'm doing. I tried the best I can and submitted as PR.

https://github.com/codeigniter4/CodeIgniter4/pull/4812

**Comment by MGatner** [comment]
@sclubricants I haven't looked at your PR yet, but I'm proud of you for trying! Welcome aboard, contributor 😊

**Comment by sclubricants** [comment]
https://github.com/codeigniter4/CodeIgniter4/pull/4850

**Comment by paulbalandan** [comment]
Fixed in [`929e5c4`](https://github.com/codeigniter4/CodeIgniter4/commit/929e5c4f4259d5940b20a72db421eb0b2d4bf451).
