### ISSUE TITLE
Bug: \CodeIgniter\HTTP\UserAgent string type error

### ISSUE THREAD

**Issue by shishamo** [codeigniter4/CodeIgniter4#4800]
**Describe the bug**
$this->request->getUserAgent()->getAgentString();
return on error of "must be string type" if the agent is not send in the headers

**Suggestion?**
- className
CodeIgniter\HTTP\UserAgent
- property
protected $agent;
- might be ?
protected $agent = '';

**CodeIgniter 4 version**
4.1.0

**Context**
 - OS: Windows 10
 - Web server Apache 2
 - PHP version 7.4

**Comment by paulbalandan** [comment]
The `$agent` property already has a default `''` value since v4.0.4.

https://github.com/codeigniter4/CodeIgniter4/blob/9b51c1a8782495f63181bb8fd02c1353221b8ed4/system/HTTP/UserAgent.php#L26

**Comment by shishamo** [comment]
I haven't updated the system folder.
I have tried and everything was working properly.
Thank you very much
