### ISSUE TITLE
Don't treat all CI environment as Testing environment.

### ISSUE THREAD

**Issue by vibbow** [codeigniter4/CodeIgniter4#4804]
We are using Jenkins to do out production deploy, after file copying, jenkins will call CodeIgniter's `spark` to do some init jobs.

Since Jenkins 2.286, Jenkins changed it's behaviour, added `CI=true` environment variable.
https://issues.jenkins.io/browse/JENKINS-36707
This change merged into Jenkins LTS 2.289.1 since 2021-06-02

This breaks our deployment config, since CodeIgniter will tread Jenkins as Testing environment.

We had modify `spark` to force specific the environment as production as temp solution.

But is there a better way to archive it: using Jenkins to do deployment, and not tread Jenkins as Testing environment.

**Comment by paulbalandan** [comment]
What CI version are you using? As of v4.1.2, this has been resolved by #4692 .
