### ISSUE TITLE
Bug: Email Class - setAttachmentCID return value uses undefinded index

### ISSUE THREAD

**Issue by dirkbez** [codeigniter4/CodeIgniter4#4813]
Method setAttachmentCID( $filename ) crashes as the return value is not set.

line 763 : return $attachment['cid']; 

The array index is not set and cause an exception:
"title": "ErrorException", "type": "ErrorException", "code": 500, "message": "Undefined index: cid"

**CodeIgniter 4 version**
First encountered in version 4.1.2 seems to still be there in 4.1.3

**Affected module(s)**
System/Email/Email.php

On my local version I changed the affected line (761)  to:

`$attachment['cid'] = $this->attachments[ $i ][ 'cid' ] = uniqid( basename( $attachment[ 'name' ][ 0 ] ) . '@', TRUE );`

**Comment by paulbalandan** [comment]
This has been fixed by #4798
