### ISSUE TITLE
[Forge] Missing: Means of adding indexes on existing tables

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#4814]
The `Forge` class currently may only add indexes during table creation. We need a way to allow Forge (and thus migrations) to add indexes.

**Comment by neilsf** [comment]
+1 for this. I came here to report the same thing.

**Comment by sclubricants** [comment]
https://github.com/codeigniter4/CodeIgniter4/pull/6676 closes this

**Comment by MGatner** [comment]
Beautiful! Thanks so much @sclubricants 🏆
