### ISSUE TITLE
Dev: Update documentation code examples to reflect new coding standards

### ISSUE THREAD

**Issue by paulbalandan** [codeigniter4/CodeIgniter4#4816]
As we're all aware of the latest developments in our coding styles in a bid to shift to PSR-12 plus some of our custom styling, we've started rolling out code style changes in our code base. However, our new coding style tool **cannot** automatically correct **also** our documentation, which needs manual intervention.

We will be appreciative of a helping hand to assist us in updating also the code examples used in our documentation. Please submit pull requests while you can! 😎

**Comment by kenjis** [comment]
@paulbalandan What are *some of our custom styling*?

It seems [Coding Style Guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/styleguide.rst) is not updated. Why don't you update it at first?

**Comment by paulbalandan** [comment]
@WinterSilence thanks for the initiative! If you can tell me your general approach how you'll handle this maybe I can provide insights on skipping non php examples.

**Comment by WinterSilence** [comment]
@paulbalandan 
1. extract examples from `*.rst` files(lines with whitespaces at begin)
2. fix code style (`phpcbf` + `codeigniter4/coding-standard`)
3. replace examples
