### ISSUE TITLE
Request multipart does not get the image correctly 

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#4821]
I have the following test where I send a data and a file, the problem is that the files are not received in `$this->request->getFiles()`, only inside `$this->request->getPost()`

```php
//test
$file = TESTPATH .'_support/lorem.png';

$response = $this->withHeaders([
            	'Content-Type' => 'multipart/form-data',
                'Content-Length' => filesize($file),
             ])->post('/store',[
                  'name' => 'test',
                  'img' => file_get_contents($file)
              ]);
             // ...

// controller
$this->request->getFile('img')); // print null
```

thank's for everything!

**Comment by paulbalandan** [comment]
You should be using the name of the file as input in the form, which in this case is `test`.

**Comment by luispastendev** [comment]
Hello Paul

Do you mean to do something like that ??, in the same way it keeps returning null 

```php
 ])->post('/store',[
                  'name' => 'test',
                  'img' => $file
              ]);
```

**Comment by paulbalandan** [comment]
Hmm.. Did you try using the `test` as the `$fileID`?

```diff
-$this->request->getFile('img');
+$this->request->getFile('test');
```

**Comment by luispastendev** [comment]
sure but in the test I try to get name with `$this->request->getPost('name')` (this works) and on the other hand get the image with `$this->request->getFile('img')` just like making a multipart / form ajax call passing an img and form data at the same time

**Comment by paulbalandan** [comment]
Can you share a minimal reproducible script for this?

**Comment by luispastendev** [comment]
sure paul! 

```php
// test
public function testStoreMultipart(){

    $file = TESTPATH .'_support/lorem.png';

    $response = $this->withHeaders([
		            'Content-Type' => 'multipart/form-data',
			])->post('/store',[
                            'field' => 'asdf',
                            'myImage' => file_get_contents($file)
                        ]);

    $response->assertJSONFragment([
        'field' => true,
        'myImage' => true
    ]);
}
```
controller
```php

public function store(){
    return $this->response->setJSON([
	'field' => !empty($this->request->getVar('field')),
	'myImage' =>  !empty($this->request->getFile('myImage'))
    ]);
}
```
this test fails ...
![imagen](https://user-images.githubusercontent.com/4117596/122082702-d58d7100-cdc5-11eb-8e2c-32573b59271d.png)



I have also done a test in insomnia and this works 
![imagen](https://user-images.githubusercontent.com/4117596/122082342-8c3d2180-cdc5-11eb-9ee6-703f0b49f4af.png)

**Comment by michalsn** [comment]
Basically, you are sending a POST variable and then expecting to find it in the FILES array. It won't work.

You should do something like this:
```php
public function testStoreMultipart()
{
    $_FILES = [
        'myImage' => [
            'name' => 'lorem.png',
            'type' => 'image/png',
            'size' => 123,
            'tmp_name' => TESTPATH .'_support/lorem.png',
            'error' => 0,
        ],
    ];

    $response = $this->withHeaders([
		            'Content-Type' => 'multipart/form-data',
			])->post('/store', [
                            'field' => 'asdf',
                        ]);

    $response->assertJSONFragment([
        'field' => true,
        'myImage' => true
    ]);
}
```

**Comment by luispastendev** [comment]
TY @michalsn this works!
