### ISSUE TITLE
Bug: output 11 at the end of html? it disturb the page content

### ISSUE THREAD

**Issue by syazskylex** [codeigniter4/CodeIgniter4#4829]
Issue: Output 11 in web html
CI Version 4.1.3
OS: KDE Neon (Linux)
Web Server: Xampp 8.0.7
 
![image](https://user-images.githubusercontent.com/35444549/121785123-8a6b3680-cbea-11eb-90f7-4fbee7151cca.png)

**Comment by kenjis** [comment]
@syazskylex Please fill out the issue template. And remove the Direction at the top.

**Comment by MGatner** [comment]
I have no idea where that might be coming from. Is this a clean install of 4.1.3?

**Comment by syazskylex** [comment]
Unknown issues. It was a clean codeigniter. But, today I download it back and everything is okay like a normal CI.
