### ISSUE TITLE
Where clause getting ignored somtimes while updating hindi data to mysql database 

### ISSUE THREAD

**Issue by gouravmalviya0** [codeigniter4/CodeIgniter4#4833]
I m updating table with hindi text using where clause but sometimes it updates all the row present in table. 

I m using in below way -

$model = new TransModel();

$model->update($id,  $data);

Please let me know what is wrong here.

Thanks in advance

**Comment by paulbalandan** [comment]
Please ask support questions in the [forum](forum.codeigniter.com).

Your passed `$id` is the problem. Make sure the ID you are passing is not empty (null, false, empty string, etc.).
