### ISSUE TITLE
Bug: Namespace name doesn't match the PSR-0/PSR-4 project structure

### ISSUE THREAD

**Issue by astrahov** [codeigniter4/CodeIgniter4#4856]
**Direction**

PSR0/PSR-4

**Describe the bug**

source: `.../app/Libraries/TestLib`

```
<?php

namespace App\Libraries;

class TestLib
{

}
```

My IDE (PhpStorm) is showing error: Namespace name doesn't match the PSR-0/PSR-4 project structure

namespace `App`, folder `app`. Different case.

**CodeIgniter 4 version**
4.1.3

**Affected module(s)**
All

**Expected behavior, and steps to reproduce if appropriate**
-

**Context**
 - OS: macOS Big Sur [11.4]
 - PHP version: 7.4

**Comment by paulbalandan** [comment]
This has nothing to do with CodeIgniter. Closing..

And please ask support questions in the [forum](forum.codeigniter.com).
