### ISSUE TITLE
Bug: Command Gap

### ISSUE THREAD

**Issue by hafizprasetyo** [codeigniter4/CodeIgniter4#4857]
**Direction**
I have a problem using the word "App" as a name in a command.

**Describe the bug**
When I will create a migration file in codeigniter 4, I use the name "App_Lesson" or "AppLesson" using the command **php spark make:migration AppLesson**. The migration file was created successfully, but what happens is that the migration file is placed in the /app directory, not in /app/Database/Migrations

**CodeIgniter 4 version**
CodeIgniter 4.1.3

**Affected module(s)**
make:migration

**Expected behavior, and steps to reproduce if appropriate**
A file called AppLesson should be created and located in the /app/Database/Migrations directory.
Here's a screenshot from my terminal:
https://pasteboard.co/K7MRmBX.png

Here's a screenshot from my project explorer:
https://pasteboard.co/K7MSDEw.png

**Context**
 - OS: Windows 10
 - Web server Apache 2.4.48
 - PHP version 8.0.7

**Comment by paulbalandan** [comment]
Fixed in #4867

**Comment by hafizprasetyo** [comment]
Alright, thanks..
