### ISSUE TITLE
How to report framework security issue?

### ISSUE THREAD

**Issue by mmrtonmoybd** [codeigniter4/CodeIgniter4#4859]
I send a mail to security@codeigniter.com

But mail sending Delivery is incomplete due to DNS Error. 

I am discover a critical security bug in framework. After founding bug I am directly send a email to this address with bug details but mail is not sending. 

Now how I report this issue privatly ?

**Comment by lonnieezell** [comment]
I'll look into the DNS error. Thanks for bringing that to our attention. 

In the meantime you can email me directly at lonnieje@gmail.com.
