### ISSUE TITLE
Bug: ROOTPATH issue when Multiple Applications with one CodeIgniter Installation

### ISSUE THREAD

**Issue by freeaircn** [codeigniter4/CodeIgniter4#4887]
**Describe the bug**
Install CI project though composer methed.
For example, create another applications, named “foo”, project directories like this:
/foo
.   /app
.   /public
.   /tests
.   /writable
/app
/public
/tests
/writable
/vendor
.    /codeigniter4/framework/system
.env

When access "foo" application, through bootstrap.php, the ROOTPATH is set as directory  /foo, not directory  /

**CodeIgniter 4 version**
4.1.3

**Affected module(s)**
Affected:
1) .env file under directory / could not be loaded.
2) the COMPOSER_PATH is set wrongly as /foo/vendor/autoload.php. Under /foo, there is no directory /vendor

The code in bootstap.php as below, getting ROOTPATH from APPPATH is unreasonable.
// The path to the project root directory. Just above APPPATH.
if (!defined('ROOTPATH')) {
define('ROOTPATH', realpath(APPPATH . '../') . DIRECTORY_SEPARATOR);
}

**Expected behavior, and steps to reproduce if appropriate**
when Multiple Applications with one CodeIgniter Installation, the ROOTPATH should be pointed to directory /

**Context**
 - OS: [e.g. Windows 10]
 - Web server [e.g. Apache 1.2.3]
 - PHP version [e.g. 7.3]

**Comment by freeaircn** [comment]
close

**Comment by totoprayogo1916** [comment]
is the problem resolved?

**Comment by lonnieezell** [comment]
I'm not sure what the OP found, but the solution I would recommend would be to edit the `index.php` file for each location, and ensure that `$pathsConfig` loads the correct Paths file. Once done, I think that takes care of everything else. 

```
$pathsConfig = FCPATH . '../app/Config/Paths.php';
```

**Comment by totoprayogo1916** [comment]
The problem is, `COMPOSER_PATH` 
`autoload.php`  cannot load or Error HTTP 500

**Comment by lonnieezell** [comment]
Hm. I don't recall having to do much else, but you can check out [this repo](https://github.com/lonnieezell/ci4-foundations) for an example of multiple applications running with a single vendor folder.

**Comment by totoprayogo1916** [comment]
it works, but if add any library, it will throw error

**Comment by totoprayogo1916** [comment]
and the result if this line changed.
https://github.com/codeigniter4/CodeIgniter4/blob/1928006ccc9fa86be11bb8ee5708f4d7bec95fda/app/Config/Constants.php#L26
![image](https://user-images.githubusercontent.com/2387514/124948438-e5058000-e03a-11eb-91b2-46925aaf6e2c.png)

**Comment by freeaircn** [comment]
I tried to modify ROOTPATH config to point to root directory  ( / ), the multiple application could not work normally. I've not tried to add 3rd library through composer installing.
I think it would affect any library (composer install ...) as totoprayogo1916 said.

**Comment by kenjis** [comment]
> when Multiple Applications with one CodeIgniter Installation, the ROOTPATH should be pointed to directory /

`ROOTPATH` is the directory where `.env` locates.
In `foo` app, it must be `/foo`.

**Comment by freeaircn** [comment]
> > when Multiple Applications with one CodeIgniter Installation, the ROOTPATH should be pointed to directory /
> 
> `ROOTPATH` is the directory where `.env` locates. In `foo` app, it must be `/foo`.

what's your suggestion about the case that Multiple Applications with one CodeIgniter Installation and adding 3rd library through composer installing ?

**Comment by kenjis** [comment]
See https://codeigniter4.github.io/CodeIgniter4/general/managing_apps.html#running-multiple-applications-with-one-codeigniter-installation
> When you use Composer autoloader, fix the COMPOSER_PATH constant in app/Config/Constants.php inside each of those:
