### ISSUE TITLE
Bug: soft deleted rows ignored only if $builder->countAllResults(false) is executed

### ISSUE THREAD

**Issue by Ciro23** [codeigniter4/CodeIgniter4#4894]
**Describe the bug**
using the query builder class, select will return soft deleted rows too if $builder->countAllResult(false) is not run before $builder->get()

**CodeIgniter 4 version**
4.1

**Affected module(s)**
query builder class (?)

**Expected behavior, and steps to reproduce if appropriate**
for example, in my UserModel i have set the soft deletes to true and the mysql table has a deleted_at column.
normally if i select some users from that table it should returns only rows where deleted_at is null, but this happens only if before i run $builder->countAllResults(false).

basically, if i do something like this:
`class UserModel extends Model {

    protected $table = "users";
    protected $useTimestamps = true;
    protected $useSoftDeletes = true;

    public selectUsers() {
        $builder = $builder->select();

        return $builder->get()->getResults();
    }
} `
it will return soft deleted rows too.

if i want to return only non soft deleted rows, i have to run $builder->countAllResults(false) before $builder->get():
`class UserModel extends Model {

    protected $table = "users";
    protected $useTimestamps = true;
    protected $useSoftDeletes = true;

    public selectUsers() {
        $builder = $builder->select();

        $builder->countAllResults(false);

        return $builder->get()->getResults();
    }
}`

the last example actually works but logically it doesn't make sense, so it would be better to use $builder->countAllResults(false) to check if there are results:
`if ($builder->countAllResults(false) {
    return $builder->get()->getResults();
}

return null // or throw an exception or just checking that hey there are no results`

**Context**
 - OS: Ubuntu 20.04 LTS
 - PHP version: 8.0.7

**Comment by Ciro23** [comment]
sorry if code blocks are a little bit broken, this is my first time opening an issue and using github markdown

**Comment by Ciro23** [comment]
and....... i also forgot to use the function keyword to declare the functions...
i didn't wrote this example in my editor so i didn't notice

**Comment by michalsn** [comment]
You're confusing `Builder` class methods with `Model` class methods. Only `Model` class methods will take into account `useSoftDeletes` option.

```php
public selectUsers()
{
    return $this->select('...')->findAll();
}
```

or

```php
public selectUsers()
{
    $builder = $this->builder();
    
     if ($this->tempUseSoftDeletes) {
          $builder->where($this->deletedField, null);
     }

      return $builder->select('...')->get()->getResult();
}
```

**Comment by Ciro23** [comment]
thanks for the tip
