### ISSUE TITLE
Bug: Load Factories

### ISSUE THREAD

**Issue by mostafakhudair** [codeigniter4/CodeIgniter4#4896]
I know that we can call a specific model by regular way calling `Factories::models('UserModel')`, but while reading `Factories` manual in the user guide, I found another way to call a specific class [A]: e.g. `Factories::models('Myth\Auth\Models\UserModel')`, and When I was curious to try to load the same class with config models [B]: e.g. `Factories::config('Myth\Auth\Models\UserModel')`, its gave the same result of [A] way, which illogical

@MGatner should this marked as bug! I really don't know

**Affected module(s)**
`CodeIgniter\Config\Factories`

**Context**
OS: `Linux`
PHP version: `7.4.20`
CI version: `4.1.3`

**Comment by MGatner** [comment]
The actual method ("model", "config") isn't tied to any class unless you use the `instanceOf` option. Normally the method will be used to check directories, but since you provide the fully-qualified class it will just return it instead of searching. Not a bug, but perhaps a misuse of the component. 😂

**Comment by mostafakhudair** [comment]
Should we modify the component to prevent the developer from abusing it?

**Comment by MGatner** [comment]
I don't think it is necessary, and I'm not sure how we would. Using fully-qualified classes is the only way to bypass folder restrictions (other than changing the folder with an option) so trying to "validate" that a Config class was "really in a Config folder" is self-defeating.
