### ISSUE TITLE
Bug: Cache keys erros using throttle

### ISSUE THREAD

**Issue by matheuscastroweb** [codeigniter4/CodeIgniter4#4904]
**Describe the bug**
When using throttle, the cache keys error occurs. Just instantiate and put in middeware as it is in the documentation. 
If used the host localhost causes the error.

Error:
![image](https://user-images.githubusercontent.com/45601574/124343630-5b216700-dba3-11eb-8b04-e622563e10cc.png)

Print key: 
![image](https://user-images.githubusercontent.com/45601574/124343661-a0de2f80-dba3-11eb-966e-ff7fe26115f2.png)

File error:
![image](https://user-images.githubusercontent.com/45601574/124343670-b9e6e080-dba3-11eb-8262-9966f288b8ca.png)

**CodeIgniter 4 version**
4.1.3

**Context**
 - OS: Windows 10
 - Web server PHP - Server
 - PHP version 7.4

**Comment by michalsn** [comment]
Resolved via #4908
