### ISSUE TITLE
Bug: getVar does not return null when item doesn't exist

### ISSUE THREAD

**Issue by Ryubal** [codeigniter4/CodeIgniter4#4906]
**Describe the bug**
getVar() doesn't return null when the item I'm attempting to retrieve does not exist

**CodeIgniter 4 version**
4.1.3

**Affected module(s)**
IncomingRequest?

**Expected behavior, and steps to reproduce if appropriate**
Inside of any controller, dump the contents of getVar() with any parameter you'd like:
```php
public function update() {
	var_dump($this->request->getVar('description'));
}
```

Now, using Postman, I made a raw JSON request (HTTP PUT) with the following body (empty works, too):
```json
{
	"name": "test"
}
```

Expected behaviour: _NULL_ should be printed, as per the [documentation](https://codeigniter4.github.io/userguide/incoming/incomingrequest.html?highlight=getvar#getVar)
Actual behaviour: _string(0) ""_ is printed.

**Context**
 - OS: Windows 10
 - Web server: Apache
 - PHP version: 7.4.3

**Comment by michalsn** [comment]
Resolved via #4909
