### ISSUE TITLE
Bug: Cache->remember() not implemented but documented.

### ISSUE THREAD

**Issue by damianromanowski** [codeigniter4/CodeIgniter4#4922]
**Describe the bug**
Documentation at https://codeigniter4.github.io/userguide/libraries/caching.html#remember clearly outlines a remember() method, but is not actually implemented. Throwing `Call to undefined method CodeIgniter\Cache\Handlers\FileHandler::remember()`

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
CodeIgniter\Cache\Handlers\FileHandler

**Expected behavior, and steps to reproduce if appropriate**
```php
$cache = \Config\Services::cache();

$data = $cache->remember('some_key', 30, function() {
      return 'some data';
});

return $data;
```

**Context**
 - Debian 10
 - Apache/2.4.38
 - PHP 7.3.27-1~deb10u1

**Comment by paulbalandan** [comment]
Hi. Cache remember is implemented in v4.0.5
