### ISSUE TITLE
Bug: Error in regex_match[/^;\"'{}\[\]^<>=/]", validation rules

### ISSUE THREAD

**Issue by dreamy2h** [codeigniter4/CodeIgniter4#4929]
**Direction**
https://forum.codeigniter.com/thread-79615.html

**Describe the bug**
when entering this regex, I get an error: required|maxlength is not a valid rule. The full description of the error is in the forum link, along with the code.

**CodeIgniter 4 version**
4.1.3

**Affected module(s)**
{
    "title": "CodeIgniter\\Validation\\Exceptions\\ValidationException",
    "type": "CodeIgniter\\Validation\\Exceptions\\ValidationException",
    "code": 500,
    "message": "required|max_length is not a valid rule.",
    "file": "/srv/http/trazador/system/Validation/Validation.php",
    "line": 321,
    "trace": [
        {
            "file": "/srv/http/trazador/system/Validation/Validation.php",
            "line": 321,
            "function": "forRuleNotFound",
            "class": "CodeIgniter\\Validation\\Exceptions\\ValidationException",
            "type": "::"
        },
        {
            "file": "/srv/http/trazador/system/Validation/Validation.php",
            "line": 159,
            "function": "processRules",
            "class": "CodeIgniter\\Validation\\Validation",
            "type": "->"
        },
        {
            "file": "/srv/http/trazador/system/Controller.php",
            "line": 183,
            "function": "run",
            "class": "CodeIgniter\\Validation\\Validation",
            "type": "->"
        },
        {
            "file": "/srv/http/trazador/app/Controllers/Viaticos/Ctrl_viaticos.php",
            "line": 234,
            "function": "validate",
            "class": "CodeIgniter\\Controller",
            "type": "->"
        },
        {
            "file": "/srv/http/trazador/system/CodeIgniter.php",
            "line": 928,
            "function": "guardar_viatico",
            "class": "App\\Controllers\\Viaticos\\Ctrl_viaticos",
            "type": "->"
        },
        {
            "file": "/srv/http/trazador/system/CodeIgniter.php",
            "line": 436,
            "function": "runController",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "/srv/http/trazador/system/CodeIgniter.php",
            "line": 336,
            "function": "handleRequest",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "/srv/http/trazador/public/index.php",
            "line": 37,
            "function": "run",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        }
    ]
}

**Context**
 - OS: [Manjaro 21.0.7]
 - Web server [Apache 2.4.48 (Unix)]
 - PHP version [PHP 8.0.7]

**Comment by paulbalandan** [comment]
Fixed in #4957
