### ISSUE TITLE
Issue Forms

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#4944]
GitHub is rolling out [Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) - a more formal way of creating interactive forms during issue submission. A number of our existing templates would be better implemented as Forms, when someone has the time/interest.

**Comment by MGatner** [comment]
Shoutout to @jeromegamez for bringing these to my attention, and already having rolled out his own 😉

**Comment by sfadschm** [comment]
Looks great,  finally no more
    
     ----- Remove below this line -----

😆

**Comment by MGatner** [comment]
Egg-ZACTLY!

**Comment by paulbalandan** [comment]
Very nice! Does this also work for PR templates?

**Comment by MGatner** [comment]
@paulbalandan they do not appear to currently, but the way they are filed in the docs suggests that might be coming:

> Building communities - Issue & PR templates - Syntax for issue forms
