### ISSUE TITLE
Bug: MySQL query with errors does not return error - only a boolean

### ISSUE THREAD

**Issue by lovetoast** [codeigniter4/CodeIgniter4#4947]
**Describe the bug**
Make a MySQL DB query via CodeIgniter and include an error, a table or field or alias that does not exist, and rather than showing that error, if you run get() on that query, CodeIgniter returns a boolean. 

**CodeIgniter 4 version**
LATEST

**Affected module(s)**
MySQL database class

**Expected behavior, and steps to reproduce if appropriate**
As per all previous versions of CI, errors in a DB query should result in the error from MySQL being returned.

**Context**
On Windows, with latest CI.

**Comment by paulbalandan** [comment]
Hi, when reporting bugs please make it painless for the maintainers to reproduce your issue given their limited time and resources. As much as possible, provide a minimal reproducible test script with detailed context. If not possible, provide at least a minimal, self-contained repository demonstrating your issue with reproduction steps.

This way, we can help each other to the speedy resolution of your case. Thanks.

**Comment by lovetoast** [comment]
Hi @paulbalandan, understood, but not sure how I can provide a test script for what is essentially a MySQL query bug? Also, not sure what the value is of closing this issue, I'm quite certain it is a major departure from how CodeIgniter normally works.

**Comment by paulbalandan** [comment]
Please open another issue with the needed details. Thank you.
