### ISSUE TITLE
 fixing entity after remap 

### ISSUE THREAD

**Issue by paliz-git** [codeigniter4/CodeIgniter4#4950]
after $datamap  filed  
```php
'created_at' => null,
'updated_at' => null,
'deleted_at' => null,
```
to 
```php
'createdAt' => 'created_at',
'updatedAt' => 'updated_at' ,
'deletedAt' => 'deleted_at'
```

each time create new data to table filed set value for both them 
but only should do for created_at   not for all
 'createdAt' => 'created_at',
        'updatedAt' => 'updated_at' ,

 here table  after  insert
id= 38
key =xxoyox
value= yyyy
description=jhdfjshfjsdf
status=0
craeted_at=2021-07-19 13:25:18
updated_at=2021-07-19 13:25:18
deleted_at=NULL
heres code

```php
<?php namespace Modules\Common\Entities;

use \CodeIgniter\Entity;
use CodeIgniter\I18n\Time;

class  SettingEntity extends Entity
{
    protected $id;
    protected $key;
    protected $value;
    protected $description;
    protected $status;
    protected $createdAt;
    protected $updatedAt;
    protected $deletedAt;

    protected $attributes = [
        'id' => null,
        'key' => null,
        'value' => null,
        'description' => null,
        'status' => null,
        'created_at' => null,
        'updated_at' => null,
        'deleted_at' => null,
    ];

    protected $datamap = [
        'createdAt' => 'created_at',
        'updatedAt' => 'updated_at' ,
        'deletedAt' => 'deleted_at'
    ];

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    protected $casts = [
        'status' => 'boolean',
    ];

    protected $permissions = [];

    protected $roles = [];

    public function activate()
    {
        $this->attributes['status'] = 1;
        return $this;

    }

    public function deactivate()
    {
        $this->attributes['status'] = 0;

        return $this;
    }

    public function isActivated(): bool
    {
        return isset($this->attributes['status']) && $this->attributes['status'] == true;
    }

    public function createdAt()
    {
       // date_default_timezone_set('Asia/Tehran');
        $this->attributes['created_at'] = date('Y-m-d H:i:s', time());
        // $this->attributes['created_at'] = new  Time(date('Y-m-d H:i:s', time()), 'UTC');
        return $this;
    }

    public function updatedAt()
    {

      //  date_default_timezone_set('Asia/Tehran');
        $this->attributes['updated_at'] = date('Y-m-d H:i:s', time());

        return $this;
    }
}
```

**Comment by paulbalandan** [comment]
I don't understand what's the issue here nor the code is not readable. Please format your code using markdown.

**Comment by paliz-git** [comment]
see  it again

**Comment by paliz-git** [comment]
did you see bug  ?!

**Comment by paulbalandan** [comment]
If I understood correctly, your remapping of date fields added in the `$datamap` property is not working?

Try flipping the property mapping:
```php
protected $datamap = [
    'created_at' => 'createdAt',
    'updated_at' => 'updatedAt',
    'deleted_at' => 'deletedAt',
];

**Comment by paliz-git** [comment]
no you are wrong 
i m not beginner  thisn is not the first time i use Entitiy for Model
look at ci documentation 
`Data Mapping
At many points in your career, you will run into situations where the use of an application has changed and the original column names in the database no longer make sense. Or you find that your coding style prefers camelCase class properties, but your database schema required snake_case names. These situations can be easily handled with the Entity class’ data mapping features.

As an example, imagine you have the simplified User Entity that is used throughout your application:

<?php

namespace App\Entities;

use CodeIgniter\Entity\Entity;


Your boss comes to you and says that no one uses usernames anymore, so you’re switching to just use emails for login. But they do want to personalize the application a bit, so they want you to change the name field to represent a user’s full name now, not their username like it does currently. To keep things tidy and ensure things continue making sense in the database you whip up a migration to rename the name field to full_name for clarity.

Ignoring how contrived this example is, we now have two choices on how to fix the User class. We could modify the class property from $name to $full_name, but that would require changes throughout the application. Instead, we can simply map the full_name column in the database to the $name property, and be done with the Entity changes:

<?php

namespace App\Entities;

use CodeIgniter\Entity\Entity;

class User extends Entity
{
    protected $attributes = [
        'id' => null,
        'name' => null,        // Represents a username
        'email' => null,
        'password' => null,
        'created_at' => null,
        'updated_at' => null,
    ];

    protected $datamap = [
        'full_name' => 'name',
    ];
}
By adding our new database name to the $datamap array, we can tell the class what class property the database column should be accessible through. The key of the array is the name of the column in the database, where the value in the array is class property to map it to.

In this example, when the model sets the full_name field on the User class, it actually assigns that value to the class’ $name property, so it can be set and retrieved through $user->name. The value will still be accessible through the original $user->full_name, also, as this is needed for the model to get the data back out and save it to the database. However, unset and isset only work on the mapped property, $name, not on the original name, full_name.`

**Comment by paulbalandan** [comment]
Well, I'm not suggesting you're a beginner whatsoever. I'm just trying to let you try some options to debug your issue.

And mind you, the docs recently got changed with this PR
