### ISSUE TITLE
Dev: using `filter_*` functions instead direct access to global variables

### ISSUE THREAD

**Issue by WinterSilence** [codeigniter4/CodeIgniter4#4968]
Example:
~~~php
$_GET['foo'] = 1;
var_export($_GET); // ['foo' => 1]
var_export(filter_input_array(INPUT_GET)); // []
~~~
As you can see `filter_input_array()` return initial data, it's better use in CI because users (or vendor packages) can change globals before calling CI methods.

If there are no objections, then I will replace direct access to global variables everywhere. I will write sniff to fix this problem in future too.

**Comment by kenjis** [comment]
No feedback. So I close.

I'm still not sure this should be implemented or not, but before implementing this we need to rework all classes that handles the super globals.
These classes should be injected super global values as constructor parameters, not using super globals inside.

**Comment by WinterSilence** [comment]
@kenjis sorry, miss your answer

> By the way, what do you want to achieve with this filter_* function?

I want keep initial data of request. Now request data can be changed by vendor/user code, framework must ignore this changes. If developer wants to make changes, then he must do so by explicitly changing the corresponding method or property.
