### ISSUE TITLE
Bug: false value is blocked in required rule

### ISSUE THREAD

**Issue by OzRib** [codeigniter4/CodeIgniter4#4971]
**Direction**
This is a bug question. I had found the error cause.
Is the empty function in required rule.
A disclaimer: You can clean more the code to a best development experience.

**Describe the bug**
When I use the required rule, the value false is blocked.

**CodeIgniter 4 version**
The composer version presents this error.

**Affected module(s)**
The module Validation/Rules is the only affected.

**Expected behavior, and steps to reproduce if appropriate**
To reproduce this error, you can create a database table with a boolean value or number in a field. 
Before, you try add false  value in the field.

**Context**
 - OS: [Manjaro Linux, latest]
 - Web server [spark server, latest]
 - PHP version [8.0.8]

**Comment by WinterSilence** [comment]
@OzRib please add example to reproduce error. 
In fact, boolean columns is supported only in mysql and stored and work as `tinyint (1)`.

**Comment by OzRib** [comment]
Hello @WinterSilence . 
An example?
Try it:
create a SQL table in your database with a boolean column 
```sql
create table foo(bar boolean not null);
```
 after, create a model to the table

```php
<?php

 namespace App\Models;

use CodeIgniter\Model;

class Test extends Model
{
  protected $table = 'foo';
  protected $validationRules = [
    'bar'=>'required'
  ];
  protected $validationMessages = [
    'bar'=>[
      'required'=>'You can insert a value in bar'
    ]
  ];
}
```
If you try to insert a false value with the save, insert or another similar function you get the configured error

**Comment by OzRib** [comment]
I have started a fork fixing this @WinterSilence .
Can I send a pull request? Is finished.

**Comment by WinterSilence** [comment]
@OzRib 
> Can I send a pull request? Is finished.

why not? (:

**Comment by OzRib** [comment]
Sended (:

**Comment by WinterSilence** [comment]
@OzRib hmm.. strange solution:
1. it's stored as tinyint and CI check it as int
2. your solution is hmm.. "strange"
~~~php
public function required($str = null): bool
{
    if (is_object($str) || is_bool($str)) {
        return true;
    }
    return is_array($str) ? ! empty($str) : (trim($str) !== '');
}
~~~

**Comment by OzRib** [comment]
I tried to turn this more readable. But if is strange I change this. No prob!

**Comment by WinterSilence** [comment]
@OzRib it's less readable, work slower and BC...

**Comment by WinterSilence** [comment]
@OzRib  problem not in validation, you need add pre-filter - look to `Model::$beforeInsert/`Model::$beforeUpdate`

**Comment by OzRib** [comment]
@WinterSilence Okay! Working

**Comment by MGatner** [comment]
See the discussion on the PR, but this is actually working as intended (as far as Validation is concerned): `false` should not pass `required`. 

There are some other discussions about how Query Builder and the database layer should handle boolean values that might be a more appropriate place for this issue.

**Comment by OzRib** [comment]
Okay
