### ISSUE TITLE
Bug: Query builder escapes negative integers

### ISSUE THREAD

**Issue by wradstok** [codeigniter4/CodeIgniter4#4973]
**Describe the bug**
In #606, a bit of code was added that escapes negative values. However, I think negative values should not be escaped at all. For example, I would like to look back at negative dates using something like

```sql
WHERE date_pickup < DateAdd(month, ?, Convert(date, GetDate())
```

Due the conversion, this is translated to

```sql
WHERE date_pickup < DateAdd(month, '-6', Convert(date, GetDate())
```
Which results in an error, since we now pass a varchar to the function instead of an integer.
My question is: why are negative values escaped at all? The offending bit of code checks that the integer is negative before escaping it, and I'm not sure what the original commit intends to solve.

**CodeIgniter 4 version**
Tested in 4.1.3, should be present in all versions.

**Affected module(s)**
`Database/BaseConnection.php` lines 1312 - 1314 in the escape function. Specifically when using SQLSRV driver. Though it should be independent of driver used.

**Context**
 - OS: Windows 10
 - Web server IIS
 - PHP version 8.0

**Comment by kenjis** [comment]
I sent a PR to fix this.  #5277
