### ISSUE TITLE
Bug: Cannot addForeignKey for raw string as field (Forge)

### ISSUE THREAD

**Issue by yogisatya2705** [codeigniter4/CodeIgniter4#4986]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
I cant use `addForeignKey()` in migration when using raw string as field. My code :

```php
  public function up()
  {
    $this->forge->addField([
      "`id` BIGINT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
      "`id_const_satuan_x` BIGINT(11) NOT NULL",
      "`pembanding_x` INT NOT NULL",
      "`id_const_satuan_y` BIGINT(11) NOT NULL",
      "`pembanding_y` INT NOT NULL",
    ]);

    $this->forge->addKey('id', TRUE);
    $this->forge->addForeignKey('id_const_satuan_x', 'const_satuan', 'id', 'NO ACTION', 'CASCADE');
    $this->forge->addForeignKey('id_const_satuan_y', 'const_satuan', 'id', 'NO ACTION', 'CASCADE');
    $this->forge->createTable('const_convert_satuan', TRUE);
  }
```

The error : 

```bash
...
[CodeIgniter\Database\Exceptions\DatabaseException]

Field `id_const_satuan_x` not found.

at SYSTEMPATH/Database/Forge.php:443

Backtrace:
  1    APPPATH/Database/Migrations/2021-08-05-081056_ConstConvertSatuanMigration.php:20
       CodeIgniter\Database\Forge()->addForeignKey()
...
```

**CodeIgniter 4 version**
4.1.3

**Affected module(s)**
system/Database/Forge.php

**Expected behavior, and steps to reproduce if appropriate**

To reproduce the error  you can pass strings as fields, then addForeignKey.

To fix the error i have to make sure the code `$this->forge->addForeignKey` is right in all migration, then comment out line 441 to 444 in `system/Database/Forge.php` to skip valdation fieldname. The function will look like this :

```php
	public function addForeignKey(string $fieldName = '', string $tableName = '', string $tableField = '', string $onUpdate = '', string $onDelete = '')
	{
                // if (! isset($this->fields[$fieldName]))
		// {
		// 	throw new DatabaseException(lang('Database.fieldNotExists', [$fieldName]));
		// }

		$this->foreignKeys[$fieldName] = [
			'table'    => $tableName,
			'field'    => $tableField,
			'onDelete' => strtoupper($onDelete),
			'onUpdate' => strtoupper($onUpdate),
		];

		return $this;
	}
```

**Context**
 - OS:  Ubuntu 20.04
 - Web server Apache 2.4.41
 - PHP version 7.4.3

**Comment by paulbalandan** [comment]
Fixed in #4988
