### ISSUE TITLE
Bug: selected value in multidimensional form_dropdown

### ISSUE THREAD

**Issue by gabriel-pnhr** [codeigniter4/CodeIgniter4#4993]
**Bug**
the selected value does not work in form_dropdown helper with a multidimensional array as input

**Solution to fix it**
In this file : /system/Helpers/form_helper.php 
between line 320 and 321 add the following code : 
`$optgroupKey = (string) $optgroupKey;`

(Exactly as in line 311, so as not to compare an integer with a string)

**Comment by MGatner** [comment]
If you have a solution, please submit a Pull Request!
