### ISSUE TITLE
Bug: What might be the problem with this post request?

### ISSUE THREAD

**Issue by Elvis254** [codeigniter4/CodeIgniter4#5002]
Am getting this error when sending a post request to this controller: `CollectionsController.php`

`CRITICAL - 2021-08-13 15:53:37 --> Call to undefined method CodeIgniter\HTTP\IncomingRequest::getcollection()
#0 C:\xampp\htdocs\chuckle\admin\system\CodeIgniter.php(928): App\Controllers\CollectionsController->sanitizeQuery()
#1 C:\xampp\htdocs\chuckle\admin\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CollectionsController))
#2 C:\xampp\htdocs\chuckle\admin\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\chuckle\admin\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}`

The method in the controller is this one:

`public function sanitizeQuery()
{
return $this->outputJson(['status' => 'success', 'pageUrl' => site_url('collections/search/?query='.esc($this->request->getcollection('query', FILTER_SANITIZE_STRING)))]);
}
else
{
return $this->outputJson(['status' => 'error']);
}
}`

And the route being used is this one:

`$routes->group('collections', ['namespace' => 'App\Controllers', 'filter' => 'role:superUser'], function ($routes) {
    $routes->post('lookup', 'CollectionsController::sanitizeQuery');
});`

The request is ajax and remember its not a jQuery ajax error. I think its a bug. Or what is the problem because I can't perform the post request but the get requests are working fine.

**Comment by Elvis254** [comment]
Ooops...! I have just noticed the error. Quite sorry too fast on debugging. Its this one:

`esc($this->request->**getcollection**('query', FILTER_SANITIZE_STRING)))])`

**Comment by lonnieezell** [comment]
Glad you caught it. Please use the forums for help in the future. We try to reserve the Issues here for bugs.
