### ISSUE TITLE
Bug: Undefined constant CodeIgniter\CLI\STDERR

### ISSUE THREAD

**Issue by tonynamy** [codeigniter4/CodeIgniter4#5006]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
Calling custom commands which uses CodeIgniter\CLI\CLI::error method in controller via command() method makes PHP Fatal Error : 
Undefined constant "CodeIgniter\CLI\STDERR"

**CodeIgniter 4 version**
codeigniter/framework v4.1.3 (composer)

**Affected module(s)**
CodeIgniter\CLI\CLI

**Expected behavior, and steps to reproduce if appropriate**
Calling custom commands in controller should not throw such php fatal error.

I solved this problem by extending CodeIgniter\CLI\CLI class and overriding function like below:

`public static function error(string $text, string $foreground = 'light_red', string $background = null)
{
        if (is_cli()) {
            parent::error($text, $foreground, $background);
        } else {
            static::fwrite(STDOUT, $text . PHP_EOL);
        }
}`

This solution makes error messages to be printed through STDOUT stream. 
But I think CodeIgniter\CLI\CLI should handle this situation (using CLI::error in custom commands which can be callable in controllers) or at least, throwing an Exception not Php Fatal Error (which means this error is not handled by framework).

**Context**
 - OS: Ubuntu 18.04.5 LTS
 - Web server Apache 2.4.29
 - PHP version 8.0.8

**Comment by MGatner** [comment]
I think @paulbalandan already fixed this on `4.2`, perhaps?

**Comment by paulbalandan** [comment]
Yes, fixed in 4.2
