### ISSUE TITLE
findAll() throw exception, message:"Call to a member function getResult() on bool"

### ISSUE THREAD

**Issue by khunemz** [codeigniter4/CodeIgniter4#5036]
My code is 
```
class EmployeeController extends BaseController
{
	public function index()
	{
		$model = new EmployeeModel();
		$employees = $model->findAll();
		return view('employee/index', ['employees' => $employees]);
	}
}
```

Throw exception on `$employees = $model->findAll();`

the message is 
```
message:"Call to a member function getResult() on bool"
```

**Comment by MGatner** [comment]
You would need to share the full error trace, but my wild guess is that you are trying to use a database driver without having the extension installed.

**Comment by paulbalandan** [comment]
> message:"Call to a member function getResult() on bool"

This means that instead of a `ResultInterface` given by the read operation, it instead resulted to a `false` value which ultimately means there's something wrong in the query execution. Please check if you can connect successfully to your database OR you have a fully functioning database.
