### ISSUE TITLE
Bug: url_to() does not take into account the default namespace

### ISSUE THREAD

**Issue by ivanBell199** [codeigniter4/CodeIgniter4#5042]
**Describe the bug**
The example from the docs `echo url_to('Home::index');` does not work. Instead it needs to be `url_to('App\Controllers\Home::index')` .

However if I have a folder inside "Controllers" I still cannot get the path. For example, `url_to('App\Controllers\Admin\Categories::index')` throws error `Controller or its method is not found: App\Controllers\Admin\Categories::index
`
Am I missing something?

**CodeIgniter v4.1.3**

**Comment by sfadschm** [comment]
The first argument of the function should be a class and function name,not a path. The example works for a class `Home` with method `index`. In your case , the class name needs to be fully qualified, i.e. you should provide the complete class name including the namespace.

**Comment by ivanBell199** [comment]
I am sorry. Didn't figure out that `url_to()` only works if the route is stated insite `Config/Routes`.

**Comment by szajens** [comment]
the bug still has not been fixed, you have to patch it yourself

**Comment by kenjis** [comment]
This seems a bug in the documentation.
1. The first argument of the function should be a fully qualified classname and function name
2. This function uses reverse routing, that is you need to define the route.

**Comment by szajens** [comment]
> This seems a bug in the documentation.
> 
> 1. The first argument of the function should be a fully qualified classname and function name
> 2. This function uses reverse routing, that is you need to define the route.

You may be right.  But look at the routes-add () declaration, right there $routes->add('blog/joe', 'Blogs::users/34'); there no namespace

**Comment by kenjis** [comment]
@szajens You have a point. The specifications are not consistent.

**Comment by szajens** [comment]
Cool, thanks.
