### ISSUE TITLE
Pass the $field and $label variables to the custom rule method

### ISSUE THREAD

**Issue by chalda-pnuzig** [codeigniter4/CodeIgniter4#5047]
In custom rules it would be useful to be able to access the $field and $label variable, so they can be used with localization

https://github.com/codeigniter4/CodeIgniter4/blob/cca4660e54acad5e77820a218bc0b4a1d16cebca/system/Validation/Validation.php#L270-L280

Example: 
```php

     // Check in our rulesets 
     foreach ($this->ruleSetInstances as $set) { 
         if (! method_exists($set, $rule)) {
             continue; 
         } 
  
         $found  = true; 
         $passed = $param === false ? $set->{$rule}($value, $error, $field, $label) : $set->{$rule}($value, $param, $data, $error, $field, $label);  // HERE
  
         break; 
     } 
```

**Comment by paulbalandan** [comment]
You can send in a PR for this. Please make sure to accompany your PR with some tests for it to be accepted. Thanks.
