### ISSUE TITLE
make:model generate wrong entity

### ISSUE THREAD

**Issue by swearl** [codeigniter4/CodeIgniter4#5050]
situation 1:
```
php spark make:model MyTable --suffix Model --return entity
```

result:
Models/MyTableModel.php generated. (correct)
the returnType of MyTableModel.php is 'App\Entities\MyTableEntity' (correct)
Entities/MytableEntity.php generated. ( Entities/MyTableEntity.php expected )

situation 2:
```
php spark make:model SubFolder/MyTable --suffix Model --return entity
```

result:
Models/SubFolder/MyTableModel.php generated. (correct)
the returnType of MyTableModel.php is 'App\Entities\SubFolder\MyTableEntity' (correct)
Entities/MytableEntity.php generated. ( Entities/SubFolder/MyTableEntity.php expected )

**CodeIgniter 4 version**
4.1.3

**Comment by kenjis** [comment]
I've confirmed this bug on `develop`.

```
$ php spark make:model MyTable --suffix Model --return entity

CodeIgniter v4.1.3 Command Line Tool - Server Time: 2021-09-03 02:42:22 UTC-05:00

File created: APPPATH/Entities/MytableEntity.php

File created: APPPATH/Models/MyTableModel.php
```

```
$ php spark make:model SubFolder/MyTable --suffix Model --return entity

CodeIgniter v4.1.3 Command Line Tool - Server Time: 2021-09-03 02:42:59 UTC-05:00

File exists: APPPATH/Entities/MytableEntity.php

File created: APPPATH/Models/SubFolder/MyTableModel.php
```
