### ISSUE TITLE
Bug: $viewFile is undefined

### ISSUE THREAD

**Issue by veryslybadger** [codeigniter4/CodeIgniter4#5051]
**Describe the bug**
at line 278, if $viewFile has not been set, the debugger will crash with unknown variable $viewFile.
so at line 258 i've added           $viewFile='"" 
and changed line 278 
from           include $viewFile; // @phpstan-ignore-line
to                if(strlen($viewFile)>0) include $viewFile; // @phpstan-ignore-line
bill

**CodeIgniter 4 version**
4.1.3

**Affected module(s)**
System-Debug-Exceptions

**Expected behavior, and steps to reproduce if appropriate**
happens when a crash occurs

**Context**
 - Web server [e.g. Apache 2.1]
 - PHP version [e.g. 7.3]

**Comment by paulbalandan** [comment]
Most likely this is because (1) your default view files in `app/Views/errors/` are gone, misplaced, or renamed; or (2) the path provided in `\Config\Exceptions::$errorViewPath` is changed and wrong.

**Comment by veryslybadger** [comment]
yes, you're 100% correct, i hadn't copied views/errors to the server,
apologies for that
