### ISSUE TITLE
Bug: Routes with hashtags when POST

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#5056]
**Direction**

         $routes->post('{locale}/account/edit-profile#services', 'Account::edit');

inside form

         <?=form_open(base_url(route_to('{locale}/account/edit-profile#services')), ['autocomplete' => 'off'])?>

**Describe the bug**
Receiving Error

         ErrorException
         preg_match(): Unknown modifier 'r'
         SYSTEMPATH/Router/Router.php at line 357

Complaining line

         357             if (preg_match('#^' . $key . '$#u', $uri, $matches)) {

**CodeIgniter 4 version**
Im on Latest update

**Context**
 - PHP version 7.4

**Comment by iRedds** [comment]
The browser does not send the URI fragment to the server, so your route is meaningless.
But if you want to use a hashtag, escape it.

**Comment by Elvis254** [comment]
I thought hashtags in a url string are used to scroll the page upto the html element with that specific id which is the string after the hashtag or what exactly do you want to process here?

**Comment by kenjis** [comment]
This is not a bug.
The URI in your route should be `{locale}/account/edit-profile`.
