### ISSUE TITLE
Port FTP library from CI3

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#506]

**Comment by coderste** [comment]
I can do this if we're just porting it over and updating it to match the PHP7 Standards. Let me know exactly what I need to do and I'll get to it over the weekend

**Comment by lonnieezell** [comment]
Well, damn, that's probably why I hadn't had it listed here before. :) 

@jim-parry What do you think? I've actually already included the Typography library since I think it's handy enough of the time to keep around. I don't have problems with them being in core, personally, and don't really recall the reasons for keeping them out.

**Comment by coderste** [comment]
Well if we were to include them in core I'd be more than happy to port the FTP Library over :)

**Comment by lonnieezell** [comment]
@coderste Tell you what - while we determine whether they're being included in core, if you want to go ahead and port, that would be great. Even if we remove it to its own repo later, it still needs to be ported. 

Basically it's just a straight port to use more current PHP7 standards, and to fit in with how CI4 is currently working, which might require a new Service method added in `system/Config/Services` if it has any dependencies. Also - any tests that you can make work with it (check the CI3 repo to see if those tests are worth using.) and docs, please. 

Thanks!

**Comment by byazrail** [comment]
@lonnieezell hello,
i'm finished 1~2 months ago FTP library.
Push requested.

See codes;
https://github.com/bcit-ci/CodeIgniter4/pull/508

**Comment by coderste** [comment]
@byazrail ha I see - any Tests written for that? If not I don't mind writing some and opening a PR also I think we may need to update the documentation :)

**Comment by byazrail** [comment]
@coderste oo I see - testing documentation. testing after request update.

**Comment by coderste** [comment]
@byazrail I believe they mean PHP Unit Test and Document Updates :)

**Comment by jim-parry** [comment]
Ok, now we have two FTP ports ? Shows the wisdom of discussing it at the issue level, and "assigning" someone, to prevent duplicaiton.
"Porting" something from CI3 means fitting it into the CI4 "structure", with a Services method if needed, namespacing, conforming to the CI4 style guide (class, metho & variable naming, for instance, that would probably differ from CI3), updating or creating unit tests, and updating the user guide.

**Comment by coderste** [comment]
We can work on this PR for that now and just remove the other issue, I am also trying to revert my commit on the other branch

**Comment by jim-parry** [comment]
As for the libraries to remove or not, I have no problem with typography and ftp making their way here.

The Zip library sounds like it might suit a Compresser service, with adapters (er, handlers) for some of the compression extensions supported by PHP (zip, phar, bzip2, etc). It could start out as a straight port, but we want to keep the future in mind.

XML-RPC is a beast unto itself, and should be a separate addin. The CI3 implementation is overly complicated, and lacking some functionality (eg using TLS), and needs re-thinking, not just re-porting. I see it as part of a larger group of client/server services (eg SOAP, REST), that are better addressed once we get the basics done.

**Comment by atishamte** [comment]
As per the features of CI4, FTP will not be a part of framework
https://forum.codeigniter.com/thread-71705.html

**Comment by MGatner** [comment]
Confirmed there will be no `FTP` class in CI4.
