### ISSUE TITLE
Undefined variable in RedisHandler (line 140)

### ISSUE THREAD

**Issue by tzalexander** [codeigniter4/CodeIgniter4#5066]
Hi there,

i have updated to the latest version of CI (4.1.4.) (from 4.1.3.).
The Redis session is broken at line 140.

$this->sessionID = ${$id}; 

I get the error "Undefined variable $"theultralongsessionkeyhere"".

Is there any reason why a variablevariable is used here?

Thank you, Best Regards,
Alex

**Comment by sfadschm** [comment]
Should be fixed in `develop,` see #5062.
Be aware that many other changes from `4.2` were merged in the meantime. Maybe cherrypick the commit or fix the error manually until the next release for now.
