### ISSUE TITLE
[Forge] Setting key name manually for keys (unique, foreign, etc.)

### ISSUE THREAD

**Issue by najdanovicivan** [codeigniter4/CodeIgniter4#5075]
**Describe the bug**
Currently there is no way to manually set the key name. This can lead to issue when there are a lot of columns for which key  should be added as auto generated name will be longer than the database will allow. 
Additionally when tables are being renamed it may be needed to manually set the key name as key with the same name might already exist

**CodeIgniter 4 version**
develop

**Affected module(s)**
Forge

**Expected behavior, and steps to reproduce if appropriate**
To reproduce with mysql just try adding key with a lot of columns
$forge->addKey(['column1','column2','column3','column4','column5','column6',);

We should be able to pass the key name string in the `addKey`, `addPrimaryKey`, `addUniqueKey`, `addForeignKey` methods

**TODO**
- [x] addKey #6552
- [x] addPrimaryKey #6552
- [x] addUniqueKey #6552
- [x] addForeignKey #6468

**Comment by paulbalandan** [comment]
I don't see this as a bug but a current limitation of the Forge which can be improved further. I can try tackling this but that might take some time as I'm currently swamped but if anyone, including you, can open an introductory PR to implement this then that will be a great starter.
