### ISSUE TITLE
Bug: Session Database Handler timestamp

### ISSUE THREAD

**Issue by bedrijfsportaal** [codeigniter4/CodeIgniter4#5080]
**Describe the bug**
I'm using the session database handler, with the package of [Myth\Auth](https://github.com/lonnieezell/myth-auth). But the query field 'timestamp' isn't updating to the current_timestamp(), have been looking for solutions inside the [documentation](https://codeigniter.com/user_guide/libraries/sessions.html#databasehandler-driver) but unable to locate any mistakes.

**CodeIgniter 4 version**
4.1.4

**Affected module(s)**
Only using [Myth\Auth](https://github.com/lonnieezell/myth-auth) version 1.0.1 at this moment, don't know if it's related to this issue.

**Expected behavior, and steps to reproduce if appropriate**
Create timestamp on insert instead of 0000-00-00 00:00:00

**Context**
 - OS: Windows 10 (localhost)
 - Database: MariaDB 10.3.31
 - PHP version: 8.0.7

_If more information is required to describe this please let me know!_

**Comment by paulbalandan** [comment]
There is already a fix for this in the latest develop branch. Kindly use that to test.

**Comment by bedrijfsportaal** [comment]
Confirmed that works, thank you.
