### ISSUE TITLE
Bug: Exception occurs when `$db->fieldExists()` does not meet the conditions.

### ISSUE THREAD

**Issue by tomomo** [codeigniter4/CodeIgniter4#5082]
Hello.
About `$db->fieldExists()`.

**Describe the bug**
The docs say it returns "true" or "false"(Boolean),
But if it is "false" it will return a `BadMethodCallException`.

https://codeigniter.com/user_guide/database/metadata.html
```
$db->fieldExists()

Sometimes it’s helpful to know whether a particular field exists before performing an action. Returns a boolean true/false. Usage example:

if ($db->fieldExists('field_name', 'table_name')) {
    // some code...
}
```
**CodeIgniter 4 version**
4.1.4

**Comment by kenjis** [comment]
How to reproduce?

On `develop`, this test passes:
https://github.com/codeigniter4/CodeIgniter4/blob/04a31f00f6b293bf82587179cab9bd93e54ebb86/tests/system/Database/Live/ForgeTest.php#L914

**Comment by paulbalandan** [comment]
Looking at the code, there's nothing that shows it throws a BadMethodCallException
