### ISSUE TITLE
Possible debug toolbar css problem

### ISSUE THREAD

**Issue by rramsey** [codeigniter4/CodeIgniter4#5097]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
When the debug toolbar is enabled, the style element at the end of the toolbarContainer div is missing the style declaration.  I think this may be from bad data getting in the $styles object.  

````html
<style type="text/css">
    .debu
</style>
````
I think this is around like 270 in the toolbar.tpl.php where it's looping through the names in the $styles, but I'm not sure.

**CodeIgniter 4 version**
4.0.5

**Affected module(s)**
The debug toolbar

**Expected behavior, and steps to reproduce if appropriate**
Expect a complete style element. with a reference to an existing class.  There may be an element with a debu class, but I didn't see it immediately.  Something like this:
````html
<style type="text/css">
    .debug {
        font-size: 18pt;
        color: blue;
    }
</style>
````
Or whatever style is appropriate.

**Comment by kenjis** [comment]
I confirmed the css on `develop`. But I'm not sure where it comes from.

![Screenshot 2021-09-16 18 54 46](https://user-images.githubusercontent.com/87955/133591848-1a296da9-a42e-49fd-9cc8-1a700b913aa0.png)

**Comment by kenjis** [comment]
Putting `var_export($styles)` before the `<style>` below shows:
```
array (
  'debug-bar-timeline-0' => 'left: 15.833377838135%; width: 20.879904429118%;',
  'debug-bar-timeline-1' => 'left: 36.718050638835%; width: 39.025147755941%;',
  'debug-bar-timeline-2' => 'left: 76.21169090271%; width: 11.881589889526%;',
  'debug-bar-timeline-3' => 'left: 88.104804356893%; width: 0.82492828369141%;',
  'debug-bar-timeline-4' => 'left: 88.108380635579%; width: 0.46491622924805%;',
  'debug-bar-timeline-5' => 'left: 88.644822438558%; width: 0.20345052083333%;',
  'debug-bar-timeline-6' => 'left: 89.01834487915%; width: 113.21147282918%;',
)
```

https://github.com/codeigniter4/CodeIgniter4/blob/cc3af87ed207681a4d9e81da96e3d349eeb0031b/system/Debug/Toolbar/Views/toolbar.tpl.php#L267-L274

**Comment by rramsey** [comment]
Well, I'm sorry I found a bug, but I'm glad it wasn't something stupid I've done.  It's almost like the $name is getting truncated or something.  

I don't know how much help I can right now.  This is getting ready to move to a production site, so I don't want to play too much with the development build.  Plus our environment has multiple apps using a shared system folder, which means the system/ folder is essentially read only ATM.

Is the $styles variable available to the controllers or views?
