### ISSUE TITLE
How do I write this recursive function in the common file

### ISSUE THREAD

**Issue by Elvis254** [codeigniter4/CodeIgniter4#5104]
Hi,
I am writing this recursive function which is supposed to give me a random integer on each execution but it only returns a value once, twice, thrice or no value at all. Am not sure what I might be doing wrong. Please, help me out.
Elvis.

`
if ( ! function_exists('getRandomInt'))
{
	/**
	 * Get Random Int
	 *
	 * Lets you generate a random integer of a desired minimum and maximum length.
	 *
	 * @param	int 	$len
	 * @param 	int 	$min
	 * @param 	string 	$max
	 * @return	string 	a random integer of a desired minimum and maximum length
	 */
	function getRandomInt(int $len, int $min, int $max)
	{
		helper('text');

		$randomInt = random_string('numeric', $len);

		if ($randomInt > $min && $randomInt < $max)
		{
			return $randomInt;
		}

		getRandomInt($len, $min, $max);
	}
}
`

**Comment by kenjis** [comment]
Please ask support questions on our [forum](https://forum.codeigniter.com/forum-30.html).
We use github issues to track bugs and planned work.

**Comment by Elvis254** [comment]
I used `mt_rand()` instead. Thanks.
