### ISSUE TITLE
Git pre-commit takes no params

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#5107]
There is code in `pre-commit`:
https://github.com/codeigniter4/CodeIgniter4/blob/4b3a03af9efec77685ccba684955fae109a8dd41/admin/pre-commit#L6-L13

But it seems it makes no sense.

To check, I added the following code:
```diff
--- pre-commit.orig     2021-09-20 09:33:38.000000000 +0900
+++ pre-commit  2021-09-20 09:36:17.000000000 +0900
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+echo "$@"; exit 1
+
 PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
 STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php$`
 
```

And run `git commit`:
```
$ git commit

$ git commit -- user_guide_src/ghpages.rst

$ 
```

And I found the docs:
>  pre-commit
>
> This hook is invoked by git-commit[1], and can be bypassed with the --no-verify option. It takes no parameters, and is invoked before obtaining the proposed commit log message and making a commit. E
https://git-scm.com/docs/githooks

**Comment by paulbalandan** [comment]
This one is copied over from the same file in cakephp, I think. That part I think is to manually test the script before being deployed as a git hook. Something like:
```console
$ bash admin/pre-commit file1.php file2.php
```

**Comment by kenjis** [comment]
It is from https://tech.zumba.com/2014/04/14/control-code-quality/ ?

> That part I think is to manually test the script before being deployed as a git hook.

Maybe. But it uses only `$1`. Like this?

```
$ bash admin/pre-commit "file1.php file2.php"
```

In any case, it's code that is difficult to understand.
