### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [codeigniter4/CodeIgniter4#5110]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by MGatner** [comment]
Thank you @JamieSlome - were already rolling out SECURITY files to our modules, we will get one in here soon! 

The security email address is not routing correctly right now. Please email @lonnieezell directly at lonnieje@gmail.com. I will let him know you will be in touch.
