### ISSUE TITLE
Bug: spark migration allow null by default ( ignores 'null' parameter )

### ISSUE THREAD

**Issue by puschie286** [codeigniter4/CodeIgniter4#5113]
**Describe the bug**
migration with "php spark migrate" always allow null values, even if 'null' parameter is set in column configuration

**CodeIgniter 4 version**
4.1.3

**Expected behavior, and steps to reproduce if appropriate**
migration should behave identical with service::migration and spark migrate ( NOT NULL by default and respect 'null' parameter from column configuration )

**Context**
 - OS: windows 10
 - Web server: apache 2.4.49
 - PHP version: 8.0.1

**Comment by kenjis** [comment]
Could you give us an example code?
And what is your database?

**Comment by puschie286** [comment]
EDIT: not sure if it was a sql server bug but manual deletion of the column fixed the issue

we use a ms server 2019 and try to alter an existing table.

migration config:
```
$this->forge->addColumn( 'Antraege', [
	'Offen' => [
		'type'          => 'INT',
		'constraint'    => 5,
		'unsigned'      => true,
		'default'       => -1,
		'null'          => false,
	]
] );
```
