### ISSUE TITLE
Bug: Query binding fails when date_format is set with '%H:%i:%s'

### ISSUE THREAD

**Issue by andreipa** [codeigniter4/CodeIgniter4#5114]
**Describe the bug**
Query builder is binding incorrectly the statement with date_format (eg. %d/%m/%Y %H:%i:%s) - 22/09/2021 10:45:00 and crash.

```php
<?php

$id = 1;
//Works
$sql = " SELECT mytable.id, DATE_FORMAT(mytable.created_at,'%d/%m/%Y %H:%i') AS created_at_uk FROM mytable WHERE mytable.id = ?";
$query = $this->db->query($sql, [$id]);

//DOES NOT work
$sql = " SELECT mytable.id, DATE_FORMAT(mytable.created_at,'%d/%m/%Y %H:%i:%s') AS created_at_uk FROM mytable WHERE mytable.id = ?";
$query = $this->db->query($sql, [$id]);

```
As you can see, the only difference between both SQL is the `:%s`. This should not be binding as the (%s) means seconds on date_format.

**CodeIgniter 4 version**
CI 4.1.3

**Affected module(s)**
Not sure but looks like is Query.php

**Expected behavior, and steps to reproduce if appropriate**
Should return the query with day/month/year hour:minute:second

**Context**
 - OS: Mac
 - Web server Apache
 - PHP version 8.0

**Comment by kenjis** [comment]
`:%i:` matches the following regexp:
https://github.com/codeigniter4/CodeIgniter4/blob/fd824042df6be1375d6ea8ae5919a3d61c109b4b/system/Database/Query.php#L278

See https://regex101.com/r/lSp7qq/2

**Comment by kenjis** [comment]
Ref #4769

**Comment by vlakoff** [comment]
Refs #5138.
