### ISSUE TITLE
Bug: Error Send Email with CodeIgniter v4.1.3

### ISSUE THREAD

**Issue by ferdyciputra** [codeigniter4/CodeIgniter4#5115]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
I get an error when sending an email with config protocol smtp and codeigniter version 4.1.3

Message Error:
`Email: sendWithSmtp throwed fsockopen(): php_network_getaddresses: getaddrinfo failed: No such host is known.`

But with same email config I successfully sending an email with codeigniter version 4.0.4

**CodeIgniter 4 version**
v4.1.3

**Affected module(s)**
Not sure but looks like is /system/Email/Email.php

**Expected behavior, and steps to reproduce if appropriate**
Should successfully sending email with codeigniter version 4.1.3

**Context**
 - OS: Windows 10
 - Web server Apace
 - PHP version 7.4.18

**Comment by paulbalandan** [comment]
This is not a bug from the framework but an issue in your connection (DNS, etc.). Check this forum link for debugging steps.
https://forum.codeigniter.com/thread-16736.html

**Comment by ferdyciputra** [comment]
oke thanks @paulbalandan
