### ISSUE TITLE
Bug: Model - Should Update Will Reset Query when $useAutoIncrement is false

### ISSUE THREAD

**Issue by najdanovicivan** [codeigniter4/CodeIgniter4#5126]
**Describe the bug**
When save method is called the query will be reset when checking if there is already a value in the db conflicting with the update. 

**CodeIgniter 4 version**
git development branch

**Affected module(s)**
CodeIgniter\Model

**Expected behavior, and steps to reproduce if appropriate**
If override is made to save method which is needed when composite keys are being used. The parameters set to where will be stripped. Consider the following example:

```php
class ModelWithCompositeKey extends Model
{
    protected $primaryKey = 'key1';

    protected $useAutoIncrement = false;

    public function save($data): bool
    {
         $this->where('key2', $data->key2);
         parent->save($data);
    }
}
```

Where section is needed so that shouldUpdate() method is called with both key1 and key2 in where section. 
With this code Insert will work fine but the update will execute query only with key1 in where section. so in order for this to work on update an override on update method is also needed.

```php
public function update($id, $data): bool
    {
         $this->where('key2', $data->key2);
         parent->update($id, $data);
    }
```

I believe the builder instance should be cloned in shouldUpdate() method in order not to reset the query when checking for the existing data.

**Comment by paulbalandan** [comment]
No feedback received. Closing..
