### ISSUE TITLE
Handle lowercase in request headers

### ISSUE THREAD

**Issue by shishamo** [codeigniter4/CodeIgniter4#5131]
Hi the team. Thanks for your work.
We are using web api in the front on our project and the request headers are send in lowercase.
The method isAJAX in the IncomingRequest class (and maybe some methods in other classes) looks like handling capitalized headers only.
Is there a possibility to and this feature? Or is there a way is some Codeigniter settings maybe?
Thank you very much

**Comment by kenjis** [comment]
What does your request headers look like?

**Comment by ytetsuro** [comment]
@shishamo 

> request headers are send in lowercase.

Direct description not found, but the PHP documentation says that the global variable $_SERVER is filled by the specification CGI1.1 (RFC 3875), which states that.

> Meta-variables with names beginning with "HTTP_" contain values read from the client request header fields, if the protocol used is HTTP. The HTTP header field name is converted to upper case, has all occurrences of "-" replaced with "_" and has "HTTP_" prepended to give the meta-variable name.

https://www.php.net/manual/ja/reserved.variables.server.php

In CodeIgniter, the header is obtained from the `$_SERVER` variable as shown below, so perhaps the uppercase or lowercase is not relevant.

https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/HTTP/MessageTrait.php#L88-L99

**Comment by shishamo** [comment]
@kenjis 
«X-Requested-With» lowercase version

**Comment by kenjis** [comment]
@shishamo Sorry, I can't what you mean *lowercase version*.

As you can see https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/HTTP/MessageTrait.php#L88-L99
It seems that header names are processed with case-insensitive.

> The method isAJAX in the IncomingRequest class (and maybe some methods in other classes) looks like handling capitalized headers only.

No.

Please ask support questions on our [forum](https://forum.codeigniter.com/forum-30.html).
We use github issues to track bugs and planned work.

**Comment by shishamo** [comment]
@kenjis @ytetsuro 
Ok I got the point, sorry guys for the inconvenience
