### ISSUE TITLE
[QueryBuilder] The combination of the `setUpdateBatch()` and the `updateBatch()` is difficult to use.

### ISSUE THREAD

**Issue by ytetsuro** [codeigniter4/CodeIgniter4#5134]
The combination of the `setUpdateBatch` method and the `updateBatch` method is difficult to use.

If you try to use it, it will look like the following.

```php
$builder->setUpdateBatch([
    [
        'id'          => 2,
        'name'        => 'SUBSTRING(name, 1)',
        'description' => 'SUBSTRING(description, 3)',
    ],
    [
        'id'          => 3,
        'name'        => 'SUBSTRING(name, 2)',
        'description' => 'SUBSTRING(description, 4)',
    ],
], 'id', false);

$builder->updateBatch(null, 'id', 100);
```

1. updateBatch method hasn't `escape` argument.
2. We have specified index as the second argument of the setUpdateBatch method, but we need to specify the same value for the second argument of `updateBatch`.
3. In combination with 2, when using setUpdateBatch, you need to specify null as the first argument of the updateBatch method. It is difficult for a client to write such a code without knowing the implementation.

In my opinion, it would be easier for developers to use if they can write the following.

```php
$builder->updateBatch([
    [
        'id'          => 2,
        'name'        => 'SUBSTRING(name, 1)',
        'description' => 'SUBSTRING(description, 3)',
    ],
    [
        'id'          => 3,
        'name'        => 'SUBSTRING(name, 2)',
        'description' => 'SUBSTRING(description, 4)',
    ],
], 'id', false, 100);
```

or 

```php
 $builder->setUpdateBatch([
    [
        'id'          => 2,
        'name'        => 'SUBSTRING(name, 1)',
        'description' => 'SUBSTRING(description, 3)',
    ],
    [
        'id'          => 3,
        'name'        => 'SUBSTRING(name, 2)',
        'description' => 'SUBSTRING(description, 4)',
    ],
], 'id', false);

$builder->updateBatch(100);
```

What do you think?

**Comment by kenjis** [comment]
In both cases, it is a breaking change in the public API of updateBatch().

**Comment by ytetsuro** [comment]
You are right.

**Comment by ytetsuro** [comment]
@kenjis 

Thanks, response.

> If you change it to accept int, it is breaking change.

Sure!
I'm sorry.😞

> You could write code like this on PHP8:

Oh! You are great!
This is very readable.

> Or how about this?

Thanks.
I think very very well.😍
I will make this PR.
