### ISSUE TITLE
Can we extend environment suce as "qa" or "testing2"?

### ISSUE THREAD

**Issue by gitHusband** [codeigniter4/CodeIgniter4#5141]
Hey,

I want to set testing config which is deferent to development. 

But I see https://github.com/codeigniter4/CodeIgniter4/issues/4415
<pre>You should probably never set the environment to testing. This is designed specifically to work with unit tests and can definitely mess things up.</pre>

So I need one more environment set up to help me test in QA environment.

Can we extend environment suce as "qa" or "testing2"?

**Comment by lonnieezell** [comment]
In the future, please ask questions on the forums. GitHub is for bug-tracking. 

You can name your environments anything you want, other than `testing`, which is reserved for running tests during development. 

No need to extend it, though. If you're running another server, or domain, etc, then simply use another `.env` file with the correct settings.
