### ISSUE TITLE
Dev: Debug Toolbar should display queries on the timeline

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#5159]
Currently, the Debug Toolbar will list Query on the timeline and display the time it took. However, there's no way to tell how what query it was. 

I would like us to show, on the row just below where `Query` is listed, the query itself. This like should be hidden by default, but should be expandable by clicking on the row where `Query` is listed. 

We should use the same type of highlighting that is already happening on the Queries page. 

![Screen Shot 2021-09-30 at 10 35 34 PM](https://user-images.githubusercontent.com/51931/135561382-1b9a3886-88c8-442c-baa2-854d1ac4d098.png)

**Comment by danielTiringer** [comment]
I'll take a crack at this issue.
