### ISSUE TITLE
Dev: Debug Toolbar should show correct count of connections

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#5160]
![Screen Shot 2021-09-30 at 10 39 18 PM](https://user-images.githubusercontent.com/51931/135561680-791b3d26-a314-4499-be22-4b5c07621403.png)

Currently, the Debug Toolbar displays `0 Connections`, even though I know it just used a connection. This should show the proper connection count.

**Comment by danielTiringer** [comment]
I have an idea on how to get this issue fixed and would like to work on it.

**Comment by lonnieezell** [comment]
Great! I've assigned this to one to you. Thanks for helping out.
