### ISSUE TITLE
Model replace set created_at and updated_at to 0000-00-00

### ISSUE THREAD

**Issue by allyblaise** [codeigniter4/CodeIgniter4#5229]
When using replace function to update or insert into the table it works but set created_at and updated_at to 0000-00-00.

codeigniter v4.1.4

**Comment by ytetsuro** [comment]
@allyblaise 

We would be happy if you could tell us what driver you are using and the minimum code to reproduce.

**Comment by kenjis** [comment]
Yes. We have the issue template:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md

If you follow it, it would be a great help for us.

**Comment by paulbalandan** [comment]
@allyblaise are you able to confirm this? if not or no further feedback, i'll promptly close this.

**Comment by paulbalandan** [comment]
Closing this as no feedback received.
