### ISSUE TITLE
Bug: Migration files not created in the correct directory

### ISSUE THREAD

**Issue by Nudasoft** [codeigniter4/CodeIgniter4#5260]
**Context**
 - OS: [e.g. Windows 10 pro]
 - PHP version: [e.g. PHP 8.0.11]
 - CI version: CI4 4.1.4

I've installed a fresh copy of CI4 v4.1.4 on my local machine. and ran `php spark make:migration app_test` command. 
Migration file `AppTest` was created but in the  wrong directory. It created the file in the `CodeIgniter4-4.1.4\app` directory, not in the `CodeIgniter4-4.1.4\app\Database\Migrations`.

I have not done any modifications to the fresh copy of the framework.

And I've tried using namespace option in the command. but that also not seems to be working. It would be great if docs can be updated with a example of how to use that command with namespaces.

Thanks.

**Comment by Nudasoft** [comment]
This issue seems to be fixed in the dev branch. :)

**Comment by kenjis** [comment]
Yeah, we got the same issue yesterday!

Duplicate of #5251
