### ISSUE TITLE
Unclear operands of migration regress when including batch number

### ISSUE THREAD

**Issue by abydahana** [codeigniter4/CodeIgniter4#5296]
### PHP Version

7.3, 7.4

### CodeIgniter4 Version

4.1.4, 4.1.5

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySQLi, PostgreSQL, SQL Server, SQLite3

### What happened?

The statement of batches check seems not correct under /system/Database/MigrationRunner.php
![image](https://user-images.githubusercontent.com/10624446/140797861-35b3de58-5949-401a-bf48-4cd15e568a5c.png)

This statement cause no migration found when specifying the batch number that same as highest number of batches lists.
 
There's my stored batch under the MySQLi database:
![image](https://user-images.githubusercontent.com/10624446/140800063-71bca2b2-a27c-4e6f-9272-a47170d5c925.png)

Call this from my controller:
```$migrate->regress(2);```

Debug result for the defined parameter:
```php
while ($batch = array_pop($batches)) {
```
* The ```$batch``` returns **2**
```php
if ($batch <= $targetBatch) {
```
* The ```$targetBatch``` returns **2**

* The final results of the statement is like this:
```php
if(2 <= 2) {
    break;
}
```

This is a little confusing because if I want to delete the batch number **2**, I have to give **1** to the ```regress``` parameter: ```$migrate->regress(1);```

### Steps to Reproduce

Update the operands to:
```php
if ($batch < $targetBatch) {
    break;
}
```

### Expected Output

Correct usage batch numbering for ```regress``` method on migration.

**Comment by kenjis** [comment]
The first argument `$targetBatch` of the `regress()` is target batch number.
`$migrate->regress(2)` means go down to `2`. If `2` is the current, do nothing.
`$migrate->regress(1)` means go down to `1`.

**Comment by abydahana** [comment]
Oh i got it. I thought the ```$migrate->regress(2)``` will execute the batch number ```2```. Thank you for explanation. The documentation ```1+ specifies the batch``` confused me.

**Comment by kenjis** [comment]
You are welcome.
`1+ specifies the batch` is a bit difficult to understand for me.

**Comment by ChibuezeAgwuDennis** [comment]
Please I am not still clear with this. I am I want to regress on a particular module migration without regressing other module migration

my db migration batch = 2;

Please explain further on this
