### ISSUE TITLE
Config/Filters for subdomain

### ISSUE THREAD

**Issue by c4user** [codeigniter4/CodeIgniter4#5304]
I add routes for subdomain but no subdomain option for filters. For example, I add routes with `admin.test.com` for admin, when I want to add filters for this field, it works for both `users.test.com` and `admin.test.com`. Filters should have options for hostname and subdomain, just like methods.

**Comment by kenjis** [comment]
@c4user 
> when I want to add filters for this field, it works for both users.test.com and admin.test.com. 

What do you mean? Does not work like this?

```php
// Limit to admin.example.com
$routes->get(
    'admin',
    'Admin::index',
    [
        'subdomain' => 'admin',
        'filter' => 'admin-auth',
    ]
);
```

**Comment by c4user** [comment]
@kenjis It works for Config/Routes.php. But there is no such option for the Config/Filters.php file. Can you give an example for Config/Filters.php?

**Comment by kenjis** [comment]
No, there is no options in `Config/Filters.php` to specify sub-domain.

**Comment by kenjis** [comment]
Please submit feature requests to our [forum](https://forum.codeigniter.com/forum-29.html).
We use github issues to track bugs and planned work.
