### ISSUE TITLE
Uncaught ErrorException: SQLite3::exec(): no such function: "now()" (when store session to database)

### ISSUE THREAD

**Issue by abydahana** [codeigniter4/CodeIgniter4#5306]
### PHP Version

7.3, 7.4

### CodeIgniter4 Version

4.1.5

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

SQLite3

### What happened?

The SQLite3 has no "now()" function for the timestamp type data. A statement needed to make it work under ```system\Session\Handlers\DatabaseHandler.php``` on line ```178```, ```200``` and ```259```

### Steps to Reproduce

Need to give statement within database platform to use supported function:
```php
( $this->platform === 'sqlite3' ? "strftime('%Y-%m-%d %H:%M:%S', 'now')"  :  "now()" )
```

### Expected Output

Query will executed correctly

**Comment by kenjis** [comment]
Thank you for reporting.

> Only **MySQL** and **PostgreSQL** databases are officially supported, due to lack of advisory locking mechanisms on other platforms. Using sessions without locks can cause all sorts of problems, especially with heavy usage of AJAX, and we will not support such cases.
https://codeigniter4.github.io/CodeIgniter4/libraries/sessions.html#databasehandler-driver

But probably the previous version worked with SQLite3, right?

By the way, why do you use SQLite3 for Session? Is it something better than FileHandler?

**Comment by abydahana** [comment]
The previous version using same value and it will probably caught the same case. Your suggestion for using FileHandler for SQLite3 seem good alternative. But does it mean the DatabaseHandler are restricted for SQLite3?

**Comment by kenjis** [comment]
As documented, only MySQL and PostgreSQL are officially supported.

If you see the merit to use Session with SQLite3 and want to fix this problem,
you can send a PR:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md
