### ISSUE TITLE
Bug: listTables() and tableExists() don't work in mysql

### ISSUE THREAD

**Issue by LoganTann** [codeigniter4/CodeIgniter4#5307]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.5

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli (`php ./phpunit.phar`)

### Database

~~kagescan_tests~~ MySQL 8.0

### What happened?

When creating unit tests for my project, `db->tableExists()` always returns false even if a table exists.

### Steps to Reproduce

I created three tables : "scan_chapter", "scan_serie", "scan_volume" using `db->query`.
Then I ran that code to check what was going on : 
```php
$res = $this->db->query(<<<'EOT'
    SHOW TABLES FROM kagescan_tests;
EOT);
throw new Exception( json_encode($res->getResult(), JSON_PRETTY_PRINT)
        ." || ". json_encode($this->db->listTables(), JSON_PRETTY_PRINT)
);
```

output : 
```js
Exception: [
    {
        "Tables_in_kagescan_tests": "db_migrations"
    },
    {
        "Tables_in_kagescan_tests": "scan_chapter"
    },
    {
        "Tables_in_kagescan_tests": "scan_serie"
    },
    {
        "Tables_in_kagescan_tests": "scan_volume"
    }
] || [
    "db_migrations"
]
```

### Expected Output

```js
Exception: [
    {
        "Tables_in_kagescan_tests": "db_migrations"
    },
    {
        "Tables_in_kagescan_tests": "scan_chapter"
    },
    {
        "Tables_in_kagescan_tests": "scan_serie"
    },
    {
        "Tables_in_kagescan_tests": "scan_volume"
    }
] || [
    "db_migrations", "scan_chapter", "scan_serie", "scan_volume"
]
```

### Anything else?

I might have found why this occurs.

In [BaseConnection.php line 1350](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Database/BaseConnection.php#L1350), the framework takes only results of columns called `"table_name"` or `"TABLE_NAME"`; maybe for security reasons or to avoid an error. If no columns matches, the framework returns only the first result ("db_migrations" in my case).

But according to mysql documentation : 
> ```
> mysql> SHOW TABLES;
> +---------------------+
> | Tables_in_menagerie |
> +---------------------+
> | event               |
> | pet                 |
> +---------------------+
> ```
> The name of the column in the output produced by this statement is always **Tables_in_*db_name***, where **db_name** is the name of the database. See [Section 13.7.7.39, “SHOW TABLES Statement”](https://dev.mysql.com/doc/refman/8.0/en/show-tables.html), for more information. 

Adding that case to the allowlist should fix this issue.

PS : do anyone knows how to echo in console with phpunit ? I use a throw or a die(), which is not the best solution to test things.

**Comment by LoganTann** [comment]
I managed to create a quick & dirty workaround :

```php
// quickfix for https://github.com/codeigniter4/CodeIgniter4/issues/5307
public function tableExists($tableName) {
    if ($this->db->getPlatform() !== 'MySQLi') {
        return $this->db->tableExists($tableName); 
    }
    $dbName = "kagescan_tests";
    $rows = $this->db->query("SHOW TABLES FROM $dbName;")->getResultArray();
    foreach ($rows as $row) {
        if ($row["Tables_in_$dbName"] === $tableName) return true;
    }
    return false;
}

/** Checks if required tables have been created */
public function testTables()
{
    $this->assertFalse($this->tableExists('scan_tableThatDontExists'));
    $this->assertTrue($this->tableExists('scan_serie'));
    $this->assertTrue($this->tableExists('scan_chapter'));
    $this->assertTrue($this->tableExists('scan_volume'));
}
```

**Comment by kenjis** [comment]
Thank you for reporting.

> In BaseConnection.php line 1350, the framework takes only results of columns called "table_name" or "TABLE_NAME"; maybe for security reasons or to avoid an error. If no columns matches, the framework returns only the first result ("db_migrations" in my case).

No, the code finds the key **Tables_in_db_name**.
And tables are included in `$row`:
https://github.com/codeigniter4/CodeIgniter4/blob/d7523eb06a2d37b0f356d02b0562680130c83fe4/system/Database/BaseConnection.php#L1342

**Comment by kenjis** [comment]
@LoganTann 
Can't reproduce.

```php
<?php

namespace CodeIgniter\Database\Live;

use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\DatabaseTestTrait;

final class SampleTest extends CIUnitTestCase
{
    use DatabaseTestTrait;

    protected $refresh = false;

    public function testListTables()
    {
        $res = $this->db->query(<<<'EOT'
                SHOW TABLES FROM ci4_test;
            EOT);
        echo  json_encode($res->getResult(), JSON_PRETTY_PRINT)
            . ' || '
            . json_encode($this->db->listTables(), JSON_PRETTY_PRINT);
        exit;
    }
}
```

```sh-session
$ vendor/bin/phpunit tests/system/Database/Live/SampleTest.php 
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.12
Configuration: /Users/kenji/work/codeigniter/CodeIgniter4/phpunit.xml

[
    {
        "Tables_in_ci4_test": "db_ci_sessions"
    },
    {
        "Tables_in_ci4_test": "db_empty"
    },
    {
        "Tables_in_ci4_test": "db_ip_table"
    },
    {
        "Tables_in_ci4_test": "db_job"
    },
    {
        "Tables_in_ci4_test": "db_migrations"
    },
    {
        "Tables_in_ci4_test": "db_misc"
    },
    {
        "Tables_in_ci4_test": "db_secondary"
    },
    {
        "Tables_in_ci4_test": "db_stringifypkey"
    },
    {
        "Tables_in_ci4_test": "db_type_test"
    },
    {
        "Tables_in_ci4_test": "db_user"
    },
    {
        "Tables_in_ci4_test": "db_without_auto_increment"
    }
] || [
    "db_ci_sessions",
    "db_empty",
    "db_ip_table",
    "db_job",
    "db_migrations",
    "db_misc",
    "db_secondary",
    "db_stringifypkey",
    "db_type_test",
    "db_user",
    "db_without_auto_increment"
]
```

**Comment by kenjis** [comment]
@LoganTann 

What do you see if you add `dd($this->db->getDatabase());` in your test code?
```php
dd($this->db->getDatabase()); // Add

$res = $this->db->query(<<<'EOT'
    SHOW TABLES FROM kagescan_tests;
EOT);
throw new Exception( json_encode($res->getResult(), JSON_PRETTY_PRINT)
        ." || ". json_encode($this->db->listTables(), JSON_PRETTY_PRINT)
);
```

**Comment by LoganTann** [comment]
The bug was from the cache. I edited my code to be : 
```php
/**
 * quickfix for https://github.com/codeigniter4/CodeIgniter4/issues/5307
 */
public function tableExists($tableName) {
    $this->db->resetDataCache();
    $retval = $this->db->tableExists($tableName);
    echo "\n\n \"$tableName\": ", $retval?"in ":"not in ", json_encode($this->db->listTables());
    return $retval; 
}
```

Output without `$this->db->resetDataCache();` :  
```
 "scan_tableThatDontExists": not in ["db_migrations"]

 "scan_serie": not in ["db_migrations"]
```

output with  `$this->db->resetDataCache();` :
```
 "scan_tableThatDontExists": not in ["db_migrations","scan_chapter","scan_serie","scan_volume"]

 "scan_serie": not in ["db_migrations","scan_chapter","scan_serie","scan_volume"]
```

I wonder why tableExists still returns false even with "scan_serie" ... That's weird

**Comment by LoganTann** [comment]
After some echo debugging, I found out that `tableExists` adds a prefix to the table name
```
testing scan_tableThatDontExists:
  protectIdentifiers: db_scan_tableThatDontExists
  listTables: ["db_migrations","scan_chapter","scan_serie","scan_volume"]
  Result: false


testing scan_serie:
  protectIdentifiers: db_scan_serie
  listTables: ["db_migrations","scan_chapter","scan_serie","scan_volume"]
  Result: false
```

**Comment by LoganTann** [comment]
Oh, found out the error : https://github.com/Kagescan/kagescan-cms/blob/dev/App/Config/Database.php#L66

I had to replace `'DBPrefix' => 'db_',` to `'DBPrefix' => '',`

**Comment by kenjis** [comment]
@LoganTann If you don't use `DBPrefix` in `default`, you should not use it in `tests` either.

**Comment by LoganTann** [comment]
Fine, thanks for your help ! 

Recap when creating raw sql : 
- You should call `$this->db->resetDataCache()` to tell to the framework that you just created a table.
- You should also handle the database prefix from your config. The default table prefix for tests is `db_`, so if it's empty in the `default` config, this haves to be the same in the `tests` config.

**Comment by kenjis** [comment]
@LoganTann 
> Or should I rather change the way I create tables ?

If there is a possibility of using DBPrefix in the future, it would be better to create the table using CodeIgniter methods instead of hardcoding the raw table name in the SQL statement.

However, I prefer the simplicity of coding freely without using DBPrefix at all.
