### ISSUE TITLE
Docs: Correction of specification error description regarding [Testing Controllers]

### ISSUE THREAD

**Issue by lf-uraku-yuki** [codeigniter4/CodeIgniter4#5338]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.5

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MySQL 8.0

### What happened?

https://codeigniter.com/user_guide/testing/controllers.html

1. [execute] actually takes the second and subsequent arguments and is used to specify the arguments of the controller function.
2. [withURI] does not pass any arguments to the controller function. In fact, even in scenarios where the arguments are passed as a URI, you should use the optional arguments of the execute function, which are not documented.

https://codeigniter.com/user_guide/testing/response.html

The [isOK] function checks if the body is empty along with the status code. It's a good idea to mention this.

### Steps to Reproduce

It's a document issue.

### Expected Output

It may be correct in the long run to allow [withURI] to interpret the arguments specified on the URI.

### Anything else?

I have a problem with my own English ability, so I would like to ask someone else to correct it.

**Comment by kenjis** [comment]
@lf-uraku-yuki Thank you for reporting!

> [withURI] does not pass any arguments to the controller function. In fact, even in scenarios where the arguments are passed as a URI, you should use the optional arguments of the execute function, which are not documented.

What do you mean?
It seems there is no explanation like "pass arguments to the controller function".

> Allows you to provide a new URI that simulates the URL the client was visiting when this controller was run. This is helpful if you need to check URI segments within your controller. The only parameter is a string representing a valid URI:
https://codeigniter.com/user_guide/testing/controllers.html

**Comment by lf-uraku-yuki** [comment]
> What do you mean?
> It seems there is no explanation like "pass arguments to the controller function".

In the document

> This is helpful if you need to check URI segments within your controller.

I misunderstood that the description is for processing the argument specification part on the URI (such as the 350 part of http://example.com/customer/edit/350).

**Comment by kenjis** [comment]
Ah, if you do like this:

```php
$result = $this->withURI('http://example.com/customer/edit/350')
                       ->controller(\App\Controllers\CustomerController::class)
                       ->execute('edit');
```

It may not wonder you expect `350` is passed to the controller function.
But it is not. Because the controller testing executes a controller method directly with `execute()`.

**Comment by lf-uraku-yuki** [comment]
We thank you for your cooperation.

**Comment by kenjis** [comment]
@lf-uraku-yuki Can you review #5339 ?
