### ISSUE TITLE
Bug: Using `model()` in seed files runs but nothing is seeded.

### ISSUE THREAD

**Issue by Sammyskills** [codeigniter4/CodeIgniter4#5341]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.18

### What happened?

Trying to create a seed using the global function `model()` runs without errors, but nothing is seeded. 

From the [documentation](https://codeigniter.com/user_guide/dbmgmt/seeds.html#using-faker), you can see that the `model()` function can be used within the seed file, enabling us to run the seeding via the model, instead of hardcoding table names, etc. 
But when the cli command (or via controller) is run, it returns successful, but in reality, nothing is done.

For instance:
`
public function run()
    {
        $model = model('ModelName');
        $model->insert([
            'email'      => static::faker()->email,
            'ip_address' => static::faker()->ipv4,
        ]);
    }
`
In the code above, if you run `php spark db:seed SeederName`, it returns a successful message when nothing happened actually. If you try to purposely make a mistake in the name of the model or any of the methods, the cli command returns errors (which is expected).

### Steps to Reproduce

- Download the latest version of CI `composer create-project codeigniter4/appstarter project-folder`
- Create a database and update your `app/Config/Database.php` file
- Using the terminal, run `php spark make:scaffold Admin` or if you prefer to create them individually, you can run `php spark make:controller Admin`, `php spark make:model Admin`, `php spark make:seeder Admin --suffix`
- Add 'email' and 'ip_address' to the protected `$allowedFields` array in your model
- Add the code from the [docs](https://codeigniter.com/user_guide/dbmgmt/seeds.html#using-faker) to your seed file
- Run `php spark db:seed AdminSeeder` or `php spark db:seed Admin` (based on the name of your seed file) via your terminal

### Expected Output

I expected the actual seeding to occur.

**Comment by kenjis** [comment]
Follow your Steps to Reproduce, I got the following error.
Because there is no `admins` table yet.

But it seems the INSERT statement looks fine.

```sh-session
$ php spark db:seed Admin

CodeIgniter v4.1.5 Command Line Tool - Server Time: 2021-11-17 03:59:08 UTC-06:00


[mysqli_sql_exception]

Table 'ci4.admins' doesn't exist

at SYSTEMPATH/Database/MySQLi/Connection.php:292

Backtrace:
  1    SYSTEMPATH/Database/MySQLi/Connection.php:292
       mysqli()->query('INSERT INTO `admins` (`email`, `ip_address`) VALUES (\'crist.maiya@gmail.com\', \'102.93.191.240\')', 0)

  2    SYSTEMPATH/Database/BaseConnection.php:670
       CodeIgniter\Database\MySQLi\Connection()->execute('INSERT INTO `admins` (`email`, `ip_address`) VALUES (\'crist.maiya@gmail.com\', \'102.93.191.240\')')

  3    SYSTEMPATH/Database/BaseConnection.php:598
       CodeIgniter\Database\BaseConnection()->simpleQuery('INSERT INTO `admins` (`email`, `ip_address`) VALUES (\'crist.maiya@gmail.com\', \'102.93.191.240\')')

  4    SYSTEMPATH/Database/BaseBuilder.php:1760
       CodeIgniter\Database\BaseConnection()->query('INSERT INTO `admins` (`email`, `ip_address`) VALUES (:email:, :ip_address:)', [...], false)

  5    SYSTEMPATH/Model.php:239
       CodeIgniter\Database\BaseBuilder()->insert()

  6    SYSTEMPATH/BaseModel.php:738
       CodeIgniter\Model()->doInsert([...])

  7    SYSTEMPATH/Model.php:620
       CodeIgniter\BaseModel()->insert([...], true)

  8    APPPATH/Database/Seeds/Admin.php:15
       CodeIgniter\Model()->insert([...])

  9    SYSTEMPATH/Database/Seeder.php:143
       App\Database\Seeds\Admin()->run()

 10    SYSTEMPATH/Commands/Database/Seed.php:77
       CodeIgniter\Database\Seeder()->call('App\\Database\\Seeds\\Admin')

 11    SYSTEMPATH/CLI/Commands.php:63
       CodeIgniter\Commands\Database\Seed()->run([])

 12    SYSTEMPATH/CLI/CommandRunner.php:70
       CodeIgniter\CLI\Commands()->run('db:seed', [...])

 13    SYSTEMPATH/CLI/CommandRunner.php:56
       CodeIgniter\CLI\CommandRunner()->index([...])

 14    SYSTEMPATH/CodeIgniter.php:822
       CodeIgniter\CLI\CommandRunner()->_remap('index', 'db:seed', 'Admin')

 15    SYSTEMPATH/CodeIgniter.php:410
       CodeIgniter\CodeIgniter()->runController(Object(CodeIgniter\CLI\CommandRunner))

 16    SYSTEMPATH/CodeIgniter.php:318
       CodeIgniter\CodeIgniter()->handleRequest(null, Object(Config\Cache), false)

 17    SYSTEMPATH/CLI/Console.php:48
       CodeIgniter\CodeIgniter()->run()

 18    ROOTPATH/spark:63
       CodeIgniter\CLI\Console()->run()
```

**Comment by Sammyskills** [comment]
Well, that's weird, because I didn't get that error. 

Please, can you create the admin table with just the id, email and ip_address just to test ?

**Comment by kenjis** [comment]
No problem.

```php
<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class Admin extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'id' => [
                'type'           => 'INT',
                'unsigned'       => true,
                'auto_increment' => true,
            ],
            'email' => [
                'type'       => 'VARCHAR',
                'constraint' => '100',
            ],
            'ip_address' => [
                'type' => 'VARCHAR',
                'constraint' => '45',
            ],
        ]);
        $this->forge->addPrimaryKey('id');
        $this->forge->createTable('admins');
    }

    public function down()
    {
        $this->forge->dropTable('admins');
    }
}
```

```sh-session
$ php spark migrate

CodeIgniter v4.1.5 Command Line Tool - Server Time: 2021-11-17 04:47:38 UTC-06:00

Running all new migrations...
	Running: (App) 2021-11-17-095412_App\Database\Migrations\Admin
Done migrations.
```

```php
$ php spark db:seed Admin

CodeIgniter v4.1.5 Command Line Tool - Server Time: 2021-11-17 04:47:46 UTC-06:00

Seeded: App\Database\Seeds\Admin
```
![Screenshot 2021-11-17 19 49 57](https://user-images.githubusercontent.com/87955/142186968-836a3019-8137-4d93-a30d-26aa261077b3.png)

**Comment by Sammyskills** [comment]
Well, for reasons which I can't explain, it is not working for my main project folder.

At first, when I created a fresh installation in a new directory, it didn't work. But now, I just created another installation, and it worked. 

Please see my attached video showing that it doesn't work in my existing project. I don't know where to check or the settings to update as no errors are produced.

https://user-images.githubusercontent.com/8720569/142197593-1b64aec0-6c3a-461e-883f-f5ceb7ee5b0e.mp4

**Comment by kenjis** [comment]
It is wired you don't see any errors.
But I can't reproduce it. So I can't fix your own problem.

**Comment by kenjis** [comment]
@Sammyskills 
> PS: I am not using the fakerphp/faker library, hence the reason I am not generating any details with it for now. Could this be a reason why the model() doesn't seed the expected data into my db?

According to the User Guide, you need to install Faker with Composer. Did you?
https://codeigniter.com/user_guide/dbmgmt/seeds.html?highlight=faker#using-faker

**Comment by Sammyskills** [comment]
Well, it seems that the issue was from my installation, as it was upgraded from v4.1.4 to v4.1.5

So, I don't know what the issue must have been, but I've been able to forge ahead by getting a fresh installation and continuing with it. With that being said, I'll simply close this issue.

Thanks.
