### ISSUE TITLE
Bug: PHP Fatal error:  Uncaught ErrorException: Undefined property: Config\\Exceptions::$sensitiveDataInTrace

### ISSUE THREAD

**Issue by fedeburo** [codeigniter4/CodeIgniter4#5342]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Hi everyone. I am having problems to visualize correctly the errors in "development" mode in my local env. Every time there is an error, it always end in the same blank page with the following sentences:

PHP Fatal error:  Uncaught ErrorException: Undefined property: Config\\Exceptions::$sensitiveDataInTrace in ........

Looking at the code and at different versions that you had released, i notice that there is a change on system/Debug/Exceptions.php, spcecially in the commit: 1cbdeac15c34e7bb85a70906324cb2195edba452, on lines 244 - 250, where it is changed the way that is compared the way that is compared the variable $sensitiveDataInTrace

`if (! empty($this->config->sensitiveDataInTrace)) {
`
to

` if ($this->config->sensitiveDataInTrace !== []) {`

It seems that this comparison is causing errors, and CodeIgniter is not showing the correct error in the usual way that it was shown in older versions.

I tried to downgrade codeigniter to version 4.1.4, and in this version, errors are shown correctly.

I wait for your answer, thanks!

### Steps to Reproduce

Error on local, execute in page.

### Expected Output

It is excpected that CodeIgniter show the correct error in the way that CodeIgniter always shows the error

**Comment by kenjis** [comment]
Fixed by  #5314

See https://github.com/codeigniter4/CodeIgniter4/search?q=%24sensitiveDataInTrace&type=issues

**Comment by kenjis** [comment]
Workaround:
Add the property `$sensitiveDataInTrace` in `app/Config/Exceptions.php`.
https://github.com/codeigniter4/CodeIgniter4/blob/d4db7b22dc8fb9901d94ab89c14f84fc662fff0e/app/Config/Exceptions.php#L59
