### ISSUE TITLE
Bug: Undefined method 'setBody'.

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#5351]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MariaDB

### What happened?

![image](https://user-images.githubusercontent.com/2387514/142355100-b8890c0d-b0ce-4ea1-9cb6-be4bdf861564.png)

### Steps to Reproduce

using "intelephense"
and this my code

```php
return $this->response
            ->setStatusCode(200)
            ->setContentType($file->getMimeType())
            ->setBody(file_get_contents($img))
            ->send();
```

### Expected Output

The notice should not appear.

**Comment by kenjis** [comment]
What is *intelephense*?

No problem with PhpStorm.
![Screenshot 2021-11-18 14 27 39](https://user-images.githubusercontent.com/87955/142357254-fd1b167f-2123-43fc-8a84-4fb62e96b453.png)

**Comment by paulbalandan** [comment]
@kenjis intelephense and intellisense are VS Code PHP plugins.

This is another case of interface discrepancy. `$this->response` is wired to `ResponseInterface` and `setBody` is from `MessageInterface`, so intelephense truly says the method is not found. But, the instance in `$this->response` is a `Response` object which implements both `ResponseInterface` and `MessageInterface` so this should not be a problem.

**Comment by paulbalandan** [comment]
Related: #4356

**Comment by kenjis** [comment]
@paulbalandan Thank you!

I misunderstood that there is `setBody()` in `ResponseInterface`.

Not directly related, but `setBody()`is not defined in PSR-7.
https://github.com/php-fig/http-message/blob/master/docs/PSR7-Interfaces.md
