### ISSUE TITLE
Bug: `config()` can't load Config file in a module if there is a Config file with the same name

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#5356]
### PHP Version

8.0

### CodeIgniter4 Version

`develop` (0aa542b664a365c8898b6a1e98fa890e92a580e8)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

`config()` can't load Config file in a module if there is a Config file with the same name.

### Steps to Reproduce

Configure `'Acme\Blog` namespace:
```diff
--- a/app/Config/Autoload.php
+++ b/app/Config/Autoload.php
@@ -43,6 +43,7 @@ class Autoload extends AutoloadConfig
     public $psr4 = [
         APP_NAMESPACE => APPPATH, // For custom app namespace
         'Config'      => APPPATH . 'Config',
+        'Acme\Blog'   => ROOTPATH . 'acme/Blog',
     ];
 
     /**
```

Create `acme/Blog/Config/Blog.php`:
```php
<?php

namespace Acme\Blog\Config;

use CodeIgniter\Config\BaseConfig;

class Blog extends BaseConfig
{
    public $siteName  = 'My Great Site';
    public $siteEmail = 'webmaster@example.com';
}
```

Create `app/Config/Blog.php`:
```php
<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

class Blog extends BaseConfig
{
    public $siteName  = 'app/Config/Blog';
    public $siteEmail = 'webmaster@example.com';
}
```

Create `acme/Blog/Config/Routes.php`:
```php
<?php

$routes->group('blog', ['namespace' => 'Acme\Blog\Controllers'], function ($routes) {
    $routes->get('/', 'Blog::index');
});
```

Create `acme/Blog/Controllers/Blog.php`:
```php
<?php
namespace Acme\Blog\Controllers;

use App\Controllers\BaseController;

class Blog extends BaseController
{
    public function index()
    {
        $config = config(\Acme\Blog\Config\Blog::class);
        echo $config->siteName;
    }
}
```

Run `php spark serve`.

Navigate to http://localhost:8080/blog

You see `app/Config/Blog`.

### Expected Output

`My Great Site`

**Comment by MGatner** [comment]
This is intentional. `Factories` with the `preferApp` flag will always grab a class with the same shortname from **app/** if it exists. If an alternate version is needed you can pass `preferApp => false` to the call.

For Config files specifically I would consider two instances of the same shortname to be a conflict (assuming one does not extend the other) that a developer should resolve. 

Modules that need to override or add to known configurations in **app/** should use Registrars.

**Comment by kenjis** [comment]
@MGatner Thank you for your answer.

I did not expect `config(\Acme\Blog\Config\Blog::class)` may return `Config\Blog` object.
So I add it to the user guide: #5366
