### ISSUE TITLE
`Model::paginate()` Return it as it was

### ISSUE THREAD

**Issue by tumilovich-dev** [codeigniter4/CodeIgniter4#5363]
### PHP Version

8.0, 8.1

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

If you enter a non-existent page (? Page = num), then displays the records first

### Steps to Reproduce

```php
public function paginate(?int $perPage = null, string $group = 'default', ?int $page = null, int $segment = 0)
    {
        $pager = Services::pager(null, null, false);

        if ($segment) {
            $pager->setSegment($segment);
        }

        $page = $page >= 1 ? $page : $pager->getCurrentPage($group);
        // Store it in the Pager library, so it can be paginated in the views.
        $this->pager = $pager->store($group, $page, $perPage, $this->countAllResults(false), $segment);
        $perPage     = $this->pager->getPerPage($group);
        $offset      = ($pager->getCurrentPage($group) - 1) * $perPage;

        return $this->findAll($perPage, $offset);
    }
```

### Expected Output

```php
public function paginate(?int $perPage = null, string $group = 'default', ?int $page = null, int $segment = 0)
    {
        $pager = Services::pager(null, null, false);

        if ($segment) {
            $pager->setSegment($segment);
        }

        $page = $page >= 1 ? $page : $pager->getCurrentPage($group);
        // Store it in the Pager library, so it can be paginated in the views.
        $this->pager = $pager->store($group, $page, $perPage, $this->countAllResults(false), $segment);
        $perPage     = $this->pager->getPerPage($group);
        $offset      = ($page - 1) * $perPage;

        return $this->findAll($perPage, $offset);
    }
```

**Comment by kenjis** [comment]
Thank you for reporting.

But I don't get what you say, because your "Steps to Reproduce" is code and I can't do it.
And your "Expected Output" is also code. Do you really want to output the source code?

**Comment by kenjis** [comment]
This #5125 ?

It is a bug fix, and the current behavior is the specification.
What's wrong with you?

**Comment by John-Betong** [comment]
A default integer NULL parameter is not within an integer scope and is handled by PHP type juggling. 

Replacing NULL with an integer within the variable scope will alleviate many problems. 

Future PHP versions will make matters worse.

**Comment by kenjis** [comment]
> Replacing NULL with an integer within the variable scope will alleviate many problems.

It is done:
https://github.com/codeigniter4/CodeIgniter4/blob/10496ff022c351be0a0af620824f2d286c7e1c5d/system/BaseModel.php#L1082

**Comment by tumilovich-dev** [comment]
If the page number does not exist, records from the database are returned.
And yes! I am good.
