### ISSUE TITLE
Bug: Type Error when Validator gets unexpected structured array

### ISSUE THREAD

**Issue by shishamo** [codeigniter4/CodeIgniter4#5369]
PHP Version

7.4

CodeIgniter4 Version

4,1,5

CodeIgniter4 Installation Method

Composer (new project)

Which operating systems have you tested for this bug?

Linux

Which server did you use?

apache

Database

MariaDB 10.1.31

What happened?
When using array key validation as below example:
> 'arr.*.index' => 'required'

And receive data of array as below
> [1,2,3,4,5]

Send a php error because an array is required in dot_array_search and _dot_array_search functions using inside the validation 

Steps to Reproduce
```php
$data['arr'] = [1,2,3,4,5];
$validation->setRules([
    'arr.*.index' => 'required',
]);
```

Send a php error

Expected Output
Need to return false because invalid data?

Anything else?

**Comment by kenjis** [comment]
```php
<?php

namespace App\Controllers;

use Config\Services;

class Home extends BaseController
{
    public function index()
    {
        $validator = Services::validation();
        $validator->setRules([
           'arr.*.index' => 'required',
       ]);

        $data['arr'] = [1,2,3,4,5];

        $isValid = $validator->run($data);
        d($isValid);
    }
}
```

> TypeError
> _array_search_dot(): Argument #2 ($array) must be of type array, int given, called in .../CodeIgniter4/system/Helpers/array_helper.php on line 56

**Comment by sfadschm** [comment]
In principle, I would think it is up to the developer to make sure that the data structure passed to the validator is of the expected type (and/or dimensionality).

**Comment by kenjis** [comment]
@sfadschm
Validator checks the passed data (structure) is valid or not.
Do you want to  validate the structure before passing it to Validator?

**Comment by sfadschm** [comment]
I think I see your point, but I also think the core of the problem is rather that a misformed array is passed here.
The PR looks reasonable tough also for other cases to avoid dot-search to fail 👍

**Comment by kenjis** [comment]
>  I also think the core of the problem is rather that a misformed array is passed here.

What do you mean? Where is *here* ?

A web site visitor (or an attacker) can send a misformed array.

**Comment by sfadschm** [comment]
> > I also think the core of the problem is rather that a misformed array is passed here.
> 
> What do you mean? Where is _here_ ?
> 
> A web site visitor (or an attacker) can send a misformed array.

_Here_ was refering to validation after form input, but I missed the case of attacker input. I like the solution and misunderstood the problem, so all good from my side 😄
