### ISSUE TITLE
I need oracle database to connect with CodeIgniter 4

### ISSUE THREAD

**Issue by abranasays** [codeigniter4/CodeIgniter4#5390]
Sir, In Codeigniter 3 there is feature available for connect with oracle database.
Sir, But Codeigniter 4 there is no feature I found to connect with oracle database.

Sir, is there any way to connect with oracle database in Codeigniter 4? or there is no feature to connect?

**Comment by kenjis** [comment]
See #2487

**Comment by paulbalandan** [comment]
The open PR is enough to track the Oracle requirement. No need to keep this open.
