### ISSUE TITLE
Bug: `Debug\Toolbar\Collectors\Database` depends on `VENDORPATH`

### ISSUE THREAD

**Issue by John-Betong** [codeigniter4/CodeIgniter4#5401]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

mysql  Ver 8.0.27-0ubuntu0.21.04.1 for Linux on x86_64 ((Ubuntu))

### What happened?

Production:
Whoops!
We seem to have hit a snag. Please try again later...

Development:
Error
Undefined constant "CodeIgniter\Debug\Toolbar\Collectors\VENDORPATH" 

### Steps to Reproduce

Added :
 .env  ->  CI_ENVIRONMENT = development

### Expected Output

Expected old CI4 Project to render and not produce errors

### Anything else?

Amended the following and Bug cleared:

File: /var/www/anetizer.com/ci4/system/bootstrap.php : 126

// KLUDGE - Because I have used git clone instead of Composer
  // echo 'File: ' .__file__ .' : ' .__line__; die;
  if (! defined('VENDORPATH')) {
    define('VENDORPATH', realpath(ROOTPATH . 'vendor') . DIRECTORY_SEPARATOR);
  }

**Comment by kenjis** [comment]
I can't reproduce the error.

```
$ git clone --depth=1 https://github.com/codeigniter4/CodeIgniter4.git
$ cp env .env
$ vi .env
```

```diff
$ diff -u env .env
--- env	2021-11-27 12:38:05.000000000 +0900
+++ .env	2021-11-27 12:38:30.000000000 +0900
@@ -14,7 +14,7 @@
 # ENVIRONMENT
 #--------------------------------------------------------------------
 
-# CI_ENVIRONMENT = production
+CI_ENVIRONMENT = development
 
 #--------------------------------------------------------------------
 # APP
```
```
$ php spark serve
```
Navigate to http://localhost:8080/ and I see "Welcome to CodeIgniter 4.1.5".

**Comment by kenjis** [comment]
@John-Betong What if you run `composer update`?

**Comment by John-Betong** [comment]
I had problems with "composer update" so decided from the Linux Command Line to:

1. rm -Rf  /var/www/CodeIgniter4
2. run "composer create-project codeigniter4/appstarter /var/www/CodeIgniter4"
3. sudo chmod -Rf 0777 /var/www/CodeIgniter4/writable
4. browse to  http:/localhost/Codegniter4/public

And it worked without any problems so...

1. rm -Rf  /var/www/CodeIgniter4
2. cd /var/www
3.  git clone https://github.com/codeigniter4/CodeIgniter4.git
4. sudo chmod -Rf 0777 /var/www/CodeIgniter4/writable
5. browse to  http:/localhost/Codegniter4/public
. 
and it worked????

Don't you love computers :)

**Comment by kenjis** [comment]
@John-Betong It seems your installation was broken something.

**Comment by John-Betong** [comment]
The problem is solved locally but I just checked one of my online sites...

![Screenshot from 2021-11-28 08-34-34](https://user-images.githubusercontent.com/163515/143725599-7c591dd8-9e0d-47a1-bf79-166cd9d4ff86.png)

**Comment by kenjis** [comment]
The debug toolbar code obviously depends on `VENDORPATH`.
It seems it is a new bug when you don't use Composer.

**Comment by kenjis** [comment]
@John-Betong This is a bug.
Because CI4 should be able to be used without Composer (like Zip installation).

But if you use with Composer, just `composer update` fixes the error.

And if you use v4.1.5, the error does not occur. If you run just `git clone ...`,
you get the latest `develop` branch, which is after v4.1.5.

**Comment by kenjis** [comment]
@John-Betong This bug was fixed. Please try the latest `develop` branch.
Thank you for reporting.

**Comment by John-Betong** [comment]
Many thanks, now working without any problems on both localhost and a couple of online sites. .

The Github link: https://github.com/codeigniter4/CodeIgniter4/commit/775f50cc98b32044ec9f6ab1cde5502d87783430

Are you able to trace the exact version or do you require more information?

**Comment by kenjis** [comment]
@John-Betong 
> Are you able to trace the exact version

Yes.

> or do you require more information?

No.

And I fixed the bug, so I know the exact version that the bug was fixed.
