### ISSUE TITLE
Bug: Can't get Cookie via helper

### ISSUE THREAD

**Issue by pawelkg** [codeigniter4/CodeIgniter4#5417]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### What happened?

I have code like this:
```php
helper('cookie');
var_dump(has_cookie('test'));
var_dump(get_cookie('test'));
set_cookie('test', 'test', 10);
var_dump(has_cookie('test'));
var_dump(get_cookie('test'));
var_dump(get_cookie('test', true));
```

get_cookie method return null, and should return 'test'.
On second run, has_cookie return false but get_cookie return 'test'.

My results (on Spark serve and on apache server):
```
bool(false)
NULL
bool(true)
NULL
NULL
```

### Steps to Reproduce

Install fresh copy of CI, run code above. Tested on sparks and regular server.

### Expected Output

get_cookie return 'test'

### Anything else?

has_cookie return true when get_cookie return null... on second run has_cookie return false while get_cookie return cookie.

**Comment by kenjis** [comment]
This is not a bug.

`get_cookie()` gets cookie from **Request**.
`has_cookie()` and `set_cookie` do to **Response**.

>  get_cookie($index[, $xssClean = false])
> this function acts very similarly to **IncomingRequest**::getCookie(), except it will also prepend the $cookiePrefix that you might’ve set in your app/Config/App.php file.
https://codeigniter4.github.io/CodeIgniter4/helpers/cookie_helper.html#get_cookie

>  has_cookie(string $name[, ?string $value = null[, string $prefix = '']])
> This is an alias of **Response**::hasCookie().
https://codeigniter4.github.io/CodeIgniter4/helpers/cookie_helper.html#has_cookie

>  set_cookie($name[, $value = ''[, $expire = ''[, $domain = ''[, $path = '/'[, $prefix = ''[, $secure = false[, $httpOnly = false[, $sameSite = '']]]]]]]])
>  this function is an alias for **Response**::setCookie().
https://codeigniter4.github.io/CodeIgniter4/helpers/cookie_helper.html#set_cookie
