### ISSUE TITLE
Bug: `redirect()` does not send previously set cookies

### ISSUE THREAD

**Issue by pawelkg** [codeigniter4/CodeIgniter4#5422]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

Following code result with no cookie ('test') saved.
```php
    public function step1()
    {
        helper('cookie');
        set_cookie([
            'name' => 'test',
            'value' => 'test',
            'expire' => 0,
            'path' => '/'
                   ]);
        setcookie('test2', 'test2 ' . date("H:i:s"), 0, '/');

        return redirect()->to('/step2');
    }

    public function step2()
    {
        helper('cookie');
        echo "<pre>";
        var_dump(get_cookie('test'));
        var_dump(get_cookie('test2'));
        echo "</pre>";
    }
```

If page is not redirected, cookie is created normally. Cookie set by set cookie() is created normally all the time.

### Steps to Reproduce

Run code from example above.

### Expected Output

Cookie 'test' to be created.

**Comment by iRedds** [comment]
https://codeigniter.com/user_guide/general/common_functions.html#redirect

**Comment by kenjis** [comment]
@iRedds What do you mean?

**Comment by kenjis** [comment]
I've confirmed this bug.

**Comment by kenjis** [comment]
@pawelkg Thank you for reporting.
I sent a PR to fix this: #5424

**Comment by iRedds** [comment]
> @iRedds What do you mean?
doc
```php
// Copies all cookies from global response instance
return redirect()->back()->withCookies();
```

**Comment by kenjis** [comment]
Oh, this is not a bug.
