### ISSUE TITLE
Bug: Time class: undefined methods

### ISSUE THREAD

**Issue by danilort** [codeigniter4/CodeIgniter4#5430]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

CodeIngiter 4.1.5

In the online documentation there are these examples:
https://codeigniter.com/user_guide/libraries/time.html
```
$time = $time->setYear(2017);
$time = $time->setMonthNumber(4); // April
$time = $time->setMonthLongName('April');
$time = $time->setMonthShortName('Feb'); // February
$time = $time->setDay(25);
$time = $time->setHour(14); // 2:00 pm
$time = $time->setMinute(30);
$time = $time->setSecond(54);
```

But these methods are missing in the Time class:
```
Call to undefined method CodeIgniter\I18n\Time::setMonthShortName() 
Call to undefined method CodeIgniter\I18n\Time::setMonthLongName()
Call to undefined method CodeIgniter\I18n\Time::setMonthNumber()
```

In fact, I don't see them in the file: system\I18n\Time.php

### Steps to Reproduce

$time = $time->setYear(2017);
$time = $time->setMonthNumber(4); // April
$time = $time->setMonthLongName('April');
$time = $time->setMonthShortName('Feb'); // February
$time = $time->setDay(25);
$time = $time->setHour(14); // 2:00 pm
$time = $time->setMinute(30);
$time = $time->setSecond(54);

### Expected Output

No error

**Comment by kenjis** [comment]
Thank you for reporting. It seems these methods are not needed.

```php
<?php
namespace App\Controllers;
use CodeIgniter\I18n\Time;
class Home extends BaseController
{
    public function index()
    {
        $time = new Time('2021-01-01');

        echo $time->setYear(2017) . PHP_EOL;
        echo $time->setMonth(4) . PHP_EOL; // April
        echo $time->setMonth('April') . PHP_EOL;
        echo $time->setMonth('Feb') . PHP_EOL; // February
        echo $time->setDay(25) . PHP_EOL;
        echo $time->setHour(14) . PHP_EOL; // 2:00 pm
        echo $time->setMinute(30) . PHP_EOL;
        echo $time->setSecond(54) . PHP_EOL;
    }
}
```
```
2017-01-01 00:00:00
2021-04-01 00:00:00
2021-04-01 00:00:00
2021-02-01 00:00:00
2021-01-25 00:00:00
2021-01-01 14:00:00
2021-01-01 00:30:00
2021-01-01 00:00:54
```

**Comment by kenjis** [comment]
@danilort I sent a PR. See #5431.
