### ISSUE TITLE
Bug: ErrorException #1 Uncaught ErrorException: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/share/nginx/sites/vtrans/system/Validation/FormatRules.php:253

### ISSUE THREAD

**Issue by xankitpundir** [codeigniter4/CodeIgniter4#5438]
### PHP Version

8.1

### CodeIgniter4 Version

CodeIgniter: 4.1.5

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

MariaDB 10.2

### What happened?

{PHP internal code}   —  CodeIgniter\Debug\Exceptions->shutdownHandler ()
Uncaught ErrorException: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/share/nginx/sites/vtrans/system/Validation/FormatRules.php:253

246      */
247     public function valid_ip(?string $ip = null, ?string $which = null): bool
248     {
249         if (empty($ip)) {
250             return false;
251         }
252 
253         switch (strtolower($which)) {
254             case 'ipv4':
255                 $which = FILTER_FLAG_IPV4;
256                 break;
257 
258             case 'ipv6':
259                 $which = FILTER_FLAG_IPV6;
260                 break;

### Steps to Reproduce

Post request 
In controller Use this 

$this->session->setFlashdata('alert-msg', 'Email and Password required.');
return redirect()->to(base_url());

### Expected Output

It should redirect with flash message

**Comment by iRedds** [comment]
https://github.com/codeigniter4/CodeIgniter4/issues/5436
