### ISSUE TITLE
Bug: Model->insert() method returns 0 after successful database insertion if table's primary key does not auto increment.

### ISSUE THREAD

**Issue by dragonbiketoursvn** [codeigniter4/CodeIgniter4#5466]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MariaDB

### What happened?

I'm not sure whether this acutally is a bug or whether it was intentionally designed this way. However, if one uses `$model->insert() `to insert a record into a table with a non-auto-incrementing primary key, the return value will be 0 after a successful insertion. Obviously, in this scenario one will have had to include the primary key value within the record being inserted so one can test for successful insertion by adding a subsequent query to check for the existence of a record with said value as primary key, e.g. 

`if ($model->find(PRIMARY_KEY_VALUE_OF_INSERTED_RECORD !== null)`

If one is using the return value of ->insert() to perform error handling in case of a failed insertion, this can be cause for confusion.

### Steps to Reproduce

Create a table with a primary key that doesn't auto-increment. Create a model linked to this table. Insert a record using ->insert() and check the return value. Check the table itself to confirm whether insertion was successful. 

### Expected Output

I would expect `->insert()` to return a truthy value after any successful insertion, regardless of whether an auto-incrementing primary key is being used or not.

**Comment by kenjis** [comment]
Can't reproduce in the latest `develop`.

```sql
create table test (
  id int(11) not null,
  name varchar(255) not null,
  primary key (id)
);
```
```php
<?php
namespace App\Models;
use CodeIgniter\Model;
class TestModel extends Model
{
    protected $table = 'test';
    protected $useAutoIncrement = false;
    protected $allowedFields = ['id', 'name',];
}
```
```php
<?php
namespace App\Controllers;
use App\Models\TestModel;
class Home extends BaseController
{
    public function index()
    {
        $model = model(TestModel::class);
        $id = $model->insert(['id' => 2, 'name' => 'test']);
        var_dump($id); exit;
    }
}
```
```
$ php public/index.php 
int(2)
```

**Comment by dragonbiketoursvn** [comment]
My apologies. I hadn't set $useAutoIncrement to false.

**Comment by kenjis** [comment]
@dragonbiketoursvn No problem.
Nobody's perfect.
