### ISSUE TITLE
Bug: Can't unset mapped property in Entitiy

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#5495]
### PHP Version

8.0

### CodeIgniter4 Version

`develop` (60f1367c8ad16c4dea998a9d9a4bb1a7fd48c75c)

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli

### What happened?

> In this example, when the model sets the full_name field on the User class, it actually assigns that value to the class’ $name property, so it can be set and retrieved through $user->name. The value will still be accessible through the original $user->full_name, also, as this is needed for the model to get the data back out and save it to the database. However, **unset and isset only work on the mapped property, $name, not on the original name, full_name.**
https://codeigniter.com/user_guide/models/entities.html#data-mapping

But unsetting mapped property does not work.

```php
unset($user->name);
```

From https://forum.codeigniter.com/thread-80835.html

**Note**: the user guide says "unset and isset only work on the mapped property", but `isset()` works on the original name.

### Steps to Reproduce

```php
<?php
namespace App\Entities;
use CodeIgniter\Entity\Entity;
class User extends Entity
{
    protected $attributes = [
        'id' => null,
        'name' => null, // Represents a username
        'email' => null,
        'password' => null,
        'created_at' => null,
        'updated_at' => null,
    ];

    protected $datamap = [
        'name' => 'full_name',
    ];
}
```
```php
<?php
namespace App\Controllers;
use App\Entities\User;
class Home extends BaseController
{
    public function index()
    {
        $user = new User();
        echo $user->name . PHP_EOL;

        $user->name = 'John Smith';
        echo $user->name . PHP_EOL;

        unset($user->name);
        echo $user->name . PHP_EOL;
    }
}
```
```sh-session
$ php public/index.php 

John Smith
John Smith
```

### Expected Output

```sh-session
$ php public/index.php 

John Smith

```

**Comment by iRedds** [comment]
I have integrated Entities into CI3 based on Laravel.
And I didn't understand why the example doesn't work. But now everything became clear.

I and Laravel use datamap ``alias => original``
```php
$user->name = 'John Smith';  //$attributes['name'] = 'John Smith'
```

CI4 use ``original => alias``
```php
$user->name = 'John Smith';  //$attributes['full_name'] = 'John Smith'

//and it means
unset($user->name); //unset $attributes['name'] 
echo $user->name . PHP_EOL;  //get $attributes['full_name'] 
```

**Comment by kenjis** [comment]
@iRedds Does Laravel have Entities?
It seems no entry in the docs.

**Comment by kenjis** [comment]
@iRedds Your understanding is not correct. 
But there seems to be a flaw in the design in Entities.

**Comment by iRedds** [comment]
> @iRedds Does Laravel have Entities? It seems no entry in the docs. If you know, show the URL, please.

I mean I have implemented entities based on Eloquent. That is, the way it is now in CI4.
