### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by waqasmaqbool** [codeigniter4/CodeIgniter4#5498]
### PHP Version

7.3

### CodeIgniter4 Version

31

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

phpdbg

### Database

MySQL

### What happened?

in codeginter please paste this html code in form <div class="alert alert-success col-5">Waqas Maqbool</div>'
you will see success alert i want to show it as text

### Steps to Reproduce

in codeginter please paste this html code in form <div class="alert alert-success col-5">Waqas Maqbool</div>'
you will see success alert i want to show it as text

### Expected Output

success class

**Comment by cijagani** [comment]
Can you provide proper information? What type of issue you are facing?

**Comment by paulbalandan** [comment]
This seems to be spam. Closing.
