### ISSUE TITLE
Bug: Redirecting routes not working with typical route 

### ISSUE THREAD

**Issue by jahmedk** [codeigniter4/CodeIgniter4#5499]
### PHP Version

7.4

### CodeIgniter4 Version

4.0.5

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Redirecting routes not working with typical route 

![image](https://user-images.githubusercontent.com/22505794/147368248-82dd69b9-43dc-4a85-833f-9af3802f8de4.png)

### Steps to Reproduce

..

### Expected Output

should redirect on new typical route

**Comment by kenjis** [comment]
@jahmedk What do you mean by "typical route"?

Your route definition has a syntax error.
```php
$routes->addRedirect('product/(:any)', 'Product::$1');
```
You must set at least **ControllerName::MethodName** in the second argument.

And it seems `'product/(:segment)` catches all the routes to `product/*`,
so `'product/(:any)'` is not reached.

**Comment by iRedds** [comment]
[doc ](https://codeigniter.com/user_guide/incoming/routing.html#redirecting-routes)

```php
$routes->add('users/profile', 'Users::profile', ['as' => 'profile']);

// Redirect to a named route
$routes->addRedirect('users/about', 'profile');
// Redirect to a URI
$routes->addRedirect('users/about', 'users/profile');
```
The redirect target does not support value substitution.

**Comment by iRedds** [comment]
You can try a solution like this
```php
$routes->add('products/(:any)', function ($param) {
    throw new RedirectException('product/' . $param);
});
```

**Comment by jahmedk** [comment]
> You can try a solution like this
> 
> ```
> $routes->add('products/(:any)', function ($param) {
>     throw new RedirectException('product/' . $param);
> });
> ```

Yes this is working 
$routes->add('products/(:any)', function ($param) {
    throw new \CodeIgniter\Router\Exceptions\RedirectException('product/' . $param);
});

Thanks to all
