### ISSUE TITLE
Bug: `hasFile()` with no file return true

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#5503]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

`hasFile()` always returns `true` even if no file is selected

### Steps to Reproduce

Controller (Home.php)
```PHP
<?php

namespace App\Controllers;

use CodeIgniter\HTTP\Files\FileCollection;

class Home extends BaseController
{
    public function index()
    {
        helper('form');
        return view('form');
    }

    public function upload()
    {
        $coll = new FileCollection();
        var_dump($_FILES);
        var_dump($this->request->getFile('file'));
        var_dump($coll->hasFile('file'));
    }
}
```

This my view (form.php)
```PHP
<?= form_open_multipart('home/upload') ?>
<?= form_upload('file') ?>
<?= form_button(['type' => 'submit', 'content' => 'upload']) ?>
<?= form_close() ?>
```

Then click upload with no file selected.

The result is like: 
![image](https://user-images.githubusercontent.com/2387514/147387052-1c03b66c-cd94-4adb-8b7e-db6f96bc6531.png)

### Expected Output

`hasFile()` should return `false` if no files were submitted.

**Comment by kenjis** [comment]
I've confirmed this behavior.

But I'm not sure hasFile() should return false if no files were submitted.

**Comment by totoprayogo1916** [comment]
so, we have to check with similar `$_FILES['file']['name'] === ''`?
whereas we have the `hasFile()` function.

**Comment by kenjis** [comment]
@totoprayogo1916 What do you want to do?
Do you need to use `hasFile()`?

**Comment by kenjis** [comment]
There is already `isValid()` in UploadedFile.
https://codeigniter.com/user_guide/libraries/uploaded_files.html?highlight=isvalid#verify-a-file

**Comment by AkinOlawale** [comment]
Oh I didn't see that. Thanks for pointing that out. I'm new to the framework and would like to start contributing.. I guess I need to install the framework and see what's happening. But thanks for the clarification.

**Comment by kenjis** [comment]
@AkinOlawale If you would like to contribute, I recommend you read the current in-progress User Guide 
https://codeigniter4.github.io/CodeIgniter4/ and the CI4 source code.
