### ISSUE TITLE
Bug: double data in Response Headers

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#5514]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cgi-fcgi

### What happened?

double data in Response Header
see screenshot:
![image](https://user-images.githubusercontent.com/2387514/147725356-d16b03a9-7116-477a-96b7-72ba69d0c0be.png)

### Steps to Reproduce

enable CSP, or add `setHeader()` also make double data

this my controller
```PHP
<?php

namespace App\Controllers;

class Files extends BaseController
{
    public function index($fn)
    {
        $path = WRITEPATH . 'uploads' . DIRECTORY_SEPARATOR . $fn;
        $file   = new \CodeIgniter\Files\File($path);

        // if (!$file->isWritable()) {
        if (! is_file($path)) {
            throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound('File not found!');
        }

        return $this->response
            ->setStatusCode(200)
            ->setContentType($file->getMimeType())
            ->setBody(file_get_contents($path))
            ->send();
    }
}
```

### Expected Output

no double data in Response header

**Comment by kenjis** [comment]
I have confirmed this bug.

Even if CSP is disabled, `Cache-control` and `Content-Type` are duplicated.

```
HTTP/1.1 200 OK
Host: localhost:8080
Date: Thu, 30 Dec 2021 08:45:47 GMT
Connection: close
X-Powered-By: PHP/8.0.14
Cache-control: no-store, max-age=0, no-cache
Content-Type: image/png; charset=UTF-8
Cache-control: no-store, max-age=0, no-cache
Content-Type: image/png; charset=UTF-8
Debugbar-Time: 1640853947
Debugbar-Link: http://localhost:8080/index.php?debugbar_time=1640853947
```

**Comment by kenjis** [comment]
@totoprayogo1916 This is not a bug of CI4.
The controller code is incorrect. Controllers should return Response objects.

```php
        return $this->response
            ->setStatusCode(200)
            ->setContentType($file->getMimeType())
            ->setBody(file_get_contents($path));
```

**Comment by iRedds** [comment]
Don't use the send() method.

**Comment by totoprayogo1916** [comment]
thanks @kenjis @iRedds
