### ISSUE TITLE
[mysqli_sql_exception]  Cannot add foreign key constraint  at SYSTEMPATH\Database\MySQLi\Connection.php:292 

### ISSUE THREAD

**Issue by daniel911025** [codeigniter4/CodeIgniter4#5517]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

5.7.24

### What happened?

Make a migration, introducing a foreign key get this on shell

[mysqli_sql_exception]
Cannot add foreign key constraint
at SYSTEMPATH\Database\MySQLi\Connection.php:292

### Steps to Reproduce

```php
   $this->forge->addKey('user_info_id', true);       
        $this->forge->addForeignKey('user_info_id', 'users', 'id', 'CASCADE', 'CASCADE'); //<--------THIS RUN
        $this->forge->addForeignKey('user_info_id', 'users', 'id', 'SET NULL', 'CASCADE'); //<--------NOT RUN
        $this->forge->createTable('users_info');
        $this->db->enableForeignKeyChecks();
    }
```

### Expected Output

Get a correct migration.

**Comment by kenjis** [comment]
`user_info_id` is a primary key that can't be null.

**Comment by daniel911025** [comment]
Thanks for time, :)
