### ISSUE TITLE
Bug:  Config\App cookie settings deprecated but Config\Cookie not implemented in CSRF

### ISSUE THREAD

**Issue by xbotkaj** [codeigniter4/CodeIgniter4#5552]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.6 - develop

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

In Config\App for cookie settings is written that those settings are deprecated in favor of Config\Cookie but Config\Cookie is not reflected. For example, the CSRF constructor accepts only App Config instead of Config\Cookie

### Steps to Reproduce

- Clean installation
- Removing cookie config from Config\App in favor of Config\Cookie
- Enabling CSRF
- Make request

### Expected Output

CSRF should take Cookie configuration from Config\Cookie instead of Config\App

**Comment by paulbalandan** [comment]
I believe this is already taken care of:
https://github.com/codeigniter4/CodeIgniter4/blob/357021472f3227198c809e2439bea97486b0d830/system/Security/Security.php#L212-L226

**Comment by kenjis** [comment]
@xbotkaj You can't remove the deprecated Config\App cookie settings.

If you remove it, you get the error like this:
```
$ php spark serve
PHP Warning:  Undefined property: Config\App::$cookiePath in /Users/kenji/work/codeigniter/CodeIgniter4/system/HTTP/Response.php on line 163
PHP Stack trace:
PHP   1. {main}() /Users/kenji/work/codeigniter/CodeIgniter4/spark:0
PHP   2. require() /Users/kenji/work/codeigniter/CodeIgniter4/spark:45
PHP   3. CodeIgniter\CodeIgniter->initialize() /Users/kenji/work/codeigniter/CodeIgniter4/system/bootstrap.php:146
PHP   4. CodeIgniter\Config\BaseService::exceptions() /Users/kenji/work/codeigniter/CodeIgniter4/system/CodeIgniter.php:173
PHP   5. CodeIgniter\Config\BaseService::__callStatic($name = 'exceptions', $arguments = []) /Users/kenji/work/codeigniter/CodeIgniter4/system/CodeIgniter.php:173
PHP   6. CodeIgniter\Config\Services::exceptions($config = *uninitialized*, $request = *uninitialized*, $response = *uninitialized*, $getShared = *uninitialized*) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/BaseService.php:248
PHP   7. CodeIgniter\Config\BaseService::getSharedInstance($key = 'exceptions', ...$params = variadic(NULL, NULL, NULL)) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/Services.php:234
PHP   8. CodeIgniter\Config\BaseService::exceptions(NULL, NULL, NULL, FALSE) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/BaseService.php:189
PHP   9. CodeIgniter\Config\BaseService::__callStatic($name = 'exceptions', $arguments = [0 => NULL, 1 => NULL, 2 => NULL, 3 => FALSE]) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/BaseService.php:189
PHP  10. CodeIgniter\Config\Services::exceptions($config = NULL, $request = NULL, $response = NULL, $getShared = FALSE) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/BaseService.php:248
PHP  11. CodeIgniter\Config\BaseService::response() /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/Services.php:239
PHP  12. CodeIgniter\Config\BaseService::__callStatic($name = 'response', $arguments = []) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/Services.php:239
PHP  13. CodeIgniter\Config\Services::response($config = *uninitialized*, $getShared = *uninitialized*) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/BaseService.php:248
PHP  14. CodeIgniter\Config\BaseService::getSharedInstance($key = 'response', ...$params = variadic(NULL)) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/Services.php:479
PHP  15. CodeIgniter\Config\BaseService::response(NULL, FALSE) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/BaseService.php:189
PHP  16. CodeIgniter\Config\BaseService::__callStatic($name = 'response', $arguments = [0 => NULL, 1 => FALSE]) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/BaseService.php:189
PHP  17. CodeIgniter\Config\Services::response($config = NULL, $getShared = FALSE) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/BaseService.php:248
PHP  18. CodeIgniter\HTTP\Response->__construct($config = class Config\App { public $baseURL = 'http://localhost:8080/'; public $indexPage = 'index.php'; public $uriProtocol = 'REQUEST_URI'; public $defaultLocale = 'en'; public $negotiateLocale = FALSE; public $supportedLocales = [0 => 'en']; public $appTimezone = 'America/Chicago'; public $charset = 'UTF-8'; public $forceGlobalSecureRequests = FALSE; public $sessionDriver = 'CodeIgniter\\Session\\Handlers\\DatabaseHandler'; public $sessionCookieName = 'ci_session'; public $sessionExpiration = '36000'; public $sessionSavePath = 'ci_sessions'; public $sessionMatchIP = FALSE; public $sessionTimeToUpdate = 300; public $sessionRegenerateDestroy = FALSE; public $cookiePrefix = ''; public $cookieDomain = ''; public $cookieSecure = FALSE; public $cookieHTTPOnly = TRUE; public $cookieSameSite = 'Lax'; public $proxyIPs = ''; public $CSRFTokenName = 'csrf_test_name'; public $CSRFHeaderName = 'X-CSRF-TOKEN'; public $CSRFCookieName = 'csrf_cookie_name'; public $CSRFExpire = 7200; public $CSRFRegenerate = TRUE; public $CSRFRedirect = TRUE; public $CSRFSameSite = 'Lax'; public $CSPEnabled = FALSE }) /Users/kenji/work/codeigniter/CodeIgniter4/system/Config/Services.php:484
```

**Comment by xbotkaj** [comment]
@kenjis exactly that is the issue. If it is depreciated, it means it should not be considered as necessary to run the application and it should not be the first choice to take settings from, instead, the primary source should be Config\Cookie, if it is not found there, then go to Config\App for back compatibility.

**Comment by kenjis** [comment]
@xbotkaj Maybe you are correct. But if you remove the properties, you get the error.

I think *deprecated* means not recommended and it will be deleted in the future.
But not deleted now.

> It is kinda weird when you need to make setup the two places for the same thing to work properly.

You don't have to make setup the two places. Only `Config\Cookie` is enough.
If you setup `Config\Cookie`, the values take effect. The values in `Config\App` is ignored.
If not, it is a bug. Report it, please.

Why do you want to delete the properties in `Config\App`?

**Comment by xbotkaj** [comment]
@kenjis I was just playing around with config and realized some settings were not taken from Config\Cookie but instead from Config\App so I tried to delete it to see what will happen and where it will break. It was CSRF for me where it threw an error.

I can check later what exactly is taken from App and what from Cookie. :) For now, I have the same setup on both places.

**Comment by kenjis** [comment]
@xbotkaj This is not related, but if you use session, I recommend you use Session based CSRF Protection.
Then CSRF cookie is not needed.
https://www.codeigniter.com/user_guide/libraries/security.html#csrf-protection-methods

**Comment by xbotkaj** [comment]
Thank You @kenjis for me it works now, I wanted just to let you know that this issue occurred, and to be aware of it. :) Like I mentioned before I let there the old config and it works for now.

**Comment by kenjis** [comment]
@xbotkaj Okay, I close this for now.
I was not able to confirm the issue that some settings were not taken from Config\Cookie.
If you will find the exact way to reproduce, feel free to reopen.
