### ISSUE TITLE
Bug: Migration regress on a particular module

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#5568]
### PHP Version

7.3, 7.4, 8.0, 8.1

### CodeIgniter4 Version

4.1.4, 4.1.5, 4.1.6, 4.1.7

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

Mysql

### What happened?

The migration regress function is not working fine. I want to ``regress()`` on a particular module migration files but not working.
I called the module db migration batch which is ``2`` it reject the module migration files then regress on modules batch <> 2.
Please explain more on this on how to regress on the particular module without regressing other modules or fix this if is bug.

Thanks

### Steps to Reproduce

```php
$module_namespace = 'ShopCart';
$migrate->setNamespace($module_namespace)->regress(2);

```

### Expected Output

I am expecting it to delete the ``ShopCart`` migration table

**Comment by kenjis** [comment]
>  I want to regress() on a particular module migration files

In my understand, the CI4's migration does not work like that.
`regress()` takes the target batch number, and it has nothing to do with namespaces.
https://codeigniter4.github.io/CodeIgniter4/dbmgmt/migration.html#regress

**Comment by ChibuezeAgwuDennis** [comment]
okay but this feature will be fine and I know they will be other developers who will need this

**Comment by ChibuezeAgwuDennis** [comment]
> @ChibuezeAgwuDennis I don't get what you want exactly. You can regress to the batch number in any namespace now.

@kenjis On which version of codeigniter 4

**Comment by kenjis** [comment]
@ChibuezeAgwuDennis What do you mean *not working*? I can't see your screen, so I don't get what really happened.
What did you do? What did you get? The exact error message?
And can you show us the output `php spark migrate:status`?

**Comment by ChibuezeAgwuDennis** [comment]
I have extended the MigrationRunner class to do what I want to do with a particular module migration. I think is working fine now to what I want.
@kenjis thanks a lot okay
