### ISSUE TITLE
Bug: Migration status not working with different namespaces

### ISSUE THREAD

**Issue by demirkaric** [codeigniter4/CodeIgniter4#5577]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySQL 8.0.27-0ubuntu0.20.04.1

### What happened?

On the command php spark migrate:status 
The migrated details for columns "Group", "Migrated On", "Batch" are missing on all namespaces besides App namespace.
Please refer to the image below:
![image_2022_01_15T10_38_24_142Z (1)](https://user-images.githubusercontent.com/19651216/150298045-a1adf231-26b5-45c1-946c-058d5233fb1b.png)

### Steps to Reproduce

Do migration on multiple namespaces and check php spark migrate:status
You will see that data for columns "Group", "Migrated On", "Batch" missing for all namespaces besides App namespace,

### Expected Output

php spark migrate:status 
"Group", "Migrated On", "Batch" data on all namespaces.

**Comment by kenjis** [comment]
@demirkaric The screenshot was deleted.
You can upload it to GitHub by dragging it into the text area.

**Comment by kenjis** [comment]
I've confirmed this bug.

```
$ php spark migrate:status

CodeIgniter v4.1.7 Command Line Tool - Server Time: 2022-01-20 02:49:14 UTC-06:00

+-----------+-------------------+-----------------------+---------+---------------------+-------+
| Namespace | Version           | Filename              | Group   | Migrated On         | Batch |
+-----------+-------------------+-----------------------+---------+---------------------+-------+
| App       | 2022-01-20-084314 | CreateCiSessionsTable | default | 2022-01-20 02:47:08 | 1     |
| Myth\Auth | 2017-11-20-223112 | create_auth_tables    | ---     | ---                 | ---   |
+-----------+-------------------+-----------------------+---------+---------------------+-------+
```

```
SELECT * FROM `migrations`

id	version	class	group	namespace	time	batch	
1	2022-01-20-084314	App\Database\Migrations\CreateCiSessionsTable	default	App	1642668428	1	
2	2017-11-20-223112	Myth\Auth\Database\Migrations\CreateAuthTables	default	Myth\Auth	1642668543	2	
```

**Comment by kenjis** [comment]
@demirkaric Try this:
```diff
--- a/system/Commands/Database/MigrateStatus.php
+++ b/system/Commands/Database/MigrateStatus.php
@@ -108,6 +108,7 @@ class MigrateStatus extends BaseCommand
                 continue;
             }
 
+            $runner->setNamespace(null);
             $history = $runner->getHistory((string) $group);
             ksort($migrations);
 
```

**Comment by kenjis** [comment]
@demirkaric Try #5605 if you can.
