### ISSUE TITLE
Auto route in modules

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#5580]
Please I think it will be good for codeigniter to also auto route in modules without defining the routes or if there is anything like that already please include the document

**Comment by ChibuezeAgwuDennis** [comment]
> Please I think it will be good for codeigniter to also auto route in modules without defining the routes or if there is anything like that already please include the document

@kenjis  please can you reflect this

**Comment by kenjis** [comment]
Please submit feature requests to our [forum](https://forum.codeigniter.com/forum-29.html).
We use github issues to track bugs and planned work.
