### ISSUE TITLE
Bug: website ssl expire

### ISSUE THREAD

**Issue by lmanliang** [codeigniter4/CodeIgniter4#5582]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.17

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

maria

### What happened?

https://codeigniter.com/  SSL Cert is expire.

### Steps to Reproduce

https://codeigniter.com/  SSL Cert is expire.

### Expected Output

https://codeigniter.com/  SSL Cert is expire.

### Anything else?

https://codeigniter.com/  SSL Cert is expire.

**Comment by kenjis** [comment]
@lmanliang What do you mean?

> Valid from August 11, 2021 to August 11, 2022
https://www.sslshopper.com/ssl-checker.html#hostname=codeigniter.com

**Comment by lmanliang** [comment]
1/14 is display ssl expire.
now is 
![image](https://user-images.githubusercontent.com/6987926/149644211-647d3133-0923-440c-9979-12eea72e0d4b.png)

**Comment by kenjis** [comment]
It seems your network problem.
I can see https://codeigniter.com/ without any problem.

**Comment by lonnieezell** [comment]
It also appears correct for me.
