### ISSUE TITLE
Documentation: Query Builder update() method param order

### ISSUE THREAD

**Issue by andre-torelli** [codeigniter4/CodeIgniter4#5583]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.16

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

The documentation seems to be wrong. In the "query builder class" session, in the update method the order of the parameters is not correct. There it shows `$builder->update($data, ['id' => $id]);` when it should actually be `$builder->update(['id' => $id], $data);`

### Steps to Reproduce

```php
$builder->update($data, ['id' => $id]);
```

### Expected Output

```php
$builder->update(['id' => $id], $data);
```

**Comment by kenjis** [comment]
The first parameter is *set*, the second is *where*:
https://github.com/codeigniter4/CodeIgniter4/blob/98fed8351603371064773f56a19af446a0db13cc/system/Database/BaseBuilder.php#L1898
