### ISSUE TITLE
Bug: Message of throw error 404 pagenotfound not working when override 404 on production mode

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#5585]
### PHP Version

7.4

### CodeIgniter4 Version

latest

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

Trying to send custom Message of throw error 404 on pagenotfound exception

https://github.com/codeigniter4/CodeIgniter4/blob/057917caecbf53304e3bb696bd83dd4536ee745e/system/CodeIgniter.php#L843

not working when override 404 on production mode not sending error message to controller. 

### Steps to Reproduce

on production mode in routes

```php
$routes->set404Override('App\Controllers\Homepage\Error::show404');
```

in Homepage Controller

```php
throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound('homepage does not exist !');
```

### Expected Output

in the Error Controller show404 method

it should send the message "homepage does not exist" into the controller params or something

**Comment by kenjis** [comment]
Can't reproduce in the latest `develop` branch.

```diff
--- a/app/Config/Routes.php
+++ b/app/Config/Routes.php
@@ -20,7 +20,7 @@ $routes->setDefaultNamespace('App\Controllers');
 $routes->setDefaultController('Home');
 $routes->setDefaultMethod('index');
 $routes->setTranslateURIDashes(false);
-$routes->set404Override();
+$routes->set404Override('App\Controllers\Homepage\Error::show404');
 $routes->setAutoRoute(true);
 
 /*
```

```php
<?php

namespace App\Controllers\Homepage;

use App\Controllers\BaseController;

class Error extends BaseController
{
    public function show404()
    {
        throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound(
            'homepage does not exist !'
        );
    }
}
```

`.env`
```
CI_ENVIRONMENT = production
```

![Screenshot 2022-01-20 9 32 19](https://user-images.githubusercontent.com/87955/150240596-238e3304-258b-418d-8f26-02c235049209.png)

**Comment by crustamet** [comment]
this works or not, i don't understand, for me it is only showing message on the CI_ENVIRONMENT = development

**Comment by kenjis** [comment]
@crustamet What do you see on production mode?

**Comment by crustamet** [comment]
Message on production mode is "Page not found"
while message on production mode is the message that i've set 'homepage does not exist !'

**Comment by crustamet** [comment]
I have tried not overwriting the 404 and still the message is not the one i am sending

The message is different in development mode and production mode

**Comment by crustamet** [comment]
And of course is not sending the message because on line 

https://github.com/codeigniter4/CodeIgniter4/blob/057917caecbf53304e3bb696bd83dd4536ee745e/system/CodeIgniter.php#L843

is not treating the message if 404 is overwritten in the routes.

I only see the Controller is set and the Method, but the message is not sent trough here, that means you need to catch the message from errorHandling

**Comment by crustamet** [comment]
Maybe i am doing something wrong or something, i can post all my example code how i have it maybe then can you reproduce ?

**Comment by crustamet** [comment]
By the way i just changed the route using a closure now everything works while using view_cell with the controller inside the closure.

I think the override function is only used and intended for single language purpose applications.
