### ISSUE TITLE
Bug: Validation rule 'matches' returns false

### ISSUE THREAD

**Issue by yeasherarafath** [codeigniter4/CodeIgniter4#5597]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

10.4.14-MariaDB

### What happened?

// re is form input name

```php
$posts_tmp = $this->request->getPost();

$validation->check($posts_tmp['re'],'matches[re]');
```

when I am trying to validate input field and it's value by using matches rule, it's returning false. But it should return true, because both are same.

### Steps to Reproduce

Matching two values test => 100 and test1 => 100.

Now it should return true because test and test1 matches with each others.

In html
```html
<form method="post" action="<?php echo base_url(); ?>" accept-charset="utf-8">
	<input type="text" name="test" value="100" placeholder="">
	<input type="text" name="test1" value="100" placeholder="">
	<button type="submit">submit</button>
</form>
```

In php
```php
<?php

if($this->request->getMethod()=='post'){

$Validation = \Config\Services::validation();

echo "post ";
print_r("check '".$Validation->check($this->request->getPost()['test1'],'matches[test]')."'");
}
?>
```

### Expected Output

`true.`

### Anything else?

The rules 'differs' is also returning false every time.

**Comment by kenjis** [comment]
`check()` can get only the passed value, it does not know other field data.
You can't use it with the rules that needs other field data like  `$validation->check($value, 'matches[field]')`.

Why do you use `check()`?
I recommend you use `run()` instead.

**Comment by kenjis** [comment]
@yeasherarafath I strongly recommend you upgrade to v4.1.7.
See Security Advisory https://github.com/codeigniter4/CodeIgniter4/security/advisories/GHSA-w6jr-wj64-mc9x
