### ISSUE TITLE
Bug: fopen(/data/web/barotem/writable/session/ci_sessionbgu3r2frnef18ooamq5grjtitslhqank): Failed to open stream: No space left on device

### ISSUE THREAD

**Issue by Yangseok** [codeigniter4/CodeIgniter4#5598]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

10.3.32-MariaDB-0ubuntu0.20.04.1-log

### What happened?

ErrorException

fopen(/data/web/barotem/writable/session/ci_sessionbgu3r2frnef18ooamq5grjtitslhqank): Failed to open stream: No space left on device

### Steps to Reproduce

Refresh.

### Expected Output

site open

**Comment by Yangseok** [comment]
![Uploading 스크린샷 2022-01-20 오후 2.22.18.png…]()

**Comment by Yangseok** [comment]
![스크린샷 2022-01-20 오후 2 22 18](https://user-images.githubusercontent.com/6768687/150279543-c7f8703d-f786-49f8-b48a-45d69d26daf6.png)

**Comment by iRedds** [comment]
Try clearing the sessions directory

**Comment by kenjis** [comment]
No space left on device. Delete unneeded files on your server.

Please ask your support questions in the forums. Thanks! 
https://forum.codeigniter.com/forum-30.html

**Comment by Yangseok** [comment]
Thank you.
