### ISSUE TITLE
Doc: Same migration class name

### ISSUE THREAD

**Issue by iRedds** [codeigniter4/CodeIgniter4#5611]
### PHP Version

7.3

### CodeIgniter4 Version

latest

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### What happened?

It is not possible to apply a migration if a migration with the same class name was already called at the time the migrations were applied.

Example. You create migrations sequentially.
create_users_table, ``change_users_table``, create_posts_table, ``change_users_table``.
Now you want to apply them to the new database.
And you get an error.

### Steps to Reproduce

> php spark make:migration test
> php spark make:migration test
> php spark migrate

Cannot declare class App\Database\Migrations\Test, because the name is already in use

### Expected Output

It is not possible to fix this in the current way.
It is only possible to clarify in the documentation that the name of the migration must be unique.

### Anything else?

It seems to me a practical solution would be to use anonymous classes.

```php
<?php
use CodeIgniter\Database\Migration;

return new class extends Migration { /*...*/}
```
This solution is not affected by the class name error and also removes the redundant code for parsing the migration file.

I understand that this is currently impossible to implement, so I propose to add a task to the v5 roadmap.

**Comment by kenjis** [comment]
> I understand that this is currently impossible to implement, so I propose to add a task to the v5 roadmap.

Why impossible?

**Comment by iRedds** [comment]
@kenjis Because now it will be BC.
Of course, if you can force all developers to change the format of their migration files, then that makes a difference.

**Comment by kenjis** [comment]
Is it impossible to support both migration files?

**Comment by iRedds** [comment]
It is possible, but the problem of class name collisions will not go away.

**Comment by iRedds** [comment]
I could do a PR, but you made me so scared of BC and v5 that sometimes I don’t want to offer something.

**Comment by lonnieezell** [comment]
The easy solution is to name your classes more specific. Besides making this a non-issue, it makes it simpler for you to find which file you need to look at later. 

`change_users_table_add_beta_flag`, `change_users_table_track_views`, or whatever.

**Comment by kenjis** [comment]
@lonnieezell Excellent solution!

**Comment by iRedds** [comment]
@lonnieezell password reset joke.
At the expense of uniqueness, i wrote at the beginning.

**Comment by iRedds** [comment]
``return new class`` is independent of namespace and class name.
There is no need to pre-read the class and parse the namespace and class name, as is done now.

**Comment by kenjis** [comment]
I sent a PR #5631 to fix the docs.
