### ISSUE TITLE
Bug: Exception thrown on set database - adapter SQLSRV

### ISSUE THREAD

**Issue by demirkaric** [codeigniter4/CodeIgniter4#5616]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MSSQL Server

### What happened?

In the file vendor/codeigniter4/framework/system/Database/SQLSRV/Connection.php on the line 433

```php
 if ($this->execute('USE ' . $this->_escapeString($databaseName))) {
            $this->database  = $databaseName;
            $this->dataCache = [];

            return true;
        }
```

The code above will throw exception since USE statement must have the name of database within []

### Steps to Reproduce

Simply try to connect on SQLSERV database and it will throw exception: 
ERROR - 2022-01-25 11:35:06 --> [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'DatabaseName'.

### Expected Output

As peer mssql documentation: https://docs.microsoft.com/en-us/sql/t-sql/language-elements/use-transact-sql?view=sql-server-ver15

Simply surrounding database name with [] will fix this bug, 

Solution:

```php
 if ($this->execute('USE [' . $this->_escapeString($databaseName) . ']')) {
            $this->database  = $databaseName;
            $this->dataCache = [];

            return true;
        }
```
Applied in vendor/codeigniter4/framework/system/Database/SQLSRV/Connection.php on the line 433

**Comment by kenjis** [comment]
@demirkaric Thank you for reporting.

> Simply try to connect on SQLSERV database and it will throw exception:

Why do our SQLSRV unit tests pass?
https://github.com/codeigniter4/CodeIgniter4/runs/4947696316?check_suite_focus=true

**Comment by demirkaric** [comment]
It's on the setDatabase() method, I used that method, the example of the database name 
Used it like this:
```php
$this->db->setDatabase("7_11_trade_20180226_110654_K3TecMainDB_5EE7AF4A_default")
```

**Comment by kenjis** [comment]
Can't reproduce.

```php
<?php
namespace App\Controllers;
class Home extends BaseController
{
    public function index()
    {
        $db = db_connect();
        $query = $db->query('SELECT @@Version AS SQL_VERSION');
        var_dump($query->getRow()->SQL_VERSION);
    }
}
```
I see 
> string(198) "Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64) Jan 12 2022 22:30:08 Copyright (C) 2019 Microsoft Corporation Developer Edition (64-bit) on Linux (Ubuntu 20.04.3 LTS) "

**Comment by kenjis** [comment]
@demirkaric I cannot reproduce on the latest `develop` branch.
If you have this problem with the latest `develop` branch, create an issue with precise steps to reproduce the error.
