### ISSUE TITLE
Bug: DownloadResponse Fails with Large Files

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#5620]
### PHP Version

7.4, 8.0

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS, Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

`DownloadResponse` is set up to stream file data in chunks to circumvent memory issues, but something is still causing memory overflows:
```
CRITICAL - 2022-01-25 16:53:30 --> Allowed memory size of 134217728 bytes exhausted (tried to allocate 67112960 bytes)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
```

### Steps to Reproduce

I have created a repo to demonstrate the error: https://github.com/MGatner/codeigniter-error

### Expected Output

We need to be able to support large file downloads.

### Anything else?

Ivan proposed it "may be due to output buffering maybe enabling ob_implicit_flush on downloads" in [this Slack conversation](https://codeigniterchat.slack.com/archives/C47FK3GRY/p1643042395062100), a good place to start.

**Comment by kenjis** [comment]
@MGatner Try #5623
