### ISSUE TITLE
Bug: Cannot use seeds in tests/_support

### ISSUE THREAD

**Issue by SteeveDroz** [codeigniter4/CodeIgniter4#5622]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli

### Database

SQLite3 in :memory:

### What happened?

When performing a UnitTest, I would like to use seeders located in `tests/_support/Database/Seeds`.

In my test class (that inherits `CIUnitTestCase` and uses `DatabaseTestTrait`), I add the following attributes:

```php
    protected $seed = 'TestSeeder';
```
When I run the tests, the following message appears:

```
Error: Class 'App\Database\Seeds\TestSeeder' not found
```

### Steps to Reproduce

1. Create `tests/_support/Database/Seeds/TestSeeder.php` and add a class located in the `Support\Database\Seeds` namespace and extending `CodeIgniter\Database\Seeder`.
2. Create a test class that extends `CodeIgniter\Test\CIUnitTestCase` and uses `CodeIgniter\Test\DatabaseTestTrait` with the `protected $seed = 'TestSeeder'` attribute.
3. Create a dummy test in that class.
4. Run the tests with `vendor/bin/phpunit`.

### Expected Output

The correct Seeder should be used.

### Anything else?

I noticed two things:

First, when providing the name of a non-existing Seeder, the message is:

```
InvalidArgumentException: The specified seeder is not a valid file: [REMOVED]/tests/_support/Database/Seeds/NonExistingSeeder.php
```
Meaning that my existing Seeder is correctly detected, as the message changes when I provide a valid name.

Second, there are two data stored in the Seeder. I know that because I added a var_dump on `$this->seeder` before https://github.com/codeigniter4/CodeIgniter4/blob/f843d0011f58f87d39e0cca0962ee89ccee8ee20/system/Test/DatabaseTestTrait.php#L205

I see those two elements:

```
protected $seedPath =>
  string(63) "[REMOVED]/tests/_support/Database/Seeds/"
```

and

```
protected $config =>
class Config\Database#87 (4) {
    public $filesPath =>
    string(46) "[REMOVED]/app/Database/"
    ...
```
I suspect that the file detection uses `$seeder->seedPath`, but the actual loading tries to use `$seeder->config->filePath`.

Also, when I put my test Seeders in `app\Database\Seeds` and adapt the code from my Test class, it works, comforting me in the idea that the above observation is true.

**Comment by kenjis** [comment]
```php
protected $seed = \Support\Database\Seeds\TestSeeder::class;
```

**Comment by SteeveDroz** [comment]
Sorry I forgot to mention that, I tried too. The result is:

```
Error: Class 'Support\Database\Seeds\TestSeeder' not found
```

My IDE detects it correctly, though.

**Comment by SteeveDroz** [comment]
I confirm the source of the bug, this workaround solves the problem, both for a `'TestSeeder'` and `\Support\Database\Seeds\TestSeeder::class`:

```php
    public function setUp(): void
    {
        \config('database')->filedPath = SUPPORTPATH . 'Database' . DIRECTORY_SEPARATOR;
    }
```

I wouldn't consider that as a reason to close this issue, though!

**Comment by kenjis** [comment]
Sorry, I confused the namespace.

`tests/_support/Database/Seeds/TestSeeder.php`
```php
<?php
namespace Tests\Support\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TestSeeder extends Seeder
{
    public function run()
    {
    }
}
```
`tests/SampleTest.php`
```php
<?php

use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\DatabaseTestTrait;

final class SampleTest extends CIUnitTestCase
{
    use DatabaseTestTrait;

    protected $seed = Tests\Support\Database\Seeds\TestSeeder::class;

    public function test()
    {
        $this->assertTrue(true);
    }
}
```
```sh-session
$ vendor/bin/phpunit tests/SampleTest.php 
PHPUnit 9.5.13 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.14
Configuration: /Users/kenji/work/codeigniter/CodeIgniter4/phpunit.xml

.                                                                   1 / 1 (100%)

Time: 00:00.144, Memory: 14.00 MB

OK (1 test, 1 assertion)
```

**Comment by SteeveDroz** [comment]
Yet another [PICNIC](https://en.wiktionary.org/wiki/PICNIC) error: I had the wrong namespace in my seeder: `Support\Database\Seeds` (missing the `Tests` part) because I assumed that it was like `Config` instead of `App\Config`.

Sorry for bothering you with that :disappointed:

**Comment by kenjis** [comment]
Don't worry, nobody's perfect.
