### ISSUE TITLE
Modules and vendor directory

### ISSUE THREAD

**Issue by iRedds** [codeigniter4/CodeIgniter4#5626]
### What happened?

The framework scans the directories of the modules specified in the autoload config at runtime and includes code that extends the settings, like routes or filters.
It also scans the vendor directory for modules. 
Which doesn't seem like a very good approach to me.

In addition to unnecessary scanning of the entire vendor directory in search of module configs (looking for routes = scanning vendor; looking for filters = scanning vendor), a situation may arise when this approach will make the application work incorrectly.

The example may be unsuccessful, but it shows the "vulnerability" of the approach.

Add the ``Diet`` namespace to composer.json.
```json
"autoload": {
    "psr-4": {
	"App\\": "app",
	"Config\\": "app/Config",
	"Diet\\" : "vendor/dietest/src"
    },
},
```
Generating autoloader files ``composer dump-autoload`` 

Create file ``vendor/dietest/src/Config/Routes.php``
```php
<?php
die('FAIL');
```
We start the ``php spark serve`` dev server and when we access the server we get ``FAIL``.

This shows that any composer package that has the file structure ``Config/Routes.php`` or ``Config/Filters.php`` and is not a module can affect the operation of the application.

It seems to me that if you limit the modules only to the list specified in the config, then this will have a positive effect on performance. What I mean is that even a module installed as a composer package will need to be registered in the configuration file. It will also allow you to temporarily disable such a module by simply commenting it out in the config.

### Anything else?

The framework uses classes as configuration files. If arrays were used, then by modifying the Publisher tool it would be possible to use it to register modules in configs. Like in Laravel

**Comment by kenjis** [comment]
I'm thinking the same thing. Searching for too many unneeded composer packages is wasteful.

> The framework uses classes as configuration files. If arrays were used, then by modifying the Publisher tool it would be possible to use it to register modules in configs. Like in Laravel

What do you mean?

**Comment by lonnieezell** [comment]
But the framework doesn't use arrays anymore, so that's a moot point. 

Discovery of modules can be disabled already: https://github.com/codeigniter4/CodeIgniter4/blob/develop/app/Config/Modules.php#L32

**Comment by lonnieezell** [comment]
You can still make the system "discover services" with classes. That doesn't need an array. I am curious, though - have you actually noticed an significant performance issue that you can provide data on?

**Comment by kenjis** [comment]
@lonnieezell 
For example, if I set `$discoverInComposer` false, and add [PSR4 namespaces](https://github.com/codeigniter4/CodeIgniter4/blob/develop/app/Config/Autoload.php#L43),
can I use Myth Auth without any problems?

**Comment by lonnieezell** [comment]
Have never tried it, but I would think yes. It doesn't stop Composer from working, it just doesn't scan the packages in vendor during the module discovery process, for things like views, controllers, config files, etc.

**Comment by kenjis** [comment]
I got 193 namespaces in my project.
Installing composer packages with `--no-dev`, I still got 41.
Almost all packages are not CI4 modules.

```diff
--- a/system/Autoloader/FileLocator.php
+++ b/system/Autoloader/FileLocator.php
@@ -170,6 +170,7 @@ class FileLocator
         $foundPaths = [];
         $appPaths   = [];
 
+        dd(count($this->getNamespaces()));
         foreach ($this->getNamespaces() as $namespace) {
             if (isset($namespace['path']) && is_file($namespace['path'] . $path)) {
                 $fullPath = $namespace['path'] . $path;
```

```diff
--- a/system/Router/RouteCollection.php
+++ b/system/Router/RouteCollection.php
@@ -343,7 +343,10 @@ class RouteCollection implements RouteCollectionInterface
         $routes = $this;
 
         if ($this->moduleConfig->shouldDiscover('routes')) {
+            $s0 = microtime(true);
             $files = $this->fileLocator->search('Config/Routes.php');
+            $s1 = microtime(true);
+            dd($s1 - $s0);
 
             foreach ($files as $file) {
                 // Don't include our main file again...
```

This is not a significant performance issue, but is wasteful.

```
193 namespaces: 0.0013971328735352
 41 namespaces: 0.00032496452331543
```

**Comment by lonnieezell** [comment]
Thanks for taking the time to measure that! That's quite a few package namespaces! 

It's not a significant enough performance hit to need to change things, I don't think. And when you need the performance boost it's nice to know that turning discoverInComposer off can have an impact.

**Comment by iRedds** [comment]
> > The framework uses classes as configuration files. If arrays were used, then by modifying the Publisher tool it would be possible to use it to register modules in configs. Like in Laravel
> 
> What do you mean?

A simple example.
```php
$conf = require 'conf.php'; // return ['test' => ['key' => 'value']];

$conf['test']['key2'] = 'value2';

file_put_contents('conf.php',"<?php \n return " . var_export($conf, true) . ';');

// conf.php
<?php 
 return array (
  'test' => 
  array (
    'key' => 'value',
    'key2' => 'value2',
  ),
);
```
It won't work with a class.

**Comment by iRedds** [comment]
@lonnieezell Thanks for the answer. I completely forgot about this setting.
