### ISSUE TITLE
Bug: Curl request body not resetting

### ISSUE THREAD

**Issue by jahmedk** [codeigniter4/CodeIgniter4#5632]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.7

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

![image](https://user-images.githubusercontent.com/22505794/151756884-a1a78cd2-9642-4a87-8172-3ea83118b563.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/22505794/151756897-7efe3e79-bffe-49b4-b331-2d52b30d1f56.png)

### Expected Output

The body of the second request should be empty because I did not add any parameters to the curl body.

**Comment by kenjis** [comment]
Please try: https://codeigniter4.github.io/userguide/libraries/curlrequest.html#sharing-options

**Comment by kenjis** [comment]
And I recommend you use v4.1.8.
See https://github.com/codeigniter4/CodeIgniter4/security/advisories/GHSA-7528-7jg5-6g62

**Comment by jahmedk** [comment]
Ok Thanks @kenjis

**Comment by tsomeq** [comment]
@kenjis 
I am affraid to say , is this issue really fixed ?

It seems `CURLRequest->resetOptions()` does not clear its `body` property defined in the parent class,
 (  https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/HTTP/CURLRequest.php#L148 )
So setting shareOptions to false does not solve this issue. 

Next time calling `$client->send()` method without options, that body is automatically added to `$curlOptions` in `applyBody()`.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/HTTP/CURLRequest.php#L427

I can clear the body with calling `setBody(false)` explicitly, but I think this is not safe way .
If 1st and 2nd requests are sent to different services, 2nd request might leak private information of 1st one.

Thanks.

**Comment by kenjis** [comment]
@tsomeq I deleted your comment.
See https://github.com/codeigniter4/CodeIgniter4/security/policy

**Comment by kenjis** [comment]
We have confirmed that this bug has not been fixed.

**Comment by tsomeq** [comment]
Thank you for quick reaction.
