### ISSUE TITLE
Bug: Php spark returns 404 error in testing environment

### ISSUE THREAD

**Issue by shishamo** [codeigniter4/CodeIgniter4#5641]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

Mariadb

### What happened?

Php spark return 404 error message in testing environment as below.

`ERROR: 404
Controller or its method is not found: \App\Controllers\System\Cienv::index`

### Steps to Reproduce

- set env: CI_ENVIRONMENT = testing
- run: `php spark env`

### Expected Output

Return correct spark output

**Comment by kenjis** [comment]
> The environment testing is the special one for PHPUnit testing. It has special conditions built into the framework at various places to assist with that. You can’t use it for your development.
https://codeigniter4.github.io/userguide/general/environments.html#the-environment-constant

**Comment by shishamo** [comment]
I see, thank you for your prompt answer.
