### ISSUE TITLE
Bug: Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by mridah** [codeigniter4/CodeIgniter4#5676]
### PHP Version

7.4

### CodeIgniter4 Version

4.0.3

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 8.0.27

### What happened?

I have 2  projects developed on CI running on a server with `PHP 7.4.22`. I have set up a new server with a higher PHP version `7.4.27`. 

Everything else is the same - the code, branch, config, etc, but when I access it on the browser, it throws the error:

> PHP Fatal error:  Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /var/www/html/proj1/app/Config/Events.php:27) in /var/www/html/proj1/system/Debug/Exceptions.php:162\nStack trace:\n#0 [internal function]: CodeIgniter\\Debug\\Exceptions->errorHandler()\n#1 /var/www/html/proj1/system/Debug/Exceptions.php(162): header()\n#2 /var/www/html/proj1/system/Debug/Exceptions.php(223): CodeIgniter\\Debug\\Exceptions->exceptionHandler()\n#3 [internal function]: CodeIgniter\\Debug\\Exceptions->shutdownHandler()\n#4 {main}\n  thrown in /var/www/html/proj1/system/Debug/Exceptions.php on line 162

This is happening on both the projects. All other PHP based applications are working fine.

### Steps to Reproduce

I just migrated to a server with a newer PHP version

### Expected Output

The application should have run properly as everything is the same.

**Comment by paulbalandan** [comment]
Unless you can pinpoint where in the framework this is failing or give us a minimal reproduction case, this cannot be regarded as a bug. Please send your support questions in the forum.

**Comment by kenjis** [comment]
@mridah I recommend you upgrade to the latest v4.1.8.
See https://github.com/codeigniter4/CodeIgniter4/security/advisories
