### ISSUE TITLE
Bug: Insert Empty string to Not Null field in Database

### ISSUE THREAD

**Issue by paschalidis** [codeigniter4/CodeIgniter4#5705]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL '5.7.31-0ubuntu0.18.04.1'

### What happened?

**Insert Empty string to Not Null field in Database**

***Short description***
When you don't pass the value of a field in the model `insert` function, it's by default set to an empty string in the database row.

For example, I have the following table in the database:
Table: Tasks 
Fields: id (int, auto-increment), name (varchar[255] not null), description (varchar[255])

Use the `insert` function from Model, to insert a new row in the table :
```
        $taskModel = new TaskModel();
        $data = ['description' => 'test description'];
        $result = $taskModel->insert($data);
```
Row create with name value an empty string instead of an error about Not Null Value.

### Steps to Reproduce

1. Set one field to the database table to Not Null.
2. Create a new model eg. TaskModel and extends Model.
3. Set $protectFields = false;
4. Pass to the `insert` function the data for the table except for the field you have set to Not Null.
5. A new row is created in the database table and set to not null fields empty strings.

### Expected Output

**This is the output expected from CI4 to be the same as the database error.**

```
INSERT INTO `tasks` (`description`) VALUES ("test description")	
Error Code: 1364. Field 'name' doesn't have a default value	
```

### Anything else?

**Database extra information:**
Charset = utf8mb4
Collation = utf8mb4_general_ci
Engine = InnoDB

**Comment by iRedds** [comment]
You can enable STRICT MODE in config ``'strictOn' => true,``

**Comment by paschalidis** [comment]
Thank you @iRedds.
It's work.

**Comment by kenjis** [comment]
This is MySQL's default behavior.
