### ISSUE TITLE
Doc: Incoming request. Uploaded Files.

### ISSUE THREAD

**Issue by iRedds** [codeigniter4/CodeIgniter4#5707]
### What happened?

Doc: https://codeigniter.com/user_guide/incoming/incomingrequest.html#uploaded-files

>Information about all uploaded files can be retrieved through $request->getFiles(), which returns a [FileCollection](https://codeigniter.com/user_guide/libraries/uploaded_files.html) instance. This helps to ease the pain of working with uploaded files, and uses best practices to minimize any security risks.

But the IncomingRequest::getFiles() method returns an array. 
https://github.com/codeigniter4/CodeIgniter4/blob/968c0278a0ba4138cf3e64a2bbab5f3a800532d5/system/HTTP/IncomingRequest.php#L714-L721

**Comment by kenjis** [comment]
Is this a bug of the documentation?

**Comment by kenjis** [comment]
I don't know what "uses best practices to minimize any security risks" means.

**Comment by lonnieezell** [comment]
The docs should be updated here to returning an array. 

Best practices to minimizes security risks I believe was referring to the way the File instances return mime type, etc,  where it doesn't just base it on what the client said it was, but does it's best to determine what it really is.

**Comment by kenjis** [comment]
@lonnieezell Thanks!
I sent a PR #5709
