### ISSUE TITLE
Bug: Migration rollback does not work for SQLite3

### ISSUE THREAD

**Issue by murugappanrm** [codeigniter4/CodeIgniter4#5710]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

sqlite3

### What happened?

I defined the SQLite3 parameters in the .env file:

```
database.default.database = ../app/Repository/database/mysqlite2.db
database.default.DBDriver = 'SQLite3'
```
Then creates migration for this database as follows:
```php
<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class MigrateSqlitex extends Migration
{
    public function up()
    {
        $this->forge->createDatabase('mysqlite2.db');
        $this->forge->addField([
            'id' => [
                'type' => 'INT',
                'constraint' => 5,
                'unsigned' => true,
                'auto_increment' => true,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
                'unique' => true,
            ],
            'author' => [
                'type' => 'VARCHAR',
                'constraint' => 100,
                'default' => 'King of Town',
            ],
            'description' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'status' => [
                'type' => 'ENUM',
                'constraint' => ['publish', 'pending', 'draft'],
                'default' => 'pending',
            ],
        ]);
        $this->forge->addPrimaryKey('id');
        $this->forge->createTable('users');

    }

    public function down()
    {
        $this->forge->dropTable('users');
        $this->forge->dropDatabase('mysqlite2.db');
    }
}

```
I executed the migration and all went fine.

I did a rollback but nothing was rolled-back. The Database and Tables remained. Is this a bug? If not what did  do wrong?? The documentation is so minimal in CI4 site!!!

### Steps to Reproduce

The steps are detailed above

### Expected Output

The output on rollback should result in the database and tables being removed.

**Comment by kenjis** [comment]
You cannot drop database in Migration.
If you drop database, the `migrations` table will be lost, and Migration raises an Error.
```
SQLite3::exec(): no such table: migrations
```

You cannot and don't need to use `createDatabase()` in SQLite.
In SQLite, a database is created when you connect to the database.

**Comment by murugappanrm** [comment]
Hi Kenji,

Thank you. That still proved one of my other points. The CI4 documentation is so summarized it really difficult for us to get real answers from it. Since you closed this i have to raise another isssue on the migration of SQLite.

**Comment by kenjis** [comment]
> We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
>
> If you raise an issue here that pertains to support or a feature request, it will be closed! If you are not sure if you have found a bug, raise a thread on the forum first - someone else may have encountered the same thing.
>
> Before raising a new GitHub issue, please check that your bug hasn't already been reported or fixed.
https://github.com/codeigniter4/CodeIgniter4#repository-management

**Comment by kenjis** [comment]
@murugappanrm 
> The CI4 documentation is so summarized it really difficult for us to get real answers from it.

 We don't understand what's missing in it.
You could send PRs to improve the docs.
Tthank you.
