### ISSUE TITLE
Documentation: There is no recommended install but tutorial uses it

### ISSUE THREAD

**Issue by mvdw** [codeigniter4/CodeIgniter4#5750]
### PHP Version

7.4

### CodeIgniter4 Version

develop

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli

### Database

none

### What happened?

CodeIgniter is completely new for me.

The installation manual says:

> - If you would like the simple “download & go” install that CodeIgniter3 is known for, choose the manual installation.
> - If you plan to add third party packages to your project, or want to keep CodeIgniter up to date easily, we recommend the Composer installation.

So, I went for the "simple" way.

Then, I want to follow the tutorial. The tutorial says:

> for this tutorial we will use the recommended way and install the AppStarter package through Composer. 

So, now I am stuck. There was no recommended way. Why is the tutorial not build on the "simple download & go" install method? This seems illogical.

**Comment by kenjis** [comment]
Thank you for reporting.
It seems the bug of the documentation.
We recommend Composer installation.
