### ISSUE TITLE
redirect is not working in initController()

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#5777]
Hello why is this not working. 
I created a child Controller trying to check if constant is defined on the parent controller. if not redirect as the general option but not working both on construct function and inicontroller.

```php

 public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger);

        if (!defined('ADMINPATH')) {
            
            return redirect()->to(site_url());
        }
    }

```

the redirect is not working

**Comment by kenjis** [comment]
> We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
https://github.com/codeigniter4/CodeIgniter4#repository-management

**Comment by kenjis** [comment]
> why is this not working.

`initController()` is kind of constructor.
It can't return anything.
