### ISSUE TITLE
Bug: Unable to catch DatabaseException when MySQL server down

### ISSUE THREAD

**Issue by alexxbout** [codeigniter4/CodeIgniter4#5782]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

10.4.19-MariaDB

### What happened?

An internal error occured : Attempt to read property \"errno\" on bool.

Codeigniter 4 try to access "errno" property on a boolean when retreiving errors.

### Steps to Reproduce

Use Database.php class.
Connect to database using $db = db_connect();
Retreive errors using $db->error();
Shutdown MySQL server to display errors.

### Expected Output

Showing errors to prevent crash screen.
\CodeIgniter\Database\Exceptions\DatabaseException();

**Comment by kenjis** [comment]
@alexxbout 
Can't reproduce it. When connecting to the database, I see:
```
CodeIgniter\Database\Exceptions\DatabaseException #8
Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
```

What do you want to do? if you call `$db->error()` without connecting to the database like:
```php
        $db = db_connect();
        $db->error(); 
```

**Comment by alexxbout** [comment]
![image](https://user-images.githubusercontent.com/63796783/157238178-8a00d532-480a-4bee-899d-3bd6f177c669.png)

This error is shown when calling $db->error();

I wanted to catch the DatabaseException when shutting down the MySQL server. I found that database errors message and code can be retrieved when calling $db->error().

I'm using this method placed in BaseController.php, to conenct to my database :
![image](https://user-images.githubusercontent.com/63796783/157239202-5d629794-3d6c-4267-9aa4-08c546f78164.png)

Is there a way to catch correctly DatabaseException when the server is not running ?

**Comment by kenjis** [comment]
> This error is shown when calling $db->error();

It is because you call `$db->error()` without connecting to the database.
`db_connect()` just create a connection instance. It connects to the database when running a query.

> Is there a way to catch correctly DatabaseException when the server is not running ?

Just `try` and `catch` DatabaseException.

**Comment by kenjis** [comment]
> We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
https://github.com/codeigniter4/CodeIgniter4#repository-management
