### ISSUE TITLE
Bug: Form POST data leaking between different routes

### ISSUE THREAD

**Issue by Nudasoft** [codeigniter4/CodeIgniter4#5791]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

Expected normal behavior
-----------------------------
1. I'm on the user signin route.
2. I click on the password reset link on the user signin view.
3. I fill the input field on password reset form on password reset route.
4. Hit the continue button to post data.
5. After "**small period of time**" I hit the cancel button to go back to user signin route.
6. On user signin route, there is nothing unexpected happened.

![ok](https://user-images.githubusercontent.com/30935025/157625742-ba923ba9-c899-4af0-aa2c-ac7885ad69f7.gif)

Unexpected abnormal behavior
-----------------------------------
1. I'm on the user signin route.
2. I click on the password reset link on the user signin view.
3. I fill the input field on password reset form on password reset route.
4. Hit the continue button to post data.
5. After "**very short period of time**" I hit the cancel button to go back to user signin route.
6. On user signin route, post data from password reset form get repopulated on user signin form.

![notok](https://user-images.githubusercontent.com/30935025/157626901-9c3a6b5e-ed11-4c21-aa87-3ce6eeae3ebb.gif)

I use JS to disable form submit buttons. but I can guarantee that JS not related to this issue. I have tried this with JS disabled and the result is same.

I use "if (strtolower($this->request->getMethod()) === 'post') {}" to verify if the form is submitted and use "$this->request->getPost()" to get post data.

And the repopulated input field name attribute value same as password reset form input field name value. Also I use old() to repopulate input fields.

And both forms has its action attribute specified.

Thanks.

### Steps to Reproduce

Please check the what happened section to get a idea on how to reproduce this.

### Expected Output

Please check the what happened section to see what is the expected output.

**Comment by kenjis** [comment]
It is normal behavior of `old()`.
It shows user input data saved in the session.

You sent username in the reset password page.
You clicked the cancel button, but the username reached the server and saved in the session.
And it is shown in the next page with `old()`.
