### ISSUE TITLE
Bug: getFieldNames() using the default db groups DBPrefix when connecting with another database group.

### ISSUE THREAD

**Issue by fairsketch** [codeigniter4/CodeIgniter4#5794]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.17

### What happened?

Using 2 database groups. 
When connecting with 2nd database group, there is no db_prefix in config. But the  `$db2->getFieldNames("table_name")` using the prefix from 1st database group. 

### Steps to Reproduce

Add 2 database group in \app\Config\Database.php

In 1st database, use a db_prefix. In 2nd database don't use db_prefix. 

Connect with database 2. 
```php
$db2 = Config\Database::connect('2nd_database');
```

Try to call this: 
```php
$db2->getFieldNames("table_name");
```

See the error. 2 database is using the prefix of 1st database. 

### Expected Output

2nd database should use the 2nd database group db prefix instead of 1st database group db prefix.

**Comment by kenjis** [comment]
@fairsketch 
First, v4.1.8 has serious vulnerability. Please upgrade to v4.1.9.
See https://github.com/codeigniter4/CodeIgniter4/security/advisories

Can't reproduce.
Can you show us exact steps to reproduce?

**Comment by paulbalandan** [comment]
No feedback for a month, closing. Please open a new issue report once the requirements are met.
