### ISSUE TITLE
Bug: curlrequest request function returns ResponseInterface class instead of Response class

### ISSUE THREAD

**Issue by qbuache** [codeigniter4/CodeIgniter4#5795]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

curlrequest "request" (and every get, post, patch, etc) functions return a `ResponseInterface` class instead of a `Response` class.

Which technically works, but messes with the code completion and error coloring.

The [documentation](https://codeigniter.com/user_guide/libraries/curlrequest.html#making-requests) states : `Since the response is an instance of CodeIgniter\HTTP\Response you have all of the normal information available to you: ..` but in practice it's a `@var \CodeIgniter\HTTP\ResponseInterface $result`

### Steps to Reproduce

Make a CURL request with the `\Config\Services::curlrequest` "request" function and try to use the result as a `Response` class

### Expected Output

The `\Config\Services::curlrequest` "request" function to return a `Response` class object

**Comment by qbuache** [comment]
`curlrequest` functions return a `ResponseInterface` class instead of a `Response` class. Which messes with VScode code completion and errors.
 
![ci_response2](https://user-images.githubusercontent.com/4728069/158125206-589bb4d1-562d-47bb-aba4-10656437cc9c.png)
.

**Comment by kenjis** [comment]
> curlrequest functions return a ResponseInterface class instead of a Response class. 

It is probably by design. 
> This class is modeled after the [Guzzle HTTP Client](http://docs.guzzlephp.org/en/latest/) library since it is one of the more widely used libraries. Where possible, the syntax has been kept the same so that if your application needs something a little more powerful than what this library provides, you will have to change very little to move over to use Guzzle.
https://codeigniter4.github.io/userguide/libraries/curlrequest.html

But I'm not sure the ResponseInterface is really compatible with PSR-7.

If you don't care Guzzle compatibility,
workaround is setting the type by `@var Response $response`.

PhpStorm works properly with auto-completion.

**Comment by aswinkumar863** [comment]
The same issue on VSCode also with PHP IntelliSense extension added.  I also raised a query on the forum regarding it. 

https://forum.codeigniter.com/showthread.php?tid=79103

**Comment by paulbalandan** [comment]
This is just another issue on the interface design.
