### ISSUE TITLE
Bug: Timer::getElapsedTime() returns incorrect value

### ISSUE THREAD

**Issue by emilebourquin** [codeigniter4/CodeIgniter4#5797]
### PHP Version

8.1

### CodeIgniter4 Version

latest

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

There is a bug in `system/Debug/Timer.php`'s `getElapsedTime` function when elapsed times are `>= 1,000` seconds.

(This bug has been in CI since the 3.0 days, in Benchmark.php's elapsed_time function.)

The code is currently:
```php
return (float) number_format($timer['end'] - $timer['start'], $decimals);
```

note that:
```php
$number = (float) number_format(1000 - 1, 4); // returns 999
$number = (float) number_format(1001 - 1, 4); // returns ... 1
```

This is because of the default thousands separator of number_format. To fix, use no thousands separator:
```php
$number = (float) number_format(1001 - 1, 4, '.', '');
```

which returns the expected 1000.0000

However, even without the cast to (float), if the return value is compared to an integer:

```php
if($elapsed_time <= 300) ...
```

this code will trigger, as 1,000.0000 <= 300 . No matter of casting that I have tried will fix this.

### Steps to Reproduce

Call timer start() , then 1,0001 seconds later, call timer stop(). Compare the return value of getElapsedTime to say 5. It will be < 5

### Expected Output

getElapsedTime should not return numbers decorated with a thousands separator, as it messes with comparisons against other integers.

**Comment by kenjis** [comment]
I sent a PR  #5798
