### ISSUE TITLE
Bug: Invalid regexp pattern: System\Config\Publisher::$restrictions[FCPATH]

### ISSUE THREAD

**Issue by jtoberling** [codeigniter4/CodeIgniter4#5799]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

Publisher Config Restriction contains invalid Regexp pattern for FCPATH. 

Codeigniter4/System/Config/Publisher.php:
```php
    public $restrictions = [
**BAD**:
        FCPATH   => '#\.(?css|js|map|htm?|xml|json|webmanifest|tff|eot|woff?|gif|jpe?g|tiff?|png|webp|bmp|ico|svg)$#i',

**BETTER**:
        FCPATH   => '#\.?(css|js|map|html?|xml|json|webmanifest|tff|eot|woff?|gif|jpe?g|tiff?|png|webp|bmp|ico|svg)$#i',
];
```

### Steps to Reproduce

Just try to publish something to "./public/". 
Default restrictions filters out...

### Expected Output

Regexp pattern should be corrected.

**Comment by kenjis** [comment]
The config is updated in the `develop` branch:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/app/Config/Publisher.php#L26

If you think something wrong with it, feel free to reopen.

**Comment by rumpfc** [comment]
I found another mismatch in regex. It matches `.wof` and `.woff`, but not `.woff2`. I think that's a typo, I don't know any `.wof` file formats. The regex should be

```
#\.?(css|js|map|html?|xml|json|webmanifest|tff|eot|woff2?|gif|jpe?g|tiff?|png|webp|bmp|ico|svg)$#i
                                                       ^ (added "2" to "woff")
```

**Comment by kenjis** [comment]
What do you mean?
`woff2?` does not match `.wof`.
