### ISSUE TITLE
Bug: CodeIgniter 4.2 OCI8 dbpreifx

### ISSUE THREAD

**Issue by BoburDeveloper** [codeigniter4/CodeIgniter4#5801]
In Oracle dbdriver problem with dbprefix. dbprefix is duplicating

**Comment by kenjis** [comment]
Please use bug report:
https://github.com/codeigniter4/CodeIgniter4/issues/new?assignees=&labels=bug&template=bug_report.yml&title=Bug%3A+

**Comment by kenjis** [comment]
@BoburDeveloper 
As you see, we use `DBPrefix` in testing, and works fine.
https://github.com/codeigniter4/CodeIgniter4/blob/94b70e83f61d453494a4eafadfedc5ee231d9241/tests/_support/Config/Registrar.php#L110
