### ISSUE TITLE
issue when u use redirect()->back() multiple tabs in a browser

### ISSUE THREAD

**Issue by hunter-and1** [codeigniter4/CodeIgniter4#5811]
### PHP Version

7.3

### CodeIgniter4 Version

4.1.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

when u open multi tabs page have submit form and using redirect()->back() first one he will send back good result. but if u go to another one and send data he will back to first ongle page.

sry my english very bad.

### Steps to Reproduce

open two tabs page have submit form and using redirect()->back() first one he will send back good result. but if u go to another one and send data.

### Expected Output

expect to back to normal page have in start.

### Anything else?

problme i guess be couse u using cookie storing back url page for all application i guess u have to used for single page resquestt save back url.

**Comment by kenjis** [comment]
@hunter-and1 Thank you for taking time.

What is multi tabs page?
Can you show us minimum sample code to reproduce it?

**Comment by hunter-and1** [comment]
for exmple:

u have this method in controller
```
function updateService($id){
 // code
 redirect()->back();
}
```
$routes->post('update_service/(:num)', 'ServiceController::updateService/$1');

and u open in your browser two tab first one 
tab1 => /update_service/654
tab2 => /update_service/25

when u submit tab1 he will back to /update_service/654
but when u submit in tab2 he will take last data of url he will return /update_service/654

**Comment by kenjis** [comment]
Thanks. I got it, multiple tabs in a web browser.

But it seems it is not possible to fix it now, because CI4 Session does not support multiple tabs/windows.
And `redirect()->back()` uses the Session. It has only one previous URL value.

**Comment by hunter-and1** [comment]
yeah i see that

**Comment by hunter-and1** [comment]
i think i have do `redirect()->to(current_url()) ` or he will be same ??

**Comment by kenjis** [comment]
You can use `redirect()->to()`:
https://codeigniter4.github.io/userguide/general/common_functions.html#redirect

**Comment by iRedds** [comment]
@kenjis 
https://github.com/codeigniter4/CodeIgniter4/blob/92eb705dc4165fe7727245f81e4976a6e4da3639/system/Helpers/url_helper.php#L153
I think it can be replaced with: 
```php
$referer = Services::request()->getServer('HTTP_REFERER', FILTER_SANITIZE_URL) 
                 ?? $_SESSION['_ci_previous_url'] 
                 ?? site_url('/');
```

**Comment by kenjis** [comment]
@iRedds I'm not sure HTTP_REFERER is more reliable than the session value.

**Comment by MGatner** [comment]
We don't want to use HTTP_REFERRER, it introduces other issues. Think of `redirect()->back()` as taking you to "the last page viewed during this Session", not the browser "back" button. If you need multiple browser tabs to work independently then you should use private windows to start multiple sessions.

**Comment by iRedds** [comment]
So you need to add a description to the user guide and the RedirectResponse::back() method from the previous_url() helper description. Because the expected behavior doesn't match reality.

**Comment by kenjis** [comment]
I sent a PR to update the user guide: #5815

**Comment by kenjis** [comment]
I think it is already well-documented in `previous_url()`:
https://github.com/codeigniter4/CodeIgniter4/blob/2a1f23f3b86d3fb1ce2eb235aae01f37b2701ecd/system/Helpers/url_helper.php#L141-L148

**Comment by MGatner** [comment]
> doesn't match reality

Doesn't it though? As a developer when I came across this for the first time I was not surprised at all the "back" meant "back in the session history". Maybe that was from previous backend experience - but are people so confused about how sessions work that we have to "fix" them?

**Comment by iRedds** [comment]
@kenjis But we are using ``redirect()->back()``, not ``previous_url()``.
@MGatner Sorry, but no one in their right mind would be guided by a session. What you explain by experience is not normal behavior, but only that you perceive incorrect behavior as normal.

Using ``redirect()->back()`` the developer expects the user to be redirected to the page from which the request was made.

**Comment by kenjis** [comment]
@iRedds What do you mean? 
I sent a PR to add a note for `redirect()->back()`.
See https://codeigniter4.github.io/CodeIgniter4/general/common_functions.html#redirect

What else do you need?

**Comment by iRedds** [comment]
@kenjis I meant that the documentation before your PR, as well as the description of the RedirectResponse::back() method, did not specify the behavior and/or that this method uses the previous_url() helper. And the only way to find out about using previous_url() was to look at the implementation of the RedirectResponse::back() method.
