### ISSUE TITLE
Warning: 'getMethod' is depreciated. intelephense(1007) in vs code

### ISSUE THREAD

**Issue by bhojkamal** [codeigniter4/CodeIgniter4#5827]
### PHP Version

7.4, 8.0

### CodeIgniter4 Version

4.1.3 - 4.1.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDb 10.4.18

### What happened?

I use the following code in VS code and it give warning for the getMethod. 
```
if ($this->request->getMethod() == 'post') {
            $rules = [
                'title' => 'required|min_length[3]|max_length[200]',
                'content' => 'required|min_length[20]',
            ];
.
...
```
![image](https://user-images.githubusercontent.com/14083299/159870216-0d6891c7-531c-454d-a1da-13a3a8f19210.png)

It also showing error for `$this->request->getVar('title'), or $this->request->getPost('title'). `

It says  `Undefined method 'getVar'.intelephense(1013)` Same for `getPost` 
![image](https://user-images.githubusercontent.com/14083299/159870920-a756e228-35b4-444b-bd3e-d416e9e99418.png)

I want to get rid of this warning and errors on my code. I don't see such warning or errors underline with red colors in codeIgntier 3 or Laravel programming in same vs code. 

The application is running but I want to clean code. I looked on examples and on guide but they use same way as I use. 

### Steps to Reproduce

on getMethod , the line is strike through it and showing warning in vs code.
on getVar or getPost, red warning lines are underline in vs code like showing spelling errors on doc by spelling checker. 

### Expected Output

It should not have warning or errors in the code. The should be clean and nice. 

### Anything else?

So, what shall I use, and It works and get red of this warning and errors?

**Comment by iRedds** [comment]
1. Information in the @deprecated tag. It's on your screenshot.
2. $this->request has a RequestInterface typehint, but this interface does not contain a getVar() method, etc. That's why the warning comes up.

You can't just pick it up and fix it. This will bring about breaking changes. Therefore, wait for the 5th version. Well, or until the policy regarding the BС changes.

**Comment by bhojkamal** [comment]
> 1. Information in the @deprecated tag. It's on your screenshot.
> 2. $this->request has a RequestInterface typehint, but this interface does not contain a getVar() method, etc. That's why the warning comes up.
> 
> You can't just pick it up and fix it. This will bring about breaking changes. Therefore, wait for the 5th version. Well, or until the policy regarding the BС changes.

Ok. I will wait then.
