### ISSUE TITLE
Bug:  Can't find a route for 'u/1/george'.  - Can't pass an optional parameter to route

### ISSUE THREAD

**Issue by WEB-TM** [codeigniter4/CodeIgniter4#5828]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

Guys, how to pass an optional parameter to route on Codeigniter 4? Does not have such a feature?
```
// Route
$routes->get('u/(:num)/(:any)/(:any)', 'MemberController::index/$1/$2/$3', ['as' => 'view_profile']);
```

```
// In MemberController
public function index($id, $username, $section = null)
{
        // var_dump([
        //     'id' => $id,
        //     'username' => $username
        // ]);
        return view('user/profile');
}
```

It trows that error
![image](https://user-images.githubusercontent.com/73018912/159929629-ebe780b8-2493-4abe-b32a-4acd51b5dba7.png)

### Steps to Reproduce

I tried (:any?), (:any)?
$routes->get('u/(:num)/(:any)/(:any?)', *** ... 
Then I set the parameter to null in the function by default but its still trows the same error: 404 - File Not Found. Can't find a route for 'u/1/george'.

### Expected Output

Should be possible to pass optional parameters to route

**Comment by kenjis** [comment]
> `(:any)` will match all characters from that point to the end of the URI. This may include **multiple URI segments**.
 https://codeigniter4.github.io/userguide/incoming/routing.html#placeholders

Try like this:
```php
$routes->get('u/(:num)/(:segment)', 'MemberController::index/$1/$2', ['as' => 'view_profile']);
$routes->get('u/(:num)/(:segment)/(:segment)', 'MemberController::index/$1/$2/$3', ['as' => 'view_profile']);
```
