### ISSUE TITLE
Bug: View parser throws view exception with nested 'if' within javascript code

### ISSUE THREAD

**Issue by RaymondFJ** [codeigniter4/CodeIgniter4#5831]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

mysql

### What happened?

when parsing a view with inline javascript (within a script tag, specifically an if statement within outer braces {})
the view parser mis-interpretes this code as a view conditional and improperly transforms the code to a php conditional.

### Steps to Reproduce

controller code:
```php
public function test(){
		$parser = service('parser');

        $somedata = [
            'message' => 'massagee'
        ];
        $view = <<<'EOL'
                 <script type="text/javascript">
                     var f = function(){
                         if(true){
                             alert('{message}');
                         }
                     }
                 </script>
                 EOL;

        return $parser->setData($somedata)->renderString($view);
    }
```

error message:
```
You have a syntax error in your Parser tags: <script type="text/javascript">
var f = function()if ((true){
alert('{message): ');
}
}
</script>
```

problem:
the nested javascript if statement has been parsed
and php tags have been placed around it 
(observed by printing the output directly pre-evaluation in the parser class)

### Expected Output

Expected output would be the non-modified javascript,
with the substituted tag within.

```js
<script type="text/javascript">
                     var f = function(){
                         if(true){
                             alert('massagee');
                         }
                     }
                 </script>
```

**Comment by kenjis** [comment]
Related: #5825

**Comment by kenjis** [comment]
The error is because you write `if` condition in the template:
```
{
     if(true){
        alert('{message}
```

Workaround is to use `{noparse}`:
```
{noparse}if(true){{/noparse}
```

**Comment by kenjis** [comment]
I recommend you don't write JavaScript code in templates.

**Comment by RaymondFJ** [comment]
@kenjis 

Thank you for your assessment.

With all do respect I think the recommendation of not writing JavaScript code within templates is ridiculous;
and would recommend reconsidering that stance in a view template parser.

That being said, if that is the stance of CI4 I would suggest a few features:

1. making mention that this is a porting concern from CI3 applications to CI4 on this page: https://codeigniter4.github.io/userguide/installation/upgrade_view_parser.html at least
2. making conditional parsing an optional 'on by default' argument for the parser render/renderString functions

Thank you again for your help with the issue

**Comment by kenjis** [comment]
@RaymondFJ Thank you for comment.
Not writing JavaScript code within templates is a common practice.
You write JavaScript in js files and include it in a template.
You could get a value in a tag in the template from the JavaScript code.

I don't know the porting concern from CI3 applications to CI4.
Do you mean the sample code works on CI3?

You could send a PR to change the documentation.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/README.md
Contributions are welcome.

**Comment by RaymondFJ** [comment]
@kenjis 
> Not writing JavaScript code within templates is a common practice.

Writing JavaScript within HTML is a common practice, inline <script> tags with code are still very widely used.

> You write JavaScript in JS files and include it in a template.
> You could get a value in a tag in the template by the JavaScript code.

In a brand-new application that might be reasonable; though in our case we're porting a rather large application from
CI3 to CI4; if it came to refactoring all of that code we would probably just end up using a different template framework
that allows for JavaScript without issue.

> I don't know the porting concern from CI3 applications to CI4. Do you mean the sample code works on CI3?

Yes, you can write JavaScript readily within templates in CI3 without issue; so this was a surprise when discovered in CI4.

As it stands our current solution is to just comment out CI4 template conditional parsing, not ideal but it works.

**Comment by kenjis** [comment]
> Yes, you can write JavaScript readily within templates in CI3 without issue; so this was a surprise when discovered in CI4.

Okay, I'm not sure the error would be fixed, but reopen this issue for now.

**Comment by RaymondFJ** [comment]
@kenjis 

Thanks, I suppose this is at least an opportunity for others to comment if they encounter the same issues as CI4 gains traction

**Comment by kenjis** [comment]
I sent a PR to add option to disable Parser conditionals: #5841

**Comment by kenjis** [comment]
@RaymondFJ I sent another PR: #5842
It can solve the syntax error and you can still use Parser conditionals if you want.
