### ISSUE TITLE
Bug: page with jquery on HEAD not working if CI_DEBUG is enabled

### ISSUE THREAD

**Issue by bokunodev** [codeigniter4/CodeIgniter4#5832]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cgi-fcgi

### Database

mysql

### What happened?

i have multiple pages with `<script src="jqyuery">` at the top
if CI_DEBUG is set to true in environment/development.php, errors are loggef into browser console.
but everything works just fine with CI_DEBUG disabled.

### Steps to Reproduce

have a page with jquery on the head

### Expected Output

everything works fine

### Anything else?

i'm using jquery CDN, laragon as web server, we notice it because the bug does not appear in production server. also, we dont use template and our js code does not depend on jquery. its just for datatable js.
we didn't investigate any further.

**Comment by kenjis** [comment]
I checked, but can't reproduce it.

```diff
--- a/app/Views/welcome_message.php
+++ b/app/Views/welcome_message.php
@@ -7,6 +7,8 @@
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="/favicon.ico"/>
 
+    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
+
    <!-- STYLES -->
 
    <style {csp-style-nonce}>
```
and navigate to `http://localhost:8080/`.
I see no errors in the browser console.
