### ISSUE TITLE
Bug: Spark cannot use Сommand option on PHP 7.4 (Cannot unpack array with string keys)

### ISSUE THREAD

**Issue by iRedds** [codeigniter4/CodeIgniter4#5835]
### PHP Version

7.4

### CodeIgniter4 Version

dev

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli

### What happened?

```
[Error]

Cannot unpack array with string keys

at SYSTEMPATH\CodeIgniter.php:893

Backtrace:
  1    SYSTEMPATH\CodeIgniter.php:467
       CodeIgniter\CodeIgniter()->runController()

  2    SYSTEMPATH\CodeIgniter.php:346
       CodeIgniter\CodeIgniter()->handleRequest()

  3    SYSTEMPATH\CLI\Console.php:48
       CodeIgniter\CodeIgniter()->run()

  4    ROOTPATH\spark:79
       CodeIgniter\CLI\Console()->run()


Process finished with exit code 9.
```

### Steps to Reproduce

```
php.exe spark make:migration a --table
```

### Anything else?

1. Adds options to the list of arguments.
 https://github.com/codeigniter4/CodeIgniter4/blob/7107e782f86b3394c22cf980c85bc385b42b9207/system/HTTP/CLIRequest.php#L206
We unpack the array ``[0 => 'make:migration', 1 => 'a' 'table' => null]``, which causes an exception.
https://github.com/codeigniter4/CodeIgniter4/blob/7107e782f86b3394c22cf980c85bc385b42b9207/system/CodeIgniter.php#L892-L894

2. The console command tests use the ``command()`` function call, which differs in functionality from calling a command in the console via ``spark``.
I think that command call tests should be supplemented with a test that simulates calling a command in the console.

**Comment by kenjis** [comment]
@iRedds Thanks! I sent a PR.

**Comment by MGatner** [comment]
Thanks for the clear description and fast response!
