### ISSUE TITLE
Bug: Database defaultGroup was not changed based on Environment

### ISSUE THREAD

**Issue by chaluvadinarasimha** [codeigniter4/CodeIgniter4#5848]
### PHP Version

7.3

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.2

### What happened?

I created different database groups in Config/Database.php file
development, production with different groups,
i changed defaultGroup from Database constructor based on Environment set by .env file

### Steps to Reproduce

add different groups in Config/Database.php
with production, development

and 

add code to Database constructor 
```php
if (ENVIRONMENT === 'development') {
    $this->defaultGroup = 'development';
}
```

i got the following error in System/Database/Config file
error: "default is not a valid database connection group"

screenshot attached
![database_error](https://user-images.githubusercontent.com/39306532/161361806-a205f182-6381-40fa-b7f7-c5330428572a.jpg)

### Expected Output

flawless change of defaultGroup based on Environment

**Comment by kenjis** [comment]
@chaluvadinarasimha Thank you for reporting.

What is **Database constructor**? Full Classname?

**Comment by chaluvadinarasimha** [comment]
file: App\Config\Database.php


<?php
namespace Config;

use CodeIgniter\Database\Config;

/**
 * Database Configuration
 */
class Database extends Config
{
 public $production = [];
 public $development = [];

 public function __construct()
    {
        parent::__construct();

        // Ensure that we always set the database group to 'tests' if
        // we are currently running an automated test suite, so that
        // we don't overwrite live data on accident.
       if (ENVIRONMENT === 'testing') {
             $this->defaultGroup = 'tests';
       }
       if (ENVIRONMENT === 'development') {
             $this->defaultGroup = 'development';
       }
      if (ENVIRONMENT === 'production') {
             $this->defaultGroup = 'production';
       }
    }

}

**Comment by chaluvadinarasimha** [comment]
> @chaluvadinarasimha Thank you for reporting.
> 
> What is **Database constructor**? Full Classname?


**file: App\Config\Database.php**




class Database extends Config
{
    
    public $defaultGroup = 'default';

    public $development= [  ];
    public $production= [  ];

    public function __construct()
    {
        parent::__construct();

        // Ensure that we always set the database group to 'tests' if
        // we are currently running an automated test suite, so that
        // we don't overwrite live data on accident.
        if (ENVIRONMENT === 'testing') {
             $this->defaultGroup = 'tests';
        }
       **if (ENVIRONMENT === 'development') {
             $this->defaultGroup = 'development;
       }**

    }
}

**Comment by kenjis** [comment]
Can't reproduce.

`.env`:
```
CI_ENVIRONMENT = development
```

```diff
--- a/app/Config/Database.php
+++ b/app/Config/Database.php
@@ -86,5 +86,9 @@ class Database extends Config
         if (ENVIRONMENT === 'testing') {
             $this->defaultGroup = 'tests';
         }
+
+        if (ENVIRONMENT === 'development') {
+            $this->defaultGroup = 'development';
+       }
     }
 }
```

```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        $db = db_connect();
        d($db);
    }
}
```

Navigate to http://localhost:8080/

```
InvalidArgumentException

development is not a valid database connection group. 

SYSTEMPATH/Database/Config.php at line 65
```

**Comment by kenjis** [comment]
@chaluvadinarasimha What if you change like this? Do you see `development`?

```php
    public function __construct()
    {
        parent::__construct();

        // Ensure that we always set the database group to 'tests' if
        // we are currently running an automated test suite, so that
        // we don't overwrite live data on accident.
        if (ENVIRONMENT === 'testing') {
            $this->defaultGroup = 'tests';
        }

        dd(ENVIRONMENT);
    }
```

**Comment by chaluvadinarasimha** [comment]
> @chaluvadinarasimha What if you change like this? Do you see `development`?
> 
> ```
>     public function __construct()
>     {
>         parent::__construct();
> 
>         // Ensure that we always set the database group to 'tests' if
>         // we are currently running an automated test suite, so that
>         // we don't overwrite live data on accident.
>         if (ENVIRONMENT === 'testing') {
>             $this->defaultGroup = 'tests';
>         }
> 
>         dd(ENVIRONMENT);
>     }
> ```
I have two copies of same database one for dev, another for prod.
I want, when I am in development, my database will be local MySQL db, when I change environment to production  db connection should be changed accordingly.

**Comment by kenjis** [comment]
@chaluvadinarasimha I mean, your code should work as you expect. 
At least I confirmed it worked.

Your error message is `default is not a valid database connection group`.
It means `if (ENVIRONMENT === 'development')` is false.

**Comment by chaluvadinarasimha** [comment]
Yes

**Comment by kenjis** [comment]
@chaluvadinarasimha What do you mean by yes?
If you solve this issue, please close.

**Comment by chaluvadinarasimha** [comment]
removed DBGroup in Extended Model Class, it works fine.
Thank you for you are response.
