### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ivose** [codeigniter4/CodeIgniter4#5879]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

A long time i searched a reason why the next doesn't work in CI4. Fetching data with ajax:
<code>
fetch('https://example.com/delete-item/' + id, {
  method: 'DELETE',
})
.then(res => res.text()) // or res.json()
.then(res => console.log(res))
</code>
Also i tried with jquery ajax. The same problem... .

### Steps to Reproduce

-

### Expected Output

-

**Comment by iRedds** [comment]
What is the response from ajax request?

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
