### ISSUE TITLE
Bug: Multiple CLI::color inside CLI::write change color of strings that shouldn't be affected

### ISSUE THREAD

**Issue by andrej-spicka** [codeigniter4/CodeIgniter4#5892]
### PHP Version

7.4, 8.0

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### What happened?

When used `CLI::color` at the beginning of the string inside `CLI::write` and then again later inside string, all characters **between the two** instances of `CLI::color` became **affected by the first** instance if `CLI::color`.
If there is only one `CLI::color` inside `CLI::write`, output is just as expected.
Doesn't matter if it is run via CLI inside controller or as a spark command.

### Steps to Reproduce

```php
<?php
namespace App\Controllers;

use CodeIgniter\CLI\CLI;

class Home extends BaseController
{
    public function index(): void
    {
        CLI::write('white white white white', 'white');
        CLI::write('white white ' . CLI::color('red', 'red') . ' white', 'white');
        CLI::write('white white white ' . CLI::color('red', 'red'), 'white');
        CLI::write(CLI::color('red', 'red') . ' white white white', 'white');
        CLI::write(CLI::color('red', 'red') . ' white white ' . CLI::color('red', 'red'), 'white');
        CLI::write(CLI::color('red', 'red') . ' white ' . CLI::color('red', 'red') . ' white', 'white');
    }
}

```
Run via CLI.

### Expected Output

All **white** words should be in white color, all **red** words should be in red.

**Comment by kenjis** [comment]
@andrej-spicka Thank you for reporting.
I've confirmed the bug.
<img width="658" alt="screenshot 2022-04-13 8 50 16" src="https://user-images.githubusercontent.com/87955/163072617-a02e04f7-4117-472a-91a6-2ae4164c1ae4.png">

**Comment by kenjis** [comment]
@andrej-spicka Please try #5893

**Comment by andrej-spicka** [comment]
> @andrej-spicka Please try #5893

It works for me.
