### ISSUE TITLE
how to do join table to another database?

### ISSUE THREAD

**Issue by mahdikur** [codeigniter4/CodeIgniter4#5896]
i found error 
> Table '`database_name`.`table_name`' doesn't exist 

in the documentation it is only available how to provide a database group only, but not yet available how to combine the two database connections

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

If you send a bug report, use the bug report form:
https://github.com/codeigniter4/CodeIgniter4/issues/new?assignees=&labels=bug&template=bug_report.yml&title=Bug%3A+

Thank you.
