### ISSUE TITLE
Bug: HEAD requests all return a 404

### ISSUE THREAD

**Issue by retalieight** [codeigniter4/CodeIgniter4#5898]
### PHP Version

7.4

### CodeIgniter4 Version

4.0.4

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

MySQL 5.7.37

### What happened?

For some reason with my site all my HEAD requests even on working pages you can perform a GET request on generate a 404 not found. How can this be fixed so that it works?

const CI_VERSION = '4.0.4'

Example:

[root@yaarcorp public_html]# curl -I https://www.mediyaar.com/blood-test/
HTTP/1.1 404 Not Found
Date: Thu, 14 Apr 2022 16:25:36 GMT
Server: Apache
Cache-control: no-store, max-age=0, no-cache
Upgrade: h2,h2c
Connection: Upgrade
Vary: User-Agent
Content-Type: text/html; charset=UTF-8

### Steps to Reproduce

curl -I any page that returns a 200 on a GET request and get a 404 returned on a HEAD request.

### Expected Output

HEAD requests should return 200 if the page exists.

**Comment by kenjis** [comment]
Thank you for reporting.

Because you did not implemented them.
There is no concept like *page* in CodeIgniter or PHP.

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by retalieight** [comment]
So use the forum?

<html>
<body>


CodeIgniter Forums
--
We cannot process your registration because there has already been 2 new registration(s) from your ip address in the past 24 hours. Please try again later.


</body>
</html>

**Comment by retalieight** [comment]
Everyone seems to get that.

**Comment by kenjis** [comment]
@retalieight Thank you!
We investigate it.

**Comment by kenjis** [comment]
This is not related, but v4.0.4 is too old and not secure.
We strongly recommend you upgrade to v4.1.9.
See https://github.com/codeigniter4/CodeIgniter4/security/advisories

**Comment by lonnie-vault** [comment]
@retalieight thanks for reporting that about the forums. That was the first I'd heard of it. I've changed a setting that I believe should fix that. Can you try signing up at the forums again and let us know if we need to take additional steps or not?
