### ISSUE TITLE
Bug: DataException "There is no data to update." doesn't fire if $primaryKey is present in $allowedFields

### ISSUE THREAD

**Issue by rmilecki** [codeigniter4/CodeIgniter4#5904]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.7

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cgi-fcgi

### What happened?

Calling `BaseModel::update()` should throw `DataException` "There is no data to update." if nothing in database entry (row) has changed. It doesn't happen if model's `$allowedFields` contains `$primaryKey` (for whatever reason - developer mistake or some rare case).

Example:
```php
class FooModel extends Model
{
    protected $table = 'foo';
    protected $primaryKey = 'id';
    protected $returnType = '\App\Entities\Foo';
    protected $allowedFields = [ 'id', 'name' ];
}
```

### Steps to Reproduce

```php
$fooModel = new FooModel();

$foo = $fooModel->find(1);
$foo->fill(['unused' => 'foo' ]);
$fooModel->update($foo);
```

### Expected Output

DataException "There is no data to update."

### Anything else?

Pseudo-code explaining what actually happens:
```php
BaseModel::update()
    BaseModel::transformDataToArray()
        BaseModel::objectToArray()
            Model::objectToRawArray()
                BaseModel::objectToRawArray()
                    Entity::toRawArray()                                       ← This gets an array of changed only values
                $properties[$this->primaryKey] = $data->{$this->primaryKey}    ← This sets $primaryKey even if it wasn't set in $data passed to the BaseModel::update()
    BaseModel::doProtectFields()                                               ← This filters to-be-updated columns using $allowedFields
    if (empty($data))
        throw DataException::forEmptyDataset('update');
```

**Comment by rmilecki** [comment]
I'm not CodeIgniter expert but I think that order inside `BaseModel::update()` should be changed. It seems to me that it should:

1. Generate raw array from object (e.g. from `Entity`) with changed-only values
2. Filter to-be-updated columns using `$allowedFields`
3. Check for `$data` to be empty and throw an exception if it is
4. [Finally] Set `$primaryKey` in the raw array containing values to be updated in database row

**Comment by kenjis** [comment]
Thank you for reporting.

I can't understand the situation when you set the primary key in `$allowedFields`.
Why do you need it?

And it seems CodeIgniter Model dose not support that case.

**Comment by lonnie-vault** [comment]
Primary key should never be an allowed field. That array is for fields that can be updated during mass assignments, like taking a $_POST array and passing it all into the model. Only the fields in allowedFields would be saved then. In that example, you obviously don't want it overwriting your primary key.

**Comment by kenjis** [comment]
This is clearly a misuse.
I have sent PR #6021 to update the documentation.

**Comment by kenjis** [comment]
Can't reproduce in the develop branch.

```sql
-- auto-generated definition
create table foo
(
    id   int auto_increment
        primary key,
    name varchar(255) not null
);
```
```php
<?php

namespace App\Entities;

use CodeIgniter\Entity\Entity;

class Foo extends Entity
{
    protected $datamap = [];
    protected $dates   = [];
    protected $casts   = [];
}
```
```php
<?php

namespace App\Models;

use CodeIgniter\Model;

class FooModel extends Model
{
    protected $table         = 'foo';
    protected $primaryKey    = 'id';
    protected $returnType    = '\App\Entities\Foo';
    protected $allowedFields = ['id', 'name'];
}
```
```php
<?php

namespace App\Controllers;

use App\Models\FooModel;

class Home extends BaseController
{
    public function index()
    {
        $fooModel = new FooModel();

        $foo = $fooModel->find(1);
        $foo->fill(['unused' => 'foo']);
        $fooModel->update($foo);
    }
}
```
http://localhost:8080/
```
CodeIgniter\Database\Exceptions\DataException

There is no data to update. 
```

**Comment by kenjis** [comment]
@rmilecki If you still have this issue, please check the latest `develop` branch.
