### ISSUE TITLE
Feature request: enable development mode for list of IP Addresses

### ISSUE THREAD

**Issue by datamweb** [codeigniter4/CodeIgniter4#5912]
Hello.
I saw the question with the subject "**How I can set (or switch on) CI_ENVIRONMENT to DEVELOPMENT mode for my personal IP address?**" [here](https://forum.codeigniter.com/showthread.php?tid=81730&pid=395648#pid395648).
**I answered this question**, but I think having a variable in file `App.php` to set **IP addresses** can be **user-friendly**.
eg: 
```
    public $enableDevelopmentModeOfIPAddresses= [
                    '172.0.1.1',
                    '175.25.25',
    ];
```
Do you agree with me?

**Comment by kenjis** [comment]
Please submit feature requests to our [forum](https://forum.codeigniter.com/forum-29.html).
We use github issues to track bugs and planned work.
