### ISSUE TITLE
Prefix added twice when I used method like in Builder

### ISSUE THREAD

**Issue by patmartel** [codeigniter4/CodeIgniter4#5917]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySql

### What happened?

When I used method "like" in Builder , the db prefix is added twice 

I join the error send.

The DB prefix is "applis_"

My code is :
$this->builder->like('clients.name', 'test');

mysqli_sql_exception #1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%test%
OR `applis_``applis_clients`.`name` LIKE '%test%' ESCAPE '!'

### Steps to Reproduce

Create a DB config file with DBPrefix not empty
Create a request with builder
Add clause like

### Expected Output

I expected a query result

**Comment by iRedds** [comment]
Already fixed. https://github.com/codeigniter4/CodeIgniter4/pull/5778
