### ISSUE TITLE
Bug: Conflict example `env` file with docker-compose

### ISSUE THREAD

**Issue by baharsah** [codeigniter4/CodeIgniter4#5920]
### PHP Version

8.0, 8.1

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli

### Database

MariaDB 10.2

### What happened?

Conflict with docker-compose while using example .env file from codeigniter

### Steps to Reproduce

``` bash
$ docker-compose up

unexpected character "." in variable name near "app.baseURL = [Redacted] ....

```

### Expected Output

docker-compose started correctly

### Anything else?

No

**Comment by paulbalandan** [comment]
As of v4.1.5, you can use underscores in place of the dots (e.g. `app_baseUrl`)

**Comment by kenjis** [comment]
See dev docs:
https://codeigniter4.github.io/CodeIgniter4/general/configuration.html#env-var-namespace-separator
