### ISSUE TITLE
Bug: BaseCommand $params Type

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#5926]
### PHP Version

7.4

### CodeIgniter4 Version

develop

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli

### What happened?

I believe that the typing on `BaseCommand::run()` was supposed to be `@param array<int, string> $params` (a "list" of strings), not `@param array<string, mixed> $params` (string keys, mixed values).

https://github.com/codeigniter4/CodeIgniter4/blob/bca263c5fef57cf3152b31916c26a63496341be6/system/CLI/BaseCommand.php#L96-L101

I started tracing this back and it was taking too long but should be quick follow-up at some point.

### Steps to Reproduce

See code

### Expected Output

See code

**Comment by kenjis** [comment]
```
$ php spark make:migration Test --table table

CodeIgniter v4.1.9 Command Line Tool - Server Time: 2022-04-27 16:24:57 UTC-05:00


┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ $params                                                                                                                                        │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
array (2) [
    0 => string (4) "Test"
    'table' => string (5) "table"
]
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Called from .../system/Commands/Generators/MigrationGenerator.php:80 [dd()]
```

**Comment by kenjis** [comment]
`$params` comes from [$_SERVER['argv']](https://www.php.net/manual/en/reserved.variables.argv.php).
https://github.com/codeigniter4/CodeIgniter4/blob/bca263c5fef57cf3152b31916c26a63496341be6/system/HTTP/CLIRequest.php#L180

`@param array<int|string, string> $params` is correct.

**Comment by kenjis** [comment]
I sent a PR #5927

**Comment by MGatner** [comment]
Ah it has both types. Okay thanks for clarifying - I made a mistake on the Myth:Auth analysis (or failed to fix a preexisting mistake).
