### ISSUE TITLE
Bug: ErrorException use the ``command()`` in the controller when of SAPI not equls cli

### ISSUE THREAD

**Issue by datamweb** [codeigniter4/CodeIgniter4#5943]
### PHP Version

7.3, 7.4, 8.0, 8.1

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

5.6

### What happened?

PR related to: [link](https://forum.codeigniter.com/showthread.php?tid=81792)
`ErrorException #64` When use ``command('db:seed KishanSeeder');`` in the controller. This error occurred when transferring Project CI4 to an online host. Most likely related to **SAPI** .

### Steps to Reproduce

Step 1: Install CI4 on the online host.
Step 2: Build **app\Database\Seeds\KishanSeeder.php** :
```
<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KishanSeeder extends Seeder
{
    public function run()
    {

        $data = [
        'field_name1'                  => 'Kishan field 1',
        'field_name2'                 => 'Kishan field  2',
        ];

        $this->db->table('table_name')->insert($data);
    }
}
```
Step 3: Add `command('db:seed KishanSeeder')` to the controller **app\Controllers\Home.php** : 
```
<?php

namespace App\Controllers;


class Home extends BaseController
{
    public function index()
    {
        command('db:seed KishanSeeder');
        return;
     
    }
}

```

Step Four View Link **CI4.com/public/home**
```
ErrorException #64
CodeIgniter\Autoloader\Autoloader::main(): Failed opening required '/home/pooyapa2/passkey.ir/index.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') [search →](https://www.duckduckgo.com/?q=ErrorException+CodeIgniter%5CAutoloader%5CAutoloader%3A%3Amain%28%29%3A+Failed+opening+required++%28include_path%3D%29)

SYSTEMPATH/Commands/Server/rewrite.php at line 46

39 // then let the request handle it like normal.
40 if ($uri !== '/' && (is_file($path) || is_dir($path))) {
41     return false;
42 }
43 
44 // Otherwise, we'll load the index file and let
45 // the framework handle the request from here.
46 require_once $fcpath . 'index.php';
47 // @codeCoverageIgnoreEnd
```

### Expected Output

Execute command ``command('db:seed KishanSeeder');`` and record the data in the table.

### Anything else?

Solution 1: calling the following address: `CI4.com/public/` **not** `CI4.com/public/home`
Solution 2: create a file `index.php` in root ci4.
Solution 3: Edit file **system/Commands/Server/rewrite.php** and add 
```
$ListSAPI = array('apache', 'apache2handler', 'cgi', 'cgi-fcgi', 'cli', 'cli-server', 'embed', 'fpm-fcgi', 'litespeed', 'phpdbg');
if (in_array(PHP_SAPI, $ListSAPI)) {
    return;
}
```
Solution 4: Delete line `require_once $fcpath . 'index.php';` in file **system/Commands/Server/rewrite.php**
The proposed solutions have been tested, but their impact on other framework functions has not been measured, so it needs to be reviewed.

**Comment by kenjis** [comment]
Can't reproduce it.

I see `Your environment is currently set as development. `.
```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        return command('env');
    }
}
```

**Comment by kenjis** [comment]
I don't know why `SYSTEMPATH/Commands/Server/rewrite.php` runs.
It is only for `spark serve` command.
And there is no `CodeIgniter\Autoloader\Autoloader::main()` method in CodeIgniter4.

> Solution 1: calling the following address: CI4.com/public/ not CI4.com/public/home

What's the difference?

It seems this is not a problem in CI4, but in the server environment/setup.

**Comment by datamweb** [comment]
> I don't know why `SYSTEMPATH/Commands/Server/rewrite.php` runs. It is only for `spark serve` command. And there is no `CodeIgniter\Autoloader\Autoloader::main()` method in CodeIgniter4.
> 
> > Solution 1: calling the following address: CI4.com/public/ not CI4.com/public/home
> 
> What's the difference?
Look at this.
[Home](https://passkey.ir/public/home) An error is given here.
Then look there.
[Not Error](https://passkey.ir/public/) The commands are executed here. T**he data is recorded in a table.**
**Both have different functions on the same server.**
No problem when tested on localhost. 
Please test on your **online server**(SAPI =**litespeed**).


> 
> It seems this is not a problem in CI4, but in the server environment/setup.

**Comment by datamweb** [comment]
> Can't reproduce it.
> 
> I see `fpm-fcgi Your environment is currently set as development. `.
> 
> ```
> <?php
> 
> namespace App\Controllers;
> 
> class Home extends BaseController
> {
>     public function index()
>     {
>         return PHP_SAPI . command('env');
>     }
> }
> ```

No it is `litespeed Your environment is currently set as development.`

**Comment by kenjis** [comment]
@datamweb Try this:
https://codeigniter4.github.io/CodeIgniter4/installation/troubleshooting.html#only-the-default-page-loads

**Comment by kenjis** [comment]
It may not matter, but your server is incorrectly configured.

You base URL should be `https://passkey.ir/`, not `https://passkey.ir/public/`.
`DOCUMENT_ROOT` should be ` /home/pooyapa2/passkey.ir/public`, not ` /home/pooyapa2/passkey.ir`

**Comment by kenjis** [comment]
> Look at this.
[Home](https://passkey.ir/public/home) An error is given here.
Then look there.
[Not Error](https://passkey.ir/public/) The commands are executed here. The data is recorded in a table.
Both have different functions on the same server.

Both URL should run exactly the same controller.
So the error indicates there is a misconfiguration in the server configuration.

> No problem when tested on localhost.
Please test on your online server(SAPI =litespeed).

I don't have litespeed.

**Comment by datamweb** [comment]
> It may not matter, but your server is incorrectly configured.
> 
> You base URL should be `https://passkey.ir/`, not `https://passkey.ir/public/`. `DOCUMENT_ROOT` should be ` /home/pooyapa2/passkey.ir/public`, not ` /home/pooyapa2/passkey.ir`

@kenjis Thanks, you are a superman, The problem was solved by setting `DOCUMENT_ROOT ` correctly.
