### ISSUE TITLE
Bug: [Validation] field with asterisk (nested array) `matches` rule

### ISSUE THREAD

**Issue by mostafakhudair** [codeigniter4/CodeIgniter4#5945]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 4.9

### What happened?

```php
    protected $validationRules = [
        'debit_amount'                           => [
            'label' => 'DEBIT AMOUNT',
            'rules' => 'required|decimal|is_natural_no_zero|matches[beneficiaries_accounts.*.credit_amount]',
        ],
        'beneficiaries_accounts.*.credit_amount' => [
            'label' => 'CREDIT AMOUNT',
            'rules' => 'required|decimal|is_natural_no_zero',
        ],
    ];
```

```php
$this->validation->setRules($model->getValidationRules());
```

**Case 1:**
```php
    $data = [
        "debit_amount"           => 1500,
        "beneficiaries_accounts" => [
            "account_1" => [
                "credit_amount" => 1500,
            ],
        ],
    ];
```

**Case 2:**
```php
    $data = [
        "debit_amount"           => 1500,
        "beneficiaries_accounts" => [
            "account_1" => [
                "credit_amount" => 1000,
            ],
            "account_2" => [
                "credit_amount" => 500,
            ],
        ],
    ];
```

```php
    if (! $this->validation->run($data))) {
        if ($this->validation->hasError())) {
            return $this->validation->listErrors();
        }

        return "Success";
    }
```

### Steps to Reproduce
**Case 1:**
Output: `Success`.

**Case 2:**
Output: `The Debit Amount field does not match the Credit Amount field.`.

### Expected Output
**Case 1:**
Output: `Success`.

**Case 2:**
Output: `Success`.

**Comment by kenjis** [comment]
@mostafakhudair You forgot to write down the actual output.

**Comment by mostafakhudair** [comment]
My bad, updated

**Comment by kenjis** [comment]
Ref #5942

**Comment by dani-gouken** [comment]
I don't think that this is a bug. In case 2 none of the `credit_amount` matches the debit amount

**Comment by kenjis** [comment]
> I don't think that this is a bug. In case 2 none of the credit_amount matches the debit amount

Yes, it is true.

`matches[]` expects string data, but `beneficiaries_accounts.*.credit_amount` data is an array.
So it seems it never matches.
