### ISSUE TITLE
Feature: [Validation] new rule `required_if`

### ISSUE THREAD

**Issue by mostafakhudair** [codeigniter4/CodeIgniter4#5954]
I'm wondering why we don't have rule for conditional usage `required_if` will be a great feature to handle conditional validation.

example:
```php
    $rules = [
        'gender' => [
            'label' => 'Gender',
            'rules' => 'required|in_list[male,female]',
        ],
        'age'    => [
            'label' => 'age',
            'rules' => 'required|numeric|greater_than_equal_to[21]|less_than_equal_to[50]',
        ],
        'job'    => [
            'label' => 'Job',
            'rules' => 'required_if[(gender,=,male&&age,>=,25&&age,<=,35)||(gender,=,female&&age,>=,21&&age,<=,40)]',
        ],
    ];
```

and comparison operators would be:-

Operator | Name 
-- | -- 
`=` | Equal
`!=` | Not Equal
`<` | Less Than
`<=` | Less Than or Equal to
`>` | Greater Than
`>=` | Greater Than or Equal to

**Comment by iRedds** [comment]
no god please no.
1. This looks ugly.
2. The rule separator is a vertical bar.

**Comment by mostafakhudair** [comment]
any idea doing it with better look?
the rule is needed in some cases

**Comment by kenjis** [comment]
Creating Custom Rules
https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#creating-custom-rules

**Comment by mostafakhudair** [comment]
Thanks kenjis, I know how to create a custom rule, but i'm talking about adding `required_ifi` as a core rule

**Comment by kenjis** [comment]
https://laravel.com/docs/9.x/validation#rule-required-if
```
required_if:anotherfield,value,...
```
If there is the restriction of defining it with strings, this is about the limit of the parameters.
```
required_if[anotherfield,value,...]
```
I am opposed to more rules unless a very great need is identified.
You can write any custom rules.

**Comment by iRedds** [comment]
@mostafakhudair 
At the beginning, the validator should ignore the empty rule.
Next, you can "build" the rule
```php
$rules = [
    'field' => [ true ? 'required' : '', 'rule2', 'rule3'],
];
```

**Comment by paulbalandan** [comment]
It seems this is a derivation of an existing rule which, as @iRedds pointed out, can be easily made. I would go for a new rule in the core if that's a unique rule not a derivation.
