### ISSUE TITLE
Bug: bad display in Debugbar/Routes/Params

### ISSUE THREAD

**Issue by szajens** [codeigniter4/CodeIgniter4#5955]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Bug in file: system/Debug/Toolbar/Views/_routes.tpl line 83:
`('&lt;empty&gt;&nbsp| default: ' . var_export($param->isDefaultValueAvailable() ? $param->getDefaultValue() : null, true)),`

currently show: `paramName	&lt;empty&gt;&nbsp| default: 'defaultValue'`

problem: double entities

### Steps to Reproduce

`('<empty> | default: ' . var_export($param->isDefaultValueAvailable() ? $param->getDefaultValue() : null, true)),`

### Expected Output

`paramName	<empty> | default: 'defaultValue'`

### Anything else?

![parambug](https://user-images.githubusercontent.com/65465848/166555891-f2d7b6ff-3372-4672-b785-b5ffa2847936.png)

**Comment by kenjis** [comment]
> Bug in file: system/Debug/Toolbar/Views/_routes.tpl line 83:

There is no line 83.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Debug/Toolbar/Views/_routes.tpl

Please try the latest develop.

**Comment by kenjis** [comment]
Fixed by #5619

**Comment by szajens** [comment]
sorry,

system/Debug/Collectors/Routes.php

**Comment by kenjis** [comment]
Okay, anyway this bug was fixed already in the `develop`.

**Comment by szajens** [comment]
Sorry for the mistake
