### ISSUE TITLE
Bug: Limit to subdomains, not work

### ISSUE THREAD

**Issue by szajens** [codeigniter4/CodeIgniter4#5959]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.9 develop

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

> https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#limit-to-subdomains
> You can restrict it to any subdomain by setting the value to an asterisk, (*). If you are viewing from a URL that does not have any subdomain present, this will not be matched:

// Limit to any sub-domain
`$routes->add('from', 'to', ['subdomain' => '*']);` <-not work

### Steps to Reproduce

Change in file: [https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Router/RouteCollection.php#L1354](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Router/RouteCollection.php#L1354)

change old: `unset($host[count($host)]);`
to new: `unset($host[count($host)-1]);`

### Expected Output

bug fix

**Comment by szajens** [comment]
or `array_pop($host)`

**Comment by kenjis** [comment]
@szajens Thank you!
This must be a bug.

**Comment by kenjis** [comment]
I sent a PR #5961.
