### ISSUE TITLE
Bug: error_404.php mismatched property value and does not support languages

### ISSUE THREAD

**Issue by szajens** [codeigniter4/CodeIgniter4#5976]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.9 develop

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

mismatched property value: [line 27](https://github.com/codeigniter4/CodeIgniter4/blob/develop/app/Views/errors/html/error_404.php#L27)
old: `letter-spacing: 0.8;` change to: `letter-spacing: 0.8px;`

does not support languages [line 79](https://github.com/codeigniter4/CodeIgniter4/blob/develop/app/Views/errors/html/error_404.php#L79)
old: `Sorry! Cannot seem to find the page you were looking for.` maybe change to: `<?=\Config\Services::language()->getLine('HTTP.pageNotFound')?>`

### Steps to Reproduce

as above

### Expected Output

as above

**Comment by kenjis** [comment]
I don't know it is a bug that the message does not use lang().
You can change view file contents freely in `app/Views/`.

At least, "Sorry! Cannot seem to find the page you were looking for." is not the same as "Page Not Found".
