### ISSUE TITLE
`define()` in Events

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#5977]
I would like to move the following `define()` from the `Events` class file, because it causes an errors when using preloading.
Where should these be located?
https://github.com/codeigniter4/CodeIgniter4/blob/496dece14f0b9877420d19908f2c96773a2b6b79/system/Events/Events.php#L17-L19

```
CRITICAL - 2022-05-08 06:28:21 --> Undefined constant "CodeIgniter\Events\EVENT_PRIORITY_NORMAL"
#0 /Users/kenji/work/codeigniter/ci3-and-4-benchmark/ci4/app/Config/Events.php(50): CodeIgniter\Events\Events::on('pre_system', Object(Closure))
#1 /Users/kenji/work/codeigniter/ci3-and-4-benchmark/ci4/vendor/codeigniter4/framework/system/Events/Events.php(94): include('/Users/kenji/wo...')
#2 /Users/kenji/work/codeigniter/ci3-and-4-benchmark/ci4/vendor/codeigniter4/framework/system/Events/Events.php(141): CodeIgniter\Events\Events::initialize()
#3 /Users/kenji/work/codeigniter/ci3-and-4-benchmark/ci4/vendor/codeigniter4/framework/system/CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#4 /Users/kenji/work/codeigniter/ci3-and-4-benchmark/ci4/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
```

Related #5974

**Comment by MGatner** [comment]
I suppose we have to keep them for backwards-compatibility, but these should really be class constants. Maybe put them in **config/Constants.php** with a deprecation comment and then make new class constants that we use internally? How does that sound?

**Comment by kenjis** [comment]
Perfect! 
I sent a PR #6000
