### ISSUE TITLE
Bug: Redirect not working in templete

### ISSUE THREAD

**Issue by amirandev** [codeigniter4/CodeIgniter4#5994]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

I'm trying to redirect one page to one another but it doesn't works at all

![image](https://user-images.githubusercontent.com/73018912/167815920-a5991d31-e14d-4242-815f-244114821e45.png)

![image](https://user-images.githubusercontent.com/73018912/167816492-239d8084-3efd-493c-b6ce-4268e41b91c5.png)

### Steps to Reproduce

I have already tried

```
redirect()->route('about_us')
redirect()->to(route('about_us'))
redirect(route('about_us'))
header('location: '.route('about_us'))

```

### Expected Output

About us page (Expected to reditect index to about page)

**Comment by kenjis** [comment]
This is the specification of CI4, not a bug.
You can't redirect in Views.

`redirect()` just returns `RedirectResponse` object.
