### ISSUE TITLE
Bug: Using placeholder (:any) before {locale} in routes cause incorrect $localeSegment value.

### ISSUE THREAD

**Issue by kpeu3u** [codeigniter4/CodeIgniter4#5997]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

 MySQL 5.6

### What happened?

Incorrect `$localeSegment` when route is set as: `$routes->get('(:any)/lang/{locale}', 'Language::index');`

Using placeholder in routes cause problem in getting:
```php
$localeSegment = array_search('{locale}', preg_split('/[\/]*((^[a-zA-Z0-9])|\(([^()]*)\))*[\/]+/m', $key), true);
```
at line 375.
The `$localeSegment` suppose to be 3 but returned value is 2

### Steps to Reproduce

```php
$routes->get('(:any)/lang/{locale}', 'Language::index');
```

URL: https://domain.name/test/lang/bg

App Config:
```php
public $defaultLocale = 'en';
public $supportedLocales = ['en', 'bg',];
```

### Expected Output

expect to set locale as 'bg'

**Comment by iRedds** [comment]
Can't reproduce
```php
public $defaultLocale = 'en';
public $supportedLocales = ['en', 'uk', 'bg'];

$routes->get('(:any)/lang/{locale}', fn () => service('request')->getLocale());
```
test/lang/uk -> uk
test/lang/bg -> bg
test/lang/aaa -> en

```   
(:any)/lang/{locale}
  0     1      2  
```

**Comment by MGatner** [comment]
@iRedds Did you test on 4.1.9?

**Comment by iRedds** [comment]
@MGatner yep

**Comment by kpeu3u** [comment]
Let me post my specific case and some debugging results:
Routes.php
`$routes->group('emenu', ['namespace' => 'Emenu\Controllers'], static function ($routes) {
    $routes->get('/', 'Home::index');
    $routes->get('(:any)/lang/{locale}', 'Language::index');
});`

App.php
`    /**
     * --------------------------------------------------------------------------
     * Default Locale
     * --------------------------------------------------------------------------
     *
     * The Locale roughly represents the language and location that your visitor
     * is viewing the site from. It affects the language strings and other
     * strings (like currency markers, numbers, etc), that your program
     * should run under for this request.
     *
     * @var string
     */
    public $defaultLocale = 'bg';

    /**
     * --------------------------------------------------------------------------
     * Negotiate Locale
     * --------------------------------------------------------------------------
     *
     * If true, the current Request object will automatically determine the
     * language to use based on the value of the Accept-Language header.
     *
     * If false, no automatic detection will be performed.
     *
     * @var bool
     */
    public $negotiateLocale = false;

    /**
     * --------------------------------------------------------------------------
     * Supported Locales
     * --------------------------------------------------------------------------
     *
     * If $negotiateLocale is true, this array lists the locales supported
     * by the application in descending order of priority. If no match is
     * found, the first locale will be used.
     *
     * @var string[]
     */
    public $supportedLocales = ['bg', 'en', 'es', 'ru', 'fr', 'de', 'gr', 'ro'];`

Call url: https://domain.dev/emenu/pod-vishnata/lang/en

Debug result:

Router.php:

` // Reset localeSegment
            $localeSegment = null;

            $key = $key === '/'
                ? $key
                : ltrim($key, '/ ');

            $matchedKey = $key; **"emenu/(.*)/lang/{locale}"**

            // Are we dealing with a locale?
            if (strpos($key, '{locale}') !== false) {
                $localeSegment = array_search('{locale}', preg_split('/[\/]*((^[a-zA-Z0-9])|\(([^()]*)\))*[\/]+/m', $key), true); **2**

                // Replace it with a regex so it
                // will actually match.
                $key = str_replace('/', '\/', $key);
                $key = str_replace('{locale}', '[^\/]+', $key); **"emenu\/(.*)\/lang\/{locale}"**
            }
`
IncomingRequest.php:
` /**
     * Sets the locale string for this request.
     *
     * @return IncomingRequest
     */
    public function setLocale(string $locale) **$locale: "lang"**
    {
        // If it's not a valid locale, set it
        // to the default locale for the site.
        if (! in_array($locale, $this->validLocales, true)) {
            $locale = $this->defaultLocale; **sets default locale back to bg**
        }

        $this->locale = $locale;
        Locale::setDefault($locale);

        return $this;
    }`

**Comment by MGatner** [comment]
@kpeu3u Have you tested this against the `develop` branch? There have been so many unreleased changes that 4.1.9 is hard to judge anymore.

**Comment by kpeu3u** [comment]
@MGatner I haven't test against develop branch, i just checked line $localeSegment = array_search('{locale}', preg_split('/[\/]*((^[a-zA-Z0-9])|\(([^()]*)\))*[\/]+/m', $key), true); for regular expression changes. Changes in method that determine locale segment refers to variable name changes only.
