### ISSUE TITLE
Database backup is not working with MySQLi.

### ISSUE THREAD

**Issue by DhPandya** [codeigniter4/CodeIgniter4#5998]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 8.0

### What happened?

I'm working on a CodeIgniter 4 project where I have to provide the functionality to take the full backup of the currently connected database with CodeIgniter 4. But CodeIgniter is showing an error mentioned below.

**CodeIgniter\Database\Exceptions\DatabaseException #8 Unsupported feature of the database platform you are using.**

### Steps to Reproduce

Just set up the latest CodeIgniter 4 Version and write the below code into your controller.
Connect your database with your CodeIgniter 4.

```
$db = \Config\Database::connect();
$util = \Config\Database::Utils($db);
$util->backup([
    'format' => 'gzip',
    'filename' => 'backup' . date('Y-m-d')
]);
```

![image](https://user-images.githubusercontent.com/46279781/168642372-e4e0ee17-53a8-47c8-aee3-48ae1446f4f2.png)

### Expected Output

It should return the full database backup instead of an Exception.

**Comment by iRedds** [comment]
Are you seriously?

**Comment by DhPandya** [comment]
> 

Yes. Please help me out with these.

**Comment by kenjis** [comment]
It seems there is no `backup()` method.
https://codeigniter4.github.io/CodeIgniter4/search.html?q=backup&check_keywords=yes&area=default

**Comment by kenjis** [comment]
If you want this feature, it seems you need to implement it for all supported databases.
https://forum.codeigniter.com/showthread.php?tid=72750&pid=362231#pid362231

Probably nobody will implement it.

**Comment by kenjis** [comment]
> Please help me out with these.

If you really need to backup your database with PHP,
find a good package for it, or port CI3 code and create a package if you like it.

https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/drivers/mysqli/mysqli_utility.php

But I think `mysqldump` command is a better choice.

**Comment by DhPandya** [comment]
> > Please help me out with these.
> 
> If you really need to backup your database with PHP, find a good package for it, or port CI3 code and create a package if you like it.
> 
> https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/drivers/mysqli/mysqli_utility.php
> 
> But I think `mysqldump` command is a better choice.

Thank you for replying & for providing great suggestion. I will look into your suggestion.

**Comment by datamweb** [comment]
@kenjis  I've been working on a package development called **codeigniter-spark-plus** for some time.
Which adds a number of commands to the CLI.
One of the `run:backup` commands. I have encountered a number of challenges in implementing it, which I am trying to solve.
I will let you know if I can overcome them.
If you want to know the full list of commands let me know so I can send it to you.
