### ISSUE TITLE
Documentation: CodeIgniter 4 URI Routing documentation error 

### ISSUE THREAD

**Issue by Hamed-Zargham** [codeigniter4/CodeIgniter4#6017]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

CodeIgniter 4 User Guide documentation, URI Routing:

[https://codeigniter.com/user_guide/incoming/routing.html](https://codeigniter.com/user_guide/incoming/routing.html)

In "Examples" section we read: 

" A URL containing the word “journals” in the first segment will be remapped to the “**AppBlogs**” class, and the default method, which is usually index():

$routes->add('journals', '**App\Blogs**'); "

As I tested The backslash before Blogs causes system looks for '**App**' directory inside App/Controllers directory (in fact App/Controllers/App !), so **will not** remap to  “AppBlogs” class !

In my opinion to avoid confusing newbies perhaps it would be better to remove the word 'App' from class name so the corrected documentation would be:

A URL containing the word “journals” in the first segment will be remapped to the “**Blogs**” class, and the default method, which is usually index():

$routes->add('journals', '**Blogs**');  

### Steps to Reproduce

 $routes->add('journals', 'App\Blogs');

### Expected Output

 $routes->add('journals', 'Blogs');

### Anything else?

https://codeigniter.com/user_guide/incoming/routing.html

**Comment by kenjis** [comment]
@Hamed-Zargham Thank you for taking time.

What you say is correct.
```php
$routes->add('journals', 'App\Blogs');  // -> \App\Controller\App\Blogs
$routes->add('journals', '\App\Blogs'); // -> \App\Blogs
```

That's fixed in the develop user guide.
See https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#examples

**Comment by Hamed-Zargham** [comment]
> @Hamed-Zargham Thank you for taking time.
> 
> What you say is correct.
> 
> ```
> $routes->add('journals', 'App\Blogs');  // -> \App\Controller\App\Blogs
> $routes->add('journals', '\App\Blogs'); // -> \App\Blogs
> ```
> 
> That's fixed in the develop user guide. See https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#examples

Thanks!
