### ISSUE TITLE
Docs: CI 4 Installation Troubleshooting Guide

### ISSUE THREAD

**Issue by Hamed-Zargham** [codeigniter4/CodeIgniter4#6040]
### PHP Version

7.3, 7.4, 8.0, 8.1

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL

### What happened?

Hi,
in [this link](https://codeigniter.com/user_guide/installation/troubleshooting.html#:~:text=If%20a%20URL%20like%20/mypage/find/apple%20doesn%E2%80%99t%20work%2C%20but%20the%20similar%20URL%20/index.php/mypage/find/apple%20does%2C%20that%20sounds%20like%20your%20.htaccess%20rules%20(for%20Apache)%20are%20not%20set%20up%20properly%2C%20or%20the%20mod_rewrite%20extension%20in%20Apache%E2%80%99s%20httpd.conf%20is%20commented%20out.) 
It seems that
/**index.php**/mypage/find/apple
should be changed to:
mypage/find/apple/**index.php**

### Steps to Reproduce

[ reference link](https://codeigniter.com/user_guide/installation/troubleshooting.html#:~:text=If%20a%20URL%20like%20/mypage/find/apple%20doesn%E2%80%99t%20work%2C%20but%20the%20similar%20URL%20/index.php/mypage/find/apple%20does%2C%20that%20sounds%20like%20your%20.htaccess%20rules%20(for%20Apache)%20are%20not%20set%20up%20properly%2C%20or%20the%20mod_rewrite%20extension%20in%20Apache%E2%80%99s%20httpd.conf%20is%20commented%20out.)

### Expected Output

mypage/find/apple/index.php

### Anything else?

[ reference link](https://codeigniter.com/user_guide/installation/troubleshooting.html#:~:text=If%20a%20URL%20like%20/mypage/find/apple%20doesn%E2%80%99t%20work%2C%20but%20the%20similar%20URL%20/index.php/mypage/find/apple%20does%2C%20that%20sounds%20like%20your%20.htaccess%20rules%20(for%20Apache)%20are%20not%20set%20up%20properly%2C%20or%20the%20mod_rewrite%20extension%20in%20Apache%E2%80%99s%20httpd.conf%20is%20commented%20out.)

**Comment by kenjis** [comment]
The latest `develop` User Guide:
https://codeigniter4.github.io/CodeIgniter4/installation/troubleshooting.html#i-have-to-include-index-php-in-my-url

`/mypage/find/apple` means something like `http://localohost/mypage/find/apple`.
`/index.php/mypage/find/apple` means something like `http://localohost/index.php/mypage/find/apple`
I think they are not wrong.

Do you say `http://localohost/mypage/find/apple/index.php` is correct?
Why?

**Comment by Hamed-Zargham** [comment]
> The latest `develop` User Guide: https://codeigniter4.github.io/CodeIgniter4/installation/troubleshooting.html#i-have-to-include-index-php-in-my-url
> 
> `/mypage/find/apple` means something like `http://localohost/mypage/find/apple`. `/index.php/mypage/find/apple` means something like `http://localohost/index.php/mypage/find/apple` I think they are not wrong.
> 
> Do you say `http://localohost/mypage/find/apple/index.php` is correct? Why?

I thought that example wanted to say mypage/find/apple/index.php
(thought index.php has been placed at the end by mistake !)
I caught the point after your made it clear :slightly_smiling_face:
regards

**Comment by kenjis** [comment]
Okay, you are probably new to PHP.

`http://localohost/index.php/mypage/find/apple` seems weird, but it is correct URL,
and the `index.php` will be executed.

But it is not clean, so everybody wants to remove (hide) the `index.php` and configures web server.
