### ISSUE TITLE
Bug: Misdiagnosis `extension` for file `zip`

### ISSUE THREAD

**Issue by datamweb** [codeigniter4/CodeIgniter4#6046]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli

### What happened?

Incorrect detection of zip file extensions.

```
$file = new \CodeIgniter\Files\File($myZipFilePath);
$ext = $file->guessExtension();
```
The expected output is **zip**. But the value of **pptx** is returned.

### Steps to Reproduce

Create a zip file in path `SUPPORTPATH . 'Files/myZipFile.zip';`.
Run the following test.

```
    public function testHaveExtensionZip()
    {
       $fileZip = SUPPORTPATH . 'Files/myZipFile.zip';
        $file = new File($fileZip);
        $this->assertSame('zip', $file->guessExtension());
    }
```
Test failure. Because **pptx** is returned.

### Expected Output

The value of `zip ` is returned.

### Anything else?

Temporary solution:
Transfer [L143](https://github.com/codeigniter4/CodeIgniter4/blob/d464fbf859afad076f69d4e2677dbf55955ac26e/app/Config/Mimes.php#L143) ~ [L149]https://github.com/codeigniter4/CodeIgniter4/blob/d464fbf859afad076f69d4e2677dbf55955ac26e/app/Config/Mimes.php#L149
 to [L103](https://github.com/codeigniter4/CodeIgniter4/blob/d464fbf859afad076f69d4e2677dbf55955ac26e/app/Config/Mimes.php#L103) lines in file `app/Config/Mimes.php`.

**Comment by kenjis** [comment]
I've confirmed this behavior.

It is weird that all `application/zip` files are guessed as `pptx`.
Moving the `zip` item up seems to be fine.
```php
'zip'   => [
            'application/x-zip',
            'application/zip',
            'application/x-zip-compressed',
            'application/s-compressed',
            'multipart/x-zip',
        ],
```

**Comment by paulbalandan** [comment]
But the question is: Are `application/x-zip` and `application/zip` correct mime types for pptx files?

**Comment by kenjis** [comment]
@paulbalandan Good point!

```php
<?php
namespace App\Controllers;
use CodeIgniter\Files\File;
class Home extends BaseController
{
    public function index()
    {
        $fileZip = WRITEPATH . '000081487.pptx';
        $file = new File($fileZip);
        d($file->getMimeType());
    }
}
```
```
$ php public/index.php 

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ $file->getMimeType()                                                                                                                    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
string (73) "application/vnd.openxmlformats-officedocument.presentationml.presentation"
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Called from .../app/Controllers/Home.php:10 [d()]
```

But I found a note from 10 years age:
> MS Office 2007 extensions (pptx, xlsx, docx) do not have a default Mime type, they have "application/zip" mime type
 https://www.php.net/manual/ja/function.finfo-file.php#107750

**Comment by paulbalandan** [comment]
But Office 2007 does not have `x` in the extensions. As far as I know, they are .ppt, .doc, .xls

**Comment by iRedds** [comment]
doc/xls/ppt is a binary file format. 
docx/xlsx/pptx is a zip archive that contains all data in xml.

**Comment by kenjis** [comment]
> The big change in PowerPoint 2007 and PowerPoint 2008 for Mac (PowerPoint version 12.0) was that the stable binary file format of 97–2003 was replaced as the default by a new [zipped](https://en.wikipedia.org/wiki/Zip_(file_format)) [XML](https://en.wikipedia.org/wiki/XML)-based [Office Open XML](https://en.wikipedia.org/wiki/Office_Open_XML) format (.pptx files).
https://en.wikipedia.org/wiki/Microsoft_PowerPoint#Office_Open_XML_(since_2007)

**Comment by datamweb** [comment]
PPTX files have replaced [.PPT](https://fileinfo.com/extension/ppt) files as the standard file format for saving presentations in PowerPoint. Unlike PPT files, which store presentation data in a single binary file, PPTX files are saved in the Open XML format, which stores data as separate files and folders in a compressed [Zip](https://techterms.com/definition/zip) package. The archive includes various types of files, such as an [.XML](https://fileinfo.com/extension/xml) file that stores presentation properties, one or more [.TXT](https://fileinfo.com/extension/txt) files that contain slide notes, and images and other media files that are included in the presentation.

**Comment by paulbalandan** [comment]
Maybe we can tweak a little this proposed code from the [link](https://www.php.net/manual/ja/function.finfo-file.php#107750)
```php
<?php

$arrayZips = array("application/zip", "application/x-zip", "application/x-zip-compressed");

$arrayExtensions = array(".pptx", ".docx", ".dotx", ".xlsx");

$file = 'path/to/file.xlsx';

$original_extension = (false === $pos = strrpos($file, '.')) ? '' : substr($file, $pos);

$finfo = new finfo(FILEINFO_MIME);

$type = $finfo->file($file);

if (in_array($type, $arrayZips) && in_array($original_extension, $arrayExtensions))
{
   return $original_extension;
}
```
