### ISSUE TITLE
Migration is not working when adding addKeys() method first parameter as array

### ISSUE THREAD

**Issue by DhPandya** [codeigniter4/CodeIgniter4#6064]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

8.0.27

### What happened?

I'm working through CodeIgniter 4 migration where I am trying to add Index constraints on some columns. As per the documentation and method definition, I have specified the array containing the name of the number of columns that need to be indexed. As soon I have fired the command ` php spark migrate` It gives me an error & found that CodeIgniter joins all the array keys in a single String.

![ctTbZ](https://user-images.githubusercontent.com/46279781/171565040-e1b06de9-87cd-44f6-9bce-592a50c0d8db.png)

But if I tried using decreasing the number of values specified in the array then it is working perfectly. Can anyone assist me with why this issue is getting when a number of keys are more?

![image](https://user-images.githubusercontent.com/46279781/171565146-d5d42895-6d92-4d36-b5e4-86766f1eb2c1.png)

### Steps to Reproduce

Create one migration and try to add an index on more than 6 columns using a single array like the below code.
```
$this->forge->addKey('id', true);
$indexKeys = array('company_id', 'recurring_id', 'company', 'pickup_date', 'department', 'driver_id', 'no_of_box', 'delivery_count', 'request_id');
$this->forge->addKey($indexKeys);
$attributes = array('ENGINE' => 'InnoDB');
$this->forge->createTable('schedules', true, $attributes);
```

### Expected Output

It should migrate the migration without any error. Like below.
![image](https://user-images.githubusercontent.com/46279781/171565677-16fdb375-02c1-4133-9dfa-1edf01d302e3.png).

Migrations are working with a maximum of 6 Keys. As soon as I have added more values to the array it stops working.

**Comment by iRedds** [comment]
The addKey() method is designed for one key.
All fields specified in the array are one key.
The key name is generated by concatenating the names of the specified fields.

The error you mentioned is generated by mysql.

To create an index for each field, you need to call the addKey() method on each field.

**Comment by DhPandya** [comment]
> The addKey() method is designed for one key. All fields specified in the array are one key. The key name is generated by concatenating the names of the specified fields.
> 
> The error you mentioned is generated by mysql.
> 
> To create an index for each field, you need to call the addKey() method on each field.

Okay, I got the point. But why it is happening after increasing the array values above 7 keys? It is working well upon 6 array values as I have shown in the image attached to the description. In my case,, I need to add keys to more than 6 Columns.

**Comment by kenjis** [comment]
See https://codeigniter4.github.io/CodeIgniter4/dbmgmt/forge.html#adding-keys

> But why it is happening after increasing the array values to 7 keys & above? 

Because the key name got to be too long.
See https://dev.mysql.com/doc/refman/8.0/en/identifier-length.html

**Comment by DhPandya** [comment]
> See https://codeigniter4.github.io/CodeIgniter4/dbmgmt/forge.html#adding-keys
> 
> > But why it is happening after increasing the array values to 7 keys & above?
> 
> Because the key name got to be too long. See https://dev.mysql.com/doc/refman/8.0/en/identifier-length.html

Now I got the point. Thank you for replying to me & assist with the issue. Marking isssue as a close.
