### ISSUE TITLE
set "$supportedLocales " in .env file

### ISSUE THREAD

**Issue by nicojmb** [codeigniter4/CodeIgniter4#6070]
Hi, 

It's possible to set "$supportedLocales " in .env?

I have not seen how to put an array there, I had to modify the Config\App.php file and I don't like it :(

**Comment by paulbalandan** [comment]
Currently there is no way except to set the first value of the `$supportedLocales` array.
```php
// in Config\App
public $supportedLocales = ['en'];

// in .env
app.supportedLocales.0 = fr
// => will change to 'fr'
```

**Comment by paulbalandan** [comment]
However, `app.supportedLocales.1 = ja` will not set the second value to `ja`

**Comment by iRedds** [comment]
Tell me, for what?
Do you have different locales for development, testing and production?

**Comment by nicojmb** [comment]
> Tell me, for what? Do you have different locales for development, testing and production?

No, i've the same locales for dev, test and prod.

The problem is that all my apps are multilingual and I need to set the variable "$supportedLocales" to ['es', 'en', 'de', 'fr','ru'. 'sw" in every app.

Personally, I don't like to touch anything inside "app" so that I can update the application more easily.

One solution is to put all locales as default value in codeigniter, what do you think?

**Comment by iRedds** [comment]
.env is the environment settings. Because development, testing and production may require different settings for the database, local and third-party services.
I don't see the point in specifying locales if you use the same setting for all environments.

**This is actually bad advice.**
```
Thank gods that CI4 uses classes as configs (actually, no. it's bullshit).
You can create a constructor in the App config and read and parse the value from .env
```

**Comment by kenjis** [comment]
Ref,  #5526

**Comment by kenjis** [comment]
Personally, I think setting locales in the config file is correct, because a developer does not need to change the site locales.

> Personally, I don't like to touch anything inside "app" so that I can update the application more easily.

If we follow this theory, we don't need any config files in `app/Config/`.
If you use https://github.com/tattersoftware/codeigniter4-patches , updating non-`system/` folders is very easy.

And, I don't even want to add more functionality to CI4's env parser, which already has many own functionality.
We should carefully consider whether it is worth supporting arrays.

**Comment by lakolmena** [comment]
for whatever reason it doesn't work with the single quote, use double quotes instead
`app.supportedLocales = ["es","en"]`

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/CodeIgniter4/pull/5526#issuecomment-1003800580

We can override the existing config item only.

**Comment by kenjis** [comment]
This issue is closed as there seems to be no need for it.

If necessary, open a new issue.
