### ISSUE TITLE
Bug: Spark command not working after upgrade to 4.2.0

### ISSUE THREAD

**Issue by ageir** [codeigniter4/CodeIgniter4#6078]
### PHP Version

8.1

### CodeIgniter4 Version

4.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli

### What happened?

Running spark command from example in documentation no longer works with CI 4.2. 
I get the following error:
`PHP Fatal error:  Uncaught TypeError: CodeIgniter\CLI\Console::__construct(): Argument #1 ($app) must be of type CodeIgniter\CodeIgniter, int given, called in /home/user/code/ci4/spark on line 48 and defined in /home/user/code/ci4/vendor/codeigniter4/framework/system/CLI/Console.php:29
Stack trace:
#0 /home/user/code/ci4/spark(48): CodeIgniter\CLI\Console->__construct()
#1 {main}
  thrown in /home/user/code/ci4/vendor/codeigniter4/framework/system/CLI/Console.php on line 29`

If I downgrade to 4.1.9 it will work again.

### Steps to Reproduce

```php
<?php

namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;

class AppInfo extends BaseCommand
{
    protected $group       = 'App';
    protected $name        = 'app:info';
    protected $description = 'App info';

    public function run(array $params)
    {
        CLI::write('PHP Version: ' . CLI::color(PHP_VERSION, 'yellow'));
        CLI::write('CI Version: ' . CLI::color(\CodeIgniter\CodeIgniter::CI_VERSION, 'yellow'));
        CLI::write('APPPATH: ' . CLI::color(APPPATH, 'yellow'));
        CLI::write('SYSTEMPATH: ' . CLI::color(SYSTEMPATH, 'yellow'));
        CLI::write('ROOTPATH: ' . CLI::color(ROOTPATH, 'yellow'));
        CLI::write('Included files: ' . CLI::color(count(get_included_files()), 'yellow'));
    }
}
```

Using code from the documentation
and run: ` php spark app:info`
`php spark list` is also not working.

### Expected Output

The spark commands should work as intended in the documentation.

**Comment by kenjis** [comment]
See https://codeigniter4.github.io/userguide/installation/upgrade_420.html#index-php-and-spark

**Comment by kenjis** [comment]
@ageir Did you solve the problem?
If okay, please close this issue.

**Comment by ageir** [comment]
Yes. Missed that. Thanks
