### ISSUE TITLE
Bug: doAfterUpdate Not sent ID when use update() with builder

### ISSUE THREAD

**Issue by danuri** [codeigniter4/CodeIgniter4#6093]
### PHP Version

7.4, 8.1

### CodeIgniter4 Version

4.2.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

SqlSrv

### What happened?

Update with query builder not send an ID to doAfterUpdate in Model.

### Steps to Reproduce

```php
$model = new UsulModel();
$model 
        ->where(['ID' => $id,'OTHERID' => $oid])
        ->set(['STATUS' => 1])
        ->update();
```
And this what happened:

```
Array
(
    [id] => 
    [data] => Array
        (
            [STATUS] => 1
            [UPDATED_AT] => 2022-06-07 17:56:37
        )

    [result] => 1
)
```

### Expected Output

if use simple update:

`$model->update($id,['STATUS' => 1]);`

There is ID
```
Array
(
    [id] => Array
        (
            [0] => 33
        )

    [data] => Array
        (
            [STATUS] => 1
            [UPDATED_AT] => 2022-06-07 17:58:30
        )

    [result] => 1
)
```

### Anything else?

How to get ID from update with query builder ?

**Comment by kenjis** [comment]
`CodeIgniter\Model` is kind of wrapper for Query Builder.
If you want to use `CodeIgniter\Model` features, you need to use `CodeIgniter\Model`'s methods.

```php
$model = new UsulModel();
$model 
        ->where(['OTHERID' => $oid])
        ->set(['STATUS' => 1])
        ->update($id);
```
