### ISSUE TITLE
Bug: setDefaultMethod does not work.

### ISSUE THREAD

**Issue by tomomo** [codeigniter4/CodeIgniter4#6122]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.0, develop

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### What happened?

setDefaultController does not work properly. Is there anything missing?
No matter what you specify, it is suitable for "home".

https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html

### Steps to Reproduce

app/Config/Routes.php
````
$routes->setDefaultController('Home');
  ↓
$routes->setDefaultController('Welcome');
````

### Expected Output

```
# php spark routes

+--------+--------+------------------------------------------+----------------+---------------+
| Method | Route  | Handler                                  | Before Filters | After Filters |
+--------+--------+------------------------------------------+----------------+---------------+
| GET    | /      | \App\Controllers\Home::index             | csrf           | toolbar       |
| CLI    | ci(.*) | \CodeIgniter\CLI\CommandRunner::index/$1 |                |               |
+--------+--------+------------------------------------------+----------------+---------------+
````

**Comment by kenjis** [comment]
What do you want to do?
What's the exact problem?

The default controller is setting for auto routing.
No matter what you set the default controller, your defined routes do not change.

**Comment by tomomo** [comment]
Thank you for your answer.

It was my mistake. excuse me.
First, there was a lack of explanation that we had set up automatic routing.
```
$routes->setAutoRoute(true);
```

And no matter what I specified, such as "Welcome", it was skipped to "Home".
But, I noticed that the subsequent `$Routes->get('/','Home :: index');` is working.
I was able to get the expected result by deleting it.

**Comment by kenjis** [comment]
Glad to hear that it is not a bug.

If you use auto routing, migration to new improved auto routing is recommended.
https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#auto-routing-improved

**Comment by tomomo** [comment]
I am using the new automatic routing feature as soon as possible.

Thank you always!
