### ISSUE TITLE
Bug: common model function

### ISSUE THREAD

**Issue by gitHusband** [codeigniter4/CodeIgniter4#6123]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

macOS, Linux

### Which server did you use?

fpm-fcgi

### What happened?

I want to get model by using common model() function

`$companyModel = model("\Common\Models\CompanyModel");`

But it's not expected.

The $companyModel is instance of \App\Models\CompanyModel

I want it to be instance of \Common\Models\CompanyModel

### Steps to Reproduce

The $companyModel is instance of \App\Models\CompanyModel

### Expected Output

I want $companyModel to be instance of \Common\Models\CompanyModel

**Comment by kenjis** [comment]
You can't do it with `model()`. It is not a bug, is the specification.
See https://codeigniter4.github.io/CodeIgniter4/concepts/factories.html#example

Try:
```php
$companyModel = Factories::models('Common\Models\CompanyModel', ['preferApp' => false]);
```

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
