### ISSUE TITLE
Dev: Time::toDatabase()

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#6124]
See https://github.com/codeigniter4/CodeIgniter4/pull/6116#pullrequestreview-1005687856

**Comment by datamweb** [comment]
Yessssss:👍👍

**Comment by kenjis** [comment]
Closed by https://github.com/codeigniter4/CodeIgniter4/pull/6431

**Comment by kenjis** [comment]
This feature was removed by https://github.com/codeigniter4/CodeIgniter4/pull/6509
