### ISSUE TITLE
Bug: BaseBuilder increment/decrement do not reset state after a query.

### ISSUE THREAD

**Issue by iRedds** [codeigniter4/CodeIgniter4#6145]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

If you call several increment/decrement in a row, then the state is not reset.

### Steps to Reproduce

```php
$db = db_connect()->table('table');

$db->where('id', 1)->increment('value'); // UPDATE `table` SET `value` = `value` + 1 WHERE `id` = 1;
$db->where('id', 2)->increment('value'); // UPDATE `table` SET `value` = `value` + 1 WHERE `id` = 1 AND `id` = 2;
```

**Comment by kenjis** [comment]
Fixed by #6146
