### ISSUE TITLE
Autoroute (legacy) - blocks calls to controllers referenced in routes->add function

### ISSUE THREAD

**Issue by devorama** [codeigniter4/CodeIgniter4#6148]
### PHP Version

8.0

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

mysql8

### What happened?

in version 4.1.5 when you added a route in routes file
for example

 $routes->add('testroute/(:any)', 'Testcontroller::view/$1');

then I could make calls to 
testroute
and 
Testcontroller
directly without issue

but now with 4.2.x
all calls not 
Testcontroller
is now in the $protectedControllers variable due to it passing all routes to the first variable in the contructor. 

![image](https://user-images.githubusercontent.com/33496470/174338497-1a9076a7-62c0-4e7b-b353-3176e1d848fe.png)

Basically I did not read in the docs or understand from usage in the past that adding a route would block the controller from direct access ,as I need it to have direct access sometimes in this case it is a alternative view to the same controller thanks to the link, but now the alternative view is disabling the main controller

### Steps to Reproduce

create any controller
add 2 methods one called 
mainview
and
alternativeview
add a route 
 $routes->add('testroute/(:any)', 'Testcontroller::alternativeview/$1');

you should be able to access the view via 
<server>/testroute/
but all calls to
<server>/testcontroller/mainview
is now disabled

### Expected Output

controller referenced in views to still work

### Anything else?

I will look at alternative code or ways around this, but just wanted to hightlight as a issue of concern

**Comment by devorama** [comment]
Checked older code
and past forloop only ran for the cli routes not all routes as current one, will adapt current loop on my side for cli only and test

![image](https://user-images.githubusercontent.com/33496470/174341363-7d51bc44-e770-4fe6-ba33-f11fbeaabb8f.png)

Note comment in now code also indicates it meant to work as old for cli routes only, thus should be save todo it for that only
![image](https://user-images.githubusercontent.com/33496470/174341561-0935e012-5b20-4e6f-81e1-d3f53e4e8916.png)

**Comment by devorama** [comment]
I can confirm only cli entry is the expected one, not my one added via ->add method
![image](https://user-images.githubusercontent.com/33496470/174345427-ce4bc8ba-83db-4c19-b540-6ec414baf0db.png)

**Comment by devorama** [comment]
seems it is this line in getRoutes that make the ->add routes part of cli
I will try to register all other methods one by one to get past this issue then

![image](https://user-images.githubusercontent.com/33496470/174345633-7f2aa907-40d4-4212-90be-66d2a7eb82d2.png)

**Comment by devorama** [comment]
Alternative config works, will go with that. thank you

**Comment by kenjis** [comment]
@devorama You don't upload screenshot of text file. It is difficult to read, can' copy the text.
It is not good practice. You can just paste the text or GitHub provides how to link source code easily.

https://github.com/codeigniter4/CodeIgniter4/blob/b3ebf5bd6bbf5c28618a0d8d62f8994c0d91dda8/system/Router/AutoRouter.php#L130-L142

**Comment by kenjis** [comment]
Thank you for reporting.

It seems this is because of the bug fix.

> To prevent unexpected access from the web browser, if a controller is added to a cli route ($routes->cli()), all methods of that controller are no longer accessible via auto-routing.
https://codeigniter4.github.io/CodeIgniter4/changelogs/v4.2.0.html#behavior-changes

Anyway, `$routes->add()` is very dangerous and you should not use it.
Replacing it with HTTP verb method is good practice.
