### ISSUE TITLE
Bug: SQLite3 $model->getIndexData('tablename') Error

### ISSUE THREAD

**Issue by sclubricants** [codeigniter4/CodeIgniter4#6151]
### PHP Version

8.0

### CodeIgniter4 Version

4.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

SQLite3

### What happened?

Calling $model->getIndexData('tablename'); causes error in SQLite3.

Call to a member function escapeString() on bool

SYSTEMPATH\Database\SQLite3\Connection.php at line 154

```php
149     /**
150      * Platform-dependant string escape
151      */
152     protected function _escapeString(string $str): string
153     {
154         return $this->connID->escapeString($str);
155     }
```

For some reason the connID is not initialized.

### Steps to Reproduce

Create controller and model with an existing table in sqlite3

Call $model->getIndexData('tablename');

### Expected Output

expected results of table index data

### Anything else?

No problems running queries but this call isn't working.

**Comment by kenjis** [comment]
Thank you for reporting.

I sent a PR #6152
