### ISSUE TITLE
Bug: Validation/FileRules/is_image: mb_strpos deprecation bug

### ISSUE THREAD

**Issue by Erdmanny** [codeigniter4/CodeIgniter4#6155]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

![CI4_deprecation_bug](https://user-images.githubusercontent.com/50449416/174458228-26976e47-8ff2-48d0-b025-4998453b76de.png)

mb_strpos does not allow $haystack to be null in php version 8.1.5

'Mimes::guessTypeFromExtension($file->getExtension());' returns null for files of type 'xcf' and thereby 'mb_strpos()' throws an error.

### Steps to Reproduce

Use 'is_image' as part of a form validation and input a 'xcf' file.

### Expected Output

'mb_strpos()' should not throw an error, so the function returns true or false.

**Comment by kenjis** [comment]
Thank you for reporting.

I sent a PR #6157
