### ISSUE TITLE
Adding dynamic properties by Registrars will be deprecated on PHP 8.2

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#6162]
Registrars can add dynamic properties now.

But the sample code in the user guide will cause the error on PHP 8.2.
https://codeigniter4.github.io/CodeIgniter4/general/configuration.html#explicit-registrars

```console
bash-3.2$ php public/index.php 


[ErrorException]

Creation of dynamic property Config\MySalesConfig::$actual is deprecated

at SYSTEMPATH/Config/BaseConfig.php:211

Backtrace:
  1    SYSTEMPATH/Config/BaseConfig.php:211
       CodeIgniter\Debug\Exceptions()->errorHandler(8192, 'Creation of dynamic property Config\\MySalesConfig::$actual is deprecated', '.../CodeIgniter4/system/Config/BaseConfig.php', 211)

  2    SYSTEMPATH/Config/BaseConfig.php:64
       CodeIgniter\Config\BaseConfig()->registerProperties()

  3    APPPATH/Controllers/Home.php:9
       CodeIgniter\Config\BaseConfig()->__construct()

  4    SYSTEMPATH/CodeIgniter.php:896
       App\Controllers\Home()->index()

  5    SYSTEMPATH/CodeIgniter.php:466
       CodeIgniter\CodeIgniter()->runController(Object(App\Controllers\Home))

  6    SYSTEMPATH/CodeIgniter.php:349
       CodeIgniter\CodeIgniter()->handleRequest(null, Object(Config\Cache), false)

  7    FCPATH/index.php:55
       CodeIgniter\CodeIgniter()->run()
```

```console
bash-3.2$ php -v
PHP 8.2.0-dev (cli) (built: Jun 20 2022 00:32:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.0-dev, Copyright (c), by Zend Technologies
```

References:
- https://wiki.php.net/rfc/deprecate_dynamic_properties
- #6160

**Comment by iRedds** [comment]
#[AllowDynamicProperties]

**Comment by kenjis** [comment]
The issue is we will continue to use Dynamic Properties that PHP will denies by default or not.

**Comment by iRedds** [comment]
Why not use the Entity::$attributes case?

**Comment by kenjis** [comment]
> Why not use the Entity::$attributes case?

What do you mean?
Do you mean that we should change it to use magic properties?

**Comment by kenjis** [comment]
@iRedds Okay, thanks for explanation. It is an option.

It seems there are three options.

1. Use `#[AllowDynamicProperties]`
2. Use magic properties
3. Do not support dynamic property injection

I think 3. is simple and preferable.

I did not know that Registrars can add dynamic properties.
Not documented until recently. See #6160

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/CodeIgniter4/pull/6172#issuecomment-1165468080

**Comment by kenjis** [comment]
We do not recommend the use of dynamic properties in Registrar.
