### ISSUE TITLE
Bug: send emails

### ISSUE THREAD

**Issue by DevLogsan** [codeigniter4/CodeIgniter4#6217]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.24

### Unable to send mails with Codeigniter 4

I want to send emails with a google email address but now the "Less secure app access" parameter is disabled and impossible to re-enable it.

https://support.google.com/accounts/answer/6010255?hl=en&authuser=1&visit_id=637922832282988134-2476474830&p=less-secure-apps&rd=1

### Steps to Reproduce

Simply reproduce as the example filling in with it's data.

https://codeigniter.com/user_guide/libraries/email.html?highlight=send#sending-email

and fill in correctly `app/Config/Email.php`

### Expected Output

no mail sent

**Comment by kenjis** [comment]
Can you show us the exact steps to reproduce especially `app/Config/Email.php` config?

**Comment by kenjis** [comment]
As you show the URL, Google no longer supports "username and password" authentication.
So you can't use your password to send mails.

> To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.
https://support.google.com/accounts/answer/6010255?hl=en&authuser=1&visit_id=637922832282988134-2476474830&p=less-secure-apps&rd=1

**Comment by DevLogsan** [comment]
> As you show the URL, Google no longer supports "username and password" authentication. So you can't use your password to send mails.
> 
> > To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.
> > https://support.google.com/accounts/answer/6010255?hl=en&authuser=1&visit_id=637922832282988134-2476474830&p=less-secure-apps&rd=1

Yes exactly, but is there another way to send emails with codeigniter 4 that could work? I couldn't find help with that. Otherwise, I should use a different email than Gmail

**Comment by DevLogsan** [comment]
> Can you show us the exact steps to reproduce especially `app/Config/Email.php` config?

`public $protocol = 'smtp';`
`public $SMTPHost = 'smtp.googlemail.com';` (I also tested `public $SMTPHost = 'smtp.gmail.com';`)
`public $SMTPUser = '*********@gmail.com';` _of course I tested with my identifiers.._
`public $SMTPPass = '***************';`
`public $SMTPPort = 465;`
`public $SMTPCrypto = 'ssl';`
`public $mailType = 'html';`

**Comment by kenjis** [comment]
Create an [App Password](https://support.google.com/accounts/answer/185833) and use it.

```
public $SMTPPass = '***************';
```

**Comment by DevLogsan** [comment]
it works, thank you soo much!
