### ISSUE TITLE
Bug: The Validation::run() method does not match the ValidationInterface.

### ISSUE THREAD

**Issue by iRedds** [codeigniter4/CodeIgniter4#6224]
### CodeIgniter4 Version

4.2.1

### What happened?

Missing $dbGroup argument.

https://github.com/codeigniter4/CodeIgniter4/blob/7439b6ec5134492bbbf466d99bc206aa883a4b54/system/Validation/Validation.php#L109

https://github.com/codeigniter4/CodeIgniter4/blob/7439b6ec5134492bbbf466d99bc206aa883a4b54/system/Validation/ValidationInterface.php#L28

**Comment by kenjis** [comment]
It does not seem to be an error.
https://3v4l.org/U59Qp

**Comment by kenjis** [comment]
Do you have any specific problems on this mismatch?

**Comment by iRedds** [comment]
No problem. But it seems to me that the meaning in the declaration of the interface is lost if the class that implements it is different.

**Comment by kenjis** [comment]
In this case, it seems that updating the `run()` method in the `ValidationInterface` in version 5 would solve the problem.

Or try to change the interface in `4.3`?

**Comment by iRedds** [comment]
I don't know how to get out of this situation. I thought that the team would find the optimal solution.

**Comment by kenjis** [comment]
Closed by 6253
