### ISSUE TITLE
Bug: 'Special' characters in a symbolic link cause an error "Fatal error: Uncaught Error: Class 'App\Config' not found"

### ISSUE THREAD

**Issue by R-W-C** [codeigniter4/CodeIgniter4#6236]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 8.0.21

### What happened?

Error message "Fatal error: Uncaught Error: Class 'App\Config' not found" on fresh install

### Steps to Reproduce

Just install using composer in a folder containing a symbolic link in the path containing 'special characters'.

In my case the path was D:\Dropbox (Dubbel 16). 

Removing the brackets solved the issue, but is in fact a workaround.

### Expected Output

See the welcome page

### Anything else?

Bug has been reported on StackOverflow: https://stackoverflow.com/a/72825733/760777 with the possible workaround.

The problem is probly caused by using the function file_exists. It returns FALSE when containing a symbolic link with certain characters.

**Comment by datamweb** [comment]
See #6192 .

**Comment by kenjis** [comment]
Thank you for reporting, but as datamweb pointed out, this is not a bug.

See the note:
https://codeigniter4.github.io/CodeIgniter4/installation/installing_composer.html#installation-set-up
