### ISSUE TITLE
Bug: php spark migrate:status all entries appear twice

### ISSUE THREAD

**Issue by tzalexander** [codeigniter4/CodeIgniter4#6242]
### PHP Version

8.0

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli

### Database

Aurora

### What happened?

All entries in the status list (php spark migrate:status) appear twice.
The entire list is appended again at the end.

### Steps to Reproduce

php spark migrate:status

### Expected Output

expected List:
filename: A B C

got List:
filename: A B C A B C

**Comment by kenjis** [comment]
Can you show your composer.json autoload.psr4?
https://github.com/codeigniter4/CodeIgniter4/blob/ba7d36c2992150049df4c2f1d18b3fc31494d4f0/composer.json#L42-L49

**Comment by tzalexander** [comment]
sure:
`"autoload": {
    "psr-4": {
      "App\\": "app",
      "Config\\": "app/Config"
    },
    "exclude-from-classmap": [
      "**/Database/Migrations/**"
    ]
  },`

**Comment by kenjis** [comment]
Thank you.

Remove `"App\\"` and `"Config\\"` namespaces. They are defined CI4 config file and not necessary.
See https://github.com/codeigniter4/appstarter/blob/11e4eeb652b41cdaaeda74753676af5a2acb107e/composer.json#L19-L22

**Comment by tzalexander** [comment]
Thank you!
And append "CodeIgniter\\": "system/"  instead?

**Comment by kenjis** [comment]
No.
Don't forget to run `composer dump-autoload`.
