### ISSUE TITLE
Bug: `spark routes` show error when using custom placeholder (regex)

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#6276]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MariaDB

### What happened?

when run `php spark routes`
show 404 error like:
![image](https://user-images.githubusercontent.com/2387514/179688692-4e87e6df-8928-4414-83ae-5299879244d9.png)

### Steps to Reproduce

add route
```php
// app/Config/Routes.php
$routes->get('detail/([a-z0-9]{40})', 'User::detail/$1');
// or add using custom placeholder

$routes->addPlaceholder('uid', '[a-z0-9]{40}');
$routes->get('detail/(:uid)', 'User::detail/$1');
```
then run 
```bash
php spark routes
```

### Expected Output

show route lists as expected

**Comment by kenjis** [comment]
Thanks for reporting.
I sent a PR #6279
