### ISSUE TITLE
Bug: Can not use $modelObject->save($entityObject) in ver.4.2.1

### ISSUE THREAD

**Issue by cwwjsyc** [codeigniter4/CodeIgniter4#6280]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.2,

### What happened?

Can not user $modelObject->save($entityObject) in ver.4.2.1
report error like:
```
mysqli_sql_exception #1062
Duplicate entry '1' for key 'PRIMARY' 

```

### Steps to Reproduce

Defined Model:
```php
<?php

namespace App\Models;

use CodeIgniter\Model;

class UserModel extends Model
{
    protected $table = 'user';
    protected $primaryKey = 'id';
    protected $useAutoIncrement = true;
    protected $returnType = \App\Entities\UserEntity::class;
    protected $dateFormat = 'int';
    protected $useTimestamps = true;
    protected $allowedFields = ['id', 'name', 'hit'];
    protected $useSoftDeletes = true;
    protected $createdField = 'created_time';
    protected $updatedField = 'updated_time';
    protected $deletedField = 'deleted_time';
}
```
Define Entity:
```php
<?php
namespace App\Entities;
use CodeIgniter\Entity\Entity;

class UserEntity extends Entity
{
	protected $datamap = [
        'id' => 'id',
        'createdTime' => 'created_time',
        'updateTime' => 'updated_time',
        'deletedTime' => 'deleted_time',
        'userName' => 'name',
        'userHit' => 'hit',
    ];
    protected $casts = [
        'id' => 'integer',
        'created_time' => '?integer',
        'updated_time' => '?integer',
        'deleted_time' => '?integer',
        'name' => '?string',
        'hit' => '?integer',
    ];	
}
```
In Controller Class ，Define Function

```php
public function index()
    {
    	$this->userModel = model('App\Models\UserModel', true, $db);
    	$user = $this->userModel->find(1);
    	$user->userHit += 5;
    	$this->userModel->save($user);
        return view('welcome_message');
    }
```

### Expected Output

It can not work in 4.2.1 ,but can run well in 4.1.19

**Comment by cwwjsyc** [comment]
Delete 'id' from allowedFields array. It seems  not update ,it work Insert.
![微信截图_20220719175852](https://user-images.githubusercontent.com/26668815/179723881-45b4fbf8-245d-46bb-a45a-559d4aab25a3.png)

**Comment by cwwjsyc** [comment]
`The $primaryKey field should never be an allowed field.`  is not a good way.
Because primaryKey can snowflakeId,  a string or others. it not alwasy use a  auto Increment Int number.

> Remove `id` from the allowedFields property. https://codeigniter.com/user_guide/models/model.html#allowedfields

**Comment by kenjis** [comment]
Your model has `useAutoIncrement` true.
You should configure the table with auto Increment.

Remove `'id' => 'id',` in `$datamap`.
