### ISSUE TITLE
Bug: Call to undefined function form_open() 

### ISSUE THREAD

**Issue by hamzazafeer** [codeigniter4/CodeIgniter4#6287]
### PHP Version

7.3

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

Mysql

### What happened?

Call to undefined function form_open() in CI 4

### Steps to Reproduce

By using `helper("form");` in function them form properly loads, but using autoload method it is not working it says _Call to undefined function form_open() in CI 4_

### Expected Output

it should load proper form 

### Anything else?

https://stackoverflow.com/questions/73089822/call-to-undefined-function-form-open-in-ci-4

**Comment by kenjis** [comment]
v4.2 requires PHP 7.4.
https://codeigniter4.github.io/CodeIgniter4/changelogs/v4.2.0.html#highlights

**Comment by kenjis** [comment]
> but using autoload method it is not working it says Call to undefined function form_open() in CI 4

How do you autoload?
Can you show the controller code?

**Comment by hamzazafeer** [comment]
> > but using autoload method it is not working it says Call to undefined function form_open() in CI 4
> 
> How do you autoload? Can you show the controller code?

I am autoloading using BaseController.php file.

`protected $helpers = ["form"];`

**Comment by datamweb** [comment]
@hamzazafeer Hello, 

in file `app\Controllers\BaseController`, set the values as follows:
```php
protected $helpers = ['form'];
 ```
It is **very important** that `MyController` extends from `BaseController`.
Consider the example below (`app\Controllers\MyController`).
```php
<?php

namespace App\Controllers;

class MyController extends BaseController
{
    public function index()
    {
        echo form_open();
    }
}
```
If you do the above correctly, everything will work fine.

**Comment by hamzazafeer** [comment]
I am extending like this

      <?php namespace App\Controllers\admin;

              use CodeIgniter\Controller;
              use App\Models\UserModel;

              class LoginController extends Controller
           {

**Comment by kenjis** [comment]
@hamzazafeer You don't extend `BaseController`.

CodeIgniter\Controller's `$helpers` is empty array.
So your LoginController's `$helpers` is also empty array.

**Comment by paulbalandan** [comment]
You are defining the `$helpers` in your `BaseController` but your controllers are extending from `CodeIgniter\Controller`. You should instead extend from `BaseController`.
```diff
 <?php namespace App\Controllers\admin;

-use CodeIgniter\Controller;
+use App\Controllers\BaseController;
 use App\Models\UserModel;

-class LoginController extends Controller
+class LoginController extends BaseController
 {
```

**Comment by hamzazafeer** [comment]
```
<?php namespace App\Controllers\admin;

//use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\UserModel;

class LoginController extends BaseController
{
```

Now I extend like this, now it is not showing any error.  Thank You Every One
