### ISSUE TITLE
Bug: Cache with file can't delete by key

### ISSUE THREAD

**Issue by zsy78191** [codeigniter4/CodeIgniter4#6289]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

mysql 5.6

### What happened?

I use file cache to store some data and when I want to delete it by key, it returns false.
Then I found the system code, where I added the debug code, I found that the key was not the same as the cached filename.

### Steps to Reproduce

```php
$cache = \Config\Services::cache(); 
$cache->delete('email_invitation');
```

The key I used is `email_invitation` and cached file name is `cache_email_invitation`.
But look this img:

<img width="1111" alt="截屏2022-07-23 21 49 44" src="https://user-images.githubusercontent.com/3960959/180607971-f932edad-d30b-4a82-a408-5f15c2821f87.png">

delete key is not the real file name, key is `email_invitation`  but filename is `cache_email_invitation`.

### Expected Output

thanks for your work.

**Comment by zsy78191** [comment]
```
  $cache = \Config\Services::cache();
        if (!$cache->delete('email_invitation')) {
            $cache->delete('cache_email_invitation');
        }
```
I was forced to implement the code that deletes the cache this way, which I'm guessing is not what you expected.

**Comment by datamweb** [comment]
Hello @zsy78191و 
Set the value below
```php
public $prefix = 'cache_';
```
in file 
https://github.com/codeigniter4/CodeIgniter4/blob/3800c5d4f22bc30a44577418d9814f33f4a030d5/app/Config/Cache.php#L83

Now try as below 
```php
$cache = \Config\Services::cache();
$cache->delete('email_invitation');
```

There should be no problem.

**Comment by kenjis** [comment]
Can't reproduce.

```php
        $cache = \Config\Services::cache();
        $cache->save('email_invitation', 'test test', 3600);
```

It creates `writable/cache/email_invitation`, not `cache_email_invitation`.

```console
$ php spark cache:info

CodeIgniter v4.2.1 Command Line Tool - Server Time: 2022-07-23 17:53:50 UTC-05:00

+------------------+------------------------------------------+-----------+---------------------+
| Name             | Server Path                              | Size      | Date                |
+------------------+------------------------------------------+-----------+---------------------+
| index.html       | ROOTPATH/writable/cache/index.html       | 131 Bytes | 2022-05-17 04:06:38 |
| email_invitation | ROOTPATH/writable/cache/email_invitation | 74 Bytes  | 2022-07-23 22:52:22 |
+------------------+------------------------------------------+-----------+---------------------+
```

**Comment by zsy78191** [comment]
Sorry to trouble you, the cache method I used encapsulates a "cache_" at the beginning, I didn't notice this, thank you very much.
