### ISSUE TITLE
Bug: unable to add more than one file to FileCollection constructor

### ISSUE THREAD

**Issue by AnakinA1** [codeigniter4/CodeIgniter4#6290]
### PHP Version

7.3, 7.4, 8.0, 8.1

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

macOS, Linux

### Which server did you use?

fpm-fcgi

### Database

MariaDB 10.8

### What happened?

When I'm trying to create `FileCollection` object from 2 or more files paths (not directories), passed in the `__constructor`, only first file is added. Because in `FileCollection->add()` method uses `return $this->addFile($path);` instead of `$this->addFile($path);` that ends the execution of the `foreach` loop

### Steps to Reproduce

`$object = new FileCollection(['/path/to/file', '/path/to/other-file']);`

### Expected Output

An object containing all passed files

**Comment by datamweb** [comment]
Hi @AnakinA1 ,
Do you get what you need with the following code?

```php 
use CodeIgniter\Files\FileCollection;

$files = new FileCollection();

$file= APPPATH . 'Config/Auth.php';
$otherFile = APPPATH . 'Config/AuthGroups.php';

dd($files->addFiles([$file,$otherFile]));

```

**Comment by AnakinA1** [comment]
Hi, yes, but question is that inside docs mentioned that `FileCollection` allows to work with groups of files and by logic `__constructor` should provide an opportunity to add as many files/dirs as you want. And the current behavior is blocking the ability to add more than 1 file via the constructor, for no real reason

**Comment by kenjis** [comment]
I've confirmed this bug.
I sent a PR to fix it. See #6291

**Comment by AnakinA1** [comment]
Great, thank you!

**Comment by kenjis** [comment]
This bug has only been sent a PR and has not yet been fixed.
