### ISSUE TITLE
Bug: app can't running when created in a path directory with '@' character

### ISSUE THREAD

**Issue by ngekoding** [codeigniter4/CodeIgniter4#6299]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

When creating an app in a path directory contains '@' character, the app can't running.

Got this error messages:

`PHP Fatal error:  Uncaught Error: Class 'Config\App' not found in /Users/nur/Devs/WebProjects/works@ftugm/ci4-app/vendor/codeigniter4/framework/system/Config/Factories.php:126 ...`

My app installation in /Users/nur/Devs/WebProjects/**works@ftugm**/ci4-app (contains @)

But when I try to install in different directory (without @), the app running well.

### Steps to Reproduce

1. Create directory with `@` character e.g. `works@ftugm`
2. Create the codeigniter project inside that directory with composer

```sh
> cd works@ftugm
> composer create-project codeigniter4/appstarter ci4-app
```
3. Run the app

```sh
> cd ci4-app
> php spark serve
```
4. We get the errors

### Expected Output

The app running well.

**Comment by datamweb** [comment]
Hi @ngekoding ,
This is not a bug.

CodeIgniter autoloader does not allow special characters that are illegal in filenames on certain operating systems. The symbols that can be used are /, _, ., :, \ and space. So if you install CodeIgniter under the folder that contains the special characters like (, ), etc., CodeIgniter won’t work.

**more info see** : #6192 & [installation-set-up](https://codeigniter4.github.io/CodeIgniter4/installation/installing_composer.html#installation-set-up) 

**Thanks for the report,**

**Comment by ngekoding** [comment]
Thank you, just starting to use ci4 from ci3. So it is must be closed.
