### ISSUE TITLE
Bug: Parse error: syntax error, unexpected '_592_000' (T_STRING), expecting ')'

### ISSUE THREAD

**Issue by fre2mansur** [codeigniter4/CodeIgniter4#6305]
### PHP Version

7.3

### CodeIgniter4 Version

4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Parse error: syntax error, unexpected '_592_000' (T_STRING), expecting ')' in E:\MYPROJECTS\codignitor\app\Config\Constants.php on line 41

### Steps to Reproduce

php spark serve

### Expected Output

This will launch the server and you can now view your application in your browser at http://localhost:8080/.

### Anything else?

Im using VS CODE editor

**Comment by iRedds** [comment]
CI 4.2+ requires php version 7.4+

**Comment by kenjis** [comment]
Duplicate of #6306
