### ISSUE TITLE
Parse error: syntax error, unexpected '_536_000' (T_STRING), expecting ')'

### ISSUE THREAD

**Issue by fre2mansur** [codeigniter4/CodeIgniter4#6306]
### PHP Version

7.3

### CodeIgniter4 Version

4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Parse error: syntax error, unexpected '_536_000' (T_STRING), expecting ')' in E:\MYPROJECTS\codignitor\system\Common.php on line 480

### Steps to Reproduce

php spark serve

### Expected Output

This will launch the server and you can now view your application in your browser at http://localhost:8080/.

### Anything else?

![image](https://user-images.githubusercontent.com/8459473/181398575-92f1d3a5-bd3d-46f9-8f18-69c0218e2131.png)

**Comment by datamweb** [comment]
Hi, CodeIgniter Version(eg : 4.2.0)?

**Comment by kenjis** [comment]
CodeIgnier 4.2 requires PHP 7.4+
https://codeigniter4.github.io/CodeIgniter4/changelogs/v4.2.0.html#highlights

**Comment by paulbalandan** [comment]
Actually, this can be a bug in how we bootstrap the framework. The PHP version check happens in `index.php` and `spark` after the  `bootstrap.php` file is `require`d. In the bootstrap file, we `require` both `Common.php` and `Constants.php` which contains version-specific features (e.g. numeric literal separators).

I think if we can move the version check before requiring these files, then we can avoid these reports in the future.

**Comment by kenjis** [comment]
> Actually, this can be a bug in how we bootstrap the framework.

Exactly. The version check should be done in the very beginning of index.php and spark.

**Comment by fre2mansur** [comment]
I downloaded the latest version as zip.
It works fine when I  install from cmd composer so I don't think the php version is the issue.

**Comment by kenjis** [comment]
@fre2mansur Composer installs the version that works with your php.
Probably you have CI v4.1.9 on PHP 7.3.

Check the CI version:
```
$ php spark
```
