### ISSUE TITLE
Bug: CI_ENVIRONMENT bug in container

### ISSUE THREAD

**Issue by mozzar** [codeigniter4/CodeIgniter4#6313]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MariaDB

### What happened?

In the container the environment variable CI_ENVIRONMENT=development is set, even so codeigniter does not use development.php but production.php (As if production was set). I think it is a matter of replacing _ with . (Somewhere in the code is hardcoded taking of CI_ENVIRONMENT instead of CI.ENVIRONMENT or something like that - namespace separator https://www.codeigniter.com/user_guide/general/configuration.html).

### Steps to Reproduce

setup CI_ENVIRONMENT in container environment variables without .env or env file and check whether the errors that appear will have a stacktrace or whether the "whoops" production page will appear

### Expected Output

It should use the development environment variable when it's set on the container and now it doesn't detect it.

### Anything else?

nope.

**Comment by kenjis** [comment]
Thank you for reporting.

What is the container? and how did you set the environment variable without .env or env file?

Probably #6257 is related.

**Comment by kenjis** [comment]
Can you get `$_ENV['CI_ENVIRONMENT']`?

**Comment by mozzar** [comment]
> Thank you for reporting.
> 
> What is the container? and how did you set the environment variable without .env or env file?
> 
> Probably #6257 is related.

is probably related, I will check later 
https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/

**Comment by kenjis** [comment]
#6257 was merged into `develop` branch, and it will be included in v4.2.2.

**Comment by tangix** [comment]
Could this solve/affect #3992 ?

**Comment by kenjis** [comment]
This is the case that does not use `.env` file.

**Comment by kenjis** [comment]
@tangix #3992 is solved and closed. If you have an issue, [create another issue](https://github.com/codeigniter4/CodeIgniter4/issues/new?assignees=&labels=bug&template=bug_report.yml&title=Bug%3A+).
