### ISSUE TITLE
Bug: CI Debug not working

### ISSUE THREAD

**Issue by fre2mansur** [codeigniter4/CodeIgniter4#6339]
### PHP Version

7.3

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

mysql

### What happened?

Php, database, or any error it's not throwing the error or CI Debug instead it's showing the Whoops! page error.

### Steps to Reproduce

install using composer check do some error

### Expected Output

CI debug should appear

### Anything else?

.env 
CI_ENVIRONMENT = development 

app/boot/development.php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

Am I missing something?

**Comment by kenjis** [comment]
Cannot reproduce it.

Install CI 4.1.9 appstarter.

Prepare `.env`.

```diff
--- env	2022-01-04 09:59:30.000000000 +0900
+++ .env	2022-08-04 11:43:36.000000000 +0900
@@ -14,7 +14,7 @@
 # ENVIRONMENT
 #--------------------------------------------------------------------
 
-# CI_ENVIRONMENT = production
+CI_ENVIRONMENT = development
 
 #--------------------------------------------------------------------
 # APP
```

Change `Home.php`.

```diff
--- a/app/Controllers/Home.php
+++ b/app/Controllers/Home.php
@@ -6,6 +6,6 @@ class Home extends BaseController
 {
     public function index()
     {
-        return view('welcome_message');
+        eturn view('welcome_message');
     }
 }
```

Run `php spark serve`.
Navigate to http://localhost:8080/.

![Screenshot 2022-08-04 11 48 30](https://user-images.githubusercontent.com/87955/182752371-938f2b31-f9fb-456b-b245-bf2b4edae364.png)

**Comment by fre2mansur** [comment]
My bad I haven't renamed the env to .env so it was in the production mode.

**Comment by kenjis** [comment]
@fre2mansur Don't worry! Nobody's perfect.
