### ISSUE TITLE
DOCS: about Spark & public/index.php

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#6346]
### What happened?

Content Changes in spark & index.php are not included.
see: https://codeigniter4.github.io/userguide/installation/upgrade_422.html

**Comment by kenjis** [comment]
These are not Mandatory File Changes, but yes they are updated and missing in Project Files.

**Comment by kenjis** [comment]
I sent a PR: #6347

**Comment by MGatner** [comment]
Thanks @totoprayogo1916. I forgot to include them in my `git diff` so only **app/** was posted. Thanks to @kenjis for the fast response!
