### ISSUE TITLE
Bug: Email class may not log an error when it fails to send

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#6350]
CodeIgniter4 Version: 4.2.2

See https://github.com/codeigniter4/shield/issues/330#issuecomment-1206366593 and https://github.com/codeigniter4/shield/pull/345

**Comment by ddevsr** [comment]
In my environtment windows successfull send with smtp gmail (port 465 & ssl), But in linux server fail (tls://smtp.google.com Unreachable network).

**Comment by kenjis** [comment]
This issue is about error logging.

*Unreachable network* is the problem of the network, not in the framework.
