### ISSUE TITLE
Bug:  Uncaught ErrorException: print_r(): Property access is not allowed yet

### ISSUE THREAD

**Issue by fre2mansur** [codeigniter4/CodeIgniter4#6376]
### PHP Version

7.3

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

mysql

### What happened?

I was trying to test the custom DB connections, I want to handle the invalid DB connection but it's throwing me the below message.

```
ErrorException #1
Uncaught ErrorException: print_r(): Property access is not allowed yet in 
APPPATH\Views\errors\html\error_exception.php at line 96
```

### Steps to Reproduce

My Connection Model
```php
 protected $beforeInsert   = ['testConnection'];

    protected function testConnection(array $data)
    {
        $custom = [
            'DSN'      => '',
            'hostname' => $data['data']['host'],
            'username' => $data['data']['username'],
            'password' => $data['data']['password'],
            'database' => '',
            'DBDriver' => 'MySQLi',
            'DBPrefix' => '',
            'pConnect' => false,
            'DBDebug'  => (ENVIRONMENT !== 'production'),
            'charset'  => 'utf8',
            'DBCollat' => 'utf8_general_ci',
            'swapPre'  => '',
            'encrypt'  => false,
            'compress' => false,
            'strictOn' => false,
            'failover' => [],
            'port'     => $data['data']['port'],
        ];

        try {
            $forge = \Config\Database::forge($custom);
            $forge->createDatabase('my_db_2');  //breaks here
        }  catch(\Exception $e) {
           exit($e->getMessage()); //it supposed to break here
        }
        die();
        return $data;
    }
```

### Expected Output

To handle the error on catch mode

### Anything else?

I'm not sure if is this bug or if am i missing something.

![image](https://user-images.githubusercontent.com/8459473/184464249-9edcf434-724c-4175-8683-cf5562332f55.png)

**Comment by kenjis** [comment]
Upgrade to the latest version.
https://github.com/codeigniter4/CodeIgniter4/releases
