### ISSUE TITLE
Bug: increment/decrement not working in Cache RedisHandler; method "remember" not listed in CacheInterface

### ISSUE THREAD

**Issue by tzalexander** [codeigniter4/CodeIgniter4#6385]
### PHP Version

8.0

### CodeIgniter4 Version

4.2.4

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

MySQL

### What happened?

The methods increment and decrement use the wrong php redis hashKey. Currently "data" is used - it should be "__ci_value" if I am right.

The method "remember" is not listed CacheInterface (system/Cache/) and is not suggested. See docs https://www.codeigniter.com/user_guide/libraries/caching.html.

Thank you

### Steps to Reproduce

```php
cache()->save('test', 5);  // test = 5
cache()->decrement('test', 2);

cache()->get('test'); // test = 5; it should be 3
```

### Expected Output

3 instead of 5

**Comment by paulbalandan** [comment]
> The methods increment and decrement use the wrong php redis hashKey. Currently "data" is used - it should be "__ci_value" if I am right.

Please open a PR with your changes so that we can discuss further. Also don't forget to add unit tests.

> The method "remember" is not listed CacheInterface (system/Cache/) and is not suggested. See docs https://www.codeigniter.com/user_guide/libraries/caching.html.

This is intended. The "remember" method came after `CacheInterface` was finalized, so adding it would break custom implementations of the interface. It can be added to the interface though in a major version bump.

**Comment by paulbalandan** [comment]
It seems the increment and decrement functions are untested.
https://github.com/codeigniter4/CodeIgniter4/blob/57385ea1bf64fb31c235f9c15eff4d39a69cbbc1/tests/system/Cache/Handlers/RedisHandlerTest.php#L169-L176
