### ISSUE TITLE
The query statement “select... for update”, how do I do that? Is there a method?

### ISSUE THREAD

**Issue by houjl04** [codeigniter4/CodeIgniter4#6387]
The query statement “select... for update”, how do I do that? Is there a method?

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

You can use `query()` method:
https://codeigniter4.github.io/CodeIgniter4/database/queries.html#regular-queries
