### ISSUE TITLE
Bug: Database Connection ID Is Empty

### ISSUE THREAD

**Issue by fre2mansur** [codeigniter4/CodeIgniter4#6403]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

mysql

### What happened?

Connection id is always empty whether is the connection is correct or wrong.

### Steps to Reproduce

```php
 $custom = [
  'DSN'      => '',
  'hostname' => 'localhost',
  'username' => 'root1',
  'password' => "",
  'database' => 'my_db_2',
  'DBDriver' => 'MySQLi',
  'DBPrefix' => '',
  'pConnect' => false,
  'DBDebug'  => (ENVIRONMENT !== 'production'),
  'charset'  => 'utf8',
  'DBCollat' => 'utf8_general_ci',
  'swapPre'  => '',
  'encrypt'  => false,
  'compress' => false,
  'strictOn' => false,
  'failover' => [],
  'port'     => '3306',
];
$db = db_connect($custom);
print_r($db);  // [connID] => 
print_r($db->error());  // Attempt to read property "errno" on bool
```

### Expected Output

The connection id should be valid for the connected connection
* Returns the last error code and message.
* Must return this format: `['code' => string|int, 'message' => string`
* `intval(code) === 0` means "no error".

### Anything else?

![image](https://user-images.githubusercontent.com/8459473/185782524-20e7f385-d39d-4922-9f9c-c7099ba0ab55.png)

**Comment by kenjis** [comment]
`db_connect()` does not connect to the database yet.
What do you want to do?

**Comment by fre2mansur** [comment]
To test the custom connection before do the forge operations

**Comment by fre2mansur** [comment]
> `db_connect()` does not connect to the database yet.
> What do you want to do?
> 

What do you mean it does not connected to the database yet?

**Comment by kenjis** [comment]
> What do you mean by it does not connected to the database yet?

`db_connect()` just creates CI's DB connection object.
The code in your usage is not executed yet in the `db_connect()`.

```php
// Create connection
$conn = new mysqli($servername, $username, $password);
```

**Comment by paulbalandan** [comment]
You don't have a failover set for your DB connections, so upon `db_connect()` your connection won't start yet.
Try either (1) setting failover connections, or (2) `db_connect($custom)->connect();`
