### ISSUE TITLE
Bug: Defined Routes work only for GET method, POST, PUT, DELETE return 303 redirect to main page

### ISSUE THREAD

**Issue by rorysteward** [codeigniter4/CodeIgniter4#6404]
### PHP Version

8.0

### CodeIgniter4 Version

4.2.4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySQL 8.0

### What happened?

I am trying implement basic REST API and I am facing peculiar problem with routes. I have defined routes
```php
$routes->group(
    'api/v1',
    [
        'namespace' => 'App\Controllers\Api\V1',
        'filters' => 'ApiGuard',
    ],
    static function ($routes) {
        $routes->resource('companies', [
            'placeholder' => '(:num)',
            'only' => ['index', 'show', 'create', 'update', 'delete', 'edit']
        ]);
    }
);
```
And I have defined functions as such

```php
<?php

namespace App\Controllers\Api\V1;

use CodeIgniter\API\ResponseTrait;
use CodeIgniter\HTTP\IncomingRequest;
use App\Models\Api\V1\AuthenticationModel;
use CodeIgniter\RESTful\ResourceController;

class Companies extends ResourceController
{
    use ResponseTrait;
    /**
     * Instance of the main Request object.
     *
     * @var CLIRequest|IncomingRequest
     */
    protected $request;
    protected $format = 'json';

    public function index()
    {
        $AuthModel = new AuthenticationModel();
        $response = $AuthModel->select('company_id, com.*')
            ->join('companies AS com', 'company_id = com.id')
            ->where('api_token', $this->request->getHeaderLine('X-Api-Token'))
            ->findAll();
        return $this->respond($response);
    }

    public function show($id = null)
    {
        $AuthModel = new AuthenticationModel();
        $response = $AuthModel->select('company_id, com.*')
            ->join('companies AS com', 'company_id = com.id')
            ->where('api_token', $this->request->getHeaderLine('X-Api-Token'))
            ->where('company_id', mb_substr($this->request->getUri()->getSegment(4), 0, -5))
            ->findAll();
        return $this->response->setJSON($response);
    }

    public function create($id = null)
    {
        print_r('test');
        $response = 'test';
        return $this->respond($response);
    }
    public function update($id = null)
    {
        print_r('test');

        $response = [
            'test' => 'test'
        ];
        return $this->respond($response);
    }
    public function edit($id = null)
    {
        print_r('test');
    }
    public function delete($id = null)
    {
    }
}
```
And only GET method works, POST, PUT and DELETE redirect to main page.

### Steps to Reproduce

Create Controller which extends ResourceController, add appropiate rules as shown in https://codeigniter.com/user_guide/incoming/restful.html and send request via postman.

### Expected Output

Reaching defined function in routes

### Anything else?

<img width="1205" alt="2022-08-21 18_01_23-Postman" src="https://user-images.githubusercontent.com/87198302/185802533-b7003d9f-097c-421f-a4ef-5a6c5364a283.png">
<img width="1206" alt="2022-08-21 18_01_48-Postman" src="https://user-images.githubusercontent.com/87198302/185802534-576275f2-6e24-4d31-b134-1459638557f3.png">
<img width="1204" alt="2022-08-21 18_02_06-Routes php - framework - Visual Studio Code" src="https://user-images.githubusercontent.com/87198302/185802535-eacdbbaf-f800-4394-92ce-acdf122cee80.png">

**Comment by neznaika0** [comment]
CSRF token verification enabled in filters? For all POST requests, this is often confusing for beginners as there is no error notification.
If protection is enabled, you need to add code CSRF to postman or disable routes API in  filter file

**Comment by rorysteward** [comment]
Yes! I have CSRF enabled. I will look into exempting API calls from this check. over 20 hours of scratching my head. I thought it is something wrong with me. For a future would be great if there was a error message. And yes indeed I am self taught novice trying to wire some ideas

**Comment by neznaika0** [comment]
See https://www.codeigniter.com/user_guide/libraries/security.html#redirection-on-failure
Error message can be read and redirect disable

**Comment by kenjis** [comment]
@rorysteward I sent a PR #6406
