### ISSUE TITLE
Dev: remove `_parent_name` in BaseBuilder::objectToArray()

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#6412]
I would like to remove `_parent_name` in BaseBuilder::objectToArray().

https://github.com/codeigniter4/CodeIgniter4/blob/071cd044fb97948bd965b308c2ce1d0e5b524dce/system/Database/BaseBuilder.php#L2708-L2709

Because it seems there is no place to use ` '_parent_name'` in the code base.

**Comment by MGatner** [comment]
I'm not even sure what this does 😅

**Comment by kenjis** [comment]
I don't know either.

**Comment by iRedds** [comment]
It came from ci2 (I didn't find the 1.x version). Perhaps this is an internal solution from EllisLab.

**Comment by MGatner** [comment]
Wow. That's some legacy! 

Burn it with 🔥
