### ISSUE TITLE
Class Connection odbc not found.

### ISSUE THREAD

**Issue by rmanalu15** [codeigniter4/CodeIgniter4#6423]
I have checked system folder on codeigniter4 and I can't find any odbc driver, previously it was available on codeigniter3.
how it's work in codeigniter4? thankyou to anybody can help this issue.

Error
Class 'CodeIgniter\Database\odbc\Connection' not found.

**Comment by paulbalandan** [comment]
ODBC driver is not yet supported. Drivers supported at the moment are: MySQLi, PostgreSQL, SQLite3, Oracle OCI8, SQL Server

**Comment by kenjis** [comment]
See https://codeigniter4.github.io/CodeIgniter4/intro/requirements.html

> how it's work in codeigniter4?

Port the Ci3's driver to CI4 and send a PR.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

But if you send the PR, I recommend you make small but working portion of the whole driver.
Big PRs are difficult to review and will not be merged soon. See #2487
