### ISSUE TITLE
Bug: BaseHandler.php error

### ISSUE THREAD

**Issue by kseok2307** [codeigniter4/CodeIgniter4#6425]
### PHP Version

8.0, 8.1

### CodeIgniter4 Version

CodeIgniter 4.2.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

MySQL 5.7

### What happened?

When trying to handle mysql session
An error occurred in BaseHandler.php file 

`ini_set function ` Error correction is required.

### Steps to Reproduce

App.php

public $sessionDriver = 'CodeIgniter\Session\Handlers\DatabaseHandler';
public $sessionSavePath = 'ci_sessions';

### Expected Output

Fatal error
Uncaught ErrorException: ini_set(): Session ini settings cannot be changed when a session is active in /mnt/d/project/vendor/codeigniter4/framework/system/Session/Handlers/BaseHandler.php:162
Stack trace:

**Comment by ddevsr** [comment]
Give your code controller

**Comment by kseok2307** [comment]
> Give your code controller

Thanks for your reply.

The file session handler works, but the session database handling throws an error.

`
$sessionData = array(
 'emp_id' => $row['emp_id']
);
$this->Session->set($sessionData );
`

**Comment by DhPandya** [comment]
@kseok2307 
Share your code that is responsible to initialize the $this->Session.
And if possible share your whole controller code.

**Comment by kseok2307** [comment]
I got an error trying to handle the session database.
File handling works well in my code.

![image](https://user-images.githubusercontent.com/100179655/187000783-3d10d081-58ae-4f9d-8fd2-4c14af0135ae.png)



[app\Libraries\AuthLibrary.php]
=> It's a library file that I made.
![image](https://user-images.githubusercontent.com/100179655/186998185-be246063-c35e-499a-a2ae-49b255b33cd7.png)

[app\Controllers\LoginController.php]

![image](https://user-images.githubusercontent.com/100179655/186999805-57345536-6cdd-4c01-8781-0b90383186db.png)

[app\Services\AuthService.php]
=> It's a library file that I made.
![image](https://user-images.githubusercontent.com/100179655/187000076-452bd83b-9f6c-4502-a4f3-4fac71f0752e.png)

[vendor\codeigniter4\framework\system\Session\BaseHandler.php]
=> error

![image](https://user-images.githubusercontent.com/100179655/187000534-fa98cc25-46f6-45fc-8d74-ea9092e94db9.png)

**Comment by kenjis** [comment]
@kseok2307 Please don't use screenshot for your code. We cannot copy & paste it.

**Comment by kenjis** [comment]
Can you show the Stack trace?

> Uncaught ErrorException: ini_set(): Session ini settings cannot be changed when a session is active in /mnt/d/project/vendor/codeigniter4/framework/system/Session/Handlers/BaseHandler.php:162
Stack trace:

**Comment by kseok2307** [comment]
> @kseok2307 Please don't use screenshot for your code. We cannot copy & paste it.
I'm really sorry.
I made a mistake because I am a beginner in writing.
The source code is in the company, so screenshots are everything.

**Comment by kseok2307** [comment]
> Can you show the Stack trace?
> 
> > Uncaught ErrorException: ini_set(): Session ini settings cannot be changed when a session is active in /mnt/d/project/vendor/codeigniter4/framework/system/Session/Handlers/BaseHandler.php:162
> > Stack trace:


This is how it was solved.

`@int_set('session.save_path',$this->savePath);`

**Comment by kseok2307** [comment]
> > Can you show the Stack trace?
> > > Uncaught ErrorException: ini_set(): Session ini settings cannot be changed when a session is active in /mnt/d/project/vendor/codeigniter4/framework/system/Session/Handlers/BaseHandler.php:162
> > > Stack trace:
> 
> This is how it was solved.
> 
> `@int_set('session.save_path',$this->savePath);`


Thank you so much for your concern.
