### ISSUE TITLE
Query build should accept in WHERE clause MATCH AGAINST

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#6428]
So i've been searching how to make this query with the query builder class or the model but there is no way how to make this query here in example 

SELECT * FROM `countries` WHERE MATCH (`title`) AGAINST ('a b c') OR MATCH (`name`) AGAINST ('a b c')

The Where method concatenates "=" symbol so i cannot do this maybe there is a way ?
But surely the Match() method can be implemented this way.

WHERE MATCH works differently so i really need this some way to implement it but i do not want to make a long query that i need to escape all of its content.

**Comment by ddevsr** [comment]
You can custom where condition with `RawSql`

[See this](https://codeigniter.com/user_guide/database/query_builder.html#query-builder-where-rawsql)

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
