### ISSUE TITLE
Bug: Long time to debug (with dd) for enum

### ISSUE THREAD

**Issue by MrFrost-Nv27** [codeigniter4/CodeIgniter4#6429]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL

### What happened?

If we debugging with dd for enum, especially enum cases or enum class itself, its taking long time . but if we debug enum's name or value is not long.

### Steps to Reproduce

We create an enum
![Screenshot (26)](https://user-images.githubusercontent.com/70581926/187003475-24128670-1312-4d54-b8c6-d0d351a0274c.png)
```
namespace MrFrost\HtmlObject\Enums\Attributes;

enum GlobalAttributes: string
{
    case accesskey = "Specifies a shortcut key to activate/focus an element";
    case contenteditable = "Specifies whether the content of an element is editable or not";
    case data = "Used to store custom data private to the page or application";
    case dir = "Specifies the text direction for the content in an element";
    case draggable = "Specifies whether an element is draggable or not";
    case hidden = "Specifies that an element is not yet, or is no longer, relevant";
    case id = "Specifies a unique id for an element";
    case lang = "Specifies the language of the element's content";
    case spellcheck = "Specifies whether the element is to have its spelling and grammar checked or not";
    case style = "Specifies an inline CSS style for an element";
    case tabindex = "Specifies the tabbing order of an element";
    case title = "Specifies extra information about an element";
    case translate = "Specifies whether the content of an element should be translated or not";

    public function getType(): bool
    {
        return match ($this) {
            self::contenteditable, self::draggable, self::hidden, self::spellcheck, self::translate => "bool",
            default => "string"
        };
    }
}
```
And debug the enum cases
![Screenshot (27)](https://user-images.githubusercontent.com/70581926/187003492-62300419-0c2c-4cfc-bb95-25e83256adb0.png)
`dd(GlobalAttributes::cases());`
is taking long time then we get "Maximum execution time" error
![Screenshot (25)](https://user-images.githubusercontent.com/70581926/187003523-c95f65ef-05d1-4b11-8486-0d6c049033b8.png)

### Expected Output

 Fatal error: Maximum execution time of 120 seconds exceeded in E:\Nova\Latihan\HtmlObject\vendor\kint-php\kint\src\Renderer\RichRenderer.php on line 518

**Comment by kenjis** [comment]
Can you give the minimum code (not a screenshot) to reproduce the issue?

**Comment by MrFrost-Nv27** [comment]
> Can you give the minimum code (not a screenshot) to reproduce the issue?
this the enum class file
<?php

namespace MrFrost\HtmlObject\Enums\Elements;

enum HtmlElements: string
{
        // Header
    case Header1 = 'h1';
    case Header2 = 'h2';
    case Header3 = 'h3';
    case Header4 = 'h4';
    case Header5 = 'h5';
    case Header6 = 'h6';

        // Semantic
    case Div = 'div';
    case Span = 'span';

        // Typing
    case Paragraph = 'p';
    case Strong = 'strong';
    case Emphasized = 'em';
    case Italic = 'i';
    case Subscript = 'sub';
    case Superscript = 'sup';

        // Links
    case Hyperlink = 'a';
    case Link = 'link';

        // Utils
    case Break = 'br';
    case HorizontalRule = 'hr';

    public function isContainable(): bool
    {
        return match ($this) {
            self::Break, self::HorizontalRule, self::Link => false,
            default => true
        };
    }

    public function isAppendable(): bool
    {
        return match ($this) {
            self::Header1, self::Header2, self::Header3, self::Header4, self::Header5, self::Header6,
            self::Strong, self::Emphasized, self::Italic, self::Subscript, self::Superscript
            => false,
            default => true
        };
    }
}

and i try to dd in index controller to see it in screen
dd(HtmlElements::cases());

**Comment by MrFrost-Nv27** [comment]
> Can you give the minimum code (not a screenshot) to reproduce the issue?
That i update the thread and add my code

**Comment by kenjis** [comment]
@MrFrost-Nv27 Thank you for update!
I've confirmed the behavior.

It seems an issue in Kint. I created an Issue: https://github.com/kint-php/kint/issues/392

**Comment by MrFrost-Nv27** [comment]
> @MrFrost-Nv27 Thank you for update! I've confirmed the behavior.
> 
> It seems an issue in Kint. I created an Issue: [kint-php/kint#392](https://github.com/kint-php/kint/issues/392)

Ok thanks for the response

**Comment by MrFrost-Nv27** [comment]
Oke great, thanks

**Comment by kenjis** [comment]
Kint 4.2.0 was released.

If you install CodeIgniter via Composer, `composer update` will solve this problem.
If not, the next release v4.2.5 would solve this problem.
