### ISSUE TITLE
Bug: URL with .php suffix doesn't showing a not found page.

### ISSUE THREAD

**Issue by enix-app** [codeigniter4/CodeIgniter4#6435]
### PHP Version

8.0

### CodeIgniter4 Version

4.2.4

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

URL with **_.php_** suffix doesn't showing a not found page.

### Steps to Reproduce

null

### Expected Output

A not found page.

**Comment by kenjis** [comment]
Duplicate of #6232
