### ISSUE TITLE
make Time object usable with QueryBuilder in all locales

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#6439]
### PHP Version

8.0

### CodeIgniter4 Version

`develop` (799d6558187669a847f5ac573226e2e1ef6a31f6)

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli

### What happened?

In locale fa, cannot use `Time` object with QueryBuilder.

The following code generates the query  like `UPDATE "users" SET "last_active" = '۲۰۲۲-۰۸-۲۹ ۱۳:۰۰:۰۰' WHERE "id" = 1`.
And it results in database query error.

```php
        Locale::setDefault('fa');

        $builder = new BaseBuilder('users', $this->db);

        $time = Time::parse('2022-08-29 13:00');
        $builder->testMode()->set('last_active', $time)->where('id', 1)->update();
        $sql = $builder->getCompiledUpdate();
```

### Steps to Reproduce

See above.

### Expected Output

Generates `UPDATE "users" SET "last_active" = '2022-08-29 13:00:00' WHERE "id" = 1`.

**Comment by MGatner** [comment]
I'm not sure this is a bug. `set()` does not support object values, so the only reason this doesn't cause an error is because `Time` is Stringable. This is the equivalent to:
```php
$builder->testMode()->set('last_active', (string) $time)->where('id', 1)->update();
```
`Time::__toString()` is intentionally locale-specific, so the appropriate call should be to specify `toDatabase()` (or the backwards-compatible version).

**Comment by kenjis** [comment]
> set() does not support object values

I'm not sure. It is not documented it supports or not, and it has type `mixed` in PHPDoc.
https://github.com/codeigniter4/CodeIgniter4/blob/622f82942ec6064fb44eb4ab82cda468baa47687/system/Database/BaseBuilder.php#L1499

Actually non Stringable objects never work.

I think it is not consistent in behavior to work with en locale and not with fa. Simply confusing.
So it is good to support Time object in any locale, because it is a standard CI4 class.
If this is not a bug, then it is an enhancement.

**Comment by datamweb** [comment]
Kenjis may help you!

```php
     $fa= numfmt_create( 'fa', \NumberFormatter::DECIMAL );
     $output = numfmt_parse( $fa, '۲' );

     dd($output);
```
**output :** 
`$output double 2`

https://www.php.net/manual/en/numberformatter.create.php

**Comment by MGatner** [comment]
> it is good to support Time object in any locale

I don't see a way to do that other than checking `$value instanceof Time` then replacing it with `$value = $value->toDatabase()`. It feels kind of hacky but if this feels important I don't think it poses an actual problem.

**Comment by kenjis** [comment]
@datamweb Thanks for the info.
But datetime is not decimal, so it seems we cannot use it in this case.

I sent a PR https://github.com/codeigniter4/CodeIgniter4/pull/6456
