### ISSUE TITLE
Bug: Commands that require the use of validation return an error

### ISSUE THREAD

**Issue by michalsn** [codeigniter4/CodeIgniter4#6457]
### PHP Version

8.0

### CodeIgniter4 Version

4.2.5 / develop

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli

### Database

-

### What happened?

Using validation in the Command ends with an error.

E.g.
```
CLI::prompt('Variable', null, 'required');
```

### Steps to Reproduce

Run the command:
```
php spark make:migration
```
and then provide a name for the migration.

After confirming the name, you will get an error, and the command won't be executed.

### Expected Output

No errors.

### Anything else?

A bug was introduced to the `system/Validation/FileRules.php` here: https://github.com/codeigniter4/CodeIgniter4/commit/b53d482699a5f454e537544fc87c132d740545b1

The idea of checking this should be revisited.

**Comment by datamweb** [comment]
Related to: #6452

**Comment by michalsn** [comment]
Thanks, I missed it.
