### ISSUE TITLE
Bug:  Postgresql createTable if not exists with multiple schemas

### ISSUE THREAD

**Issue by mawi1077** [codeigniter4/CodeIgniter4#6458]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

PostgreSQL 13.7

### What happened?

to use multiple schema I set in database config
'schema' => 'schema1,schema2'
that's working fine so far.

but when use createTable with option "if not exist" then I get Error Table Exists
that happens because the query in Connection::_listTables has an syntax error in WHERE CLAUSE

### Steps to Reproduce

'schema' => 'schema1,schema2'
$forge = \Config\Database::forge();
$forge->createTable($tablename, TRUE);

### Expected Output

the function should return object or false, without generating an error

**Comment by kenjis** [comment]
Thank you for the report.

But the Steps to Reproduce can not run.
Please provide minimum running code to reproduce the error.
And you didn't provide the exact error message, too.

```
'schema' => 'schema1,schema2'
$forge = \Config\Database::forge();
$forge->createTable($tablename, TRUE);
```

**Comment by kenjis** [comment]
How did you call `checkOrCreateTable()`?
What's the exact parameter value?

**Comment by mawi1077** [comment]
i fix it for me with an dirty hack in Connection.php 208 _listTables(bool $prefixLimit = false): string

       $array = explode(',', $this->schema); 
        $whc = '';
        foreach ($array as $sc){
            if ($whc != '' ) $whc .= " OR ";
            $whc .= '"table_schema" = \'' . $sc . "'";
        } 
        $sql = 'SELECT "table_name" FROM "information_schema"."tables" WHERE '.$whc;

**Comment by kenjis** [comment]
Is `'schema' => 'schema1,schema2'` valid config?

**Comment by kenjis** [comment]
It is `$schema`, not `$schemas`.
I don't think `'schema1,schema2'` is a valid value.

> At least with the default settings the search path get set to "public, public".

It seems a bug, but no harm.

**Comment by sclubricants** [comment]
Forge is designed to use one schema at a time. We could add a method to set schema but this could get messy. This listTables() method would have have to use schema and table as cache names. But like I said this gets messy.

I'd recommend using a separate connection for each schema.

https://www.postgresql.org/docs/current/ddl-schemas.html

**Comment by kenjis** [comment]
No plan to support multiple schema. Close.
