### ISSUE TITLE
Bug: Error en Constants.php line 41 to 43

### ISSUE THREAD

**Issue by daltonmart** [codeigniter4/CodeIgniter4#6464]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.5

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

in the file App/Config/Constants.php lines 41 to 43:
41 defined('MONTH')  || define('MONTH', 2_592_000);
42 defined('YEAR')   || define('YEAR', 31_536_000);
43 defined('DECADE') || define('DECADE', 315_360_000);
the "_" character must be removed, leaving it as follows:

defined('MONTH')  || define('MONTH', 2592000);
defined('YEAR')   || define('YEAR', 31536000);
defined('DECADE') || define('DECADE', 315360000);

### Steps to Reproduce

see on file App/Config/Constants.php lines 41 to 43:

### Expected Output

nothing

**Comment by datamweb** [comment]
Hi @daltonmart , Not Bug.
[See](https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.numeric-literal-separator)
