### ISSUE TITLE
Bug: Custom filter `except` is not working

### ISSUE THREAD

**Issue by DhPandya** [codeigniter4/CodeIgniter4#6465]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 8.1.0

### What happened?

Custom filter except is not working. It is working fine for the $globals. But the $filters is not working.

### Steps to Reproduce

Below is my code to except the logout route from the check_frontuser_login filter.

Filter.php
```php
/**
     * List of filter aliases that should run on any
     * before or after URI patterns.
     *
     * Example:
     * 'isLoggedIn' => ['before' => ['account/*', 'profiles/*']]
     *
     * @var array
     */
    public $filters = [
        'before' => [
            'check_frontuser_login' => [
                'except' => 'user/logout'
            ],
        ]
    ];
```

Routes.php
```php
$routes->group(FRONTEND, ['filter' => 'check_frontuser_login', 'namespace' => 'App\Controllers\Frontend'], function ($routes) {
    $routes->match(['get', 'post'], 'profile', 'RegisterUsersController::profile');
    $routes->get('logout', 'RegisterUsersController::logout');
});
```

### Expected Output

When declaring the except in the $filters array it should accept the particular routes from the filter.

**Comment by kenjis** [comment]
There is no `except` in `$filters`.
See https://codeigniter4.github.io/CodeIgniter4/incoming/filters.html#filters

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
