### ISSUE TITLE
Using left Join in CodeIgniter4

### ISSUE THREAD

**Issue by bossoff** [codeigniter4/CodeIgniter4#6493]
Hi, Please how can some use Left Join in [CodeIgniter4] aside from Join? Cause I can't find where it is stated on the documentation.

Thanks.

**Comment by datamweb** [comment]
Hi, Please see [JOIN](https://codeigniter.com/user_guide/database/query_builder.html#join).

**Comment by bossoff** [comment]
Actually, I have two column Ids in my Table called (Manual_funding). 
1. is UserId referencing the Users table while 
2. is the process_by_id  also linked back to the User table?

So now I needed to Join the Manual_funding Table with the Users Table matching the two ids. But the problem is that I can only join the Users table once with userId and I need to check for the process_by_id on that same Users Table (userId).

Thanks

**Comment by datamweb** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by bossoff** [comment]
Alright Cool. But I will love it if CI4 can also add LeftJoin, InnerJoin, and all as new futures aside from the join that has been added.

Thanks

**Comment by datamweb** [comment]
My friend, I am a framework user like you.
These rules are the same for all of us.
In any case, if you need a new feature, you should proceed from section  [CodeIgniter 4 Feature Requests](https://forum.codeigniter.com/forumdisplay.php?fid=29).
However, I would like to draw your attention to the following image:

![Screenshot 2022-09-05 025457](https://user-images.githubusercontent.com/9530214/188337618-6b37a002-f15c-4289-95a2-3fe408afb5e6.jpg)

**Comment by bossoff** [comment]
Wow. Thanks, man.
