### ISSUE TITLE
Bug: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by DevLogsan** [codeigniter4/CodeIgniter4#6528]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.24

### What happened?

nothing works anymore

### **Controllers :**
```php
$session = session();
$modelParametres = new ModelParametres();

$ClientRetourne = $modelParametres->retournerClientID($ClientID);
$session->set('noclient', $ClientRetourne["noclient"]);
```

### **Models :**
```php
public function retournerClientID($ClientID)
    {
        $builder = $this->db->table('client');
        $builder->join('obtenir', 'client.noclient = obtenir.noclient');
        $builder->join('grade', 'obtenir.nograde = grade.nograde');
        $builder->where('client.noclient', $ClientID);
        $query = $builder->get();
        if (count($query->getResultArray()) == 1) {
            return $query->getRowArray();
        }
        else
        {
            return false;
        }
    }
```

### Expected Output

before I had no problem, I have the error that since a few days,
it is supposed to refer 1 specific customer

**Comment by cijagani** [comment]
Please use latest version. 4.2.6

**Comment by kenjis** [comment]
When `$modelParametres->retournerClientID()` returns false,
you cannot access `$ClientRetourne["noclient"]`.

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
