### ISSUE TITLE
Docs: Note for No input file specified

### ISSUE THREAD

**Issue by neznaika0** [codeigniter4/CodeIgniter4#6542]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.6

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

On one of the hosting reg.ru there is a problem "_No input file specified_"
I believe that this is an incorrect server setting (related due to nginx or php-cgi), they write about it on other resources.
The problem was solved by changing **public/.htaccess**
on the
  `RewriteRule ^([\s\S]*)$ index.php [L,NC]`
I don’t know how common this error is, maybe it’s worth adding a note about this to the documentation?
https://codeigniter.com/user_guide/installation/troubleshooting.html
for example this: If you encounter a _No input file specified_ error, try changing htaccess to "code example"

### Steps to Reproduce

Move files from localhost to shared hosting

### Expected Output

Must run app

**Comment by neznaika0** [comment]
Now I can check if the site is working.
I tried to start the router in different ways - index.php does not find it.
Could only open https://example.com/index.php?/foo?page=1

**Comment by neznaika0** [comment]
> 

Yes, this rules work. Added ? solves the problem

**Comment by kenjis** [comment]
@neznaika0 Thank you for your feedback!
I sent a PR: #6545
