### ISSUE TITLE
Bug: render `Parser` default value with empty array

### ISSUE THREAD

**Issue by ddevsr** [codeigniter4/CodeIgniter4#6553]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.6

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.7

### What happened?

See comment [#6550](https://github.com/codeigniter4/CodeIgniter4/pull/6550#discussion_r973727496), empty array cannot parsing default value.

### Steps to Reproduce

```php
$parser = new Parser($this->config, $this->viewsDir, $this->loader);

$obj = (object) '';

$data = [
      'value1' => 0.0,
      'value2' => [],
      'value3' => $obj->scalar,
      'value4' => false,
];

$template = '{ value1|default(foo) } { value2|default(bar) } { value3|default(baz) } { value4|default(john) }';
$parser->setData($data);

echo $parser->renderString($template);
```

### Expected Output

Result is `foo bar baz john`

**Comment by kenjis** [comment]
What do you want to show when you set an array to a *variable* ?
Or why do you need to set an array?

**Comment by ddevsr** [comment]
> That's odd! `empty([])` is definitely true - I wonder if this is somehow getting interpolated as `empty[''])` (which is false)? I think that we still allow `array` types here, and address this as a bug in another PR.

@MGatner say need still allow array types. When testing with `[]` or `['']` get result error.

**Comment by kenjis** [comment]
An array cannot be converted to a string. So we cannot show an array in the web page.
Or it is converted to `Array` with PHP warning if we use PHP view.

I don't see the use case of an array.

**Comment by ddevsr** [comment]
```php
    public function testDefaultManyValue()
    {
        $parser = new Parser($this->config, $this->viewsDir, $this->loader);

        $obj = (object) '';

        $data = [
            'value1' => 0.0,
            'value2' => [['test' => '']],
            'value3' => $obj->scalar,
            'value4' => false,
        ];

        $template = '{ value1|default(foo) } {value2}{ test|default(bar) }{/value2} { value3|default(baz) } { value4|default(john) }';

        $parser->setData($data);
        $this->assertSame('foo bar baz john', $parser->renderString($template));
    }
```

With this its OK, but if use case array from database is `[]`?

**Comment by kenjis** [comment]
By the way, when `0.0` comes, why do we return the default value?

**Comment by kenjis** [comment]
> With this its OK, but if use case array from database is []?

Do you mean the value of `test` is `[]`?
In that case, what value will come when it is not empty array?

**Comment by ddevsr** [comment]
No, i mean what if `'data' => []`

```php
    public function testDefaultArrayValue()
    {
        $parser = new Parser($this->config, $this->viewsDir, $this->loader);

        $data = [
            'data' => [
                [
                    'field_no'    => 1,
                    'field_title' => 'Mouse',
                    'field_amount'=> 20,
                ],
                [
                    'field_no'    => 2,
                    'field_title' => 'Keyboard',
                    'field_amount'=> 44,
                ],
            ],
        ];

        $template = '{data}[{ field_no|default(bar) }] { field_title|default(bar) } = { field_amount|default(bar) }\n{/data}';

        $parser->setData($data);
        $this->assertSame('[1] Mouse = 20\n[2] Keyboard = 44\n', $parser->renderString($template));
    }
```

**Comment by kenjis** [comment]
`{blog_entries}` is `[]`? 
Do you want `{blog_entries|default(No data available)}`?

**Comment by ddevsr** [comment]
Yes, like that
