### ISSUE TITLE
Bug: Composer Install An Existing Project ( The "--no-dev" option does not exist. )

### ISSUE THREAD

**Issue by robikasep** [codeigniter4/CodeIgniter4#6560]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.6

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

Mysql

### What happened?

so what's happening? if i type normal without --no-dev run smothly but with --no-dev the composer won't let me install, after 
few minutes i do experiment type in terminal like this:
composer require codeigniter4/framework --no-dev
composer require codeigniter4 --no-dev
composer require --no-dev
composer --no-dev

but none of one that work and try another experiment:
composer require --update-no-dev
composer update --no-dev

and that's work but we won't update package composer.json and composer.lock (project) because could be conflict or error

### Steps to Reproduce

1. clone an existing project 
2. open terminal in root project
3. type: composer require codeigniter4/framework --no-dev
4. showing red box error The "--no-dev" option does not exist.

documentation: https://codeigniter.com/user_guide/installation/installing_composer.html#adding-codeigniter4-to-an-existing-project

### Expected Output

Complete Install an Existing Project with --no-dev

### Anything else?

documentation: https://codeigniter.com/user_guide/installation/installing_composer.html#adding-codeigniter4-to-an-existing-project

this is feature/bug? i don't know, but absolutely you guys can fix it

**Comment by kenjis** [comment]
Thank you for reporting!

Yes, there is no such option.
```console
$ composer require codeigniter4/framework --no-dev

                                         
  The "--no-dev" option does not exist.  
                                         

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

I sent a PR #6562

**Comment by robikasep** [comment]
you welcome sir
i really love it for your respon is really fast i thought this bug will be fix in several week or days! 😅

**Comment by MGatner** [comment]
The docs are wrong! @kenjis is working on it. Use this:
```shell
composer require codeigniter4/framework --update-no-dev
```

**Comment by robikasep** [comment]
thanks MGatner i've been try that and it's work very well
