### ISSUE TITLE
Bug: site_url giving different output in Ci4 

### ISSUE THREAD

**Issue by hamzawain7** [codeigniter4/CodeIgniter4#6561]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.6

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### What happened?

calling site_url("template/meet-%26-greet") gives different output than the one in codeigniter 3.

codeigniter 3 output = .../index.php/art/template/meet-%26-greet
codeigniter 4 output = .../index.php/art/template/meet-&-greet

I believe site_url shouldn't be decoding the url as one can use the output of it in hrefs without worrying of getting "The URI you submitted has disallowed characters." error

### Steps to Reproduce

call site_url("template/meet-%26-greet") 

### Expected Output

.../index.php/art/template/meet-%26-greet

**Comment by kenjis** [comment]
Thank you for reporting.
It seems `/template/meet-%26-greet` is a valid URL path.

This code decode `%xx`:
https://github.com/codeigniter4/CodeIgniter4/blob/5a0f1e38c515d0e7ab640f5cfb54c61f1d131275/system/HTTP/URI.php#L877-L879

**Comment by kenjis** [comment]
> It seems /template/meet-%26-greet is a valid URL path.

But if we normalize the URL, it will be `/template/meet-&-greet`.

Using https://github.com/glenscott/url-normalizer:
```php
$ cat test.php 
<?php

require_once 'vendor/autoload.php';

$url = 'http://example.com/template/meet-%26-greet';
$un = new URL\Normalizer($url);
echo $un->normalize() . PHP_EOL;
```
```console
$ php test.php 
http://example.com/template/meet-&-greet
```

**Comment by kenjis** [comment]
> I believe site_url shouldn't be decoding the url as one can use the output of it in hrefs without worrying of getting "The URI you submitted has disallowed characters." error

It seems there is no such error in CI4.
Did you get the error?

**Comment by kenjis** [comment]
I believe URLs should be normalized and the current behavior of `site_url()` has no problem.

**Comment by robikasep** [comment]
i think you need learn the new behavior URL /http/uri/etc of codeigniter 4 is a bit diffrent especially with the new version 4.2

**Comment by hamzawain7** [comment]
My bad,"&" is allowed in urls in ci4 unlike ci3
