### ISSUE TITLE
Dev: OutgoingRequestInterface is missing

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#6573]
The current CI4 does not have Request interface for an outgoing request.

Problem:
- `CURLRequest` must implement methods for incoming requests that do not have to have.

![](http://www.plantuml.com/plantuml/png/ZP9FIyD04CNl-oc6djMJq6kX5mCLGbflNfOu6uBx9-vCH91-TrVTDYMTb9rJillc_LuUsH3hoAEpQj3jk-uGLlM-kL-lu5j1cjupHgDRX9hY-lKPYPAeEfqgITJWnuZ4Pn7W5wD_emKBIEC38rWq3C789WhoQ0zXv2xqleFuBthukqo8NnyvqnxZ9yR5P09II2PQ2VbwtmQtdE-efhAtrUDrrM95qxM8RgqcEcr2xmQB3ZsVZoHrDiej56tVNTCl3AlyuNFZ_3uLoc60OEPwjTWWc13XwN2ePrLUiBUxgXIRf6N49Bm1V6bsnSH9gqf_uwFQfEVHsHy0)
http://www.plantuml.com/plantuml/uml/ZPBD3i8W48JlFCN6iteoyG5wiOacJTMR5rAtJMCB5T2OcBwxzB-nMuKRy34p31Gykl44OH4SmzLs0My6TgJ2e8fvX11ejRqSK6iB-Tqgew0Gxm_KfeS0NmR5LSz8L0f26eGCOmCofaLgh1fSW7oOHAOY0TL0wthJMjGwPAOZgYUgtyb8osaoMcgSBnMHpEVpbOmLNTcUlvbMJLOqR9FMKSQrxav2cXSPvYYCfiKQkXNgMt0ulPowZmJzzkBVmkryADJ8ekhpYsUp3K8i5UnEfu1wwiRRs_kkjWFwnz62FmpFuTxPSM2PwpSksGS0

```puml
@startuml

package "PSR-7" {
    interface Psr7\MessageInterface

    interface Psr7\RequestInterface extends Psr7\MessageInterface
    note left of Psr7\RequestInterface
        an outgoing request.
    end note

    interface Psr7\ServerRequestInterface extends Psr7\RequestInterface
    note left of Psr7\ServerRequestInterface
        an incoming request.
    end note
}

package "CI4" {
    interface MessageInterface
    interface RequestInterface
    class Message implements MessageInterface
    class Request extends Message implements MessageInterface, RequestInterface

    class IncomingRequest extends Request
    note top of IncomingRequest
      an incoming request for HTTP.
    end note

    class CLIRequest extends Request
    note top of CLIRequest
      an incoming request for CLI.
    end note

    class CURLRequest extends Request
    note top of CURLRequest
      an outgoing request.
    end note
}

@enduml
```

**Comment by paulbalandan** [comment]
Fixed in #6698
