### ISSUE TITLE
Bug: required_with validation rule works in insert new record mode but not in update mode

### ISSUE THREAD

**Issue by padamnet** [codeigniter4/CodeIgniter4#6577]
### PHP Version

7.4

### CodeIgniter4 Version

CI_VERSION = '4.2.6'

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 10.4.24-MariaDB

### What happened?

I have a problem with required_with rule. In my form I have 4 input text fileds: fielda, fieldb, fieldc, fieldd.

The rule I want to have is: if any of the fields fieldb, fieldc, fieldd has any content then fielda becomes mandatory. So In the model I have the rule

```php
protected $validationRules = [

        'fielda' => 'required_with[fieldb,fieldc, fieldd]'

    ];

    protected $validationMessages = [

        'fielda' => [

            'required_with' => 'Please fill in fielda'

       ],
```

The rule works fine when I enter a new record and If I fill in with data any of the fields fieldb, fieldc, fieldd without writting anything to fielda it stops me with the message 'Please fill in fielda'. Then I have to write something in fielda and the record is added to the database. Now if I return to that record to modify it the rule does not work. I may remove fielda content and the record is updated without any error message.
I have attached the test project with the database so you can check it,

[mycustom.zip](https://github.com/codeigniter4/CodeIgniter4/files/9636841/mycustom.zip)
[mycustomdb.sql.zip](https://github.com/codeigniter4/CodeIgniter4/files/9636843/mycustomdb.sql.zip)

### Steps to Reproduce

You can run the attached project.

### Expected Output

I am expecting the validation rule required_with to work not only in the insertion mode but to operate in update mode as well.

**Comment by kenjis** [comment]
Thank you for reporting.

> I am expecting the validation rule required_with to work not only in the insertion mode but to operate in update mode as well.

It is not so easy to do so.

The current behavior is an expected one.

> Important
When you update data, the validation in the model class only validate provided fields. So when you set the rule required, if you don’t pass the required field data, the validation won’t fail. This is to avoid validation errors when updating only some fields.
https://codeigniter4.github.io/CodeIgniter4/models/model.html#in-model-validation

**Comment by padamnet** [comment]
Hello kenjis
To my point of view there is an ambiguity and weakness to this.

**Comment by kenjis** [comment]
There is  `cleanRules()` method:
https://github.com/codeigniter4/CodeIgniter4/blob/47ed563468e0887d4a9bcdc770de429dbca252ab/system/BaseModel.php#L1314

If you call `cleanRules(false)` and pass the fields for `required_with`, 
the validation would work as you expected.

**Comment by padamnet** [comment]
Thank you for your concern on the matter. Practically how can I do this? Is there any example to follow?
Regards

**Comment by kenjis** [comment]
No, it is not documented at all.
I did not know of its existence.

**Comment by padamnet** [comment]
Then, maybe the only solution is to create a custom rule. What do you think?

**Comment by kenjis** [comment]
> If you call `cleanRules(false)` and pass the data that contains fields for `required_with`, 
the validation would work as you expected, maybe.

No, it is not.

If `$cleanValidationRules` is true, the validation rules for the field that is not contained in the passed data will be removed before validation.

But it does not seems to work if you don't call `validate()` by yourself.
If you call `insert()` or `update()` or `save()`, the `$cleanValidationRules` value will be changed automatically.
I'm not sure this is a bug or not.

**Comment by kenjis** [comment]
> Then, maybe the only solution is to create a custom rule. What do you think?

A custom rule cannot solve the problem.

**Comment by kenjis** [comment]
There are two issues:
1. When Model updates an Entity, the validation rule in the Model will be cleaned. That is the rules for a field that does not exists in the data to save will be removed.
2. When you use Entity, Model updates only changed fields automatically. That is the fields that is not changed will not included in the data to save.

In your sample case, if `fielda` is changed to empty string, the Entity provides only the changed field `fielda`,
and Model validates the data with the rule for `fielda` field only. 
`fieldb` , `fieldc`, `fieldd` are not included in the data to validate, so `fielda` will be not required.

**Comment by kenjis** [comment]
I sent a PR #6588
@padamnet Please try if you can.
