### ISSUE TITLE
Bug: $this->cachePage($n) - Pagination Problem

### ISSUE THREAD

**Issue by mbnl** [codeigniter4/CodeIgniter4#6584]
### PHP Version

8.0

### CodeIgniter4 Version

4.2.6

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

Mysql 5.6

### What happened?

First of all, his English is not good.

I have a blog page and I am using pagination.

When I use the $this-cachePage() function on my blog page, it shows the 1st page that is cached when switching between pages, so it doesn't switch to other pages. How can I solve this?

### Steps to Reproduce

public function index()
    {
        $this->cachePage(60);

        $pageImage = model('PageImages')->image('blog', $this->cms);

        $blogQuery = model('Blogs')->orderBy('tarih','DESC');
        $list = $blogQuery->paginate(1);
        $pager = $blogQuery->pager;

        $this->setPageTitle($this->cms->lang('blog'));
        return view('blog',compact('pageImage','list','pager'));
    }

### Expected Output

on which page it should be cached

**Comment by lonnieezell** [comment]
Cache page will cache the entire page and doesn't work well with dynamic pages like that. It doesn't currently take Query vars into account. 

I would do the caching within the controller just so that it doesn't have to hit the database at all. Then make sure you clear the cache whenever you publish a new blog post.

**Comment by mbnl** [comment]
> Cache page will cache the entire page and doesn't work well with dynamic pages like that. It doesn't currently take Query vars into account.
> 
> I would do the caching within the controller just so that it doesn't have to hit the database at all. Then make sure you clear the cache whenever you publish a new blog post.

thank you for your response.

**Comment by kenjis** [comment]
The Query String bug was fixed in the `develop`branch  and it will be included in v4.2.7. 
See #6475
