### ISSUE TITLE
Set default locale without prefix

### ISSUE THREAD

**Issue by mbnl** [codeigniter4/CodeIgniter4#6605]
I write a multilanguage application. I don't want to use locale prefix for the default language, so for example my URL structure should be like this:

https://example.com/about-us
https://example.com/contant
https://example.com/es/about-us
https://example.com/es/contant
https://example.com/de/about-us
https://example.com/de/contant

When I make a website using CodeIgniter, I always find a solution for myself by writing a custom function, but it would be great if CodeIgniter brought it as a default feature.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
