### ISSUE TITLE
Bug: PostgreSQL boolean field columns

### ISSUE THREAD

**Issue by vitalijalbu** [codeigniter4/CodeIgniter4#6609]
### PHP Version

8.1

### CodeIgniter4 Version

latest

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

fpm-fcgi

### Database

PostgreSQL

### What happened?

Inside my db i have booleans fields, t-f.
it's possible to return true or false when typing fro example `(bool)$row['status_online']`
it's returning 0 or 1 , it's ok but for people who build rest api, it's not as clear... thanks

### Steps to Reproduce

- create a postgresql table with a boolean column field
- create codeigniter query to get row query data
- type (bool)$row['field']

### Expected Output

TRUE - FALSE

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by kenjis** [comment]
I think `$db->query()` should not alter the query result.
