### ISSUE TITLE
Bug: Unable to connect to the database when name contains word `export`

### ISSUE THREAD

**Issue by psuplat** [codeigniter4/CodeIgniter4#6621]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli

### Database

PostgreSQL

### What happened?

Unable to connect to the database when database group name contains word _export_, even is it's only a partial name, ie. _exports_data_ will also fail.

### Steps to Reproduce

Define db group with word `export` in .env file:
```
database.exports_test.hostname = localhost
database.exports_test.database = dev_db
database.exports_test.username = postgres
database.exports_test.password = postgres
database.exports_test.DBDriver = Postgre
database.exports_test.DBDebug = FALSE
database.exports_test.schema = exports_test
database.exports_test.port = 5432
```

define this group in app/Config/Database.php:
```
public $exports_test= [
    'hostname' => '',
    'schema' => '',
    'username' => '',
    'password' => '',
    'database' => '',
    'DBDriver' => '',
    'DBPrefix' => '',
    'pConnect' => false,
    'DBDebug'  => (ENVIRONMENT !== 'production'),
    'cacheOn'  => false,
    'cacheDir' => '',
    'charset'  => 'utf8',
    'DBCollat' => 'utf8_general_ci',
    'swapPre'  => '',
    'encrypt'  => false,
    'compress' => false,
    'strictOn' => false,
    'failover' => [],
];
```

try to run a query against the db. You will receive `You have not selected a database type to connect to` error message

### Expected Output

Query results

**Comment by kenjis** [comment]
Thank you for reporting.

Is this because of *database group name* or *database schema name* ?

**Comment by paulbalandan** [comment]
I think this is because of `DotEnv` class replacing `export` to empty string during sanitization.

**Comment by psuplat** [comment]
group name. If I change the group name to `expor`, but keep the schema name it then works as it should

**Comment by kenjis** [comment]
This is a bug in `DotEnv`.
A workaround is to set in the Config file.
