### ISSUE TITLE
Bug: valid_json language string missing in /system/Language/en/Validation.php

### ISSUE THREAD

**Issue by rpfennin** [codeigniter4/CodeIgniter4#6623]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.6

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS, Linux

### Which server did you use?

fpm-fcgi

### Database

MySQL 8

### What happened?

The valid_json language string is missing in /system/Language/en/Validation.php.  I can certainly fix this by providing my own string, but given this is a stock validation rule, it probably aught to exist.

### Steps to Reproduce

create a validation rule containing valid_json, and pass invalid json.

### Expected Output

I would expect to see something like:
The content field must be valid json.

Instead i get:
Validation.valid_json

**Comment by kenjis** [comment]
Thank you for reporting. I confirmed this bug.

We welcome a [PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

**Comment by ddevsr** [comment]
I send PR #6624
