### ISSUE TITLE
Bug: CLIRequest::getCookie() does not exist

### ISSUE THREAD

**Issue by sclubricants** [codeigniter4/CodeIgniter4#6642]
### PHP Version

8.0

### CodeIgniter4 Version

4.2.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

cli

### What happened?

When running a controller through CLI if the controller runs get_cookie() an error occurs.

### Steps to Reproduce

Create a controller:

	public function index()
	{
		$model = new TestModel();

                helper('cookie');
                $remember = get_cookie('remember');

		return 'success';
	}

run  php C:\xampp\portal\public\index.php public/test/index

### Expected Output

expected 'success'

### Anything else?

I tried the set_cookie() method to see if it causes error and it did not.

I understand you cant set/retrieve cookies via CLI but this causes errors using Myth-Auth and calling a controller. It checks the remember me cookie and throws the error:

```
[Error]

Call to undefined method CodeIgniter\HTTP\CLIRequest::getCookie()

at SYSTEMPATH\Helpers\cookie_helper.php:81
```

As a quick work around I copied the `IncomingRequest::getCookie()` method to `CLIRequest` and things are working.

Perhaps `cookie_helper`should not call `getCookie()` on a CLI request.

**Comment by kenjis** [comment]
> I understand you cant set/retrieve cookies via CLI but this causes errors using Myth-Auth and calling a controller. It checks the remember me cookie and throws the error:

Yes, you cannot use cookies via CLI.

What's the exact problem  using Myth-Auth and calling a controller?
Why do you need to run the controller via CLI?

**Comment by sclubricants** [comment]
Myth-Auth calls authentication check and calls getCookie.

My controllers output json responses that can be used for webpage but responses are output to a file when called from CLI. Its how I do multithreading of jobs. A collector looks for these files and reports status for individual job.

It makes sense to not throw an error. PHP's cookie methods do not throw errors on CLI.

**Comment by sclubricants** [comment]
>Can you get the correct result when running the controller via CLI if no error ocurrs?

The error goes away when adding the getCookie() method to CLIRequest.

With Myth-Auth any request calls the get_cookie() method. Perhaps it could be a Myth-Auth issue but I still think that calling get_cookie() on a CLI request should cause an error. If should just return null.

**Comment by sclubricants** [comment]
Myth-Auth LocalAuthenticator::

```php
    public function check(): bool
    {
        if ($this->isLoggedIn())
        {
            // Do we need to force the user to reset their password?
            if ($this->user && $this->user->force_pass_reset)
            {
                throw new RedirectException(route_to('reset-password') .'?token='.$this->user->reset_hash);
            }

            return true;
        }

        // Check the remember me functionality.
        helper('cookie');
        $remember = get_cookie('remember');

        if (empty($remember))
        {
            return false;
        }
```

**Comment by kenjis** [comment]
> Myth-Auth calls authentication check and calls getCookie.

Are you saying that the error occurs because the Myth Auth controller filter works when running via CLI?

Personally, I think CLIRequest should have all the methods that IncommingRequest has.
In this case, `getCookie()` that returns null.

**Comment by sclubricants** [comment]
>Are you saying that the error occurs because the Myth Auth controller filter works when running via CLI?

Yes. I have everything locked down except a public route. But even calling the public route its running this check() method. I can't recall all the details of how I set it up though.

>Personally, I think CLIRequest should have all the methods that IncommingRequest has.

I agree! This is why I made the issue here and not on Myth-Auth. The set_cookie() method doesn't seem to have any issues because its on the response object. By the same logic you would need to cut the headers out of the response for a CLIResponse. But this is unnecessary.

We should add the getCookie() method returning null.

**Comment by sclubricants** [comment]
It seems a lot of these methods could be on the Request class and then override where needed. This might be better than adding them all to CLIRequest.

I sent PR to add this method to CLIRequest for now.

**Comment by sclubricants** [comment]
isAJAX() is another method that could potentially cause errors. The scripts that I have the cookie error with I use for both CLI and ajax. I don't use the isAJAX() method though so haven't had the error but its a possibility.

**Comment by kenjis** [comment]
> It seems a lot of these methods could be on the Request class and then override where needed. This might be better than adding them all to CLIRequest.

It is not clear what the current Request class is.
Or it has too many responsibilities. See #6573
