### ISSUE TITLE
Dev: remove self-closing HTML tags in helpers

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#6649]
> The W3C validator displays a warning for : Self-closing tag syntax in text/html documents is widely discouraged.

See
- https://github.com/codeigniter4/CodeIgniter4/issues/6602#issuecomment-1268432153
- https://forum.codeigniter.com/showthread.php?tid=83552

**Comment by visserrobin** [comment]
I made the changes in form_helper.php, not sure how to commit the changes or does the branch on the right hand side have the commit included? Sorry, newbie.....

**Comment by sclubricants** [comment]
>The spec has changed. Now, "void" or "self-closing" elements should not include the slash, when served as HTML 5 doctype. However, if it is being served as XHTML, the closing slash may be required (check the docs in this case). In practical use, pages will usually display as expected even if the closing / has been included, but this is not gauranteed (it is dependent on the browser effectively re-writing the code for you, and interpreting it as you intended.) Also, if for some reason your page is required to pass HTML 5 validation, it might not pass if you close tags for void elements.

https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5

**Comment by paulbalandan** [comment]
Closed by #6789
