### ISSUE TITLE
Bug:  Unable to use table alias when using the function getFieldData

### ISSUE THREAD

**Issue by mrelliot69** [codeigniter4/CodeIgniter4#6694]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

Mysql

### What happened?

Type: mysqli_sql_exception

Message: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`l`' at line 1

### Steps to Reproduce

set the var $this->table to
"tablename tablealias"
        $this->table = 'tablename tablealias';

### Expected Output

The metafields returned by the function getFieldData

**Comment by kenjis** [comment]
You misuse Model. Model is not QueryBuilder.

> Specifies the database table that this model primarily works with. 
https://codeigniter4.github.io/CodeIgniter4/models/model.html#table

`tablename tablealias` is not a table name.

**Comment by mrelliot69** [comment]
so how to i set a table alias?

**Comment by kenjis** [comment]
`CodeIgniter\Model` does not need it.

> The CodeIgniter’s Model provides convenience features and additional functionality that people commonly use to make working with a single table in your database more convenient.
https://codeigniter4.github.io/CodeIgniter4/models/model.html#id2
