### ISSUE TITLE
Bug: Model's Event Data structure inconsistency

### ISSUE THREAD

**Issue by altrusl** [codeigniter4/CodeIgniter4#6701]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.2

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

fpm-fcgi

### Database

MySQL 8.0

### What happened?

Model events

```    
protected $afterFind = ['normalizeData'];

protected function normalizeData(array $data) {    
    var_dump($data);
    exit;
}
```

Output on Ubuntu 20.02

```
array(4) {
--
  | ["id"]=>
  | NULL
  | ["data"]=>
  | array(1) {
  | [0]=>
  | object(stdClass)#76 (1) {
  | ["data"]=>
  | string(1461) "[{"payload": {"action":
...
```

Output on Windows 10

```
 array(4) {
-- | --
  | ["id"]=>
  | string(1) "2"
  | ["data"]=>
  | object(stdClass)#72 (1) {
  | ["data"]=>
  | string(3311) "[{"payload": {"action":
...
```

On Linux $data["data"] is an array with single element (object representing a table row)
On Windows it's that object

Also $data["id"] is NULL on Linux and number on Windows

### Steps to Reproduce

Environments:

- Ubuntu, Nginx, MySQL 8, PHP 8.1, CodeIgniter 4.1.2, php-mysqli
- Windows 10, Nginx, PHP 8.1, CodeIgniter 4.1.2, php-mysqli

### Expected Output

Data structure should be the same - either an array of objects, or an object

**Comment by kenjis** [comment]
Thank you for reporting.
Please check the latest version v4.2.7.

**Comment by altrusl** [comment]
It's the same with CI v4.2.7.

**Comment by kenjis** [comment]
On macOS, when `$returnType` is `array`, the `$data` is something like this:
```
array(4) {
  'id' =>
  int(1)
  'data' =>
  array(7) {
    'id' =>
    int(1)
    'name' =>
    string(11) "Derek Jones"
    'email' =>
    string(15) "derek@world.com"
    'country' =>
    string(2) "US"
    'created_at' =>
    NULL
    'updated_at' =>
    NULL
    'deleted_at' =>
    NULL
  }
  'method' =>
  string(4) "find"
  'singleton' =>
  bool(true)
}
```
when `$returnType` is `object`:
```
array(4) {
  'id' =>
  int(1)
  'data' =>
  class stdClass#94 (7) {
    public $id =>
    int(1)
    public $name =>
    string(11) "Derek Jones"
    public $email =>
    string(15) "derek@world.com"
    public $country =>
    string(2) "US"
    public $created_at =>
    NULL
    public $updated_at =>
    NULL
    public $deleted_at =>
    NULL
  }
  'method' =>
  string(4) "find"
  'singleton' =>
  bool(true)
}
```

**Comment by kenjis** [comment]
I don't know why the results are different between Windows and Ubuntu.
The database data and the code you run are exactly the same?

**Comment by altrusl** [comment]
Yes, the same code and one database
May be it's because of JSON column?

```
CREATE TABLE `game_session` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`playerId` INT(10) NOT NULL DEFAULT '0',
	`data` JSON NULL DEFAULT 'json_array()',
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
```

**Comment by kenjis** [comment]
Can you show the minimum code to reproduce that works?

**Comment by altrusl** [comment]
I'm sorry, I just now had time to test this issue.
Unfortunately, I have already changed the database schema and code. I tried rolling back and I think I found the problem. The databases did seem to be different, but when I use the Model->find(id) method with an existing `id`, everything is fine. When a row with such `id` does not exist in the table, then `$data` is obtained like this:
```
array(4) {
["id"]=>
NULL
["data"]=>
array(85) {
[0]=>
object(stdClass)#70 (1) {
_... all rows from the table_
```

```
protected $afterFind = ['normalizeData'];
protected function normalizeData(array $data) {
var_dump($data);
}
```

That is, $data['data'] contains all the data from the table
Is it right?

**Comment by kenjis** [comment]
`Model::find(null)` returns all rows from the table.
In that case, you will get something like this:
```
array(4) {
  'id' =>
  NULL
  'data' =>
  array(4) {
    [0] =>
    class stdClass#94 (7) {
    ... // all rows from the table
```
But if you specify the id that does not exist like `Model::find(999)` ,
you will see:
```
array(4) {
  'id' =>
  int(999)
  'data' =>
  NULL
  'method' =>
  string(4) "find"
  'singleton' =>
  bool(true)
}
```

**Comment by altrusl** [comment]
Yes, that was NULL
Sorry for the mess
Thank you

**Comment by altrusl** [comment]
Not a bug
