### ISSUE TITLE
CSRF Incidents

### ISSUE THREAD

**Issue by donpwinston** [codeigniter4/CodeIgniter4#6719]
Please write a message to the log when a CSRF event occurs or provide a way for the developer to do so. I spent two days trying to figure out why an external app failed to post a file upload. All I got was a 303 in Apache's log.

**Comment by kenjis** [comment]
Sorry for inconvenience.
The default setting will be changed to throwing Exception since v4.3.0.
> Changed the default setting to not redirect when a CSRF check fails so that it is easy to see that it is a CSRF error.
https://github.com/codeigniter4/CodeIgniter4/blob/4.3/user_guide_src/source/changelogs/v4.3.0.rst#changes

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
