### ISSUE TITLE
Bug: Cache does not respect subdomain

### ISSUE THREAD

**Issue by c4user** [codeigniter4/CodeIgniter4#6746]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.7

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySQL 

### What happened?

Cache always creates a filename (key) using the hostname. For this reason, cache does not work when using a route with limit a subdomain. For example, when the cache is enabled, it doesn't matter whether it is stored for xxx.domain.com or yyy.domain.com. It shows the same content in both addresses. 

### Steps to Reproduce

-

### Expected Output

It is expected to produce content based on subdomains.

Cache must be compatible with subdomains.

**Comment by kenjis** [comment]
I think #6785 fixes the bug.
Can you try `4.3` branch?

**Comment by kenjis** [comment]
Closed by #6785
