### ISSUE TITLE
Bug: Time is not immutable

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#6762]
According to the User Guide, `Time` has been stated **immutable** since v4.0.0-alpha.1:
> CodeIgniter provides a fully-localized, **immutable**, date/time class that is built on PHP's DateTime object, but uses the Intl extension's features to convert times across timezones and display the output correctly for different locales. This class is the Time class and lives in the CodeIgniter\I18n namespace.
https://github.com/codeigniter4/CodeIgniter4/blob/v4.0.0-alpha.1/user_guide_src/source/libraries/time.rst

And all the methods implemented in `Time` are immutable.

But `Time` extends `DateTime` which is mutable, and there are some methods that are not overridden by `Time`.
Therefore the following methods will mutate the current object:
* __construct()
* add()
* modify()
* setDate()
* setISODate()
* setTime()
* sub()

As a result, the current `Time` is a class that most of the methods are immutable but some are mutable.
This is very bad design and extremely difficult to use.

See https://github.com/codeigniter4/CodeIgniter4/pull/6752#discussion_r1005525320

**Comment by InsiteFX** [comment]
I would say fix it before it gets to far out of control.

**Comment by kenjis** [comment]
Closed by #6771
