### ISSUE TITLE
Bug: `spark key:generate` doesn't generate `encryption.key` if no template

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#6838]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.10

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

Try deleting all entries in `.env` so you can sort out which ones to use.
But when running `spark key:generate` no `encryption.key` is created even though the message on the shell is successful.

### Steps to Reproduce

remove all `.env` then run `php spark key:generate`

### Expected Output

In `.env` should create `encryption.key =` even without template

**Comment by paulbalandan** [comment]
You mean you cleared the contents of `.env`?

**Comment by datamweb** [comment]
> > You mean you cleared the contents of `.env`?
> 
> yes

The question is, why should you delete the contents of this file?

**Comment by paulbalandan** [comment]
I'm not sure which behavior is more intuitive to handle such edge case:
1. Output the generated key to the terminal instead, like using the `--show` flag; or
2. Adding the line if not found in the .env

**Comment by datamweb** [comment]
I chose the second option.😀

**Comment by paulbalandan** [comment]
Fix is underway.
