### ISSUE TITLE
Automated Codeigniter upgrades like LARAVEL SHIFT

### ISSUE THREAD

**Issue by LawrenceAddo** [codeigniter4/CodeIgniter4#6888]
I am wondering if there is a solution that helps to provide automated Codeigniter upgrades like LARAVEL SHIFT?

see here   https://laravelshift.com/

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

As far as I know, there is no such thing.
