### ISSUE TITLE
mysqli_sql_exception. error if there are spaces in my user folder name

### ISSUE THREAD

**Issue by DCreati** [codeigniter4/CodeIgniter4#6904]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.10

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 8.0.31

### What happened?

```
SELECT * FROM 'settings' WHERE 'context' IS NULL
SELECT GET_LOCK('41c409f5e688a472d5fec9021721b373', 300) AS ci_session_lock
SELECT 'data' FROM 'C:\Users\Martin' 'Dovey\Documents\ppj\writable\session' WHERE 'id' = '373rcak46gc9mvvfv9b536jd5gcfsc58' AND 'ip_address' = '::1' 
```

this query generated this error:
#0 C:\Users\Martin Dovey\Documents\ppj\vendor\codeigniter4\codeigniter4\system\Database\MySQLi\Connection.php(292): mysqli->query()

the problem is that my user folder contains spaces and this prevents the application from executing the code correctly.

### Steps to Reproduce

the error reported by app when i start it

### Expected Output

the folder "Martin Dovey" is considered as unique and not separate

**Comment by kenjis** [comment]
Please provide steps how to reproduce.

Do you have the table named `C:\Users\Martin Dovey`?
Why do you use such a strange table name?

**Comment by paulbalandan** [comment]
Why are you using a file path as the table name? `WRITABLE . 'session'` should only be used for session if you are using the file handler. Otherwise, you must set the correct database table name.

**Comment by paulbalandan** [comment]
This looks like a misuse.

**Comment by paulbalandan** [comment]
No further info provided.
