### ISSUE TITLE
Yes

### ISSUE THREAD

**Issue by mackxpall** [codeigniter4/CodeIgniter4#6905]
Yes

_Originally posted by @mackxpall in https://github.com/iamkun/dayjs/issues/2138#issuecomment-1326589233_

**Comment by cijagani** [comment]
Seems like spam.

**Comment by datamweb** [comment]
https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam

**Comment by mackxpall** [comment]
> Seems like spam.

Like the canned meet?

**Comment by mackxpall** [comment]
https://github.com/mackxpall/Logic-x-Logic-to-the-tenth./issues/1
