### ISSUE TITLE
`$cleanValidationRules` in model is not working

### ISSUE THREAD

**Issue by SyedMuradAliShah** [codeigniter4/CodeIgniter4#6918]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.10

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.6.7

### What happened?

I'm arising the issue again `$cleanValidationRules`.  Its still not working, even `cleanRules()` while using method `insert()`, `insertBatch()` or `save()`.

### Steps to Reproduce

In the model set `$validationRules` and then set `$cleanValidationRules = true`.

### Expected Output

We exepct the required rules to be removed if the data is not passed.

**Comment by SyedMuradAliShah** [comment]
After dig down the `BaseModel.php` , I came to know that some lines there which making it.

```
        // Set $cleanValidationRules to false temporary.
        $cleanValidationRules       = $this->cleanValidationRules;
        $this->cleanValidationRules = false;
```

```
            // Restore $cleanValidationRules
            $this->cleanValidationRules = $cleanValidationRules;
```

```
        // Restore $cleanValidationRules
        $this->cleanValidationRules = $cleanValidationRules;
```
The above statements are in methods `insert()`, `insertBatch()`. These statements are actually causing the issue if we remove them, it works perfectly for `insert()`, `insertBatch()`, `save()`.

I'm not making the pull request, I want someone expert to test it further for now its working for me.

Line 706: [BaseModel.php Line:706](https://github.com/codeigniter4/CodeIgniter4/blob/2a33c1fe714118d9c79a91b2d941e1dae58afdb4/system/BaseModel.php#L706)

Line 788: [BaseModel.php Line:788](https://github.com/codeigniter4/CodeIgniter4/blob/2a33c1fe714118d9c79a91b2d941e1dae58afdb4/system/BaseModel.php#L788)

**Comment by kenjis** [comment]
This is not a bug. It is intentional.

> Whether validation rules should be removed that do not exist in the passed data. This is used in updates. 
https://codeigniter4.github.io/CodeIgniter4/models/model.html#clean-validation-rules

Why do you need to remove rules when you insert?

**Comment by SyedMuradAliShah** [comment]
Here in documentation I can see that its a bug.
> https://codeigniter4.github.io/CodeIgniter4/models/model.html#clean-validation-rules
> Prior to v4.2.7, `$cleanValidationRules` did not work due to a bugs

When I read `BaseModel`, in the `insert()` the `cleanValidationRules` setting up as false, before transforming data, which is causing issue of removing validation for non passed data.

Removing that lines helped to solve the issue, when we pass data to model,  so the validation will be removed for non passed data.

**Comment by kenjis** [comment]
No. $cleanValidationRules works for updates only.
Prior to v4.2.7 it did not work at all.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
