### ISSUE TITLE
Dev: drop PHP 7.4 support

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#6921]
PHP 7.4 reached the end of life on 28 Nov 2022.
https://www.php.net/supported-versions.php

- [x] update minimum version to PHP 8.0
  - #7924 
- [x] update PSR\Log to v3. See #4936
- [x] update PSR\Log to v2
  - #7967 
- [x] refactor for PHP 8.0
  - #8354 
  - #7964

**Comment by juanma386** [comment]
Good option, need mind on news updates made from php8.2 not old dangerous versions on php7

**Comment by kenjis** [comment]
I would like to drop 7.4 support in v4.5.

**Comment by neznaika0** [comment]
I like. But do you think it is necessary to include features from 8.0 - 8.2? Enum, read only.. and update the old features? As in my case str_starts_with

**Comment by kenjis** [comment]
If we drop 7.4, we can use new features in 8.0. But all code must run in PHP 8.0, so we cannot use new features in 8.1 or 8.2.

**Comment by kenjis** [comment]
Now PHP 7.4's share is 25%.
![Screenshot 2024-02-15 14 09 01](https://github.com/codeigniter4/CodeIgniter4/assets/87955/b9e6ab1c-ed7f-4d3d-83fa-592d1cb91b0b)
https://packagist.org/packages/codeigniter4/framework/php-stats#all

**Comment by aslanutku** [comment]
> Now PHP 7.4's share is 25%. ![Screenshot 2024-02-15 14 09 01](https://private-user-images.githubusercontent.com/87955/304956761-b9e6ab1c-ed7f-4d3d-83fa-592d1cb91b0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDg1MDAsIm5iZiI6MTcwOTg0ODIwMCwicGF0aCI6Ii84Nzk1NS8zMDQ5NTY3NjEtYjllNmFiMWMtZWQ3Zi00ZDNkLTgzZmEtNTkyZDFjYjkxYjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIxNTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZTkzYmYwNjA5M2UwZDM1M2FkODkyZjI3OTcwZGIzM2EwNDg0Njg4NDQwOGIzNDUxMDM3MzZjNGQyNDIwMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5GIcYyzBWQwthNi8Yu6pt1iDZ7DsprsE8tb_o2hKZFc) https://packagist.org/packages/codeigniter4/framework/php-stats#all

Greetings,

Could you share any information on when PHP 7.4 support will end for CodeIgniter 4? I'm facing challenges installing new packages because of dependency issues related to older versions, notably with `psr/log`. Your insight would greatly help in planning for future project upgrades and overcoming these installation hurdles.

Thank you.

**Comment by kenjis** [comment]
@aslanutku v4.5.0 will drop PHP 7.4 support.
I do not know when that can be released, but I personally would like to do it as soon as possible.
I hope to release it within a month or at the latest within a couple of months.
However, if the reviews do not proceed, the release cannot be made.

**Comment by kenjis** [comment]
Now PHP 7.4 is 10.9%, and 8.0 is 8.2%.
![Screenshot 2024-04-06 9 56 08](https://github.com/codeigniter4/CodeIgniter4/assets/87955/b86811cf-813e-4304-abbf-ec6400bca57e)

**Comment by kenjis** [comment]
Closed by #8354
