### ISSUE TITLE
[Docs]: PDO driver not supported

### ISSUE THREAD

**Issue by ampmonteiro** [codeigniter4/CodeIgniter4#6932]
### PHP Version

7.3, 7.4, 8.0, 8.1

### CodeIgniter4 Version

4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS, Windows, Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

In sequence of this issue https://github.com/codeigniter4/CodeIgniter4/issues/3922,
In the Docs > Databases >  'Database Configuration)' section as well as in 'Connect to Your Database' in 'Build Your First Application', should be mentioned that PDO driver is not supported.

### Steps to Reproduce

-

### Expected Output

-

**Comment by sclubricants** [comment]
Why would you want to use pdo mysql over mysqli?

I have begun working on a PDO ODBC driver but it has a lot of work to do.

**Comment by kenjis** [comment]
It is documented in Server Requirements:
https://codeigniter4.github.io/CodeIgniter4/intro/requirements.html

**Comment by kenjis** [comment]
I sent a PR #6933

**Comment by ampmonteiro** [comment]
@sclubricants 

PDO was created for a reason.

PDO base drives exist since php 5.1, why not use it?

Others frameworks use it, why not CI ?

@kenjis 

English is not my native lang.

So i Think the text should be clear. Something like,  " PDO drivers base are not supported."

This should be clear in 3 places:
- in requirements section
- in Databases > 'Database Configuration' section
-  in 'Connect to Your Database' in 'Build Your First Application'

Thanks

**Comment by kenjis** [comment]
We will accept your contributions. You could write PDO drivers and send PRs.

> CodeIgniter is a community driven project and accepts contributions of code and documentation from the community. These contributions are made in the form of Issues or [Pull Requests](https://help.github.com/articles/using-pull-requests/) on the [CodeIgniter4 repository](https://github.com/codeigniter4/CodeIgniter4) on GitHub.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/README.md

> I think with PDO the code would be more clean and reusable.

If you say about your application code, no. Your code will hardly change.

**Comment by kenjis** [comment]
I think my PR is sufficient.
It is clearly documented. It is obvious that PDO is not supported now.

```rst
*******************
Supported Databases
*******************

A database is required for most web application programming.
Currently supported databases are:

  - MySQL via the *MySQLi* driver (version 5.1 and above only)
  - PostgreSQL via the *Postgre* driver
  - SQLite3 via the *SQLite3* driver
  - MSSQL via the *SQLSRV* driver (version 2005 and above only)
  - Oracle via the *OCI8* driver (version 12.1 and above only)
```

**Comment by ampmonteiro** [comment]
@kenjis 

if you think so, then  you can close the issue.

Thanks.
