### ISSUE TITLE
Bug: Entity is not returning the blank value field

### ISSUE THREAD

**Issue by DhPandya** [codeigniter4/CodeIgniter4#6950]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 8.0.27

### What happened?

An entity does not return the column value if an Empty or null value is passed.

### Steps to Reproduce

1. Install CodeIgniter 4 Using Composer
2. Create one model whose return type is Entity
3. Now use set (Ex. setDateOut) in the Entity.
4. Now fill the date_out filed once
5. Now update the date_out field by Empty or null.
6. Now an entity will not return the date_out field in the attributes array.

### Expected Output

If the column is allowed null values from the database and if the Entity is been configured according to that, then it should return that null valued Keys in the **attributes** array.

**Comment by kenjis** [comment]
Can you show the minimum code to reproduce?

**Comment by DhPandya** [comment]
> Can you show the minimum code to reproduce?


```
//Entity
public function setDateOut($date_out)
    {
        if (!empty($date_out)) {
            $date = DateTime::createFromFormat('M d, Y h:i A', $date_out);
            $this->attributes['date_out'] = $date->format('Y-m-d H:i');
            return $this;
        }        
    }
```

In the Controller
`$order_entity->date_out = $posted_data['date_out'];`

**Comment by kenjis** [comment]
`null` is empty.
https://3v4l.org/vvAiO

**Comment by DhPandya** [comment]
> `null` is empty. https://3v4l.org/vvAiO

Yes but even i passed empty to the value, Entity doesn't returned that particular field.

**Comment by kenjis** [comment]
I don't get your issue.

Can you show the sample code?
Now use set (Ex. setDateOut) in the Entity.
Now fill the date_out filed once
Now update the date_out field by Empty or null.
Now an entity will not return the date_out field in the attributes array.

**Comment by DhPandya** [comment]
> I don't get your issue.
> 
> Can you show the sample code? Now use set (Ex. setDateOut) in the Entity. Now fill the date_out filed once Now update the date_out field by Empty or null. Now an entity will not return the date_out field in the attributes array.

```
//Controller
$posted_data = $this->request->getPost();
$order_entity = new OrderEntity();
$order_entity->date_out = $posted_data['date_out']; // Sometimes it contains the date sometimes not.
$success = $this->order_model->save($order_entity);

//Entity
public function setDateOut($date_out)
    {
        if (!empty($date_out)) {
            $date = DateTime::createFromFormat('M d, Y h:i A', $date_out);
            $this->attributes['date_out'] = $date->format('Y-m-d H:i');
        }
        return $this;
    }
```
Below is the Data that Entity returned when I used _set() 
![image](https://user-images.githubusercontent.com/46279781/206132186-31412f39-0fa5-4227-a4a2-4fcadec4717b.png)

Below is the Data that Entity returns when I don't used _set()
![image](https://user-images.githubusercontent.com/46279781/206132732-3a3ddd90-8231-426f-95a4-118c9c620c41.png)

**Comment by kenjis** [comment]
> Below is the Data that Entity returned when I used _set()

What is the `_set()`?

**Comment by DhPandya** [comment]
> > Below is the Data that Entity returned when I used _set()
> 
> What is the `_set()`?

Entity concept for the Data mutation.
getter() setter() methods.
In this case, I want to format the date before it passes in the model.
So I've created the setDateOut() method in the entity.

**Comment by DhPandya** [comment]
> Do you want to set `$this->attributes['date_out']` to `null`?
> 
> ```
>     public function setDateOut($date_out)
>     {
>         if (!empty($date_out)) {
>             $date = DateTime::createFromFormat('M d, Y h:i A', $date_out);
>             $this->attributes['date_out'] = $date->format('Y-m-d H:i');
>             return $this;
>         } else {
>             $this->attributes['date_out'] = null;
>             return $this;
>         ]
>     }
> ```

Yes @kenjis.
Thanks for the valuable suggestion.
