### ISSUE TITLE
Bug: [Cookie] validatePrefix function can not understand bool var even if its a boolean var

### ISSUE THREAD

**Issue by Slamoth** [codeigniter4/CodeIgniter4#6982]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.10

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

Postgres

### What happened?

I have an application with benedmunds IONAuth integrated with it. I can login to the site with no problem.
But when I logout protected function validatePrefix in `vendor/codeigniter4/framework/system/Cookie/Cookie.php`throws an error like below.

```
TypeError
CodeIgniter\Cookie\Cookie::validatePrefix(): Argument #2 ($secure) must be of type bool, null given, called in /srv/www/htdocs/vendor/codeigniter4/framework/system/Cookie/Cookie.php on line 226
```

![image](https://user-images.githubusercontent.com/6489169/208049422-22ba5a00-181d-430a-b60a-b58baa8256d0.png)

The line 222 on that file sets secure flag for cookie from App.php in config directory with `$secure   = $options['secure'];`
But it seems that `validatePrefix`function can not understand that if the variable is type of bool or not.

I used dd($secure) and the result is
```
$secure boolean false
```
but validatePrefix function can not decide !

When I change the line 222 `$secure   = $options['secure'];` to `$secure   = (bool)$options['secure'];` everything works fine.

### Steps to Reproduce

Login with IONAuth login page (http://somesite.com/auth/login) and logout with (http://somsite.com/auth/logout)

### Expected Output

redirection to login page.

**Comment by Slamoth** [comment]
Sorry for disruption. Found out what is wrong. the bug is not about CI4 infrastructure. Its a bug about IonAuth.
If anyone using it there is something called rememberCookieName on `vendor/benedmunds/codeigniter-ion-auth/Libraries/IonAuth.php`on line 414. It actually tries to delete a cookie while its not even there so incoming null is expected.

if we change that file to
```php
		// delete the remember me cookies if they exist
		if (isset($_COOKIE[$this->config->rememberCookieName])) {
            delete_cookie($this->config->rememberCookieName);
        }
```
everything works as expected

**Comment by kenjis** [comment]
I tested the following code, but cannot reproduce the TypeError.

```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        helper('cookie');

        delete_cookie('remember_code');
    }
}
```

**Comment by Slamoth** [comment]
no need @kenjis. got it figured it out. Its because of IonAıth...
