### ISSUE TITLE
Undefined variable $uploaded_fileinfo on https://codeigniter4.github.io/userguide/libraries/uploaded_files.html#the-success-page

### ISSUE THREAD

**Issue by SergeTkach** [codeigniter4/CodeIgniter4#7008]
### PHP Version

8.1

### CodeIgniter4 Version

4.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB

### What happened?

I get error with file uploading

ErrorException
Undefined variable $uploaded_fileinfo
APPPATH\Views\common\upload_success.php at line 11

### Steps to Reproduce

I have created script by instructions in documentation -- https://codeigniter4.github.io/userguide/libraries/uploaded_files.html#creating-the-upload-form

I understand that there is an mistake in documentation near:

`$data = ['uploaded_flleinfo' => new File($filepath)];`
It need to be:
`$data = ['uploaded_fileinfo' => new File($filepath)];`

I mean there is char **l** instead of **i** in substring 'file'

### Expected Output

Return file info after uploading

### Anything else?

I have found mistake n documentation and described it

**Comment by kenjis** [comment]
Yes, it is a typo.
