### ISSUE TITLE
Bug: The getFiles method of \CodeIgniter\Events class is declared as 'public', but it should probably be 'public static'.

### ISSUE THREAD

**Issue by benedict-tshaba** [codeigniter4/CodeIgniter4#7045]
### PHP Version

8.2

### CodeIgniter4 Version

4.2.11

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

The getFiles method of \CodeIgniter\Events class is declared as 'public', but it should probably be 'public static'?

### Steps to Reproduce

Just try to make this call (which will throw an error since the getFiles is not static, and its an anti-pattern to instantiate the Events class just to be able to call this method.):
\CodeIgniter\Events\Events::getFiles();

### Expected Output

A list of Events.php config file locations.

### Anything else?

We ran into this issue while trying to implement a solution that requires us to get a list of those locations, our system is a web-based configuration for installations were you don't have access to modify the files on the drive.

Our current workaround was just to patch the class to add the static keyword to that method definition and update our installation. Just wondering if there is maybe a valid reason why the getFiles method is not public static and if maybe we should change it to include the static keyword.

**Comment by kenjis** [comment]
The properties in the Event class are all static and all methods other than getFiles() are static.
So I agree that the method should be static.

**Comment by MGatner** [comment]
That looks like just a typo to me. It will still work in an instantiated object even if we change it to `static` so let's do just that. @benedict-tshaba Would you send a PR for this please? Literally just add the word `static` - you can donut through GitHub's UI if you're not comfortable with the workflow, it will guide you.
