### ISSUE TITLE
Bug: Use of boolean instead of bool

### ISSUE THREAD

**Issue by donpwinston** [codeigniter4/CodeIgniter4#7048]
### PHP Version

8.2

### CodeIgniter4 Version

4.2.10

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS, Linux

### Which server did you use?

apache

### What happened?

VSCODE Intellisense detected improper type "boolean". Should be "bool".

app/Config/Cache.php line 137

### Steps to Reproduce

See app/Config/Cache.php line 137

### Expected Output

Get error reported by VSCode's Intellisense

**Comment by ddevsr** [comment]
I dont see any error

**Comment by paulbalandan** [comment]
I'm using vscode and does not see any error. In any case, can you send PR for the change?

**Comment by donpwinston** [comment]
I'm using the PHP DEVSENSE extension also. There's no "boolean" in php. It must be "bool". 

    On Wednesday, January 4, 2023 at 06:09:07 AM EST, John Paul E. Balandan, CPA ***@***.***> wrote:  
 
 


I'm using vscode and does not see any error. In any case, can you send PR for the change?

**Comment by kenjis** [comment]
phpDocumentor permits `boolean`.
https://docs.phpdoc.org/3.0/guide/references/phpdoc/types.html#definition-of-a-type

But PSR-5 does not permit `boolean`.
https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#keyword

We accept PR for the change!

**Comment by ddevsr** [comment]
Ah i see, PSR-5 accept `bool` not `boolean.

I send PR #7051.

**Comment by kenjis** [comment]
But now PSR-5 is a draft, not accepted yet.
