### ISSUE TITLE
Bug: BaseBuilder::setBind can cause name conflict

### ISSUE THREAD

**Issue by Martin-4Spaces** [codeigniter4/CodeIgniter4#7049]
### PHP Version

8.0

### CodeIgniter4 Version

4.2.11

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### What happened?

I encountered wrong SQL when using keys ending in ".1". 

### Steps to Reproduce

Take a look at this simplified, silly, example. And how the binds array overwrites the key `name.1` when entering `name` twice.
```php
    $model = new ProjectModel();
    $model->where('name.1', 'test1');
    // Bind array: [
    // name.1 => test1
    //]

    $model->where('name', 'test2');
    // Bind array: [
    // name.1 => test1
    // name => test2
    //]

    $model->where('name', 'test3');
    // Bind array: [
    // name.1 => test3
    // name => test2
    //]
```

### Expected Output

I expect the bind array not to overwrite existing keys.

### Anything else?

A few suggestions..

Here is the `setBind()` method
```php
    protected function setBind(string $key, $value = null, bool $escape = true): string
    {
        if (! array_key_exists($key, $this->binds)) {
            $this->binds[$key] = [
                $value,
                $escape,
            ];

            return $key;
        }

        if (! array_key_exists($key, $this->bindsKeyCount)) {
            $this->bindsKeyCount[$key] = 1;
        }

        $count = $this->bindsKeyCount[$key]++;

        $this->binds[$key . '.' . $count] = [
            $value,
            $escape,
        ];

        return $key . '.' . $count;
    }
```

If we put all keys into `bindsKeyCount`, we would catch this issue. But this will have negative memory impact. 
Instead we could implement recursive name checking.

**Comment by kenjis** [comment]
This is not a bug.

> CodeIgniter doesn’t support dots (.) in the database, table, and column names.
https://codeigniter4.github.io/CodeIgniter4/database/queries.html#query-basics

**Comment by Martin-4Spaces** [comment]
Aha, fair enough then.
I managed to bypass the limitation by extending BaseBuilder. So I can support my use case.
If the decision is not to support this, you can just as well close this issue.

**Comment by kenjis** [comment]
An identifier may be consist of `hostname.database.table.column`.
So it is not easy if dot is used in them.
