### ISSUE TITLE
Bug:  Dev Toolbar Load heavily and Hang Browser

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#7058]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.11

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli

### What happened?

When I am on development mood my script load normal and after the developer toolbar load the browser will start to hang or responds slowly. 

Another  bug

When I switch to production mood, the developer toolbar still show.

### Steps to Reproduce

I try debugging to see where this error is coming from

I try editing the Toolbar Class on 

```php

   /**
     * Inject debug toolbar into the response.
     *
     * @codeCoverageIgnore
     */
    public function respond()
    {
        if (ENVIRONMENT === 'testing') {
            return;
        }

        $request = Services::request();
```

To this to see if my script will load fine and it does 

```php

 /**
     * Inject debug toolbar into the response.
     *
     * @codeCoverageIgnore
     */
    public function respond()
    {
        if (ENVIRONMENT === 'testing' || ENVIRONMENT === 'production') {
            return;
        }

        $request = Services::request();
```

### Expected Output

...

**Comment by kenjis** [comment]
Cannot reproduce.
Please show us minimum steps to reproduce.

**Comment by kenjis** [comment]
> When I switch to production mood, the developer toolbar still show.

https://github.com/codeigniter4/CodeIgniter4/blob/d8d52757b38c16a836e5296c331ecf9a6e9f324d/app/Config/Events.php#L44-L47
If `CI_DEBUG` is not true, `Services::toolbar()->respond()` is not called.

**Comment by ChibuezeAgwuDennis** [comment]
> > When I switch to production mood, the developer toolbar still show.
> 
> https://github.com/codeigniter4/CodeIgniter4/blob/d8d52757b38c16a836e5296c331ecf9a6e9f324d/app/Config/Events.php#L44-L47
> 
> If `CI_DEBUG` is not true, `Services::toolbar()->respond()` is not called.

I am checking on what you said

**Comment by ChibuezeAgwuDennis** [comment]
> > > When I switch to production mood, the developer toolbar still show.
> > 
> > 
> > https://github.com/codeigniter4/CodeIgniter4/blob/d8d52757b38c16a836e5296c331ecf9a6e9f324d/app/Config/Events.php#L44-L47
> > 
> > If `CI_DEBUG` is not true, `Services::toolbar()->respond()` is not called.
> 
> I am checking on what you said

![image](https://user-images.githubusercontent.com/53615067/211119343-1d22dd72-a62b-4819-9c4a-9e73c30b0d1f.png)

in production it is returning 

![image](https://user-images.githubusercontent.com/53615067/211119704-dd3db81e-6170-45f7-8355-bcf32b91efa8.png)

**Comment by ChibuezeAgwuDennis** [comment]
> > > > When I switch to production mood, the developer toolbar still show.
> > > 
> > > 
> > > https://github.com/codeigniter4/CodeIgniter4/blob/d8d52757b38c16a836e5296c331ecf9a6e9f324d/app/Config/Events.php#L44-L47
> > > 
> > > If `CI_DEBUG` is not true, `Services::toolbar()->respond()` is not called.
> > 
> > 
> > I am checking on what you said
> 
> ![image](https://user-images.githubusercontent.com/53615067/211119343-1d22dd72-a62b-4819-9c4a-9e73c30b0d1f.png)
> 
> in production it is returning
> 
> ![image](https://user-images.githubusercontent.com/53615067/211119704-dd3db81e-6170-45f7-8355-bcf32b91efa8.png)

I have fixed this CI_ENVIRONMENT = production displaying true but what of the hanging on browser

**Comment by kenjis** [comment]
`CI_DEBUG` is set to false in
https://github.com/codeigniter4/CodeIgniter4/blob/d8d52757b38c16a836e5296c331ecf9a6e9f324d/app/Config/Boot/production.php#L21
unless you define it before the code above.

**Comment by ChibuezeAgwuDennis** [comment]
I have fixed the always true issue.
But what of the slow loading or hanging of browser when on development mood. 
or is it conflicting anything or heavy loading

**Comment by paulbalandan** [comment]
> But what of the slow loading or hanging of browser when on development mood.

Please provide minimum steps to reproduce the slow loading or hanging browser. Without the steps, we can only assume it's a problem with your code and not of the framework.
