### ISSUE TITLE
Bug: Unable to connect to the database when customizing Config/Database.php

### ISSUE THREAD

**Issue by h-shaktawat-dw** [codeigniter4/CodeIgniter4#7064]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.11

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.2.0

### What happened?

When create project and set environment variable based on `$_SERVER['HTTP_HOST']`, then set base_url based on environment variable, after this set database connect in **app/Config/Database.php.** on staging server database not get based on conditions, only connect for default variable configurations instead of staging variable configurations in Database.php

if change code in **vendor\codeigniter4\framework\system\Database\Config.php**  for condition 

```php
if (empty($group)) {
   $group = ENVIRONMENT === 'testing' ? 'tests' : $config->defaultGroup;
}
```

as 

```php
$group = ENVIRONMENT === 'testing' ? 'tests' : $config->defaultGroup;
```

it is working fine

### Steps to Reproduce

1. composer create-project codeigniter4/appstarter my-project
2. set ENVIRONMENT variable based on $_SERVER['HTTP_HOST'].
3. set base url based on ENVIRONMENT variable
4. set database connect in app/Config/Database.php based on ENVIRONMENT
5. run project on local and server

### Expected Output

Database connect configurations need to get based on ENVIRONMENT instead of Default only. 

### Anything else?

Log File :: 

CRITICAL - 2023-01-09 11:17:57 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()

**Comment by kenjis** [comment]
Could you show us the exact steps to reproduce?

> set ENVIRONMENT variable based on $_SERVER['HTTP_HOST'].

What ENVIRONMENT variable? and How?

> set base url based on ENVIRONMENT variable

How?

> set database connect in app/Config/Database.php based on ENVIRONMENT

How?

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by h-shaktawat-dw** [comment]
1. Create Project :: composer create-project codeigniter4/appstarter my_project

2. Move index.php and .htaccess at root directory from public folder

3. Update index.php at line number 32
**-> before :** require FCPATH . '../app/Config/Paths.php'; 
**-> after :** require FCPATH . 'app/Config/Paths.php'; 

4. Update index.php before **$app = Config\Services::codeigniter();**
**-> add this code**

   $host = $_SERVER['HTTP_HOST'];
   if ($host == "production.domain") {
       define("ENVIRONMENT", "production");
   } else if ($host == "staging.domain") {
       define("ENVIRONMENT", "staging");
   } else {
       define("ENVIRONMENT", "development");
   }
 
5. Update App.php at app/App.php

**-> add this code**


    // Set base url dynamically
    public function __construct()
    {
        parent::__construct();

        $this->setBaseUrl(); // Set the Base URL
    }

    protected function setBaseUrl()
    {
        switch (ENVIRONMENT) {
            case 'production':
                $this->baseURL = "https://production.com/";
                break;
            case 'staging':
                $this->baseURL = "https://staging.com/";
                break;
            default:
                $this->baseURL = "http://localhost/my_project/";
                break;
        }
    }

6. Update Database.php at app/Database.php

My Code :: 

    public function __construct()
    {
        parent::__construct();

        // Ensure that we always set the database group to 'tests' if
        // we are currently running an automated test suite, so that
        // we don't overwrite live data on accident.

        switch (ENVIRONMENT) {
            case 'production':
                $this->defaultGroup = 'production';
                break;
            case 'staging':
                $this->defaultGroup = 'staging';
                break;
            case 'development':
                $this->defaultGroup = 'development';
                break;
            default:
                $this->defaultGroup = 'default';
                break;
        }
    }

    public $default= []
    public $development = []
    public $staging= []
    public $production= []
    
    Set database configuration for particular environment

**Comment by kenjis** [comment]
It seems your code should work.
How do you connect to the database?

And an attacker may be able to spoof `$_SERVER['HTTP_HOST']` value. 
So it is better to validate the value.

**Comment by kenjis** [comment]
If you still think this is a bug, feel free to reopen.
