### ISSUE TITLE
Bug: Validation on null for trim

### ISSUE THREAD

**Issue by ValdisM** [codeigniter4/CodeIgniter4#7067]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### What happened?

trim() on null is not working for validation.

I suggest to edit: Validation.php Line 302: 

$passed = $param === false ? $rule((string) $value ?? '') : $rule((string) $value ?? '', $param, $data);

### Steps to Reproduce

make rule without a post.

### Expected Output

Expected:\

Previous:
$passed = $param === false ? $rule($value) : $rule($value, $param, $data);

$passed = $param === false ? $rule((string) $value ?? '') : $rule((string) $value ?? '', $param, $data);

**Comment by kenjis** [comment]
Sorry, I don't get what you say. Why do you use `trim()`?
Validation never alters input data.

Can you show exact Steps to Reproduce?

**Comment by kenjis** [comment]
If you still think this is a bug, feel free to reopen.

**Comment by pietos** [comment]
I have the same issue, when you post an empty value on a form validation where you specified trim it results into:

  "message": "trim(): Passing null to parameter #1 ($string) of type string is deprecated",
  "file": "C:\\docker_xampp\\htdocs\\slurpee_portal\\system\\Validation\\Validation.php",

**Comment by kenjis** [comment]
If you specify `trim` in the validation rules, the Validation does not trim the value.
Why do you need to specify `trim` ?

**Comment by pietos** [comment]
Well, the problem is not trim but the function:
permit_empty

in the permit empty they do a trim on the value to see if it's really "", but when the value is NULL this results into this error.

system\Validation\Validation.php

![image](https://github.com/codeigniter4/CodeIgniter4/assets/58322436/4a2ce2bd-bae2-4bbf-9df1-b191b302529a)

**Comment by kenjis** [comment]
Cannot reproduce.
If you can reproduce the error, please create an issue with minimum code to reproduce.

```
php > echo trim(null);
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in php shell code on line 1
PHP Stack trace:
PHP   1. {main}() php shell code:0
PHP   2. trim($string = NULL) php shell code:1
```
```
php > echo trim((string) null);
php > 
```
