### ISSUE TITLE
Missing getting some parameters with route_to() or url_to().

### ISSUE THREAD

**Issue by KS7ven** [codeigniter4/CodeIgniter4#7070]
"route_to" or "url_to" does not take the subdomain option from the "subdomain" parameter passed in the router group.

**Example:**
```php
$routes->group('', ['namespace' => 'App\Controllers', 'subdomain' => 'app'], static function ($routes) {
   $routes->get('login', 'LoginController::loginView', ['as' => 'login']);
   $routes->post('login', 'LoginController::loginAction');
});
```

**Result:**
Currently, get the website link (Configured in App.php or .env) and do not pass any parameters.

**Expectation:**
Take configured domain and match with route parameter and path.
**That is:** ```app.domainconfigured.test/login```

**Comment by kenjis** [comment]
Thank you for reporting.
Can you show your use case?

`route_to()` returns a route (URI path after index.php).
So it seems it is not this case.

**Comment by KS7ven** [comment]
Good for using "route_to()" for common routes it works normally.
For example:
```
$routes->group('', ['namespace' => 'App\Controllers'], static function ($routes) {
   $routes->get('login', 'LoginController::loginView', ['as' => 'login']);
   $routes->post('login', 'LoginController::loginAction');
});
```
or 
```
$routes->get('login', 'App\Controllers\LoginController::loginView', ['as' => 'login']);
$routes->post('login', 'App\Controllers\LoginController::loginAction');
```
**Result:** domainconfigured.test/login

But as I describe in the opening of the topic it doesn't work, that is, it doesn't pass nor the subdomain nor reports the path after the index.php (which normally I also remove the index.php).

**Comment by kenjis** [comment]
```diff
--- a/app/Config/Routes.php
+++ b/app/Config/Routes.php
@@ -31,6 +31,9 @@ $routes->set404Override();
 // route since we don't have to scan directories.
 $routes->get('/', 'Home::index');
 
+$routes->get('login', 'App\Controllers\LoginController::loginView', ['as' => 'login']);
+$routes->post('login', 'App\Controllers\LoginController::loginAction');
+
 /*
  * --------------------------------------------------------------------
  * Additional Routing
```
```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        dd(route_to('login'));
    }
}
```
The result is: `string (6) "/login"`

> Result: domainconfigured.test/login

What do you mean? `route_to()` does not return hostname.

**Comment by KS7ven** [comment]
Yes, the result is indeed "/login", but for a route that uses the "subdomain" parameter, it doesn't work.

For example:
```
$routes->group('', ['namespace' => 'App\Controllers', 'subdomain' => 'app'], static function ($routes) {
   $routes->get('login', 'LoginController::loginView', ['as' => 'login']);
   $routes->post('login', 'LoginController::loginAction');
});
```

It returns as if the route did not exist (it releases the link to the same page or to the default hostname without the requested subdomain).

ATT: I'm talking about the parameter `'subdomain' => 'app'],` which is not passed to route_to(); For root route it works fine.

**Comment by kenjis** [comment]
You misunderstand *route*.
See https://codeigniter4.github.io/CodeIgniter4/general/urls.html#url-structure

A route does not contain hostname at all.

**Comment by KS7ven** [comment]
Ok, but how does the use of the subdomain passed in the route?
base_url() just passes the hostname described in the App.php or .env.

**Comment by kenjis** [comment]
> base_url() just passes the hostname described in the App.php or .env.

Since v4.3.0, you can set `$allowedHostnames`.
See https://codeigniter4.github.io/CodeIgniter4/changelogs/v4.3.0.html#multiple-domain-support

**Comment by KS7ven** [comment]
> Since v4.3.0, you can set $allowedHostnames.
> See https://codeigniter4.github.io/CodeIgniter4/changelogs/v4.3.0.html#multiple-domain-support

Got it, but how do I use the domains listed in the `$allowedHostnames` string in `base_url()` or other types of calls?

**Comment by kenjis** [comment]
It is automatically used in `base_url()`.

**Comment by KS7ven** [comment]
Yes, but if I'm using the root domain in the app's route and a module with a subdomain in the route and I use base_url(), the system will always pick the root domain...
How do I turn on the subdomain being recognized by the framework?

**Comment by kenjis** [comment]
> How do I turn on the subdomain being recognized by the framework?

Navigate to subdomain URL. There is no other way now.

I don't understand your use case. How do you want to use `base_url()`?
Also this issue is for `route_to()` or `url_to()`. What's the relation with `base_url()`?

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by kenjis** [comment]
No feedback. Close.
