### ISSUE TITLE
Bug: using NOT EXISTS on a subQuery where results in 'NOT EXISTS ='

### ISSUE THREAD

**Issue by Gildedter** [codeigniter4/CodeIgniter4#7076]
### PHP Version

8.1, 8.2

### CodeIgniter4 Version

4.2.10

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

SQL Server 2019

### What happened?

I have the following code:

```php
private function someQuery()
{
    $builder = $this->db->newQuery()->fromSubquery(
        $this->db->table('person')
            ->where('status', 1)
            ->unionAll(
                static fn (BaseBuilder $b)
                => $b->from('person AS p', true)
                    ->where(
                        'p.dateAssigned =',
                        static fn (BaseBuilder $ib)
                        => $ib->select('MAX(dateAssigned)', false)
                            ->from('person ', true)
                            ->where('status', 0)
                            ->where('eid= p.eid')
                    )
                    ->where(
                        'NOT EXISTS',
                        static fn (BaseBuilder $bb)
                        => $bb->select('id', false)
                            ->from('person ', true)
                            ->where('status', 1)
                            ->where('eid= p.eid')
                    )
            ),
        'p'
    );
    return $this;
}
```

the generated sql roughly looks like this:
```sql
(SELECT *
    FROM (SELECT *
        FROM person
        WHERE status = 1) uwrp0
UNION ALL
    SELECT *
    FROM (SELECT *
        FROM person AS p
        WHERE p.dateAssigned =(SELECT MAX(dateAssigned)
            FROM person
           WHERE status =0 AND eid= p.eid) AND NOT EXISTS = (SELECT id <- INCORRECT PLACEMENT OF  '=' HERE
            FROM person
            WHERE sStatus = 1 AND eid= p.eid)) uwrp1
) p
```

### Steps to Reproduce

Use NOT EXIST condition in a BaseBuilder instance

### Expected Output

`WHERE status =0 AND eid= p.eid) AND NOT EXISTS (SELECT id` on the faulty statement

**Comment by kenjis** [comment]
See https://codeigniter4.github.io/CodeIgniter4/database/query_builder.html#where

**Comment by Gildedter** [comment]
> See https://codeigniter4.github.io/CodeIgniter4/database/query_builder.html#where

so not planned? I ended up using:
`->where(new RawSql(// query))`

anything else just keeps adding `=` at the end of my `NOT EXISTS`

**Comment by kenjis** [comment]
The first parameter of `where()` takes:
1. field name
2. field name + operator (e.g. `<`)
3. array with field name and the value
4. string (WHERE clause)
5. RawSql

It does not accept `'NOT EXISTS'`.
