### ISSUE TITLE
Bug: Email config in the .env doesn't appear as expected

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#7077]
### PHP Version

7.4

### CodeIgniter4 Version

4.3.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

```BASH
# .env
email.fromEmail = 'XYZ'
```

v4.2.12
![image](https://user-images.githubusercontent.com/2387514/211508212-016c46b2-2ea9-443b-b10e-c41e7043e917.png)

v4.3.0
![image](https://user-images.githubusercontent.com/2387514/211508786-02905e95-11ae-46c3-bb75-93a877a0f8d8.png)

### Steps to Reproduce

just set .env

```BASH
# .env
email.fromEmail = 'XYZ'
```

### Expected Output

Same as in the previous version.

**Comment by kenjis** [comment]
It seems `get_object_vars()` does not return uninitialized properties.

**Comment by paulbalandan** [comment]
> It seems `get_object_vars()` does not return uninitialized properties.

It seems not.

> Uninitialized properties are considered inaccessible, and thus will not be included in the array.
https://www.php.net/manual/en/function.get-object-vars.php

**Comment by kenjis** [comment]
Workaround:
```diff
--- a/app/Config/Email.php
+++ b/app/Config/Email.php
@@ -6,9 +6,9 @@ use CodeIgniter\Config\BaseConfig;
 
 class Email extends BaseConfig
 {
-    public string $fromEmail;
-    public string $fromName;
-    public string $recipients;
+    public ?string $fromEmail  = null;
+    public ?string $fromName   = null;
+    public ?string $recipients = null;
 
     /**
      * The "user agent"
```
Or
```diff
--- a/app/Config/Email.php
+++ b/app/Config/Email.php
@@ -6,9 +6,9 @@ use CodeIgniter\Config\BaseConfig;
 
 class Email extends BaseConfig
 {
-    public string $fromEmail;
-    public string $fromName;
-    public string $recipients;
+    public $fromEmail;
+    public $fromName;
+    public $recipients;
 
     /**
      * The "user agent"
```

**Comment by kenjis** [comment]
I sent a PR: #7078
