### ISSUE TITLE
Bug: Validation not showing in version 4.3.0

### ISSUE THREAD

**Issue by fdjrr** [codeigniter4/CodeIgniter4#7089]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

I want to show validation but in version 4.3.0, it is not showing.

### Steps to Reproduce

```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
  public function create()
  {
    if (!$this->validate([
      'first_name' => 'required',
    ])) return redirect()->back()->withInput();
  }

  public function index()
  {
    return view('create', [
      'validation' => \Config\Services::validation(),
    ]);
  }
}
```

### Expected Output

`$validation->getErrors() array (0)`

**Comment by kenjis** [comment]
Can you show minimum code to reproduce your issue?
I don't understand what your issue is.

**Comment by fdjrr** [comment]
i want to show validation error in view but not showing...

View
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <?php d($validation->getErrors()) ?>
  <form action="<?= base_url('create') ?>" method="POST">
    <input type="text" name="first_name">
    <button type="submit">Submit</button>
  </form>
</body>

</html>
```

Controller
```
<?php

namespace App\Controllers;

class Home extends BaseController
{
  public function create()
  {
    if (!$this->validate([
      'first_name' => 'required',
    ])) return redirect()->back()->withInput();
  }

  public function index()
  {
    return view('create', [
      'validation' => \Config\Services::validation(),
    ]);
  }
}
```

this code should run normally in the previous version, but in the current version it doesn't run normally.

**Comment by kenjis** [comment]
> this code should run normally in the previous version, but in the current version it doesn't run normally.

Sorry, working the code in the previous version is a bug.
See https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_430.html#redirect-withinput-and-validation-errors

See also https://github.com/kenjis/ci4-validation-tutorial

**Comment by fdjrr** [comment]
how to fetch one line error validation if using withinput()? because in your repository code there is only `<?= validation_list_errors() ?>` to show all validation errors.

**Comment by fdjrr** [comment]
then what about `\Config\Service::validation()` ?

**Comment by kenjis** [comment]
See also https://github.com/codeigniter4/CodeIgniter4/issues/7092#issuecomment-1379867912
