### ISSUE TITLE
Bug: PHP 8.2, session lost after redirecting to subdomain

### ISSUE THREAD

**Issue by harpreetsb** [codeigniter4/CodeIgniter4#7094]
### PHP Version

8.2

### CodeIgniter4 Version

4.3

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

I remember this sometimes happened in 2017 with codeigniter 3.
We recently upgraded to PHP 8.2 and also upgraded codeingiter 4.3.
The issue seems to be that session is lost while we redirect to a subdomain that has same code base.
UPDATE: same settings are working fine with PHP 8.1.

### Steps to Reproduce

Here are steps:
- we ask user to login at `example.com/authenticate/login`
- we take values(via ajax) and set session at form action route `authenticate/validate-login` and respond a url `dash.example.com/dashboard` to JS
- we redirect user with js to the provided url in ajax response, i.e. `dash.example.com/dashboard`
- The session is lost.

### Expected Output

session should not be lost after redirecting to subdomain

**Comment by kenjis** [comment]
> UPDATE: same settings are working fine with PHP 8.1.

As far as I know, there is no change on Session in PHP 8.2.
How do you share session?

**Comment by harpreetsb** [comment]
While making a small sample code to prove my claim here, I came across the problem.
We are using plesk and plesk lets you select PHP version for each subdomain as well.
So did change the PHP version for `example.com` but forgot to do it for `dash.example.com`
Closing this issue.
