### ISSUE TITLE
Bug: Creation of dynamic property Config\Exceptions::$logDeprecations is deprecated

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#7097]
From Slack:

Deprecated: Creation of dynamic property Config\Exceptions::$logDeprecations is deprecated in ...\vendor\codeigniter4\framework\system\Debug\Exceptions.php on line 87
Deprecated: Creation of dynamic property Config\Exceptions::$deprecationLogLevel is deprecated in ...\vendor\codeigniter4\framework\system\Debug\Exceptions.php on line 88

PHP 8.2 & CI 4.3.0

**Comment by paulbalandan** [comment]
How is this our bug if we have indicated in the upgrade guide to add these two properties to __app/Config/Exceptions.php__?

> ## [Content Changes](https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/installation/upgrade_430.rst#id65)
> The following files received significant changes (including deprecations or visual adjustments) and it is recommended that you merge the updated versions with your application:
> ...
> - _app/Config/Exceptions.php_
> Two additional public properties were added: $logDeprecations and $deprecationLogLevel. See See [:ref:`logging_deprecation_warnings`](https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/installation/upgrade_430.rst#id43) for details.

**Comment by kenjis** [comment]
It is recommendation. But this is mandatory in PHP 8.2.

**Comment by paulbalandan** [comment]
Ah I see. Thanks for the clarification.
