### ISSUE TITLE
Bug: Errors deprecated

### ISSUE THREAD

**Issue by ALTITUDE-DEV-FR** [codeigniter4/CodeIgniter4#7104]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MYSQL 5.6

### What happened?

Hello,
I have a lot of problems with version 4.3.0 (installation by composing, and manual by following the guide).

My version 4.2.12 in PHP 8.2 works perfectly, in new version 4.3.0 PHP 8.2 returns full of errors which are the following and makes impossible to use the framework.

Deprecated: Creation of dynamic property Config\Exceptions::$logDeprecations is deprecated in C:\wamp64\www\vendor\codeigniter4\framework\system\Debug\Exceptions.php on line 87

Deprecated: Creation of dynamic property ConfigExceptions::$deprecationLogLevel is deprecated in C:\wamp64\www\vendor\codeigniter4\framework\system\Debug\Exceptions.php on line 88

and more in this file.

### Steps to Reproduce

I Use the version 4.1.12 with PHP 8.2, upgrade with composer update or manual install with follow the guide to upgrade.
Log deprecated error and website not started..

### Expected Output

Deprecated: Creation of dynamic property Config\Exceptions::$logDeprecations is deprecated in C:\wamp64\www\vendor\codeigniter4\framework\system\Debug\Exceptions.php on line 87
[22 h 59](https://codeigniterchat.slack.com/archives/C47FK3GRY/p1673474377278579)

Deprecated: Creation of dynamic property Config\Exceptions::$deprecationLogLevel is deprecated in C:\wamp64\www\vendor\codeigniter4\framework\system\Debug\Exceptions.php on line 88

**Comment by kenjis** [comment]
See in-progress User Guide:
https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_430.html

**Comment by ALTITUDE-DEV-FR** [comment]
Really thanks is now fixed with the #7100 

For help others novices dev: 

// Add in your app/config/exceptions.php

    public $logDeprecations = true;
    public $deprecationLogLevel = true;
