### ISSUE TITLE
Bug: I have a 500 error even though I have no error

### ISSUE THREAD

**Issue by ALTITUDE-DEV-FR** [codeigniter4/CodeIgniter4#7105]
### PHP Version

8.2

### CodeIgniter4 Version

4.1.12

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MYSQL 5.6

### What happened?

I started to develop my own CMS, it works perfectly, fast, secure etc, I even have security scores in A+ and 100% on Google Insight, however according to some tools like GT METRIX or Chromes extensions it tells me that my site is in error 500, except that this is not the case, I do not know where to find this kind of concerns.

Link to test : https://dev01.altitude-dev.com/

### Steps to Reproduce

Just load the website and check.

Network console, no errors.. 
Google Insight same
GtMetrix detect a error 500 and others apps.

### Expected Output

Error 500 in tools.

**Comment by datamweb** [comment]
#7093 ?

**Comment by ALTITUDE-DEV-FR** [comment]
> #7093 ?

I use this, its a problem ? 

`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /

RewriteCond %{REQUEST_URI} ^system.*
RewriteRule ^(.*)$ /index.php?/$1 [L]

RewriteCond %{REQUEST_URI} ^application.*
RewriteRule ^(.*)$ /index.php?/$1 [L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L]
</IfModule>

<IfModule !mod_rewrite.c>
ErrorDocument 404 /index.php
</IfModule>

<IfModule mod_deflate.c>
  # force compression for clients that mangle 'Accept-Encoding' request headers
  <IfModule mod_setenvif.c>
  <IfModule mod_headers.c>
    SetEnvIfNoCase ^(Accept-EncodXng|X-cept-Encoding|X{15}|~{15}|-{15})$ ^((gzip|deflate)\s*,?\s*)+|[X~-]{4,13}$ HAVE_Accept-Encoding
    RequestHeader append Accept-Encoding "gzip,deflate" env=HAVE_Accept-Encoding
  </IfModule>
  </IfModule>
</IfModule>

<IfModule mod_headers.c>
	  Header set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
	  Header set X-Content-Type-Options "nosniff"
    Header set X-Xss-Protection "1; mode=block"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set Referrer-Policy "strict-origin-when-cross-origin"
    Header set Permissions-Policy "geolocation=self"
    Header always set Content-Security-Policy "font-src *; form-action 'self'; object-src 'none'; base-uri 'none'; frame-ancestors"
</IfModule>`

**Comment by kenjis** [comment]
I got Whoops! page at the first visit.
But I reloaded, your site looks great.

Check your web server log and CodeIgniter log to get the reason of 500 errors.

**Comment by ALTITUDE-DEV-FR** [comment]
> I got Whoops! page at the first visit. But I reloaded, your site looks great.
> 
> Check your web server log and CodeIgniter log to get the reason of 500 errors.

Its my problem i have any problem :( any logs in my project :( localhost or live.. is verry obscur bug :D

**Comment by datamweb** [comment]
> I got Whoops! page at the first visit. But I reloaded, your site looks great.

Yes , Whoops ,after normal.

**Comment by ALTITUDE-DEV-FR** [comment]
I have check my log server, no errors detected, and no logs in server live with errors, and no log created in the writable folder..
Throttle is the problem ?

**Comment by ALTITUDE-DEV-FR** [comment]
I mso sorry is my fault, i have make a verification "banned" user IP its make the problem..
Solved

**Comment by kenjis** [comment]
If you implement like this https://codeigniter4.github.io/CodeIgniter4/libraries/throttler.html#the-code
the response code is 429, not 500.

**Comment by ALTITUDE-DEV-FR** [comment]
> If you implement like this https://codeigniter4.github.io/CodeIgniter4/libraries/throttler.html#the-code the response code is 429, not 500.

Small question with Throttler, how to define time lock user, example i have made this : 

        // -- Antispam & ForceBrute --
        
        $throttler  = \Config\Services::throttler();
        $allow      = $throttler->check('perform', 4, MINUTE);
        
        How to lock user for 5 minutes ?
