### ISSUE TITLE
Bug: uri_string() does not return subfolders in baseURL

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#7124]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

n/a

### What happened?

`uri_string()` should return the absolute path part of the current URL.
https://codeigniter4.github.io/CodeIgniter4/helpers/url_helper.html#uri_string

But it returns only the route.

### Steps to Reproduce

```
app.baseURL = 'http://localhost:8888/ci431/public/'
```
Navigate to `http://localhost:8888/ci431/public/home`.
```php
d(uri_string()); // "home"
d(uri_string(true)); // "home"
```

### Expected Output

If the current user guide is correct:
```php
d(uri_string()); // "/ci431/public/home"
d(uri_string(true)); // "home"
```

### Anything else?

Related #7123
The parameter `$relative` was introduced in #3682 https://github.com/codeigniter4/CodeIgniter4/pull/3682/commits/aa48ef0a2220f552686c15c5632ad4a3155ba22a v4.0.5

**Comment by kenjis** [comment]
The documented behavior of `uri_string()`:
```
app.baseURL = http://some-site.com/subfolder/

uri_string(); // "/subfolder/blog/comments/123"
```
 is not the same as CI3's `uri_string()`.

CI3:
`http://localhost:8888/ci3113/index.php/welcome/index`:
```
uri_string(); // "welcome/index"
```

**Comment by kenjis** [comment]
@MGatner https://github.com/codeigniter4/CodeIgniter4/pull/3682/commits/aa48ef0a2220f552686c15c5632ad4a3155ba22a
`function uri_string(bool $relative = false): string`

Why is the default `$relative = false`?
CI3's `uri_string()` returns only relative values.

**Comment by MGatner** [comment]
That commit was to maintain the current default behavior. I was unaware of CI3's function at the time - not a deliberate change from its behavior.

**Comment by kenjis** [comment]
Thank you.

I checked the behavior in v4.0.5. It is the same as v4.3.1.

```
app.baseURL = 'http://localhost:8888/ci405/public/'

d(uri_string());
d(uri_string(true));
```

Navigate to `http://localhost:8888/ci405/public/home`.

The results:
```
uri_string() string (4) "home"
uri_string(...) string (4) "home"
```

**Comment by kenjis** [comment]
Probably `uri_string(false)` hasn't worked all along.
Because `IncommingRequest`'s constructor changes the path in the URI object to the relative path (route).

@codeigniter4/core-team Can I remove the parameter as a bug fix?
I can't imagine a use case.

**Comment by MGatner** [comment]
Fine by me. I will push again for a separate class to handle internal URIs; I think we need it despite the complexity it adds.

**Comment by kenjis** [comment]
I sent a PR #7135
