### ISSUE TITLE
Bug: Errors displayed in wrong order when using Validation:SetRule

### ISSUE THREAD

**Issue by Joubinho** [codeigniter4/CodeIgniter4#7145]
### PHP Version

7.4, 8.0, 8.1, 8.2

### CodeIgniter4 Version

4.3.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS, Windows

### Which server did you use?

apache

### What happened?

When using many SetRule from Validation service in order :
```php
$validation->setRule('username', 'Username', 'required');
```
Then 
```php
$validation->setRule('password', 'Password', 'required');
```

Errors are shown in reverse order.
("Password error" then "Username error")

### Steps to Reproduce

When using many SetRule from Validation service like that :
```php
$validation = \Config\Services::validation();
$validation->setRule('username', 'Username', 'required');
$validation->setRule('password', 'Password', 'required');
if ($this->validation->withRequest($this->request)->run()) {...}
```

Submit your form and show errors in view with :
`<?= validation_list_errors() ?>`

### Expected Output

"Username error"
then 
"Password error" 

### Anything else?

The problem seems to be in Validation/Validation.php line 446
When I replace :
```php
$this->setRules($ruleSet + $this->getRules(), $this->customErrors);
```
By : 
```php
$this->setRules($this->getRules() + $ruleSet, $this->customErrors);
```

It's in the right order (but may cause other problem).

**Comment by ddevsr** [comment]
I send PR #7149
