### ISSUE TITLE
Bug: developer environment causes TH elements to sort tables on click

### ISSUE THREAD

**Issue by malytomas** [codeigniter4/CodeIgniter4#7225]
### PHP Version

8.2

### CodeIgniter4 Version

v4.3.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Enabling developer environment (adding the bottom-right flame icon to the page) leaks functionality onto the actual page, making TH elements react to clicks and sort tables.

### Steps to Reproduce

CI_ENVIRONMENT = development
have table with TH elements and click it

### Expected Output

Clicking TH elements to sort tables should be limited to tables inside the flame-icon panel.

**Comment by kenjis** [comment]
Duplicate of #6808
