### ISSUE TITLE
Bug: Reverse routing fails for routes with regex containing parenthesis

### ISSUE THREAD

**Issue by csg-luke** [codeigniter4/CodeIgniter4#7237]
### PHP Version

8.0

### CodeIgniter4 Version

4.3.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MariaDB 10.6

### What happened?

Reverse routing is failing for routes with regex containing parenthesis

Error: preg_match(): Compilation failed: missing closing parenthesis at offset 19,
vendor/codeigniter4/framework/system/Router/RouteCollection.php
line: 1238

Looking at the RouteCollection.php line 1211 
`preg_match_all('/\(([^)]+)\)/', $from, $matches);`
It appears the regex is only matching to the first parenthesis and losing the rest.

### Steps to Reproduce

```php
$routes->addPlaceholder('imgFileExt', '^.*\.(?:jpg|png)$');
$routes->get('images/(:imgFileExt)', 'Images::getFile/$1');
```
```php
$file = 'test.jpg';
url_to('Images::getFile', $file)
```

### Expected Output

**<base_url>/images/test.jpg**

**Comment by kenjis** [comment]
I don't want to permit *Route* like `images/(^.*\.(?:jpg|png)$)`.
I think it would be fine to say that regular expressions with double parentheses such as this are not supported.

```
+--------+----------------------------+------+-------------------------------------+----------------+---------------+
| Method | Route                      | Name | Handler                             | Before Filters | After Filters |
+--------+----------------------------+------+-------------------------------------+----------------+---------------+
| GET    | /                          | »    | \App\Controllers\Home::index        |                | toolbar       |
| GET    | images/(^.*\.(?:jpg|png)$) | »    | \App\Controllers\Images::getFile/$1 | <unknown>      | <unknown>     |
+--------+----------------------------+------+-------------------------------------+----------------+---------------+
```

**Comment by kenjis** [comment]
Cannot reproduce the error.
I got:
```
404
Can't find a route for 'get: images/test.jpg'.
```

**Comment by kenjis** [comment]
Workaround:
```php
$routes->addPlaceholder('img', '.*\.jpg|.*\.png');
$routes->get('images/(:img)', 'Home::index/$1');
```

**Comment by kenjis** [comment]
Try #7880
