### ISSUE TITLE
Bug: issue to remove folder from the segment http://localhost/codeigniter4 while folder Codeigniter4

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#7281]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.2

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

After I updated my script to Codeigniter 4.3.2, I discovered codeigniter installation script is include to the url part when `request()->getPath()` is called. This happened when the installation folder is in capital letter (Codeigniter4) while loading `http:/localhost/codeigniter4/user` 
When I call `request()->getPath()` returns `codeigniter4/user`.

### Steps to Reproduce

I went to `IncomingRequest.php` on line 280. I changed 
```php
$uri   = $parts['path'] ?? ''; 
```
to

```php
$uri   = strtolower($parts['path'] ?? '');
```
by converting the part to lowercase

i also did the same on line 290
```php
          foreach (explode('/', $_SERVER['SCRIPT_NAME']) as $i => $segment) {
                
                // If these segments are not the same then we're done
                if (! isset($segments[$i]) || $segment !== $segments[$i]) {
                    break;
                }

                array_shift($keep);
            }
```
to
```php
           foreach (explode('/', strtolower($_SERVER['SCRIPT_NAME'])) as $i => $segment) {
                
                // If these segments are not the same then we're done
                if (! isset($segments[$i]) || $segment !== $segments[$i]) {
                    break;
                }

                array_shift($keep);
            }
```
converting the `$_SERVER['SCRIPT_NAME']` to lowercase

So this fixed my issue

### Expected Output

I expected  `http:/localhost/codeigniter4/user`  to return `user` as the uri path when I call `request()->getPath()` either the installation folder is in capital letter or not.

**Comment by kenjis** [comment]
> This happened when the installation folder is in capital letter (Codeigniter4) while loading http:/localhost/codeigniter4/user

What do you mean?
What is your baseURL? 
Where did you install your CI4 project?
How did you configure your web server?

**Comment by kenjis** [comment]
This change is probably not acceptable. Because the path is case sensitive.

```php
$uri   = strtolower($parts['path'] ?? '');
```
See https://webmasters.stackexchange.com/questions/90339/why-are-urls-case-sensitive

**Comment by ChibuezeAgwuDennis** [comment]
> > This happened when the installation folder is in capital letter (Codeigniter4) while loading http:/localhost/codeigniter4/user
> 
> What do you mean? What is your baseURL? Where did you install your CI4 project? How did you configure your web server?

> *What did you mean?*
I install codeigniter in the laragon server folder `www => Codeigniter4` then in my browser i load `http:/localhost/codeigniter4/admin/login` it return `Can't find a route for 'get: codeigniter4/admin/login'. `. if you watch `Can't find a route for 'get: sperad/admin/login'. ` you will notice the installation directory (codeigniter4) is included to the path but if  `http:/localhost/Codeigniter4/admin/login` changing this `codeigniter4` in the url to `Codeigniter4` just as the installation directory it worked

**Comment by kenjis** [comment]
I don't know laragon. Is the `www` folder the document root?

If your baseURL is `http:/localhost/Codeigniter4/`, you should access `http:/localhost/Codeigniter4/`.
If your baseURL is `http:/localhost/codeigniter4/`, you should access `http:/localhost/codeigniter4/`.
They are different URLs.

**Comment by ChibuezeAgwuDennis** [comment]
> I don't know laragon. Is the `www` folder the document root?
> 
> If your baseURL is `http:/localhost/Codeigniter4/`, you should access `http:/localhost/Codeigniter4/`. If your baseURL is `http:/localhost/codeigniter4/`, you should access `http:/localhost/codeigniter4/`. They are different URLs.

yeah just like htdocs for xampp

**Comment by kenjis** [comment]
> yeah just like htdocs for xampp

I got it.

Then, if `Codeigniter4` is your CI4 project folder, why you can access with `http:/localhost/Codeigniter4/`?
Why not `http:/localhost/Codeigniter4/public/`?
There is no `Codeigniter4/index.php`.

**Comment by ChibuezeAgwuDennis** [comment]
> > yeah just like htdocs for xampp
> 
> I got it.
> 
> Then, if `Codeigniter4` is your CI4 project folder, why you can access with `http:/localhost/Codeigniter4/`? Why not `http:/localhost/Codeigniter4/public/`? There is no `Codeigniter4/index.php`.

i was thinking since the Codeigniter4 is the installation directory, codeigniter would have detect it without been case sensitive. i don't know if it okay like that but the segments can be case sensitive

**Comment by ddevsr** [comment]
I am use ``Laragon``, if you folder in ``www`` is ``Codeginter4``, you must opened in browser ```http://codeigniter4.test``` by default configuration ``autowebroot``

**Comment by ChibuezeAgwuDennis** [comment]
> ![image](https://user-images.githubusercontent.com/97607754/220224754-820d84f2-bfb8-406f-8cd3-92bfdc7c5f17.png)
> @ChibuezeAgwuDennis  I am use ``Laragon``, if you folder in ``www`` is ``Codeginter4``, you must opened in browser ```http://codeigniter4.test``` by default configuration ``Auto Virtual Host``.

This is when using virtual host. What of straight http:/localhost/.... when not using virtual host. This is what i mean. I have already tried all these before posting this issue

**Comment by kenjis** [comment]
It seems this is not a framework issue, but a web server configuration issue.

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by ChibuezeAgwuDennis** [comment]
@kenjis I don't know if this has fixed. Please I get the url  is case sensitive why. I taught since I am working on localhost either the installation directory is in capital later or not this supposed to work

**Comment by kenjis** [comment]
> I expected http:/localhost/codeigniter4/user to return user as the uri path when I call request()->getPath() either the installation folder is in capital letter or not.

If the folder is `Codeigniter4`, the URL should be `http:/localhost/Codeigniter4/user`
If you want `http:/localhost/codeigniter4/user`, the folder should be `codeigniter4`.
Most production servers use case sensitive filesystems. So we cannot fix this as you suggested.

**Comment by ChibuezeAgwuDennis** [comment]
okay @kenjis thanks
