### ISSUE TITLE
Cannot change $allowedHostnames with `.env`

### ISSUE THREAD

**Issue by paulalbinson** [codeigniter4/CodeIgniter4#7311]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

It appears the new allowed hostnames feature doesn't work with .env configuration. If you set alternative domains in the .env file e.g.:

app.baseURL = 'https://example.com/'
app.allowedHostnames = ['different.domain']

it won't recognise the alternative domain whereas if you set it in App.php it works e.g.,

public array $allowedHostnames = ['different.domain'];

For flexibility it is better to have configurations in .env then can vary things per environment so if this could be fixed that would be great.

### Steps to Reproduce

Not applicable

### Expected Output

Alternative domain should work

**Comment by kenjis** [comment]
`.env` or environment variables can change the existing config items.

See #5526

**Comment by kenjis** [comment]
Ah, you are confusing `.env` and PHP.
The variables in `.env` are not PHP variables.
You cannot use a PHP array like `['different.domain']`.

**Comment by paulalbinson** [comment]
Well how can you specify multiple allowedHostnames in .env then? Is this likely to be the problem?

**Comment by kenjis** [comment]
Simply you can't by default.
You need to implement a feature to support an array value.
Easy way is something like this: https://github.com/codeigniter4/CodeIgniter4/pull/5526/files

**Comment by paulalbinson** [comment]
Then it shouldn't really be called allowedHostnames if you can't have more than one specified.

**Comment by kenjis** [comment]
You can set them in `Config\App`.
By the way, why do you need to change hostnames with `.env`?
