### ISSUE TITLE
Bug: Inline style not rendered

### ISSUE THREAD

**Issue by Rahul118** [codeigniter4/CodeIgniter4#7313]
### PHP Version

7.4

### CodeIgniter4 Version

4.3.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

Inline style not rendered. When I am trying to add some inline styling by style attribute its goes blank. I have attached screenshot.
![image](https://user-images.githubusercontent.com/36496199/221539480-01a8e51a-b7f5-4481-85dc-cee6d16fbff5.png)
![image](https://user-images.githubusercontent.com/36496199/221539916-2d1c6df6-d521-4122-a8eb-3af28576b46e.png)

### Steps to Reproduce

Create a simple view file with style attribute

### Expected Output

Expected Result should be like this.
![image](https://user-images.githubusercontent.com/36496199/221540319-3a578df1-0f43-419a-a5c8-0d3e32528ef8.png)

**Comment by kenjis** [comment]
Please do not use screenshot for source code.
We cannot copy and paste it.

Can't reproduce.
```php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to CodeIgniter 4!</title>
    <meta name="description" content="The small framework with powerful features">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="/favicon.ico">
</head>
<body>

<div style="font-size:22px">Hello</div>

</body>
</html>
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to CodeIgniter 4!</title>
    <meta name="description" content="The small framework with powerful features">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="[/favicon.ico](view-source:http://localhost:8080/favicon.ico)">
</head>
<body>

<div style="font-size:22px">Hello</div>

</body>
</html>
```

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by Rahul118** [comment]
Vey sorry i did not pay attention to CSP, actually i have enabled csp thats why inline styling was not working.

**Comment by kenjis** [comment]
No problem. Nobody's perfect.
See also #7314
