### ISSUE TITLE
Dev: drop PHP 8.0 support with CI 4.4

### ISSUE THREAD

**Issue by element-code** [codeigniter4/CodeIgniter4#7320]
PHP 8.0 will reach the end of life on 28 Nov 2022.
https://www.php.net/supported-versions.php

Relating to https://github.com/codeigniter4/CodeIgniter4/issues/6921 : guessing that this won't be CI 4.3 thing, so we are already at a breaking change then.
Whilst at it, drop PHP 8.0 as well, since it is already in its security-support-only phase (which itself ends in a few months 26 Nov 2023) and migration to at least PHP 8.1 should be in the process already.
This allows simplifying code using new features, at least for CI 4.4.
PHP 8.0 installation percentages are already dropping their share already, since people **are** upgrading to newer versions quicker than back in the day.

![grafik](https://user-images.githubusercontent.com/7399618/222114424-f200a1c7-4e9d-42e9-8a7d-dac1c247afaf.png)
https://packagist.org/packages/codeigniter4/framework/php-stats

Using up energy supporting nearly EOL Versions in a "new PHP world" which is moving along way faster is a waste of energy in my opinion. It kinda feels like parts of the CI Community have not yet realized, that the "good old days" of having PHP 5.6 maintained for many years are over and moving along is the new normal.

**Comment by kenjis** [comment]
The problem is the share of PHP 7.4.
I think dropping PHP 8.0 can be done only after dropping PHP 7.4.

**Comment by element-code** [comment]
> I think dropping PHP 8.0 can be done only after dropping PHP 7.4.

Yes I'm totally fine with that, for people who can't run CI 4.4 with PHP 7.4 anymore it would be not a problem to directly switch to PHP 8.1 / 8.2 instead of PHP 8.0.

> The problem is the share of PHP 7.4.

My opinion is that sometimes forcing people to do the right thing is ok. E.g., forcing them to use a secure PHP version when they want to upgrade to CI 4.4
The point is, that as long as they run CI 4.3 they can use PHP 7.4, it just if they want to upgrade anyway.

**Comment by kenjis** [comment]
I know your opinion. 
This is a big change, so I think we need more discussion at our Forum.

**Comment by proff56** [comment]
big changes are the harbinger of growth... growth is good :)

**Comment by kenjis** [comment]
I posted on the forum.
https://forum.codeigniter.com/showthread.php?tid=87036

**Comment by kenjis** [comment]
PHPUnit 10 requires PHP 8.1 or PHP 8.2.
https://phpunit.de/getting-started/phpunit-10.html

**Comment by kenjis** [comment]
I would like to drop 8.0 in CI 4.5.

**Comment by kenjis** [comment]
laminas-escaper 2.13 requires PHP 8.1 or later.
https://packagist.org/packages/laminas/laminas-escaper#2.13.0

**Comment by kenjis** [comment]
PHP 7.4: 22.9%
PHP 8.0: 12.8%
![Screenshot 2023-10-13 17 23 11](https://github.com/codeigniter4/CodeIgniter4/assets/87955/06bcd3fe-33fb-4240-acf5-935e1d6d9002)

**Comment by kenjis** [comment]
I sent PR #8042

**Comment by kenjis** [comment]
PHP 8.0 support will be dropped in 4.5.
