### ISSUE TITLE
Bug: Dot (Period) not accepted in Validation messages?

### ISSUE THREAD

**Issue by cdsaenz** [codeigniter4/CodeIgniter4#7329]
### PHP Version

7.4

### CodeIgniter4 Version

4.3.2 latest

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

After some time trying different things to make custom validation messages work, I realize they fail when I add a dot at the end of the sentence. Is it possible that there's some regex or such that's breaking everything when the dot appears? Thanks!

### Steps to Reproduce

```php
        $messages = [
            'first_name' => [
                  /* Does not work */                
                'required'   => 'First name is missing.', 
                'min_length' => 'First name is too short.'  
            ],
            'usr_email' => [                          
                 /* IT DOES work */
                'min_length' => 'Email too short',  
                'is_unique'  => 'Email is not unique'  
            ]
        ];   
```

### Expected Output

Custom $messages being used in `getErrors()`, instead you get an empty array on `first_name` (but ok in usr_email, where there's no dots/periods)

**Comment by cdsaenz** [comment]
After reading again the docs I realized the dot is used in several "smart" ways (dot notation for arrays, language translations). so my workaroud  is to use `&#46` and away it goes :)

**Comment by kenjis** [comment]
Cannot reproduce.
The following test passes.
https://github.com/codeigniter4/CodeIgniter4/blob/e1c13f687fcb0f0a5ea2869ebd362dfd6d83f952/tests/system/Validation/ValidationTest.php#L562-L570

**Comment by cdsaenz** [comment]
Thanks I'll try the different code approach, I use `$this->validate()` in the Controller, but I think it reroutes to the `$validation->run()` right? Anyway this is the whole code, which now works because I am using the HTML entities. As soon as I use the period at the end, it fails. Will check the whole thing again just in case.

```php
$rules = [
    'first_name'  => ['required', 'min_length[2]'],
    'usr_email'   => 'is_unique[users.usr_email]|min_length[5]'
];

/* WARNING: DON'T USE PERIOD (.) in MESSAGE */
$messages = [
    'first_name' => [
        'required'   => l('First name is missing&#46'),
        'min_length' => l('First name is too short&#46')
    ],
    'usr_email' => [
        'min_length' => l('Email too short'),
        'is_unique'  => l('Email is not unique')
    ]
];

if (!$this->validate($rules, $messages)) {
    /* rest of code */
}
```

**Comment by kenjis** [comment]
> I use $this->validate() in the Controller, but I think it reroutes to the $validation->run() right?

Yes, `$this->validate()` calles `Validation::run()`.

What's `l()` in the code?

**Comment by cdsaenz** [comment]
> What's `l()` in the code?

Good catch. I was just looking at that..  Makes sense that it would be the issue. It's a function where I wrap around the `lang()`  function to translate strings. The dot is meaningful in translations too. But I took it away and it still fails with the dots. Weird. Don't worry I'll eventually build a whole fresh app to test it out. 

```php
/**
 * Translate from Language/{locale}/app/$file 
 * ($file = "core" by default)
 */
function l(string $string, array $args = [], string $file = "core", $locale = null)
{    
    $t = lang("app/{$file}.{$string}", $args,$locale);  
    return $t;
}
```

**Comment by kenjis** [comment]
When `$string` is `'First name is missing.'`, you call `lang('app/core.First name is missing.')`.
What do you want to get?

**Comment by cdsaenz** [comment]
It will simply look for "First name is missing" as a key in the lang file and bring over its translation (if any), else it will give me back the original.  I use(d) like that it in CI3.  I never used a key for every message (something like "firstNameMissing"); that's nice but it means not only to code every message but also to translate twice from the beginning (a second language might not be needed at first). It's a little like gettext/.po files work. And in CI4 I use the `app/core.` bit to eventually distribute the strings in files (`app/users.` for example)

**Comment by kenjis** [comment]
It seems this issue is because of your customization.
Close.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
