### ISSUE TITLE
Bug: Wrong @deprecrated annotation in HTTP/Request.php For getMethod()

### ISSUE THREAD

**Issue by donpwinston** [codeigniter4/CodeIgniter4#7334]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### What happened?

My VS Code DeveSenses extension flags $request->getMethod() as an error because the entire method is marked as deprecated. Actually only the optional parameter bool $upper is deprecated. I believe the correct way to annotate this is the following:

remove the line "@deprecated The $upper functionality will be removed and this will revert to its PSR-7 equivalent"

Add * #[Deprecated] above the line " * @param bool $upper Whether to return in upper or lower case."

### Steps to Reproduce

Install the DevSenses VS Code extension.

### Expected Output

No underline for the text getMethod() in your code.

**Comment by kenjis** [comment]
Thank you for reporting.

What is DeveSenses extension?
The purpose of the `@deprecrated` annotation is to inform that the optional parameter is deprecated to developers.
The way you show can inform it to devs who don't use the extension?

**Comment by donpwinston** [comment]
https://www.devsense.com/en

The devsense engineer told me he thinks the following is the proper way to do it.
...* #[Deprecated]* @param bool $upper Whether to return in upper or lower case....

The way it is done now indicates the entire method is deprecated which is not the case. 

    On Sunday, March 5, 2023 at 05:47:38 PM EST, kenjis ***@***.***> wrote:  
 
 


Thank you for reporting.

What is DeveSenses extension?
The purpose of the @deprecrated annotation is to inform that the optional parameter is deprecated to developers.
The way you show can inform it to devs who don't use the extension?

**Comment by kenjis** [comment]
I don't use DeveSenses.

Do you mean the following? It causes Undefined Type.
![Screenshot 2023-03-06 9 48 57](https://user-images.githubusercontent.com/87955/222996499-54aac105-ce93-4370-bd69-f8820b1d4d8b.png)

And it does not inform me the deprecation.
![Screenshot 2023-03-06 9 49 21](https://user-images.githubusercontent.com/87955/222996507-f2afdc49-1935-4617-9e2d-f34a7c048dc2.png)

**Comment by donpwinston** [comment]
No. You need to put it in the comment area:
    /**     * Get the request method.     * #[Deprecated]     * @param bool $upper Whether to return in upper or lower case.     *     *     * @codeCoverageIgnore     */    public function getMethod(bool $upper = false): string   {      return ($upper) ? strtoupper($this->method) : strtolower($this->method);   }


 

    On Sunday, March 5, 2023 at 07:52:00 PM EST, kenjis ***@***.***> wrote:  
 
 


I don't use DeveSenses.

Do you mean the following? It causes Undefined Type.


And it does not inform me the deprecation.

**Comment by donpwinston** [comment]
ok. Then just remove the @deprecated annotation.


 

    On Monday, March 6, 2023 at 10:20:25 AM EST, John Paul E. Balandan, CPA ***@***.***> wrote:  
 
 


The #[Deprecated] attribute is still an RFC. See https://wiki.php.net/rfc/deprecated_attribute. So I'm not sure if the placement of the attribute actually "works".

**Comment by kenjis** [comment]
This is intentional.

If there is a better way to let devs know that that parameter is deprecated, 
which is supported by most of the IDEs, please send PR.
