### ISSUE TITLE
Bug: Undefined constant "CodeIgniter\Database\MySQLi\MYSQLI_STORE_RESULT" php 8.2

### ISSUE THREAD

**Issue by sajjadef98** [codeigniter4/CodeIgniter4#7345]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.2

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 

### What happened?

my site [manbaenab.ir](https://manbaenab.ir/) update to php.8.2 but i have 
**Error
Undefined constant "CodeIgniter\Database\MySQLi\MYSQLI_STORE_RESULT"** 
in test version  https://manbaenab.greenmovie.ir/ 
my host Company(parspack.com) say :
The MySQLI module cannot be activated on php8.2 and you should use MySQLND instead. If desired, the PHP version can be adjusted to 8.1 so you can use MySQLI.
-------------

### Steps to Reproduce

Error
Undefined constant "CodeIgniter\Database\MySQLi\MYSQLI_STORE_RESULT" 

### Expected Output

MySQLi

**Comment by kenjis** [comment]
> The MySQLI module cannot be activated on php8.2 and you should use MySQLND instead.

The MySQLi module can be activated on PHP 8.2.
You should use MySQLND, but it is not the replacement for MySQLi.
See https://www.php.net/manual/en/mysqlnd.overview.php

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
