### ISSUE TITLE
Bug: [Migration] Relative rollback not working (php spark migrate:rollback -b -1)

### ISSUE THREAD

**Issue by Mauricevb** [codeigniter4/CodeIgniter4#7349]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### What happened?

According to the [documentation](https://codeigniter.com/user_guide/dbmgmt/migration.html#id10) it should be possible to rollback to a relative batch using the `-b` parameter with a negative number. 

E.g. `php spark migrate:rollback -b -1`

Unfortunately this doesn't work. It reverts to batch 1.

### Steps to Reproduce

Run `php spark migrate:rollback -b -1` in a project with multiple batches. 

### Expected Output

Only the latest batch reverted 

### Anything else?

I also tried `php spark migrate:rollback -b "-1"` but this didn't solve anything. It looks like `getOption(string $name)` in CLI.php can't find the option 'b'.

**Comment by kenjis** [comment]
Yes, an argument that starts with `-` is an option, not a value.
So we cannot specify `-1` as a value.

**Comment by kenjis** [comment]
Workaround: `php spark migrate:rollback -b ' -1'`

**Comment by kenjis** [comment]
@Mauricevb Do you really need the feature to specify relative number?

**Comment by kenjis** [comment]
Fixed the docs by #7350
