### ISSUE TITLE
Bug: Implicit conversion from float (PHP_INT_MIN) to int loses precision

### ISSUE THREAD

**Issue by ArrayIterator** [codeigniter4/CodeIgniter4#7376]
### PHP Version

8.1, 8.2

### CodeIgniter4 Version

Latest (4.x)

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS, Windows, Linux

### Which server did you use?

apache

### Database

MariaDB 10.10

### What happened?

```abs()``` function make the system resulting depreciated log cause less / bigger than int.

```
[DEPRECATED] Implicit conversion from float 9.223372036854776E+18 to int loses precision in SYSTEMPATH/Router/RouteCollection.php on line 519.
--
  | 1 SYSTEMPATH/Router/Router.php(394): CodeIgniter\Router\RouteCollection->getRoutes('get')
  | 2 SYSTEMPATH/Router/Router.php(182): CodeIgniter\Router\Router->checkRoutes('dashboard/auth/login')
  | 3 SYSTEMPATH/CodeIgniter.php(815): CodeIgniter\Router\Router->handle('dashboard/auth/login')
  | 4 SYSTEMPATH/CodeIgniter.php(449): CodeIgniter\CodeIgniter->tryToRouteIt(Object(App\Libraries\Services\RouteCollection))
  | 5 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
  | 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()

```
![image](https://user-images.githubusercontent.com/37867551/227442317-74709a0e-7878-49dd-acbd-ce423d98e5fe.png)

### Steps to Reproduce

```pphp
<?php
/**
 * Adding routes (add, match or what ever that calling fallback `create` method and contains priority bigger / less than integer
 */
$routes = \Config\Services::routes();
$routes->setPrioritize(true);
$routes = $routes->add('path', 'Controller::method', ['priority' => PHP_INT_MIN]);
// whatever
```

### Expected Output

Maybe the `abs` function is not needed by the routes prioritization.

https://github.com/codeigniter4/CodeIgniter4/blob/829bcb2bd7397d3e6f444672421f363f8a89bae0/system/Router/RouteCollection.php#L1309

The code will make route array sorting using precision loses

https://github.com/codeigniter4/CodeIgniter4/blob/829bcb2bd7397d3e6f444672421f363f8a89bae0/system/Router/RouteCollection.php#L519

**Comment by iRedds** [comment]
Doc: "The parameter accepts positive integers and zero. "

**Comment by kenjis** [comment]
Yes. This is a misuse.

> The parameter accepts positive integers and zero.
https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#changing-route-priority
