### ISSUE TITLE
Security Guidelines are out of dated

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#7390]
See https://codeigniter4.github.io/CodeIgniter4/concepts/security.html

The OWASP Top 10 in the docs is the version in 2013.
https://owasp.org/www-pdf-archive/OWASP_Top_10_-_2013.pdf
https://www.hahwul.com/cullinan/history-of-owasp-top-10/

The latest is OWASP Top 10 2021.
https://owasp.org/www-project-top-ten/

**Comment by naftalimurgor** [comment]
Hey @kenjis 
I'm ready to take on this! You may assign me this 

Thank you!

**Comment by kenjis** [comment]
Done! Thank you for cooperation!

**Comment by kenjis** [comment]
The update process has started. #8652

**Comment by kenjis** [comment]
Closed by #8715
