### ISSUE TITLE
Bug: Generator Command cannot locate the view template.

### ISSUE THREAD

**Issue by sammyskills** [codeigniter4/CodeIgniter4#7405]
### PHP Version

7.4

### CodeIgniter4 Version

4.3.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

I created a generator command like so:
```
php spark make:command TestCommandGenerator --type generator --command make:me-test
```
And updated the file like so:
```php
public function run(array $params)
{
    $this->component = 'Library';
    $this->directory = 'Libraries';
    $this->template = 'me.tpl.php';

    $this->execute($params);
}
```
I have the generator template in the directory: `app/Commands/Generators/Views/me.tpl.php`. But when I try to use the command `php spark make:me-test`, I get the error message:
```
Invalid file: "CodeIgniter\Commands\Generators\Views\me.tpl.php"
```

### Steps to Reproduce

1. Create a new command:  `php spark make:command TestCommandGenerator --type generator --command make:me-test`.
2. Create the generator template and place it within the `app/Commands/Generators/Views` folder.
3. Update the `run()` method of the `TestCommandGenerator.php`  to contain the name of the view template you created above: `$this->template = ''; // name of file here`
5. Run the command `php spark make:me-test`.

### Expected Output

I expect that the view template file would be located within the `app` namespace instead of `CodeIgniter`.

**Comment by datamweb** [comment]
It seems, not creating file **me.tpl.php** is intentional, the reason is even though file **me.tpl.php** should be defined in **app\Config\Generators.php**.

The following link explains how to create a new [command](https://forum.codeigniter.com/showthread.php?tid=86571&pid=406436#pid406436).

**Comment by sammyskills** [comment]
I'm not even bothered about automatically creating the view template, but locating it when it is added in the `$this->template` variable.

If it must also be declared in the `app/Config/Generators.php` file, then the documentation is either misleading or it doesn't contain enough explanations.

**Comment by kenjis** [comment]
The documentation seems to be insufficient.
https://codeigniter4.github.io/CodeIgniter4/cli/cli_generators.html

**Comment by sammyskills** [comment]
Which is better for the docs?
- A new page within the Command Line Usage menu, called `Creating Custom Generators`, OR
- Within the current `CLI Generators` page.

**Comment by sammyskills** [comment]
Submitted a PR #7408
