### ISSUE TITLE
Bug: Why not check the browser name?

### ISSUE THREAD

**Issue by warmbook** [codeigniter4/CodeIgniter4#7418]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### What happened?

I add one row to the property 'browsers' of 'Config\UserAgents' class, the key is 'MicroMessenger' and the value is 'WeChat'. Then I want to know whether a HTTP request is from WeChat browser, so I called the 'isBrowser' method in my service code and the only argument is 'WeChat'. But it always returns false. I read the first floor code and find that the 'isBrowser' method only check if the key is exist.

### Steps to Reproduce

Add one row to the property 'browsers' of 'Config\UserAgents' class, the key is 'MicroMessenger' and the value is 'WeChat'. Then call the 'isBrowser' method with 'WeChat'.

### Expected Output

Return true when the header 'user-agent' contains 'MicroMessenger'.

### Anything else?

Sometimes, we only want to know whether the HTTP request is from some browser, and don't care which version it is. So why not compare the argument '$key' with the property 'browser'? Just like this:
```php
if ($key === null || $this->browser === $key) {
    return true;
}
```

**Comment by kenjis** [comment]
I don't know why the current behavior is like this.
But it comes from CI3 and the parameter is `$key` that specifies the Config array key.

- https://www.codeigniter.com/userguide3/libraries/user_agent.html#CI_User_agent::is_browser
- https://codeigniter4.github.io/CodeIgniter4/libraries/user_agent.html#CodeIgniter\HTTP\UserAgent::isBrowser

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
