### ISSUE TITLE
Bug: PhpStorm spelling errors

### ISSUE THREAD

**Issue by InsiteFX** [codeigniter4/CodeIgniter4#7428]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.3

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.28

### What happened?

Cosmedic.

Not really a bug, but phpStrom is flagging spelling errors in index.php

index.php

phpStorm is flaging these as spelling errors!

Line 50 - * the application run, and does all of the dirty work to get

// should be - remove the of
* the application run, and does all the dirty work to get

Line 63 -  * Now that everything is setup, it's time to actually fire

// should be - change setup to set up
 * Now that everything is set up, it's time to actually fire

### Steps to Reproduce

Just open index.php with phpStorm.

### Expected Output

No phpStorm spelling errors.

**Comment by kenjis** [comment]
I sent a PR #7430
