### ISSUE TITLE
Bug: PhpStorm warnings in public/index.php

### ISSUE THREAD

**Issue by InsiteFX** [codeigniter4/CodeIgniter4#7434]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.3 updated today

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.28

### What happened?

phpStorm throwing Warnings on these 2 lines now.

Line #16 - Can be replaced with 'const' syntax

// Path to the front controller (this file)
define('FCPATH', )__DIR__ . DIRECTORY_SEPARATOR;

Line #67 - Unhandled \CodeIgniter\Router\Exceptions\RedirectException
$app->run();

### Steps to Reproduce

Open in phpStorm
Top right Warning sign.

### Expected Output

No Warnings.

**Comment by kenjis** [comment]
If you think this should be fixed, why don't you send a PR?
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

**Comment by iRedds** [comment]
@kenjis Can the Codeigniter::run() method really throw RedirectExceptions?
This exception is caught in the ``catch`` block, so I think the ``* @throws RedirectException`` docblock is misleading. Or am I missing something?

**Comment by kenjis** [comment]
@InsiteFX If you report an issue, please write the file path.

**Comment by kenjis** [comment]
PhpStorm says "Exception 'RedirectException' is never thrown in the function".
![Screenshot 2023-04-14 15 46 28](https://user-images.githubusercontent.com/87955/231965034-4c001965-475f-45b9-a241-fac13c06be62.png)

**Comment by kenjis** [comment]
@iRedds It seems you are correct. `@throws RedirectException` should be removed.
