### ISSUE TITLE
Bug: The session is not saved

### ISSUE THREAD

**Issue by MatteoCigognini** [codeigniter4/CodeIgniter4#7465]
### PHP Version

8.0

### CodeIgniter4 Version

4.3.2

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

When you set the data in the session and reload the page, the session is empty.

I tried both with session saved in writepath session and database. Same result, empty session.

### Steps to Reproduce

Example:

- Set data to session
`$_SESSION['name_of_the_variable'] = 'Hello world!';`

- After the page reload, this is the result:
`print_r($_SESSION['name_of_the_variable']); // Array ( [__ci_last_regenerate] => 1682676778 )`

### Expected Output

`print_r($_SESSION['name_of_the_variable']); // Array ( [__ci_last_regenerate] => 1682676778, [name_of_the_variable] => 'Hello world!')`

**Comment by ddevsr** [comment]
I cannot reproduce

**Comment by ddevsr** [comment]
Read docs on https://codeigniter4.github.io/CodeIgniter4/libraries/sessions.html

**Comment by MatteoCigognini** [comment]
> I cannot reproduce

The problem is that the session gets emptied, wherever I set it. There is something wrong with the session management functions probably.

**Comment by kenjis** [comment]
Try:
```php
$session = \Config\Services::session();
$session->set('name_of_the_variable', 'Hello world!');
```

Using `$_SESSION` is not recommended.

**Comment by MatteoCigognini** [comment]
> Try:
> 
> ```
> $session = \Config\Services::session();
> $session->set('name_of_the_variable', 'Hello world!');
> ```
> 
> Using `$_SESSION` is not recommended.

Ok, I've tried `$session->set('name_of_the_variable', 'Hello world!');`

The result is always the same, the session does not contain the variable 'name_of_the_variable'.

Using the database driver I noticed that every time I reload the page a new session is generated.

**Comment by kenjis** [comment]
> The id value contains the session cookie name (Config\Session::$cookieName) and the session ID and a delimiter. It should be increased as needed, for example, when using long session IDs.
https://codeigniter.com/user_guide/libraries/sessions.html#configure-databasehandler
