### ISSUE TITLE
Bug: [DebugBar] Missing CSP nonce value

### ISSUE THREAD

**Issue by donpwinston** [codeigniter4/CodeIgniter4#7473]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.4

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

When the toolbar is turned, CSPEnables is true the nonce value appears to be missing in the javascript code below:

```js
            var t = window.open();
                t && (t.document.open(), t.document.write(l.mktag("html") + l.mktag("head") + l.mktag("title") + "Kint (" + (new Date).toISOString() + ")" + l.mktag("/title") + l.mktag('meta charset="utf-8"') + l.mktag('script class="kint-rich-script" nonce="' + l.script.nonce + '"') + l.script.innerHTML + l.mktag("/script") + l.mktag('style class="kint-rich-style" nonce="' + l.style.nonce + '"') + l.style.innerHTML + l.mktag("/style") + l.mktag("/head") + l.mktag("body") + '<input class="kint-note-input" placeholder="Take some notes!"><div class="kint-rich">' + e.parentNode.outerHTML + "</div>" + l.mktag("/body")), t.document.close())
```

### Steps to Reproduce

Turn CSPEnabled on, set CI_ENVIRONMENT to 'development'. Request a page generated by CI. Look at browser javascript console. An error stating missing nonce value will be displayed. In my case the browser is Safari.

### Expected Output

No error in the Javascript console.

**Comment by kenjis** [comment]
Thank you for reporting. What's the exact error message?

**Comment by donpwinston** [comment]
Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy.




 

    On Tuesday, May 2, 2023 at 08:13:15 AM EDT, kenjis ***@***.***> wrote:  
 
 


Thank you for reporting. What's the exact error message?

**Comment by kenjis** [comment]
It seems there is no JavaScript code that was reported in the current version (4.4.x).
If you still have this issue, please go to #8405 or create an new issue.
