### ISSUE TITLE
Bug: {csp-style-nonce} Does Not Work when 404

### ISSUE THREAD

**Issue by donpwinston** [codeigniter4/CodeIgniter4#7476]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

in app/Views/errors/html/error_404.php I added {csp-style-nonce} to the style tag:

`<style {csp-style-nonce}> `

no nonce value was inserted when the 404 page was requested. 

```
CI_ENVIRONMENT = 'development'
CSPEnabled = true
autoNonce = true
```

however when I used `<?= csp_style_nonce() ?>` instead a nonce value was inserted as expected.

### Steps to Reproduce

in app/Views/errors/html/error_404.php I added `{csp-style-nonce}` to the style tag:

`<style {csp-style-nonce}> `

no nonce value was inserted when the 404 page was requested. 

```
CI_ENVIRONMENT = 'development'
set CSPEnabled = true
set autoNonce = true
```

### Expected Output

```
<style nonce="e4c8794ad48fbce7b02b6143">
```

### Anything else?

Maybe the toolbar is why it doesn't work for some reason.

**Comment by kenjis** [comment]
This is not a bug, or if it is, it cannot be easily fixed.
If we change the behavior, I think we need more discussions.

Currently, 404 is handled as an exception in exception handler, and the replacement of the string `{csp-style-nonce}` is not performed. It is done for only normal requests.

I recommend you use`csp_style_nonce()` and disable AutoNonce, because it is more secure.

**Comment by donpwinston** [comment]
ok, thanks 

    On Tuesday, May 2, 2023 at 07:43:50 PM EDT, kenjis ***@***.***> wrote:  
 
 


This is not a bug, or if it is, it cannot be easily fixed.
If we change the behavior, I think we need more discussions.

Currently, 404 is handled as an exception in exception handler, and the replacement of the string {csp-style-nonce} is not performed. It is done for only normal requests.

I recommend you usecsp_style_nonce() and disable AutoNonce, because it is more secure.
