### ISSUE TITLE
Bug: PosgreSQL server version

### ISSUE THREAD

**Issue by marekmosna** [codeigniter4/CodeIgniter4#7484]
### PHP Version

8.0

### CodeIgniter4 Version

v4.3.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli

### Database

PostgreSQL 13.10

### What happened?

`$db->getVersion();`  returns `false`

### Steps to Reproduce

```
$db = db_connect();
echo $db->getVersion();
```

### Expected Output

13.10 (Debian 13.10-0+deb11u1)

### Anything else?

I can make a pull request to fix it. Please specify if you want to store and return entire `$pgVersion['server']`  or just version accorsing to [version semantic](https://semver.org/)

**Comment by michalsn** [comment]
Yes, the code logic in the `getVersion()` method is broken. A fix would be greatly appreciated. 

We just need the version number from `$pgVersion['server']`.
