### ISSUE TITLE
Bug: getGet, getPost, and other becomes undefined method after use ResponseTrait

### ISSUE THREAD

**Issue by sk8dvlpr** [codeigniter4/CodeIgniter4#7486]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

in previous version 4.3.3 it worked normally when using use ResponseTrait, but when updating to version 4.3.4 getGet or getPost and others it becomes Undefined Method. but the getGet or getPost functions are still running normally, but in my IDE it turns red and it's very annoying. I tried asking using Slack but it seems no one is very active there.

### Steps to Reproduce

use ResponseTrait;

### Expected Output

Defined Method

**Comment by michalsn** [comment]
Hmm... not a bug per se, but it can be annoying.

I guess this change created the issue: https://github.com/codeigniter4/CodeIgniter4/commit/de96bb0441eeb14af281fd2b161950059c5b9e39

The change seems reasonable. My knowledge of making IDE happy is small, but hopefully, someone can come up with a solution.

**Comment by kenjis** [comment]
I sent a PR #7495
