### ISSUE TITLE
Bug: Validation: Closure rule in combination with rule `permit_empty` fails

### ISSUE THREAD

**Issue by element-code** [codeigniter4/CodeIgniter4#7490]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.4

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

When using [`permit_empty`](https://www.codeigniter.com/user_guide/libraries/validation.html#rules-for-general-use) in combination with a [closure rule](https://www.codeigniter.com/user_guide/libraries/validation.html#using-closure-rule) the fatal error `Object of class Closure could not be converted to string` at [SYSTEMPATH/Validation/Validation.php at line 279](https://github.com/codeigniter4/CodeIgniter4/blob/42b174fc75d01098936514606f6147dffbaccb8b/system/Validation/Validation.php#L278) occurs.

### Steps to Reproduce

Use `'rules' => ['permit_empty', fn($value) => true]` as validation config and supply an empty value for the field.

### Expected Output

1. check if the key of the rule is one of `required_with` and `required_without` for closures too, as done for all other rules
2. closures should work in combination with `permit_empty`

### Anything else?

It is likely that `array_diff` has difficulties with non-string values; which would be an issue with [`if_exist`](https://github.com/codeigniter4/CodeIgniter4/blob/42b174fc75d01098936514606f6147dffbaccb8b/system/Validation/Validation.php#L242) too.

**Comment by element-code** [comment]
Hi @michalsn, I also worked on a bug fix in the meantime.
Mix bug fix is only for PHP 8.2, so there might be some changes needed.
All in all, I primarily introduced `processSingleRule` to get rid of all the duplicate code.

https://github.com/codeigniter4/CodeIgniter4/compare/develop...element-code:CodeIgniter4:fix-validation-closures

**Comment by michalsn** [comment]
@element-code Sounds great!

I didn't want to mix things up, so I only focused on fixing the reported bug. But feel free to send a PR that will refactor the code to make it better / cleaner.

**Comment by element-code** [comment]
@michalsn sounds good. I don't have the time to write extensive tests tho, is this something you would participate in?
