### ISSUE TITLE
Bug: output buffer

### ISSUE THREAD

**Issue by iRedds** [codeigniter4/CodeIgniter4#7493]
### PHP Version

7.4

### CodeIgniter4 Version

all

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

The application starts monitoring the buffer in the ``CodeIgniter::tryToRouteIt()`` method.
https://github.com/codeigniter4/CodeIgniter4/blob/42b174fc75d01098936514606f6147dffbaccb8b/system/CodeIgniter.php#L813

For a correct response, and in case of a 404 error, if a custom handler is defined, the ``CodeIgniter::gatherOutput()`` method is called. In which we are trying to complete the monitoring of the buffer.

https://github.com/codeigniter4/CodeIgniter4/blob/42b174fc75d01098936514606f6147dffbaccb8b/system/CodeIgniter.php#L1009-L1014

But this code only works if something was passed to the buffer, such as using ``echo``.
If nothing has been written to the buffer, then buffer monitoring is not disabled.
Also, if the ``ob_start()`` function has been called multiple times while the application is running, then ``ob_end_clean()`` will only terminate the last one.

### Steps to Reproduce

```php
namespace CodeIgniter;

use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\Mock\MockCodeIgniter;
use Config\App;

/**
 * @internal
 */
final class StepsToReproduceTest extends CIUnitTestCase
{
    public function testOB()
    {
        $actual['phpunit'] = ob_get_level();

        ob_start();

        $actual['beforeApp'] = ob_get_level();

        (new MockCodeIgniter(new App()))->run();

        $actual['afterApp'] = ob_get_level();

        ob_get_clean();

        $this->assertSame(
            [
                'phpunit' => 1,
                'beforeApp' => 2,
                'afterApp' => 2,
            ],
            $actual
        );
    }
}
```
```
1) CodeIgniter\StepsToReproduceTest::testOB
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &0 (
     'phpunit' => 1
     'beforeApp' => 2
-    'afterApp' => 2
+    'afterApp' => 3
 )

```

### Expected Output

Normalize work on the buffer.

### Anything else?

In the \CodeIgniter\Debug\Exceptions class, buffer monitoring also ends incorrectly.
https://github.com/codeigniter4/CodeIgniter4/blob/42b174fc75d01098936514606f6147dffbaccb8b/system/Debug/Exceptions.php#L273-L275

```php
class OBuffer
{
    protected ?int $level;

    public function start(): void
    {
        $this->level = ob_get_level();
        ob_start();
    }

    public function getClean(): string
    {
        $content = '';

        while (ob_get_level() > $this->level) {
            $content .= ob_get_contents();
            ob_end_clean();
        }

        return $content;
    }
}
```

This is an example of code that, in my opinion, will solve the buffer monitoring problem if you replace the ``ob_`` function calls in the ``CodeIgniter::tryToRouteIt()`` and ``CodeIgniter::gatherOutput()`` methods with the appropriate methods class.
It will also remove redundant code.

https://github.com/codeigniter4/CodeIgniter4/blob/42b174fc75d01098936514606f6147dffbaccb8b/system/CodeIgniter.php#L1018-L1022

**Comment by kenjis** [comment]
Closed by #7500
