### ISSUE TITLE
Bug: Missing 404 response code for custom handler.

### ISSUE THREAD

**Issue by iRedds** [codeigniter4/CodeIgniter4#7494]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

If a custom 404 handler is defined and it does not return a Response instance with a response code set, then the response code will be 200.

### Steps to Reproduce

```php
$routes->set404Override([Test::class, 'index']);

public function index()
{
    echo 'error'; // HTTP 200 expected 404
    return 'error'; // HTTP 200 expected 404
    return $this->response->setBody('error'); // HTTP 200 expected 404
    return $this->response->setBody('with code')->setStatusCode(400); // HTTP 400
}
```

### Expected Output

The 404 response code should be the default.

**Comment by kenjis** [comment]
> The set404Override() method does not change the Response status code to 404. If you don’t set the status code in the controller you set, the default status code 200 will be returned. 
https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#override

**Comment by iRedds** [comment]
I disagree. It sounds like: "We will cut off your leg, but you can put on a prosthesis yourself".

In fact, with this note, the team is trying to avoid responsibility.
If this is a 404 error, then 404 should be returned by default, and if a different response code is needed, then the developer should install it himself.

**Comment by kenjis** [comment]
It is the behavior in CI3.
If we change the behavior, it is a breaking change.

I'm not sure the feature is really to show 404 error, because it does not return the response code 404.
But it is true the name is `set404Override()`, so it is natural to interpret as what you say.

If you really need to change this as a bug, we need consensus.

**Comment by iRedds** [comment]
Either no one in the core team is interested, or no one monitors the repository.
Well, I'm tired of banging my head against the wall.
