### ISSUE TITLE
env file doesn't coming with dot in CI 4.3.4

### ISSUE THREAD

**Issue by ritika7111** [codeigniter4/CodeIgniter4#7497]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

Mysql

### What happened?

Hi Team,

env file doesn't coming with dot in CI 4.3.4 due to that developers are experiencing multiple issues related to environment changes and database connection. would you please resolve it ASAP. so that new users or developer didn't face the same issues which I had faced at initial level of development using CI 4.3.4.

Thanks,
Ritika

### Steps to Reproduce

Manuallly installation of CI 4.3.4

### Expected Output

env file should come with dot it should be .env

### Anything else?

Please resolve it soon so the new developers will not face the issues.

**Comment by paulbalandan** [comment]
The `env` file shipping with every release is meant to be used as the template. You need to `cp env .env` to create your own `.env` file from this template.

**Comment by kenjis** [comment]
See https://codeigniter4.github.io/CodeIgniter4/general/configuration.html#environment-variables-and-codeigniter
