### ISSUE TITLE
Bug: PageRendered.php -  getNext() and getPrevious()

### ISSUE THREAD

**Issue by xttrust** [codeigniter4/CodeIgniter4#7502]
### PHP Version

8.1

### CodeIgniter4 Version

v4.3.4-0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

 MySQL 5.6

### What happened?

```php
public function getPrevious()
    {
        if (! $this->hasPrevious()) {
            return null;
        }

        $uri = clone $this->uri;

        if ($this->segment === 0) {
            $uri->addQuery($this->pageSelector, $this->first- 1);
        } else {
            $uri->setSegment($this->segment, $this->first- 1);
        }

        return URI::createURIString(
            $uri->getScheme(),
            $uri->getAuthority(),
            $uri->getPath(),
            $uri->getQuery(),
            $uri->getFragment()
        );
    }
```
```php
public function getNext()
    {
        if (! $this->hasNext()) {
            return null;
        }

        $uri = clone $this->uri;

        if ($this->segment === 0) {
            $uri->addQuery($this->pageSelector, $this->last+ 1);
        } else {
            $uri->setSegment($this->segment, $this->last+ 1);
        }

        return URI::createURIString(
            $uri->getScheme(),
            $uri->getAuthority(),
            $uri->getPath(),
            $uri->getQuery(),
            $uri->getFragment()
        );
    }
```

### Steps to Reproduce
```php
public function getPrevious()
    {
        if (! $this->hasPrevious()) {
            return null;
        }

        $uri = clone $this->uri;

        if ($this->segment === 0) {
            $uri->addQuery($this->pageSelector, $this->current - 1);
        } else {
            $uri->setSegment($this->segment, $this->current - 1);
        }

        return URI::createURIString(
            $uri->getScheme(),
            $uri->getAuthority(),
            $uri->getPath(),
            $uri->getQuery(),
            $uri->getFragment()
        );
    }
```
```php
public function getNext()
    {
        if (! $this->hasNext()) {
            return null;
        }

        $uri = clone $this->uri;

        if ($this->segment === 0) {
            $uri->addQuery($this->pageSelector, $this->current + 1);
        } else {
            $uri->setSegment($this->segment, $this->current + 1);
        }

        return URI::createURIString(
            $uri->getScheme(),
            $uri->getAuthority(),
            $uri->getPath(),
            $uri->getQuery(),
            $uri->getFragment()
        );
    }
```

### Expected Output

The pager didn't work properly. The prev and next buttons didn't go to the next page or the prev page. It jumped by `$pager->setSurroundCount(2);`

Example: First, Prev, 1.2.current.4.5 Next, Last
When press the next will go to page 7 instead of page 4. Same thing with prev.

By modifying `$this->first`/`$this->last` with `$this->current` fix the problem.

**Comment by michalsn** [comment]
This might be a bit confusing, but please read the user guide section about the differences between `getNext()`, `getPrevious()` and, `getNextPage()`, `getPreviousPage()`. You want to use the latter two.

https://codeigniter.com/user_guide/libraries/pagination.html#links

**Comment by kenjis** [comment]
Yes, that is clearly documented:
>For example, you have the current page set at 5 and you want to have the links before and after (the surroundCount) to be 2 each, that will give you something like this:
>
>3  |  4  |  5  |  6  |  7
>
>getPrevious() returns the URL for page 2. getNext() returns the URL for page 8.
>
>If you want to get page 4 and page 6, use getPreviousPage() and getNextPage() instead.

https://codeigniter.com/user_guide/libraries/pagination.html#getprevious-getnext
