### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by nmauludina** [codeigniter4/CodeIgniter4#7521]
### PHP Version

8.0

### CodeIgniter4 Version

4.1.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.27

### What happened?

I am trying to [run controller by cli](https://codeigniter.com/user_guide/cli/cli_controllers.html#running-controllers-via-cli). It runs in starter project with the same version but doesn't run in my project.
My project use [myth-auth package](https://github.com/lonnieezell/myth-auth). Everything is fine until I set aliases in  `app/config/filter.php` file.

The thing I say it does not work means the console just showing blank, no error statement, no information, just blank.
![image](https://github.com/codeigniter4/CodeIgniter4/assets/59868224/133db155-c4b8-42de-918b-d89606db1ae9)

### Steps to Reproduce

1. Use Codeigniter 4.1.1
2. Install [myth-auth package](https://github.com/lonnieezell/myth-auth)
3. Config the package
4. Do db migration
5. Try the example [run controller by cli](https://codeigniter.com/user_guide/cli/cli_controllers.html#running-controllers-via-cli)

### Expected Output

It will shows "Hello World!" in the console.

**Comment by ddevsr** [comment]
Its not bug, you loaded double extentions `openssl`

**Comment by samsonasik** [comment]
Closing as not a bug.

**Comment by kenjis** [comment]
Don't use 4.1.1. It has a lot of vulnerabilities.
https://github.com/codeigniter4/CodeIgniter4/security/advisories

**Comment by nmauludina** [comment]
> Its not bug, you loaded double extentions `openssl`

ignore 'openssl', it also appear in starter ci 4.1.1 project
![image](https://github.com/codeigniter4/CodeIgniter4/assets/59868224/db88e525-20df-4ed5-9fec-b557b72ea667)

**Comment by samsonasik** [comment]
It is not a bug,  You configure php extension wrong, also, please use latest version. You can ask question to forum instead http://forum.codeigniter.com/
