### ISSUE TITLE
Incorrect Date (Month) Display

### ISSUE THREAD

**Issue by KipchirchirIan** [codeigniter4/CodeIgniter4#7528]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

What is the current behavior of the Date & Time library and is the documentation up to date? Incorrect month is displayed when you try to display the month using `Time::createFromDate();`. This looked so unreal to me to the point I was doubting myself as to whether it's a serious bug or I was the one making a mistake somewhere. I have decided to post it anyway. I apologize if this is a mistake on my part.

Some examples and what the result is:

**Note**: Todays date is:  _31st May 2023_
```php
dd(\CodeIgniter\I18n\Time::createFromDate(null, 2)->toLocalizedString('MMM d, yyyy')); // Result: Mar 3, 2023
```
```php
dd(\CodeIgniter\I18n\Time::createFromDate(null, 4)->toLocalizedString('MMM d, yyyy')); // Result: May 1, 2023
```
```php
dd(\CodeIgniter\I18n\Time::createFromDate(null, 6)->toLocalizedString('MMM d, yyyy')); // Result: Jul 1, 2023
```
```php
dd(\CodeIgniter\I18n\Time::createFromDate(null, 9)->toLocalizedString('MMM d, yyyy')); // Result: Oct 1, 2023
```
```php
dd(\CodeIgniter\I18n\Time::createFromDate(1, 11)->toLocalizedString('MMM d, yyyy')); // Result: Dec 1, 2001
```

Basically, printing from 1 - 12 displays: `Jan, Mar, Mar, May, May, Jul, Jul, Aug, Oct, Oct, Dec, Dec`

### Steps to Reproduce

- Install afresh CI 4.3.5 with Composer AppStarter and just `dd()` in the `Home` controller within the `index()` method.

```php
class Home extends BaseController
{
    public function index()
    {
        dd(\CodeIgniter\I18n\Time::createFromDate(null, 9)->toLocalizedString('MMM d, yyyy'));
        //return view('welcome_message');
    }
}
```

- Create copy of `env` file and rename it to `.env`
- Uncomment and replace `production` with `development` in the `.env` file:

```sh
#--------------------------------------------------------------------
# ENVIRONMENT
#--------------------------------------------------------------------

CI_ENVIRONMENT = development
```

- CD into your project root directory and type the command below then press enter:

```sh
php spark serve
```

### Expected Output

```php
dd(\CodeIgniter\I18n\Time::createFromDate(null, 1)->toLocalizedString('MMM d, yyyy')); // Result: Jan 31, 2023
```
The result above is correct based on CI4's documentation which mentions that if the value for either year, month or day is left empty or null, the current value for year, month or day will be used respectively. Interesting thing is, if you include the day part everything works fine i.e.

```php
dd(\CodeIgniter\I18n\Time::createFromDate(null, 2, 1)->toLocalizedString('MMM d, yyyy')); // Result: Feb 1, 2023
```

Reversing the day and month:

```php
dd(\CodeIgniter\I18n\Time::createFromDate(null, 1, 2)->toLocalizedString('MMM d, yyyy')); // Result: Jan 2, 2023
```

For the 2nd argument with 9 as the value: 

```php
dd(\CodeIgniter\I18n\Time::createFromDate(null, 9)->toLocalizedString('MMM d, yyyy')); // Result: Sep 31, 2023
```
 The rest should be obvious.

**Comment by paulbalandan** [comment]
These all seem correct behavior for me:
```php
dd(\CodeIgniter\I18n\Time::createFromDate(null, 2)->toLocalizedString('MMM d, yyyy'));
// Original Result: Feb. 31, 2023 -->incorrect date! move 3 days after (31 - 28)
// Final Result: Mar 3, 2023

dd(\CodeIgniter\I18n\Time::createFromDate(null, 4)->toLocalizedString('MMM d, yyyy'));
// Original: April 31, 2023 -->incorrect date! move 1 day after (31 - 30)
// Result: May 1, 2023

dd(\CodeIgniter\I18n\Time::createFromDate(null, 6)->toLocalizedString('MMM d, yyyy'));
// Original: June 31, 2023 --> incorrect again; adjust 1 day
// Result: Jul 1, 2023

dd(\CodeIgniter\I18n\Time::createFromDate(null, 9)->toLocalizedString('MMM d, yyyy'));
// Original: September 31, 2023 --> incorrect; move 1 day
// Result: Oct 1, 2023

dd(\CodeIgniter\I18n\Time::createFromDate(1, 11)->toLocalizedString('MMM d, yyyy'));
// Original: Nov 31, 2023 --> move 1 day
// Result: Dec 1, 2001
```

**Comment by paulbalandan** [comment]
See https://3v4l.org/9TFd8. This is native to PHP.
