### ISSUE TITLE
Bug: Parents filters are not work in group and subgroups routes

### ISSUE THREAD

**Issue by haralex89** [codeigniter4/CodeIgniter4#7530]
### PHP Version

7.4

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MariaDB 10.5

### What happened?

If you have a groups and subgroups routes and each group contains diferents filters, the system take the internal filter and remove the parents filter.

For example: if you visit the route primary/primary-group take efect the authGuardPrimary it´s fine. But, if you visit the route primary/second/second-group take efect the authGuardSecond and authGuardPrimary not work

```php
$routes->group('primary', ['filter' => ['authGuardPrimary']], static function ($routes) {
    $routes->add('primary-group', 'Home::primary');
    $routes->group('second', ['filter' => ['authGuardSecond']], static function ($routes) {
        $routes->add('second-group', 'Home::second');
    });
});
```

### Steps to Reproduce

```php
$routes->group('primary', ['filter' => ['authGuardPrimary']], static function ($routes) {
    $routes->add('primary-group', 'Home::primary');
    $routes->group('second', ['filter' => ['authGuardSecond']], static function ($routes) {
        $routes->add('second-group', 'Home::second');
    });
});
```

### Expected Output

The authGuardPrimary should execute when i visit the route primary/second/second-group

**Comment by iRedds** [comment]
doc: "Options passed to the outer group() (for example namespace and filter) are not merged with the inner group() options."

**Comment by kenjis** [comment]
Yes, it is documented clearly.
See the note in https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#grouping-routes
