### ISSUE TITLE
Bug: Layouts routes accept wrong lowercase route.

### ISSUE THREAD

**Issue by defg-dev** [codeigniter4/CodeIgniter4#7533]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 8.0

### What happened?

`<?= $this->extend('layouts\Admin\main') ?>` This work perfectly but the real folder name is "Layout", back-slash still work equal.
When enter on production appaer the error message.

`<?= $this->extend('layouts\Admin\main') ?>` and this `<?= $this->extend('Layouts/Admin/main') ?>` do the same thing. This is correct?

### Steps to Reproduce

Create a layout extend() call.

### Expected Output

Show views correctly

**Comment by kenjis** [comment]
> The extend() method takes the name of any view file that you wish to use. Since they are standard views, they will be located just like a view. By default, it will look in the application’s View directory, but will also scan other PSR-4 defined namespaces.
https://codeigniter4.github.io/CodeIgniter4/outgoing/view_layouts.html#using-layouts-in-views

`'layouts\Admin\main'` is a *namespaced* view. It means `Admin/main.php` in the `layouts` namespace.
`'Layouts/Admin/main'` is a view path. It means `app/View/Layouts/Admin/main.php`.

**Comment by kenjis** [comment]
> When enter on production appaer the error message.

What is the exact error message?

**Comment by kenjis** [comment]
`\` is the namespace delimiter. `/` is the file path delimiter. 
Do not confuse these.

**Comment by defg-dev** [comment]
> 

Understod, work perfectly on windows folder system, codeignter route correctly, but on linux fail, drop Invalid file name error.

**Comment by kenjis** [comment]
> You should always be careful about the case of filenames. Many developers develop on case-insensitive file systems on Windows or macOS. However, most server environments use case-sensitive file systems. If the file name case is incorrect, the autoloader cannot find the file on the server.
https://codeigniter4.github.io/CodeIgniter4/concepts/autoloader.html#codeigniter4-autoloader

> This work perfectly but the real folder name is "Layout"

It is just a misuse. If you want to point out the file path and the folder name is `Layout`,
you must write it as `Layout`. On Windows it just happen to work, but does not work on most servers that run on Linux.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
