### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Ningthem-Singh** [codeigniter4/CodeIgniter4#7546]
### PHP Version

7.4, 8.0, 8.1

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

Maria DB 10.4.22

### What happened?

Showing there is no route if i use the CodeIgniter 4 syntax which is 
$routes->get('/', [Home::class, 'index']); it doesn't work instead have to use the older syntax that is 
$routes->get('/', 'Home::index'); 

![Screenshot 2023-06-07 154456](https://github.com/codeigniter4/CodeIgniter4/assets/107441727/80d4c57e-fb29-4077-8e21-78a022007bd2)
![Screenshot 2023-06-07 154621](https://github.com/codeigniter4/CodeIgniter4/assets/107441727/4a202b4a-7b80-43ea-8d6a-0bae21553f83)

### Steps to Reproduce

Instead of CI3 syntax in route if you use CI4 syntax there is error

### Expected Output

As i am using CI4 it only wise to use the CI4 syntax instead of the older CI3 syntax

**Comment by kenjis** [comment]
It is just a misuse, not a bug.
See the screenshot. It shows `not found: \Config\Home::index`.
The controller should be `App\Controllers\Home`.
If you use `::class` keyword, you must specify the correct classname.
You need to learn PHP namespaces.

**Comment by Ningthem-Singh** [comment]
Yes I am new to this stuff but could you help in understanding why in some route it works and the in others it doesn't and i have to use the old technique/syntax. This is my routes.php

<?php
namespace Config;
use App\Controllers\RegisterController;
use App\Controllers\TasksController;

// Create a new instance of our RouteCollection class.
$routes = Services::routes();

/*
 * --------------------------------------------------------------------
 * Router Setup
 * --------------------------------------------------------------------
 */
$routes->setDefaultNamespace('App\Controllers');
$routes->setDefaultController('Home');
$routes->setDefaultMethod('index');
$routes->setTranslateURIDashes(false);
$routes->set404Override();

// $routes->get('/', [Home::class, 'index']); ///this doesnt work idk why
$routes->get('/', 'Home::index'); // instead this works
$routes->get('/login', 'LoginController::index');
$routes->get('/register', [RegisterController::class, 'index']); // but in this case it works
$routes->get('/tasks', [TasksController::class, 'index']);  //also this works
$routes->get('/tasks/show/(:num)', [TasksController::class, 'show']);   //also this works

$routes->post('/register', [RegisterController::class, 'do_register']); //also this works
$routes->post('/login', 'LoginController::do_login');   //the ::class doesnt work here as well

if (is_file(APPPATH . 'Config/' . ENVIRONMENT . '/Routes.php')) {
    require APPPATH . 'Config/' . ENVIRONMENT . '/Routes.php';
}
//------------------------------------------------------------------------------------------------------------------------------

> It is just a misuse, not a bug. See the screenshot. It shows `not found: \Config\Home::index`. The controller should be `App\Controllers\Home`. If you use `::class` keyword, you must specify the correct classname. You need to learn PHP namespaces.

**Comment by kenjis** [comment]
Because you don't understand PHP namespaces.
It is not CI4 thing, but PHP thing.
CI4 and modern PHP uses namespaces everywhere.
So I recommend you learn namespacing completely.

Read:
- https://www.w3schools.com/php/php_namespaces.asp
- https://www.php.net/manual/en/language.namespaces.rationale.php

P.S. If you show your code, do not use screenshots, but use copy and paste, please.

**Comment by Ningthem-Singh** [comment]
Thank you for the knowledge shared by you.
> And Yes i have got it I realized now why you kept saying namespaces even though I used it but only on the `RegisterController` and I should have done the same for `LoginController` and `Home` as well. 
> And yes I have not used Markdown so much.

![Thank You Logo]
(https://www.google.com/url?sa=i&url=https%3A%2F%2Ftenor.com%2Fsearch%2Fthanks-you-gifs&psig=AOvVaw1yf8lT6ViH7HUaQf2IyHA_&ust=1686287660332000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJil7Zn1sv8CFQAAAAAdAAAAABAJ)
