### ISSUE TITLE
Bug: pgsql password containing semicolons

### ISSUE THREAD

**Issue by MickaelCa** [codeigniter4/CodeIgniter4#7550]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.3

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

PostgreSQL

### What happened?

```
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;db-dev-pgbouncer.default.svc.cluster.local&quot; (10.98.218.164), port 5432 failed: FATAL: SASL authentication failed
```

### Steps to Reproduce

Use a pgsql password with a semicolon

### Expected Output

Connection not failing

### Anything else?

https://github.com/codeigniter4/framework/blob/master/system/Database/Postgre/Connection.php#L72-L73

**Comment by kenjis** [comment]
Thank you for reporting.

How do you configure app/Config/Database.php?
and how do you fix this bug?
