### ISSUE TITLE
Bug:  sql error ON DUPLICATE KEY UPDATE (in the upsertBatch method)

### ISSUE THREAD

**Issue by silvasamu** [codeigniter4/CodeIgniter4#7563]
### PHP Version

7.4

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySQL 5.7

### What happened?

When executing the method, it is generating the wrong sql

### Steps to Reproduce

```php
$query = $this->db->table('user2')
    ->select('user2.name, user2.email, user2.country')
    ->join('user', 'user.email = user2.email', 'left')
    ->where('user.email IS NULL');

$sql = $builder->setQueryAsData($query)->upsertBatch();
``` 

/* MySQLi produces:
    INSERT INTO `db_user` (`country`, `email`, `name`)
    SELECT user2.name, user2.email, user2.country
    FROM user2
    LEFT JOIN user ON user.email = user2.email
    WHERE **user.email IS NULLON** DUPLICATE KEY UPDATE
    `country` = VALUES(`country`),
    `email` = VALUES(`email`),
    `name` = VALUES(`name`)
*/

### Expected Output

```php
$query = $this->db->table('user2')
    ->select('user2.name, user2.email, user2.country')
    ->join('user', 'user.email = user2.email', 'left')
    ->where('user.email IS NULL');

$sql = $builder->setQueryAsData($query)->upsertBatch();
``` 

/* MySQLi produces:
    INSERT INTO `db_user` (`country`, `email`, `name`)
    SELECT user2.name, user2.email, user2.country
    FROM user2
    LEFT JOIN user ON user.email = user2.email
    WHERE **user.email IS NULL _(add a space here)_ ON** DUPLICATE KEY UPDATE
    `country` = VALUES(`country`),
    `email` = VALUES(`email`),
    `name` = VALUES(`name`)
*/

**Comment by kenjis** [comment]
Try:
```diff
--- a/system/Database/BaseBuilder.php
+++ b/system/Database/BaseBuilder.php
@@ -1982,7 +1982,7 @@ class BaseBuilder
         if ($sql === '') {
             $updateFields = $this->QBOptions['updateFields'] ?? $this->updateFields($keys)->QBOptions['updateFields'] ?? [];
 
-            $sql = 'INSERT INTO ' . $table . ' (' . implode(', ', $keys) . ")\n{:_table_:}ON DUPLICATE KEY UPDATE\n" . implode(
+            $sql = 'INSERT INTO ' . $table . ' (' . implode(', ', $keys) . ")\n{:_table_:} ON DUPLICATE KEY UPDATE\n" . implode(
                 ",\n",
                 array_map(
                     static fn ($key, $value) => $table . '.' . $key . ($value instanceof RawSql ?
```

**Comment by kenjis** [comment]
Please check #7564

**Comment by silvasamu** [comment]
It worked! thanks!
