### ISSUE TITLE
imagecreatefrompng(): gd-png: libpng warning

### ISSUE THREAD

**Issue by YapsBridging** [codeigniter4/CodeIgniter4#7567]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

mysql

### What happened?

when i try to resize some image but not all image i found this error

imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile
codeigniter4\framework\system\Images\Handlers\GDHandler.php  line 357

### Steps to Reproduce

```php
$image = \Config\Services::image();
$image->withFile(WRITEPATH . '/uploads/test.png')
->resize(100,100)
->save(WRITEPATH . '/uploads/test2.png');
```

### Expected Output

image resize

### Anything else?

![10](https://github.com/codeigniter4/CodeIgniter4/assets/34118561/815b3986-08b4-4ed2-b9c1-a9b8bf034cfb)

this sample image

**Comment by YapsBridging** [comment]
also
imagecreatefromjpeg()
imagecreatefromgif()

the function can return error

https://www.php.net/manual/en/function.imagecreatefromgif.php

https://www.php.net/manual/en/function.imagecreatefrompng.php

**Comment by michalsn** [comment]
Should the attached file cause an error? Because I'm not able to get it.

PHP 8.2.6, libpng 1.6.39

**Comment by kenjis** [comment]
I've got no error.
![test2](https://github.com/codeigniter4/CodeIgniter4/assets/87955/0c952429-d49b-4a55-9a86-9a2b3c9781d6)
PHP 8.1.20

**Comment by YapsBridging** [comment]
> Should the attached file cause an error? Because I'm not able to get it.
> 
> PHP 8.2.6, libpng 1.6.39

sory my english not good

i think the file may have a small probrem/broken ,or format RGB non standart..or other,,but file can still work ,can display in good condition

in my situation , i get the error n i dont know  where the problem .why some people not get error.

i try to simple code but still error, 

when i google ..indeed some people got similar error

when i check in manual php 

this function return GDImage or False On error 
in the manual php  to handle the error during loading image 

he use @ for baypass the error..with this @ function can return False or Null,  

and in CI file GDHandler.php.
 he call the function but not use @.. 
i think its the problem..so function doesn't  return false but instead returns an error 
that causing the function Resize CI to stop
