### ISSUE TITLE
Bug: Test feature change value passed in params

### ISSUE THREAD

**Issue by shishamo** [codeigniter4/CodeIgniter4#7593]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

PostgreSQL 15.2

### What happened?

When a `boolean` is  passed as the body to the `call` testing feature params, the value is changed as `string` value
When a `integer` is passed  as the body to the `call` testing feature params, the value is changed as `string` value

### Steps to Reproduce

In the `FeatureTestTrait`
```php
$response = $this->withBodyFormat('json')->call('put', "put/uri", [
    'value1' => true,
    'value2' => false,
    'value3' => 2,
]);
```

In the controller
```php
dd($this->request->getJsonVar());
```

will log
```
stdClass#1912 (2) (
    public 'value1' -> string (1) "1"
    public 'value2' -> string (1) ""
    public 'value3' -> string (1) "2"
)
```

### Expected Output

should log
```
stdClass#1912 (2) (
    public 'value1' -> bool true
    public 'value2' -> bool false
    public 'value3' -> int 2
)
```

**Comment by iRedds** [comment]
I confirm the bug. Present in the current version
In the `call` method, we call methods.
https://github.com/codeigniter4/CodeIgniter4/blob/2834ef991f3735db115040e0d368061b679438f4/system/Test/FeatureTestTrait.php#L158-L159
In the `populateGlobals` method, we store the passed parameters as _REQUEST.
In the `setRequestBody` method, we are trying to form the body, but we are not passing the params argument.

Since the params argument is empty, we try to extract it from _REQUEST.
https://github.com/codeigniter4/CodeIgniter4/blob/2834ef991f3735db115040e0d368061b679438f4/system/Test/FeatureTestTrait.php#L369-L371

But the `fetchGlobal` method returns the value passed through the filter `filter_var($value, FILTER_DEFAULT, 0)`. This casts any value to a string.

**Comment by kenjis** [comment]
> The third parameter accepts an array that is used to populate the superglobal variables for the HTTP verb you are using. So, a method of GET would have the $_GET variable populated, while a post request would have the $_POST array populated.
>
> ...
>
> Note
> The $params array does not make sense for every HTTP verb, but is included for consistency.
>
> https://codeigniter4.github.io/CodeIgniter4/testing/feature.html#requesting-a-page

At least, there is no superglobals for PUT requests in PHP.

**Comment by shishamo** [comment]
sorry, i have forgotten `$this->withBodyFormat('json')` in my example but i am using it in my tests

this is should be handled as a json request isn't it?

**Comment by iRedds** [comment]
@kenjis we have tests with the same behavior as in issue.
https://github.com/codeigniter4/CodeIgniter4/blob/ccd52d1998004324d30cfd7cfc29c337807d0ff3/tests/system/Test/FeatureTestTraitTest.php#L361-L387

but if the data contains a boolean value or an integer, then the tests will fail.

**Comment by kenjis** [comment]
> You can set the format of your request’s body using the withBodyFormat() method. Currently this supports either json or xml. This will take the parameters passed into call(), post(), get()… and assign them to the body of the request in the given format. This will also set the Content-Type header for your request accordingly. 
https://codeigniter4.github.io/CodeIgniter4/testing/feature.html#formatting-the-request

It is true that `withBodyFormat('json')` sets the request body from the parameters and the Content-Type.

So this behavior is a bug, and to populate supergloabals in the documentation are not accurate.

**Comment by kenjis** [comment]
@iRedds The `$response` values in two test methods are exactly the same.
Do you know what the `testCallWithJsonRequestObject()` method tests?

**Comment by iRedds** [comment]
@kenjis Judging by the code, this test checks for the use of an object as an argument in the `assertJSONExact` method.
Although `object` is not declared as a parameter type in docBlock.

**Comment by kenjis** [comment]
Workaround:
```php
        $headers = [
            'CONTENT_TYPE' => 'application/json',
        ];
        $data = [
            'value1' => true,
            'value2' => false,
            'value3' => 2,
        ];
        $response = $this->withHeaders($headers)
            ->withBody(json_encode($data))
            ->call('put', '/');
    }
```
```
stdClass#398 (3) (
    public 'value1' -> boolean true
    public 'value2' -> boolean false
    public 'value3' -> integer 2
)
```

**Comment by kenjis** [comment]
I sent a PR #7602

**Comment by shishamo** [comment]
@kenjis 
i found a strange case when passed `null` in params as well
could you have a look please?

**Comment by shishamo** [comment]
```php
$response = $this->withBodyFormat('json')->call('put', "put/uri", [
    'value1' => null,
]);
```

is logging

```php
stdClass#1740 (2) (
    public 'value1' -> string (0) ""
)
```

**Comment by kenjis** [comment]
Cannot reproduce with #7602
```
stdClass#89 (1) (
    public 'value1' -> null
)
```
```diff
diff --git a/app/Config/Routes.php b/app/Config/Routes.php
index c251ec22c4..a5076ef9da 100644
--- a/app/Config/Routes.php
+++ b/app/Config/Routes.php
@@ -29,7 +29,7 @@ $routes->set404Override();
 
 // We get a performance increase by specifying the default
 // route since we don't have to scan directories.
-$routes->get('/', 'Home::index');
+$routes->put('/', 'Home::index');
 
 /*
  * --------------------------------------------------------------------
diff --git a/app/Controllers/Home.php b/app/Controllers/Home.php
index 7f867e95ff..309bf6aa99 100644
--- a/app/Controllers/Home.php
+++ b/app/Controllers/Home.php
@@ -6,6 +6,6 @@ class Home extends BaseController
 {
     public function index()
     {
-        return view('welcome_message');
+        dd($this->request->getJsonVar());
     }
 }
diff --git a/tests/system/Test/FeatureTestTraitTest.php b/tests/system/Test/FeatureTestTraitTest.php
index 4863d17ae5..aef05d424e 100644
--- a/tests/system/Test/FeatureTestTraitTest.php
+++ b/tests/system/Test/FeatureTestTraitTest.php
@@ -609,4 +609,11 @@ final class FeatureTestTraitTest extends CIUnitTestCase
 
         $this->assertSame('test', $request->getBody());
     }
+
+    public function test()
+    {
+        $response = $this->withBodyFormat('json')->call('put', "/", [
+            'value1' => null,
+        ]);
+    }
 }
```

**Comment by kenjis** [comment]
@shishamo Does #7602 fix your issue or not?

**Comment by MGatner** [comment]
I agree this is a bug. It would be good to get confirmation from @shishamo but I think we proceed regardless.

**Comment by shishamo** [comment]
@kenjis 
@MGatner 
Sorry for the late reply. It looks fine and working for me!
Thank you~
