### ISSUE TITLE
Dev: [php-cs-fixer] Detected deprecations in use

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#7594]
Detected deprecations in use:
- Option "annotation_exclude" for rule "final_internal_class" is deprecated and will be removed in version 4.0. Use "exclude" to configure PHPDoc annotations tags and attributes.
- Option "annotation_include" for rule "final_internal_class" is deprecated and will be removed in version 4.0. Use "include" to configure PHPDoc annotations tags and attributes.
- Rule "no_blank_lines_before_namespace" is deprecated. Use "blank_lines_before_namespace" instead.
- Rule "single_blank_line_before_namespace" is deprecated. Use "blank_lines_before_namespace" instead.

See https://github.com/codeigniter4/CodeIgniter4/actions/runs/5306306699/jobs/9603798768

**Comment by paulbalandan** [comment]
I'll release a little later today.

**Comment by paulbalandan** [comment]
Fixed in https://github.com/CodeIgniter/coding-standard/commit/44c52a40449712840f3a79c9c9e0cee59c6fef91
