### ISSUE TITLE
'schema' array key missing in app\Config\Databse.php

### ISSUE THREAD

**Issue by robertogerola** [codeigniter4/CodeIgniter4#7600]
### PHP Version

8.1

### CodeIgniter4 Version

4.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

PostgreSQL 14.8

### What happened?

The array key `schema` is missing in the array default configuration both for `$default` and `$tests` variables.
This prevents the `schema` setting specified in .env file to be taken into account, and `public` schema is set as default.

### Steps to Reproduce

Set the variable `database.default.schema` in .env file and verifiy it is not considered and 'public' value is instead set by default.

### Expected Output

It should be possible to set the values of `database.default.schema` and `database.tests.schema` variables in the .env file with the default configuration.

**Comment by kenjis** [comment]
The default values are examples for MySQLi and SQLite3.
You can add `schema` by yourself if you use PostgreSQL.

If we add it, we should add all config items in all database drivers.
