### ISSUE TITLE
Validation Placeholders doest work when edit record

### ISSUE THREAD

**Issue by dmonium** [codeigniter4/CodeIgniter4#7601]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.27

### What happened?

after enter a record in the database, if i want to edit some field, i always got logic error validation placeholder, my table is tb_goods, and goods_id is autonumeric, i have only one unique field goods_code 

```php
protected $validationRules;

public function __construct()
	{
$this->validationRules = [
			'goods_id' => [
				'rules' => 'is_natural_no_zero',
				'errors' => [
					'is_natural_no_zero' => 'error desconocido'
				]
			],
			'goods_code' => [
				'rules' => 'is_unique[tb_goods.goods_code,goods_id,{goods_id}]',
				'errors' => [
					'is_unique' => lang('language.goods_rules_code')
				]
			]
]
}
public function modify()
{
if ($this->request->getMethod() == 'post' && $this->validate($this->validationRules )) {
$this->goods->update(
					$this->request->getPost('goods_id'),
					[
						'goods_code' => $this->request->getPost('goods_code'),
						'goods_code_supplier' => $this->request->getPost('goods_code_supplier'),
						'goods_name' => $this->request->getPost('goods_name'),
						'goods_description' => $this->request->getPost('goods_description'),
						'goods_link' => $this->request->getPost('goods_link'),
						'goods_weight' => $this->toNum($this->request->getPost('goods_weight')),
						'unit_id' => $this->request->getPost('unit_id'),
						'chapter_id' => $this->request->getPost('chapter_id'),
						'heading_id' => $this->request->getPost('heading_id'),
						'hscode_id' => $this->request->getPost('hscode_id'),
						'supplier_id' => $this->request->getPost('supplier_id'),
						'user_id' => $this->user_session->user_id
					]
				);
				return redirect()->to(base_url() . 'goods');
}else {
			return $this->edit($this->request->getPost('goods_id'), $this->validator);
		}
}
```

### Steps to Reproduce

open a view to edit field  of goods, click en save button (call goods controller modify function, this use update function) 
get error

### Expected Output

save the changes in goods fields

**Comment by kenjis** [comment]
This is not a bug, but a misuse.

The rule for `goods_id` is `is_natural_no_zero`. It means it must be natural and no zero (empty/not exist is not allowed).
But the data to validate does not have `goods_id`.

If `goods_id` is not required, add `permit_empty` like `permit_empty|is_natural_no_zero`.

**Comment by dmonium** [comment]
I know the update() method, $good_id is never empty neither null , this is generated automumeric in database, when show the edit view I pass the good_id in the data and input hidden, next click in save button via post request and I got it with $this->request->getPost('goods_id').

 if i renove the validation rules for good_id, I still got the error message,

**Comment by kenjis** [comment]
You did not pass `goods_id` in the second parameter (`$data`).
The Model validates the `$data`.

```php
$this->goods->update(
					$this->request->getPost('goods_id'),
					[
						'goods_code' => $this->request->getPost('goods_code'),
						'goods_code_supplier' => $this->request->getPost('goods_code_supplier'),
						'goods_name' => $this->request->getPost('goods_name'),
						'goods_description' => $this->request->getPost('goods_description'),
						'goods_link' => $this->request->getPost('goods_link'),
						'goods_weight' => $this->toNum($this->request->getPost('goods_weight')),
						'unit_id' => $this->request->getPost('unit_id'),
						'chapter_id' => $this->request->getPost('chapter_id'),
						'heading_id' => $this->request->getPost('heading_id'),
						'hscode_id' => $this->request->getPost('hscode_id'),
						'supplier_id' => $this->request->getPost('supplier_id'),
						'user_id' => $this->user_session->user_id
					]
				);
```

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
