### ISSUE TITLE
LogicException: No validation rules for the placeholder: id 

### ISSUE THREAD

**Issue by luciocodeigniter** [codeigniter4/CodeIgniter4#7605]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

5.7.33

### What happened?

When I update a record using validations in the Model, the error LogicException: No validation rules for the placeholder: id

![ERRO_PLACEHOLDER](https://github.com/codeigniter4/CodeIgniter4/assets/100212803/a9045d4e-00f6-444f-a1a6-2d1c780d6957)

### Steps to Reproduce

edit a record

### Expected Output

update the record in the database

**Comment by luciocodeigniter** [comment]
```
protected $validationRules  = [
        'id'          => 'permit_empty',
		///...
```

**Comment by kenjis** [comment]
`LogicException` means your code has a bug, please fix it.

Generally speaking, the rule `permit_empty` only for id (placeholder) is not enough. 
It should check the format like `is_natural_no_zero` (and max length) of the value. 

Because `permit_empty` just permits any string or empty, and an attacker might be able to send string that can attack something.

**Comment by luciocodeigniter** [comment]
When using 'is_natural_no_zero' when creating a record, I cannot insert the record into the database precisely because the ID does not yet exist. That is, I will always have the message:
`[id] => The id field must only contain digits and must be greater than zero.`

How to solve this using the validations in the Model?

**Comment by kenjis** [comment]
Sorry, I mean `permit_empty|is_natural_no_zero`.

**Comment by luciocodeigniter** [comment]
Now it worked. Thanks!

**Comment by gosocial2** [comment]
When 'id' is not in allowed fields neither in the form, this error should not have occurred. permit_empty is rather sensible for auto incrementing primary keys and should be exempt from validation when not featured in a form.
Therefore, this is a CodeIgniter bug whcih you need to accept, own and fix.

It seems, the more we advocate the framework to bring in new adopters, the more you guys break existing functionality to drive them away to other platforms.

**Comment by kenjis** [comment]
This Exception is for fixing the most serious vulnerability https://github.com/codeigniter4/CodeIgniter4/security/advisories/GHSA-m6m8-6gq8-c9fj
If you think there is a bug, feel free to report or send a PR to fix.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/README.md
