### ISSUE TITLE
Bug: Routes with {locale} before the actual path are not loaded properly

### ISSUE THREAD

**Issue by SvetoslavStefanov** [codeigniter4/CodeIgniter4#7609]
### PHP Version

8.0

### CodeIgniter4 Version

4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL

### What happened?

I'm having a few sets of routes and localization on my website. The problem comes when I put {locale} before the actual route, because it reads everything there as a locale. Let me give an example:

### Steps to Reproduce

```php
$routes->useSupportedLocalesOnly(true);

$routes->get('userEmployee/edit/(:num)', [HomeController::class, 'index']); //route 1
$routes->get('{locale}/userEmployee/edit/(:num)', [HomeController::class, 'index']); //route 2

$routes->get('admin/userEmployee/edit/(:num)', [AdminHomeController::class, 'index']); //route 3
$routes->get('admin/{locale}/userEmployee/edit/(:num)', [AdminHomeController::class, 'index']); //route4
```

### Expected Output

In this case `route 3` wouldn't be accessible, because I'll get an error "language not supported" - it will try to match "admin" as a language in this case. I'm expecting to be able to access all my routes, if they're not duplicated. 

In this case `admin` is wrongly matched as a `{locale}`, which is causing all the issues here.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by kenjis** [comment]
> If I'm allowed to define this in Config/Routes.php, this means that I'm expected to be able to access that route, right?

No. 
Routes are registered in the routing table in the order in which they are defined.
If there are more than one matching route for a URI, the first matching route will be executed.

> Or at least to be presented with an error that this is not allowed route.

It is not implemented that way.
If you can implement that way, feel free to send a PR.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

**Comment by SvetoslavStefanov** [comment]
They're clearly different routes and they shouldn't be treated as the same in the first place.
They're treated as the same, which is the bug I'm reporting here.

The way `{locale}` is being matched is wrong. It should take into account that there are other routes, before proceeding forward in the "matching" process.

**Comment by kenjis** [comment]
They are different routes. 
But the `{local}` route matches first, because you define it first.
`{local}` is a wild card.
