### ISSUE TITLE
Why can't I use the 'unit_id' and 'service_id' placeholders in validations?

### ISSUE THREAD

**Issue by luciocodeigniter** [codeigniter4/CodeIgniter4#7625]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

5.7.33

### What happened?

Why can't I use the 'unit_id' and 'service_id' placeholders in validations?

Payload:

![PAYLOAD_ERROR](https://github.com/codeigniter4/CodeIgniter4/assets/100212803/42001cb7-037c-4d2d-a41f-a47591ad0d38)

Validations in the controller:

```
$request   = (array) $this->request->getJSON();

$rules = [
	'unit_id'       => 'required|is_not_unique[units.id,id,{unit_id}]', // just existing
	'service_id'    => 'required|is_not_unique[services.id,id,{service_id}]', // just existing

	'month'         => 'required',
	'day'           => 'required',
	'hour'          => 'required',
];

if (!$this->validateData($request, $rules)) {

	// status code 400 - bad request
	return $this->response->setStatusCode(400)->setJSON([
		'success' => false,
		'errors' => $this->validator->getErrors(),
	]);
}
```

### Steps to Reproduce

Sending request with fetch api

### Expected Output

validations occur normally

### Anything else?

Error caught in log

ERROR - 2023-06-26 15:56:23 --> [ERROR] The placeholder field cannot use placeholder: `unit_id `SYSTEMPATH\Validation\Validation.php:696

**Comment by luciocodeigniter** [comment]
Find out...

```
///...

$rules = [
	'unit_id'       => 'required|is_not_unique[units.id]', 
	'service_id'    => 'required|is_not_unique[services.id]', 

	'month'         => 'required',
	'day'           => 'required',
	'hour'          => 'required',
];
```

**Comment by kenjis** [comment]
To replace `{unit_id}`, we should validate the value before using it.
So Validation tries to check the `unit_id` value, but the validation rules contains `{unit_id}`.
So Validation raises the error.

**Comment by luciocodeigniter** [comment]
So the following is not correct?

```
///...

$rules = [
'unit_id' => 'required|is_not_unique[units.id]',
'service_id' => 'required|is_not_unique[services.id]',

'month' => 'required',
'day' => 'required',
'hour' => 'required',
];
```

**Comment by kenjis** [comment]
It is correct If you want:
- `unit_id` value must be in the database table
- `service_id` value must be in the database table

**Comment by luciocodeigniter** [comment]
They are. So I can assume the rules are correct?

**Comment by kenjis** [comment]
Yes.

And it is better to add format rules like `max_length`, `is_natural_no_zero` in all fields, so that Validation invalidates the invalid values (by attacks or something) earlier (e.g., before sending to the database).
