### ISSUE TITLE
Bug: Issue with using the url_to() function for named routes in grouped routes with (:alpha) placeholder as group name

### ISSUE THREAD

**Issue by iamsyh** [codeigniter4/CodeIgniter4#7651]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.6

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 8.0

### What happened?

I am experiencing an issue with the url_to() function in CodeIgniter 4 when trying to generate URLs for named routes that are defined within a route group using the (:alpha) placeholder.

Issue is when I try to use the url_to() function to generate a URL for a named route within a group that uses the (:alpha) placeholder, I get the foillowing error:

```
ErrorException

Undefined array key 0

SYSTEMPATH/Router/RouteCollection.php at line 1242

1235         if (count($params) > $placeholderCount) {
1236             $locale = $params[$placeholderCount];
1237         }
1238 
1239         // Build our resulting string, inserting the $params in
1240         // the appropriate places.
1241         foreach ($matches[0] as $index => $pattern) {
1242             if (! preg_match('#^' . $pattern . '$#u', $params[$index])) {
1243                 throw RouterException::forInvalidParameterType();
1244             }
1245 
1246             // Ensure that the param we're inserting matches
1247             // the expected param type.
1248             $pos  = strpos($from, $pattern);
1249             $from = substr_replace($from, $params[$index], $pos, strlen($pattern));
```

### Steps to Reproduce

1. Define a route group using the group() method with the (:alpha) placeholder.
2. Within this group, define a route with a name using the 'as' option.
3. Try to use the url_to() function to generate a URL for the named route.

**Config/Routes.php**
```php
$routes->group('(:alpha)', ['filter' => 'tenant'], static function ($routes) {
    $routes->match(['get'], 'login', 'Common\LoginController::loginView', ['as' => 'loginURL']);
    // other routes here
});
```

**Then in a view or in a controller, call:**

`echo url_to('loginURL');`

### Expected Output

The url_to() function should generate the correct URL for the named route within the group.

### Anything else?

The routes are being grouped based on a tenant or region identifier. The aim is to use the url_to() function to correctly generate URLs for these tenant-specific or region-specific routes.

**Comment by kenjis** [comment]
The error message is not helpful, but you miss an argument.

Try:
```php
echo url_to('loginURL', 'abc');
```

See https://codeigniter4.github.io/CodeIgniter4/helpers/url_helper.html#url_to

**Comment by iamsyh** [comment]
> The error message is not helpful, but you miss an argument.
> 
> Try:
> 
> ```
> echo url_to('loginURL', 'abc');
> ```
> 
> See https://codeigniter4.github.io/CodeIgniter4/helpers/url_helper.html#url_to

that worked, thank you!
