### ISSUE TITLE
contact form with database check submitted form data using AI, and as a result, data should not be saved into the database if form data is not related to the Complaint & Project Requirement.

### ISSUE THREAD

**Issue by Jkssm** [codeigniter4/CodeIgniter4#7682]
### PHP Version

7.4

### CodeIgniter4 Version

4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 5.6 

### What happened?

Contact form with database check submitted form data using AI, and as a result, data should not be saved into the database if form data is not related to the Complaint & Project Requirement.

### Steps to Reproduce

Contact form with database check submitted form data using AI, and as a result, data should not be saved into the database if form data is not related to the Complaint & Project Requirement.

### Expected Output

Contact form with database check submitted form data using AI, and as a result, data should not be saved into the database if form data is not related to the Complaint & Project Requirement.

### Anything else?

Contact form with database check submitted form data using AI, and as a result, data should not be saved into the database if form data is not related to the Complaint & Project Requirement.

**Comment by samsonasik** [comment]
it seems you reported issue to wrong repo on specific to your project, we need reproducible code for bug report.
