### ISSUE TITLE
Bug: [Model] setValidationRule() cannot use with ruleGroup

### ISSUE THREAD

**Issue by serge1978** [codeigniter4/CodeIgniter4#7689]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.6

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

MySQL 8.0.28

### What happened?

**Model::setValidationRule()** method doesn't work and leads to error for me:

Link for method in user guide:
https://codeigniter.com/user_guide/models/model.html?highlight=setvalidationrule#CodeIgniter\Model::setValidationRule

### Steps to Reproduce

I'm trying to use Model::setValidationRule() method inside of model.
For example:
```php
class ExampleModel extends Model
{

    protected $validationRules = 'rulesGroup'; // group is in .../app/Config/Validation.php

    public function doSomethingWithData(array $data): bool
    {
        $fieldRules = [
            'label' => 'FieldLabel',
            'rules' => ['required', 'max_length[5]'],
        ];

        $this->setValidationRule('fieldName', $fieldRules);

        // .... do some job

        return true; // or false if something is wrong
    }

}
```

### Expected Output

As I understood from the user guide I expected to override validation rules for the specified field dynamically, declared earlier in $validationRules property...

**Comment by kenjis** [comment]
What is the exact error message?

**Comment by kenjis** [comment]
@serge1978 Please try: #7691

**Comment by kenjis** [comment]
As a workaround:
- get the rules from the Config file
- change the rules array as you like
- set it with `setValidationRules()`

**Comment by serge1978** [comment]
> What is the exact error message?

```
 "message": "Cannot access offset of type string on string",
"file": "/usr/share/nginx/html/hot-guitars.ru/vendor/codeigniter4/framework/system/BaseModel.php",
```

**Comment by serge1978** [comment]
@kenjis , thanks!

**Comment by serge1978** [comment]
@kenjis, oh, forgot to ask...
Is this behavior currently a bug or a feature? Will setValidationRule() method work with ruleGroup in future release?
