### ISSUE TITLE
Bug: [Pager] Knocks down variables for View

### ISSUE THREAD

**Issue by neznaika0** [codeigniter4/CodeIgniter4#7703]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.6

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

I couldn't determine exactly why it works in one place and not in another. When calling $pager->links(), my parameters set inside the template disappear. I added a "_title_", but it disappears after the **Pager**. If you install it in the controller, everything is fine. BUT elsewhere, setting variables in the template works fine (even with **Pager**)

### Steps to Reproduce

```php
<?php
// init $model->paginate() in Controller
$this->setVar('title', 'New title');

echo $this->extend('_layout/backend');
?>

<?= $this->section('content') ?>
    <table class="table text-center">
        ...
    </table>
    <?php dd($this, 'first') ?>

    <?= $pager->links('default'); ?>

    <?php dd($this, 'second') ?>
<?= $this->endSection() ?>
```
In first dump N variables, in second N-1 vars (unset "title")

### Expected Output

I looked into the system Pager file. It calls **$this->view->setVar('pager', $pager)->render(...)** Probably this call interrupts the previous template code?

**Comment by kenjis** [comment]
Ref #6251

**Comment by kenjis** [comment]
@neznaika0 Thank you for reporting.

But what is the exact issue? 
Your code does not make sense. Why do you need *title* after `$pager->links('default')`.
Also your sample code is not executable.
It would be nice that you provide the minimum working code that reproduce your issue.
I mean, just copy and paste, and it reproduce this issue.

**Comment by neznaika0** [comment]
yes, the code is shown for general understanding so uses the model. The main problem is that $title disappears in the final rendering (backend template, <title>$title</title>). And this is only when Pager is called, without it (Pager) $title exists and is added in the extensible template.
Yes, right now $title is not needed in the template, it should be in the final HTML
The reason for this use is to transfer - the setting of variables inside the template instead of the controller
I am far from the PC, if possible I will post a demo

**Comment by kenjis** [comment]
The View is very complicated system, and I don't get it in details.
I don't get the difference among `$data`, `$tempData`, `$renderVars`, and `$saveData` yet.

But it seems `$this->tempData` is the variables that can be used in the view files:
https://github.com/codeigniter4/CodeIgniter4/blob/f8bdf2c85168517aa2eef34aab2b59afbe0c8b5e/system/View/View.php#L218-L230

And if we call the `render()`, it resets `$this->tempData`:
https://github.com/codeigniter4/CodeIgniter4/blob/f8bdf2c85168517aa2eef34aab2b59afbe0c8b5e/system/View/View.php#L280

**Comment by kenjis** [comment]
> The main problem is that $title disappears in the final rendering (backend template, <title>$title</title>).

It seems wrong that the Pager uses the shared View object.
`$pager->links()` calls `View::render()` that resets `$this->tempData`.

**Comment by neznaika0** [comment]
Yes, I looked a little. There are general data (from the controller or passed to render()), there are additional ones in the template.
I think this is the wrong behavior of Pager. It should not interrupt the flow of templates. 
do you have any suggestions?

**Comment by neznaika0** [comment]
Will cloning `View` or `\Config\Services::renderer(getShared:false) ` fix the situation?

**Comment by kenjis** [comment]
Yes, probably. Please try: #7758

**Comment by neznaika0** [comment]
[kenjis](https://github.com/kenjis), great. Fixed problem. I hope this will not affect in the future

**Comment by melroy89** [comment]
After my upgrade I got issues. I actually used two variables in my own pager PHP page.

Like so: `<button type="button" class="btn btn-dark" disabled><?= 'Page ' . $currentPage . ' of ' . $totalPages; ?></button>`

My controller would fill-in these variables:

```php
      $data = [
            ......,
            'currentPage' => $someModel->pager->getCurrentPage('group1'), // The current page number
            'totalPages'  => $someModel->pager->getPageCount('group1'),   // The total page count
      ];
```


This now leads to: `Undefined variable $currentPage`. How can I get this working again..? What do you advise here?

**Comment by kenjis** [comment]
```php
<button type="button" class="btn btn-dark" disabled><?= 'Page ' . $pager->getCurrentPage('group1') 
. ' of ' . $pager->getPageCount('group1'); ?></button>
```

**Comment by melroy89** [comment]
> ```
> $pager->getPageCount('group1')
> ```

Haha. No I already tried that of course..

This will give me another error:

```
Call to undefined method CodeIgniter\Pager\PagerRenderer::getCurrentPage()
```

**Comment by melroy89** [comment]
Thanks. I wasn't aware this method also has changed. 

It also seems to work without providing the group. Which I set via `->paginate()` as second argument. Is that parameter required? Since it seems it also fills in the `default` group I think.

**Comment by kenjis** [comment]
That is confusing, but `$someModel->pager` and `$pager` in the Pager template are different class instances.
The `$pager` in the template knows all about itself, so it does not take the `group` parameter.
