### ISSUE TITLE
CodeIgniter exception screen exposing all the .env files variables

### ISSUE THREAD

**Issue by DhPandya** [codeigniter4/CodeIgniter4#7704]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySQL 8.0

### What happened?

I was checking the development server and suddenly one exception throws from the code.
Now guess what! I am checking the server tab and found that all the information I mentioned in the .env file is exposed to that error screen, including the database username, Host, and Password.

![image](https://github.com/codeigniter4/CodeIgniter4/assets/46279781/8095693b-299a-419e-a978-c447701c6af6)

### Steps to Reproduce

Generate the error page of the codeigniterCodeigniter

### Expected Output

It should not expose the sensitive information on the error screen.

**Comment by kenjis** [comment]
Thank you for reporting.

This is not a bug, but a specification.
I sent PR #7706 to make it clear.

If you have information that would be problematic if leaked, we recommend setting the environment to `production`.

**Comment by kenjis** [comment]
If anyone knows of a specific way to remedy this issue, we would appreciate suggestions.

**Comment by DhPandya** [comment]
> ific way to remedy this issu

@kenjis 

Please review my pull request 
https://github.com/codeigniter4/CodeIgniter4/commit/d70af4bd14e5995ba37f74e2f276d1ab6a05ee96

**Comment by paulbalandan** [comment]
This should not be a problem if you are in `development`. You are developing your app so I would expect everything to be detailed. If this is the `production` environment, then this can be a bug.

**Comment by DhPandya** [comment]
> This should not be a problem if you are in `development`. You are developing your app so I would expect everything to be detailed. If this is the `production` environment, then this can be a bug.

@paulbalandan 
Agreed with you at some level. But when the website is hosted on the development server it is running in development mode and at the time if the variables are publically available then might be problematic.

**Comment by paulbalandan** [comment]
@DhPandya what do you mean development server? like `php spark serve`?

**Comment by DhPandya** [comment]
> If anyone knows of a specific way to remedy this issue, we would appreciate suggestions.

No on the hosting server.

**Comment by paulbalandan** [comment]
Hmm. My proposal for this to use a blacklist of keys that would be censored when displayed in the exception screen.

**Comment by DhPandya** [comment]
> Hmm. My proposal for this to use a blacklist of keys that would be censored when displayed in the exception screen.

Yes @paulbalandan Exactly. Regarding this I've created a one pull request https://github.com/codeigniter4/CodeIgniter4/pull/7707#issue-1804375894.

Please have a look into that.

**Comment by neznaika0** [comment]
The dump gives out the correct information - namely $_SERVER. Why $_ENV was combined in this array is unclear. Are there any good reasons?

**Comment by kenjis** [comment]
The Warning will be added in the documentation:
https://codeigniter4.github.io/CodeIgniter4/general/errors.html#error-reporting

**Comment by kenjis** [comment]
If you want to see all _SERVER variables, use `development`.
If you don't want, use `production` or create a custom environment like `staging` and customize the output as you like.

**Comment by im-machakata** [comment]
This was a good suggestion. I had pushed an update from github and it didn't work out as expected although it had passed tests and was working well on live development server. This forced me to turn development on in the env file and literally exposed all the env secrets which shouldn't have been exposed in the first place. There's no better way to debug when you have an error on a client's server, and you run the risk of exposing your **secrets**.
