### ISSUE TITLE
Bug: $sensitiveDataInTrace does not work

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#7708]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.6 and develop

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

n/a

### What happened?

```
1. APPPATH/Controllers/Home.php : 15   —  App\Controllers\Home->f ( arguments )                          

$obj     stdClass Object 
         (     
              [password] => ****************** 
         )

$array   Array 
         (     
              [password] => secret2 
         )
```

### Steps to Reproduce

```diff
--- a/app/Config/Exceptions.php
+++ b/app/Config/Exceptions.php
@@ -49,7 +49,7 @@ class Exceptions extends BaseConfig
      * In order to specify 2 levels, use "/" to separate.
      * ex. ['server', 'setup/password', 'secret_token']
      */
-    public array $sensitiveDataInTrace = [];
+    public array $sensitiveDataInTrace = ['password'];
 
     /**
      * --------------------------------------------------------------------------
```
```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        $obj = (object) [
            'password' => 'secret1',
        ];

        $array = ['password' => 'secret2'];

        $this->f($obj, $array);
    }

    private function f($obj, $array)
    {
        foo($obj, $array);
    }
}
```

### Expected Output

The array's `password` value should also be `******************`.

### Anything else?

If I set `$sensitiveDataInTrace = ['file']`, I get the following error:
> Fatal error: Uncaught TypeError: Cannot assign string to property Config\Cache::$file of type array in .../CodeIgniter4/system/Debug/Exceptions.php on line 325

Ref  #4550

**Comment by ping-yee** [comment]
![image](https://github.com/codeigniter4/CodeIgniter4/assets/65348108/c197104f-b50b-4b8f-a181-8a688215100c)

It even doesn't be handled in object in my side.
Can let me try to handle this issue? and It seems will be a breaking change.

**Comment by kenjis** [comment]
```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        $obj = (object) [
            'default' => ['password' => 'secret1'],
        ];

        $array = ['password' => 'secret2'];

        $this->f($obj, $array);
    }

    private function f($obj, $array)
    {
        foo($obj, $array);
    }
}
```
![Screenshot 2023-07-21 13 43 13](https://github.com/codeigniter4/CodeIgniter4/assets/87955/b82540cf-0fa8-4b99-ae2d-249cf5107414)

**Comment by kenjis** [comment]
@ping-yee What do you mean?
Try #7725
