### ISSUE TITLE
Bug: When both setAutoRoute and $autoRoutesImproved are set to true, automatic routing will fail

### ISSUE THREAD

**Issue by huayuprophet** [codeigniter4/CodeIgniter4#7738]
### PHP Version

7.4

### CodeIgniter4 Version

4.3.6

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

Mysql5.7

### What happened?

When both setAutoRoute and $autoRoutesImproved are set to true, automatic routing will fail.

### Steps to Reproduce

to set setAutoRoute and $autoRoutesImproved true
And write a demo:
![图片](https://github.com/codeigniter4/CodeIgniter4/assets/106079510/5947705b-58e6-487f-9653-fd67d16f21d5)

### Expected Output

404 page
![图片](https://github.com/codeigniter4/CodeIgniter4/assets/106079510/19bb15a6-8162-45c1-a271-e9760bf2d7a3)

**Comment by kenjis** [comment]
It seems you don't understand what **Auto Routing (Improved)** is.
It is a different routing system than Auto Routing (Legacy).

Please read the documentation.
https://codeigniter4.github.io/CodeIgniter4/incoming/controllers.html#let-s-try-it-hello-world
and https://codeigniter4.github.io/CodeIgniter4/changelogs/v4.2.0.html#v420-new-improved-auto-routing
