### ISSUE TITLE
Bug: Model cannot insertBatch when $useAutoIncrement is false

### ISSUE THREAD

**Issue by MaulanaMalikS** [codeigniter4/CodeIgniter4#7744]
### PHP Version

8.2

### CodeIgniter4 Version

v4.3.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

Model cannot insert using `insertBatch` when `$useAutoIncrement` is set to `false`.

It's exactly the same as this issue:
https://forum.codeigniter.com/showthread.php?tid=84733

But it occurs in `insertBatch`.

### Steps to Reproduce

1. Create a model, set `$useAutoIncrement` to `false`, and exclude `$primaryKey` from `$allowedFields` as mentioned in the [docs](https://codeigniter.com/user_guide/models/model.html#allowedfields).

2. Instantiate model, `$model = model(MyModel::class);`

3. Utilize the `$model->insertBatch($data);` method to insert data, including the primary key.

### Expected Output

The data should be inserted into the database.

### Anything else?

https://forum.codeigniter.com/showthread.php?tid=84733

**Comment by kenjis** [comment]
I've confirmed this bug.

> CodeIgniter\Database\Exceptions\DataException : There is no primary key defined when trying to make insertBatch.

```diff
--- a/tests/system/Models/InsertModelTest.php
+++ b/tests/system/Models/InsertModelTest.php
@@ -65,6 +65,26 @@ final class InsertModelTest extends LiveModelTestCase
         $this->seeInDatabase('job', ['name' => 'Cab Driver']);
     }
 
+    public function testInsertBatchUseAutoIncrementSetToFalse(): void
+    {
+        $insertData = [
+            [
+                'key'   => 'key1',
+                'value' => 'value1',
+            ],
+            [
+                'key'   => 'key2',
+                'value' => 'value2',
+            ],
+        ];
+
+        $this->createModel(WithoutAutoIncrementModel::class);
+        $this->model->insertBatch($insertData);
+
+        $this->seeInDatabase('without_auto_increment', ['key' => 'key1']);
+        $this->seeInDatabase('without_auto_increment', ['key' => 'key2']);
+    }
+
     public function testInsertBatchValidationFail(): void
     {
         $jobData = [
```

**Comment by kenjis** [comment]
@MaulanaMalikS I sent #7759. Try it if you can.

**Comment by MaulanaMalikS** [comment]
@kenjis, yes, I've tried it and it works!
