### ISSUE TITLE
Bug: service return type

### ISSUE THREAD

**Issue by Terrorboy** [codeigniter4/CodeIgniter4#7754]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### What happened?

```
function service(string $name, ...$params): ?object
{
    return Services::$name(...$params);
}
```
I don't know why you forced it to object and null.

just in case
(service('foo')->bar() === true)
There are cases where you receive it as a bool like
In some cases, there is no separate return due to single execution.

Should methods registered as services in the future always return object or null?

### Steps to Reproduce

```
class Services extends BaseService
{
        public static function login($getShared=true)
        {
                   ...
               return $is_login; // true or false
        }
}
```

### Expected Output

service(): Return value must be of type ?object, bool returned

**Comment by paulbalandan** [comment]
It should always return `object|null` but only enforced thru PHPDocs. `service()` and the Services class act like a factory or a container. It loads your desired service class. They are not the service class.

**Comment by paulbalandan** [comment]
In your case, you must instead create a Login class, do the logic there, then load the class thru Services::login. It would be something like
`service('login')->is_login`

**Comment by Terrorboy** [comment]
Has confirmed.
thank you
