### ISSUE TITLE
Bug: [Model] BaseModel not save entities from updateBatch() 

### ISSUE THREAD

**Issue by neznaika0** [codeigniter4/CodeIgniter4#7762]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

On run `$model->updateBatch($entities, 'id')` see:

```
mysqli_sql_exception #1064
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near...
```

### Steps to Reproduce

1. Create array with `Entity::class` objects
2. Run $model->updateBatch($entities, 'your_primary_key') (model for your Entity)
3. See Exception

### Expected Output

The update operation must be performed

### Anything else?

I have tested several options. Here $entities is an array of entities, $model is their model.

1. Directly saving
```php
$model->updateBatch($entities, 'id'); // Exception
```
2. Convert entities to raw array onlyChanged = **true**
```php
foreach ($entities as $entity) {
    $raw[] = $entity->toRawArray(true);
}
$model->updateBatch($raw, 'id'); // Exception
```
3. Convert entities to raw array onlyChanged = **false**
```php
foreach ($entities as $entity) {
    $raw[] = $entity->toRawArray(false);
}
$model->updateBatch($raw, 'id'); // OK
```
4. Temporarily changed the system BaseModel onlyChanged = **false**
```php
if (is_object($row) && ! $row instanceof stdClass) {
    $row = $this->objectToArray($row, false, true); // OK
}
```
https://github.com/codeigniter4/CodeIgniter4/blob/c56edf271765a63729f6731e4790b80fa1fc4598/system/BaseModel.php#L982C67-L982C67

**Comment by kenjis** [comment]
See `UpdateModelTest::testUpdateBatchWithEntity()`.  Entities work with `updateBatch()`.

How did you create the `$entities`?
It seems this is not a bug, if the entities do not have changed data.
Can you show the generated SQL statement?

**Comment by neznaika0** [comment]
Ok. I tested.
```
$model->updateBatch($entities, 'id');
```
1. **changed = true**, no changes (objects have not changed). SQL wrong criteries UNION ALL
```
 array:18 [▼
  0 => []
  1 => []
  2 => []
  3 => []
  4 => []
  5 => []
  6 => []
  7 => []
  8 => []
  9 => []
  10 => []
  11 => []
  12 => []
  13 => []
  14 => []
  15 => []
  16 => []
  17 => & []
]
---
UPDATE `settings`
    INNER JOIN (
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT  UNION ALL
    SELECT 
    ) `_u`
    ON `settings`.`id` = `_u`.`id`
    SET
```
2. **changed = true**, changed objects. SQL UNION ALL empty
```
 array:18 [▼
  0 => []
  1 => array:2 [▼
    "value" => "Created on CodeIgniter framework (edited)"
    "id" => 84
  ]
  2 => array:2 [▼
    "value" => "en"
    "id" => 85
  ]
  3 => []
  4 => []
  5 => []
  6 => []
  7 => []
  8 => []
  9 => []
  10 => []
  11 => []
  12 => []
  13 => []
  14 => []
  15 => []
  16 => []
  17 => & []
]
---
    UPDATE `settings`
    INNER JOIN (
    SELECT  UNION ALL
    SELECT 
    ) `_u`
    ON `settings`.`id` = `_u`.`id`
    SET
```
3. **changed = false,** objects toRawArray() always return the full array
```
array:18 [▼
  0 => array:4 [▶]
  1 => array:4 [▼
    "parameter" => "title"
    "value" => "Created on CodeIgniter framework (edited)"
    "description" => "Default title in HTML"
    "id" => 84
  ]
  2 => array:4 [▼
    "parameter" => "language"
    "value" => "en"
    "description" => "Default language"
    "id" => 85
  ]...
---
    UPDATE `settings`
    INNER JOIN (
    SELECT 'Folder with template theme' `description`, 83 `id`, 'theme' `parameter`, 'default' `value` UNION ALL
    SELECT 'Default title in HTML' `description`, 84 `id`, 'title' `parameter`, 'Created on CodeIgniter framework (edited)' `value` UNION ALL
    SELECT 'Default language' `description`, 85 `id`, 'language' `parameter`, 'en' `value` UNION ALL
    // many SELECT here
    ) `_u`
    ON `settings`.`id` = `_u`.`id`
    SET
    `settings`.`description` = `_u`.`description`,
    `settings`.`parameter` = `_u`.`parameter`,
    `settings`.`value` = `_u`.`value`
```

**Comment by neznaika0** [comment]
@kenjis , my Model
```
    protected $table = 'settings';
    protected $primaryKey = 'id';
    protected $allowedFields = [
        'parameter',
        'value',
        'description',
    ];
    protected $returnType = SettingsParameter::class;
```
My Entities have similar setters for properties. toRawArray() is not affected and has standard behavior
```
final class SettingsParameter extends Entity
{
    private ?int   $id;
    private string $parameter;
    private string $value;
    private ?string $description;

    public function setParameter(string $parameter)
    {
        $this->parameter = $this->attributes['parameter'] = $parameter;

        return $this;
    }
    // custom call fill() to correctly set the properties of the object. I wrote about such a problem
    public function setAttributes(array $data)
    {
        parent::setAttributes($data);
        $this->fill($data)->syncOriginal();

        return $this;
    }
```

**Comment by neznaika0** [comment]
My opinion is a mistake in the preparation of the test. You are not updating a part of the entity, but actually replacing it with a new one. Try to change the behavior to a more natural one, synchronize the attributes.

```
$entity2->id      = 4;
$entity2->name    = 'Jones Martin';
$entity2->country = 'India';
$entity2->deleted = 0;
$entity1->syncOriginal();
$entity1->country = 'China';

array(1) {
  [0]=>
  string(103) "UPDATE `user`
INNER JOIN (
SELECT 'China' , 1  UNION ALL
SELECT 
) `_u`
ON `user`.`id` = `_u`.`id`
SET
"
}
```

**Comment by kenjis** [comment]
Thank you for the detailed information.

It seems there is no consideration in `updateBatch()` for Entities with only changed data.
So now the `updateBatch()` supports only full data updates.

By the way, why do you need to use `updateBatch()` for Entities?
Why not use `update()` or `save()`?

**Comment by neznaika0** [comment]
In my opinion this is a better option than using a loop and updating each record. In one line code.
If there is an opportunity in the framework, then why not use it?
Can I find out if a fix will be released? If not, it is worth adding a note in the documentation about the restriction

**Comment by kenjis** [comment]
@codeigniter4/database-team 
It seems the current SQL statement for `updateBatch()` does not process the partial updates.
Changing the following `true` to `false` is the correct solution?
https://github.com/codeigniter4/CodeIgniter4/blob/c56edf271765a63729f6731e4790b80fa1fc4598/system/BaseModel.php#L982

**Comment by neznaika0** [comment]
I created my own version of the settings from the database. In fact, this is a collection of SettingsParameterEntity[]. I want to save it after the administrator changes it through the controller. There is a method for this:
```
    /**
     * @var SettingsParameter[]
     */
    private array $storage = [];

    /**
     * @param SettingsParameter[]
     */
    public function __construct(array $parameters = [])
    {
        foreach ($parameters as $parameter) {
            $this->storage[$parameter->getParameter()] = $parameter;
        }
    }

    public function storeWithModel(): bool
    {
        $model = new SettingsParameterModel();

        return $model->updateBatch(array_values($this->storage), 'id') === false ? false : true;
    }
```

**Comment by iRedds** [comment]
@neznaika0 Can you tell me what I'm missing in my example? Because everything works for me.
```php
$m = new MyModel(); // fields [id, type]
$es = [];
for ($i = 1; $i < 9; $i++) {
    $es[] = new MyEntity(['id' => $i, 'type' => rand(0, 1)]);
}
$m->updateBatch($es, 'id');
/**
      It works the same

      $es = $m->findAll();
      foreach ($es as $e) {
          $e->type = 1;
      }
      $m->updateBatch($es, 'id');
*/

// The entity was generated by the team and has not changed.
namespace App\Entities;

use CodeIgniter\Entity\Entity;

class MyEntity extends Entity
{
    protected $datamap = [];
    protected $dates   = ['created_at', 'updated_at', 'deleted_at'];
    protected $casts   = [];
}
```

**Comment by neznaika0** [comment]
Add more fields to make "changed" work.  But change only a part of them
```
$m = new MyModel(); // fields [id, type, username, job]
$es = $m->findAll();
foreach ($es as $e) {
    // not update fields job, username
    $e->type = 1;
}
$m->updateBatch($es, 'id');

// this Entity->original has all fields of the model. No problem
// All you need to catch is to get the saved entities and change some properties (not all)
$es[] = new MyEntity(['id' => 1, 'type' => rand(0, 1)]); // job, usermane is old
$es[] = new MyEntity(['id' => 2, 'job' => rand(0, 1)]); type, username is old
```

**Comment by iRedds** [comment]
@neznaika0 Thanks, now I understand.

@kenjis 
> It seems the current SQL statement for `updateBatch()` does not process the partial updates.
> Changing the following `true` to `false` is the correct solution?

This will work if the entity is taken from the database when all fields exist.
If the entity is new,
```php
$es[] = new MyEntity(['id' => 1, 'type' => rand(0, 1)]); // job, usermane is old
$es[] = new MyEntity(['id' => 2, 'job' => rand(0, 1)]); // type, username is old
```
it will be the same.

The first thing that comes to mind is
1. Remove data from the set that contains fewer fields than constraint+1
2. If in some array there is a field that is not in other arrays (and vice versa), then make a request to the database and fill in the missing data. 

Or, at the SQL level, make a subquery into the database for the missing field.
```sql
UPDATE `table`
    INNER JOIN (
    SELECT 'a' `a`, (SELECT b FROM table WHERE ...) `b`, 1 `id`   # b missing
    UNION ALL  
    SELECT (SELECT a FROM table WHERE ...) `a`, 'b' `b`, 2 `id`   # a missing
    ) `_u`
    ON `table`.`id` = `_u`.`id`
    SET
    `table`.`a` = `_u`.`a`,
    `table`.`b` = `_u`.`b`,
```

**Comment by kenjis** [comment]
@iRedds If you create a new entity instance by yourself, you are not updating it. It should be an insertion.
So I think the code is a misuse.

It is better to raise an error if constraint is not enough.
