### ISSUE TITLE
Bug: with form_input helper is incorrectly show strings with &  in input as &amp;

### ISSUE THREAD

**Issue by jozefrebjak** [codeigniter4/CodeIgniter4#7792]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MariaDB 10.2

### What happened?

I'm using `form_input` helper to work with HTML inputs. Sometimes I need to store strings containing for example special character `&`. With add form it's saved correctly in database, but if I want to show stored value in edit form, then value is automatically escaped with `parse_form_attributes` helper and `&` is then shown to the user like `&amp;`. 

### Steps to Reproduce

Use `form_input` helper to store some string for example `Father & Son` and then use `<?= set_value('foo', $foo->bar) ?>` in html value. 

### Expected Output

it should show in input `&` and not `&amp;`.

### Anything else?

How to deal with this ? If user is editing `Father & Son` then it's shown in html input as `Father &amp; Son`. After update of form it's saved to db as `Father &amp; Son` and then it's shown in form like `Father &amp;amp; Son`.

**Comment by datamweb** [comment]
How about the following?
```php
<?= set_value('foo', $foo->bar, false) ?>
```

**Comment by neznaika0** [comment]
https://codeigniter.com/user_guide/helpers/form_helper.html#set_value
html_escape flag set?

**Comment by kenjis** [comment]
Yes, this is not a bug. It is clearly documented.

> The second (optional) parameter allows you to set a default value for the form. The third (optional) parameter allows you to turn off HTML escaping of the value, in case you need to use this function in combination with i.e., [form_input()](https://codeigniter.com/user_guide/helpers/form_helper.html#form_input) and avoid double-escaping.
https://codeigniter.com/user_guide/helpers/form_helper.html#set_value
