### ISSUE TITLE
Bug: Mysql Migration

### ISSUE THREAD

**Issue by maneesh-007** [codeigniter4/CodeIgniter4#7810]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MySql  8.0

### What happened?

I tried to migrate using php spark migrate using mysql Database it throws the error 
[CodeIgniter\Database\Exceptions\DatabaseException]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

at SYSTEMPATH\Database\BaseConnection.php:646
but it is working fine with postgres

### Steps to Reproduce

1) make a migration
2) define all details
3) php spark migrate

### Expected Output

migration successful

**Comment by kenjis** [comment]
Check the SQL statement.

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
