### ISSUE TITLE
Bug: Unexpected behavior of has_cookie helper function.

### ISSUE THREAD

**Issue by yeasherarafath** [codeigniter4/CodeIgniter4#7813]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.7

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.27

### What happened?

Example of Issue:
I have created a cookie using JS 

```
var now = new Date();
var time = now.getTime()+(6*(60*60*1000));
var expireTime = time + (1000*(3600))*24;
now.setTime(expireTime);
document.cookie = "myCookie"+"=test; expires="+now.toUTCString()+";";
```

![image](https://github.com/codeigniter4/CodeIgniter4/assets/50262277/6227523d-d3d6-4a1a-84fd-2f9bcb3f82fc)

Then trying to access "myCookie"

```
helper('cookie');
// set_cookie('myCookie','true_CI',time()+5600);

echo "1. [has_cookie('myCookie')]: ".(!has_cookie('myCookie') ? "No Cookies For You Named 'myCookie'" : 'Here is your Cookie "'.get_cookie('myCookie').'"') . '<br>';

echo '2. [$_COOKIE["myCookie"]]: '.(!isset($_COOKIE['myCookie']) ? "No Cookies For You Named 'myCookie'" : 'Here is your Cookie "'.$_COOKIE['myCookie'].'"') . '<br>';
```
The output

![image](https://github.com/codeigniter4/CodeIgniter4/assets/50262277/fd5102d9-8967-42e8-8b6b-e42be18088f0)

But it should print 

1. [has_cookie('myCookie')]: Here is your Cookie "test"

### Steps to Reproduce

Create a cookie using JS 

```
var now = new Date();
var time = now.getTime()+(6*(60*60*1000));
var expireTime = time + (1000*(3600))*24;
now.setTime(expireTime);
document.cookie = "myCookie"+"=test; expires="+now.toUTCString()+";";
```

![image](https://github.com/codeigniter4/CodeIgniter4/assets/50262277/6227523d-d3d6-4a1a-84fd-2f9bcb3f82fc)

 Try to access "myCookie"

```
helper('cookie');
// set_cookie('myCookie','true_CI',time()+5600);

echo "1. [has_cookie('myCookie')]: ".(!has_cookie('myCookie') ? "No Cookies For You Named 'myCookie'" : 'Here is your Cookie "'.get_cookie('myCookie').'"') . '<br>';

echo '2. [$_COOKIE["myCookie"]]: '.(!isset($_COOKIE['myCookie']) ? "No Cookies For You Named 'myCookie'" : 'Here is your Cookie "'.$_COOKIE['myCookie'].'"') . '<br>';
```

### Expected Output

has_cookie('myCookie') should return true, because I already I have cookie named myCookie with value "test".

I had tested it by downloading fresh zip file from github.

**Comment by neznaika0** [comment]
Its no bug. The cookie you are checking is not contained in the request. They WILL BE sent in response. It's not the same as $_COOKIE
To check for real cookies, you can do `get_cookie('myCookie') ?? false`
