### ISSUE TITLE
Bug: For set_checkbox, when default is true the checkbox will become checked when redirected back with input.

### ISSUE THREAD

**Issue by WrestlingPotato** [codeigniter4/CodeIgniter4#7814]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

`<input type="checkbox" name="fruit" value="apple" <?= set_checkbox("fruit", "apple", true) ?>>`
The input is part of a user submitted form. 
When the view is generated, I want the checkbox to be checked by default. Then the user submits their form, the controller validates the information, then is redirected accordingly.
However, when the user is redirected back with input, 'fruit' is checked, even when the user unchecks it.

I suspect that this is because when 'fruit' is unchecked, 'fruit' is not added to $_POST, then when set_checkbox does not find an old value, which causes it to use the default value, which is checked. I think this because my CI_ENVIRONMENT is development, and I can see that _ci_old_input does not contain 'fruit'.

### Steps to Reproduce

have 
`<input type="checkbox" name="fruit" value="apple" <?= set_checkbox("fruit", "apple", true) ?>>`
in the view,

then 
`return redirect()->back()->withInput();`
in the controller, after the user submits the form

### Expected Output

Checkbox should be checked by default, then checked/unchecked according to user input when redirected back with input.

**Comment by kenjis** [comment]
Yes, `withInput()` stores POST values in the session, 
and there is no `fruit` data if you don't check anything.
Then `set_checkbox()` checks it because the default is `true`.

This behavior is from CI3, so maybe this is the spec?

**Comment by kenjis** [comment]
@WrestlingPotato If you could fix this issue, please send a PR.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/README.md

**Comment by kenjis** [comment]
Ah, CI3 does not have `withInput()`. So there is no problem!

The workaround is not to use the redirect.

**Comment by kenjis** [comment]
I found a bug in the documentation: #7816

**Comment by WrestlingPotato** [comment]
I'm just starting to learn CI4, so I don't know how to fix the issue, and wanted to bring attention to the issue. For now I just gave up on having the checkbox be checked by default.

**Comment by kenjis** [comment]
@WrestlingPotato No problem. I found how to fix. Try #7818
