### ISSUE TITLE
Bug: system\Cache\CacheInterface.php

### ISSUE THREAD

**Issue by iFreeshine** [codeigniter4/CodeIgniter4#7828]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.7

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### What happened?

system\Cache\CacheInterface.php        Missing method ： deleteMatching(string $pattern)

### Steps to Reproduce

none

### Expected Output

none

### Anything else?

none

**Comment by paulbalandan** [comment]
Yes, the interface does not have the method. But BaseHandler has it.

Closing as the discussion is in #4356

**Comment by kenjis** [comment]
If you want to fix this issue, send a PR to the next minor version branch, now `4.5`.
