### ISSUE TITLE
v4.3.8 release

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#7842]
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/admin/RELEASE.md

- [x] #7848
- [x] #7849

**Comment by kenjis** [comment]
It seems there is no epub userguide v4.3.8:
https://github.com/codeigniter4/userguide

There is no version in the commit message:
https://github.com/codeigniter4/userguide/commit/368723d53171b7e9e0e8e377eb1eea1eff8632f6
and `CodeIgniter.epub` was created.

Manually renamed for now.
https://github.com/codeigniter4/userguide/commit/9852f1c35d8371cffd64baffd873ddd2e4a607fb

**Comment by kenjis** [comment]
```
Run ./source/.github/scripts/deploy-userguide ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/userguide ${GITHUB_REF##*/}
  ./source/.github/scripts/deploy-userguide ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/userguide ${GITHUB_REF##*/}
  shell: /usr/bin/bash -e {0}
Preparing for version 
Merging files from /home/runner/work/CodeIgniter4/CodeIgniter4/source to /home/runner/work/CodeIgniter4/CodeIgniter4/userguide
error: pathspec 'master' did not match any file(s) known to git
Running Sphinx v4.3.2
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/5970889910/job/16199163159

The version number is missing.

Output:
```
Preparing for version 
Merging files from /home/runner/work/CodeIgniter4/CodeIgniter4/source to /home/runner/work/CodeIgniter4/CodeIgniter4/userguide
```
Shell script:
```
SOURCE=$1
TARGET=$2
RELEASE=$3
VERSION=`echo "$RELEASE" | cut -c 2-`

echo "Preparing for version $3"
echo "Merging files from $1 to $2"
```

Does anyone know why the script couldn't get the version number?

**Comment by paulbalandan** [comment]
`${GITHUB_REF##*/}` does not work anymore?

**Comment by kenjis** [comment]
No, when v4.4.0 was released, it worked.
https://github.com/codeigniter4/userguide

**Comment by paulbalandan** [comment]
But it was manually renamed, right?

**Comment by kenjis** [comment]
No, I manually renamed v4.3.8 epub. v4.4.0 epub is created automatically.
