### ISSUE TITLE
Bug: Latest 4.4.0

### ISSUE THREAD

**Issue by ALTITUDE-DEV-FR** [codeigniter4/CodeIgniter4#7859]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

After latest update 4.4.0

Fatal error: Uncaught Error: Undefined constant "CodeIgniter\ENVIRONMENT" in C:\wamp64\www\vendor\codeigniter4\framework\system\CodeIgniter.php on line 581

### Steps to Reproduce

Just composer Update (3.7.0 > 4.4.0)

### Expected Output

Fatal error: Uncaught Error: Undefined constant "CodeIgniter\ENVIRONMENT" in C:\wamp64\www\vendor\codeigniter4\framework\system\CodeIgniter.php on line 581

**Comment by samsonasik** [comment]
You may need to replace spark file

https://github.com/codeigniter4/CodeIgniter4/blob/94515959306c9678943b706cd03517f190c022f7/spark#L82

and various config, see changelog

https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/changelogs/v4.4.0.rst

**Comment by ddevsr** [comment]
I have another bug,

```
Uncaught Error: Class "Kint\Renderer\AbstractRenderer" not found in D:\Project\laragon\www\askred\app\Config\Kint.php on line 46
```
![image](https://github.com/codeigniter4/CodeIgniter4/assets/97607754/c802e9bc-3489-42a3-9c31-70638ad86711)

When install `kint-php/kint` to `require-dev`, appear other message

```
Uncaught Error: Call to undefined method Config\DocTypes::__set_state() in D:\Project\laragon\www\askred\writable\cache\FactoriesCache_config on line 681
```
![image](https://github.com/codeigniter4/CodeIgniter4/assets/97607754/4d883586-23f4-43d5-ae61-d5ba2a9bab7a)

**Comment by samsonasik** [comment]
I can't reproduce with fresh install appstarter, you may need to copy various files:

- env
- public/index.php
- spark
- also sync app/Config/*

**Comment by samsonasik** [comment]
see list of upgrade guide https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/installation/upgrade_440.rst

**Comment by samsonasik** [comment]
upgrade guide: https://codeigniter4.github.io/userguide/installation/upgrade_440.html

changelog: https://codeigniter4.github.io/userguide/changelogs/v4.4.0.html

**Comment by kenjis** [comment]
@ddevsr If you use Config Caching, read:
https://codeigniter4.github.io/CodeIgniter4/concepts/factories.html#prerequisite

**Comment by ALTITUDE-DEV-FR** [comment]
All are working now in my side, Good Job @kenjis best Update <3 next support 8.3 =)

**Comment by ddevsr** [comment]
@samsonasik @kenjis I cleared cache files, and refresh page its `OK`. and next refresh appear error.

I added `BaseConfig` in `app\Config\DocTypes` really done to me

```diff
--- a/app/Config/DocTypes.php
+++ b/app/Config/DocTypes.php
@@ -2,7 +2,9 @@

 namespace Config;

-class DocTypes
+use CodeIgniter\Config\BaseConfig;
+
+class DocTypes extends BaseConfig
```

**Comment by paulbalandan** [comment]
I think this is because `config(DocTypes::class)` is called even though it is not a config.

**Comment by ddevsr** [comment]
Yes, i called `html` helper in autoload helper `BaseController`

**Comment by kenjis** [comment]
Ah, yes, there are two `config(DocTypes::class)` in the `src/`.

Extending `BaseConfig` and using `config(DocTypes::class)` make very slow to load.
If it is possible, I would like to use `new DocTypes()`.
