### ISSUE TITLE
Bug: max_length STRLEN issues

### ISSUE THREAD

**Issue by Valkhan** [codeigniter4/CodeIgniter4#7888]
### PHP Version

8.0

### CodeIgniter4 Version

4.3.7

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySql 5.7

### What happened?

Using default validation rules with a string of 62 characters the validation does not trigger  false value with a rule set for max_length[60]

``` php 
<?php 
$data= ['receivers' => string 'XXXXXXXXX EUGÊNIA XXXXXXXX|XXXXXXXXX Eugênio XX XXXXXXXX XXX']; // (length=62)
```

validation rule:
```
[receivers] => permit_empty|max_length[60]
```

when I compare strlen with mb_strlen over the given value I get two different counts:
```
Array
(
    [strlen] => 62
    [mb_strlen] => 60
)
```

I see that the default method (vendor\codeigniter4\framework\system\Validation\Rules.php)  has this logic:

```php
 /**
     * Returns true if $str is $val or fewer characters in length.
     */
    public function max_length(?string $str, string $val): bool
    {
        return is_numeric($val) && $val >= mb_strlen($str ?? '');
    }
```

### Steps to Reproduce

1. Create a model and add a validation rule for max_length of 60
2. use this value to test: "XXXXXXXXX EUGÊNIA XXXXXXXX|XXXXXXXXX Eugênio XX XXXXXXXX XXX"
3. it should return false as it has over 60 characters

### Expected Output

Validation Returns false

### Anything else?

Since the validation rules mostly result in storing data in the database, the difference between count of mb_strlen and strlen becomes a silent error.

I would advise to keep strlen as default, or give another option to have 2 max_length options:

max_length = uses strlen
max_length_mb = uses mb_strlen

**Comment by kenjis** [comment]
Why do you think the string has 62 characters?

```
XXXXXXXXX EUGÊNIA XXXXXXXX|XXXXXXXXX Eugênio XX XXXXXXXX XXX
123456789012345678901234567890123456789012345678901234567890
         10        20        30        40        50        60      
```

Changing the behavior of `max_length` is a breaking change.
I recommend you create your own validation rule to check byte length.

**Comment by Valkhan** [comment]
Because var dump results at 62 chars, my code editor has 62 positions but due to some special chars like ê the length is misleading 

Em 31 de ago. de 2023 21:43, em 21:43, kenjis ***@***.***> escreveu:

**Comment by visserrobin** [comment]
with strlen() the character Ê is taking two characters, therefor the character count is 62, rather than 60. As the original string is actually exactly 60 characters, mb_strlen() looks to be correct to me.....

```
$myString = 'XXXXXXXXX EUGÊNIA XXXXXXXX|XXXXXXXXX Eugênio XX XXXXXXXX XXX';
echo '<mb_strlen>'.mb_strlen($myString, 'UTF8').'<br>';
echo '<strlen>'.strlen($myString).'<br>';
for($x=0;$x<strlen($myString);$x++)
{
    echo substr($myString, $x, 1). '<BR>';
}
```

**Comment by kenjis** [comment]
Sorry, but you seems to misunderstand what is a character and byte.
"Ê" is one character, not two characters.
"あ" is one character, not three characters.

Probably you need the `max_byte` rule.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by Valkhan** [comment]
Thank you both for taking time to look into it, but as I canno disclose the actual data that my app received from an API that caused all that, and the problem that is happening with the count difference that cannot be reproduced by "copy past", perhaps I was receiving some invisible chars as well.

My solution was to remove all special chars like: "Ê" to "E" and strip anything else that wasn't alphanum, and to add max_length_bytes custom rule.

Special thanks to @visserrobin explanation, it didn't solve my problem, but got me on the right track.
