### ISSUE TITLE
Autoload module class from db.

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#7893]
Hello,
Autoload module class  Dynamically From db or from any sources should be nice without adding it manually to the autoload.php file. I try doing that but it's not working saying class not found

**Comment by kenjis** [comment]
What is Jello?

**Comment by ChibuezeAgwuDennis** [comment]
> What is Jello?

Sorry that is Hello,

**Comment by kenjis** [comment]
I cannot imagine use cases.
Extend the Autoloader.

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by cijagani** [comment]
@ChibuezeAgwuDennis I think this can be done by Registrar.php
You can implement it your own project.

**Comment by kenjis** [comment]
The Registrar is a feature by `BaseConfig`.
`Config\Autoload` is one of special config files that does not extend `BaseConfig`.
So Registrar does not work for `Config\Autoload`.

**Comment by cijagani** [comment]
> The Registrar is a feature by `BaseConfig`. `Config\Autoload` is one of special config files that does not extend `BaseConfig`. So Registrar does not work for `Config\Autoload`.

https://github.com/CorbitalTechnologies/ci4-starterkit/blob/master/app/Config/Registrar.php

**Comment by ChibuezeAgwuDennis** [comment]
@cijagani thanks i am checking it. This is what i was expecting with example
