### ISSUE TITLE
filter not working

### ISSUE THREAD

**Issue by hinditutorpoint** [codeigniter4/CodeIgniter4#7909]
Hi am facing a issue please guide me my project in ci:4.4.0
https://forum.codeigniter.com/showthread.php?tid=88433

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
