### ISSUE TITLE
Dev: Model always instantiates Validation even if not used

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#7935]
See https://forum.codeigniter.com/showthread.php?tid=88392&pid=412412#pid412412

**Comment by neznaika0** [comment]
The fix has been released, should I close the issue?

**Comment by kenjis** [comment]
No. 4.5 is not released.

**Comment by kenjis** [comment]
Close this because there are too many Issues.

This will be fixed in v4.5.0.
