### ISSUE TITLE
Bug: Changing env file won't take effect

### ISSUE THREAD

**Issue by mhmmdtech** [codeigniter4/CodeIgniter4#7979]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.2

### What happened?

I cloned codeigniter and changed the environment settings to fit the development environment but these changes are not applied.

### Steps to Reproduce

Clone CodeIgniter Change the environment settings, for example, set CI ENVIRONMENT on development Then run the project No changes have been made

### Expected Output

Making changes to the env file as explained in the documentation should affect the development environment

### Anything else?

I think this is a tiny problem and I can fix it.

**Comment by kenjis** [comment]
See 
- https://codeigniter4.github.io/CodeIgniter4/installation/running.html#set-to-development-mode
- https://codeigniter4.github.io/CodeIgniter4/general/configuration.html#dotenv-file
