### ISSUE TITLE
Bug: Should international characters be considered Alpha numeric?

### ISSUE THREAD

**Issue by Ukuser36** [codeigniter4/CodeIgniter4#7983]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.6

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

The validation library currently returns FALSE if accented characters are provided such as in the word Café. Should this not be considered a valid alpha numeric string? Whilst this was tested in 4.3.6 I don't believe the code in 4.4.1 is any different.

### Steps to Reproduce

```
$validation = \Config\Services::validation();
echo $validation->check('Café','alpha') ? 1 : 0;
```

### Expected Output

1

**Comment by neznaika0** [comment]
https://github.com/codeigniter4/CodeIgniter4/blob/da0bddf7cad675872a21a61823faf1a421fb3936/system/Validation/FormatRules.php#L28
Only ascii symbols a-Z allowed

**Comment by kenjis** [comment]
I also think the rule should pass only `[a-zA-Z]+`.
