### ISSUE TITLE
Bug in documentation: use statement missing.

### ISSUE THREAD

**Issue by rhsboss** [codeigniter4/CodeIgniter4#7991]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

 A 404 error was displayed after completing the beginner tutorial on the codeigniter.com user guide.
https://codeigniter.com/user_guide/tutorial/static_pages.html

### Steps to Reproduce

- Install CodeIgniter 4.4.1 via composer
- create 'Pages' controller and all other pages as  stated in the  user guide: https://codeigniter.com/user_guide/tutorial/static_pages.html
- run php spark serve
- 

### Expected Output

The newly created  'home' and 'about' pages should be displayed as directed in the user_guide.

### Anything else?

The solution it found was to add the following line after "use CodeIgniter\Router\RouteCollection;" at the top inside the 
"config routes.php"

" use App\Controllers\Pages; "

**Comment by kenjis** [comment]
It is described.
![Screenshot 2023-09-29 5 46 55](https://github.com/codeigniter4/CodeIgniter4/assets/87955/f584db47-4472-4d51-baa0-16c40fcc043a)
https://codeigniter.com/user_guide/tutorial/static_pages.html#setting-routing-rules

**Comment by kenjis** [comment]
If you find a bug in the docs, feel free to report it.
