### ISSUE TITLE
Bug: ControllerTestTrait::execute() return json body twice in response

### ISSUE THREAD

**Issue by alexxbout** [codeigniter4/CodeIgniter4#7996]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL 8

### What happened?

When we try to run the controller tests and look at the body responses, we get a duplicate response.
I'd like to point out that there are no duplicates in the responses when they are called in postman, and that the result is in JSON.

The error appears because of this code in the execute function:
```php
// Check for output to set or prepend
// @see \CodeIgniter\CodeIgniter::gatherOutput()
...
if (is_string($output)) {
    if (is_string($response->getBody())) {
        $response->setBody($output . $response->getBody());
    } else {
        $response->setBody($output);
    }
}
...
```

### Steps to Reproduce

Create a test class like this one:

```php
<?php

use App\Controllers\Home;
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\ControllerTestTrait;
use CodeIgniter\Test\DatabaseTestTrait;

use function PHPUnit\Framework\assertTrue;

class TestControllerSales extends CIUnitTestCase {
    use ControllerTestTrait;
    use DatabaseTestTrait;

    public function testHome() {
        $result = $this
            ->controller(Home::class)
            ->execute("index");

        assertTrue($result->isOK());

        log_message("debug", $result->getJSON());
    }
}
```

### Expected Output

It should display the response only once.

**Comment by kenjis** [comment]
> I'd like to point out that there are no duplicates in the responses when they are called in postman, and that the result is in JSON.

Thank you, but I don't know where the code is, because you did not write the file name.

**Comment by kenjis** [comment]
Cannot reproduce. I got `string (22) "{
    "result": "OK"
}"`.

```php
<?php

namespace App\Controllers;

use CodeIgniter\HTTP\Response;

class Home extends BaseController
{
    public function index(): Response
    {
        $data = ['result' => 'OK'];

        return $this->response->setJSON($data);
    }
}
```

```php
<?php

use App\Controllers\Home;
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\ControllerTestTrait;
use CodeIgniter\Test\DatabaseTestTrait;

use function PHPUnit\Framework\assertTrue;

/**
 * @internal
 */
final class TestControllerSales extends CIUnitTestCase
{
    use ControllerTestTrait;
    use DatabaseTestTrait;

    public function testHome()
    {
        $result = $this
            ->controller(Home::class)
            ->execute('index');

        assertTrue($result->isOK());

        dd($result->getJSON());
    }
}
```

**Comment by alexxbout** [comment]
Okay, I found the problem. I was forgetting to return in my controller methods and I was calling the send method which was not useful and which caused the duplication. Thanks for your help.
