### ISSUE TITLE
Bug:  404 error when completing the "Create News Items" tutorial in the user guide

### ISSUE THREAD

**Issue by rhsboss** [codeigniter4/CodeIgniter4#8000]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

10.4.22-MariaDB

### What happened?

Followed the tutorial in user_guide and  got a "404" page not found  exception when the URI: /news/create

->  https://codeigniter.com/user_guide/tutorial/create_news_items.html

### Steps to Reproduce

Follow the steps in the user guide: https://codeigniter.com/user_guide/tutorial/create_news_items.html

### Expected Output

A form with the  following: 
- "textbox" for the news item "title"
-  "textarea" for the news item  "text" (details of the news item)
-  a "create news item" button  to submit the form

### Anything else?

Solution change the  URI 
From: http://localhost:8080/news/create
To: http://localhost:8080/news/new

**Comment by sammyskills** [comment]
Thank you for reporting. 

I sent a PR #8001.

**Comment by kenjis** [comment]
Thank you for reporting.

It was fixed in `develop` branch.
See https://codeigniter4.github.io/CodeIgniter4/tutorial/create_news_items.html#create-a-news-item
