### ISSUE TITLE
Bug: CI returns 200 OK even though the route does not exist

### ISSUE THREAD

**Issue by xonipatino** [codeigniter4/CodeIgniter4#8009]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Codeigniter 4.4.1 responds with code **200 OK** when a Fetch request is made even if the route does not exist.

### Steps to Reproduce

1. These are my defined routes.

<img width="600" alt="image" src="https://github.com/codeigniter4/CodeIgniter4/assets/36271268/65e61c8b-f88f-4570-af42-2b14a4bfab02">

2. In the browser, modify the 'action' attribute in the form for the '**usuarios/nuevo**' route, placing it as '**usuarios/nuevoss**', _POST_ method.

<img width="575" alt="image" src="https://github.com/codeigniter4/CodeIgniter4/assets/36271268/c360d76c-cda1-4db2-acfc-7c51522f7119">

3. The request is sent and the response was 200 OK.

<img width="485" alt="image" src="https://github.com/codeigniter4/CodeIgniter4/assets/36271268/35efd900-f058-4697-9749-edaaa2510eba">

4. And upon reviewing the response content it was the following.

```
{
    "title": "CodeIgniter\\Exceptions\\PageNotFoundException",
    "type": "CodeIgniter\\Exceptions\\PageNotFoundException",
    "code": 404,
    "message": "Can't find a route for 'post: usuarios/nuevoss'.",
    "file": "C:\\Users\\xonip\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
    "line": 966,
    "trace": [
        {
            "file": "C:\\Users\\xonip\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 966,
            "function": "forPageNotFound",
            "class": "CodeIgniter\\Exceptions\\PageNotFoundException",
            "type": "::"
        },
        {
            "file": "C:\\Users\\xonip\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 362,
            "function": "display404errors",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "C:\\Users\\xonip\\www\\local_html\\macc\\public\\index.php",
            "line": 79,
            "function": "run",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "C:\\Users\\xonip\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\Commands\\Server\\rewrite.php",
            "line": 47,
            "args": [
                "C:\\Users\\xonip\\www\\local_html\\macc\\public\\index.php"
            ],
            "function": "require_once"
        }
    ]
}
```

### Expected Output

The response code that CI should send is 404.

![image](https://github.com/codeigniter4/CodeIgniter4/assets/36271268/3eed415b-476d-4c63-9be2-b087a740e1ca)

since the route '**usuarios/nuevoss**' does not exist in the route declarations.

**Comment by kenjis** [comment]
Please try this patch:
```diff
--- a/system/CodeIgniter.php
+++ b/system/CodeIgniter.php
@@ -979,8 +979,7 @@ class CodeIgniter
         // Display 404 Errors
         $this->response->setStatusCode($e->getCode());
 
-        echo $this->outputBufferingEnd();
-        flush();
+        $this->outputBufferingEnd();
 
         // Throws new PageNotFoundException and remove exception message on production.
         throw PageNotFoundException::forPageNotFound(
```

**Comment by xonipatino** [comment]
Hello @kenjis, bug solved, thank you very much!

**Comment by ddevsr** [comment]
This issue will be close after PR merged
