### ISSUE TITLE
Bug: Adding a primary key to an existing table not working

### ISSUE THREAD

**Issue by priitperna** [codeigniter4/CodeIgniter4#8019]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySql 8

### What happened?

When trying to add a primary key to an existing table, it does not work:
```php
$this->forge->addPrimaryKey('id', 'pk_actions');
$this->forge->processIndexes('actions');
```

### Steps to Reproduce

Create a migration to add a primary key to an existing table with the following rows:
```php
$this->forge->addPrimaryKey('id', 'pk_actions');
$this->forge->processIndexes('actions');
```

### Expected Output

Primary key should be added.

### Anything else?

The problem seems to lie in the `processIndexes()` function as it only processes primary keys when a non primary key is added:
```php
        if (! empty($this->keys)) {
            $sqls = $this->_processIndexes($this->db->DBPrefix . $table, true);

            $pk = $this->_processPrimaryKeys($table, true);

            if ($pk !== '') {
                $sqls[] = $pk;
            }
        }
```

**Comment by kenjis** [comment]
Thank you for reporting. Try #8031
