### ISSUE TITLE
connect to remote database server

### ISSUE THREAD

**Issue by yapeng-wyp** [codeigniter4/CodeIgniter4#8023]
### PHP Version

8.0

### CodeIgniter4 Version

4.4.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

Mysql5.6

### What happened?

I want connect other database [remote] . but :

Error connecting to the database: mysqli_sql_exception: Connection refused
Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused
Unable to connect to the database.
Main connection [MySQLi]: Connection refused

### Steps to Reproduce

I try edit database config array like this 
```php
$met_conf = [
            'hostname' => 'example.com',
            'username' => 'example',
            'password' => 'example&123distant',
            'database' => 'example',
            'DBDriver' => 'MySQLi',
            'DBPrefix' => '',
            'pConnect' => false,
            'DBDebug' => true,
            'charset' => 'utf8',
            'DBCollat' => 'utf8_general_ci',
            'swapPre' => '',
            'encrypt' => false,
            'compress' => false,
            'strictOn' => false,
            'port' => 3306,
            'numberNative' => false,
        ];
```

because this conection always need  but this user only have "select" Permissions. so I create a function belowed  common.php
to connect this database. but always return error. and I connect this database successfully  on the terminal

### Expected Output

nothing

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by yapeng-wyp** [comment]
> We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

Posted but not resolved.

**Comment by kenjis** [comment]
If you can connect to the database server with plain PHP code, it is surely a bug in CodeIgniter.
