### ISSUE TITLE
Event Point `pre_system` and `post_system` are different from the docs

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#8049]
Are these bugs or not?

https://codeigniter4.github.io/CodeIgniter4/extending/events.html#event-points
- `pre_system` Called **very early** during system execution. **Only the benchmark and events class have been loaded** at this point. No routing or other processes have happened.
- `post_system` Called **after the final rendered page is sent to the browser**, at the end of system execution after the finalized data is sent to the browser.

**Comment by kenjis** [comment]
Is the CI4 documentation just out of date?
http://codeigniter.com/userguide3/general/hooks.html#hook-points

Why are `pre_controller`, `post_controller`, `display_override`, and `cache_override` missing in CI4?

**Comment by MGatner** [comment]
I think just inaccurate descriptions. I wouldn't change the current behavior.

**Comment by kenjis** [comment]
Okay, I will fix as a bug in the docs.

**Comment by kenjis** [comment]
I sent a PR #8055.
