### ISSUE TITLE
Bug: [DebugBar] after switch light and back to dark

### ISSUE THREAD

**Issue by ddevsr** [codeigniter4/CodeIgniter4#8064]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

x

### What happened?

https://github.com/codeigniter4/CodeIgniter4/pull/8063#issuecomment-1771967860

Another bug after switch to light and back again dark will change `timeline-parent-open` to dark

![image](https://github.com/codeigniter4/CodeIgniter4/assets/97607754/667608fb-66ac-45fd-9d14-04644b68cd55)

### Steps to Reproduce

Open your debug bar in dark

### Expected Output

![image](https://github.com/codeigniter4/CodeIgniter4/assets/97607754/95080b92-caec-48f6-8ad2-e4bbd4df03b7)

**Comment by kenjis** [comment]
Reverting #7907 seems to solve the issue.
But I approved the PR, so it was okay at that time...

```diff
--- a/admin/css/debug-toolbar/_theme-dark.scss
+++ b/admin/css/debug-toolbar/_theme-dark.scss
@@ -150,10 +150,6 @@
         .timer {
             background-color: $g-orange;
         }
-
-        .timeline-parent-open td {
-            color: $t-dark;
-        }
     }
 }
```
![Screenshot 2023-10-21 20 52 03](https://github.com/codeigniter4/CodeIgniter4/assets/87955/b162b0d1-0097-4d51-a33b-944a79e83174)

**Comment by kenjis** [comment]
Reverting #7907 and I use Edge, I was able to reproduce the issue.
![Screenshot 2023-10-21 21 09 04](https://github.com/codeigniter4/CodeIgniter4/assets/87955/f9c40067-7c6b-450f-8358-92aa01416164)
But after switching to light mode and dark mode again, the issue was disappeared.
I cannot reproduce it now.

**Comment by sfadschm** [comment]
I feel switching the light/dark mode should not affect styles, but rather toggle them, or should it?
Is there some JS running on the mode change which alters the DOM elements ? Otherwise it does not make sense to me that the error only  occurs on switching back and forth.

**Comment by kenjis** [comment]
I sent PR #8125
