### ISSUE TITLE
Bug: Endless Processes trace ENOENT (No such file or directory) 

### ISSUE THREAD

**Issue by mettleshade** [codeigniter4/CodeIgniter4#8082]
### PHP Version

8.0

### CodeIgniter4 Version

latest

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MariaDB 10.6

### What happened?

Hello friends, the process of searching for missing files in my project is ongoing and doesn't stop. I have updated Composer, but the issue remains unresolved.

### Steps to Reproduce

When I enter the command "strace -tt -T -p pid_id" via SSH, I can see the errors.

### Expected Output

bug fix.

### Anything else?

![Screenshot_1](https://github.com/codeigniter4/CodeIgniter4/assets/51230161/8fcb40fa-19d1-46cf-8774-a984042f2bf9)

**Comment by kenjis** [comment]
Cannot reproduce.

**Comment by mettleshade** [comment]
It appears to be happening when the website's traffic is increasing. Currently, all processors are at 100%.

> Cannot reproduce.

**Comment by mettleshade** [comment]
> Ah, it is probably not a bug.
> 
> If you write code like `helper('foo')`, CI4 searches for the helper file `foo_helper.php` in all namespaces by default.
> 
> > Helpers will be automatically discovered within defined namespaces when using the helper() function, as long as it is within the namespaces Helpers directory:
> > https://codeigniter4.github.io/CodeIgniter4/general/modules.html#helpers
> 
> Specify Composer packages to search: https://codeigniter4.github.io/CodeIgniter4/general/modules.html#specify-composer-packages or if you want to load single helper file, specify the _namespace_: https://codeigniter4.github.io/CodeIgniter4/general/helpers.html#loading-from-non-standard-locations

Thank you! Can we specify exact locations for our own helpers in the system, for example: app/Helpers/test_helper.php? I couldn't find it in the documentation.

**Comment by mettleshade** [comment]
After uploading the file, does keep search!
![Screenshot_2](https://github.com/codeigniter4/CodeIgniter4/assets/51230161/c7565bbf-9684-4a80-9a20-c7a2108794f1)


**Does it upload the files again every time the user enters the site?**

**Comment by kenjis** [comment]
@mettleshade What did you upload? and what do you want?
It seems scanning for unrelated composer package namespaces is gone.

**Comment by kenjis** [comment]
> Can we specify exact locations for our own helpers in the system, for example: app/Helpers/test_helper.php?

```php
helper('App\test');
// or
helper('App\Helpers\test');
```

But the following would be faster.
```php
require APPPATH . 'Helpers/test_helper.php';
```

**Comment by mettleshade** [comment]
Thank you. I have disabled Composer Packages and Auto-Discovery, but there hasn't been a significant improvement in performance. I'm considering making performance-enhancing changes, and if I do, I'll let you know.

**Comment by kenjis** [comment]
Thank you for the info. Checking for non-existent helpers, etc. is useless, but does not seem to have a significant impact on performance.

It seems your server is just busy because of huge traffic.
Examine the bottleneck and eliminate it.
