### ISSUE TITLE
Bug: Exception view appears in production mode

### ISSUE THREAD

**Issue by jrdmellow** [codeigniter4/CodeIgniter4#8092]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

Exceptions encountered in an environment with `CI_ENVIRONMENT` set to `production` and php's `error_reporting` disabled (ie. `Off`, from the default `php.ini-production`) will show the `errors\html\error_exception` view instead of `errors\html\production`.

### Steps to Reproduce

- Install CI4 via composer.
- Ensure `CI_ENVIRONMENT` is set to `production` and `error_reporting` is `Off` or equivalent.
- Alter `App\Controllers\Home.php` to cause an exception/parser error
- Access the website from a browser.

### Expected Output

CI should fall back to the `errors\html\production` view when an exception is encountered in a production environment.

### Anything else?

It appears the issue comes from the `app\Config\Boot\production.php` defaults;

```
ini_set('display_errors', '0');
```

Debugging `ExceptionHandler.php, determineView` reveals that the `str_ireplace`  results in a string containing `0` (zero) as expected, but then erroneously passes the condition `str_ireplace(...) !== '')`.

Altering `app\Config\Boot\production.php` to use 'Off' or one of the other expected values leads to the proper behaviour, but a value of 0 should be handled properly.

**Comment by jrdmellow** [comment]
Why was this closed and edited without feedback?
Was there something wrong with this report? Not considered a bug?

**Comment by kenjis** [comment]
Please do not make public any uncovered flaws.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/SECURITY.md

**Comment by jrdmellow** [comment]
Understood, I see how this would be considered a security issue.
Thank you for the feedback.

**Comment by kenjis** [comment]
We are preparing the fix.
