### ISSUE TITLE
Bug: [DebugBar] `HotReload` causes 500 error

### ISSUE THREAD

**Issue by neznaika0** [codeigniter4/CodeIgniter4#8093]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MariaDB 10

### What happened?

See forum [thread-88719](https://forum.codeigniter.com/showthread.php?tid=88719) 
I observed this behavior in myself, so I decided to open a issue.
Feature breaks (500 error) or refreshes pages for a long time.
Browser: Yandex (Chromium)

Unfortunately, I can't say more yet - only on a smartphone.

### Steps to Reproduce

Run server and enable HotReload in dev toolbar.

### Expected Output

Normal page refresh with minimal speed delay

**Comment by michalsn** [comment]
@neznaika0  Please check #8112 when you have time.

**Comment by kenjis** [comment]
We need more detailed "Steps to Reproduce".

**Comment by neznaika0** [comment]
I tested it again. I think this is because of the **built-in server** - it is not configured to work multithreaded.
The `hot-reload` event completely takes up the process, it freezes (waiting for the page to refresh).

On the server with **apache2** It works perfectly.

**Comment by kenjis** [comment]
If you use macOS or Linux, you can run it with multi-threads.
```
PHP_CLI_SERVER_WORKERS=4 php spark serve
```

**Comment by neznaika0** [comment]
I configure vhost. CLI server for fast tests.
