### ISSUE TITLE
Bug: Cannot declare class Kint\Kint

### ISSUE THREAD

**Issue by pntrivedy** [codeigniter4/CodeIgniter4#8159]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL

### What happened?

I updated packages using 'composer update' faced this error. 

Cannot declare class Kint\Kint, because the name is already in use

APPPATH/Config/Kint.php at line 41
```php
namespace Kint;

use InvalidArgumentException;
use Kint\Parser\ConstructablePluginInterface;
use Kint\Parser\Parser;
use Kint\Parser\PluginInterface;
use Kint\Renderer\RendererInterface;
use Kint\Renderer\TextRenderer;
use Kint\Zval\Value;

/**
 * @psalm-consistent-constructor
 */
class Kint implements FacadeInterface
{
...
```

When I change env from development to production I face 404 error on route that was working fine previously.

### Steps to Reproduce

Nil

### Expected Output

Working app

**Comment by kenjis** [comment]
From what version did you upgrade CI4?
And did you follow all the upgrading guides?
https://codeigniter4.github.io/CodeIgniter4/installation/upgrading.html

**Comment by pntrivedy** [comment]
@kenjis : From 4.1.8

@paulbalandan : Yes namespace is Kint. Does App/Config/ have Kint.php by default?

**Comment by paulbalandan** [comment]
Why are you using Kint as your namespace?

**Comment by kenjis** [comment]
@pntrivedy I cannot reproduce the error.
I've installed v4.1.8 and upgraded to v4.4.3.
See https://github.com/kenjis/ci418to433/commits/main

**Comment by paulbalandan** [comment]
@pntrivedy Do not replace `app/Config/Kint.php` with the one inside `system/ThirdParty/Kint/Kint.php`! They are different classes.

**Comment by kenjis** [comment]
`app/Config/Kint.php` is a Config class for CI4.
Copy the latest one.
https://github.com/kenjis/ci418to433/blob/main/app/Config/Kint.php
