### ISSUE TITLE
Bug:  Unknown column `updated_at` in 'field list'

### ISSUE THREAD

**Issue by datamweb** [codeigniter4/CodeIgniter4#8192]
### PHP Version

8.2

### CodeIgniter4 Version

CodeIgniter v4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

libmysql - mysqlnd 8.0.10

### What happened?

> Unknown column updated_at in 'field list'

Column `updated_at` is required for all tables! 

### Steps to Reproduce

```console
composer create-project codeigniter4/appstarter CI4-bug
```
```console
php spark make:migration Test
```
```php
<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class Test extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'id'         => ['type' => 'int', 'constraint' => 11, 'unsigned' => true, 'auto_increment' => true],
            'email'      => ['type' => 'varchar', 'constraint' => 255],
            'ip_address' => ['type' => 'varchar', 'constraint' => 255],
            'created_at'   => ['type' => 'datetime', 'null' => true],
        ]);
        $this->forge->addPrimaryKey('id');


        $this->forge->createTable('test', false);
    }

    public function down()
    {
        //
    }
}

```

```console
php spark migratin --all
```
```console
php spark make:model Test
```

```php
<?php

namespace App\Models;

use CodeIgniter\Model;

class Test extends Model
{
    protected $table            = 'test';
    protected $primaryKey       = 'id';
    protected $useAutoIncrement = true;
    protected $returnType       = 'array';
    protected $useSoftDeletes   = false;
    protected $protectFields    = true;
    protected $allowedFields    = [
        'email'
    ];

    // Dates
    protected $useTimestamps = true;
    protected $dateFormat    = 'datetime';
    protected $createdField  = 'created_at';

    // Validation
    protected $validationRules      = [];
    protected $validationMessages   = [];
    protected $skipValidation       = false;
    protected $cleanValidationRules = true;

    // Callbacks
    protected $allowCallbacks = true;
    protected $beforeInsert   = [];
    protected $afterInsert    = [];
    protected $beforeUpdate   = [];
    protected $afterUpdate    = [];
    protected $beforeFind     = [];
    protected $afterFind      = [];
    protected $beforeDelete   = [];
    protected $afterDelete    = [];
}
```

```diff
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index(): string
    {
+model('Test')->insert([
+'email' =>'xx@fff.FFf',
+'ip_address' =>'127.127.0.0',
+]);
-return view('welcome_message');
    }
}
```

### Expected Output

The presence of `updated_at` in the tables should not be mandatory.

![Screenshot 2023-11-12 005830](https://github.com/codeigniter4/CodeIgniter4/assets/9530214/b5c61e23-279b-450c-95d8-8ecb73feb5bb)

### Anything else?

If I add column `updated_at` to the table. The error is fixed.

I could create a separate field for the date here instead of using `$useTimestamps`, but the question is why didn't CI cover this.

**Comment by kenjis** [comment]
At least this is not a bug.
> This requires that the table have columns named created_at, updated_at and deleted_at in the appropriate data type.
https://codeigniter4.github.io/CodeIgniter4/models/model.html?highlight=usetimestamps#dates

**Comment by kenjis** [comment]
Try:
```php
protected $updatedField = '';
```

**Comment by datamweb** [comment]
@kenjis You always make me happy, it worked!
Thanks!

**Comment by kenjis** [comment]
This is just a lack of documentation because that is how the code works.

**Comment by kenjis** [comment]
It was documented.
> Leave it empty to avoid update it (even $useTimestamps is enabled).
https://codeigniter4.github.io/CodeIgniter4/models/model.html?highlight=usetimestamps#updatedfield
