### ISSUE TITLE
Bug: imagewebp(): Palette image not supported by webp

### ISSUE THREAD

**Issue by stevy80** [codeigniter4/CodeIgniter4#8197]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.2

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 8

### What happened?

When converting some .png images to .webp with the using of the image library (gd), the following error occurs:
imagewebp(): Palette image not supported by webp

### Steps to Reproduce

```php
$image = \Config\Services::image(); 
$image->withfile($filePath); // $filePath to the png file
$image->convert(IMAGETYPE_WEBP);
$image->save();
```

### Expected Output

valid webp file

### Anything else?

currently the code in the GDHandler.php (save function):

```php
// for png and webp we can actually preserve transparency
if (in_array($this->image()->imageType, $this->supportTransparency, true)) {
   imagealphablending($this->resource, false);
   imagesavealpha($this->resource, true);
}
```

if I use imagepalettetotruecolor there, the problem solved for me, like:

```php
// for png and webp we can actually preserve transparency
if (in_array($this->image()->imageType, $this->supportTransparency, true)) {
   imagepalettetotruecolor($this->resource);
   imagealphablending($this->resource, false);
   imagesavealpha($this->resource, true);
}
```

**Comment by vini123** [comment]
虚幻之物对应着冥冥之路！：《羽》

**Comment by kenjis** [comment]
Cannot reproduce. The following test passes without errors.
Does it depend on the source PNG file?

```diff
--- a/tests/system/Images/GDHandlerTest.php
+++ b/tests/system/Images/GDHandlerTest.php
@@ -412,6 +412,14 @@ final class GDHandlerTest extends CIUnitTestCase
         $this->assertSame(exif_imagetype($this->start . 'work/ci-logo.png'), IMAGETYPE_PNG);
     }
 
+    public function testImageConvertPngToWebp(): void
+    {
+        $this->handler->withFile($this->origin . 'ci-logo.png');
+        $this->handler->convert(IMAGETYPE_WEBP);
+        $this->handler->save($this->start . 'work/ci-logo.webp');
+        $this->assertSame(exif_imagetype($this->start . 'work/ci-logo.webp'), IMAGETYPE_WEBP);
+    }
+
     public function testImageReorientLandscape(): void
     {
         for ($i = 0; $i <= 8; $i++) {
```

**Comment by stevy80** [comment]
Yes, it depends from the png. Some works (like ci-good.png), some not (ci-bad.png).  

![ci-bad](https://github.com/codeigniter4/CodeIgniter4/assets/204900/388e95fb-75f0-4017-97a0-5ff8f6160b09)
![ci-good](https://github.com/codeigniter4/CodeIgniter4/assets/204900/6aa2a685-2485-43e3-9a78-4e8a89537ee8)

**Comment by kenjis** [comment]
@stevy80 Thank you! I sent a PR #8210
