### ISSUE TITLE
No way to remove an already added CSP header

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#8213]
Hello i always set a default src on each route inside the controller that extends a default controller

and i have no option to recreate the response csp headers

but on some routes CSP headers need to be modified
for example i cannot use **nonce** with **unsafe-inline** 
it just simply does not work.

so i tried this kind of approach

inside this file **system/HTTP/ContentSecurityPolicy.php**
i have added this public function to help me rewrite the headers for a particular src

	public function updateSrc(string $src, string $uri, ?bool $explicitReporting = null)
	{
		$this->$src = [];
		
		$this->addOption($uri, $src, $explicitReporting ?? $this->reportOnly);
	}
	
	
and inside my controller 

	$this->response->CSP->updateSrc('styleSrc', 'unsafe-inline'); // this removes all the headers for styleSrc and add unsafe_inline
	$this->response->CSP->updateSrc('fontSrc', 'https://fonts.gstatic.com');
	$this->response->CSP->addStyleSrc('self'); // after that i can add default stuff..
	$this->response->CSP->addFontSrc('self'); // after that i can add default stuff..
	
is this a correctly approach ? 
can we get this method or some other way to remove and recreate the header for a particular source (styleSrc, scriptSrc) ?

**Comment by kenjis** [comment]
As you say, there is no way to remove the existing CSP directives.
https://codeigniter4.github.io/CodeIgniter4/outgoing/csp.html

And it would be better to have a method to remove directives.
`setDirective('style-src', '...')` or `resetDirective('style-src', '...')`?

**Comment by crustamet** [comment]
this would be a great feature if i just can remove the directives just as you say..

**Comment by kenjis** [comment]
Ah, just making a directive empty is better? E.g., `clearDirective('style-src')`.

**Comment by crustamet** [comment]
Works for me, but there is no clearDirective implemented :D

**Comment by kenjis** [comment]
I sent a PR #8220

**Comment by crustamet** [comment]
looks like a good PR for me :D it should pass all the tests.

**Comment by kenjis** [comment]
@crustamet If you review/test #8220 and you think it should be merged, please approve the PR.

**Comment by crustamet** [comment]
I had updated the source code with your modifications, for me its working.
If i knew how to approve the PR i would.
I do approve the PR.

How can i approve the PR ?

**Comment by kenjis** [comment]
See ![Screenshot 2023-11-17 6 50 08](https://github.com/codeigniter4/CodeIgniter4/assets/87955/70a4400b-fbe2-49ea-94d2-5164bd54b2a0)
