### ISSUE TITLE
No way to get params from matched route

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#8241]
i propose just making a method for it to just return them

like this

in FILE : **system/Router/Router.php**

`
    public function getMatchedRouteParams()
    {
        return $this->params;
    }
`

**Comment by datamweb** [comment]
Please submit feature requests to our [forum](https://forum.codeigniter.com/forum-29.html).
We use github issues to track bugs and planned work.

**Comment by crustamet** [comment]
Please, this is a feature request.

I just want that piece of code inside the **Router**.

This is a bug because when i print the current route it shows me the params and there is no way to get them

**Comment by kenjis** [comment]
Why don't you use `params()`?
https://github.com/codeigniter4/CodeIgniter4/blob/8b9529fd9a55f1808cbee192b24cc11169ecc11e/system/Router/Router.php#L289-L292
