### ISSUE TITLE
Bug: Call to an undefined method CodeIgniter\HTTP\URI::getRoutePath()

### ISSUE THREAD

**Issue by sanchawebo** [codeigniter4/CodeIgniter4#8246]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL 5.7

### What happened?

When coding a filter i came across the following issue:
PHPStan marks the line `$route = $uri->getRoutePath();` with the error in the title. That happens because `getUri()` return a `URI` instance and not a `SiteURI` instance.

### Steps to Reproduce

```php
public function before(RequestInterface $request, $arguments = null)
{
     $uri   = $request->getUri();
     $route = $uri->getRoutePath();
}
```

### Expected Output

Expected no error and intellisense for `$uri`.

### Anything else?

If i annotate `$uri` with `/** @var \CodeIgniter\HTTP\SiteURI $uri */` it works properly.

**Comment by kenjis** [comment]
Thank you for reporting.

Yes, PHPStan is correct. `URI` does not have `getRoutePath()`.

`$request->getUri()` must return `URI` to follow [PSR-7](https://www.php-fig.org/psr/psr-7/). (CI4 is not yet PSR-7 compliant, but we are working toward it.)
How could we fix this?

**Comment by evele** [comment]
Why this marked as completed??? Still not working.
