### ISSUE TITLE
Bug: Model does not update `created_at` column

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#8247]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.3 and develop 1d6b7ac3c9b9b1d426cd480140588f1b84fb6988

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli

### Database

n/a

### What happened?

The following test fails:
```php
<?php

namespace CodeIgniter\Models;

use Tests\Support\Models\UserTimestampModel;

/**
 * @group DatabaseLive
 *
 * @internal
 */
final class TimestampModelTest extends LiveModelTestCase
{
    protected $migrate     = true;
    protected $migrateOnce = true;
    protected $refresh     = false;
    protected $seed        = '';

    private function prepareOneRecord(): void
    {
        $this->createModel(UserTimestampModel::class);
        $this->db->table('user')->truncate();

        $data = [
            'name'       => 'John Smith',
            'email'      => 'john@example.com',
            'country'    => 'US',
            'created_at' => '2000-01-01 12:00:00',
            'updated_at' => '2000-01-01 12:00:00',
        ];
        $this->model->insert($data);
    }

    public function testUpdateArrayUpdates UpdatedAt(): void
    {
        $this->prepareOneRecord();

        $user = $this->model->find(1);

        $user['country'] = 'CA';
        $this->model->update($user['id'], $user);

        $user = $this->model->find(1);

        $this->assertNotSame('', $user['updated_at']);
        $this->assertNotSame($user['created_at'], $user['updated_at']);
    }
}
```
```php
<?php

namespace Tests\Support\Models;

use CodeIgniter\Model;

class UserTimestampModel extends Model
{
    protected $table         = 'user';
    protected $allowedFields = [
        'name',
        'email',
        'country',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
    protected $returnType     = 'array';
    protected $useSoftDeletes = true;
    protected $useTimestamps  = true;
    protected $dateFormat     = 'datetime';
}
```

### Steps to Reproduce

Run test above.

### Expected Output

The test passes.

### Anything else?

> $useTimestamps
This boolean value determines whether the current date is automatically added to all inserts and updates. If true, will set the current time in the format specified by [$dateFormat](https://codeigniter4.github.io/CodeIgniter4/models/model.html#dateformat).
https://codeigniter4.github.io/CodeIgniter4/models/model.html#dates

**Comment by kenjis** [comment]
Is this not a bug? 
> the current date is automatically **added** to all inserts and updates.

**Comment by lonnieezell** [comment]
I'm on my phone so can't look at the original code right now but here's my view:

- created_at should be updated only on inserts, and only if the existing data doesn't have any value in created at. You might need to insert some old data and not lose the existing creation date.
- updated at should always be updated for both inserts and updates. It could be argued that if it has an existing updated date we should respect that, and I would be ok with that.

**Comment by kenjis** [comment]
No problem. The code was wrong. I've fixed.

The issue is:
- If we pass an array data with `update_at` to Model, the `update_at` column is not changed.
- If we pass an Entity with `update_at` to Model, the `update_at` column is updated.

This is because Entity uses onlyChanged.

The following test passes:
```php
    public function testUpdateEntityUpdatesCreatedAt(): void
    {
        $this->createModel(UserTimestampModel::class);
        $this->setPrivateProperty($this->model, 'returnType', User::class);
        $this->setPrivateProperty($this->model, 'tempReturnType', User::class);
        $this->db->table('user')->truncate();

        $data = [
            'name'       => 'John Smith',
            'email'      => 'john@example.com',
            'country'    => 'US',
            'created_at' => '2000-01-01 12:00:00',
            'updated_at' => '2000-01-01 12:00:00',
        ];
        $this->model->insert($data);

        $user = $this->model->find(1);

        $user->country = 'CA';
        $this->model->update($user->id, $user);

        $user = $this->model->find(1);

        $this->assertNotSame('', $user->updated_at);
        $this->assertNotSame($user->created_at, $user->updated_at);
    }
```

**Comment by kenjis** [comment]
This is complicated because `$allowedFields` effects.

The normal use case is not to add `created_at` and `updated_at` to `$allowedFields`, so these fields are removed, resulting in the date and time being automatically set or updated even if they are passed. Therefore there is no problem.

> You might need to insert some old data and not lose the existing creation date.

In this case, we need to add `created_at` to `$allowedFields`, and there seems no problem.

>  if it has an existing updated date we should respect that, and I would be ok with that.

In this case, we need to add `updated_at` to `$allowedFields`, and if Entity is used and `updated_at` is not changed, the passed updated_at dates will not be respected. But if we want to change `updated_at` date, we would change the value in Entity, so there seems no problem.

In the end, the current Model behavior seems to be no problem.

**Comment by kenjis** [comment]
I sent PR to add tests: #8249

**Comment by lonnieezell** [comment]
You're right. I wasn't thinking about allowed fields. If they need to add old data like that they can always do it directly through a builder instance.
