### ISSUE TITLE
Bug: Resource and Presenter routes does not accept qualified names for controller option

### ISSUE THREAD

**Issue by puwnd** [codeigniter4/CodeIgniter4#8248]
### PHP Version

7.4, 8.1

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### What happened?

According to the documentation the _Resource_ and _Presenter_ routes can accept a _controller_ option like **App\Home**. But if I run the  
`php spark routes` command, it displays the handler like this: **\App\Controllers\App\Controllers\Home::index**, but it should be like this: **\App\Controllers\Home::index**. So in this case it will not be found and throws 404.

### Steps to Reproduce

In the app/Routes.php file:

```php
$routes->resource('test', ['controller' => Home::class]);
```

### Expected Output

The `php spark routes` command should display **\App\Controllers\Home::index** for handler. Or just modify the documentation :D

### Anything else?

Source: https://stackoverflow.com/questions/77545608/problem-to-make-api-restful-test-using-codeigniter-4-framework-urls-dont-answ/77545871#77545871

I tried to answer the question with some workaround, but it seems to be a minor bug for me.

**Comment by kenjis** [comment]
Try:
```php
$routes->resource('test1', ['namespace' => '\\', 'controller' => Home::class]);
$routes->resource('test2', ['controller' => '\\' . Home::class]);
$routes->resource('test3', ['controller' => 'Home']);
```

This is because `if a controller is written without a leading \, the Default Namespace will be prepended:`
See https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#controller-s-namespace

**Comment by kenjis** [comment]
I sent PR to fix docs: #8253

**Comment by steven7mwesigwa** [comment]
I don't think this is a bug. 

The StackOverflow original poster basically wasn't aware that the router would add the default namespace value to the front of the controller specified by the route.

[CodeIgniter4 namespace repeating itself: Controller or its method is not found: \\App\\Controllers\\App\\Controllers\\TypeBloodController::index](https://stackoverflow.com/a/77547544/7376590)

**Comment by kenjis** [comment]
@steven7mwesigwa Yes, this is not a bug in the framework.

But the current sample code in *RESTful Resource Handling* is misleading:
https://codeigniter4.github.io/CodeIgniter4/incoming/restful.html#change-the-controller-used
We don't use/expect controllers lke `\App\Controllers\App\Gallery`.
