### ISSUE TITLE
Bug:  Uncaught Error: Call to undefined function form_open() in 

### ISSUE THREAD

**Issue by arjunhgw** [codeigniter4/CodeIgniter4#8252]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

the form_open() is not working

### Steps to Reproduce

i have a controller file

<?php

namespace App\Controllers;

use App\Models\MyFormModel;
// use CodeIgniter\Controller;

class MyFormController extends BaseController
{
    public function index()
    {
       
       
        return view('my_form');
    }

    public function processForm()
    {
   
        helper('form');
        
        
        
        
        i have a model filoe as well
        
        <?php

namespace App\Models;

use CodeIgniter\Model;

class MyFormModel extends Model
{
    protected $table = 'user_data';
    protected $primaryKey = 'id';
    protected $allowedFields = ['name', 'email', 'category'];

    public function insertUserData($data)
    {
        return $this->insert($data);
    }
}

the view file

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Form</title>
</head>
<body>

<?php echo form_open(base_url('my-form/process-form')); ?>

    <label for="name">Name:</label>
    <input type="text" name="name" value="<?php echo set_value('name'); ?>" required>
    <?php echo '<p style="color: red;">' . \Config\Services::validation()->getError('name') . '</p>'; ?>

    <label for="email">Email:</label>
    <input type="email" name="email" value="<?php echo set_value('email'); ?>" required>
    <?php echo '<p style="color: red;">' . \Config\Services::validation()->getError('email') . '</p>'; ?>

    <label for="category">Category:</label>
    <select name="category" required>
        <option value="" selected disabled>Select...</option>
        <option value="tag1">Tag 1</option>
        <option value="tag2">Tag 2</option>
        <option value="other">Other</option>
    </select>
    <?php echo '<p style="color: red;">' . \Config\Services::validation()->getError('category') . '</p>'; ?>

    <?php echo form_submit('submit', 'Submit'); ?>
    <?php echo form_close(); ?>

    <?php
    // Display the global sum if it's set in flash data
    if (session()->getFlashdata('globalSum')) {
        echo '<p>Global Sum: ' . session()->getFlashdata('globalSum') . '</p>';
    }
    ?>

</body>
</html>

form_open shows undefined

### Expected Output

from should open

### Anything else?

also in routes
$routes->post('my-form/process-form', 'MyFormController::processForm');

**Comment by samsonasik** [comment]
You need to load the form helper, read the docs https://codeigniter.com/user_guide/helpers/form_helper.html?highlight=form_open#id2

**Comment by arjunhgw** [comment]
it is already loaded in my controller file

**Comment by samsonasik** [comment]
That's not, see function index() that load the form and doesn't load the helper.

**Comment by arjunhgw** [comment]
class MyFormController extends BaseController
{
    public function index()
    {
        
        helper('form');
        return view('my_form');
    }
this is not working

**Comment by samsonasik** [comment]
did you try load on the view?

**Comment by arjunhgw** [comment]
please elaborate

**Comment by samsonasik** [comment]
In view file; write :.

```php
// your my_form.php
helper("form");

echo form_open();
```

**Comment by arjunhgw** [comment]
nope its not working

**Comment by kenjis** [comment]
Your code should work.

But v4.1.5 is too old. Upgrade to the latest version.
https://codeigniter4.github.io/CodeIgniter4/installation/upgrading.html

**Comment by samsonasik** [comment]
That's strange, it probably related with how you open the project, if you install manually, ensure you follow the doc

https://codeigniter.com/user_guide/installation/installing_manual.html
