### ISSUE TITLE
Bug: autoloader: global helpers are not loaded when bootstraped with phpunit

### ISSUE THREAD

**Issue by benbro01** [codeigniter4/CodeIgniter4#8272]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 8.1

### What happened?

I upgraded the CI Library to v1.0.0-beta.8 which changed how the helpers are loaded: "Helper autoloading has been changed to be done by CodeIgniter's autoloader instead of Composer." [https://github.com/codeigniter4/shield/blob/develop/UPGRADING.md#version-100-beta7-to-100-beta8](url)

Therefore I changed the autoloader.php config file to globaly load the "auth" and "setting" helper. After that many of my tests failed due to the helper not being loaded by the testing framework.

### Steps to Reproduce

1. Create any custom helper file with a method "test_autoloader"
2. Add the helper to the `$helper` array in `Config\Autoload.php`
3. write a test which extends CIUnitTestCase
4. run `function_exists('test_autoloader')` - it will return false

### Expected Output

when comparing the "normal" bootstrap.php to the bootstrap.php which is loaded on testing, it becomes obvious, that the `Services::autoloader()->loadHelpers();` is missing and therefore the helper specified in `Config\Autoload.php` are not loaded. 
In my case this leads to the shield lib failing because the function from the helper can not be found.

### Anything else?

**vendor/codeigniter4/framework/system/bootstrap.php**:
```php
...
require_once SYSTEMPATH . 'Config/Services.php';
require_once APPPATH . 'Config/Services.php';

// Initialize and register the loader with the SPL autoloader stack.
Services::autoloader()->initialize(new Autoload(), new Modules())->register();
Services::autoloader()->loadHelpers();
```

**vendor/codeigniter4/framework/system/Test/bootstrap.php**:
```php
...
require_once SYSTEMPATH . 'Config/Services.php';
require_once APPPATH . 'Config/Services.php';

// Initialize and register the loader with the SPL autoloader stack.
Services::autoloader()->initialize(new Autoload(), new Modules())->register();

// Now load Composer's if it's available
if (is_file(COMPOSER_PATH)) {
    require_once COMPOSER_PATH;
}
...
```

**Comment by benbro01** [comment]
let me clarify, I meant creating any helper, for example `test_autoloader_helper.php` which implements the method `test_autoloader()`. Add `test_autoloader` to the `$helpers` array in `Config\Autoload.php`. Therefore 3333333333333

**Comment by kenjis** [comment]
I sent PR #8275. Please review and approve if it okay.

**Comment by benbro01** [comment]
Yes, this works, at least for my issues, thanks
