### ISSUE TITLE
Bug: SYSTEMPATH/Session/Handlers/FileHandler.php at line 128

### ISSUE THREAD

**Issue by mettleshade** [codeigniter4/CodeIgniter4#8279]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.2

### What happened?

I created an extension for my error_exception.php file to log errors to the database. I am encountering a recurring issue, but there is no problem when I manually enter URLs.

Error:
`SYSTEMPATH/Session/Handlers/FileHandler.php at line 128 -> 0 www.hepsimoda.com.tr/bt-zebra-desen-balon-kol-tunik-vizon-krem`

I have many different URLs like this one, and I'm encountering the same issue.

error_exception.php
```php
$errorId = uniqid('error', true);
$title = "Hata oluştu, Lütfen ekran görüntüsü alıp site iletişimine bildiriniz.";
?>
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex">

    <title><?= esc($title) ?></title>
    <style>
        <?= preg_replace('#[\r\n\t ]+#', ' ', file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . 'debug.css')) ?>
    </style>

    <script>
        <?= file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . 'debug.js') ?>
    </script>
</head>
<body onload="init()">

<!-- Header -->
<div class="header">
    <div class="container">
        <h1><?= esc($title), esc($exception->getCode() ? ' #' . $exception->getCode() : '') ?></h1>
        <p>
            <?= nl2br(esc($exception->getMessage())) ?>
            <a href="https://www.duckduckgo.com/?q=<?= urlencode($title . ' ' . preg_replace('#\'.*\'|".*"#Us', '', $exception->getMessage())) ?>"
               rel="noreferrer" target="_blank">search &rarr;</a>
        </p>
    </div>
</div>

<?php
HataLog('Kritik Hata', "", esc(clean_path($file)) . "</b> at line <b>" . esc($line) . " -> " . " " . $exception->getCode() . " " . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']);
?>

</body>
</html>
```

### Steps to Reproduce

I don't know how it occurred.

### Expected Output

I don't know how it occurred.

**Comment by mettleshade** [comment]
error_exception file :

<?php

use Config\Services;
use CodeIgniter\CodeIgniter;

$errorId = uniqid('error', true);
$title = "Hata oluştu, Lütfen ekran görüntüsü alıp site iletişimine bildiriniz.";
?>
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex">

    <title><?= esc($title) ?></title>
    <style>
        <?= preg_replace('#[\r\n\t ]+#', ' ', file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . 'debug.css')) ?>
    </style>

    <script>
        <?= file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . 'debug.js') ?>
    </script>
</head>
<body onload="init()">


<div class="header">
    <div class="container">
        <h1><?= esc($title), esc($exception->getCode() ? ' #' . $exception->getCode() : '') ?></h1>
        <p>
            <?= nl2br(esc($exception->getMessage())) ?>
            <a href="https://www.duckduckgo.com/?q=<?= urlencode($title . ' ' . preg_replace('#\'.*\'|".*"#Us', '', $exception->getMessage())) ?>"
               rel="noreferrer" target="_blank">search &rarr;</a>
        </p>
    </div>
</div>

<?php
HataLog('Kritik Hata', "", esc(clean_path($file)) . "</b> at line <b>" . esc($line) . " -> " . " " . $exception->getCode() . " " . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']);
?>

</body>
</html>

**Comment by mettleshade** [comment]
error_exception file : https://prnt.sc/pgV3eX7B3RQZ

**Comment by kenjis** [comment]
What is `0 www.hepsimoda.com.tr/bt-zebra-desen-balon-kol-tunik-vizon-krem` in the log?
Can you show all error messages with backtrace?

**Comment by mettleshade** [comment]
sorry,I'm not understand

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
