### ISSUE TITLE
Bug: useSoftDeletes not working

### ISSUE THREAD

**Issue by ksevendev** [codeigniter4/CodeIgniter4#8297]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

8.0

### What happened?

I am using useSoftDeletes; however, when I delete, either manually or through a request, the data continues to be displayed as "deleted." I have already used methods such as getRow, find, findAll, paginate, getResult, and so on.

### Steps to Reproduce

```php
 class MemberModel extends Model
    {
        //protected $DBGroup          = 'default';

        protected $table            = 'people';
        protected $primaryKey       = 'id';

        protected $useAutoIncrement = true;

        protected $returnType       = 'object';
        protected $useSoftDeletes   = true;

        protected $protectFields    = true;
        protected $allowedFields    = [
           ...
        ];

        // Dates
        protected $useTimestamps = true;
        protected $dateFormat    = 'datetime';
        protected $createdField  = 'created_at';
        protected $updatedField  = 'updated_at';
        protected $deletedField  = 'deleted_at';
        
        ...
```

Examples:

```php       
        public function countAllMembers($type)
        {
            $builder = $this->table($this->table);
            $builder->where($this->table . '.type', $type);
            return $builder->countAllResults();
        }

        public function getContributions($ID)
        {
            $builder = $this->table($this->table);
            $builder->select('*');
            $builder->where($this->table . '.id', $ID);
            $builder->join('people_contributions contribution', $this->table . '.id = contribution.people_id');
            return $builder->findAll();
        }
```

### Expected Output

Hidden register deleted

**Comment by kenjis** [comment]
You are confusing Model and Query Builder.
The soft deletes are a feature in Model. Query Builder does not have soft deletes.
> If true, the find*() methods will only return non-deleted rows, unless the withDeleted() method is called prior to calling the find*() method.
https://codeigniter4.github.io/CodeIgniter4/models/model.html#usesoftdeletes
