### ISSUE TITLE
Bug: Entity::jsonSerialize() returns strange dates

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#8303]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.3 and develop

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MySQL 8.0.34

### What happened?

Entity with dates returns JSON with strange format of dates.
```
    "created_at": {
        "date": "2023-12-07 04:00:48.000000",
        "timezone_type": 3,
        "timezone": "UTC"
    },
```

### Steps to Reproduce

```
+----+------------+--------------------+---------+--------------------+--------------------+------------+
| id | name       | email              | country | created_at         | updated_at         | deleted_at |
+----+------------+--------------------+---------+--------------------+--------------------+------------+
| 1  | John Smith | john@example.co... | US      | 2023-12-07 04:0... | 2023-12-07 04:0... |            |
+----+------------+--------------------+---------+--------------------+--------------------+------------+
```
```php
<?php

namespace App\Models;

use App\Entities\User;
use CodeIgniter\Model;

class UserModel extends Model
{
    protected $table            = 'user';
    protected $returnType       = User::class;
    protected $allowedFields    = [
        'name',
        'email',
        'country',
    ];

    // Dates
    protected $useTimestamps = true;
    protected $dateFormat    = 'datetime';
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';
}
```
```php
<?php

namespace App\Entities;

use CodeIgniter\Entity\Entity;

class User extends Entity
{
    protected $datamap = [];
    protected $dates   = ['created_at', 'updated_at', 'deleted_at'];
    protected $casts   = [];
}
```
```php
    public function index()
    {
        $users = new UserModel();
        /** @var User $user */
        $user = $users->find(1);
        echo json_encode($user, JSON_PRETTY_PRINT);
    }
```

```json
{
    "id": "1",
    "name": "John Smith",
    "email": "john@example.com",
    "country": "US",
    "created_at": {
        "date": "2023-12-07 04:00:48.000000",
        "timezone_type": 3,
        "timezone": "UTC"
    },
    "updated_at": {
        "date": "2023-12-07 04:00:48.000000",
        "timezone_type": 3,
        "timezone": "UTC"
    },
    "deleted_at": null
}
```

### Expected Output

```json
{
    "id": "1",
    "name": "John Smith",
    "email": "john@example.com",
    "country": "US",
    "created_at": "2023-12-07 04:00:48",
    "updated_at": "2023-12-07 04:00:48",
    "deleted_at": null
}
```

### Anything else?

See also #8302

**Comment by michalsn** [comment]
Seems like the default behavior for the `DateTime` object.

If we want to change it, the question is, do we really want to lose the time zone information?

**Comment by neznaika0** [comment]
Yes, it defaut action for JSON dates. Timezone may be set 
 **2023-12-07 04:00:48 +1:00** 
**2023-12-07 04:00:48 Europe/Berlin**
?

**Comment by kenjis** [comment]
> If we want to change it, the question is, do we really want to lose the time zone information?

Yes. Because this issue is about the default behavior.
And `(string) Time::now()` returns a string without timezone like `2023-12-08 00:58:44`.

Whether timezone is required or not depends on requirement.
If it is needed, a dev can override the jsonSerialize() method.

**Comment by michalsn** [comment]
I don't have a strong opinion about this, but I wouldn't call it a bug.

If we want to change this behavior that should be considered as a breaking change since the default value for JSON will change. Developers who have built an API may rely on this because this is the default behavior in PHP.

**Comment by neznaika0** [comment]
Why don't we know? This shows what type of zone is displayed. To restore an object, it is not important, you only need the date and timezone.

 Why not add array support with these keys to `Time()`? It works for me

**Comment by kenjis** [comment]
> Why don't we know?

Because it is not documented. I don't know the exact meaning.

> Why not add array support with these keys to Time()? It works for me

What do you mean?

**Comment by kenjis** [comment]
There seem to be maybe three values for `timezone_type`.
https://3v4l.org/gDGst

**Comment by neznaika0** [comment]
`A DateTimeZone object provides access to three different types of timezone rules: UTC offset (type 1), timezone abbreviation (type 2), and [timezone identifiers](https://www.php.net/manual/en/timezones.php) as published in the IANA timezone database (type 3).`
https://www.php.net/manual/en/datetimezone.construct.php#refsect1-datetimezone.construct-description

**Comment by neznaika0** [comment]
We studied this when there was a bug with Datetime serialization. Don't you remember?
https://github.com/codeigniter4/CodeIgniter4/issues/7780#issuecomment-1666594405

**Comment by neznaika0** [comment]
> > Why not add array support with these keys to Time()? It works for me
> 
> What do you mean?

```php
<?php

namespace App\Entities\Cast;

use CodeIgniter\Entity\Cast\BaseCast;
use CodeIgniter\Entity\Cast\DatetimeCast;
use CodeIgniter\I18n\Time;
use DateTimeZone;

/**
 * Adds date conversion from a JSON array as:
 * [
 *     'date'          => '2000-11-25 10:20:35.000000'
 *     'timezone_type' =>  3
 *     'timezone'      => 'Europe/Moscow'
 * ]
 */
class ExtendedDatetimeCast extends BaseCast
{
    public static function get($value, array $params = [])
    {
        return DatetimeCast::get($value, $params);
    }

    public static function set($value, array $params = [])
    {
        if (is_array($value) && array_key_exists('date', $value) && array_key_exists('timezone', $value)) {
            return DatetimeCast::get(new Time($value['date'], new DateTimeZone($value['timezone'])));
        }

        return DatetimeCast::set($value, $params);
    }
}
```

**Comment by crustamet** [comment]
I don't think it is a bug because if you want the expected output you can just remove the 


	class User extends Entity
	{
	    protected $datamap = [];
	    //protected $dates   = ['created_at', 'updated_at', 'deleted_at'];
	    protected $dates = [];
	    protected $casts   = [];
	}

and it should work as you wanted.

**Comment by kenjis** [comment]
The current behavior is the behavior of PHP's `DateTime`.
So we can think this is not a bug. 

```php
echo json_encode(new DateTime('now'));
// {"date":"2024-02-08 22:57:15.503235","timezone_type":3,"timezone":"UTC"}
```

**Comment by feyputra** [comment]
> The current behavior is the behavior of PHP's `DateTime`. So we can think this is not a bug.
> 
> echo json_encode(new DateTime('now'));
> // {"date":"2024-02-08 22:57:15.503235","timezone_type":3,"timezone":"UTC"}

I can't convert to 
"created_at": "2026-01-27 23:42:48",
"updated_at": "2026-01-27 23:42:48",
I followed the documentation but it still results in date array,. How can I fulfill my expectations above?

**Comment by michalsn** [comment]
@feyputra Please ask support questions in the [Forum](https://forum.codeigniter.com/forum-30.html).

You should probably override the current `jsonSerialize()` implementation.

**Comment by feyputra** [comment]
> [@feyputra](https://github.com/feyputra) Please ask support questions in the [Forum](https://forum.codeigniter.com/forum-30.html).
> 
> You should probably override the current `jsonSerialize()` implementation.

It's a bit strange, when created_at and updated_at are not registered in Entity but the variables change by themselves.

**Comment by neznaika0** [comment]
Dates are a built-in feature. When you call `$o->created_at`, you will get the conversion automatically. set `$dates = []` and add the dates manually in `$casts`.

**Comment by feyputra** [comment]
I tried using jsonSerialize and the data was as expected, but when I called it back in the Controller, for example, : $report->created_at the result returned an array. Very annoying
