### ISSUE TITLE
request post empty as string to null for insert in to FOREIGN KEY

### ISSUE THREAD

**Issue by rozpuh** [codeigniter4/CodeIgniter4#8328]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDb 10.8

### What happened?

I receive data from the form
```php
$post = $this->request->getPost();
 array(1) { [0]=> array(5) { ["price_from"]=> string(1) "8" ["price_to"]=> string(1) "8" ["brand_id"]=> string(0) "" ["customer_group_id"]=> string(0) "" ["coefficient"]=> string(1) "8" } }
```

it defines empty strings as (string)
Because of this, an error occurs when inserting into the database on fields where they are defined as null

In Laravel, empty lines are defined as zero and there are no problems when inserting them into the database.
 
 

### Steps to Reproduce

```php
$post = $this->request->getPost();
 model('SupplierPriceSettingModel')->insertBatch($post);
```

mysql error
Cannot add or update a child row: a foreign key constraint fails (`test`.`ax_supplier_price_settings`, CONSTRAINT `ax_supplier_price_settings_ibfk_2` FOREIGN KEY (`brand_id`) REFERENCES `ax_brands` (`id`) ON DELETE CASCADE)

### Expected Output

empty as null in request

**Comment by rozpuh** [comment]
found a solution
sql_mode='ORACLE,EMPTY_STRING_IS_NULL'

But I think the request() should itself be converted to null

**Comment by kenjis** [comment]
You are trying to insert an empty string to the database column.
An empty string is not a null.
If you want to insert null, why don't you insert null instead of an empty string?

Why do you think the current behavior is a bug?
How do we do when we really want to insert an empty string?

**Comment by rozpuh** [comment]
> You are trying to insert an empty string to the database column. An empty string is not a null. If you want to insert null, why don't you insert null instead of an empty string?
> 
> Why do you think the current behavior is a bug? How do we do when we really want to insert an empty string?

maybe this isn't a bug.  Maybe it's worth adding conversion of empty strings to null in the settings?  because when using table relationships in a database by key, type conversion problems arise.  Your insert and update are very convenient, I don’t need to create my data array before inserting it into the database, I just pass request()-getPost().  but now it turns out I need to check each element in the array and convert empty strings to null

**Comment by kenjis** [comment]
For example, simply add the following method to your (base) controller.
Or you could extend the Request class to have such method.
Is it worthwhile for the framework to have the feature?  

```php
private function getPost(): array
{
    $data = $this->request->getPost()
    $array = array_map(function($value) {
        return $value === '' ? null : $value;
    }, $array);
}
```

**Comment by paolooo** [comment]
Before saving the data, we could perform an auto sanitizing or casting. But, you can simply do this manually by adding it into your saving logic.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
