### ISSUE TITLE
Bug: [CURLRequest] Multiple HTTP 100 return by API 

### ISSUE THREAD

**Issue by PhpEssential** [codeigniter4/CodeIgniter4#8347]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### What happened?

When I call API built with a Flask server, this one return these headers:

HTTP/1.1 100 Continue

HTTP/1.1 100 Continue

HTTP/1.1 500 INTERNAL SERVER ERROR
Server: Werkzeug/2.2.3 Python/3.7.16
Date: Tue, 19 Dec 2023 21:30:20 GMT
Content-Type: application/json
Content-Length: 403
Access-Control-Allow-Origin: *
Connection: close

In this case the CURLRequest class doesn't parse correctlly the headers

### Steps to Reproduce

Make POST API with Flask 2.2.5 in debug mode and call it via CURLRequest

### Expected Output

In this case status code should be 500 not 100

### Anything else?

Just change this:
```php
        if (strpos($output, 'HTTP/1.1 100 Continue') === 0) {
```
By this:
```php
        while (strpos($output, 'HTTP/1.1 100 Continue' . $breakString) === 0) {
```

at line 392

For others who have the problem, actually I overwrite the class and specially the function send in my project and instanciate it via this function in Config\Service:

```php
    public static function curlrequest($options = [], ResponseInterface $response = null, App $config = null, $getShared = false) {
        if ($getShared) {
            return static::getSharedInstance('curlrequest');
        }
        
        if(empty($config)) {
            $config = config(App::class);
        }
        return new CURLRequest($config, new URI((empty($options['baseURI']) ? null : $options['baseURI'])), $response, $options);
     }
```

**Comment by kenjis** [comment]
Your fix makes an existing test fail.

How about this?
```diff
--- a/system/HTTP/CURLRequest.php
+++ b/system/HTTP/CURLRequest.php
@@ -389,7 +389,7 @@ class CURLRequest extends OutgoingRequest
         // Set the string we want to break our response from
         $breakString = "\r\n\r\n";
 
-        if (strpos($output, 'HTTP/1.1 100 Continue') === 0) {
+        while (strpos($output, 'HTTP/1.1 100 Continue') === 0) {
             $output = substr($output, strpos($output, $breakString) + 4);
         }
 
```

**Comment by ping-yee** [comment]
Off topic, I have prepared the reproduction code and set up the server.
But how can I obtain the header information?

```
HTTP/1.1 100 Continue

HTTP/1.1 100 Continue

HTTP/1.1 500 INTERNAL SERVER ERROR
Server: Werkzeug/2.2.3 Python/3.7.16
Date: Tue, 19 Dec 2023 21:30:20 GMT
Content-Type: application/json
Content-Length: 403
Access-Control-Allow-Origin: *
Connection: close
```

**Comment by kenjis** [comment]
```console
$ curl -v https://codeigniter.com
```

**Comment by ping-yee** [comment]
@kenjis I've reproduced the issue and the change can work.
I sent the PR #8466

**Comment by kenjis** [comment]
@ping-yee Great!

**Comment by PhpEssential** [comment]
Ok thanks ! In my case the flask call another api, maybe it's the way to reproduce
