### ISSUE TITLE
Bug: View HTML Table class displays tag attributes as columns 

### ISSUE THREAD

**Issue by eSkiSo** [codeigniter4/CodeIgniter4#8361]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 8

### What happened?

When using the addRow using 'data'with cell tag attributes (class, colspan, etc), the cell tags attributes will be displayed as columns

### Steps to Reproduce

```php
$table = new \CodeIgniter\View\Table();
$table->addRow(['data' => 'Blue', 'class' => 'highlight', 'colspan' => 2]);
echo $table->generate();
```

### Expected Output

Expected:
```html
<td class='highlight' colspan='2'>Blue</td>
```

What it outputs:
```html
<td>Blue</td><td>highlight</td><td>2</td></tr>
```

### Anything else?

Please notice that if you add another 'column' on the same **addRow** it will output correctly:
```php
$table->addRow(['data' => 'Blue', 'class' => 'highlight', 'colspan' => 2], 'Red');
```
Outputs:
```html
<td colspan="2" class="highlight">Blue</td><td>Red</td></tr>
```

**Comment by kenjis** [comment]
Related #8054

**Comment by kenjis** [comment]
I have confirmed this behavior.
But do you really need to output one row table like that?

**Comment by kenjis** [comment]
This seems difficult (impossible?) to fix. So I don't fix.

**Comment by kenjis** [comment]
Workaround.

```php
        $table = new \CodeIgniter\View\Table();
        $table->addRow([['data' => 'Blue', 'class' => 'highlight', 'colspan' => 2]]);
        return $table->generate();
```

**Comment by eSkiSo** [comment]
Fair enough. Close it.
