### ISSUE TITLE
Add possibility to ignore SMTP TLS certificate validation

### ISSUE THREAD

**Issue by orhtej2** [codeigniter4/CodeIgniter4#8371]
When interacting with STARTTLS SMTP would it be possible to either
- accept self-signed certificates
- ignore cert being issued for different domain
- allow server name override for IP connections?

What I'd like to do is to send an email from `localhost` or `127.0.0.1`, and with currently broken configuration on my server such connection presents cert that's valid for external `domain.tld`

**Comment by kenjis** [comment]
You need to customize Email class.

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
