### ISSUE TITLE
Database Extends

### ISSUE THREAD

**Issue by byazrail** [codeigniter4/CodeIgniter4#8378]
Forum Address
https://forum.codeigniter.com/showthread.php?tid=89047

Is it possible to extend the Database Library?

The reason I want to extend is as follows;
1- Use of Master and Replica in Database Connection.
2- To process transactions on master or replica based on the style of query usage.

Usage style;
I use the master connection (Port 5432) for INSERT, UPDATE, DELETE, TRANSACTIONS queries.
I use the replica connection (Port 5433) for SELECT queries.

The reason I want to extend the database library is that I manually intervene in the CodeIgniter core files.
When a new version of CodeIgniter is released, I have to repeatedly change the core files.

Example database connection ports;
Master: 5432
Replica: 5433 - multiple replica nodes.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
