### ISSUE TITLE
Displaying Error Page with 4.4 with PHP 8.3

### ISSUE THREAD

**Issue by demyr17** [codeigniter4/CodeIgniter4#8398]
### PHP Version

8.3

### CodeIgniter4 Version

4.4

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL

### What happened?

.env file is set to development but it doesn't display the error page. When I check the development.php file under Config/Boot I see that display_errors is already set to 1. Then, when I set display_errors to 1 in production.php, it shows the error page. However, in the error page there is no error listed. Plus, it detects environment as production.

PHP Version 8.3 (there was no option for this in the selectbox)

![CI-Error-php83-v44](https://github.com/codeigniter4/CodeIgniter4/assets/61029105/fdb38b9f-4426-414a-80a9-b70cd1c7d6b9)

BTW, I'm not posting for the security error there. I know, It's because of the CSRF data that I forgot. 

### Steps to Reproduce

nothing

### Expected Output

to be able to display the error page

**Comment by kenjis** [comment]
This is a bug.
Try this: #8399
