### ISSUE TITLE
Bug: [DebugBar] block by CSP

### ISSUE THREAD

**Issue by YapsBridging** [codeigniter4/CodeIgniter4#8405]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### What happened?

Debugbar use inline style ,  in mode development and CSPEnabled true will show many error in console browser

![Screenshot 2024-01-06 115033](https://github.com/codeigniter4/CodeIgniter4/assets/34118561/337ddfab-f839-4d74-b589-fad4c64a9310)

![Screenshot 2024-01-06 125259](https://github.com/codeigniter4/CodeIgniter4/assets/34118561/ce0320af-9c3e-4e54-a444-95fd5bad57a2)

### Steps to Reproduce

set  CSPEnabled = true, 
set ENVIRONMENT to development

### Expected Output

No error

**Comment by kenjis** [comment]
Thank you for reporting.
If you can fix these, please send a PR.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

**Comment by crustamet** [comment]
any update on this ? i would really love to have this update to the debugbar, so annoying with csp enabled.

**Comment by kenjis** [comment]
@crustamet See #8411
