### ISSUE TITLE
Checking if response is redirect

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#8408]
@kenjis Please CI 4 does not have isRedirection() for a response. 
I try adding this by extending the `Codeigniter\HTTP\Response` by adding this method.
```php
   /**
     * Check if the response is a redirection.
     *
     * @return bool
     */
    public function isRedirection(): bool
    {
        // Check if the status code is in the 300-399 range
        return ($this->getStatusCode() >= 300 && $this->getStatusCode() <= 399);
    }
```

So when I try this ```php response()->isRedirection()``` from the filter, library, controller etc. it does not work. I think this feature will be cool to me and other developers

**Comment by kenjis** [comment]
CI4 uses RedirectResponse for redirect.
https://codeigniter4.github.io/CodeIgniter4/outgoing/response.html#redirect
So if you want to redirect, you should use it,
and you can check it `

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
