### ISSUE TITLE
Bug: Uploaded Files user guide example uses deprecated validation method

### ISSUE THREAD

**Issue by stuart897** [codeigniter4/CodeIgniter4#8430]
### PHP Version

8.3

### CodeIgniter4 Version

4.4.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS, Windows, Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

In the documentation for [Uploaded Files](https://codeigniter.com/user_guide/libraries/uploaded_files.html#the-controller), the Controller example code uses `$this->validate()` which seems to be a deprecated method since 4.2.0. Should this code example be amended to use `$this->validateData()` instead?

### Steps to Reproduce

Read the user manual 

### Expected Output

Using the non-deprecated validation method

**Comment by kenjis** [comment]
`$this->validate()` is not deprecated, but it is very complex and may be not secure.
See https://codeigniter4.github.io/CodeIgniter4/incoming/controllers.html#this-validate

Do you think `$this->validate()` should be deprecated?

**Comment by stuart897** [comment]
My mistake, I saw the warning `This method exists only for backward compatibility. Do not use it in new projects.`  and took that to imply deprecation, I'm new to using CodeIgniter 4, currently updating an old CI 2 codebase to the latest version 4.

**Comment by kenjis** [comment]
If anyone sends a PR to update the code, I would appreciate it.
