### ISSUE TITLE
Dev: [SQLSRV] Forge maps ENUM to deprecated TEXT

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#8443]
CI version: 4.4

https://github.com/codeigniter4/CodeIgniter4/blob/28cf32b0fd3a758efd536f64e1a7dd14c1c33518/system/Database/SQLSRV/Forge.php#L326-L329

> Important
> The `ntext`, `text`, and `image` data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use [nvarchar(max)](https://learn.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver16), [varchar(max)](https://learn.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver16), and [varbinary(max)](https://learn.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-ver16) instead.
https://learn.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver16

**Comment by ISADPRO** [comment]
J

**Comment by kenjis** [comment]
Closed by #8478
