### ISSUE TITLE
Bug: request->getMethod is shown deprecated 

### ISSUE THREAD

**Issue by ZeyoYT** [codeigniter4/CodeIgniter4#8487]
### PHP Version

7.4, 8.0, 8.1, 8.2, 8.3

### CodeIgniter4 Version

4.4.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

cli

### What happened?

i was trying to see if the requesting method is post or get, but when i used it it was deprecated, i checked the docs and it was not, its a issue with the comments on getMethod, the upper parameter is deprecated not the method but due to comment on the method 

'@deprecated 4.0.5 The $upper functionality will be removed and this will revert to its PSR-7 equivalen' 

this makes the editor think the method is deprecated while its not

### Steps to Reproduce

no steps required to reproduce, its a bug with getMethod comment

### Expected Output

not marked deprecated by code editors

### Anything else?

i dont know how deprecate comments work as i am pretty new, so it might not be fixable

**Comment by kenjis** [comment]
Thank you for reporting., but it is intentional.
The purpose of the `@deprecated` is to let you know "The $upper functionality will be removed".

It was already removed in 4.5 branch, and will be removed in v4.5.0.
If it is a problem for you, try to use developing 4.5 branch.
https://github.com/codeigniter4/CodeIgniter4/tree/4.5

**Comment by kenjis** [comment]
- #4717
- #7334

**Comment by ZeyoYT** [comment]
> - #4717
> - #7334
> 
> 

I dont mean like that, the method it self is not deprecated, but esitor marks it deprecated, from what i understand this could not be fixed as i mentioned above

**Comment by kenjis** [comment]
Yes, you are correct. 
we cannot fix the issue. Our usage of `@deprecated` is not correct, but we don't know a better way.

And don't worry, probably you don't have any issues except your Editor shows it is deprecated.
