### ISSUE TITLE
Bug: DB result function incorrect result declaration

### ISSUE THREAD

**Issue by Turecky** [codeigniter4/CodeIgniter4#8501]
### PHP Version

8.3

### CodeIgniter4 Version

4.4.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MySQL

### What happened?

Database function `getCustomRowObject` declared return types as `@return array|null` but must return `object` as `custom class instance`

### Steps to Reproduce

Definition placed in `system/Database/ResultInterface.php`

### Expected Output

Return type must be an `object` of `custom class instance`

**Comment by kenjis** [comment]
Yes, the return type is an object.
https://codeigniter4.github.io/CodeIgniter4/database/results.html#custom-result-objects

I sent a PR to fix: #8503
