### ISSUE TITLE
base_url() default "scheme" (protocol) should be handled from the server if none provided

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#8511]
For the most part I am listening on both ports **443**, **80**

Yet i cannot manage to load all assets based on the listening port because of the **base_url()** that is set up in the **Config/App.php** let you choose only one protocol.
for example if i go to http://example.com all assets should be loaded under http protocol
and if i go to https://example.com all assets should be loaded under https protocol.

`
	
	namespace Config;

	use CodeIgniter\Config\BaseConfig;
	use CodeIgniter\Session\Handlers\FileHandler;

	class App extends BaseConfig
	{
		/**
		 * --------------------------------------------------------------------------
		 * Base Site URL
		 * --------------------------------------------------------------------------
		 *
		 * URL to your CodeIgniter root. Typically, this will be your base URL,
		 * WITH a trailing slash:
		 *
		 *    http://example.com/
		 */
		public string $baseURL = 'http://example.com';
	}
`

from my perspective if i remove the protocol from the `$baseURL` variable the protocol it should be handled automatically 
If i **use** this `$forceGlobalSecureRequests = FALSE;`

The only way that i could do this is if i changed the url_helper file or overwrite the base_url function 

`

	if (! function_exists('base_url')) {
		/**
		 * Returns the base URL as defined by the App config.
		 * Base URLs are trimmed site URLs without the index page.
		 *
		 * @param array|string $relativePath URI string or array of URI segments
		 * @param string|null  $scheme       URI scheme. E.g., http, ftp
		 */
		function base_url($relativePath = '', ?string $scheme = null): string
		{
			$currentURI = Services::request()->getUri();

			assert($currentURI instanceof SiteURI);
		
		// These two lines here ++
		//	if(!$scheme)
		//		$scheme = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http';

			return $currentURI->baseUrl($relativePath, $scheme);
		}
	}
	
`

I don't really like my approach to this one. 
I know it can be done somehow other way from the core

The point is that in base_url() function of the url_helper **$scheme** should be already equal to the protocol of the server if not forced manually when you call the function...

**$_SERVER['SERVER_PROTOCOL']** 
or 
**$_SERVER['REQUEST_SCHEME']**

How it is now:
Now the system is just forcing all **base_url** to use whatever is in the **Config/App.php** **$baseURL** variable, and if you must change the protocol you are forced to call all 
base_url('', 'https'); to load them, 
i am forced to change all my base_url in all my project to put the scheme manually

and when using 
`$forceGlobalSecureRequests = TRUE;` 

'https' should be present in the scheme of base_url()

**Comment by kenjis** [comment]
Try to use `base_url('', '')`.

**Comment by crustamet** [comment]
i have just checked by doing base_url('', '') and browsing the site with https:// its still outputs http://

for Example the problem is that if i go to https://example.com 
currentURI is equal to http://example.com

i cannot change the baseURL dynamically from the config

**Comment by crustamet** [comment]
and the other issue right, because i have changed the Config/App.php baseURL to only use https:// 
but now there is mixed content when loading assets :)

The conclusion is that i cannot have both without changing something from the core...

**Comment by kenjis** [comment]
The following code returns `//localhost:8080/ `.
```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index(): string
    {
        return base_url('', '');
    }
}
```

**Comment by crustamet** [comment]
and navigate now with https what it outputs ?

**Comment by crustamet** [comment]
the thing is what i'm talking about is that if you use both ports 443 and 80
and you navigate the website, what you have two configs with different baseURL's to make this work ?

**Comment by kenjis** [comment]
To begin with, mixing HTTP and HTTPS on a website is a bad practice.
See https://bard.google.com/share/109d2819bb58

**Comment by kenjis** [comment]
But in my understanding, if you use `base_url(..., '')` to generate all self links, it works.
If you navigate to `https://example.com/`, the link generated by `base_url()` will be `https://example.com/...`,
and if you navigate to `http://example.com/`, the link will be `http://example.com/...`,

**Comment by crustamet** [comment]
I know it is a bad practice... for mixing them but im only testing these configs on my local machine but that is not the problem im not mixing anything, im just listening on both ports

Codeigniter should not mix the content 
[Wanted functionality] **this functionality should work only if $forceGlobalSecureRequests = FALSE;** it works great if you use TRUE
 - if i browse to http base_url should be with http
 - and if i browse with https base_url should be https
This should work without changing the config of the codeigniter 



[Now functionality]
 Case 1 :
 in my config i set the protocol http
   so i navigate to http base_url is http
   and i navigate to https base_url is http     // this shows mixed content 
 
 Case 2:
 in my config i set the protocol https
  so i navigate to http base_url is https     // this shows mixed content if forceGlobalSecureRequests = FALSE
  and i vaigate to https base_url is https
  
And both cases are the same even if forceGlobalSecureRequests = True or FALSE because this only redirects to https

**Comment by crustamet** [comment]
I think this to make it to work is i just have to make two projects with two different configs right ?
so if connection come from 80 traffic get redirects to this project
and if connection come from 443 traffic get redirects to this other project
? this is what im asking

**Comment by crustamet** [comment]
> But in my understanding, if you use `base_url(..., '')` to generate all self links, it works. If you navigate to `https://example.com/`, the link generated by `base_url()` will be `https://example.com/...`, and if you navigate to `http://example.com/`, the link will be `http://example.com/...`,

wait... maybe im not checking it right...

**Comment by crustamet** [comment]
You are right this is working it removes the protocol xD i mean it forces the protocol to be nothing haha nice maneuver...

**Comment by crustamet** [comment]
No this is not good at all :))) well, the thing is now all base_url works but now the redirects are not working correctly

so if i have a form with https if i have in my baseURL the http version, the redirects goes from HTTPS to http LOL

**Comment by crustamet** [comment]
look here

[https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/HTTP/RedirectResponse.php#L55](url)

this needs to be changed return $this->redirect(site_url($route, ''), $method, $code);

if you say you have to put that instead

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
