### ISSUE TITLE
Database: DatabaseException on CLI Migration: "No such file or directory"

### ISSUE THREAD

**Issue by rkingbishnoi** [codeigniter4/CodeIgniter4#8528]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL

### What happened?

Hello

I've encountered an issue while working with CodeIgniter 4 and MAMP PRO on macOS, specifically when running migration commands via CodeIgniter's Spark CLI tool. I'm hoping to get some insights into whether this might be a known issue, a configuration problem, or a bug.

**Issue Description:**
When attempting to run database migrations using the PHP spark migrate command, I receive the following error:

```
CodeIgniter v4.4.5 Command Line Tool - Server Time: 2024-02-08 21:20:38 UTC+00:00

Running all new migrations...
[CodeIgniter\Database\Exceptions\DatabaseException]
Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
at SYSTEMPATH/Database/BaseConnection.php:428
```

However, database connections work as expected when accessed through the web server (e.g., via browser), and a plain PHP script using mysqli can successfully connect to the database.

### Steps to Reproduce

1. Set up a CodeIgniter 4 project on macOS using MAMP PRO as the local server environment.
2. Configure the database settings in app/Config/Database.php with MAMP PRO's MySQL credentials.
3. Run php spark migrate in the terminal.

### Expected Output

The migration command should successfully connect to the database and run any new migrations.

### Anything else?

**Actual Behavior:**
The command fails with a DatabaseException error indicating that it cannot connect to the database due to "No such file or directory", suggesting an issue with locating the MySQL socket file.

**Troubleshooting Attempts:**

1. Confirmed MySQL is running in MAMP PRO and accessible via PHP scripts run through the web server.
2. Checked php.ini configurations for CLI and web environments to ensure MySQLi extension is enabled and tried specifying the MySQL socket path.
3. Reached out to MAMP PRO support to clarify if this could be a configuration issue related to how MAMP PRO handles PHP CLI environments.

I'm curious if anyone else has encountered this issue or if there are recommended solutions or workarounds. Any help or guidance would be greatly appreciated.

Thank you for your time and assistance.

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/CodeIgniter4/issues/3359#issuecomment-660855438

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by rkingbishnoi** [comment]
I have tried everything but still its not working

**Comment by kenjis** [comment]
Are you using MAMP's `php` command?

```console
$ /Applications/MAMP/bin/php/php7.4.33/bin/php -v
PHP 7.4.33 (cli) (built: Dec  8 2022 20:04:08) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Comment by rkingbishnoi** [comment]
Yes , I am using PHP 8.2 , I tried to connect using plain php that is
working fine but not on CI4 through command line nor through controller

**Comment by kenjis** [comment]
Did you try? (the path may be different in your MAMP)
```console
$ /Applications/MAMP/bin/php/php8.2.0/bin/php spark migrate
```

**Comment by rkingbishnoi** [comment]
Yes, I did. but no result only same I am getting.

**Comment by kenjis** [comment]
> I tried to connect using plain php that is
working fine but not on CI4 through command line nor through controller

How did you run the plain php?
and how did you run the migration through controller?

**Comment by rkingbishnoi** [comment]
I just checked database connection is working or not through plain php and
ci controller , So through plain php its connected and through controller
not connected

**Comment by kenjis** [comment]
If I stop MAMP servers:
```console
$ /Applications/MAMP/bin/php/php8.2.0/bin/php spark db:table --show

CodeIgniter v4.4.5 Command Line Tool - Server Time: 2024-02-09 10:08:50 UTC+00:00

[CodeIgniter\Database\Exceptions\DatabaseException]
Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
at SYSTEMPATH/Database/BaseConnection.php:428

Backtrace:
  1    SYSTEMPATH/Database/BaseConnection.php:575
       CodeIgniter\Database\BaseConnection()->initialize()

  2    SYSTEMPATH/Database/BaseConnection.php:1410
       CodeIgniter\Database\BaseConnection()->query('SHOW TABLES FROM `mysql`')

  3    SYSTEMPATH/Commands/Database/ShowTableInfo.php:105
       CodeIgniter\Database\BaseConnection()->listTables()

  4    SYSTEMPATH/CLI/Commands.php:65
       CodeIgniter\Commands\Database\ShowTableInfo()->run([...])

  5    SYSTEMPATH/CLI/Console.php:46
       CodeIgniter\CLI\Commands()->run('db:table', [...])

  6    ROOTPATH/spark:102
       CodeIgniter\CLI\Console()->run()
```
But if I start MAMP servers:
```console
$ /Applications/MAMP/bin/php/php8.2.0/bin/php spark db:table --show

CodeIgniter v4.4.5 Command Line Tool - Server Time: 2024-02-09 10:09:57 UTC+00:00

The following is a list of the names of all database tables:

+----+---------------------------+-------------+---------------+
| ID | Table Name                | Num of Rows | Num of Fields |
+----+---------------------------+-------------+---------------+
| 1  | columns_priv              | 0           | 7             |
| 2  | db                        | 2           | 22            |
| 3  | engine_cost               | 2           | 6             |
| 4  | event                     | 0           | 22            |
| 5  | func                      | 0           | 4             |
| 6  | general_log               | 0           | 6             |
| 7  | gtid_executed             | 0           | 3             |
| 8  | help_category             | 40          | 4             |
| 9  | help_keyword              | 693         | 2             |
| 10 | help_relation             | 1406        | 2             |
| 11 | help_topic                | 637         | 6             |
| 12 | innodb_index_stats        | 7           | 8             |
| 13 | innodb_table_stats        | 2           | 6             |
| 14 | ndb_binlog_index          | 0           | 12            |
| 15 | plugin                    | 0           | 2             |
| 16 | proc                      | 48          | 20            |
| 17 | procs_priv                | 0           | 8             |
| 18 | proxies_priv              | 1           | 7             |
| 19 | server_cost               | 6           | 4             |
| 20 | servers                   | 0           | 9             |
| 21 | slave_master_info         | 0           | 25            |
| 22 | slave_relay_log_info      | 0           | 9             |
| 23 | slave_worker_info         | 0           | 13            |
| 24 | slow_log                  | 0           | 12            |
| 25 | tables_priv               | 2           | 8             |
| 26 | time_zone                 | 0           | 2             |
| 27 | time_zone_leap_second     | 0           | 2             |
| 28 | time_zone_name            | 0           | 2             |
| 29 | time_zone_transition      | 0           | 3             |
| 30 | time_zone_transition_type | 0           | 5             |
| 31 | user                      | 6           | 45            |
+----+---------------------------+-------------+---------------+
```

`.env`:
```
database.default.hostname = localhost
database.default.database = mysql
database.default.username = root
database.default.password = root
database.default.DBDriver = MySQLi
database.default.DBPrefix = 
database.default.port = 8889
```

**Comment by rkingbishnoi** [comment]
Yes with the full path of php now working fine migration through CLI, but I
wanna do it just with php spark migrate command so any suggestions?

If I test like php -v then the current PHP version is showing in the
terminal.

Thanks

**Comment by kenjis** [comment]
Go to https://forum.codeigniter.com/showthread.php?tid=89400

**Comment by thecnctech** [comment]
I am more or less facing the same problem
Running all new migrations...
[CodeIgniter\Database\Exceptions\DatabaseException]
Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
at SYSTEMPATH/Database/BaseConnection.php:457

Backtrace:
  1    SYSTEMPATH/Database/BaseConnection.php:604
       CodeIgniter\Database\BaseConnection()->initialize()

  2    SYSTEMPATH/Database/BaseConnection.php:1471
       CodeIgniter\Database\BaseConnection()->query('SHOW TABLES FROM `mysql`')

  3    SYSTEMPATH/Database/BaseConnection.php:1490
       CodeIgniter\Database\BaseConnection()->listTables()

  4    SYSTEMPATH/Database/MigrationRunner.php:759
       CodeIgniter\Database\BaseConnection()->tableExists('migrations')

  5    SYSTEMPATH/Database/MigrationRunner.php:163
       CodeIgniter\Database\MigrationRunner()->ensureTable()

  6    SYSTEMPATH/Commands/Database/Migrate.php:85
       CodeIgniter\Database\MigrationRunner()->latest(null)

  7    SYSTEMPATH/CLI/Commands.php:70
       CodeIgniter\Commands\Database\Migrate()->run([])

  8    SYSTEMPATH/CLI/Console.php:48
       CodeIgniter\CLI\Commands()->run('migrate', [])

  9    SYSTEMPATH/Boot.php:338
       CodeIgniter\CLI\Console()->run()

 10    SYSTEMPATH/Boot.php:104
       CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))

 11    ROOTPATH/spark:84
       CodeIgniter\Boot::bootSpark(Object(Config\Paths))
