### ISSUE TITLE
Printing Entity class objects prints unwanted information ?

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#8555]
While working with big data entities try to debug some stuff, i always see defaultCastHandlers, castHandlers, casts and the last one _cast.

On each entity i make, I see these properties... can't we remove them completely when printing them. 
It is so annoying to see a lot of data that I'm not interested in when printing.
I get that the original and current attributes you must see, even though the current attributes are enough when printing, if wanting to print the original we should implement a method to print them.

![image](https://github.com/codeigniter4/CodeIgniter4/assets/36475250/052d7efa-f121-4ef6-8c04-65544be6d467)

In this image i have not set **dates** properties so surely i must not see them.. i have no dates for this entity
For sure im not interested in seeing **defaultCastHandlers**

Isn't there a way for the codeigniter 4 team :D somehow to make those properties disappear when printing entities or to make maybe a method that prints those properties separately ?

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Entity/Entity.php
Every Entity has these properties. So if you print_r() or var_dump() it, they should be shown.

If you want to see only the current values in an Entity:
```php
dd($entity->toRawArray());
dd($entity->toArray());
```

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by crustamet** [comment]
Yes i know what you say but I'm not talking about that, i have notice a big difference in performance working with returnType as entity in Model, so im trying to figure out what loads so much into the memory, i have highlighted those to be the things that occupy so much.

Even though you can get them toRawArray() you still lost the speed as the class gets initialized with all the defaults.

from a 0.01 seconds to a 0.05 seconds, and this is only for one query model.. 

And sorry for my bad titles i always mess them up. 

The difference in speed i noticed when there like 100 items stored in memory as i needed the items in the hole project..

And when I have stored them as arrays they were completely fast.
Yes, and i dont want them as array because i want to have access to entity method, i pass the item trough the routes.

Im just pointing out that the massive speed difference in performance and i know for sure it can be optimized.

**Comment by kenjis** [comment]
This issue is about Entity's display during debugging, not about Entity's performance.

If you have a problem with Entity performance, please create another issue. 
Provide reproducible benchmarks.

**Comment by kenjis** [comment]
@crustamet Objects are generally slower than arrays.
See https://github.com/EFTEC/php-benchmarks?tab=readme-ov-file#benchmark-array-versus-object
