### ISSUE TITLE
Bug: max_dims validation error with SVG files

### ISSUE THREAD

**Issue by JordiGarciaEmex** [codeigniter4/CodeIgniter4#8591]
### PHP Version

8.1, 8.2

### CodeIgniter4 Version

4.2.6

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

macOS, Windows, Linux

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

When you try to use the Validation library, with an SVG image plus the max_dims rule, the function getimagesize tries to get the dimensions of the SVG image, but there are no dimensions for that type.

That returns a Trying to access array offset on value of type bool error in the line 245 in the FileRules.php file.

### Steps to Reproduce

Upload an SVG using the form validation rules with mime_in accepting SVG type and max_dims set.

### Expected Output

The function detects if there are dimensions in the uploaded image and if not, skip the getimagesize check.

**Comment by kenjis** [comment]
> The function detects if there are dimensions in the uploaded image and if not, skip the getimagesize check.

If the rule skips the check, it does not do anything. The validation rule should return false if the data is not valid.

**Comment by kenjis** [comment]
You should not check the size of SVG files with `max_dims`, since `getimagesize()` cannot get the size of them.
Create a custom rule for it.

I don't know if we should add an option to not check for SVG.

**Comment by JordiGarciaEmex** [comment]
Hello Kenjis, thanks for the quick response and for the code adjustment made.

We haven't created a custom rule for SVG images because we passed multiple images to the max_dims and mime_in rules. It's not really that the size of SVG images is fake, it's more that this type of image does not have this data, that is why an exception was thought of for SVG since, after all, it is a valid image format and existing.

Our code:

"$this->form_validation->setRules(
            [
                'multipleFiles' => [
                    'rules' => 'max_size[multipleFiles,' . $this->selected_domain_preferences->max_upload_size . ']|mime_in[multipleFiles,image/jpg,image/jpeg,image/gif,image/png,image/svg+xml]|max_dims[multipleFiles,3000,3000]',
                    'errors' => [
                        'max_size' => 'Check the size (max ' . $this->selected_domain_preferences->max_upload_size . 'kb)',
                        'mime_in' => 'Check the type',
                        'max_dims' => 'Check the dimensions (max 3000px)',
                    ],
                ]
            ]
        );"

We will try to make an exception on our side so we can upload these images separately from the max_dims check.

All the best.
