### ISSUE TITLE
Bug: RedirectResponse loses any previously set cookies

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#8606]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

fpm-fcgi

### What happened?

Working on an app using Shield and I noticed that the remember-me token was not being set. 

### Steps to Reproduce

```php
$response = service('response');

        $response->setCookie(
            setting('Auth.sessionConfig')['rememberCookieName'],
            $rawToken,                   
            setting('Auth.sessionConfig')['rememberLength'],    
            setting('Cookie.domain'),
            setting('Cookie.path'),
            setting('Cookie.prefix'),
            setting('Cookie.secure'),           
            true                                               
        );

return redirect()->back();
```

### Expected Output

The cookie should be set after the user is redirected. 

### Anything else?

Looks like this happens because `service('response')` returns a shared instance of `CodeIgniter\HTTP\Response`, while `service('redirectresponse')` returns a shared instance of `CodeIgniter\HTTP\RedirectResponse`. I feel like the redirect response should copy over any cookies and maybe even headers that exist on the shared Response object otherwise any information the app set on the response is lost when they perform a redirect.

**Comment by kenjis** [comment]
I don't know why CI4 was designed like that, but the behavior is not a bug.
> Warning
If you set Cookies or Response Headers before you call redirect(), they are set to the global response instance, and they are not automatically copied to the RedirectResponse instance. To send them, you need to call the withCookies() or withHeaders() method manually.
https://codeigniter4.github.io/CodeIgniter4/outgoing/response.html#redirect

See also:
- https://codeigniter4.github.io/CodeIgniter4/outgoing/response.html#redirect-with-cookies
- https://codeigniter4.github.io/CodeIgniter4/outgoing/response.html#redirect-with-headers

**Comment by lonnieezell** [comment]
Well, that's annoying. I had forgotten about that and missed those methods as I was looking through the code. Thanks.

**Comment by kenjis** [comment]
> The cookie should be set after the user is redirected.

I thought so too. And most CI3 users would agree.

Is there a use case where you want the cookies and/or headers you set to disappear?

**Comment by lonnieezell** [comment]
Not that I can really think of, but I suppose anything's possible....
