### ISSUE TITLE
Bug: [Model] Change in behavior of the save function since 4.4.4

### ISSUE THREAD

**Issue by unit-system-fr** [codeigniter4/CodeIgniter4#8613]
### PHP Version

8.3

### CodeIgniter4 Version

4.4.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli

### What happened?

When attempting to save an entity with an empty primary key using the 'save' function, the entity is not being saved. This is because the 'shouldUpdate' function incorrectly considers the entity as requiring an update, whereas it should be treated as an insert.

https://github.com/codeigniter4/CodeIgniter4/commit/d510a42d68453086b0be115925d40ac8867da992#diff-ba12fbd742529128a8b09aba62089ee5eb3eee77f00fa250853f52a85690f92dL732

### Steps to Reproduce

Using the 'save' function on an entity by specifying an empty value for its primary key.

```php
class TabRight extends Entity {

    protected $attributes = [
        'idTabRight' => null,
        'idTab' => null,
        'idRight' => null,
        'readOnly' => null
    ];

}
class TabRightModel extends Model {

    protected $table = 'base__tabs_rights';
    protected $primaryKey = 'idTabRight';
    protected $allowedFields = ['idRight', 'idTab', 'readOnly'];
    protected $returnType = \App\Entities\Base\TabRight::class;

}
$data = new \App\Entities\Base\TabRight();
$data = $this->request->getPost('data'); //HTML form
$tabRightModel = model('App\Models\Base\TabRightModel', true, $this->db);
$tabRightModel->save($data);
``` 

### Expected Output

When the primary key is provided but empty, we should still enter the insertion block as before.

```php
protected function shouldUpdate($row): bool
    {
        return ! empty($this->getIdValue($row));
    }
```

**Comment by kenjis** [comment]
Thank you for reporting.

What do you mean by empty? We don't use `emtpy()` because it is ambiguous.

**Comment by unit-system-fr** [comment]
Ok, I understood. According to me, the test of the empty string is missing to keep the same function as before

```php
return ! ($id === null || $id === [] || $id === '');
```

**Comment by kenjis** [comment]
Are you saying that the form has an id field and the data could be an empty string?

**Comment by kenjis** [comment]
I sent PR #8614

**Comment by unit-system-fr** [comment]
Yes, in my previous example, I have an HTML form with a hidden input field named 'idTabRight' which is populated when it's an update. Otherwise, the field is left empty.
The content of my POST request for a new record is:
```
csrf_unit_system | "f6737f0d46f3a2650af0bb3a3293e34cd862f2daa7d5a86c8c5c74af1ec8cdc3"
idTabRight | ""
idRight | "1"
idTab | "45"
readOnly | "0"
``` 

And for an update : 

```
csrf_unit_system | "f6737f0d46f3a2650af0bb3a3293e34cd862f2daa7d5a86c8c5c74af1ec8cdc3"
idTabRight | "38"
idRight | "1"
idTab | "38"
readOnly | "0"
```

Thx for PR
