### ISSUE TITLE
Bug: Debug toolbar hrefs redirect to /#

### ISSUE THREAD

**Issue by mihail-minkov** [codeigniter4/CodeIgniter4#8622]
### PHP Version

7.4, 8.1

### CodeIgniter4 Version

4.4.6

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 8

### What happened?

I use the toolbar to debug queries and variables. It's important for me to have it open in specific sections, but when I click on items on the toolbar instead of just toggling that section it interprets the click as a regular link click and since those links have # it always takes me to root/# and while the toolbar does re-open to where I clicked, I have to go back to where I was in order to review stuff.

This started recently, although not sure since which version.

### Steps to Reproduce

Toggle toolbar or Toggle a section inside the toolbar

### Expected Output

Toggled section instead of link redirect

**Comment by kenjis** [comment]
Duplicated of #8594

**Comment by kenjis** [comment]
This bug has already been fixed in `develop` branch.
Please try it.

If there is still something wrong, feel free to reopen this.
