### ISSUE TITLE
too much dependencies

### ISSUE THREAD

**Issue by itisjoby** [codeigniter4/CodeIgniter4#8630]
doing a composer install of codeigniter project is downloading and installing so much dependencies, been waiting for half hour for completing the installation. please reduce the dependency hell.

**Comment by kenjis** [comment]
If you don't use the default dev packages
```
    "require-dev": {
        "fakerphp/faker": "^1.9",
        "mikey179/vfsstream": "^1.6",
        "phpunit/phpunit": "^9.1"
    },
```

try:
```console
$ composer create-project codeigniter4/appstarter ci446 --no-dev
```

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
