### ISSUE TITLE
Bug: beforeDelete not getting data when used with query builder

### ISSUE THREAD

**Issue by jamisonricks** [codeigniter4/CodeIgniter4#8637]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.6

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

macOS, Linux

### Which server did you use?

apache

### Database

MySQL 5.7

### What happened?

Writing some tests for a `beforeDelete` callback function and when I use query builder, the callback's `$data` is empty. When I use delete directly, `$data` is populated with the id.

### Steps to Reproduce

Given this model's beforeDelete callback:

```php
  protected function removeFromSearch($data) {
    print_r($data);
  }
```

When I run this code:

```php
$gallery_model->where('id', $gallery['id'])->delete();
```

I get this output:

```
Array
(
    [id] =>
    [purge] =>
)
```

When I run this this code:

```php
$gallery_model->delete($gallery['id']);
```

I get this output:

```
Array
(
    [id] => Array
        (
            [0] => 79
        )

    [purge] =>
)
```

### Expected Output

I expect the output to be the same where the `$data` parameter is provided for the callback regardless of how `delete()` is called.

**Comment by kenjis** [comment]
This is not a bug.

> Important
The Model does not provide a perfect interface to the Query Builder. The Model and the Query Builder are separate classes with different purposes. They should not be expected to return the same data.
https://codeigniter4.github.io/CodeIgniter4/models/model.html#mixing-methods-of-query-builder-and-model
