### ISSUE TITLE
Bug: [SQLSRV] Query Builder always sets `"<database>"."<schema>".` to the table name

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#8697]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.7 and develop

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

SQLSRV

### What happened?

Query Builder always sets `"<database>"."<schema>".` to the table name.

E.g., `new SQLSRVBuilder('database.dbo.table', $this->db)` generates SQL statements with `FROM "test"."dbo"."database.dbo.table"`.

Why does SQLSRV always use table name with database and schema?
The behavior is only in SQLSRV.

### Steps to Reproduce

The following test fails:
```php
    public function testConstructorWithMultipleSegmentTableWithSQLSRV(): void
    {
        $this->db = new MockConnection(['DBDriver' => 'SQLSRV', 'database' => 'test', 'schema' => 'dbo']);

        $builder = new SQLSRVBuilder('database.dbo.table', $this->db);

        $expectedSQL = 'SELECT * FROM "database"."dbo"."table"';

        $this->assertSame($expectedSQL, str_replace("\n", ' ', $builder->getCompiledSelect()));
    }
```
```
Failed asserting that two strings are identical.
Expected :'SELECT * FROM "database"."dbo"."table"'
Actual   :'SELECT * FROM "test"."dbo"."database.dbo.table"'
```

### Expected Output

`SELECT * FROM "database"."dbo"."table"`

### Anything else?

The following test passes:
```php
    public function testConstructorWithMultipleSegmentTable(): void
    {
        $this->db = new MockConnection([]);

        $builder = new BaseBuilder('database.table', $this->db);

        $expectedSQL = 'SELECT * FROM "database"."table"';

        $this->assertSame($expectedSQL, str_replace("\n", ' ', $builder->getCompiledSelect()));
    }
```

**Comment by ping-yee** [comment]
```php
public function testFromWithMultipleTablesAsStringWithSQLSRV(): void
    {
        $this->db = new MockConnection(['DBDriver' => 'SQLSRV', 'database' => 'test', 'schema' => 'dbo']);

        $builder = new SQLSRVBuilder('user', $this->db);

        $builder->from(['jobs, roles']);

        $expectedSQL = 'SELECT * FROM "test"."dbo"."user", "test"."dbo"."jobs", "test"."dbo"."roles"';

        $this->assertSame($expectedSQL, str_replace("\n", ' ', $builder->getCompiledSelect()));
    }
```

It seems it will auto generate the database and schema at the before design.

**Comment by ping-yee** [comment]
```php
public function testFromWithMultipleTablesAsStringWithSQLSRV(): void
    {
        $this->db = new MockConnection(['DBDriver' => 'SQLSRV', 'database' => 'test', 'schema' => 'dbo']);

        $builder = new SQLSRVBuilder('user', $this->db);

        $builder->from(['jobs, roles']);

        $expectedSQL = 'SELECT * FROM "test"."dbo"."user", "test"."dbo"."jobs", "test"."dbo"."roles"';

        $this->assertSame($expectedSQL, str_replace("\n", ' ', $builder->getCompiledSelect()));
    }
```

It seems that the database and schema are automatically generated by the builder when the first parameter, $table, does not include the database and schema information at the before design.

So does the behavior need to be changed? It probably will be a breaking change.

```php
public function testConstructorWithMultipleSegmentTableWithSQLSRV(): void
    {
        $this->db = new MockConnection(['DBDriver' => 'SQLSRV', 'database' => 'test', 'schema' => 'dbo']);

        $builder = new SQLSRVBuilder('database.dbo.table', $this->db);

        $expectedSQL = 'SELECT * FROM "database"."dbo"."table"';

        $this->assertSame($expectedSQL, str_replace("\n", ' ', $builder->getCompiledSelect()));
    }
```

And the MockConnection's database param is different with builder in your test case, is the exception `"database"."dbo"."table"` correct? or it will be  `"test"."dbo"."table"`.

**Comment by kenjis** [comment]
MySQL does not support schema. So that is `database.table`. `database.dbo.table` is impossible.
I just showed the SQLSRV's behavior is different from other drivers.

**Comment by ping-yee** [comment]
I have implemented the solution to handle this behavior without changing the original behavior, review please.

**Comment by kenjis** [comment]
@ping-yee My question is why does only SQLSRV need to add `"<database>"."<schema>".`?

**Comment by ping-yee** [comment]
In SQL Server, a 'schema' is used to organize and separate data within the same database, allowing management of multiple logical entities. This helps in setting different access permissions and distinguishing tables and other objects by department, project, or functionality.

See https://stackoverflow.com/questions/2221929/what-is-the-importance-of-schema-in-sql-server

In many other databases, such as MySQL, the concepts of 'database' and 'schema' are often considered synonymous. Each database essentially serves as a separate logical environment where tables and other database objects are stored.

**Comment by kenjis** [comment]
There is no code like `getFullName()` in CI3 sqlsrv.
Why does CI4 need it?
See 
- https://github.com/bcit-ci/CodeIgniter/tree/develop/system/database/drivers/sqlsrv
- https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_query_builder.php

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/CodeIgniter4/pull/8786#issuecomment-2089379521
