### ISSUE TITLE
Pager does not remove queryString from uri when pager is set to work on segments

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#8698]
Basically i've set up the pager to work on segments.

but the pages actually retain queryString from uri if i go to 

https://example.com/blog/2?page=2

When the PagerRenderer kicks in it should remove ?page=2 from the query string when recreating the pager links

https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Pager/PagerRenderer.php#L265
I have changed this function like this

```php
    public function links(): array
    {
        $links = [];

        $uri = clone $this->uri;

        for ($i = $this->first; $i <= $this->last; $i++) {
            $uri     = $this->segment === 0 ? $uri->addQuery($this->pageSelector, $i) : $uri->setSegment($this->segment, $i);
            $links[] = [
                'uri' => URI::createURIString(
                    $uri->getScheme(),
                    $uri->getAuthority(),
                    $uri->getPath(),
                    $uri->getQuery(['except' => ['page']]), // actualy it should only retain queryString that is not page
                    $uri->getFragment()
                ),
                'title'  => $i,
                'active' => ($i === $this->current),
            ];
        }

        return $links;
    }
```

But this implementation approach should only work when pager is set up on segments instead of query string.
This works for me for now but when I switch back to using the pager as before, for sure with this approach will not work.

My Feature request is to add this option to the **Pager Config**

**Comment by kenjis** [comment]
If you want to control Query String, see https://codeigniter4.github.io/CodeIgniter4/libraries/pagination.html#paginating-with-only-expected-queries

**Comment by crustamet** [comment]
Yeah i know this exists but it does not remove whatever Query Strings are in the url.

i did this 

**$Pager->only([])->links();** // this meaning, i want to remove any query string

so for this to work as i intended i have to put something in the **only(['test'])** method 
but if i have the string test in the query, now it keeps test and i don't want to

but if i have anything in the query it still puts it on the links.

What i want is to remove all the query strings from the url when building the links


for ex:
example.com/blog/2?page=2
example.com/blog/2?test=2
example.com/blog/2?asf=2

when im hovering the page 3 it keeps the query strings in the url when building links

**Comment by kenjis** [comment]
Oh, you are correct. `$pager->only([])->links()` does not work.
Try #8702

**Comment by crustamet** [comment]
i approved the pager modifications, i have tested, and works perfectly, all good.
