### ISSUE TITLE
Bug: Model:chunk() seems to be returning single entries

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#8712]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MySQL

### What happened?

Trying to loop over all active users in the system and process it in chunks of 100. I expected the value passed into the Closure to be an array of users. Instead, I'm getting a single user record each time. There's only 12 users in the sample data that match the criteria but this shouldn't affect things. 

I set the chunk size smaller than the dataset to verify and it is doing the same thing. 

I also changed the resultType of the UserModel to be a simple array to see if it was related to assigning custom classes and it is not. 

### Steps to Reproduce

```php 
model(UserModel::class)
            ->chunk(100, static function ($users)) {
                // `$users` is a single `User` record here
            });
```

### Expected Output

I expect that `$users` within the closure should be an array of up to 100 users.

**Comment by kenjis** [comment]
@lonnieezell This is not a bug because it is clearly documented.

```php
$userModel->chunk(100, static function ($data) {
    // do something.
    // $data is a single row of data.
});
```
https://codeigniter4.github.io/CodeIgniter4/models/model.html#processing-large-amounts-of-data

But I don't think the behavior is good. However changing it will be a breaking change.

**Comment by lonnieezell** [comment]
Hmm, I don't think that's the way I originally implemented it but it's too late now, as you say. 

Looking over the code it does at least still retrieve them all in a single query but it's very un-intuitive the way it works now. If I'm telling it I want a chunk of 100 rows I would expect to have access to all 100 rows. 

At least it's not completely losing the efficiency that method is supposed to provide. 

Thanks. I'll close.
