### ISSUE TITLE
Bug: [DebugBar] 4.5.0 TypeError: str_contains(): Argument #1 ($haystack) must be of type string, null given

### ISSUE THREAD

**Issue by iamsyh** [codeigniter4/CodeIgniter4#8730]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.0

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

Mysql 8

### What happened?

When defining a custom filter in app/Config/Filters.php with specific URI patterns and using the codeigniter4/shield package for authentication, the Debug Toolbar throws a TypeError if the filter triggers a redirect. This issue seems to arise from how the Debug Toolbar processes responses, particularly when a controller or filter returns a non-standard response or null.
    
![Screenshot 2024-04-09 at 03-37-37 TypeError](https://github.com/codeigniter4/CodeIgniter4/assets/5077021/1fcd9b4b-ddd4-4a84-b68f-7c5dfb50e98c)

### Steps to Reproduce

1. In app/Config/Filters.php, define a before filter rule for specific paths, excluding some with a regex pattern, as shown below:
`public array $filters = [
    'session' => [
        'before' => [
            '^myadminendpoint(?!/login|/register|/auth/a/)([a-zA-Z0-9/-]+)?$',
        ]
    ]
];`
2. Ensure the before filter (e.g., session filter from codeigniter4/shield) is configured to return a redirect under certain conditions.
3. Access a URL that matches the filter's criteria and triggers the redirect.

### Expected Output

The application should redirect to the specified location without any errors, even with the Debug Toolbar enabled.

### Workaround

Temporarily removing the Debug Toolbar from the $globals and $required arrays in the after filters configuration resolves the issue.

**Comment by kenjis** [comment]
Try #8727

**Comment by DPComp** [comment]
When will this be online in master for download / update?

**Comment by samsonasik** [comment]
It will done when it done.

You can use develop branch while wait for new release https://codeigniter.com/user_guide/installation/installing_composer.html#latest-dev and help us give more feedback in case of any regression.
