### ISSUE TITLE
Bug: [CURLRequest] Setting default Content-Type in HTTP\Response cause to multiple headers in response

### ISSUE THREAD

**Issue by warmbook** [codeigniter4/CodeIgniter4#8750]
### PHP Version

8.1

### CodeIgniter4 Version

4.5.0

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### What happened?

When I try to call getHeaderLine in a curlrequest response, it throw an exception with the message 'The header content-type already has multiple headers...'.  By viewing the code, I found it's caused by the default content-type in HTTP\Response.
In curlrequest's method setResponseHeaders, the program just call addHeader to save content-type responsed from the remote server to the property response, it won't override the default value 'text/html' set in system\HTTP\Response.php at line 170.
So is the default value necessary?

### Steps to Reproduce

```php
$mime = \Config\Services::curlrequest(['http_errors'=>FALSE],NULL,NULL,FALSE)
        ->get($url)->getHeaderLine('Content-Type');
```

### Expected Output

$mime should be a string

**Comment by kenjis** [comment]
Thank you for reporting. I confirmed the following error:

> InvalidArgumentException
>
>The header "Content-Type" already has multiple headers. You cannot use getHeaderLine().

Please try #8760.
