### ISSUE TITLE
Bug: form_open with no URL supplied

### ISSUE THREAD

**Issue by richard-keasley** [codeigniter4/CodeIgniter4#8752]
### PHP Version

8.1

### CodeIgniter4 Version

4.5.0

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

When using the helper form_open() with no URL, an error is thrown:
str_contains(): Argument #1 ($haystack) must be of type string, CodeIgniter\HTTP\SiteURI given

### Steps to Reproduce

```
echo form_open();
```

### Expected Output

I expect the `current_url(false)` (a string) to be used as a URL. 

form_helper, line 34
`$action = current_url(true);`
returns a CodeIgniter\HTTP\SiteURI

**Comment by datamweb** [comment]
This bug has already been fixed. See number #8736

duplicate #8729

**Comment by kenjis** [comment]
> I expect the current_url(false) (a string) to be used as a URL.

It is not true. `current_url(false)` and `(string) current_url(true)` are different.
