### ISSUE TITLE
Bug: `service('example')` null return if service is defined in the custom namespace in Manual Installation CI4.5.0

### ISSUE THREAD

**Issue by datamweb** [codeigniter4/CodeIgniter4#8755]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.0

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

---

### What happened?

`null `value is returned!

### Steps to Reproduce

step1: Manually install version CI4.50.
step 2: add new namespace:
```php
    public $psr4 = [
        APP_NAMESPACE => APPPATH,
        'Shield' => APPPATH . 'ThirdParty\Shield'
    ];
```
step3: Create your own class (**Shield\Example**):
```php
<?php
namespace Shield;

class Example {

    public $test = 'testVal';
}
```
step4: Create your own service(**Shield\Config\Services.php**):

```php
<?php

namespace Shield\Config;

use CodeIgniter\Config\BaseService;

class Services extends BaseService
{
      public static function example($getShared = true)
      {
          if ($getShared) {
              return static::getSharedInstance('example');
          }
     
          return new \Shield\Example();
      }
}
```
step5: use exampel service :

```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        $exampleService= service('example');

        dd($exampleService);
       
    }
}

```

`null `value is returned!

### Expected Output

My class must be returned. ($exampleService Shield\Example).

### Anything else?

The problem is only in manual installation.

**Comment by krishna-gujjjar** [comment]
Hey @datamweb, 
can you tell me how to solve this issue because i am also getting it after upgrade codeigniter v4.4.7 to v4.5.1
It was working fine before but as soon as i made changes describe in the upgrading guide, all custom services return null

**Comment by datamweb** [comment]
Hey @krishna-gujjjar,

The reason I closed this issue was because I could not reproduce the problem.

I don't have this problem now and I don't know what fixed it.
