### ISSUE TITLE
Official User Guide is not updated

### ISSUE THREAD

**Issue by Terrorboy** [codeigniter4/CodeIgniter4#8757]
### PHP Version

8.3

### CodeIgniter4 Version

4.4.5 ~ 4.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

The user manual on the official site doesn't seem to be updated.

![CleanShot 2024-04-11 at 10 29 53](https://github.com/codeigniter4/CodeIgniter4/assets/5427199/407bbfac-4501-4463-aa1d-04cb80f692c2)
![CleanShot 2024-04-11 at 10 28 17](https://github.com/codeigniter4/CodeIgniter4/assets/5427199/75d4668c-64d8-42c8-8d1c-db9be1019e3e)

### Steps to Reproduce

The user manual on the official site doesn't seem to be updated.

- https://codeigniter.com/user_guide/installation/upgrading.html

### Expected Output

Update history doesn't exist

**Comment by kenjis** [comment]
Sorry for the inconvenience.
We seem to be short on server admins.
See #8725

Please see the User Guide on the GitHub:
https://codeigniter4.github.io/userguide/
or the current in-progress (`develop` branch) User Guide:
https://codeigniter4.github.io/CodeIgniter4/
