### ISSUE TITLE
Bug: [Postgre] Unable to connect to the database

### ISSUE THREAD

**Issue by warcooft** [codeigniter4/CodeIgniter4#8771]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

PostgreSQL 15.4

### What happened?

I have followed the documentation regarding database configuration. [https://codeigniter.com/user_guide/datab...tion.html#](https://codeigniter.com/user_guide/database/configuration.html#)

here my db config:
```php
public array $default = [
        'DSN'          => 'Postgre://username:password@hostname:5432/database?charset=utf8&connect_timeout=5&sslmode=1',
        'hostname'     => 'localhost',
        'username'     => 'postgres',
        'password'     => '123456',
        'database'     => 'playground_db',
        'DBDriver'     => 'Postgre',
        'DBPrefix'     => '',
        'pConnect'     => false,
        'DBDebug'      => true,
        'charset'      => 'utf8mb4',
        'DBCollat'     => 'utf8mb4_general_ci',
        'swapPre'      => '',
        'encrypt'      => false,
        'compress'     => false,
        'strictOn'     => false,
        'failover'     => [],
        'port'         => 5432,
        'numberNative' => false,
        'dateFormat'   => [
            'date'     => 'Y-m-d',
            'datetime' => 'Y-m-d H:i:s',
            'time'     => 'H:i:s',
        ],
    ];
``` 

and then i got this error:

`Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: invalid sslmode value: &quot;1&quot;`

Here details:
[https://postimg.cc/bGf6Kmfw](https://postimg.cc/bGf6Kmfw)

### Steps to Reproduce

I have applied the above configuration to the .env file in Codeigniter 4.4.8 and it works fine, but why doesn't it work in Codeigniter 4.5.0? Previously I tried to apply it in .env exactly with version 4.4.8 but it didn't work. Lastly, I configured it in the Config\Database.php file and it also didn't work.

### Expected Output

-

**Comment by kenjis** [comment]
> The values accepted by pg_connect's sslmode argument are: disable, allow, prefer, require
https://www.php.net/manual/ja/function.pg-connect.php#51767

**Comment by kenjis** [comment]
> I have applied the above configuration to the .env file in Codeigniter 4.4.8 and it works fine

> Previously I tried to apply it in .env exactly with version 4.4.8 but it didn't work. 

In v4.4.8, the configuration worked or not?

**Comment by warcooft** [comment]
> > I have applied the above configuration to the .env file in Codeigniter 4.4.8 and it works fine
> 
> > Previously I tried to apply it in .env exactly with version 4.4.8 but it didn't work. 
> 
> In v4.4.8, the configuration worked or not?

Worked

**Comment by warcooft** [comment]
I try sample database connection for Postgre in Database config and now worked, Thanks @kenjis

**Comment by kenjis** [comment]
Yes, now we have "Sample database connection for Postgre":
CodeIgniter4/app/Config/Database.php at develop · codeigniter4/CodeIgniter4
https://github.com/codeigniter4/CodeIgniter4/blob/04394c6f0f34c7350ad845a147f4949da6522aa8/app/Config/Database.php#L74-L99
