### ISSUE TITLE
Bug: getInsertID is only returning 0 when using the Save() method

### ISSUE THREAD

**Issue by SupremeSimon** [codeigniter4/CodeIgniter4#8799]
### PHP Version

8.2

### CodeIgniter4 Version

4.4.6

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 8.0

### What happened?

We use class models for a number of database management functions.

We have used the save function to handle both inserting and updating of records.

```php
if (!$address_model->save($address)){
    $this->error_class->add_error("Save failed [address_model]", "Something went wrong when saving, please see error(s) below:");
    $this->error_class->add_error_array($address_model->errors());
    $this->db->transRollback();
    return 0;
}
```

If the record was inserted, we then get the ID that was inserted to run a couple more DB functions.

```php
$address->address_id = $address_model->getInsertID();
```

This seems to only be returning a 0 value now since updating.

I've found no reference to that change in the change log, but I could just have missed it.

### Steps to Reproduce

Create a model and "save_records" function (or whatever you want to name it).
Use the save() function and pass it some data that would force it to insert data rather than update.
Output the getInsertID() result.  This is what for us is now returning 0 values.

### Expected Output

I would expect it to return the ID that was inserted into the DB.

### Anything else?

The work around we are currently having to use is 

to check if we have an primary key id, then calling the insert or update function separately which works fine.

I was running version 1.3.7 before upgrading to 1.4.6.  So this occurred somewhere between those two versions.

**Comment by kenjis** [comment]
Cannot reproduce with CI 4.5.1.

I see `int(5)`:
```php
    public function testInsertID(): void
    {
        $data = [
            'name'        => 'Apprentice',
            'description' => 'That thing you do.',
        ];

        $this->createModel(JobModel::class);
        $this->model->protect(false)->save($data);

        $lastInsertId = $this->model->getInsertID();
        var_dump($lastInsertId); exit;

        $this->seeInDatabase('job', ['id' => $lastInsertId]);
    }
```

**Comment by kenjis** [comment]
> The work around we are currently having to use is
to check if we have an primary key id, then calling the insert or update function separately which works fine.

I don't know why the workaround is needed, because it is what the save() method does:
https://github.com/codeigniter4/CodeIgniter4/blob/c66cae8c0588cc909f547548169f973d19b954c3/system/BaseModel.php#L742-L759

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
