### ISSUE TITLE
Bug: CI4 + Shield + Postgre Spark error

### ISSUE THREAD

**Issue by bchapot** [codeigniter4/CodeIgniter4#8800]
### PHP Version

8.3

### CodeIgniter4 Version

4.4.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

FreeBSD 13

### Which server did you use?

apache

### Database

PostgreSQL 16

### What happened?

On FreeBSD 13 CI 4.4.5 + shield work well with Postgre (after having recreated the db schema from the Mysql version with pgload) but `spark migrate:status` returns this error :

`Unable to connect to the database
Main connection [Postgre]: call to undefined function CodeIgniter\Database\Postgre\pg_connect() 
at SYSTEMPATH/Database/BaseConnection.php:428`

### Steps to Reproduce

Install CI4 and Shield with composer,
Create some users and test register & login OK
Set a new db with Postgre using DSN setting in .env
Create and feed the postgre db with data
Change default db
Test register login etc ok
Try use spark and get the error.

### Expected Output

php spark migrate:status

**Comment by kenjis** [comment]
Install/enable pgsql.
See https://www.php.net/manual/en/pgsql.installation.php

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by bchapot** [comment]
"Test register login etc ok" means web ui is working so pgsql is well installed.

**Comment by kenjis** [comment]
PHP for web and PHP for CLI are different.
Install pgsql in PHP for CLI.
