### ISSUE TITLE
Bug: [Model] when the query ($this->first()) result returns NULL we get TypeError

### ISSUE THREAD

**Issue by avegacms** [codeigniter4/CodeIgniter4#8806]
### PHP Version

8.1, 8.2

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MariaDB 10.2

### What happened?

When the query result returns NULL we get TypeError
![CI bug](https://github.com/codeigniter4/CodeIgniter4/assets/49051631/48c15353-6203-4dc4-9922-f05ca5ec4930)
I am using  CodeIgniter’s Model + Casts + return type object)

### Steps to Reproduce

Run some query with `$this->first()`

### Expected Output

return NULL

**Comment by neznaika0** [comment]
I get the same error. Checking for NULL solves the problem (in this case)

**Comment by kenjis** [comment]
Try #8871
