### ISSUE TITLE
Bug: Invalid date format for ORACLE database for created_at and updated_at

### ISSUE THREAD

**Issue by allyblaise** [codeigniter4/CodeIgniter4#8810]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

ORACLE 19c

### What happened?

Invalid datetime format for oracle 19c

ErrorException: oci_execute(): ORA-01843: not a valid month in ../vendor/codeigniter4/framework/system/Database/OCI8/Connection.php:201

### Steps to Reproduce

Try to insert or update data into a table with $useTimestamps=true on model

### Expected Output

insert or update records on oracle db

**Comment by kenjis** [comment]
The `dateFormat` is user configuration.
If the default value is not fit your need, just you change it.
