### ISSUE TITLE
How to add CI4 in a raw project and use the database class?

### ISSUE THREAD

**Issue by sr13579** [codeigniter4/CodeIgniter4#8826]
I would like to have something like eloquent that I can fuse with any framework and use the database class. Is it possible? I asked in the forum but found no answer. If this is not the right place to ask please help me where to ask?

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by sr13579** [comment]
> We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

In forum I couldn't get a reliable answer. You gave me an answer there but it is not working with the latest version. How to find a solution for this? You can remove my post if you want.
