### ISSUE TITLE
Bug: force_https

### ISSUE THREAD

**Issue by byazrail** [codeigniter4/CodeIgniter4#8834]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

PostgreSQL

### What happened?

I was using it for https redirection on a non-https page.
I get this error on the 404 page or the page defined on the normal route.

### Steps to Reproduce

```php
            if (!is_cli() AND !$this->request->isSecure())
            {
				force_https();
            }
```

### Expected Output

CRITICAL - 2024-04-28 02:59:10 --> CodeIgniter\HTTP\Exceptions\RedirectException: 
[Method: GET, Route: /]
in SYSTEMPATH/Common.php on line 504.
 1 APPPATH/Controllers/Core/CoreController.php(233): force_https()
 2 APPPATH/Controllers/Core/SiteController.php(23): App\Controllers\Core\CoreController->initController()
 3 ROOTPATH/ThirdParty/Site/Controllers/Site.php(12): App\Controllers\Core\SiteController->initController()
 4 SYSTEMPATH/CodeIgniter.php(904): Site\Controllers\Site->initController()
 5 SYSTEMPATH/CodeIgniter.php(963): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH/CodeIgniter.php(364): CodeIgniter\CodeIgniter->display404errors()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(128): CodeIgniter\Boot::bootWeb()

**Comment by byazrail** [comment]
This error 4.4.3 old version.

`CRITICAL - 2024-04-28 00:15:53 --> 
in SYSTEMPATH/Common.php on line 531.
 1 APPPATH/Controllers/Core/CoreController.php(233): force_https()
 2 APPPATH/Controllers/Core/SiteController.php(23): App\Controllers\Core\CoreController->initController()
 3 ROOTPATH/ThirdParty/Site/Controllers/Site.php(12): App\Controllers\Core\SiteController->initController()
 4 SYSTEMPATH/CodeIgniter.php(915): Site\Controllers\Site->initController()
 5 SYSTEMPATH/CodeIgniter.php(970): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH/CodeIgniter.php(370): CodeIgniter\CodeIgniter->display404errors()
 7 FCPATH/index.php(135): CodeIgniter\CodeIgniter->run()`

Because of this problem, I updated to 4.5.1 verison, but I still encounter the same problem.

**Comment by kenjis** [comment]
Cannot reproduce.

I got the following response header:
```
HTTP/1.1 307 Temporary Redirect
Host: localhost:8080
Date: Sun, 28 Apr 2024 00:24:04 GMT
Connection: close
X-Powered-By: PHP/8.1.28
Cache-Control: no-store, max-age=0, no-cache
Content-Type: text/html; charset=UTF-8
Strict-Transport-Security: max-age=31536000
Location: https://localhost:8080/index.php/
```

```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        if (! is_cli() && ! $this->request->isSecure()) {
            force_https();
        }
    }
}
```

**Comment by byazrail** [comment]
Used;

`<?php
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger)
    {
        // Do Not Edit This Line
        parent::initController($request, $response, $logger);

            if (!is_cli() AND !$this->request->isSecure())
            {
                force_https();
            }
    }
`

**Comment by kenjis** [comment]
Cannot reproduce.

```php
<?php

namespace App\Controllers;

use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Home extends BaseController
{
    public function index(): string
    {
        return view('welcome_message');
    }

    public function initController(
        RequestInterface $request,
        ResponseInterface $response,
        LoggerInterface $logger
    ) {
        parent::initController($request, $response, $logger);

        if (! is_cli() && ! $this->request->isSecure()) {
            force_https();
        }
    }
}
```

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by byazrail** [comment]
Yes, this is how I use it.
I use it called CoreController instead of BaseController.
It wasn't just an abstract class.
Former;
class CoreController extends \CodeIgniter\Controller
New;
abstract class CoreController extends \CodeIgniter\Controller

Could this be caused by this situation?
It doesn't always give the error.

**Comment by kenjis** [comment]
Ah, I got it. You are using `$override404` and the 404 controller calls `force_https()`.
Don't call  `force_https()` in the 404 controller.

**Comment by byazrail** [comment]
Yes, I use 404 Override. This problem occurs on 404 pages.
This wasn't a problem before.
