### ISSUE TITLE
The lang function exposes the name of your language file if there is no record.

### ISSUE THREAD

**Issue by mywebmanavgat** [codeigniter4/CodeIgniter4#8835]
lang('Home.title');

If there is no title key in the array in Languages/Home.php, lang will return this.
“Home.title”

is the expected return of the “title”.

**Comment by kenjis** [comment]
Yes.

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
