### ISSUE TITLE
Bug: Error when run php spark cmd in testing env

### ISSUE THREAD

**Issue by shishamo** [codeigniter4/CodeIgniter4#8837]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

PostgreSQL 15.2

### What happened?

When try to run any spark command in testing environment, error is send as below : 

```
PHP Fatal error:  Uncaught Error: Undefined constant "CodeIgniter\Config\SUPPORTPATH" in /var/www/src/system/Config/AutoloadConfig.php:144
Stack trace:
#0 /var/www/src/system/Boot.php(231): CodeIgniter\Config\AutoloadConfig->__construct()
#1 /var/www/src/system/Boot.php(96): CodeIgniter\Boot::loadAutoloader()
#2 /var/www/src/spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#3 {main}
  thrown in /var/www/src/system/Config/AutoloadConfig.php on line 144

Fatal error: Uncaught Error: Undefined constant "CodeIgniter\Config\SUPPORTPATH" in /var/www/src/system/Config/AutoloadConfig.php:144
Stack trace:
#0 /var/www/src/system/Boot.php(231): CodeIgniter\Config\AutoloadConfig->__construct()
#1 /var/www/src/system/Boot.php(96): CodeIgniter\Boot::loadAutoloader()
#2 /var/www/src/spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#3 {main}
  thrown in /var/www/src/system/Config/AutoloadConfig.php on line 144
```

### Steps to Reproduce

Set the env file `CI_ENVIRONMENT` as `testing`

Run a spark command

`php spark env`

### Expected Output

The command should start properly

**Comment by kenjis** [comment]
This is not a bug, but a misuse.

> The environment testing is reserved for PHPUnit testing. It has special conditions built into the framework at various places to assist with that. You can’t use it for your development.
https://codeigniter4.github.io/CodeIgniter4/general/environments.html#the-defined-environments

**Comment by shishamo** [comment]
I understand thank you.
