### ISSUE TITLE
Bug: [DatetimeCast] Invalid parameter: nullable

### ISSUE THREAD

**Issue by neznaika0** [codeigniter4/CodeIgniter4#8860]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MariaDB 10

### What happened?

Conversion to date does not work.

### Steps to Reproduce

Add Model:
```php
class UserModel extends Model
{
    protected $table         = 'user';
    protected $primaryKey    = 'id';
    protected $allowedFields = [
        'first_name',
        'date_birth'
    ];
    protected $returnType     = User::class;
    protected array $casts = [
        'id' => '?int',
        'date_birth' => '?datetime'
    ];
}
```
Select row from DB (get User object):
`$this->userModel->get($userId);`
See error:
```
InvalidArgumentException
Invalid parameter: nullable search →

SYSTEMPATH/DataCaster/Cast/DatetimeCast.php at line 50
```

### Expected Output

Return Datetime object or null

### Anything else?

I think it's worth considering $params[0] = 'nullable' state
https://github.com/codeigniter4/CodeIgniter4/blob/84e06d06b67b0bc8bea71dfa24f93264eec50b19/system/DataCaster/Cast/DatetimeCast.php#L46C1-L51
```php
        $format = match ($params[0] ?? '') {
            ''      => $helper->dateFormat['datetime'],
            // 'nullable' => $helper->dateFormat['datetime'],
            'ms'    => $helper->dateFormat['datetime-ms'],
            'us'    => $helper->dateFormat['datetime-us'],
            default => throw new InvalidArgumentException('Invalid parameter: ' . $params[0]),
        };
```

**Comment by neznaika0** [comment]
It would also be nice to add other time types for DatetimeCast.
```php
'date'        => 'Y-m-d',
'time'        => 'H:i:s',
```

**Comment by neznaika0** [comment]
In the process, a question:
If _$attributes_ (_$original_) if the entities have a string value, then casting fails. **DatetimeCast** expects an object, but actually contains `$attributes['date_birth'] = '2001-05-03 19:56:00`
```
 App\Models\Entity\User {#160 ▼
  #datamap: []
  #dates: []
  #casts: []
  #castHandlers: []
  -defaultCastHandlers: array:15 [▶]
  #attributes: array:22 [▼
    "id" => "1"
    "date_birth" => "2001-05-03 19:56:00"
  ]
```

**Comment by kenjis** [comment]
Try #8870
