### ISSUE TITLE
Bug: CLI class, method promptByMultipleKeys() - default $input is of wrong type

### ISSUE THREAD

**Issue by gh-mash** [codeigniter4/CodeIgniter4#8861]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

n/a

### What happened?

The method of the **CLI** class:
`CodeIgniter\CLI\CLI::promptByMultipleKeys()`
contains a bug where the default `$input` is set as `0` _(int)_ instead of `'0'` _(string)_

When this function is used and no input is provided, it will cause a `TypeError` when trying to do a `trim($input)`

PHP file `SYSTEMPATH\CLI\CLI.php`, line 333

### Steps to Reproduce

Code sample (from CI user guide):

```php
<?php
use CodeIgniter\CLI\CLI;
$hobbies = CLI::promptByMultipleKeys('Select your hobbies:', ['Playing game', 'Sleep', 'Badminton']);

```

When executed, and when no input is provided, just Enter is pressed (a.k.a selecting the default (first) option), the `TypeError` is thrown:
```
[TypeError]
trim(): Argument #1 ($string) must be of type string, int given
at SYSTEMPATH\CLI\CLI.php:337
```

### Expected Output

`SYSTEMPATH\CLI\CLI.php`, line 333:

Old (bug):
`$input = static::prompt($extraOutput) ?: 0; // 0 is default`
New (fixed):
`$input = static::prompt($extraOutput) ?: '0'; // '0' is default`

**Comment by kenjis** [comment]
Try  #8873
