### ISSUE TITLE
Bug: Can not header reponse as file image 

### ISSUE THREAD

**Issue by geewebid** [codeigniter4/CodeIgniter4#8869]
### PHP Version

8.1

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL

### What happened?

i use this code 
$this->response->setHeader('Cache-Control', 'max-age=600, s-maxage=900, must-revalidate');
$this->response->setHeader('Content-Type', "image/png, charset=UTF-8");
$this->response->setHeader('Content-Length', filesize($filename));
return @readfile($filename);

"It returns as a broken image, but it works well for files like CSS or JavaScript. Specifically for SVG files, it works well when I add the flush() code. However, it doesn't work for JPG, PNG, or other image formats. When I checked with 'view source', the file has a broken line space on the first line, which I think is causing the problem.

### Steps to Reproduce

--

### Expected Output

its not working well in prev version like 4.4

**Comment by kenjis** [comment]
> Returns the number of bytes read from the file on success, or [false](https://www.php.net/manual/en/reserved.constants.php#constant.false) on failure
https://www.php.net/manual/en/function.readfile.php#refsect1-function.readfile-returnvalues

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
