### ISSUE TITLE
Bug: [View Cells] Too few arguments to function App\Cells\MyClass::myMethod(), 0 passed in

### ISSUE THREAD

**Issue by warcooft** [codeigniter4/CodeIgniter4#8872]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

PostgreSQL 15.4

### What happened?

I tried to implement View Cells in my project, but the parameters I sent were still not accepted by the method. the system still responds `Too few arguments to function App\Cells\MyClassCell::myMethod(), 0 passed in`

but when trying to remove the 
```php
extends Cell
```  
from the `MyClassCell` class, View Cells works properly.

I followed these instructions:

https://codeigniter.com/user_guide/outgoing/view_cells.html#simple-cells

apart from the Simple Cells sample it doesn't work.

### Steps to Reproduce

generate view cell from cli `php spark make:cell MyClass`
it reproduce this code:
```php
<?php

namespace App\Cells;

use CodeIgniter\View\Cells\Cell;

class MyClassCell extends Cell
{
    //
}
``` 
then i create this method :
```php
<?php

namespace App\Cells;

use CodeIgniter\View\Cells\Cell;

class MyClassCell extends Cell
{
    public function myMethod(array $params): array
    {
        dd($params);
    }

``` 

in view, i call my View Cells like this:

```php
<?= view_cell('App\Cells\MyClassCell::myMethod', ['key1' =>  'val1']) ?>

``` 

### Expected Output

array dump results based on the parameters i sent from view cell.

### Anything else?

view cell works properly when I remove the part of the Class
```php
extends Cell 
```
but not working with extends cell

**Comment by neznaika0** [comment]
You are using the cells incorrectly. There are two different options. You're trying to mix both. 

This is a forum question, not a fix.

```php
<?php

namespace App\Cells;

use CodeIgniter\View\Cells\Cell;

class MyClassCell extends Cell
{
    public $key1;
}
```

```php
<div>
    Cell View <?= $this->key1 ?>
</div>
```

```php
    public function index()
    {
        echo view_cell('MyClassCell', ['key1' =>  'val1']);
    }
```

**Comment by kenjis** [comment]
If you specify a method like this, it is a Simple Cell.
```php
<?= view_cell('App\Cells\MyClassCell::myMethod', ['key1' =>  'val1']) ?>
```

You don't specify a method name when you use Controlled Cells.
See the sample code in https://codeigniter.com/user_guide/outgoing/view_cells.html#calling-a-view-cell.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
