### ISSUE TITLE
Bug: language fallback doesn't kick in if message if empty

### ISSUE THREAD

**Issue by BudsieBuds** [codeigniter4/CodeIgniter4#8875]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MariaDB 10.5

### What happened?

The language fallback doesn't kick in if the message after the language key is empty.

### Steps to Reproduce

**Example 1:**
app/Language/en/Login.php
```php
<?php
return [
	"email" => "Email",
	"password" => "Password",
	"username" => "Username",
];
```

app/Language/_any-language_/Login.php
```php
<?php
return [
	"email" => "",
	"username" => "Nameuser",
];
```

app/Views/login.php
```php
<?= lang('Login.username') ?> & <?= lang('Login.password') ?> & <?= lang('Login.email') ?>
```

**Example 2 (nested):**
app/Language/en/Login.php
```php
<?php
return [
	"app_name" => "CodeIgniter",
	"welcome" => "Welcome {0}!",
];
```

app/Language/any-language/Login.php
```php
<?php
return [
	"app_name" => "",
	"welcome" => "Welcome {0}!",
];
```

app/Views/login.php
```php
<?= lang('Login.welcome', [lang('Login.app_name')]) ?>
```

**Example 3 (nested):**
app/Language/en/Login.php
```php
<?php
return [
	"app_name" => "CodeIgniter",
	"welcome" => "Welcome {0}!",
];
```

app/Language/any-language/Login.php
```php
<?php
return [
	"app_name" => "",
	"welcome" => "",
];
```

app/Views/login.php
```php
<?= lang('Login.welcome', [lang('Login.app_name')]) ?>
```

### Expected Output

If language is set to _any-language_.

**Example 1:**
`<?= lang('Login.username') ?> & <?= lang('Login.password') ?> & <?= lang('Login.email') ?>`
Expected output: `Nameuser & Password & Email`
Actual output: `Nameuser & Password &  `

**Example 2:**
`<?= lang('Login.welcome', [lang('Login.app_name')]) ?>`
Expected output: `Welcome CodeIgniter!`
Actual output: `Welcome !`

**Example 3:**
`<?= lang('Login.welcome', [lang('Login.app_name')]) ?>`
Expected output: `Welcome CodeIgniter!`
Actual output: `【Warning】Also, invalid string(s) was passed to the Language class. See log file for details.`
Warning because the placeholder isn't taken from English to pass the second parameter.

### Anything else?

Adding this example code to `codeigniter4/framework/system/Common.php` solves the first and second example, the third one throws the same error because the placeholder isn't found.
```php
if (! function_exists('lang')) {

...

        $lines = $language->getLine($line, $args);

        // Example code start
        if (empty($lines)) {
            $language->setLocale('en');
            $englishLines = $language->getLine($line, $args);

            if (is_array($lines)) {
                foreach ($lines as $key => $value) {
                    if (empty($value)) {
                        $lines[$key] = $englishLines[$key] ?? '';
                    }
                }
            } else if (empty($lines)) {
                $lines = $englishLines;
            }

            $language->setLocale($activeLocale);
        }
        // Example code end

        if ($locale && $locale !== $activeLocale) {
            // Reset to active locale
            $language->setLocale($activeLocale);
        }

        return $lines;
    }
}
````

**Comment by kenjis** [comment]
> You only need to provide values for those messages that would be localized differently for that locale variant. Any missing message definitions will be automatically pulled from the main locale settings.
https://codeigniter4.github.io/CodeIgniter4/outgoing/localization.html#language-fallback

If there is a key in a localized lang file, it will be used.
You set empty strings. So these empty strings are used.
Why is it necessary to fall back?

**Comment by BudsieBuds** [comment]
The reason for the language files with empty strings is because they're put in a Weblate instance used for community translations. These strings remain empty until they are translated by community members.
In CI3, the system would fall back to English even when the strings were empty. I was expecting the same behavior in CI4, hence I thought it was a bug.

**Comment by kenjis** [comment]
> In CI3, the system would fall back to English even when the strings were empty.

How to reproduce?
It seems there is no Language Fallback in CI3.
https://www.codeigniter.com/userguide3/libraries/language.html

**Comment by michalsn** [comment]
> In CI3, the system would fall back to English even when the strings were empty.

That is not true. The fallback will only occur if the language key in question does not exist.
Another explanation is that you have modified the default behavior in CI3 with the `MY_Lang` class.

**Comment by BudsieBuds** [comment]
You're right, I thought I did my research. The default behavior was overwritten. Thanks for your comments!
