### ISSUE TITLE
Bug: Credit card validation does not work with multiple card

### ISSUE THREAD

**Issue by samuelesantoni** [codeigniter4/CodeIgniter4#8901]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### What happened?

Credit card validation does not work with multiple card:
`'cardNumber' => [
        'label' => lang('App.label_credit_card_number'),
        'rules' => 'required|valid_cc_number[visa,mastercard]',
],`

I receive an error from `$this->validator->listErrors()`: `Validation.valid_cc_number`

If add a custom error:
`'cardNumber' => [
        'label' => lang('App.label_credit_card_number'),
        'rules' => 'required|valid_cc_number[visa,mastercard]',
        'errors' => [
            'valid_cc_number' => 'credit card number invalid.',
        ],`

in `$this->validator->listErrors()`: I can see the string: credit card number invalid, but I receive always an error.

### Steps to Reproduce

1) Create a form with an input text. 
2) Create a controller, for example for send an email, with a credit card validation. Something like: `valid_cc_number[visa,mastercard,discover]`.

### Expected Output

The validation of more type of credit card.

**Comment by kenjis** [comment]
This is not a bug.
The `valid_cc_number` rule does not accept multiple types.
https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#rules-for-general-use
