### ISSUE TITLE
Bug: postgre can not connect to database error

### ISSUE THREAD

**Issue by rjwmtgevolution** [codeigniter4/CodeIgniter4#8903]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

postgres 15.7

### What happened?

brand new installation 
composer create-project codeigniter4/appstarter adminportal2
setup my database connection in .env file
put in the following command 
php spark db:table

tried to connect to my database and I get  the following error
[CodeIgniter\Database\Exceptions\DatabaseException]
Unable to connect to the database.

at SYSTEMPATH/Database/BaseConnection.php:457

### Steps to Reproduce

brand new installation 
composer create-project codeigniter4/appstarter adminportal2
setup my database connection in .env file
put in the following command 
php spark db:table

### Expected Output

listing of tables

### Anything else?

I have another codeigniter4 application using the same postgres instance but a different database
I am able to run php spark db:table with no errors and I get a list of tables to select
this application is running codeigniter 4.4.7

**Comment by datamweb** [comment]
Please provide database(Postgre) configuration file **.env**.

**Comment by rjwmtgevolution** [comment]
Thank you for the quick response

below is my database connection in the .env file

database.default.hostname = localhost
database.default.database = admin_portal
database.default.username = admin2_dbuser
database.default.password = password
database.default.DBDriver = Postgre
# database.default.DBPrefix =
database.default.port = 5432

**Comment by rjwmtgevolution** [comment]
I can connect to the database via psql with no errors

If I go into the index.php in the public folder and put in a manual connection using pg_connect(). I can connect to the database successfully

**Comment by kenjis** [comment]
Show the full error message.

**Comment by rjwmtgevolution** [comment]
see below

CodeIgniter v4.5.1 Command Line Tool - Server Time: 2024-05-19 00:57:14 UTC+00:00

+-----------+--------------+---------------+----------+----------+------+
| hostname  | database     | username      | DBDriver | DBPrefix | port |
+-----------+--------------+---------------+----------+----------+------+
| localhost | admin_portal | admin2_dbuser | Postgre  |          | 5432 |
+-----------+--------------+---------------+----------+----------+------+

[CodeIgniter\Database\Exceptions\DatabaseException]
Unable to connect to the database.

at SYSTEMPATH/Database/BaseConnection.php:457

Backtrace:
  1    SYSTEMPATH/Database/BaseConnection.php:604
       CodeIgniter\Database\BaseConnection()->initialize()

  2    SYSTEMPATH/Database/BaseConnection.php:1471
       CodeIgniter\Database\BaseConnection()->query()

  3    SYSTEMPATH/Commands/Database/ShowTableInfo.php:120
       CodeIgniter\Database\BaseConnection()->listTables()

  4    SYSTEMPATH/CLI/Commands.php:70
       CodeIgniter\Commands\Database\ShowTableInfo()->run()

  5    SYSTEMPATH/CLI/Console.php:48
       CodeIgniter\CLI\Commands()->run()

  6    SYSTEMPATH/Boot.php:338
       CodeIgniter\CLI\Console()->run()

  7    SYSTEMPATH/Boot.php:104
       CodeIgniter\Boot::runCommand()

  8    ROOTPATH/spark:84
       CodeIgniter\Boot::bootSpark()

**Comment by rjwmtgevolution** [comment]
command issued

php spark db:table

**Comment by kenjis** [comment]
I don't know why you get the error.
But try to update the Database config file with the following sample setting:
https://github.com/codeigniter4/CodeIgniter4/blob/8fc89854cc85c3b002ce2b26d5de56f6fa131166/app/Config/Database.php#L79-L99

**Comment by rjwmtgevolution** [comment]
ok, I will check now

**Comment by rjwmtgevolution** [comment]
that worked, thank you

I am not excited about this because this will get saved in the repo. 

how can I put this in the .env file

**Comment by rjwmtgevolution** [comment]
the issue has to do with the array at the bottom of the dateformat

'dateFormat'   => [
            'date'     => 'Y-m-d',
            'datetime' => 'Y-m-d H:i:s',
            'time'     => 'H:i:s',
        ],

**Comment by rjwmtgevolution** [comment]
I got it to work. 

I used the Database configuration for Postgre but stored the credentials in the .env file

Thank you

**Comment by kenjis** [comment]
Yes, it is recommended to configure in the Database configuration file as much as possible.
Set items only that really need to change for environments in the `.env` 

I found the true cause.
See https://github.com/codeigniter4/CodeIgniter4/issues/8912#issuecomment-2130601960
