### ISSUE TITLE
Bug: [Error] Call to undefined method Config\Mimes::__set_state() at ROOTPATH/writable/cache/FactoriesCache_config

### ISSUE THREAD

**Issue by gbanc** [codeigniter4/CodeIgniter4#8914]
### PHP Version

8.3

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

Postgres

### What happened?

Codeigniter caching is causing issues, at first new migrations were not being run because the new files were not being cached/autoloaded into writable/cache/FileLocatorCache was not being updated. Deleting FileLocatorCache fixed that issue. However now a similar error cropped up, this time in FactoriesCache_config at Config\Mimes::__set_state(), because Mimes has no method __set_state(). Deleteing FactoriesCache_config does not fix this

### Steps to Reproduce

Create a view that uses mimes, e.g.   "allowed_mime_types" => config('Mimes')::$mimes['csv'],

### Expected Output

app/Config/Mimes should extend BaseConfig ? // Cached classes work as expected

**Comment by kenjis** [comment]
This is not a bug.

> Important
> Using this feature when the prerequisites are not met will prevent CodeIgniter from operating properly. Do not use this feature in such cases.
https://codeigniter4.github.io/CodeIgniter4/concepts/factories.html#prerequisite

**Comment by kenjis** [comment]
Use `new Mimes()` instead of `config('Mimes')`.
Because `config()` is slow., there is no benefit to use `config()` for `Mimes`.

Also, `Mimes` extending `BaseConfig` makes the instantiation of `Mimes` very slow. 
That is not the way to go.

**Comment by gbanc** [comment]
Either way, codeigniter factories does not work out-of-the-box with Config/Mimes.php, because it does not implement __set_state()

From your link to the docs: "By default, every Config class that is cached must implement __set_state() method."
So one would expect that the default implementation of Config/Mimes.php should implement __set_state() no?

**Comment by kenjis** [comment]
> Either way, codeigniter factories does not work out-of-the-box with Config/Mimes.php, because it does not implement __set_state()

True, you cannot use Config caching with `Config\Mimes`.
It is intentional, because we don't need to cache it.

> So one would expect that the default implementation of Config/Mimes.php should implement __set_state() no?

No.
It means, if you want to cache a Config class instance, the class must implement __set_state() method. `Config\Mimes` does not implement it, so you cannot cache it by default.

If the explanations in the user guide are not clear, please read the source code and understand how the Config caching works, and provide suggestions for improvement.

Config cache is an additional feature for experts who need any better performance. 
We recommend that users who cannot troubleshoot on their own not use it.

Also, if you use caching, we recommend that you measure whether the caching is really effective.

**Comment by gbanc** [comment]
So, if Config/Mimes doesn't need to be cached, then why is it being included by default when enabling config caching?

Its common sense that if one enables a feature in the framework, one would expect it to work with its own default system files. I did not explicitly configure it to cache Config/Mimes, it does it on its own, out-of-the-box. Which breaks. 

I would simply update the user guide to say: "Enabling this will not work by default, You have to manually override Config/Mimes and add __set_state method yourself"

**Comment by kenjis** [comment]
> So, if Config/Mimes doesn't need to be cached, then why is it being included by default when enabling config caching?

It is not included by default. You intentionally did it by calling `config('Mimes')`.

> Enabling this will not work by default, You have to manually override Config/Mimes and add __set_state method yourself

This is incorrect. You should not cache it. In other words, you should not call `config('Mimes')`. If you do not call `config()`, `Config/Mimes` has nothing to do with Config Caching.

**Comment by gbanc** [comment]
Fair enough, makes sense. Thanks for your patience
