### ISSUE TITLE
Bug: Entity Standalone Class initialization error

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#8924]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

I have created a Entity File that are not linked to a database table
i initialize the entity with some data
and wanted to echo some of the data

![image](https://github.com/codeigniter4/CodeIgniter4/assets/36475250/44084dc9-b574-4320-bf67-490a26542fc8)

### Steps to Reproduce

	class Example extends Entity
	{
		protected $attributes = [
			'test' => NULL,
			'test2' => NULL,
			'test3' => NULL,
		];
		
		public function __construct($test, $test2, $test3)
		{
			$this->attributes['test'] = $test;
			$this->attributes['test2'] = $test2;
			$this->attributes['test3'] = $test3;
		}
	}
	
	// in my contorller
	use App\Entities\Example;
	
	$Example = new Example('test', 'test2', 'test3');
	
	echo $Example->test;

### Expected Output

should echo 'test';

**Comment by crustamet** [comment]
I kinda overwrite the __construct method for the Entity class there.

    public function __construct(?array $data = null)
    {
        $this->dataCaster = new DataCaster(
            array_merge($this->defaultCastHandlers, $this->castHandlers),
            null,
            null,
            false
        );

        $this->syncOriginal();

        $this->fill($data);
    }

The point is i wanted to initialize some attributes based on some options, and i didn't want to write two lines of codes for this like this

    $Example = new Example();
    $Example->initialize('test', 'test2', 'test3');
    
    
it worked in the constructor aswell if i put 

	public function __construct($ipAddress)
	{
		$this->cast(FALSE);

		$this->attributes['test'] = $test;
		$this->attributes['test2'] = $test2;
		$this->attributes['test3'] = $test3;
	}

**Comment by kenjis** [comment]
This is not a bug. Your code is just wrong.

You have two options
- If you extend CI4's Entity, call the parent constructor in the constructor.
- Write your own Entity as you wish and use it.
