### ISSUE TITLE
Bug: storing validation rules in Config/Validation causes error

### ISSUE THREAD

**Issue by lazaruscorporation** [codeigniter4/CodeIgniter4#8937]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

Following the instructions at https://codeigniter.com/user_guide/libraries/validation.html#saving-sets-of-validation-rules-to-the-config-file I saved the following in App/Config/Validation.php (I initially tried with my own array, but then used the array from the documentation in case I'd made a typo):

``` 
public array $signup = [
        'username'     => 'required|max_length[30]',
        'password'     => 'required|max_length[255]',
        'pass_confirm' => 'required|max_length[255]|matches[password]',
        'email'        => 'required|max_length[254]|valid_email',
    ];
```

This immediately made all pages return this error: 

Cannot assign null to property Config\Validation::$signup of type array 

### Steps to Reproduce

Following instrictions above

### Expected Output

No error  (the validation rules were not yet being called from anywhere in the code)

**Comment by kenjis** [comment]
Cannot reproduce.
