### ISSUE TITLE
Bug: system/Database/OCI8/Connection.php fails to parse valid DSN

### ISSUE THREAD

**Issue by jdpurdyvi** [codeigniter4/CodeIgniter4#8984]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.2

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

Oracle 

### What happened?

Some valid DSN strings fail the isValidDSN() method, meaning that the $validDSNs['tsn'] regex is too strict in its check.

### Steps to Reproduce

Try the DSN `(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.world)(PROTOCOL=TCP)(Host=dbodsprod.is.colostate.edu)(Port=1521)))(CONNECT_DATA=(SERVICE_NAME=odsprod.infosys.colostate.edu)))` 

### Expected Output

`preg_match($validDSNs['tsn'])` returns true which causes `isValidDSN()` to return true which causes Connection->connect() to return a a valid resource

**Comment by kenjis** [comment]
Hi, the `$validDSNs['tsn']` regex has no problem.
See https://3v4l.org/h0Xt4

What's your exact issue?

**Comment by jdpurdyvi** [comment]
Thanks @kenjis . I was debugging this incorrectly. 
At line 123 of system/Database/OCI8/Connection.php `if (empty($this->DSN) && ! $this->isValidDSN()) {`
`$this->DSN` is `NULL` for me, which causes the preg_match to fail.
If I change line 108 to `if (preg_match($regexp, $this->DSN??'')) {` the connection works

**Comment by kenjis** [comment]
It seems `$this->DSN` in  `isValidDSN()` is always an empty string `''` or `null`.
The first `if` condition should be `! empty($this->DSN) && ! $this->isValidDSN()` ?
https://github.com/codeigniter4/CodeIgniter4/blob/53bfdef9f2b0370d8ca49ef068778a6839a8ed22/system/Database/OCI8/Connection.php#L123-L125
https://github.com/codeigniter4/CodeIgniter4/blob/53bfdef9f2b0370d8ca49ef068778a6839a8ed22/system/Database/OCI8/Connection.php#L105-L114

**Comment by kenjis** [comment]
@jdpurdyvi How do you configure `Config\Database`?

**Comment by jdpurdyvi** [comment]
The database connection is configured using a `.env` file. There is no line for `database.xyz.DSN`. 

I'm not sure that changing line 123 solves the issue. I tried that change and got an exception of `Main connection [OCI8]: oci_connect(): ORA-12162: TNS:net service name is incorrectly specified`. I think the call to `buildDSN()` is still needed... 🫠

**Comment by kenjis** [comment]
At first, don't use `.env` if you cannot connect the database.
After debugging, use `.env`.

See also
https://github.com/codeigniter4/CodeIgniter4/blob/53bfdef9f2b0370d8ca49ef068778a6839a8ed22/app/Config/Database.php#L129-L156

**Comment by jdpurdyvi** [comment]
Thanks. I will adjust my database connection setup.

In the meantime, if you can assume that "`$this->DSN in isValidDSN() is always an empty string '' or null.`" and we know that `preg_match` does not accept null as the 2nd parameter, why not check for null with the null coalesce operator?

**Comment by kenjis** [comment]
@jdpurdyvi Try #8986

**Comment by kenjis** [comment]
Closed by #8986

**Comment by jdpurdyvi** [comment]
Apologies for the delay. https://github.com/codeigniter4/CodeIgniter4/pull/8986 works in my env. Thanks!
