### ISSUE TITLE
Bug(OCI8): $validDSNs regex for Oracle service names should support periods

### ISSUE THREAD

**Issue by rutgers-master** [codeigniter4/CodeIgniter4#9005]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

Recent changes to OCI8/Connection.php:
https://github.com/codeigniter4/CodeIgniter4/commit/99346b48aa0b8bdb8b491f640d27640091de95a8

Cause the `$this->buildDSN();` function to get called now which exposes an issue (for me) with the `protected $validDSNs` .  The Oracle DSNs that I use contains a service name with periods, for example our DSN is something like `//host:port/my.service` which fails the `$validDSNs` check.

If the "ec" (Easy Connect) regex gets a period added to the service name part of the regex, it fixes the issue, currently the $validDSNs is:
```php
    protected $validDSNs = [
        'tns' => '/^\(DESCRIPTION=(\(.+\)){2,}\)$/', // TNS
        // Easy Connect string (Oracle 10g+)
        'ec' => '/^(\/\/)?[a-z0-9.:_-]+(:[1-9][0-9]{0,4})?(\/[a-z0-9$_]+)?(:[^\/])?(\/[a-z0-9$_]+)?$/i',
        'in' => '/^[a-z0-9$_]+$/i', // Instance name (defined in tnsnames.ora)
    ];
```
Change the 'ec' one to include a period and that fixes the issue:
` 'ec' => '/^(\/\/)?[a-z0-9.:_-]+(:[1-9][0-9]{0,4})?(\/[a-z0-9$_]+)?(:[^\/])?(\/[a-z0-9.$_]+)?$/i',`

### Steps to Reproduce

Set an Oracle database connection in CI4 to use a service name with a period, like `//host:port/my.service`, it will fail this part of the code in Connection.php (by "fail" I mean, it won't return true):
```php
        foreach ($this->validDSNs as $regexp) {
            if (preg_match($regexp, $this->DSN)) {
                return true;
            }
        }
```

### Expected Output

A DSN like `//host:port/my.service` should be considered valid.

**Comment by kenjis** [comment]
Thank you for reporting!
Please check #9006.
