### ISSUE TITLE
Validation `valid_date` does not work with time

### ISSUE THREAD

**Issue by motoroller1983** [codeigniter4/CodeIgniter4#9016]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Do validation 
```php
'end' => [
            'label'	=> ' ',
            'rules' => 'permit_empty|valid_date[H:i]'
        ],
```

### Steps to Reproduce

when i send ens value is 24:00 is not validations

### Expected Output

its should be validate

**Comment by datamweb** [comment]
Fails if field does not contain a **valid date** NOT **valid Time**.


https://github.com/codeigniter4/CodeIgniter4/blob/bab88287086c61af29314c59a40ce77ee0b5f8f0/system/Validation/FormatRules.php#L438-L472

Checks for a valid date and matches a **given date format** .

What is date format?
 see https://www.php.net/manual/en/datetime.formats.php#datetime.formats.date

**Comment by kenjis** [comment]
This is a misuse.
`valid_date` can validate only a date. `24:00` is not a date.
