### ISSUE TITLE
Bug: validation level dont work as expected

### ISSUE THREAD

**Issue by mozzar** [codeigniter4/CodeIgniter4#9022]
### PHP Version

8.3

### CodeIgniter4 Version

5.0.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

MariaDB 10.6.18 

### What happened?
Validation does not work at higher levels of the array
look at the screenshot of my rules:
![obraz](https://github.com/codeigniter4/CodeIgniter4/assets/40978856/beee7c45-02f8-47f7-a788-a81b9993adb2)

here is my request:
![obraz](https://github.com/codeigniter4/CodeIgniter4/assets/40978856/c7c86e8b-8f5d-4c0e-85af-15551ed7e153)

and here is validation:
![obraz](https://github.com/codeigniter4/CodeIgniter4/assets/40978856/5f5638fe-c0ad-4064-8270-4f9954d52ad3)

### Steps to Reproduce

create rules, eg:
```php
$rules = [
            'cards' => 'required',
            'cards.*.fields' => 'required',
            'cards.*.fields.*' => 'required',
        ];
```
create json body for request:
```php
$body = '{
  "cards": [
    {
      "fields": {"name": "name"}
    }
]
}';
```

write validate code:
```php
$validation = service('validation');
$validation->setRules($rules);
 if (!$validation->run(json_decode($body, true))) {
            // handle validation errors
            print_r($validation->getErrors());
}
```

### Expected Output

Validation should not show an error. Unless there are no "fields"

### Anything else?

thanks.

**Comment by kenjis** [comment]
Thank you for reporting.

Please use the following format in the future.

<pre>
```php
// PHP code
```
</pre>

**Comment by kenjis** [comment]
In your sample data, there is no `cards.*.fields` field.

```php
        $body = '{"cards": [{"fields": {"name": "name"}}]}';
        $data = json_decode($body, true);
        var_dump(array_flatten_with_dots($data));
```

```
array (size=1)
  'cards.0.fields.name' => string 'name' (length=4)
```

**Comment by kenjis** [comment]
@mozzar Can you describe the format of the data that you want to validate?

Also, there is a known bug #8006 in Validation with `*`.

**Comment by mozzar** [comment]
> @mozzar Can you describe the format of the data that you want to validate?
> 
> Also, there is a known bug #8006 in Validation with `*`.



> In your sample data, there is no `cards.*.fields` field.
> 
> ```
>         $body = '{"cards": [{"fields": {"name": "name"}}]}';
>         $data = json_decode($body, true);
>         var_dump(array_flatten_with_dots($data));
> ```
> 
> ```
> array (size=1)
>   'cards.0.fields.name' => string 'name' (length=4)
> ```

so I can't validate that key "fields" exists?

here is my data dumped with var_dump:
```php 
array(1) {
  ["cards"]=>
  array(1) {
    [0]=>
    array(1) {
      ["fields"]=>
      array(1) {
        ["name"]=>
        string(4) "name"
      }
    }
  }
}
```

**Comment by kenjis** [comment]
The data is:
```
'cards.0.fields.name' => 'value'
```
If all data is like that, you can write the validation rule:
```
[
    'cards.0.fields.name' => 'required',
]
```

> so I can't validate that key "fields" exists?

You can use the rule `field_exists`.

**Comment by mozzar** [comment]
> The data is:
> 
> ```
> 'cards.0.fields.name' => 'value'
> ```
> 
> If all data is like that, you can write the validation rule:
> 
> ```
> [
>     'cards.0.fields.name' => 'required',
> ]
> ```
> 
> > so I can't validate that key "fields" exists?
> 
> You can use the rule `field_exists`.

I edited my previous comment, yes it fixes my problem.
sorry for the unnecessary post.
I will close this issue.
