### ISSUE TITLE
Bug: Class 'file' not found in SYSTEMPATH\Config\Services.php on line 686.

### ISSUE THREAD

**Issue by notokrs** [codeigniter4/CodeIgniter4#9024]
### PHP Version

7.4

### CodeIgniter4 Version

4.4.8

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

SQL Server 15

### What happened?

I get this error when I deploy the application to the server, but on my local machine this never happens.
When the error appears and refresh the browser it returns to normal, but it becomes annoying because it can appear more than 10 times every day.

### Steps to Reproduce

error in log file:

```
Error: Class 'file' not found
in SYSTEMPATH\Config\Services.php on line 686.
 1 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 2 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 3 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 4 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
 5 SYSTEMPATH\Common.php(982): CodeIgniter\Config\BaseService::__callStatic('session', [])
 6 APPPATH\Filters\Dokterpriv\POLI.php(30): session()
 7 SYSTEMPATH\Filters\Filters.php(184): App\Filters\Dokterpriv\POLI->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 8 SYSTEMPATH\CodeIgniter.php(475): CodeIgniter\Filters\Filters->run('dokter/pasien/get-pasien-list', 'before')
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
```

I have checked the Sessions.php config file in my app folder and there is nothing wrong. I have followed the existing documentation.

### Expected Output

the session should be able to run as it should.

### Anything else?

I've searched Google and I only got 1 reference :

https://stackoverflow.com/questions/76528607/codeigniter-error-class-file-not-found-systempath-config-services-php-at-lin

and that doesn't solve the problem either.

**Comment by paulbalandan** [comment]
Can you check your **app/Config/Session.php** file and look at the value of the `$driver` property?

**Comment by paulbalandan** [comment]
Also, your `.env` file for the value of the `session.driver` key.

**Comment by notokrs** [comment]
my app\Config\Session.php

![Screenshot 2024-07-06 105059](https://github.com/codeigniter4/CodeIgniter4/assets/79308398/3da8a0f1-f76c-49b2-9461-8b7d01718e1d)

my .env
![Screenshot 2024-07-06 105132](https://github.com/codeigniter4/CodeIgniter4/assets/79308398/db29c01b-1008-419c-9ff5-853e88a239f9)

**Comment by kenjis** [comment]
Could you show the output of `php spark config:check Session`?

**Comment by darthleslin** [comment]
Is it happens because of php v7.4 .
I believe CI4 required 8.1 and above.
