### ISSUE TITLE
Bug: ENVIRONMENT is not updated when changed via .ENV ( 4.5.3)

### ISSUE THREAD

**Issue by ampmonteiro** [codeigniter4/CodeIgniter4#9029]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

-

### What happened?

 Following the [Docs](https://codeigniter.com/user_guide/general/environments.html#environment-constant) to change the `.env` file to change `CI_ENVIRONMENT` to  `development` and  `app.baseURL = 'http://localhost/'` when refresh de browser it is still in `production`  and even  dev toolbar dont show.

### Steps to Reproduce

i just followed the [Docs](https://codeigniter.com/user_guide/general/environments.html#environment-constant), how to change the `ENVIRONMENT` to `development` and  `app.baseURL = 'http://localhost/'` in `.env`

Also change in ` APP > Config >App,php `  the props  `indexPage` to empty string.

Only works with this command the change is applied : `php spark env development`.

### Expected Output

The same result as when execute the command `php spark env development`

![image](https://github.com/codeigniter4/CodeIgniter4/assets/31895754/2e7997d3-a51f-455d-abae-bfcb301e44da)

`Via terminal`
![image](https://github.com/codeigniter4/CodeIgniter4/assets/31895754/a6749eca-efae-4775-a11b-2783e40a7ce6)

however if change via `.env `  -> `CI_ENVIRONMENT = development` :

![image](https://github.com/codeigniter4/CodeIgniter4/assets/31895754/c28a6441-cc4f-46fb-83af-99dd1a1df0f4)

**Comment by kenjis** [comment]
Cannot reproduce.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by ampmonteiro** [comment]
@cijagani  
it nothing to do with browser cache, since, as already said, with command `php spark env development` and refreshing the page will show the correct ENV

@kenjis 
sorry but make no sense close the issue even if you cannot reproduce it. 
What you should be doing, in my opinion, is ask for more details.

So to reproduce this i used Docker with image configuration like [this](https://gist.github.com/ampmonteiro/8686637ba578c7e44ff7c1e5e90d81ee) in my Gist, just change to PHP 8.3.

i  update the docker image and even downgrad to 8.1 and same problem

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
