### ISSUE TITLE
[Feat] Routing: Support to PHP Attributes

### ISSUE THREAD

**Issue by ampmonteiro** [codeigniter4/CodeIgniter4#9030]
Hi,

since [CI 4.5.X](https://codeigniter.com/user_guide/intro/requirements.html#id1), only supports or requires PHP 8.1+,
why not take advantage of PHP feature like `Attributes` ( which p.e Symfony use for there routing).

PHP Docs abou [PHP Attributes](https://www.php.net/manual/en/language.attributes.overview.php).

With this implemented i would first deprecated the `Auto Routing (Legacy)` and later maybe `Auto Routing Improved`,
keeping the traditional way  by using  `Routes,php` file and  modern way, using `PHP Attributes`.

Thanks ;)

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by kenjis** [comment]
FYI:
- https://github.com/kenjis/ci4-attribute-routes
- https://github.com/monkenWu/CodeIgniter4-Route-Attributes

**Comment by ampmonteiro** [comment]
@kenjis 

Hi, why close the issue and after that you wrote some links with suggestion ? make no sense.

Why i have to install external libs when the framework could have this already built-in ?
Why the framework has 3 ways To implement routing ? it seams hard to manage .
Why not take advantages of a native feature of the language for routing or even to indicate the template / view ( like symfony did) ?

About the forum, why i have to create a new account ? 
 when you CI team could implement in that forum a way to use my Github account ?

And someone in that forum already ask for this feature, [here](https://forum.codeigniter.com/showthread.php?tid=91096),
with no reply what at the moment !!!!!

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
