### ISSUE TITLE
Bug: routes not work in ci 4.3.5

### ISSUE THREAD

**Issue by hinditutorpoint** [codeigniter4/CodeIgniter4#9033]
### PHP Version

7.4

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Hi ci team my project routes working stopped we didn't figure out what happened previous two day ago working fine today we add new route didn't work simply throw a 404 Can't find a route for
we have try
clear cache
clear log
clear browser history
but did not succeed another we have checked php spark routes in present routes but in debugger did not shown this issue in local 
this project upload to server then worked perfect

### Steps to Reproduce

```php
$routes->get('test', function () {
    return 'Test route works!';
});
```

### Expected Output

not works

**Comment by kenjis** [comment]
1. Cannot reproduce.
2. v4.3.5 is no longer supported. Upgrade to the latest v4.5.3.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
