### ISSUE TITLE
Bug: debug bar content not show with daisyUI ver 4.12.10

### ISSUE THREAD

**Issue by noname00AMD** [codeigniter4/CodeIgniter4#9041]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

tool bar content cant not show correctly because css "tab" class duplicate with daisyUI set to height: 2rem

### Steps to Reproduce

""

### Expected Output

""

**Comment by kenjis** [comment]
This?
https://forum.codeigniter.com/showthread.php?tid=88401

**Comment by noname00AMD** [comment]
> This? https://forum.codeigniter.com/showthread.php?tid=88401

Exactly

**Comment by noname00AMD** [comment]
thanks

**Comment by kenjis** [comment]
@noname00AMD Check, please. #9046
