### ISSUE TITLE
Bug: TypeError in pg_ping()

### ISSUE THREAD

**Issue by warcooft** [codeigniter4/CodeIgniter4#9043]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

PostgreSQL 16.3

### What happened?

pg_ping() expects the first parameter to be a PostgreSQL connection (or null), but receives the boolean value false.

See also https://github.com/codeigniter4/queue/issues/45#issue-2401691847

This is a blocker for other packages.

<img width="1311" alt="Screenshot 2024-07-11 at 05 47 49" src="https://github.com/codeigniter4/CodeIgniter4/assets/22941122/9a3f60df-5d95-4552-bb5d-1e4058b7d2f2">

### Steps to Reproduce

```php
$db = db_connect();
d($db->connect());
d($db->close());
d($db->reconnect());
d($db->getDatabase());
d($db->getVersion());
dd();
``` 

### Expected Output

The output should show the db name and db driver version.

**Comment by warcooft** [comment]
it looks like the `close()` function also doesn't work when using the PostgresSQL driver:

<img width="1680" alt="Screenshot 2024-07-11 at 07 24 15" src="https://github.com/codeigniter4/CodeIgniter4/assets/22941122/b0fe79f6-f1dd-4dc2-8f3c-a10cb80831b6">



&nbsp;
this when using MySQL:

<img width="1680" alt="Screenshot 2024-07-11 at 07 25 22" src="https://github.com/codeigniter4/CodeIgniter4/assets/22941122/c49fd2ac-ad75-444e-b420-91dcdfbde410">

### Steps to Reproduce

```php
$db = db_connect();
d($db);
// d($db->connect());
d($db->close());
// d($db->reconnect());
d($db->getPlatform());
d($db->getVersion());
dd();
```

**Comment by warcooft** [comment]
and both connections cannot be closed if before closing we run `connect()` as follows:

```php
$db = db_connect();
d($db);
d($db->connect());
d($db->close());
// d($db->reconnect());
d($db->getPlatform());
d($db->getVersion());
dd();
```

**Comment by paulbalandan** [comment]
I can reproduce the TypeError in the original issue.

**Comment by paulbalandan** [comment]
Dumb question: if you call `reconnect()` on a closed DB connection, should you initialize again? In the Postgres driver, you only call `pg_ping()` which just pings the connection if still active and tries to reconnect if broken. For MySQL driver, it explicitly closes then reinitializes the connection. Clearly a difference in behaviors, I suppose.

**Comment by warcooft** [comment]
> For MySQL driver, it explicitly closes then reinitializes the connection. Clearly a difference in behaviors.

I'm not sure if the way used to produce the error above is correct. I think both have the same behavior. thankyou for enlighten me.

**Comment by kenjis** [comment]
The behavior of `reconnect()` is to keep the connection alive or re-establish it.
> If the database server’s idle timeout is exceeded while you’re doing some heavy PHP lifting (processing an image, for instance), you should consider pinging the server by using the reconnect() method before sending further queries, which can gracefully keep the connection alive or re-establish it.
https://codeigniter4.github.io/CodeIgniter4/database/connecting.html#reconnecting-keeping-the-connection-alive

So if there is a *ping* method in the DB module, we should use it.

But in MySQL, `ping()` is no longer working. See #462

**Comment by warcooft** [comment]
That helps! thanks for explaining.
