### ISSUE TITLE
Add to $filters except urls like in globals

### ISSUE THREAD

**Issue by motoroller1983** [codeigniter4/CodeIgniter4#9050]
```php
 /**
     * List of filter aliases that should run on any
     * before or after URI patterns.
     *
     * Example:
     * 'isLoggedIn' => ['before' => ['account/*', 'profiles/*']]
     *
     * @var array<string, array<string, list<string>>>
     */
    public array $filters = [

        'isLoggedInPanel' => [
            'before' => [ 'panel/*' ],
            'except' => [ 'panel/login' ] // Add your excluded URLs here
        ]
];
```

It’s inconvenient to list all available URLs in Filters, especially since new URLs can be added later, which you need to remember to add to filters. It would be convenient to add the ability to add to exceptions. Of course, you can also add to global ones, but why if I have the filter is used for several pages, should I add it to the global ones? Thus, significantly loading the system

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
