### ISSUE TITLE
Bug: Boot Order

### ISSUE THREAD

**Issue by sclubricants** [codeigniter4/CodeIgniter4#9062]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

Prior to Codeigniter 4.5 you could have the following in /var/www/portal/app/Config/Boot/production.php

```php
use CodeIgniter\Config\Factories;
Factories::define('models', 'Myth\Auth\Models\UserModel', 'App\Models\UserModel');
```

but now the namespace CodeIgniter\Config\Factories is not found. It appears these boot files are being run before the autoloader. I'm not sure if this is a bug or not but the behavior changed and I couldn't find anything in the documentation about it.

### Steps to Reproduce

Access name space if given file.

### Expected Output

Expect that class loads.

**Comment by kenjis** [comment]
I'm not sure what should we do.

The environment boot files set PHP error reporting like:
```php
error_reporting(E_ALL & ~E_DEPRECATED);
ini_set('display_errors', '0');
```
These settings should be set as early as possible.
So now these files are loaded before loading the autoloader.

**Comment by kenjis** [comment]
Yes, I think using Event `pre_system` is better in your case.
