### ISSUE TITLE
Bug: speed bug

### ISSUE THREAD

**Issue by zsolt585** [codeigniter4/CodeIgniter4#9074]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.3

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

Hi.
We are using codeigniter 4 for mobile API.
We have upgraded the project from CI3 to CI4, and on our machine ci4 is faster, but when it is deployed to our test / production servers becomes way slower.
For example in CI3 an endpoint response time was 200ms, meanwhile in CI4 it is around 2.000 ms.

We have tried eliminating the database, to make sure not the queries are problem, but the performance did not increased.

**Comment by cijagani** [comment]
Application performance defended on many factors. Your server configuration, server settings, resources etc..  it is not ci4 issue.

**Comment by cijagani** [comment]
You can post your issues in the forum site.

**Comment by michalsn** [comment]
The v4.5 version is in fact the fastest iteration of branch 4 to date.

I would suggest providing the production server configuration/settings. You can share it on the [forum](https://forum.codeigniter.com/) - you should find some people willing to give you some feedback.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

**Comment by kenjis** [comment]
As a fact, CI4 is much slower than CI3 when comparing by the Hello World benchmark.
See #6889
