### ISSUE TITLE
Bug: Validation rule `differs` or `matches` fails if rule applied on array data

### ISSUE THREAD

**Issue by ToastStudios** [codeigniter4/CodeIgniter4#9101]
### PHP Version

8.1

### CodeIgniter4 Version

4.5.2

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL 8.3.0 - Homebrew

### What happened?

The validator will fail if using `differs` or `matches` on array data.

### Steps to Reproduce

Use these rules:

    $rules = [
        'name' => 'permit_empty',
        'emailAddress' => 'permit_empty|valid_email',
        'alias.*' => [
            'rules' => 'permit_empty|differs[name]',
            'errors' => [
                'differs' => 'You cannot use your name as alias'
            ]
        ],
    ];
Use this array to validate:

    $data = array(
        'name' => 'Princess Peach',
        'emailAddress' => 'valid@example.com',
        'alias' => array(
            'Princess Toadstool',
            'Peach'
        )
    );

### Expected Output

Validator is expected to pass since:  
`alias.0 !== name`
`alias.1 !== name`

### Anything else?

Will always fail because in `system/Validation/StrictRules/Rules.php` `array_key_exitst` does not expect `$files` to be a dot.array. This fixes the validation (might be improved/further inspected, but needed at least in functions `differs` and `matches`):

    if (str_contains($field, '.')) {
        if (! boolval(dot_array_search($field, $data))) {
            return false;
        }
    } elseif (! array_key_exists($field, $data)) {
        return false;
    }

![image](https://github.com/user-attachments/assets/53130772-88f4-47c3-a979-fc4dfd393e47)

**Comment by kenjis** [comment]
Thank you for reporting! Try #9103

**Comment by ToastStudios** [comment]
@kenjis this indeed fixes the bug, thanks!

**Comment by kenjis** [comment]
@ToastStudios Thank you for checking!

The PR has not yet been merged.
You don't need to close this, because it will be closed when the  PR is merged.
