### ISSUE TITLE
Bug: Preload issues

### ISSUE THREAD

**Issue by MickaelCa** [codeigniter4/CodeIgniter4#9110]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.4

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### What happened?

Current [preload script](https://github.com/codeigniter4/CodeIgniter4/blob/5a340d01298505bbb22efd52bf231ab64a8c23bb/preload.php) is not working.

### Steps to Reproduce

Run `php preload.php`

```
[...]
Loaded: /srv/app/vendor/codeigniter4/framework/system/rewrite.php
PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /srv/app/preload.php:91
Stack trace:
#0 /srv/app/preload.php(104): preload->load()
#1 {main}
  thrown in /srv/app/preload.php on line 91

Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /srv/app/preload.php:91
Stack trace:
#0 /srv/app/preload.php(104): preload->load()
#1 {main}
  thrown in /srv/app/preload.php on line 91
```

### Expected Output

No exception

### Anything else?

Adding `'/system/rewrite.php',` to excludes fix the issue.

**Comment by kenjis** [comment]
Thank you for reporting!
Please check #9111
