### ISSUE TITLE
Bug: Truncated email subject when contains accented characters

### ISSUE THREAD

**Issue by bereldhuin** [codeigniter4/CodeIgniter4#9122]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli

### What happened?

Setting an email with accented characters in subject (eg : french accent : éàè...) removes n characters at the end of the subjet (n = number of accented chars).

This does not occur in the body.

### Steps to Reproduce

Send an email with accented char in the subject : 

```php
 $email = service('email');

$email->setFrom('toto@gmail.com', 'Fred');
$email->setTo('titi@gmail.com');

$email->setSubject('Email éé Test');
$email->setMessage('Testing the email class.');

$email->send();
```

### Expected Output

Should send and email with the following subjet : 
`Email éé Test`

But instead sends :

`Email éé Te ` (missing 2 last chars)

### Anything else?

Using php 8.3.9 under Alpine 1.20 docker container, and Gmail as SMTP.

**Comment by kenjis** [comment]
Thank you for reporting.

But I cannot reproduce. The following test passes.
```php
    public function testEmailSubjectWithAccentedCharacters(): void
    {
        $config = config('Email');
        $email  = new MockEmail($config);

        $email->setTo('foo@foo.com');
        $email->setFrom('bar@foo.com');
        $email->setSubject('Email éé Test');

        $this->assertTrue($email->send());
        $this->assertSame('Email éé Test', $email->archive['subject']);
    }
```

**Comment by visserrobin** [comment]
Tested with a live version of Codeigniter 4.5.2. Accented characters are not truncated. Could it be a characterset issue in the Email config? I also tested iso-8859-1 and Windows1252. Windows-1252 produces gibberish but doesn't truncate the subject line.

**Comment by paulbalandan** [comment]
Closing due to no response.
