### ISSUE TITLE
Bug: `is_unique` rule specification

### ISSUE THREAD

**Issue by warcooft** [codeigniter4/CodeIgniter4#9130]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL 8

### What happened?

I thought the `is_unique` rule was supposed to check only records where the `deleted_at` column is `NULL`, correct? 
Or is that not how it's meant to work?

```php
$row = Database::connect($data['DBGroup'] ?? null) 
         ->table($table) 
         ->select('1') 
         ->where($field, $str) 
         ->limit(1); 
``` 

https://github.com/codeigniter4/CodeIgniter4/blob/f2e560f90c88cc82964f7b5f44819bd47ee4f323/system/Validation/Rules.php#L178-L207

### Steps to Reproduce

-

### Expected Output

-

**Comment by neznaika0** [comment]
Wrong. When adding a new record after checking the `email`, a DB duplication error may occur

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
