### ISSUE TITLE
Bug: return 404 if request only headers

### ISSUE THREAD

**Issue by ostap-mykhaylyak** [codeigniter4/CodeIgniter4#9132]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

If try to get only headers, return 404:

```
curl -s -I https://xxxxxx.net/xx/xx/xxxxxxx
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=UTF-8
```

```
$ curl -s -I https://codeigniter.com/
HTTP/2 404
content-type: application/json; charset=UTF-8
```

### Steps to Reproduce

curl -s -I https://codeigniter.com/

### Expected Output

return 200

**Comment by ostap-mykhaylyak** [comment]
@all remember to set:

`$routes->match(['get', 'head'], '/', 'Home::index');
`

**Comment by ostap-mykhaylyak** [comment]
https://github.com/ALL remember to set:

`$routes->match(['get', 'head'], '/', 'Home::index');`

**Comment by kenjis** [comment]
This is not a bug. If necessary, HEAD routes also need to be defined.

However, if there is a GET route, HEAD should also be accepted, so there is room for enhancement.

**Comment by incredibleasif** [comment]
> This is not a bug. If necessary, HEAD routes also need to be defined.
> 
> However, if there is a GET route, HEAD should also be accepted, so there is room for enhancement.

@kenjis Any updates on this? this issue can affect site SEO.
