### ISSUE TITLE
Bug: json-array  type  error , for model  field casting 

### ISSUE THREAD

**Issue by krangadurai** [codeigniter4/CodeIgniter4#9148]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

![Screenshot 2024-08-24 194238](https://github.com/user-attachments/assets/0c7a3bf7-9afd-4466-8f0f-7282d401ab4c)

filed casting   type json-array  type casing type errorLinks? References? Anything that will give us more context about the issue you are encountering!

Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

### Steps to Reproduce

json-array filed casting casing type error   

### Expected Output

json-array filed casting casing type error                                                                                                                                               

### Anything else?

![Screenshot 2024-08-24 194303](https://github.com/user-attachments/assets/07c8ca82-aa75-4d24-aaa1-c914bdde4e84)

system\DataCaster\Cast\JsonCast.php   line 36  add  ` $value =json_decode($value, true);`  working fine ,

**Comment by kenjis** [comment]
Sorry, this is not a bug in the framework, but a bug in your code.

See the `$ouput` is a string, not an array.
But `json-array` expects an `array`. See https://codeigniter4.github.io/CodeIgniter4/models/model.html#data-types

![Screenshot 2024-08-25 11 17 53](https://github.com/user-attachments/assets/6cbc0aab-ecd3-45da-9800-b8d9339595a4)

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
