### ISSUE TITLE
Bug: Horrible UI since the beginning of CI3 and 4

### ISSUE THREAD

**Issue by danieltorscho** [codeigniter4/CodeIgniter4#9178]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Guys, this UI is horrible, it literally hurts my eyes reading it, so it's impossible to continue. I remember CI v2 had a great UI for reading docs, not anymore since v3.

![image](https://github.com/user-attachments/assets/4cff1138-9a34-42bb-af3e-095d2a297f3f)

### Steps to Reproduce

Go check the docs: https://codeigniter.com/user_guide/index.html

### Expected Output

disabling following styles helps a lot:
```css
/* General ------------------------------------------------------------------ */

body, p, legend {
  /* font-family: "Raleway", "Helvetica", "Arial", sans-serif; */  /* <-------- TURN THIS OFF */
}

/* Titles ------------------------------------------------------------------- */

h1, h2, h3, h4, h5, h6 {
  /* font-family: "Raleway", "Helvetica", "Arial", sans-serif; */  /* <-------- TURN THIS OFF */
}
```

**Comment by danieltorscho** [comment]
Forgot to mention, I'm on Windows 10, QHD (2K) Monitor

**Comment by kenjis** [comment]
My screenshot:
![Screenshot 2024-09-08 11 15 52](https://github.com/user-attachments/assets/1dea759f-0561-4855-830f-c708f584fa44)

**Comment by neznaika0** [comment]
![Screenshot_20240908_072930_Browser](https://github.com/user-attachments/assets/b73c10de-234f-4a1f-b06b-d706cc38500e)
All good on phone and windows 11 (2k)
It seems you have a problem with font settings

**Comment by ddevsr** [comment]
![image](https://github.com/user-attachments/assets/4241fccf-8e37-4466-8870-b63766cab881)

All goods

**Comment by danieltorscho** [comment]
Given the community's feedback, I assume it happens only on my pc. Closing
