### ISSUE TITLE
Bug: Config Caching not work

### ISSUE THREAD

**Issue by neznaika0** [codeigniter4/CodeIgniter4#9181]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

After enabling configuration caching, we get errors. 
```
Call to undefined method Config\Autoload::__set_state() 
Call to undefined method Config\Paths::__set_state() 
```
Fragment  **writable/cache/FactoriesCache_config**:
```php
    'Config\\Feature' => 
    \Config\Feature::__set_state(array(
       'autoRoutesImproved' => false,
       'oldFilterOrder' => false,
       'limitZeroAsAll' => true,
    )),
    'Config\\Autoload' => 
    \Config\Autoload::__set_state(array(
       'psr4' => 
      array (
        'CodeIgniter' => '.../vendor/codeigniter4/framework/system/',
...
```
It is unclear how this was tested. But it doesn't work out of the box.

### Steps to Reproduce

1. Run `./spark optimize`
2. Open any URL (homepage)

### Expected Output

Usual rebuild of the `Autoload`, `Paths` classes

### Anything else?

You need to exclude classes from the cache or add `__set_state()` methods:

```php
    public static function __set_state(array $array)
    {
        $obj        = new static();
        $properties = array_keys(get_object_vars($obj));

        foreach ($properties as $property) {
            $obj->{$property} = $array[$property];
        }

        return $obj;
    }
```
In docs write, but it is not used in the system:
> By default, every Config class that is cached must implement __set_state() method.
> https://codeigniter.com/user_guide/concepts/factories.html#prerequisite

**Comment by kenjis** [comment]
> You need to exclude classes from the cache or add __set_state() methods:

It is the correct answer.

> By default, every Config class that is cached must implement __set_state() method.

Yes, your `Config\Autoload` and `Config\Paths` do not have __set_state() method.
So the Config Caching causes the errors.

Why do you think this is a  bug?

**Comment by neznaika0** [comment]
site does not work after the cache is enabled. Is this not a bug?

**Comment by ddevsr** [comment]
Your config `extends BaseConfig`?

**Comment by neznaika0** [comment]
This is a copy of the system config. it should not extend `BaseConfig`
https://github.com/codeigniter4/CodeIgniter4/blob/0a6b39ded15603043d3bfbfd6496d9149e5d13be/system/Autoloader/Autoloader.php#L66

**Comment by kenjis** [comment]
Why do you need to cache `Config\Autoload` and `Config\Paths`?
Most devs should not cache them, because it is waste of time.

But if you have valid reasons to cache them, implement the `__set_state()` method by yourself.
If there is something wrong with the current documentation, please send a PR to improve it.

**Comment by kenjis** [comment]
Duplicate of #8914

**Comment by neznaika0** [comment]
I know how to fix it. I turned on the function for an experiment.

Why don't you understand that the file caching is done by the system and not by me? It also caches configs without `BaseConfig`

As a user, I just turn on optimization and that's it. But the system caches unnecessary files for some reason.

**Comment by kenjis** [comment]
The framework does not cache `Config\Autoload` or `Config\Paths`.

**Comment by neznaika0** [comment]
There seems to be a problem with another package. It adds additional aliases to the cache.
Normal **writable/cache/FactoriesCache_config**
```php
  'aliases' => 
  array (
    'Config\\Exceptions' => 'Config\\Exceptions',
    'Config\\ContentSecurityPolicy' => 'Config\\ContentSecurityPolicy',
    'Config\\App' => 'Config\\App',
    'Config\\Cache' => 'Config\\Cache',
    'Config\\UserAgents' => 'Config\\UserAgents',
    'Config\\Cookie' => 'Config\\Cookie',
    'Config\\Modules' => 'Config\\Modules',
    'Config\\Toolbar' => 'Config\\Toolbar',
    'Config\\Routing' => 'Config\\Routing',
    'Config\\Filters' => 'Config\\Filters',
    'Config\\Feature' => 'Config\\Feature',
    'Config\\Logger' => 'Config\\Logger',
    'Config\\View' => 'Config\\View',
  ),
```

**Comment by neznaika0** [comment]
I apologize. I found the reason with `Paths`. But `Autoload` disappeared without a trace...

**Comment by kenjis** [comment]
Okay, I got your situation. 
If a package calls `config('XXX')` (and will be cached), it is a bit difficult to know it.
