### ISSUE TITLE
Bug: Some translation files are not loaded on purpose

### ISSUE THREAD

**Issue by saloniamatteo** [codeigniter4/CodeIgniter4#9203]
### PHP Version

8.3.11

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### What happened?

When trying to use translation files with particular names (like `design`, `services`), CodeIgniter does not purposefully load the requested files. Every other name works fine.

I also noticed it doesn't matter if the filename is only that word: if the filename starts with that word (example: `mservices`), it still doesn't load.
However, if the filename starts with that word, but ends with a different letter (example: `designp`), it works.
Moreover, if the filename starts with that word, but ends with a letter same as the last letter of the "word" (example: `servicess`), it doesn't work.

### Steps to Reproduce

Example: `app/Language/it/services.php`

```php
<?php
return [
    "aaa"  => "bbb",
];
?>
```

(Copy and paste to `app/Language/en/services.php`, aka the files are the same inside.)

Try to load `services.aaa`, you'll see it doesn't work:

```php
<?= lang('services.aaa') ?>
```

### Expected Output

Expected output is working translation files without the need for some kind of "filter".

**Comment by michalsn** [comment]
Could not reproduce. Please pay attention to the details and follow the naming convention described in the user guide: https://codeigniter.com/user_guide/outgoing/localization.html#language-localization

This is how I tested it on the current `develop`:

```php
//app/Language/en/Services.php
<?php
return [
    "aaa" => "bbb",
];
```

```php
dd(lang('Services.aaa'));
// returns: lang(...) string (3) "bbb"
```

**Comment by saloniamatteo** [comment]
@michalsn, have you tried with a lowercase name? I swear I'm not crazy. I have other translation files and they work fine, only some names (like the ones in the issue above) don't work.

**Comment by michalsn** [comment]
Yes, still no issues. Checked on macOS and Linux.

Have you tried it on a fresh install? With only 1 file added: `app/Language/en/Services.php` and a call in the controller to `lang('Services.aaa')`?

**Comment by neznaika0** [comment]
I confirm that there is no error after a clean installation. Debian, PHP 8.3.9, server run as `./spark serve`

**Comment by saloniamatteo** [comment]
That's weird. How can I debug this issue? I haven't modified any "system" files related to translations.

**Comment by datamweb** [comment]
Can you share file **app/Language/it/Services.php** for download?

**Comment by saloniamatteo** [comment]
I cannot share this file right now, but I can share the other affected file, "design".
Italian: https://github.com/saloniamatteo/salonia.it/blob/master/app/Language/it/designp.php
English: https://github.com/saloniamatteo/salonia.it/blob/master/app/Language/en/designp.php

Changing the file name to "design" and trying to get the translation keys "design.*" doesn't work..

**Comment by datamweb** [comment]
```php
$opts = [
  "title" => lang("design.title"),
   "desc"    => lang("design.desc"),
   "url"    => base_url("design"),
];
dd($opts);
```
![Screenshot 2024-09-29 193804](https://github.com/user-attachments/assets/fa90fd6a-3f96-431f-a2fe-eab6e03129d8)

Unable to produce an error, I'm on Windows.

**Comment by saloniamatteo** [comment]
How is that possible?

![image](https://github.com/user-attachments/assets/e57c2487-ccbe-4ff6-966c-e5a312e84d7d)

**Comment by saloniamatteo** [comment]
Just to be clear, I'm also using `php spark serve`, so no way it is a webserver issue.

**Comment by datamweb** [comment]
Continue by manually setting the` public string $defaultLocale = 'it';` in **Config/App.php**.

**Comment by saloniamatteo** [comment]
It still doesn't work.. plus my browser's default language (as well as the website's default language) is English.

**Comment by saloniamatteo** [comment]
Update: apparently, trying this on my server (that does NOT use `php spark serve`, but nginx as a reverse proxy) does NOT give any issues (as in, the strings load just fine). Maybe this is a `spark` issue?

**Comment by saloniamatteo** [comment]
My `.env` file is as follows:

```
CI_ENVIRONMENT = development
app.baseURL = "http://localhost:8080"
```

**Comment by datamweb** [comment]
Change the name of the language file from **design** to **Design**.
Take the values ​​as follows.
```php
lang("Design.title"),
```
Please tell me the output of the following command.
```php
dd(service('language')->getLocale());
```

**Comment by saloniamatteo** [comment]
Output: service(...)->getLocale() string (2) "en"

**Comment by saloniamatteo** [comment]
![image](https://github.com/user-attachments/assets/edac5f9d-00f4-4baf-8661-97cc3dd4a64e)

**Comment by datamweb** [comment]
> Crazily enough, having the uppercase name fixed it!

In CodeIgniter 4, language files must start with an uppercase letter to comply with the **PSR-4** autoloading standard. This standard requires file names and class names to match, starting with an uppercase letter, ensuring compatibility and avoiding issues on **case-sensitive** file systems like **Linux**.

**Comment by saloniamatteo** [comment]
Thanks for being clear, I didn't understand why only certain files did not get automatically loaded.. 😄
