### ISSUE TITLE
Dev: Enhancement add support for dbGroup in is_unique and is_not_unique validation rules

### ISSUE THREAD

**Issue by maniaba** [codeigniter4/CodeIgniter4#9215]
I recently posted a feature request on the CodeIgniter forum regarding the `is_unique` and `is_not_unique` validation rules. The current implementation lacks support for specifying a `dbGroup`, which can cause issues when working with multiple database connections.

Here is the forum post for additional context: [https://forum.codeigniter.com/showthread.php?tid=91760](https://forum.codeigniter.com/showthread.php?tid=91760)

**Request:** I propose enhancing the `is_unique` and `is_not_unique` validation rules to optionally accept a `dbGroup` as a parameter. This would allow users to specify the database connection they want the rule to apply to, providing more flexibility in multi-database environments.

I am planning to submit a pull request (PR) with these changes soon. If there are any suggestions, please let me know.

Thank you for considering this enhancement!

**Comment by paulbalandan** [comment]
To be fixed in `4.6`
