### ISSUE TITLE
Bug: insensitive like query failing with multibyte characters

### ISSUE THREAD

**Issue by ECode16** [codeigniter4/CodeIgniter4#9236]
### PHP Version

7.4

### CodeIgniter4 Version

4.4.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli

### Database

Postgres 16

### What happened?

strtolower() in BaseBuilder.php on line 1135 will ignore the multibyte characters (according to PHP8 docs) or in experience on 7.4 will mangle them into diamonds (�).

### Steps to Reproduce

`$query->like('name', 'Š', 'both', null, true)->find();`

### Expected Output
all rows where name contains `š`

### Actual Output
ErrorException: pg_query(): Query failed: ERROR:  invalid byte sequence for encoding &quot;UTF8&quot;: 0xe5 0xa1 0x27 in C:\....

**Comment by michalsn** [comment]
@ECode16 Can you check if #9238 fixes it for you?
