### ISSUE TITLE
Bug: Validation rules and

### ISSUE THREAD

**Issue by ECode16** [codeigniter4/CodeIgniter4#9247]
### PHP Version

7.4

### CodeIgniter4 Version

4.4.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli

### Database

Postgres 16

### What happened?

All alphabetical/alphanumerical evaluate to false when encountering non-English characters (accented/cyrillic).

### Steps to Reproduce

service('validation')->check('пЗХТЕГ', 'alpha');
service('validation')->check('á', 'alpha');

### Expected Output

true
true

**Comment by neznaika0** [comment]
Not bug. Read docs:
> Fails if field has anything other than
alphabetic characters in ASCII.

Use `regex_match[/[а-яё]+/]`
