### ISSUE TITLE
Bug: base_uri or baseURI in curlrequest?

### ISSUE THREAD

**Issue by warmbook** [codeigniter4/CodeIgniter4#9265]
### PHP Version

8.1

### CodeIgniter4 Version

4.5.4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### What happened?

In the [manual](https://codeigniter.org/user_guide/libraries/curlrequest.html#base-uri) and CodeIgniter\HTTP\CURLRequest->parseOptions, it's 'baseURI '. But in Config\Services::curlrequest, it's 'base_uri'.

### Steps to Reproduce

View the code

### Expected Output

Use one of 'baseURI' and 'base_uri'.

**Comment by neznaika0** [comment]
Its not bug. See
```php
return new CURLRequest(
    $config,
    new URI($options['base_uri'] ?? null),
    $response,
    $options
);
```
`base_url` for a service is not the same as `baseUrl` for a CURLRequest. `base_url` is here only for initial `URI` setup.

It looks weird, but it works

**Comment by warmbook** [comment]
@neznaika0  But in the [manual](https://codeigniter.org/user_guide/libraries/curlrequest.html#base-uri), it's 'baseURI ':

$client = service('curlrequest', [
    'baseURI' => 'https://example.com/api/v1/',
]);

**Comment by michalsn** [comment]
Yes, this seems like a bug created when we transited from `snake_case` to `camelCase` (a loooong time ago). It wasn't spotted, because `parseOptions()` method is called every time, setting the correct URI.

Feel free to send a PR with the fix.
