### ISSUE TITLE
Bug: site defaced

### ISSUE THREAD

**Issue by Under-Wow** [codeigniter4/CodeIgniter4#9268]
### PHP Version

8.1

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

 MariaDB 10.1

### What happened?

My site has been defaced by some people and their index page has been changed.

### Steps to Reproduce

I have used validation in my forms and also have ssl

### Expected Output

some files have been uploaded on my host and index has also been changed through .htaccess

As long as I was on CodeIgniter 4.3.7 I had no problems, after updating to 4.5.5 was defaced

**Comment by samsonasik** [comment]
Read security guideline https://github.com/codeigniter4/CodeIgniter4/blob/develop/SECURITY.md .
