### ISSUE TITLE
Bug: security vulnerability

### ISSUE THREAD

**Issue by shocker978** [codeigniter4/CodeIgniter4#9269]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 8

### What happened?

Files have been uploaded on my host that changed index.php, it is a private panel that only has an entry form and does not even have the ability to register. I don't have any page for file upload on my site. It is very strange. I also have Google Captcha v3 for that login form.

### Steps to Reproduce

i don't know

### Expected Output

Do not upload any file

**Comment by samsonasik** [comment]
Read security policy https://github.com/codeigniter4/CodeIgniter4/blob/develop/SECURITY.md .
