### ISSUE TITLE
Bug: CodeIgniter Migrates And Saves an Empty Migration File Info In The Database

### ISSUE THREAD

**Issue by Elvis254** [codeigniter4/CodeIgniter4#9272]
### PHP Version

8.3

### CodeIgniter4 Version

4.4.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.2

### What happened?

I decided to skip writing all other files I generated for migration except one. After executing the spark command to migrate the files were migrated including the empty files which I hadn't written code for and its information saved in the migration table on the database.

### Steps to Reproduce

It should not save details of an empty migration file in the migration table on the database.

### Expected Output

The empty files information should not be saved in the migration table on the database.

**Comment by michalsn** [comment]
If a migration file is present, it will be executed - that's how it was designed. We don't keep track of whether any changes were made to the database in the migration.

The whole point of using migrations is to make sure they’re executed in order.

If you want to skip some migrations for now, you can add it to another DB group (or namespace) and migrate only the default one.

**Comment by neznaika0** [comment]
Rename migration file to exclude from the search

**Comment by Elvis254** [comment]
@neznaika0 this works but when it comes to having same name used on both the file and table its not the best way of solving this problem.
