### ISSUE TITLE
File upload security bug

### ISSUE THREAD

**Issue by Waterforcex** [codeigniter4/CodeIgniter4#9283]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 8

### What happened?

Hello, files were uploaded on my host that do not belong to me and caused my site to fail. I have followed the security tips and used form validation. I also saw some issues that I think are related to my problem, but they have been closed, please tell me the solution you gave them.

https://github.com/codeigniter4/CodeIgniter4/issues/9269
https://github.com/codeigniter4/CodeIgniter4/issues/9268
https://github.com/codeigniter4/CodeIgniter4/issues/9266

### Steps to Reproduce

don't know

### Expected Output

don't know

**Comment by michalsn** [comment]
Please read the security policy https://github.com/codeigniter4/CodeIgniter4/blob/develop/SECURITY.md
