### ISSUE TITLE
Bug: PHP 8.4.1 Time Static function

### ISSUE THREAD

**Issue by ALTITUDE-DEV-FR** [codeigniter4/CodeIgniter4#9290]
### PHP Version

8.4.1 (new released today)

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

Mysql latest

### What happened?

Hi, the php spark is not working for PHP 8.4.1

### Steps to Reproduce

Just launch php spark serve to 8.4.1

### Expected Output

Error 500
`CRITICAL - 2024-11-21 14:06:53 --> ErrorException: Declaration of CodeIgniter\I18n\TimeTrait::createFromTimestamp(int $timestamp, $timezone = null, ?string $locale = null) must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): static`

**Comment by ALTITUDE-DEV-FR** [comment]
Fix line 268 from file TimeTrait.php in codeigniter/framework/system/i18n/..
` public static function createFromTimestamp(int|float $timestamp, $timezone = null, ?string $locale = null): static`

**Comment by michalsn** [comment]
Support for PHP 8.4 is not planned for the 4.5 branch. Changes that fix this have already been made in the 4.6 branch.
