### ISSUE TITLE
Bug: Inaccurate path resolution in Boot

### ISSUE THREAD

**Issue by sk757a** [codeigniter4/CodeIgniter4#9309]
### PHP Version

8.3

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli

### What happened?

spark prints "" and nothing else.

### Steps to Reproduce

1. Set $writableDirectory in Paths to non-existent folder
2. Run spark

### Expected Output

At least more meaningful error message.

### Anything else?

When using the realpath function, if there is no actual path in the file system, false is returned. Which is then converted to an empty string when concatenated. The result path is pointing to the root.

**Comment by michalsn** [comment]
By default in the `production` environment errors are not displayed. Please set `CI_ENVIRONMENT = development` in the `.env` file to see the detailed error.

**Comment by sk757a** [comment]
I understand and know this, but what is the point of not showing error messages in the terminal? It turns out that the terminal user in the production environment must be either an attacker or a telepath. It is unclear and unfriendly in my opinion.

**Comment by sk757a** [comment]
> By default in the `production` environment errors are not displayed. Please set `CI_ENVIRONMENT = development` in the `.env` file to see the detailed error.

I should have written about the environment, of course. My mistake.

**Comment by michalsn** [comment]
I don't believe that OP wants to change any settings to see errors in the cli.

**Comment by michalsn** [comment]
Oh... I just spotted the full description of the label I assigned to this issue, so I am removing it now.

While this may be inconvenient, we rely on the settings from the given environment to display errors.

**Comment by sk757a** [comment]
The problem is that there is one setting, but two interfaces - web and cli. The point of hiding the output of confidential information, in my opinion, exists only in the case of web. Okay, I get it. Thanks.

**Comment by michalsn** [comment]
Yes, I understand your point. But in some cases, this can be dangerous. We can't be sure what users will do with `spark`. It can be run via `cron` and log the output of the command - which would potentially expose sensitive details.

**Comment by sk757a** [comment]
I didn't think about the cron and now completely agree.
But from another point of view, a program in any environment should not silently fail. The user should be able to diagnose and to fix or report the problem. Usually in such situations, log file analysis helps, but ironically not in this case, because log file cannot be written. There is no error message, no entry in log file and no solution.

**Comment by kenjis** [comment]
@sk757a You could send a PR to check the real path in
https://github.com/codeigniter4/CodeIgniter4/blob/539436f58d5e72ba8743340994df2f07d07cf6ed/system/Boot.php#L199

**Comment by kenjis** [comment]
@paulbalandan @michalsn This is a special case, because when `$writableDirectory` is wrong, CI4 cannot log errors.
So there is no clue to debug. 
Therefore I think if a PR that checks `WRITEPATH` comes, we should accept it.

**Comment by michalsn** [comment]
Okay, let's reopen it then. What a rollercoaster 😅
