### ISSUE TITLE
Bug: The dates is not working correctly.

### ISSUE THREAD

**Issue by mbnl** [codeigniter4/CodeIgniter4#9320]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

When the date stored in the database is "2024-12-30" or "2024-12-31", the code outputs the year 2025. When I adjust the date to "2025-12-30", it shows 2026.

### Steps to Reproduce

```php

// Config\App
public string $appTimezone = 'UTC';

// Database column value : 2024-12-30 07:19:15

// My Code
echo $row->sent_at;
// Out = 2024-12-30 07:19:15 (True)

// My Code;
echo $row->sent_at->setTimezone(new DateTimeZone('Europe/Istanbul'))->toLocalizedString('d MMMM YYYY HH:mm');
// Out = 30 Aralık 2025 10:19 (False)
// The output that should be = 30 Aralık 2024 10:19 (True)

// My Code
echo $row->sent_at->toLocalizedString('d MMMM YYYY HH:mm');
// Out = 30 Aralık 2025 07:19 (False)
// The output that should be = 30 Aralık 2024 07:19 (True)

// My Code
echo $row->sent_at->humanize();
// Out = in 3 weeks (True)



// -----------------------------------------

// Database column value : 2024-12-29 07:19:15
// My Code;
echo $row->sent_at->setTimezone(new DateTimeZone('Europe/Istanbul'))->toLocalizedString('d MMMM YYYY HH:mm');
// Out = 29 Aralık 2024 10:19 (True)




### Expected Output

When the date stored in the database is "2024-12-30" or "2024-12-31", the code outputs the year 2025. When I adjust the date to "2025-12-30", it shows 2026.

### Anything else?

_No response_

**Comment by ddevsr** [comment]
use `->format('Y-m-d')` instead, `toLocalizedString()` will give you result localize to timezone

**Comment by mbnl** [comment]
> use `->format('Y-m-d')` instead, `toLocalizedString()` will give you result localize to timezone

When I edited it the way you sent, yes I got the correct result, but I needed the `toLocalizedString()` method.

The year parameter I passed to the method was `Y`, when I changed this parameter to a small `y` my problem was solved.

Let it be information for those who will encounter the same problem in the future.
