### ISSUE TITLE
Failed asserting assertNotRedirect after assertRedirect

### ISSUE THREAD

**Issue by crazafimahatratra** [codeigniter4/CodeIgniter4#9329]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

When testing a  `assertNotRedirect` after a test case containing `assertRedirect`, we got failure at the `assertNotRedirect`

Everything works when we test `assertNotRedirect` BEFORE `assertRedirect`

### Write two tests. The first is assertRedirect and the second is assertNotRedirect 

```php
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\FeatureTestTrait;

final class RedirectTest extends CIUnitTestCase
{
    use FeatureTestTrait;
    
    public function testShouldRedirect()
    {
        $response = $this->get('/dashboard/1');

        $response->assertRedirect();
    }

    public function testShouldNotRedirect()
    {
        $response = $this->get('/dashboard/2');

        $response->assertNotRedirect();
    }
}
```

### Configure the route
```php
$routes->get('/dashboard/(:num)', 'Home::dashboard/$1');
```

### Write the controller
namespace App\Controllers;

```php
class Home extends BaseController
{
    public function index(): string
    {
        return view('welcome_message');
    }

    public function dashboard($id)
    {
        if($id === '1') {
            return $this->response->redirect('/auth');
        }
        return "Welcome $id";
    }
}
```

### Run the test
```bash
./vendor/bin/phpunit tests/RedirectTest.php
```

### Expected Output

All tests should pass
```
OK (2 tests, 2 assertions)
```

**Comment by michalsn** [comment]
You have to reset services between tests: https://codeigniter.com/user_guide/testing/overview.html#services-reset

```php
protected function setUp(): void
{
    parent::setUp();

    $this->resetServices();
}
```

**Comment by crazafimahatratra** [comment]
It works. Thanks @michalsn
