### ISSUE TITLE
Bug: Running Controllers via CLI show blank on powershell

### ISSUE THREAD

**Issue by anovsiradj** [codeigniter4/CodeIgniter4#9334]
### PHP Version

8.1

### CodeIgniter4 Version

v4.5.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cgi-fcgi

### Database

11.4.3-MariaDB 

### What happened?

Running Controllers via CLI only blank on powershell

### Steps to Reproduce

copy controller snippet from https://codeigniter.com/user_guide/cli/cli_controllers.html#create-a-controller
the run in from powershell

### Expected Output

it is just blank intead of showing "hello world"

<img width="430" alt="image" src="https://github.com/user-attachments/assets/f4d1163a-25e9-4b21-b725-d172a95e6a37" />

**Comment by paulbalandan** [comment]
Hi, did you add a cli route?

**Comment by anovsiradj** [comment]
> Hi, did you add a cli route?

i dont, im using auto routing (improved)

**Comment by anovsiradj** [comment]
apparently, the request was blocked by my custom filter.

adding this to my custom filter fix the ptoblem:

```php
class SessionPrivilegeFilter implements FilterInterface
{
	public function before(RequestInterface $request, $arguments = null)
	{
		# this fix my problem
		if ($request instanceof CLIRequest) {
			return;
		}
```
