### ISSUE TITLE
Division by zero - fresh install

### ISSUE THREAD

**Issue by Przem4S** [codeigniter4/CodeIgniter4#979]
![division_by_zero](https://user-images.githubusercontent.com/37654401/38244986-b6518df8-373c-11e8-81f0-7794d68a3619.PNG)

**Comment by Przem4S** [comment]
It's local, Windows 7 x64 with XAMPP.

**Comment by Przem4S** [comment]
No htaccess, first try with public path ex. http://localhost/public

**Comment by lonnieezell** [comment]
What PHP version?

**Comment by Przem4S** [comment]
@lonnieezell PHP 7.2.3.
@AkasakaRyu I know it, both variables are 0 (zero) in this error. I don't analize deeper, only try use. When try if this area with compare to zero then Controller/View not showing up.

**Comment by lonnieezell** [comment]
@Przem4S Looking at the code, it looks like you have an older version of the code. Can you try again with the latest in the `develop` branch and let me know if it works for you?

**Comment by lonnieezell** [comment]
@Przem4S Will you have a chance to re-visit this?

**Comment by Przem4S** [comment]
@lonnieezell 
Hello, I downloaded latest develop version, and still same error.
![zrzut ekranu z 2018-05-08 o 15 49 15-fullpage](https://user-images.githubusercontent.com/37654401/39761092-72087b5a-52d7-11e8-9efb-e023512855de.png)

**Comment by Przem4S** [comment]
And, PHPInfo screenshot - maybe help.
![zrzut ekranu z 2018-05-08 o 15 51 23-fullpage](https://user-images.githubusercontent.com/37654401/39761218-c8f4d7e2-52d7-11e8-8d5c-3d3be12288dc.png)

**Comment by jim-parry** [comment]
Nothing in months. Closing
